### ISSUE TITLE
求助: 为什么我里站一进去就只有半熊猫头，外站还能搜索，但是加载不出来

### ISSUE THREAD

**Issue by nrege** [xiaojieonly/Ehviewer_CN_SXJ#1000]
![Screenshot_20240119_012013](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/149860903/88a3b744-1d9e-4c97-a391-246bf6618a57)

**Comment by Chujian077** [comment]
你需要退出登录，并重新登录，来解决这个问题

**Comment by nrege** [comment]
> 你需要退出登录，并重新登录，来解决这个问题

试过好几次了，还卸载重下了，还是不行
