### ISSUE TITLE
更新手机系统后导入数据导入不全

### ISSUE THREAD

**Issue by zapgng** [xiaojieonly/Ehviewer_CN_SXJ#1001]
手机型号iqoo10，更新os4.0系统后，将白e的数据导入本软件的1.9.7.2版本后发现只能导入一半的数据，以前的3.0系统也试过导入数据，虽然有几率闪退导致没导入完全加导入的文件夹顺序是乱的，但大部分时间导入数据没问题并且文件顺序是正常的，刚刚系统更新4.0后导入数据5023本只导入了2071本

**Comment by xiaojieonly** [comment]
系统问题，我目前没啥好办法，我自己用的是红米
