### ISSUE TITLE
> 不一定，模糊查找会检索画廊标题，标签查询则只会匹配已打上对应标签的画廊，这是正常现象

### ISSUE THREAD

**Issue by Nightmare1996** [xiaojieonly/Ehviewer_CN_SXJ#1002]
> 不一定，模糊查找会检索画廊标题，标签查询则只会匹配已打上对应标签的画廊，这是正常现象

可是它们在eh上都有artist:aya3d的标签啊?
那如果我想找到全部已下载的他的作品，我关键字应该怎么打?

_Originally posted by @Nightmare1996 in https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/999#issuecomment-1898712486_

**Comment by xiaojieonly** [comment]
aya3d
