### ISSUE TITLE
1/20下午2时左右突然无法加载里站的内容了

### ISSUE THREAD

**Issue by tisapphire** [xiaojieonly/Ehviewer_CN_SXJ#1003]
测试了一下，表战依然可以访问，但是无法加载里站内容
使用网页依然可以访问里站，排除了是我个人的梯子或者账号的原因

**Comment by dcw2021** [comment]
+1

**Comment by akamortal** [comment]
拿cookie重新登陆一下就好了。

**Comment by dcw2021** [comment]
> 拿cookie重新登陆一下就好了。

还是不行诶😩

**Comment by tisapphire** [comment]
> 拿cookie重新登陆一下就好了。

问题已解决，多谢

**Comment by tisapphire** [comment]
igneous的值突然变成了mystery，重新输入就可以了
