### ISSUE TITLE
可不可以添加一个下载原档案的选项

### ISSUE THREAD

**Issue by Erlonealpha** [xiaojieonly/Ehviewer_CN_SXJ#1006]
压缩包那里只有通过h@h下载。我还把eh和exh设置里的档案下载改为自动选择并下载原档案，这样的话不会显示h@h的选项。

**Comment by chikao2024** [comment]
直接下载就行了，这样可以通过下载里面进行观看。

**Comment by xiaojieonly** [comment]
以后会加

**Comment by Erlonealpha** [comment]
> 直接下载就行了，这样可以通过下载里面进行观看。

铜星每周给的5gb免费大小不能不用啊，而且没法保证下载的全部都是原图

**Comment by xiaojieonly** [comment]
已有
