### ISSUE TITLE
配额迅速流失

### ISSUE THREAD

**Issue by YuRen97** [xiaojieonly/Ehviewer_CN_SXJ#1009]
开原图的情况下，“阅读”直接显示“Targe Image Url error”。
关原图的情况下，能“阅读”，但是一张图就占了50配额，100张就用完配额了，以前2000张图才会用尽的。
而且“下载”虽然有速度，但是图片会转完圈后又转圈，一张图也下载不下来，配额还会飞快的用完。
有什么头绪嘛老哥？

**Comment by YuRen97** [comment]
还有个问题，之前下载的图片，再“阅读”也都显示“读取失败”。
版本是最新的1.9.7.2

**Comment by soffrin123** [comment]
对，我也是这个情况，明明没看几张图，配额就用光了

**Comment by xiaojieonly** [comment]
E站政策更新导致，不建议原图阅读

**Comment by YuRen97** [comment]
> E站政策更新导致，不建议原图阅读

现在阅读正常了，下载还是不行，而且点了下载后的作品也无法正常阅读。
是网站为了批量下载改的政策么？
现在只能全看完然后再点下载，这样直接下载完成。
想下载下来再看只能用种子了，好慢。
