### ISSUE TITLE
表站和里站均无法显示内容

### ISSUE THREAD

**Issue by nekoof** [xiaojieonly/Ehviewer_CN_SXJ#1010]
查看cookie的igneous为null，重新用网页登陆后无法解决
![Uploading IMG_20240126_224926.jpg…]()
![Uploading Screenshot_2024-01-26-22-41-57-45_159c494ea8977f628e53d8d36755ba4c.jpg…]()
问题

**Comment by xiaojieonly** [comment]
没权限，网不好
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
