### ISSUE TITLE
退出登录后想重新登陆，直接跳过了登录界面进入了ehviewer

### ISSUE THREAD

**Issue by 2911894613** [xiaojieonly/Ehviewer_CN_SXJ#1013]
如题。最近很多图片加载不出来，有时可以有时不行。我看issue里提到过重新登陆的事，就想试一下看能不能解决这个问题。点退出登录后，再打开软件，直接进入主页了，跳过了密码登录网页登录和cookies登录那个页面。在软件里我是属于未登录状态，里站之类的看不了，标签也设置不了。依旧会显示“退出登录”的按钮，但不能登录，所以现在就卡这里了，我没登录，但不准我登
![Screenshot_2024-01-28-12-55-28-850_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/76984433/4d5cfe2e-87d7-4d76-adde-dc6de28a9bb7)
![Screenshot_2024-01-28-12-55-35-182_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/76984433/5d3c274a-2b83-421a-b224-fe14bee7cffc)

**Comment by 2911894613** [comment]
点最上面的退出登录会提示我重启应用以便再次登录，但我点了后，重启应用，就直接进了主页，可能直接进了游客模式。

**Comment by xiaojieonly** [comment]
尝试关闭手机中有跳过闪屏页或者相关功能的软件

**Comment by WhiteAlbumc** [comment]
yes，是李跳跳的问题，跳过广告的，换了就好了
