### ISSUE TITLE
加载不出，根本加载不出。裸连网络错误，挂梯子不是被ban就是熊猫头

### ISSUE THREAD

**Issue by xinfeng26** [xiaojieonly/Ehviewer_CN_SXJ#1018]
![Screenshot_20240129_220333_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/157942993/0d2314ab-55a1-430c-81ca-8cd2938ba12e)
![Screenshot_20240129_220322_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/157942993/719090c9-9c7c-4c2f-8cc2-e65f24a26476)

**Comment by YuRen97** [comment]
是不是站点选了ex但是账号没有里站权限

**Comment by xinfeng26** [comment]
> 是不是站点选了ex但是账号没有里站权限

不是，我在表站，虽然我账号真没里站权限

**Comment by xinfeng26** [comment]
![Screenshot_20240129_221913_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/157942993/8a53c9f9-5f22-4873-ba24-b8027706da34)

**Comment by FuyukiAsahi** [comment]
不是被ban就是sadpanda怎么看都很有可能是你梯子的问题吧

**Comment by xinfeng26** [comment]
> 不是被ban就是sadpanda怎么看都很有可能是你梯子的问题吧
可是裸连又网络错误，梯子都是sadpanda

**Comment by xiaojieonly** [comment]
挂了梯子就把高级里的网络设置关了试试
