### ISSUE TITLE
无法登陆和载图

### ISSUE THREAD

**Issue by 2930942153** [xiaojieonly/Ehviewer_CN_SXJ#102]
无法登陆，一登陆直接闪退，跳过登陆后无法载图，关了那个也dns也无法加载

**Comment by xiaojieonly** [comment]
哪个版本？什么登录方式？

**Comment by 2930942153** [comment]
1.7.10版本的，直接登陆会闪退，通过网页登陆进去后并没有登陆，还有那种游客id，切换到exhentai站点无法加载，跳过登陆e-hentai能正常使用

**Comment by 2930942153** [comment]
1.7.10版本的，直接登陆会闪退，通过网页登陆进去后并没有登陆，还有那种游客id，切换到exhentai站点无法加载，跳过登陆e-hentai能正常使用

**Comment by xiaojieonly** [comment]
安卓几？



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月26日(Mon) Evening6:36
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 无法登陆和载图 (#102)




 
1.7.10版本的，直接登陆会闪退，通过网页登陆进去后并没有登陆，还有那种游客id，切换到exhentai站点无法加载，跳过登陆e-hentai能正常使用

**Comment by 2930942153** [comment]
安卓8.1的，现在应该通过网页登陆进去了，但是exhentai站点无法加载图片
![Screenshot_2021-04-26-20-37-30-700_com xjs ehviewer](https://user-images.githubusercontent.com/83175245/116083514-489a2700-a662-11eb-886a-98ff3be67c01.png)

**Comment by 2930942153** [comment]
安卓8.1的，现在应该通过网页登陆进去了，但是exhentai站点无法加载图片

**Comment by xiaojieonly** [comment]
里站自求多福



---Original---
From: ***@***.***&gt;
Sent at: 2021年4月26日(Mon) Evening8:38
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 无法登陆和载图 (#102)




 
安卓8.1的，现在应该通过网页登陆进去了，但是exhentai站点无法加载图片

**Comment by 2930942153** [comment]
安卓8.1，现在已经能通过网页登陆进去了，但是exhentai站点
![Screenshot_2021-04-26-20-37-30-700_com xjs ehviewer](https://user-images.githubusercontent.com/83175245/116083846-bba39d80-a662-11eb-8727-a6987137f569.png)
无法加载出来

**Comment by 2930942153** [comment]
安卓8.1，能通过网页登陆了，exhentai站点无法加载内容

**Comment by xiaojieonly** [comment]
> 安卓8.1，能通过网页登陆了，exhentai站点无法加载内容

里站自求多福，要么是网不行，要么是IP没权限

**Comment by 2930942153** [comment]
大哥，那ip怎么授权

**Comment by xiaojieonly** [comment]
> 大哥，那ip怎么授权

等，别无他法。可以百度
