### ISSUE TITLE
功能建议，能否增加下载父画廊功能，有的画廊更新反而删了好多内容

### ISSUE THREAD

**Issue by decayici** [xiaojieonly/Ehviewer_CN_SXJ#1020]
能否增加下载父画廊功能，父画廊的下载键就是跳转新版本

**Comment by xiaojieonly** [comment]
E站不支持此功能

**Comment by decayici** [comment]
是e站更新了吗？我记得老版本是可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 上午9:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 功能建议，能否增加下载父画廊功能，有的画廊更新反而删了好多内容 (Issue #1020)




 
E站不支持此功能
