### ISSUE TITLE
bug 下载内容 未知原因导致标签位置混乱

### ISSUE THREAD

**Issue by qmssd** [xiaojieonly/Ehviewer_CN_SXJ#1021]
持续有不少版本了，下载到不同下载标签的内容，偶尔会排列到默认标签的最底端。
触发条件未知，但似乎搜索到已下载内容的情况下会触发。

**Comment by xiaojieonly** [comment]
已修，你的情况是脏数据导致的，可以把乱序画廊删了重新下载试试
