### ISSUE TITLE
关于更新漫画一直重新加载更新页的原因

### ISSUE THREAD

**Issue by TAT213** [xiaojieonly/Ehviewer_CN_SXJ#1022]
更新功能对新图片放在最前面的画廊更新几乎等于没用，但是一些漫画和同人志只有个别页修改时候和把更新页放在最后面的画廊更新都是特别有用的，但是更新漫画后每次关掉app重新打开看到更新页还是会重新加载，然后在漫画文件夹里面把.ehviewer_backup文件删除就不会再重新加载。

**Comment by xiaojieonly** [comment]
后续会改成直接下载为新画廊

**Comment by maonianccw0** [comment]
MIUI的12➕的红米Note 10 Pro，请问在那里删除？

**Comment by 343678573** [comment]
> 后续会改成直接下载为新画廊

😂我说怎么更新功能没了，要重新下载好麻烦

**Comment by xiaojieonly** [comment]
新版已修复
