### ISSUE TITLE
新的列表翻页后打开内容显示上一页的内容

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#1024]
> 已更新列表分页

感谢大佬的付出，也祝大佬新年快乐。新的列表翻页在设计上确实会非常好用，但可惜的是我点击列表第二页第一个本子的时候，实际上打开的是第一页第一个本子（已尝试清理内存缓存，和重新导入数据）。设置一页显示500条的时候到第500条都是点击后打开对应本子，但翻页后点击新的标题名字的本子出来的还是前一页对应排序顺序的内容

_Originally posted by @tongsang in https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/849#issuecomment-1925050018_

**Comment by xiaojieonly** [comment]
修好了，你再试试

**Comment by tongsang** [comment]
> 修好了，你再试试

可以了，感谢大佬。祝龙年新年快乐（无牙仔跳舞.gif)
