### ISSUE TITLE
请求解封绿E的TG群

### ISSUE THREAD

**Issue by RMWW** [xiaojieonly/Ehviewer_CN_SXJ#1025]
尊敬的Xiaojie：
       您好。
       之前我在您绿E的群内吐槽了下绿E无法全部下载原图的问题，还在群里发了通过绿E和彩E下载原图后格式和大小的对比图。我10年前就在E站上传画廊了，之前也一直用的归档下载，其实绿E的原图下载问题问题本身对我没有任何影响，哪怕汉化的图片质量问题我也可以自行汉化解决，但对于其他人而言却可能是会有影响的。我言语可能有些过激，但我这样做的目的只是为了广大网友找想，希望您能重视这个问题，也真心希望您能切实解决好绿E的原图下载问题。
![Screenshot_2024-02-03-14-56-31-385_org telegram messenger paper](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/158696669/a1bff2b0-26d7-4727-8b86-169b57e38a32)

      说实话，我确实没想到因为吐槽绿的原图下载问题，而被您踢出了群聊还封了我。
求您解封我让我恢复加群吧，无论您做得怎样，我保证从今往后都不再对您的绿E进行吐槽了。
      此致
敬礼！
                                                                                                    2024年2月3日

**Comment by xiaojieonly** [comment]
拉你了
不喜欢用可以不用
你可以提issue，提pr，但你骂我那就不能怪我不客气
