### ISSUE TITLE
希望能增加本地下载分类功能

### ISSUE THREAD

**Issue by klklkklkklkkl** [xiaojieonly/Ehviewer_CN_SXJ#103]
希望可以创建本地书架收藏夹对下载的本子进行自定义分类，方便整理和查找下载的本子，感谢大佬了。
捐赠了100元，希望大佬能考虑一下这个功能

**Comment by xiaojieonly** [comment]
有了啊，你在对应页面屏幕从右往左滑看看是不是你想要的功能
