### ISSUE TITLE
突然无法使用ex了

### ISSUE THREAD

**Issue by SoulofYang** [xiaojieonly/Ehviewer_CN_SXJ#1030]
之前都可以正常使用ex，突然就打不开ex的页面了。

**Comment by cyberpunkwine** [comment]
我之前遇到过类似的情况，原因似乎是我开v短时间内下载了许多画廊导致的，几周后在我试着登录了朋友的账号可以访问ex后登录回自己的账号便意外的解决了

**Comment by ahan777** [comment]
我也是，请问楼主解决了吗

**Comment by xiaojieonly** [comment]
用cookie重新登录试试
