### ISSUE TITLE
width of the buttons do not match. (broken text)

### ISSUE THREAD

**Issue by reindex-ot** [xiaojieonly/Ehviewer_CN_SXJ#1032]
![Screenshot_2024-02-05-23-51-29-918_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/32851879/4cbdcd95-a441-4245-9d88-2ef934e2ed2e)
Button text is broken.

Japanese text (broken) "の移行を開始"
Japanese text (nomal) "%の移行を開始"
Sample Japanese text "ブックマークの移行を開始"

**Comment by xiaojieonly** [comment]
%s is a string indicator and is not displayed when there is no corresponding alternative text in the text.

**Comment by xiaojieonly** [comment]
so it's not a issue
