### ISSUE TITLE
Material Design 3 & Dynamic Color

### ISSUE THREAD

**Issue by reindex-ot** [xiaojieonly/Ehviewer_CN_SXJ#1033]
There was a build that was Material Design 3, but development has been archived.
Please add an option to change this build to Material Design 3 as well.
https://github.com/Ehviewer-Overhauled/Ehviewer

**Comment by UjuiUjuMandan** [comment]
You may be interested to its official successor: https://github.com/FooIbar/EhViewer .

Also have a look at https://archive.today/2023.09.06-195435/https://github.com/Ehviewer-Overhauled/Ehviewer/discussions/1370 .
