### ISSUE TITLE
509

### ISSUE THREAD

**Issue by OPK1EISG** [xiaojieonly/Ehviewer_CN_SXJ#1034]
一直509看一个漫画就509😭

**Comment by xiaojieonly** [comment]
如果显示509，这是因为你当前的梯子节点被大量用户共同使用，导致浏览配额耗尽。你可以切换节点或更换梯子然后重新尝试。
什么？更换了节点还是提示509吗？这说明你的梯子不太给力哦。建议不停更换，直到能够顺利访问为止。
如果你对配额是什么感兴趣，点击下方按钮。
使用GP可以重置配额。
你可以通过捐赠E站增加配额，也可以通过购买hath perks来解锁配额
