### ISSUE TITLE
无法访问里站

### ISSUE THREAD

**Issue by kuhdrd** [xiaojieonly/Ehviewer_CN_SXJ#1035]
我用cookie登的，和网页端一至，igneous也是正常的，站点也改成ex了，app内搜索里站的本子标题时搜不到，但网页版的里站可以搜到

之前都没注意，在群里看到了个有意思的本子，在app里搜才发现搜不到，但网页端的里站可以

**Comment by xiaojieonly** [comment]
看看是不是设置->Eh里屏蔽画廊给屏蔽掉了
