### ISSUE TITLE
下载无速度，怎么换网都没有，浏览都正常

### ISSUE THREAD

**Issue by huanmengxuxiang** [xiaojieonly/Ehviewer_CN_SXJ#1037]
不管用流量还是WIFI，甚至换了好几个WIFI，下载时刚开始有速度，然后会在几秒内逐渐归零，浏览搜索，下种子都没问题，配额显示也是有的，设置应该也是对的，不知道为什么
![微信图片_20240207003305](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137517506/808ce83b-2e61-40db-9bbb-b2482d1ad119)

**Comment by xiaojieonly** [comment]
有时候是这样的，E站服务器抽风导致的，毕竟是海外的服务器
