### ISSUE TITLE
近期所有版本EX站首页均解析失败，疑似客户端未正确处理CF页面（内附Log）

### ISSUE THREAD

**Issue by Sherman-Liu** [xiaojieonly/Ehviewer_CN_SXJ#1039]
开启解析失败后保存页面内容如下，疑似客户端未正确处理CF页面：
Can't parse gallery list
<html>
<head><title>421 Misdirected Request</title></head>
<body>
<center><h1>421 Misdirected Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

**Comment by Sherman-Liu** [comment]
已试验出问题来源，客户端无法正确获取igneous值，通过客户端登录或网页登录获取到的值都是null，只有手动输入cookie值才能登录

**Comment by kuhdrd** [comment]
我用cookie登录也无妨访问ex站的本子，我已经确认我的igneous不是乱码

**Comment by FengTeLai** [comment]
最近这段时间我通过PC网页查询了cookie里的igneous，发现这内容一直在变更，我不明白这是为什么。

**Comment by xiaojieonly** [comment]
E站问题
