### ISSUE TITLE
提示target image url error

### ISSUE THREAD

**Issue by 2911894613** [xiaojieonly/Ehviewer_CN_SXJ#1043]
![Screenshot_2024-02-13-00-56-12-176_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/76984433/e979dbb6-2db5-4265-b804-ea81bf0a7124)

不是某一个画廊提示，是很多画廊都会这样提示。大部分出现在other:3d，misc这一类画廊中，大概十个画廊就会出现一个，所以我没贴画廊地址。
预览图能加载，但点进去的话，你点击的那一张图会成功加载出来，但剩下的就不行了，就提示上述问题

**Comment by xiaojieonly** [comment]
关闭原图显示试试

**Comment by XiangRiKui-YYYHE** [comment]
这是什么原因引起的，有办法修复吗

**Comment by KAFUNDH** [comment]
同问，我也是预览图能加载出来但点进去就显示target image url error

**Comment by cmtg994r** [comment]
同上 之前有一陣子沒碰上這個錯誤了，結果更新最新版以後這個錯誤又跑出來了
