### ISSUE TITLE
请问无法正常版本升级怎么办？

### ISSUE THREAD

**Issue by linsen7** [xiaojieonly/Ehviewer_CN_SXJ#1044]
型号：红米12pro
问题：每次下载好后安装包后，无法自动更新，无论是软件自行更新，还是浏览器下载，都必须得卸载软件后重新安装。
备注：已经给予软件下载权限了，其他软件也是正常更新。

是手机系统的问题么？

**Comment by xzl0326** [comment]
去文件管理里单独选择安装包安装

**Comment by linsen7** [comment]
> 去文件管理里单独选择安装包安装

已解决问题，感谢。
