### ISSUE TITLE
中午开始突然无法加载和下载(一开始还能加载首页封面，退出一次首页也出不来了)，平时直连和梯子都没问题

### ISSUE THREAD

**Issue by UDDENEC** [xiaojieonly/Ehviewer_CN_SXJ#1047]
直连就是哭泣外星人，开梯子就网络错误，甚至加载不出设置里的标签页和网站设置，重新安装了之前的版本也没用。。
![Screenshot_20240216_193601_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/40954927/75a7516e-ac3f-4081-96fd-8a21b8a5892b)
![Screenshot_20240216_193601_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/40954927/4a93a273-4046-47a1-a069-3c695f5ca038)

**Comment by UDDENEC** [comment]
![Screenshot_20240216_193219_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/40954927/7213809d-b11b-47af-bbed-608f5edcc56b)
![Screenshot_20240216_194928_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/40954927/410ae7bf-70e0-4c23-ad32-5448c6352a23)

**Comment by UDDENEC** [comment]
切回eh发现没问题了，可能和这位情况一样？不过我并没开梯子下载，绝大多数我都是直连的
![Screenshot_20240216_202645_com huawei browser](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/40954927/c080fdac-f3fb-4cf4-a8b3-62ce02c03de4)

**Comment by XiaoMiao458331** [comment]
我也是一样的情况。
包括直连和VPN。

另外我切了我的另一个账号，依然是白屏或者sad panda。
切回来也是。

诡异的是，网页挂代理可以进去。

**Comment by mlbzm** [comment]
我也是，中午突然就流泪机器头，不论是直连还是挂梯子都不行，用网页版重新登录了一下可以用了。两个小时前突然又流泪机器头，用网页版重新登录也不能行了，我还以为就我一个人有这个问题，看来是绿e的app出问题了

**Comment by FengTeLai** [comment]
安卓6和12能正常连接，但安卓9进EX时显示流泪界面，无法使用。

**Comment by UDDENEC** [comment]
我让朋友登我账号试了也进不去exh 我登别人账号也进不去

**Comment by mlbzm** [comment]
> 安卓6和12可以正常连接，但安卓9进EX时显示流泪界面，无法使用。

可能是app好的设备限制崩了，我滚到1972版本也用不了

**Comment by mlbzm** [comment]
> 我让朋友登我账号试了也进不去exh 我登别人账号也进不去
大概率是崩了，等修复吧

**Comment by FengTeLai** [comment]
我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。
另外，我在其它论坛看到有人说，最近几天查看到igneous信息经常变动，我不清楚这是不是真的，各位有时间可以去了解下。

**Comment by mlbzm** [comment]
> 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。

可以用了，之前突然变成mystery了，我重新用cookies登录了

**Comment by UDDENEC** [comment]
> > 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。
> 
> 可以用了，之前突然变成mystery了，我重新用cookies登录了

请问mystery要改成别的什么嘛

**Comment by mlbzm** [comment]
> > > 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。
> > 
> > 
> > 可以用了，之前突然变成mystery了，我重新用cookies登录了
> 
> 请问mystery要改成别的什么嘛

改成你原来账号的一串字母数字，每个账号的igenous都是独一无二的

**Comment by UDDENEC** [comment]
> > > > 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。
> > > 
> > > 
> > > 可以用了，之前突然变成mystery了，我重新用cookies登录了
> > 
> > 
> > 请问mystery要改成别的什么嘛
> 
> 改成你原来账号的一串字母数字，每个账号的igenous都是独一无二的

谢谢😘不过原来的我也看不到呀，是要到网页论坛里看么

**Comment by mlbzm** [comment]
> > > > > 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。
> > > > 
> > > > 
> > > > 可以用了，之前突然变成mystery了，我重新用cookies登录了
> > > 
> > > 
> > > 请问mystery要改成别的什么嘛
> > 
> > 
> > 改成你原来账号的一串字母数字，每个账号的igenous都是独一无二的
> 
> 谢谢😘不过原来的我也看不到呀，是要到网页论坛里看么

如果有账号密码能登录网页版应该能看到吧，我没在网页版看过

**Comment by UDDENEC** [comment]
> 我从PC端查了下cookies信息，是igneous改了，我尝试退出登陆后，用新的信息录入登陆账号，现在能正常使用了，各位尝试下。 另外，我在其它论坛看到有人说，最近几天查看到igneous信息经常变动，我不清楚这是不是真的，各位有时间可以去了解下。

老哥请问新的信息在网页哪里看呀

**Comment by FengTeLai** [comment]
> 老哥请问新的信息在网页哪里看呀
我是用电脑查信息的，在设置里的网站高级设置，查cookie，手机上我没办法，实在不行只好开梯子，用网页登陆。

**Comment by FengTeLai** [comment]
我是用电脑查信息的，在设置里的网站高级设置，查cookie，手机上我没办法，实在不行只好开梯子，用网页登陆。

**Comment by UDDENEC** [comment]
成功了 谢谢大家 在exh网页f12右边应用程序–储存–cookie下就有igneous

**Comment by FengTeLai** [comment]
这两天我通过PC网页查询了cookie里的igneous，发现这内容一直在变更。

**Comment by xiaojieonly** [comment]
用cookie重新登录
