### ISSUE TITLE
设置头像后会被系统清理缓存消除，但是背景则被保留

### ISSUE THREAD

**Issue by laplace618** [xiaojieonly/Ehviewer_CN_SXJ#1049]
版本号1.9.7.6
问题类似于issues#974

app拥有相册权限，
头像和背景文件路径均至于Android\data\com.xjs.ehviewer\files下
头像和背景选择为同一.jpg文件
但是在设置好头像和背景后，退出app，且清理后台数据
再次进入app时，只有背景的图片被保留，头像变为默认图片
且此时Android\data\com.xjs.ehviewer\files和Android\data\com.xjs.ehviewer\cache文件夹中的图片文件均正常存在

此外，当图片文件被设置在主目录的Ehviewer文件夹下时，上述问题仍然存在。

**Comment by laplace618** [comment]
更正：即使不清理后台数据，退出app后重启也会出现头像被清除但背景保留的情况

**Comment by laplace618** [comment]
> 版本号1.9.7.6 问题类似于issues#974
> 
> app拥有相册权限， 头像和背景文件路径均至于Android\data\com.xjs.ehviewer\files下 头像和背景选择为同一.jpg文件 但是在设置好头像和背景后，退出app，且清理后台数据 再次进入app时，只有背景的图片被保留，头像变为默认图片 且此时Android\data\com.xjs.ehviewer\files和Android\data\com.xjs.ehviewer\cache文件夹中的图片文件均正常存在
> 
> 此外，当图片文件被设置在主目录的Ehviewer文件夹下时，上述问题仍然存在。

更正：即使不清理后台数据，退出app后重启也会出现头像被清除但背景保留的情况

**Comment by xiaojieonly** [comment]
为什么要清理app数据呢？

**Comment by laplace618** [comment]
> 为什么要清理app数据呢？

是我表述不当，不是清理数据，只是清理手机后台
