### ISSUE TITLE
可以添加一个重新获取已下载画廊的浓缩图的功能吗

### ISSUE THREAD

**Issue by lin65254154** [xiaojieonly/Ehviewer_CN_SXJ#1050]
之前下载了很多本，后来换手机后，下载页面的浓缩图全部为空
![Screenshot_2024-02-18-12-36-58-25_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/90912133/9c0b8d2c-b17c-4d5e-9a18-6d32dc8a4608)

**Comment by xiaojieonly** [comment]
你需要手动点进去一次，然后最好不要把app的缓存当成垃圾清理掉
