### ISSUE TITLE
eh1.9.7.6版本使用上的一些小问题

### ISSUE THREAD

**Issue by suisuiyourstar** [xiaojieonly/Ehviewer_CN_SXJ#1051]
1，查看画廊通过取消下载再次下载调整画廊位置后，默认跳至顶部，有时阅读后退出也会跳至顶部；
2，新增的下载页面分页功能，不能固定分页数量；

**Comment by xiaojieonly** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月18日(星期天) 晚上11:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaojieonly/Ehviewer_CN_SXJ] eh1.9.7.6版本使用上的一些小问题 (Issue #1051)





 
1，查看画廊通过取消下载再次下载调整画廊位置后，默认跳至顶部，有时阅读后退出也会跳至顶部；
 2，新增的下载页面分页功能，不能固定分页数量；

**Comment by godlove71** [comment]
借串問下
下載頁面的分頁功能有地方可以關掉嗎?

**Comment by xiaojieonly** [comment]
> 借串問下 下載頁面的分頁功能有地方可以關掉嗎?

下一版上

**Comment by xiaojieonly** [comment]
> 1，查看画廊通过取消下载再次下载调整画廊位置后，默认跳至顶部，有时阅读后退出也会跳至顶部； 2，新增的下载页面分页功能，不能固定分页数量；

已修，下一版上
