### ISSUE TITLE
功能性问题 无法搜索

### ISSUE THREAD

**Issue by Pitohui-Dichrous** [xiaojieonly/Ehviewer_CN_SXJ#1054]
无论是搜索，首页还是点开已下载本的详情，都什么也不显示了，但是手机里另一个老版本（1.7.3）却能正常使用
![Screenshot_2024-02-21-04-31-26-086_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/160625893/387acbbe-e649-4ebb-b0b9-a3155eea849d)

**Comment by Pitohui-Dichrous** [comment]
更新老版本不知道为什么没有覆盖安装，所以就保留两个app了
![IMG_20240221_043313](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/160625893/1a792780-0084-4cb9-9132-55666ce77aeb)

**Comment by starlight033** [comment]
同样情况，表站正常，里站无显示

**Comment by hikichiye** [comment]
我也是同样的情况，在19号凌晨的时候突然就不能用了

**Comment by xiaojieonly** [comment]
sni和安全dns关了试试
