### ISSUE TITLE
自动登录

### ISSUE THREAD

**Issue by Return0073** [xiaojieonly/Ehviewer_CN_SXJ#1056]
不晓得为什么会自动登录如图，退出账号后重进直接进去选择站点，无法登录，在设置里每次进去都是退出账号，但并没账号实际登录![Screenshot_20240220_234245.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/154304798/9b91e367-bb88-4645-aed2-c911be64625c)

![Screenshot_20240220_234240.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/154304798/526d5852-1a52-488b-9635-a809c1770963)

**Comment by 99naga** [comment]
把李跳跳关了

**Comment by xiaojieonly** [comment]
这种问题我看的血压高
