### ISSUE TITLE
新功能请求 下载页选中长按能快捷搜索已下载同作者作品

### ISSUE THREAD

**Issue by catShit0ne** [xiaojieonly/Ehviewer_CN_SXJ#1058]
下的比较多了也比较乱，找同作者作品一般都是要点进详情页，复制作者名或者定义，然后回下载页再点搜索粘贴，比较繁琐，还有部分被炮了的作品也没法点击详情页复制，希望能加个按钮可以直接搜索，感谢🙏

**Comment by xiaojieonly** [comment]
建议下载时做好标签分类，下载列表右边有个侧边栏建议滑出来用用
