### ISSUE TITLE
图片分享到qq显示图片不存在

### ISSUE THREAD

**Issue by kangkang003** [xiaojieonly/Ehviewer_CN_SXJ#1060]
分享图片到qq的时候好像读取不了图片，显示图片不存在，但是temp文件夹里能看到下载的临时图片，开了那个允许媒体扫描好像也不行

![Screenshot_20240221_213535](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/72567736/33f938d8-26b9-4bb9-9871-bf6729fac977)
![Screenshot_20240221_213822](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/72567736/30cb4aa9-c3de-42ec-83df-4f3299dc8d6f)

**Comment by xiaojieonly** [comment]
应该是系统或者qq把app的分享功能屏蔽了，我红米手机上是正常的

**Comment by kangkang003** [comment]
我知道了，应该是系统不允许eh读取那个temp文件夹里的东西

**Comment by kangkang003** [comment]
![Screenshot_20240226_111610](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/72567736/60ab9da2-aa09-4a87-938a-e8f99a619f51)
修改了权限后解决了
