### ISSUE TITLE
无法裸连

### ISSUE THREAD

**Issue by fyl666kl** [xiaojieonly/Ehviewer_CN_SXJ#1061]
可以通过梯子网页登录进去，但是关掉梯子重新进去显示超时。通过ck登录的话是另一个用户名。不知道怎么回事

**Comment by fyl666kl** [comment]
把软件内存清了一下发现又能裸连了。。。。

**Comment by BOXQAQ** [comment]
我清内存，清除软件数据都进不去，麻了
我的标签和收藏呜呜呜

**Comment by bb1227** [comment]
我在国外裸连和开vpn都不行 全崩

**Comment by bzt345** [comment]
加一

**Comment by xiaojieonly** [comment]
挂了vpn就把APP内的网络配置关了，站点换成e-hentai再试试
