### ISSUE TITLE
去年提过更新导致乱页的问题，并且怀疑更新方式可能没有解决方法，因为这是上传者自己排序的，每次都可能是完全不同的排序

### ISSUE THREAD

**Issue by Axwcm** [xiaojieonly/Ehviewer_CN_SXJ#1066]
去年夏天的更新有问题之后，我就一直没用过这功能。前几天刚试了一下，还是不行。这倒不是很奇怪，但为什么
没有人反应同样的问题，i was puzzled

**Comment by xiaojieonly** [comment]
这个是脏数据导致的，你可以试着删除后重新下载乱序的画廊
