### ISSUE TITLE
请问下我这是无法登陆解析吗，求教怎么解决？

### ISSUE THREAD

**Issue by hdjsheifnjs** [xiaojieonly/Ehviewer_CN_SXJ#1067]
![IMG_20240228_102508.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/109351958/e079cca4-bcc0-4e1f-9693-71a0e11c0ea8)

**Comment by xiaojieonly** [comment]
设置-eh-浏览站点改成e-hentai

**Comment by xiaojieonly** [comment]
或者重新登录试试
