### ISSUE TITLE
新功能请求：导入阅读本地文件夹中的漫画

### ISSUE THREAD

**Issue by kirito5210** [xiaojieonly/Ehviewer_CN_SXJ#1068]
首先感谢大佬的默默付出。
虽然是老生常谈的功能请求了，但是感觉上次有人提已经过去很久了，还是旧事重提一下，思路大概类似本地阅读器导入zip文件或文件夹进行阅读这样？

**Comment by xiaojieonly** [comment]
嗯，下一版打算搞归档下载功能，这个暂时还没有计划弄
