### ISSUE TITLE
下载内容顺序全乱了，页数也对不上而且需要重新下载

### ISSUE THREAD

**Issue by bosen112** [xiaojieonly/Ehviewer_CN_SXJ#1069]
版本1.9.6.6。今天所有以前下载的内容打开需要重新下载，而且顺序不对，页码也和实际不一样。在手机目录下多出了一个Ehviewer文件夹，重新下载的图片在里面。更新到最新和清除缓存也没解决
![Screenshot_20240229_160151](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/161695194/9929d180-d6d0-4fce-8241-f64325155f98)
图片里这本有四百多页，是我前几天下载的，现在跑到最下面去了。求助大佬

**Comment by xiaojieonly** [comment]
更新到最新版1.9.7.6

**Comment by bosen112** [comment]
更新了，问题没解决
