### ISSUE TITLE
一打开应用就显示未知主机

### ISSUE THREAD

**Issue by EasyRain** [xiaojieonly/Ehviewer_CN_SXJ#107]
登陆也这样提示，用网页登陆进去之后还是这样显示
![S10512-21032335](https://user-images.githubusercontent.com/46843500/117979525-95217a00-b365-11eb-9724-b8974f488923.png)

**Comment by EasyRain** [comment]
裸连和代理都试过，host关闭也没用

**Comment by xiaojieonly** [comment]
sni开了没？

**Comment by EasyRain** [comment]
> sni开了没？

设置里面那些都开关过，没用

**Comment by xiaojieonly** [comment]
只开sni和host试试

**Comment by EasyRain** [comment]
> 只开sni和host试试

现在的话可以用了，估计是网络问题吧，用代理的话必须得关掉安全dns和sni，这两个开dns就会网络错误，开sni就会未知主机，以前的版本都不需要搞这些设置开代理一样上
