### ISSUE TITLE
导入结束时出错

### ISSUE THREAD

**Issue by Metaroka** [xiaojieonly/Ehviewer_CN_SXJ#1071]
[oneplus.zip](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/14469351/oneplus.zip)

[logcat-2024-03-03-04-10-21-280.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/14470806/logcat-2024-03-03-04-10-21-280.txt)

在尝试恢复旧数据时，应用程序会在到达终点前崩溃。
结果，53 000 条记录中只恢复了 7 000 条

**Comment by xiaojieonly** [comment]
我研究下

**Comment by Metaroka** [comment]
在安卓 10 上可以恢复，但需要 30 分钟的实时时间。

**Comment by xiaojieonly** [comment]
修好了，下一版更新，原始的导入流程没有考虑到会有上万画廊的情况，直接导致主线程奔溃了。。。

**Comment by Metaroka** [comment]
> 修好了，下一版更新，原始的导入流程没有考虑到会有上万画廊的情况，直接导致主线程奔溃了。。。

是跟踪下载内容的唯一方法，我不知道有其他替代方法。
