### ISSUE TITLE
更新1.9.7.7以后里站一直显示网络错误

### ISSUE THREAD

**Issue by sdfrrrr** [xiaojieonly/Ehviewer_CN_SXJ#1072]
更新了 1.9.7.7以后直连，梯子都进不去里站重新安装回 1.9.7.6版本可以进里站。但是另一部手机上的用另一个号登录的更新到1.9.7.7依然可以正常进里站，有跟我一样遇见这个问题的人吗？

**Comment by Laxwei** [comment]
我也是，更新后一直网络错误

**Comment by xiaojieonly** [comment]
用cookie重新登录
