### ISSUE TITLE
软件内检查更新问题

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#1075]
似乎软件检查更新请求的是原版的更新链接，~~导致软件内检查更新并不会生效~~(有人正常检查更新但我试了n次都是不提示更新，而且貌似软件的检查更新按钮并没有用)(软件每次启动都会向 https://www.ehviewer.com/update.json 发出请求，而这个网站已经被拿去做了跳转，现在是一个广告网站)
![Screenshot_2024-03-04-01-43-17-221_com.guoshi.httpcanary.premium.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/bb921d3e-918f-4919-8354-03546e7ae967)

![Screenshot_2024-03-04-01-43-20-627_com.guoshi.httpcanary.premium.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/c18bf168-3239-4398-b5f8-e72cc4cd7ca8)

**Comment by Fangliding** [comment]
软件内更新还是有效的 只是旧的检查更新模块没有移除 如果秉承能跑别乱动的原则 可以考虑把这个URL指向一个无效链接避免有被别有用心的人弄到这个域名下发一个恶意更新提醒这样的事发生

**Comment by xiaojieonly** [comment]
我看下

**Comment by xiaojieonly** [comment]
已移除，下一版更新

**Comment by Steve-337** [comment]
不弹更新的原因找到了，用 r-安装组件 安装的话就不会提示更新，换用其他安装器重新安装一次后即可正常检查更新……
