### ISSUE TITLE
安卓12+设备上使用域名打开APP的问题

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#1076]
从安卓12开始，应用需要用户手动验证链接后才能使用链接打开，而一些手机系统魔改了相关设置页导致无法轻松的验证链接(如MIUI)，我建议可以和pixez那样在设置中加上此选项，来方便的跳转到设置页(如下图)![Screenshot_2024-03-04-04-05-19-457_com.perol.pixez.png](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/f00b12ca-bfbd-418b-bc2f-98812ba6f19c)

**Comment by Steve-337** [comment]
MIUI／澎湃OS进入相关设置页的方法：
MIUI：设置中搜索 所有文件 ，点击后会跳转到原生应用管理页，找到ehviewer后选择默认打开-添加链接，勾选所有域名并点击添加即可。
澎湃OS：应用设置-右上角三个点--其他设置-默认应用设置-打开链接，后续操作与MIUI一致。
(如果设备已经解锁并刷入了框架，可以使用模块来禁用安卓的应用链接验证，即可不需要手动验证链接)

**Comment by jackieka** [comment]
> MIUI／澎湃OS进入相关设置页的方法： MIUI：设置中搜索 所有文件 ，点击后会跳转到原生应用管理页，找到ehviewer后选择默认打开-添加链接，勾选所有域名并点击添加即可。 澎湃OS：使用软件(如创建快捷方式)打开 com.android.settings.applications.ManageApplications 活动，后续操作与MIUI一致。 (如果设备已经解锁并刷入了框架，可以使用模块来禁用安卓的应用链接验证，即可不需要手动验证链接)

红魔9更新系统后遇到了同样的问题....不过完全找不到哪里可以验证链接

**Comment by Steve-337** [comment]
> > MIUI／澎湃OS进入相关设置页的方法： MIUI：设置中搜索 所有文件 ，点击后会跳转到原生应用管理页，找到ehviewer后选择默认打开-添加链接，勾选所有域名并点击添加即可。 澎湃OS：使用软件(如创建快捷方式)打开 com.android.settings.applications.ManageApplications 活动，后续操作与MIUI一致。 (如果设备已经解锁并刷入了框架，可以使用模块来禁用安卓的应用链接验证，即可不需要手动验证链接)
> 
> 红魔9更新系统后遇到了同样的问题....不过完全找不到哪里可以验证链接

理论上应该都可以通过打开原生设置页来验证

**Comment by jackieka** [comment]
折腾半天终于找到了，给同样手机的人解决方法
红魔9： 应用信息-默认打开-添加链接

![IMG_20240406_015057](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/82835549/2ff0971a-4094-4687-9700-9dca6797d681)
![IMG_20240406_015109](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/82835549/cda66171-36d3-4b6c-95cc-016886d9b1f3)

**Comment by Yuki-Master** [comment]
主要是我装的app都没有显示支持连接这些按钮，也不知道用什么模块

**Comment by Steve-337** [comment]
> 主要是我装的app都没有显示支持连接这些按钮，也不知道用什么模块
> 

不显示？具体啥样子？
模块的话可以去lsp仓库搜索 Disable app link verify / 禁用应用链接验证 ，还有一些综合性的模块也支持此功能(例如HyperCeiler/Cemiuiler)

**Comment by maonianccw0** [comment]
开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）

**Comment by Steve-337** [comment]
> 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）

不是哥们，彩版的你倒是去彩版的github下提issue啊😦

**Comment by maonianccw0** [comment]
> > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> 
> 不是哥们，彩版的你倒是去彩版的github下提issue啊😦

绿色的也一样，问了没人鸟我（倒）

**Comment by Steve-337** [comment]
> > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > 
> > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> 
> 绿色的也一样，问了没人鸟我（倒）

绿版没遇到你这问题，已经是最新版了？🤔

**Comment by maonianccw0** [comment]
> > > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > > 
> > > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> > 
> > 绿色的也一样，问了没人鸟我（倒）
> 
> 绿版没遇到你这问题，已经是最新版了？🤔

是的，发现没用后删掉重下两次，什么域名那些都没用，但白版好像可以

**Comment by maonianccw0** [comment]
> > > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > > 
> > > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> > 
> > 绿色的也一样，问了没人鸟我（倒）
> 
> 绿版没遇到你这问题，已经是最新版了？🤔

ex也进不去，不知道为什么，说是两周过审核就行了，我注册几年了也没用，哪个颜色版都进不去

**Comment by Steve-337** [comment]
> > > > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > > > 
> > > > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> > > 
> > > 绿色的也一样，问了没人鸟我（倒）
> > 
> > 绿版没遇到你这问题，已经是最新版了？🤔
> 
> ex也进不去，不知道为什么，说是两周过审核就行了，我注册几年了也没用，哪个颜色版都进不去

你还是加tg频道吧……有教程

**Comment by maonianccw0** [comment]
> > > > > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > > > > 
> > > > > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> > > > 
> > > > 绿色的也一样，问了没人鸟我（倒）
> > > 
> > > 绿版没遇到你这问题，已经是最新版了？🤔
> > 
> > ex也进不去，不知道为什么，说是两周过审核就行了，我注册几年了也没用，哪个颜色版都进不去
> 
> 你还是加tg频道吧……有教程

找了半天哪里有那个都没找到

**Comment by maonianccw0** [comment]
> > > > > > 开了代理，把前置域名和内置hosts关了，阅读的时候只能加载第一张图，后面怎么点都是重试怎么办？（彩色版的）
> > > > > 
> > > > > 不是哥们，彩版的你倒是去彩版的github下提issue啊😦
> > > > 
> > > > 绿色的也一样，问了没人鸟我（倒）
> > > 
> > > 绿版没遇到你这问题，已经是最新版了？🤔
> > 
> > ex也进不去，不知道为什么，说是两周过审核就行了，我注册几年了也没用，哪个颜色版都进不去
> 
> 你还是加tg频道吧……有教程

我看有说删.ehviewer backup文件的，没找到在哪删

**Comment by Steve-337** [comment]
> 我看有说删.ehviewer backup文件的，没找到在哪删

去tg里面找解决方法……Telegram群:https://t.me/+WyclP8pPlk-JfbwS

**Comment by maonianccw0** [comment]
> > 我看有说删.ehviewer backup文件的，没找到在哪删
> 
> 去tg里面找解决方法……Telegram群:https://t.me/+WyclP8pPlk-JfbwS

OK，谢了
