### ISSUE TITLE
缩略图大小问题

### ISSUE THREAD

**Issue by dissects** [xiaojieonly/Ehviewer_CN_SXJ#1078]
目前在我的手机上出现以下情况，竖屏显示下：
缩略图大小设置为大时，查看更多评论下面显示的画廊每行显示2张图片（对我来说图片大小正好），下滑到底部，点击查看更多预览，进入画廊预览页面后，变成每行显示3张图片，缩略图的图片大小缩小，能否让画廊预览界面每行也显示2张图片？

目前其他设置下的显示效果为：
当缩略图大小设置为中时，表层预览和里层预览都是每行显示3张图片。
当缩略图大小设置为小时，表层预览和里层预览都是每行显示5张图片。

**Comment by xiaojieonly** [comment]
我看下
