### ISSUE TITLE
可以登录和搜索画廊但无法下载的问题

### ISSUE THREAD

**Issue by tonyphobia980222** [xiaojieonly/Ehviewer_CN_SXJ#1080]
如题，网页ex登录都是正常的
ehviewer客户端可以正常登录，可以搜索，也能点进画廊的详情页。
但到了点开图片的时候就会转圈，最后加载不出来显示网络错误。
此时会显示图片配额迅速消耗，明明什么都没加载出来却很快把配额干爆了。
这个问题有一段时间了，回溯客户端版本或者刚刚更新客户端版本都没用。

请问该怎么办

**Comment by xiaojieonly** [comment]
挂了梯子是吧？换个节点或者关闭原图浏览

**Comment by tonyphobia980222** [comment]
> 挂了梯子是吧？换个节点或者关闭原图浏览

不是挂梯子，肉身在国内和国外都呆过，都是一样的问题。原图浏览我刚才试着到设置-下载-下载原图关掉了，但还是显示网络错误

**Comment by xiaojieonly** [comment]
？？？用cookie重新登录试试

**Comment by tonyphobia980222** [comment]
> ？？？用cookie重新登录试试

是要把客户端的cookie删掉重新输入吗？我也想过会不会是cookie的问题，但实在是搞不懂这个，原网站的cookie也不太会查。之前好不容易不知道怎么弄好了就没再敢动。

**Comment by tonyphobia980222** [comment]
> ？？？用cookie重新登录试试

大佬，我退出登录之后重新登录也是一样的反应啊。我怀疑是我方式错了。
客户端的cookie该怎么删呢
我看ID和ipb_pass_hash和网页是一样的
有一个igneous在网页上查不到，在EH—身份cookie里有显示，是这个的问题吗？
