### ISSUE TITLE
下载一半如果网络不好中断，会导致改本内容已下载部分消失

### ISSUE THREAD

**Issue by SauronSkywalker** [xiaojieonly/Ehviewer_CN_SXJ#1081]
下载一半如果网络不好中断，会导致改本内容已下载部分消失。
一个600多页的图包，下了三百多张然后网络波动下载失败中断了，继续下载就会从第一张重头下，之前下的也打不开了，白下半天了，老版本是可以继续下载的

**Comment by xiaojieonly** [comment]
是原图下载吗？

**Comment by SauronSkywalker** [comment]
![Uploading Screenshot_2024-03-07-10-42-42-494_com.xjs.ehviewer.jpg…]()
2400x，下载线程3
非原图下载

**Comment by xiaojieonly** [comment]
看不到图片

**Comment by xiaojieonly** [comment]
多半是没给存储权限

**Comment by SauronSkywalker** [comment]
![Screenshot_2024-03-07-10-42-42-494_com xjs ehview](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/59997490/996884f5-1fa5-48b1-a0ca-73ce0233d606)
