### ISSUE TITLE
关于下载图片的问题求助

### ISSUE THREAD

**Issue by eleee112** [xiaojieonly/Ehviewer_CN_SXJ#1084]
请问下载一个画廊到一半停止后重新点击下载就从零开始重新下载了，这该怎么做，需要弄什么设定吗，下了几个稍微多图片的图集缓存会超出图片配额，结果等图片配额回复的时候重新下载又再次从零开始，然后就是下载和清零的无限循环，求助......

**Comment by xiaojieonly** [comment]
配额用完了吧？或者没给app存储权限

**Comment by eleee112** [comment]
储存权限给了，下载一半配额用完之后等第二天继续下载就又从零开始下载了，遇到几次这种画廊了，很奇怪
