### ISSUE TITLE
按Home键离开APP后再进入不会触发图案保护

### ISSUE THREAD

**Issue by cheng9413** [xiaojieonly/Ehviewer_CN_SXJ#1085]
现时只能透过back键退出或杀掉APP再重啟才能触发图案保护，但用Home键离开APP无法触发图案保护。

EhViewer版本: 1.9.7.7
安卓版本: 14

**Comment by xiaojieonly** [comment]
系统设置看看，给app重新设置一下，这个功能是系统提供的

**Comment by xiaojieonly** [comment]
或者在设置-隐私-开启不允许屏幕抓取
