### ISSUE TITLE
有时候画廊有更新点击覆盖下载没反应

### ISSUE THREAD

**Issue by decayici** [xiaojieonly/Ehviewer_CN_SXJ#1088]
具体情况见视频

**Comment by decayici** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/158288656/468e2a03-ee27-4768-be22-9302f312304d

**Comment by xiaojieonly** [comment]
我研究下

**Comment by decayici** [comment]
会不会是因为这个画廊的更新是删减了一些内容，还调整了一下图片顺序，不像别的画廊是添加内容



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 下午2:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 有时候画廊有更新点击覆盖下载没反应 (Issue #1088)




 
我研究下

**Comment by xiaojieonly** [comment]
感觉是跳转有问题，我看下代码先

**Comment by junwense** [comment]
这个还有一个问题，更新最新版本后，覆盖下载后，在app打开图片会索引不到本地文件而是从网络加载，必须要删除画廊后重新下载，才能从本地加载图片，是不是内存数据库存在问题。

**Comment by xiaojieonly** [comment]
覆盖下载有bug，已经删除
