### ISSUE TITLE
努比亚会自动把下载内容当应用垃圾文件清除

### ISSUE THREAD

**Issue by bosen112** [xiaojieonly/Ehviewer_CN_SXJ#1089]
而且点了不会被扫描还是会显示在图库里
![Screenshot_20240310_184042](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/161695194/e57551eb-e1bb-48d0-b737-9d0e3ec6a680)

**Comment by xiaojieonly** [comment]
别清理呀，我又不是努比亚他爹,很多手机都这样
不被扫描是系统问题
