### ISSUE TITLE
这个问题怎么解决 

### ISSUE THREAD

**Issue by 1286194178** [xiaojieonly/Ehviewer_CN_SXJ#109]
![Screenshot_20210516_203439](https://user-images.githubusercontent.com/84274850/118397382-3e2de480-b686-11eb-8aca-fff18223fceb.jpg)
最新版 我是跳过登录进入的

**Comment by 1286194178** [comment]
是要做些什么吗

**Comment by xiaojieonly** [comment]
看更新日志，你估计没开host和sni

**Comment by 1286194178** [comment]
@xiaojieonly 抱歉我是个小白你的意思是这样吗
![Screenshot_20210516_205727](https://user-images.githubusercontent.com/84274850/118398033-666b1280-b689-11eb-998d-2133320ac193.jpg)

**Comment by xiaojieonly** [comment]
dns关了

**Comment by xiaojieonly** [comment]
然后重启软件

**Comment by 1286194178** [comment]
还是这样

**Comment by 1286194178** [comment]
@xiaojieonly 还有别的办法吗

**Comment by xiaojieonly** [comment]
你画廊站点用的哪个？

**Comment by 1286194178** [comment]
![Uploading Screenshot_20210516_210320.jpg…]()

**Comment by 1286194178** [comment]
e－hentai

**Comment by 1286194178** [comment]
e－hentai

**Comment by xiaojieonly** [comment]
安卓几？实在不行就只能自己挂梯子了

**Comment by 1286194178** [comment]
vpn我挂了

**Comment by 1286194178** [comment]
系统是iQOO最新的originos

**Comment by xiaojieonly** [comment]
挂vpn了就不需要开sni和host了

**Comment by 1286194178** [comment]
![Screenshot_20210516_210731](https://user-images.githubusercontent.com/84274850/118398350-c0200c80-b68a-11eb-9e61-b078126738b2.jpg)
是这样全部关掉吗

**Comment by xiaojieonly** [comment]
对这里的设置修改了之后最好重启下软件

**Comment by xiaojieonly** [comment]
如果挂了vpn也不行那就是网的问题了

**Comment by 1286194178** [comment]
也不行 那看来是网的问题了

**Comment by 1286194178** [comment]
麻烦你了

**Comment by xiaojieonly** [comment]
一般来讲开了sni和host之后就能裸连了，我目前就是裸连的，网络用的电信wifi，安卓10
