### ISSUE TITLE
你好，登录不上了

### ISSUE THREAD

**Issue by AL-U37** [xiaojieonly/Ehviewer_CN_SXJ#1093]
![Screenshot_20240316_004445_com xjs ehviewer_edit_317439270503644](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/108379494/f537a113-da21-480a-843a-ae1598291382)

**Comment by xiaojieonly** [comment]
尝试使用其他方法登录

**Comment by AL-U37** [comment]
> 尝试使用其他方法登录

网页登录人机验证卡着屏幕边角，cookie不会用😭
