### ISSUE TITLE
登录后显示sad panda，用网页cookie登陆不解决问题

### ISSUE THREAD

**Issue by seelesern** [xiaojieonly/Ehviewer_CN_SXJ#1094]
![QQ图片20240316120426](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/116353684/58477c05-ae16-4df6-b187-ae023f997fd1)
![QQ图片20240316120541](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/116353684/1c263b7b-9076-4061-b4ab-1ea0804443be)
igneous仍显示mystery

**Comment by xiaojieonly** [comment]
没权限
https://nicebowl.fun/11
