### ISSUE TITLE
关于更新画廊时覆盖下载的小问题

### ISSUE THREAD

**Issue by eleee112** [xiaojieonly/Ehviewer_CN_SXJ#1098]
之前提问过下载画廊的时候无限从零开始下载循环的问题，最近探索了一下发现我这里是更新时选择覆盖下载的原因造成的。
        在1.9.7.7版本的app里更新画廊时会弹出下载为新和覆盖下载的选项，选择覆盖下载之后一大堆画廊就会出现下载从零开始而且中途中断下载后继续下载还是从零开始下载的问题。
        目前自己瞎摸了一下解决办法就是更新时选择下载为新，这样就能从头下到尾了，如果不小心点到覆盖下载，就只能从下载列表移除项目，然后到下载路径文件夹删了以前下载的那个对应画廊的文件夹，最后再重新下载了，可惜了以前下载的几千张涩图不得不重下了。

**Comment by xiaojieonly** [comment]
覆盖下载的问题还在排查
