### ISSUE TITLE
这个为什么我自己看不到

### ISSUE THREAD

**Issue by Fullary** [xiaojieonly/Ehviewer_CN_SXJ#1099]
之前从别人的链接跳转进去的，然后自己也选这个标签看不到，在标签后加上后缀也看不到。有没有懂哥给看看。
![Screenshot_2024-03-21-00-11-17-689_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118233202/e4d1bf5d-4284-425d-9743-af4618d7f7a8)
![Screenshot_2024-03-21-00-11-31-796_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118233202/ff09f32a-ae8c-49a1-8eff-8aff8b388589)
![Screenshot_2024-03-21-00-11-53-023_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118233202/e2c72e9d-99ce-482e-be23-1842f71c0592)

**Comment by Qing-98** [comment]
跟梯子所在的地区有关系的，换个其他地方的节点试试

**Comment by Nachogao** [comment]
可能是“已删除”的，在高级搜索能看到这个选项，勾选它就可以看到隐藏的图库

**Comment by xiaojieonly** [comment]
正常，我甚至搜出来只有一条数据，很多时候画廊会被人举报下架，习惯就好
