### ISSUE TITLE
下载好的文件解码失败

### ISSUE THREAD

**Issue by Nana7miChiaKi** [xiaojieonly/Ehviewer_CN_SXJ#11]
就是下载到一半的时候图片配额用完了，就算换个IP把整本下载完，当时下载的那几页也会显示解码失败，请问这种问题能解决吗

**Comment by xiaojieonly** [comment]
> 就是下载到一半的时候图片配额用完了，就算换个IP把整本下载完，当时下载的那几页也会显示解码失败，请问这种问题能解决吗

你这问题我也是第一次看到，我之前从来都没用完过配额。。。。个人建议是少这么玩，但可能确实是个bug，我到时候留意下。如果是表站到还好，但如果是里站估计很快就会被封号了的。。。。

**Comment by Nana7miChiaKi** [comment]
> > 就是下载到一半的时候图片逐步用完了，就算换个IP把整本下载完，当时下载的那几页也会显示解码失败，请问这种问题能解决吗
> 
> 你的问题我也是第一次看到，我之前从来都没用完过过度。。。。。个人建议是少这么玩，但可能确实是个bug，我到时候留意下。如果是表站到还好，但如果是里站估计很快就会被封号了的。。。。

我还发现下载到一半的时候关掉APP也会有类似的问题，只不过不是解码失败，是那种图片只加载到一半的感觉
