### ISSUE TITLE
允许媒体扫描无法关闭

### ISSUE THREAD

**Issue by xunbe1** [xiaojieonly/Ehviewer_CN_SXJ#1101]
误触允许媒体扫描后无法关闭了，一点就会卡死然后在半分钟后闪退

**Comment by xunbe1** [comment]
6，刚说完又试了一次关上了，只不过我现在相册里全是色图，受不了，而且我用的这个绿E经常出现读取错误的情况，这个怎么解决

**Comment by xiaojieonly** [comment]
系统问题，读取错误多半是没权限
