### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by dfgfwscgt** [xiaojieonly/Ehviewer_CN_SXJ#1102]
各位，这个情况该怎么解决？
![Screenshot_20240326_000210_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/164910036/5c6a8526-ebc4-48af-a8a5-450074b08d63)

**Comment by xiaojieonly** [comment]
网不好

**Comment by 976047167** [comment]
#1105
