### ISSUE TITLE
想请教一下请求画廊图片有没有特殊技巧

### ISSUE THREAD

**Issue by kikouousya** [xiaojieonly/Ehviewer_CN_SXJ#1104]
大佬你好! 我自己也在写一个pc下载器, 但请求画廊图片时一定会遇到这些错误返回中的一个, (主页, 画廊界面, 缩略图等可以正常请求)
  请求被挂起: socket hang up; 
  链接被重置: ECONNRESET: Client network socket disconnected before secure TLS connection was established
  502内部错误
这是我请求时使用的header
```
  referer = "https://exhentai.org"
  host = "s.exhentai.org"
  Referer = "https://exhentai.org/"
  origin = "https://forums.e-hentai.org"
  Connection = "keep-alive"
  Accept-Language = "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6"
  sec-ch-ua = "" Not A;Brand";v="99", "Chromium";v="102""
  sec-ch-ua-mobile = "?0"
  sec-ch-ua-platform = ""Windows""
  Sec-Fetch-Mode = "no-cors"
  Sec-Fetch-Site = "same-site"
  Cookie = "ipb_member_id=XXXX; ipb_pass_hash=XXXX; igneous=axi0afycloioyn1ab44; sk=9kydpjjmc790k32omo2899xiynce"
  User-Agent = "Mozilla/6.8.0 (Windows NT 5.0) AppleWebKit/535.9 (KHTML, like Gecko) Chrome/21.5.2433.3 Safari/535.1"
  Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  Accept-Encoding = "gzip, deflate, br"
  Sec-Fetch-Dest = "document"
```
失败例
  https://wcffomk.svknseodhure.hath.network:1443/h/8f39a624c5c795c359d54d55c4539251154c8a1d-212132-1280-905-jpg/keystamp=1711497000-ef0b8b700c;fileindex=121986709;xres=1280/2737916_105857070_p0.jpg
  所属页面: https://e-hentai.org/s/dea484a498/2749562-1 (页面本身可以请求和解析)

**Comment by xiaojieonly** [comment]
是开源项目吗？代码仓库链接看下

**Comment by xiaojieonly** [comment]
用的什么语言？实在不行搭梯子得了

**Comment by kikouousya** [comment]
> 是开源项目吗？代码仓库链接看下
你好, 是的! 源码的请求位置在这里 https://gitee.com/kikouousya/wandering/blob/code-split/src/main/service/Fetchers/EhentaiFetcher.ts#L661

> 用的什么语言？实在不行搭梯子得了
语言是js(ts), 尝试过axios库和fetch库, 拿到一样的结果
有应用本机的系统代理, 因此可以访问主页和详情页, 但图片资源本身访问不成功
梯子是指?  搭建e站的资源镜像吗?

**Comment by xiaojieonly** [comment]
我感觉你是最终图片链接有问题，实在不行建议在chrome上直接把E站的js代码拿过来用，ts引用js应该挺方便的
