### ISSUE TITLE
历史记录问题和一些遗留问题

### ISSUE THREAD

**Issue by LUrenjia114** [xiaojieonly/Ehviewer_CN_SXJ#1111]
如题，从1.9.7.7升级到1.9.7.8后我在上一个版本的看本的历史记录全部丢失，新的历史记录也无法记录
另外之前就反馈过的“使用公开cookie登录里站后每次打开软件都需要退出重新登录”的问题，出现这个问题时igneous会变成mystery，另外主页会显示一次503，再次刷新页面后就会没有任何错误报告，上次向开发者反馈后开发者表示锁定igneous或者更换网络可以解决问题，但是迄今为止问题依然没有解决，我甚至尝试过更换本人所在地址也无效

**Comment by xiaojieonly** [comment]
E站政策，胳膊拗不过大腿，个人建议以后少于公共cookie
