### ISSUE TITLE
关于软件闪退小问题的询问

### ISSUE THREAD

**Issue by SunLC258** [xiaojieonly/Ehviewer_CN_SXJ#1112]
各位大佬好，小白遇到了如下的问题：
手机更新系统之后，遇到了软件闪退的问题。系统是鸿蒙4.0.0.165，软件是最新更新的1.9.7.8。不过在重启手机或者长时间不用手机之后就会有一小段时间不会闪退，在issue区没有找到类似的问题，想要求助一下懂行的大佬。（顺便一提，这个闪退分软件，哔咔好好的而jm就闪退，黑洞加速器能用海鸥加速器就不能用，从来没遇见过这种情况）

**Comment by xiaojieonly** [comment]
多半是梯子冲突了

**Comment by xiaojieonly** [comment]
梯子关了试试

**Comment by SunLC258** [comment]
> 梯子关了试试

已经把所有梯子都关闭了（悲）可是闪退的情况依然没有改变，每次只有在长时间不用手机之后才能短暂打开一会儿，试过清除缓存也没用。
