### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by cjlJyd** [xiaojieonly/Ehviewer_CN_SXJ#1114]
如题，我期中一台手机是OPPO型号是PHP110，下载1.9.7.6后标签和搜索开启标签是汉语但删除后从另一台手机上传输过来的1.9.7.8后又无法显示搜索协助（无论用英语还是汉语都无法显示标签和作者名字）和汉语标签，删除后再在网站上下一遍还是这个情况，这个是我的手机问题还是bug？
![Screenshot_2024-04-02-01-05-45-30_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/165697887/803fb117-f999-4232-b24d-d46c13500df2)
![Screenshot_2024-04-02-01-05-30-85_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/165697887/49700687-18f0-4c4c-84a3-fb17dcdbaabc)

**Comment by cjlJyd** [comment]
![Uploading Screenshot_2024-04-02-01-31-59-11_159c494ea8977f628e53d8d36755ba4c.jpg…]()

**Comment by xiaojieonly** [comment]
应该是在下载标签库，等一会或者挂梯子等一会应该就好了

**Comment by cjlJyd** [comment]
> 是在下载标签库，等一会或者挂梯子等一会应该就可以了

在APP里的标签翻译始终属于打开状态，但是点一下APP就会重新加载，等了很久了始终无法显示汉语
![Uploading Screenshot_2024-04-03-09-02-48-61_159c494ea8977f628e53d8d36755ba4c.jpg…]()
