### ISSUE TITLE
一个下载的问题

### ISSUE THREAD

**Issue by yellowteaegg** [xiaojieonly/Ehviewer_CN_SXJ#1115]
我有一个明确已经下载好的本子，并且在手机目录内也能找到相应的资源，为何过了一段时间（一周或者是两周）不在APP内看，之后再看就会显示重新加载，并且消耗流量

**Comment by xiaojieonly** [comment]
可能被系统当垃圾删了

**Comment by yellowteaegg** [comment]
可我去文件目录里看，图片还在
