### ISSUE TITLE
1.9.7.8闪退

### ISSUE THREAD

**Issue by skyblue35** [xiaojieonly/Ehviewer_CN_SXJ#1118]
你好，我的系统：安卓7，vivo xplay6
昨天从1.9.7.7更新到1.9.7.8后打开APP读取画廊时候必定闪退，不知道为什么……期间没开过梯子，没动过别的设置，后来试过卸载重装，重装后能进登陆界面，登陆后选择E或者EX后继续闪退，读取图标那个转圈会卡一下然后闪退……请问一下这是出了什么问题？退回1.9.7.7后没任何问题……

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
更新试试

**Comment by skyblue35** [comment]
感谢，更新到1.9.10后一切正常
