### ISSUE TITLE
中文tag无法加载，点显示标签翻译按钮直接回退主页刷新

### ISSUE THREAD

**Issue by liaofuyu1** [xiaojieonly/Ehviewer_CN_SXJ#1119]
版本1.9.7.8，中文tag无法加载，点显示标签翻译按钮直接回退主页刷新[
![Screenshot_20240403-112217_Pixel 启动器](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/98232791/4c6c725c-a1e3-4c41-bc3b-2beab9a4834c)
](url)
可以安装1.9.7.7后，覆盖更新解决中文tag加载，但是按显示标签翻译按钮还是直接回退主页刷新

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
修好了
