### ISSUE TITLE
中文显示标签翻译未生效

### ISSUE THREAD

**Issue by liaofuyu1** [xiaojieonly/Ehviewer_CN_SXJ#1126]
版本1.9.7.10，安装登陆后，显示标签翻译按钮默认打开，但是没有生效，重复关开后也不生效，均等待了5分钟的下载时间，之前的版本下载标签翻译时间一般小于1分钟，且在安装后按钮默认打开并生效

**Comment by cjlJyd** [comment]
还有是依旧无法使用中文搜索

**Comment by rfgftgfgg** [comment]
我也是这样

**Comment by xiaojieonly** [comment]
挂梯子等等看，标签汉化的github库改了

**Comment by liaofuyu1** [comment]
> 挂梯子等等看，标签汉化的github库改了

挂了的，用Warp（中国节点）和微软云（香港节点）都试了，难道服务器屏蔽这两种节点吗？

**Comment by xiaojieonly** [comment]
可能没代理github，我自己测试时是没有问题的

**Comment by rfgftgfgg** [comment]
> 节点

我是通过下载1.9.77然后再升级到最新版本解决的

**Comment by liaofuyu1** [comment]
> 可能没代理github，我自己测试时是没有问题的

你能debug检查下吗？单独安装1.9.7.10确实没生效，是不是忘了绑定按钮，请求网址写错了，或者忘了set？

**Comment by Steve-337** [comment]
> 可能没代理github，我自己测试时是没有问题的

确实是不行，而且新版下载链接下载的是明文json和sha1，旧版是base64处理的无后缀文件和加密的sha1，看上去好像ehv并没有支持明文json格式的翻译文件和sha1

**Comment by xiaojieonly** [comment]
是有问题，我在改了

**Comment by xiaojieonly** [comment]
修好了，你再试试

**Comment by liaofuyu1** [comment]
> 修好了，你再试试

已修复
