### ISSUE TITLE
大佬，如果不知道自己里站的cookies怎么办

### ISSUE THREAD

**Issue by wycstc353** [xiaojieonly/Ehviewer_CN_SXJ#1129]
大佬，如果不知道自己里站的cookies怎么办，我有两个号，其中一个以前能进里站，我也不记得是哪个号了，没记cookies，现在自己浏览器翻墙都只能进表站了，用大佬的软件，手机模拟器进只能用cookies登录，可我没记里站的cookies，现在还有办法进里站吗？

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11
