### ISSUE TITLE
eh不知道什么时候套了cf防火墙

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [xiaojieonly/Ehviewer_CN_SXJ#113]
现在已经解析失效了，不能过检测

**Comment by xiaojieonly** [comment]
什么手机？

**Comment by xiaojieonly** [comment]
> 现在已经解析失效了，不能过检测

提示的啥？有相关截图吗？

**Comment by changzhouzi** [comment]
我这里挂了梯子也是解析失败，几个app都是这样

**Comment by Auth3r** [comment]
同，我用老版本1.7.3也是解析失败，换了几个版本几个方法还是这样

**Comment by xiaojieonly** [comment]
你得给我我要的信息呀，不然我怎么帮你们解决？凭空造车我不会啊~

> 同，我用老版本1.7.3也是解析失败，换了几个版本几个方法还是这样



> 现在已经解析失效了，不能过检测

**Comment by Mr-Ao-Dragon** [comment]
就点进所有需要在线加载的内容都显示解析错误，打开eh设置启动内置网页浏览器会先过cf防火墙，再到正常页面

**Comment by Mr-Ao-Dragon** [comment]
好像是看IP分别上的
