### ISSUE TITLE
希望作者大佬增添一个功能

### ISSUE THREAD

**Issue by longfei796** [xiaojieonly/Ehviewer_CN_SXJ#1130]
有些本子被删除了，但是可以通过其他地方下载压缩包后，选择用eh打开压缩包观看，能否在下载页面增添一个外部导入压缩包的页面方便查看

**Comment by Steve-337** [comment]
推荐用 perfect viewer，支持读取压缩包

**Comment by caidingding233** [comment]
你还行 我想要外部分享为PDF 但是自从我提建议叫开发者改一下UI被冲后 我就不敢再发任何issue了

**Comment by xiaojieonly** [comment]
> 你还行 我想要外部分享为PDF 但是自从我提建议叫开发者改一下UI被冲后 我就不敢再发任何issue了

还好我后面把issue冻结了，不然后面冲的人越来越

**Comment by xiaojieonly** [comment]
> 有些本子被删除了，但是可以通过其他地方下载压缩包后，选择用eh打开压缩包观看，能否在下载页面增添一个外部导入压缩包的页面方便查看

没法保证压缩包内的文件格式和命名规则，所以实现起来很难

**Comment by caidingding233** [comment]
> > 你还行 我想要外部分享为PDF 但是自从我提建议叫开发者改一下UI被冲后 我就不敢再发任何issue了
> 
> 还好我后面把issue冻结了，不然后面冲的人越来越

现在还可以看到吗 我可能需要报案 有证据吗
