### ISSUE TITLE
新版本虽修复中文标签与搜索无法显示类别bug但如果直接在搜索框里搜索Chinese类书籍无法搜索到中文

### ISSUE THREAD

**Issue by cjlJyd** [xiaojieonly/Ehviewer_CN_SXJ#1132]
如下
![IMG_20240409_052254](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/165697887/18f4185a-5e61-4240-bb40-d1c6b4738146)
![IMG_20240409_052326](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/165697887/d8222364-549f-4c02-96de-0a195267045d)

**Comment by Steve-337** [comment]
用 a:"mana$" Chinese 搜索

**Comment by Steve-337** [comment]
搜索结果和APP的tag翻译没关联，你应该检查是不是屏蔽了Chinese（例如在网站设置的 Excluded Languages 勾选了 Chinese）。还有建议用 a:"mana$" l:chinese 搜索
![Screenshot_2024-04-09-11-02-47-662_com.xjs.ehviewer.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/850062ef-03c0-4a37-ba31-55f5dc09db8a)

**Comment by cjlJyd** [comment]
好吧，还真是
