### ISSUE TITLE
历史记录消失

### ISSUE THREAD

**Issue by huanlingphantom** [xiaojieonly/Ehviewer_CN_SXJ#1133]
版本1.9.7.10
历史记录一栏空白，之前的历史记录被清空，点新的也没反应。

**Comment by jiafeimao2024** [comment]
> 版本1.9.7.10 历史记录一栏空白，之前的历史记录被清空，点新的也没反应。
设置→EH→历史记录数量，随便选个数量，之后点新的就有了记录了，之前的我的手机上也看不到

**Comment by huanlingphantom** [comment]
问题解决。选择之后历史记录数量下方会显示数字或无限制，之前没有。
![Screenshot_20240416_112240_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48439520/b7e50a7a-09b1-4a19-9714-8c3a9d5c06ef)
