### ISSUE TITLE
获取pToken错误

### ISSUE THREAD

**Issue by TANGHUAQING** [xiaojieonly/Ehviewer_CN_SXJ#1134]
![Screenshot_20240410_195945](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/156038936/a2696564-012d-4dc3-acc2-f2db3d9ee1d3)
已经试过多种方法了，包括回退版本，网页重登，cookie重登，一直报错

**Comment by TANGHUAQING** [comment]
将网页的设置改成默认之后就可以正常观看了

通过控制变量找到原因了，是多页查看器

**Comment by xiaojieonly** [comment]
1

**Comment by zgr6666** [comment]
我该如何下载
