### ISSUE TITLE
啥都没问题，就是打开无法显示画廊

### ISSUE THREAD

**Issue by y5565** [xiaojieonly/Ehviewer_CN_SXJ#1135]
![Screenshot_2024-04-12-00-45-17-302_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/166742356/7083fa25-1a35-42b4-bad0-541e0fb291f7)
打开是这样，怎么回事？求助

**Comment by 1013905619** [comment]
我也是

**Comment by BUCKBAO888** [comment]
我也是

**Comment by EchoInMirror9** [comment]
我也遇到了这个问题，重新登陆了账号就好了

**Comment by xiaojieonly** [comment]
楼上正解，或者挂个梯子
