### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by BUCKBAO888** [xiaojieonly/Ehviewer_CN_SXJ#1138]
不知怎么的就这样了
![Screenshot_20240413_091832_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/166884341/c1cc0736-8c29-481d-aa7a-bf91f36a6547)

**Comment by 1013905619** [comment]
我也是前几天还好好的。不知道怎么就不行了

**Comment by 1limisjdy** [comment]
我也是

**Comment by c29tZSBvbmU** [comment]
一样

**Comment by Pony-CW** [comment]
我要吐了，开发者不说我得说一下
高级设置不说，网络环境不说，系统版本不说，甚至连个日志都没有
虽然 xiaojie 他加了数据收集组件，但能不能不要啥都不给的无效提问，盲猜头都要大了去

**Comment by BUCKBAO888** [comment]
> 我要吐了，开发者不说我得说一下 高级设置不说，网络环境不说，系统版本不说，甚至连个日志都没有 虽然 xiaojie 他加了数据收集组件，但能不能不要啥都不给的无效提问，盲猜头都要大了去

最新版本，都是按照提问的那样说设置的，什么都没有动过 突然就变成那个样子了，日志我这里显示无法导出

**Comment by 1013905619** [comment]
> > 我要吐了，开发者不说我得说一下 高级设置不说，网络环境不说，系统版本不说，甚至连个日志都没有 虽然 xiaojie 他加了数据收集组件，但能不能不要啥都不给的无效提问，盲猜头都要大了去
> 
> 最新版本，都是按照提问的那样说设置的，什么都没有动过 突然就变成那个样子了，日志我这里显示无法导出

一样

**Comment by c29tZSBvbmU** [comment]
日记
[Uploading logcat-2024-04-14-10-38-19-935.txt…]()

**Comment by c29tZSBvbmU** [comment]
Android14 补上日记文件，顺道发现软件设置进"我的标签"是能进去的，还有表站用浏览器直接访问是一片白？
[logcat-2024-04-14-12-52-01-426.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/14969535/logcat-2024-04-14-12-52-01-426.txt)

**Comment by 1013905619** [comment]
问题解决了吗？

**Comment by BUCKBAO888** [comment]
> 问题解决了吗？

没，表站能用ex还是不行

**Comment by 1013905619** [comment]
> > 问题解决了吗？
> 
> 没，表站能用ex还是不行

可能要等更新才行了

**Comment by Steve-337** [comment]
进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……

**Comment by 1013905619** [comment]
> 进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……

还是不行。。

**Comment by Steve-337** [comment]
> > 进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……
> 
> 还是不行。。

那就是你网不行……

**Comment by 1013905619** [comment]
> > > 进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……
> > 
> > 还是不行。。
> 
> 那就是你网不行……

网页可以用，就是APP不行

**Comment by Steve-337** [comment]
> > > > 进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……
> > > 
> > > 还是不行。。
> > 
> > 那就是你网不行……
> 
> 网页可以用，就是APP不行

那你就把浏览器的里站cookie导出来放APP里面

**Comment by 1013905619** [comment]
> > > > > 进不去里站请检查cookie，并且目前里站cookie会失效，用个好点的网重新登陆……
> > > > 
> > > > 还是不行。。
> > > 
> > > 那就是你网不行……
> > 
> > 网页可以用，就是APP不行
> 
> 那你就把浏览器的里站cookie导出来放APP里面

不行。。我放弃了😞

**Comment by Steve-337** [comment]
> 不行。。我放弃了😞

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/96

**Comment by 1013905619** [comment]
> > 不行。。我放弃了😞
> 
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/96

可以看到了。谢谢你

**Comment by QAQNOQWQ** [comment]
> > > 问题解决了吗？
> > 
> > 
> > 没，表站能用ex还是不行
> 
> 可能要等更新才行了

我成功了，确定问题为cookie更新导致的无法加载ex站。退出登录后手机连梯子使用网页登录，然后就可以正常进入ex站了，记得在设置里保存下新的身份cookie

**Comment by Steve-337** [comment]
> 我成功了，确定问题为cookie更新导致的无法加载ex站。退出登录后手机连梯子使用网页登录，然后就可以正常进入ex站了，记得在设置里保存下新的身份cookie

保存没用，现在cookie是会失效的，到时间了还是要重新登陆(除非你存了有以前的9位旧cookie)

**Comment by QAQNOQWQ** [comment]
> 保存没用，现在cookie是会失效的，到时间了还是要重新登陆(除非你存了有以前的9位旧cookie)

还真是。我又重新登录了一下，用的是以前的九位旧cookie，也可以正常访问。
总之现在卡在ex站刷新不了的，用cookie重新登录下就能访问了= =

**Comment by BUCKBAO888** [comment]
我也已经解决了，重新登录下确实可以了
