### ISSUE TITLE
关于新版本更新以后下载速度的问题

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#1139]
上一个版本更新以后，新版本的下载速度就---------越---------来-----------越--------------慢-----------------了。
看issues列表貌似不是我一个人的问题，但是我保留意见。
（诶，我是不是在几个版本之前发过类似的问题？）
xiao老师，发生甚麽是了。

**Comment by BreakFaith01** [comment]
哦，还是有点不一样的，我是下载速度极慢，他们是干脆打不开。（我打得开是因为EX，不知道他们的情况是什么样子的，所以保留意见）

**Comment by xiaojieonly** [comment]
是这样的，欧洲在打仗，服务器在摩尔多瓦，摩尔多瓦在乌克兰边上
