### ISSUE TITLE
无法进入，该怎么解决？

### ISSUE THREAD

**Issue by poiuy848** [xiaojieonly/Ehviewer_CN_SXJ#114]
使用的系统为iqoo的origin OS，挂梯子也不行，已登陆，站点exhentai，但是在另一个手机连接同一个wifi，同样设置可以进入，但那手机是安卓系统。看之前也有人是origin OS系统，也是这个问题。具体该怎么解决呢？

**Comment by poiuy848** [comment]
![Uploading Screenshot_20210604_190242.jpg…]()

**Comment by poiuy848** [comment]
![Screenshot_20210604_190242](https://user-images.githubusercontent.com/65771023/120793088-faf8c000-c525-11eb-8e85-95e1cf1975be.jpg)

**Comment by poiuy848** [comment]
![Uploading Screenshot_20210604_190305.jpg…]()

**Comment by xiaojieonly** [comment]
1.检查高级中的网络设置是否正确
2.检查cookie是否正确



---Original---
From: ***@***.***&gt;
Sent at: 2021年6月4日(Fri) Evening7:09
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [xiaojieonly/Ehviewer_CN_SXJ] 无法进入，该怎么解决？ (#114)




 
使用的系统为iqoo的origin OS，挂梯子也不行，已登陆，站点exhentai，但是在另一个手机连接同一个wifi，同样设置可以进入，但那手机是安卓系统。看之前也有人是origin OS系统，也是这个问题。具体该怎么解决呢？

**Comment by poiuy848** [comment]
![Uploading Screenshot_20210604_200846.jpg…]()

**Comment by poiuy848** [comment]
![Screenshot_20210604_200846](https://user-images.githubusercontent.com/65771023/120798981-a9543380-c52d-11eb-93d4-db0901fbccb5.jpg)

**Comment by poiuy848** [comment]
![Screenshot_20210604_200846](https://user-images.githubusercontent.com/65771023/120798981-a9543380-c52d-11eb-93d4-db0901fbccb5.jpg)

**Comment by poiuy848** [comment]
cookie显示可用于登陆，网络设置如图，跟那个能用的手机一样

**Comment by poiuy848** [comment]
会不会是跟originos系统的问题？之前的提问不也有人这样吗

**Comment by xiaojieonly** [comment]
url伪装关了，然后重启软件



---Original---
From: ***@***.***&gt;
Sent at: 2021年6月4日(Fri) Evening8:13
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 无法进入，该怎么解决？ (#114)




 
会不会是跟originos系统的问题？之前的提问不也有人这样吗

**Comment by poiuy848** [comment]
![Uploading Screenshot_20210604_231032.jpg…]()

**Comment by poiuy848** [comment]
还是不行
![Uploading Screenshot_20210604_231032.jpg…]()

**Comment by xiaojieonly** [comment]
> 还是不行
只开host 和sni

**Comment by poiuy848** [comment]
也不行= =

**Comment by xiaojieonly** [comment]
> 也不行= =

。。。。

**Comment by xiaojieonly** [comment]
挂梯子吧

**Comment by poiuy848** [comment]
木有用呀，全都不行。估计这系统不能上了

**Comment by Genokillerxx** [comment]
> 木有用呀，全都不行。估计这系统不能上了

老哥解决了吗，我也是iqoo,一样能直连表站，里站就不行

**Comment by xiaojieonly** [comment]
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

**Comment by poiuy848** [comment]
iQOO这样不行，只能进入表站，里站进不去，各种设置都没用。
