### ISSUE TITLE
希望大佬能增加两个实用却简单的小功能

### ISSUE THREAD

**Issue by chiggaluo** [xiaojieonly/Ehviewer_CN_SXJ#1140]
首先感谢大佬一直用爱发电维护软件🥰
如题，第一点是想在已下载的目录中，像已收藏一样，有一个不分类的囊括所有下载画廊的页面，方便查找
第二点是，增加一个随机播放的功能，大部分绅士还是下载或收藏了很多画廊的，有时候想看却不知从何下手。如果有一个功能，可以随机播放已收藏或已下载其中的画廊，软件就更完美了

**Comment by Fince10086** [comment]
同样希望能有这两个功能🙏

**Comment by xiaojieonly** [comment]
第一个感觉实现不了，第二个下一版更新
