### ISSUE TITLE
网络连接失败

### ISSUE THREAD

**Issue by aabf11** [xiaojieonly/Ehviewer_CN_SXJ#1144]
![Screenshot_20240418_075235](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/167223086/a662477b-755a-442a-8ddb-14295cf48c99)

**Comment by zijuu** [comment]
o

**Comment by montnyuh** [comment]
把hosts.txt关掉就行了

**Comment by maplevvj** [comment]
> 把hosts.txt关掉就行了

两个全关吗？

**Comment by xiaojieonly** [comment]
感谢热心网友
