### ISSUE TITLE
看不了阅读历史

### ISSUE THREAD

**Issue by sdo9004** [xiaojieonly/Ehviewer_CN_SXJ#1146]
版本1.9.7.11点历史只能看到这里是阅读历史，看不了我看过的本子

**Comment by Steve-337** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1128#issuecomment-2041276034

**Comment by fanggchang** [comment]
蹲

**Comment by xiaojieonly** [comment]
二楼正解
