### ISSUE TITLE
1.9.7.11无法正常打开界面

### ISSUE THREAD

**Issue by Redbasebank** [xiaojieonly/Ehviewer_CN_SXJ#1147]
![Screenshot_20240419_195120](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/167532377/9ab3df9f-ac42-4f36-89ba-c29360817b7e)
求解这是因为什么呀

**Comment by chencsk** [comment]
我也是，不知道

**Comment by MOKL0718** [comment]
我也是，就一个眼泪标志，无语了

**Comment by y5565** [comment]
我也是，我之前就有这个问题好几个版本了了，都能签到但就是感觉进不去😭
![Screenshot_2024-04-20-08-56-31-752_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/166742356/1a3e05d4-c664-48d7-976b-99b1ef058741)

**Comment by OokinaSekai** [comment]
检查账号cookie中的igneous是否变成了mystery，是的话需要重新登录网页获取igneous
参考：https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/623

**Comment by xiaojieonly** [comment]
挂了梯子的话把域名前置关了，或者切表站重新登录
