### ISSUE TITLE
沒有下載原圖

### ISSUE THREAD

**Issue by s4028600** [xiaojieonly/Ehviewer_CN_SXJ#1148]
https://exhentai.org/s/6a06033155/1838968-52
我的這個圖片毀損
所以重新下載
下載原圖
這很危險！勾選這個選項會導致圖片流量配額與GP快速耗用
這個我有選
但是下載下來的檔案只有7百k
原圖是5m

**Comment by xiaojieonly** [comment]
建议使用归档下载或者种子下载，原图下载有E站风控
