### ISSUE TITLE
建议修改一下UI 让他更加像中国内地的社交平台

### ISSUE THREAD

**Issue by caidingding233** [xiaojieonly/Ehviewer_CN_SXJ#1149]
# 我为啥一直说要修改UI
首先 我们已经知道了我们Ehviewer给了大家一个上网看本子的基本的需求 基本上作者大哥@xiaojieonly 在软件内部集成hosts文件 这些我们都看得清清楚楚 当然 我们既然可以上Github 我们也是会翻Q的 也是具备了一定的能力 去自定义自己喜欢看的内容 以及部分的个性化 在这里我们不说什么了 我赞叹作者大哥的能力 （说实话 我不会写代码）
其次 我认为当时的App针对EH新人来讲 操作复杂 部分选项晦涩难懂 我们希望我们作者大哥写出来的软件不是针对一小部分群体 而是针对于一大部分没有入局的人 他们或许是想要宣泄自己 或者是想要学习人体构造 在这之前 作者已经做的很好了 我这一次就是想和作者提一点关于UI方面的意见
# 部分意见（作者大大可听 也可不听 为开源社区作贡献是一个令人尊敬的行为 若作者大佬如果是想休息一下 那就休息一下吧）
- 首先 添加底部导航栏 分为五个按钮 四个页面：首页 热门 上传 消息 我的 首页上面就是类似于xhs 关注的博主（画师）（关注也可以改成订阅）（简称关注）推荐 和分区（可以访问e站包括里站（账号可以上去的话）和外站的所有作品 按照e站原生的8大分区分类：（Doujinshi, Manga, Artist CG, Game CG, Western, Non-H, Image Set, Cosplay, Asian P那啥啥n, MISC） 右上角是搜索 可以在E站（表站和里站（账号可以上去的话））按照用户的关键词搜索 所有作品（本子）按照两栏 大封面加标题 瀑布流（位于封面下方 类似中国的部分社交软件）同时 标签（tag）不分男女的行为 直接在标题后面加井号标签 用户点到标签 可以打开一个页面 包括使用了这个标签的所有作品 同样两栏大封面 大标题 瀑布流 上传板块的按钮是一个绿色的加号 可以允许呢上传多个照片和视频 上传后起标题 附带tag不超过十个 如果有人通过网页版改了扩充标签 可以尝试显示不超过10个井号标签
- 其次 用户可以在评论区盖楼 讨论关于他们喜欢的内容 如某位动漫人物 或者某一对CP 还有 热门按照原来的算法 但是UI风格按照刚刚说过的风格 消息页面上面有 赞过我的 at我的 评论我的 以及系统消息（专门来推送E站的每日激励语句）同时允许私聊 最后一个我的页面的上面 用一个圆角矩形框住 专门写着用户的头像 个性签名 多少关注 多少粉丝 配额多少 以及配额制度作为e站的特色的介绍 包括他可以下载什么东西等等等等 底下则是一个小程序栏（如本子输出PDF 局域网传输啊 种子解析下载啊等等等等）
如果作者大哥想做一个小程序（需要导入 如果用到显示网页的情况 我也不是推崇要塞一个CEF的人 大佬可以考虑用手机自带webview）小程序栏过后 则是收藏（从E站云端同步数据）下载记录 设置（希望不要复杂选项 比如hosts设置这种 可以把他们藏进一个叫Advance Settings的东西）
- 还有 登陆界面 以熊猫做成背景图（最好留白）当用户同意许可条款（Apache条款）后 则是一个大标题：很高兴 遇见你 底下则是E站用户名啊 邮箱啊 而cookie登陆作为一个小icon 在底下 其他方式登陆的右边 先输入用户名后转到第二屏 上面写着 Hi（用户名）请输入密码 输入密码后 登陆是一个圆角矩形的 绿色的按钮 点一下登陆 回到了主页 上面的分区还在 底下的导航栏也在
- 最后是比较细节的部分 用户可以关注博主 博主可以互关 也可以拉黑 搜索有热点推荐或者历史记录（六条）搜索后 可以看到用户（博主） 作品 标签等等的板块 我把在搜索前的选项调到搜索后再仔细筛选 更加符合习惯 配额的话需要在我的页面的配额旁边做一个指引 介绍了配额是啥 可以干什么（我玩了一年E站 到现在都不知道这是啥） 本子打开后的详情页 他的左上角是返回键 上面是作者还有关注按钮 右上角是分享 可以分享给站内私信 或者是WhatsApp Facebook imesaage Telegram等软件 而中间一大块就是本子的图像页面 左右滑动换页 可以放大 放大后只有本子图像 缩小后回到详情页 底下则是标题和用井号标识的标签 最多可以显示10个 往下滑就是评论区 再往下滑就是两栏信息流
# 最后
说实话 我这一些话里面语法有一堆的矛盾 如果有什么你认为不行的 或者不切实际的（包含一段）你可以告诉我 我想作者大大也是不会考虑做关于UI方面的优化 因为他上班就已经很累了 我也感谢大家为所有的开源项目做的贡献 因为有你们 我们往小了说是看黄的 往大了说 是文化的交流和碰撞 如果作者看到了 可以考虑一下为新人做一个大家都喜欢 没有任何遗憾 方便快捷的软件 三两句说的不太清 我考虑一下可以把我的设计的UI和UX发到这里 如果作者不采用 我也不生气

**Comment by UjuiUjuMandan** [comment]
再加上开屏摇一摇广告、手机号登录、实名认证、删帖控评，就更像中国内地了。

**Comment by milozya** [comment]
我有时候真的很怀疑头像和智力的相关性

**Comment by caidingding233** [comment]
> 再加上开屏摇一摇广告、手机号登录、实名认证、删帖控评，就更像中国内地了。

你们都不注重ux吗

**Comment by caidingding233** [comment]
> 我有时候真的很怀疑头像和智力的相关性

哦 我懂了 你的意思说我的智商很好 谢谢
滚！

**Comment by Hayakee** [comment]
我很怀疑你是否知道**ehviewer和e站不是一个东西**，ehviewer绝大部分功能都是基于e站本身存在的功能实现的，e站没有的功能硬要写一个对于开发者来说是非常巨大的困难（几百万本子数据的操作，没官方提供的API写个🔨）。
**你说这么多之前能不能先调查一下两者之间的关系？**
开发者不是站长，站长本人对这种第三方也是睁一只眼闭一只眼，**不要提一些无谓的功能增加开发者的负担**，真需要你可以自己写PR或者打钱给开发者单独给你写一个（问题是你愿意出多少钱？）

**Comment by zutzo** [comment]
很好的提议，建议你直接提 Pr 
亲自操刀手写一份符合中国内地社交平台的UI

**Comment by dgtea7021** [comment]
玩原神玩的
[恭喜上新闻](https://t.me/c/1501598444/838529)

**Comment by Hukeqing** [comment]
慕名而来，前来吃瓜😊👉

**Comment by SlimeNull** [comment]
慕名而来, 吃瓜

**Comment by yigekuyou** [comment]
不是，兄弟，UI罢了

**Comment by Steve-337** [comment]
这样的UI大改我个人认为适合自行fork一份来做成一个新的分支，因为并非所有人都能接受这种UI，当然也肯定会有人喜欢这种UI，祝你能开辟一个全新UI的新分支版e站APP

**Comment by JetpackPrime** [comment]
elieli是吧🤣

**Comment by WindSakura** [comment]
你這個issue有些睿智，但你的頭像又彌補了這一切，一切都合情合理上了XDD

**Comment by Yooofox** [comment]
哪天项目只读了你在其中都有一份不可磨灭的贡献

**Comment by Miku-programm** [comment]
什么玩原神的小屁孩都来这指点江山了

**Comment by emptysuns** [comment]
这些UI改进建议都很符合钟国特色
不过我认为ehviewer就是一个e站阅读工具，没必要修改太多过于个性的功能。
尽管如此，本仓库也是开源的，你大可以fork并修改出新得分支，并取名为：eilieili

**Comment by Anankke** [comment]
玩儿原神玩儿的🤣

**Comment by BLxcwg666** [comment]
玩原神玩的🤣👉🤡

**Comment by y547153** [comment]
傻逼😅

**Comment by Just-Prog** [comment]
这么喜欢中国特色UI建议别玩Eh了好好呆在哔咔漫画，那儿适合你这种玩原神脑子玩降级了的傻逼

**Comment by Just-Prog** [comment]
导原神本子导傻了？

**Comment by Asubeats** [comment]
慕名而来，您就是产品经理？

**Comment by Fangliding** [comment]
有序观光

**Comment by cxplay** [comment]
我是癫佬, 这是我的看片神器, 充电五分钟看片两小时, 不要告诉别人哦~

**Comment by fanggchang** [comment]
国内的ui本来就一坨屎了，别拉上eh吧

**Comment by manaking86** [comment]
慕名而来

**Comment by yukaone** [comment]
癔言丁真，鉴定为脑子坏掉了

**Comment by PerfBleu** [comment]
逆天

**Comment by xiaojieonly** [comment]
写的确实很有建设性，但是就目前的情况来说，我没有那么多的精力对ui进行大规模的修改，我目前是利用空闲时间进行开发，大部分时间还是要上班工作的，而目前的捐助情况大概是一个月几百块的样子。
按照你的来，至少也得全职搞，我会饿死的

**Comment by 661266** [comment]
笑死 被噴爛

**Comment by honjow** [comment]
这就是产品经理的快乐吗

**Comment by 666gml** [comment]
赤石吃上瘾了 国内app还不够臃肿吗

**Comment by Joeyjoy64** [comment]
啥乱🤣

**Comment by terence121** [comment]
对不起我笑了

**Comment by caidingding233** [comment]
> 玩儿原神玩儿的🤣

我是小孩的妈妈。你这样去说我小孩我是很伤心的，因为每个人都有玩游戏的权利，你们不爱，请不要伤害到一个喜欢玩的人的心。请还网络一片清明。

**Comment by honjow** [comment]
请还网络一片清明？贼喊抓贼
消灭傻逼是每一个网民应有的义务

**Comment by caidingding233** [comment]
> 请还网络一片清明？贼喊抓贼
> 消灭傻逼是每一个网民应有的义务

# 孩子都他妈这样了 你们还是这种b态度![IMG_20240512_235745.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/72660933/83e1f5a0-2eec-4bb9-84eb-54680f1aa1e8)

（小朋友说）~~妈的把老子的钱乱撒 好 老子就是傻bi 老子都tm这样了 活着tm15岁 抑郁症没有~~
# 一个人 他妈妈的 一个人 你知道从出生 到现在 **有他妈的一个人 一个人 把我当成人吗**
你们吃着**人血馒头** 做着二鬼子做的事 歧视自己人 这里他妈的是
# GITHUB
~~你妈蛋 见到中国人就喷 见到哪怕一滴点的〇 就他妈的怼着骂 还他妈消灭sb 我看你就是傻逼~~
（妈妈说）先为我孩子的嘴巴道歉 他是有点情绪激动 他刚刚甚至想跳楼 你们作为 大人 是否有 **关照过特殊的人**更何况 他是未成年 还是抑郁症 我不是说他的观点好 他后来哭着说 我ehviewer 我只需要毛玻璃 还有一个更好的UI 他还想着 他自己做一个镜像服务器 他要做一个自己的eh 他每天除了玩原神 就是和我逗 他见到我只能维持这样 你们看到他的GitHub仓库 只有一个giantpig 这个工程 基本上 就是 他生命中第一个hello world 您想过吗 您在黑夜里看到一个蜡烛 可是您觉得他亮的太离谱了 于是 您把他灭了 他心里怎么想 他本来被校园霸凌 回到家 看到自己喜欢的事情 或者 他想探索的事情 见到这样 你让一个母亲居心何在？！我儿子说的你们这群日本鬼子渗透中国 原来他妈的从弱势群体开始 你们他妈要点b脸吗？！你们看到中国的五星红旗 你们有脸吗
（你们是日本鬼子 没事了）
你们自己看着办

**Comment by WindSakura** [comment]
> > 请还网络一片清明？贼喊抓贼
> > 消灭傻逼是每一个网民应有的义务
> 
> # 孩子都他妈这样了 你们还是这种b态度![IMG_20240512_235745.jpg](https://private-user-images.githubusercontent.com/72660933/329866970-83e1f5a0-2eec-4bb9-84eb-54680f1aa1e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzU1ODgsIm5iZiI6MTcxNTUzNTI4OCwicGF0aCI6Ii83MjY2MDkzMy8zMjk4NjY5NzAtODNlMWY1YTAtMmVlYy00YmI5LTg0ZWItNTQ2ODBmMWFhMWU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE3MzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMjU1NmJlNzhkZWI4Y2E2OTMzMjY4MzRmMWM3YWU0MTEwNGM4MjU5YTI3NmZkOTlmNDE0MTUyOGIzNzNlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YwMw6VXbmlhi1c9157NclmLC4Yqmm2yHy75qiCYYGjg)
> （小朋友说）~妈的把老子的钱乱撒 好 老子就是傻bi 老子都tm这样了 活着tm15岁 抑郁症没有~
> 
> # 一个人 他妈妈的 一个人 你知道从出生 到现在 **有他妈的一个人 一个人 把我当成人吗**
> 你们吃着**人血馒头** 做着二鬼子做的事 歧视自己人 这里他妈的是
> 
> # GITHUB
> ~你妈蛋 见到中国人就喷 见到哪怕一滴点的〇 就他妈的怼着骂 还他妈消灭sb 我看你就是傻逼~ （妈妈说）先为我孩子的嘴巴道歉 他是有点情绪激动 他刚刚甚至想跳楼 你们作为 大人 是否有 **关照过特殊的人**更何况 他是未成年 还是抑郁症 我不是说他的观点好 他后来哭着说 我ehviewer 我只需要毛玻璃 还有一个更好的UI 他还想着 他自己做一个镜像服务器 他要做一个自己的eh 他每天除了玩原神 就是和我逗 他见到我只能维持这样 你们看到他的GitHub仓库 只有一个giantpig 这个工程 基本上 就是 他生命中第一个hello world 您想过吗 您在黑夜里看到一个蜡烛 可是您觉得他亮的太离谱了 于是 您把他灭了 他心里怎么想 他本来被校园霸凌 回到家 看到自己喜欢的事情 或者 他想探索的事情 见到这样 你让一个母亲居心何在？！我儿子说的你们这群日本鬼子渗透中国 原来他妈的从弱势群体开始 你们他妈要点b脸吗？！你们看到中国的五星红旗 你们有脸吗 （你们是日本鬼子 没事了） 你们自己看着办
亲爱的吧友，在这个特殊的时刻，我想表达我对你母亲的去世的深深哀悼。我知道这很难，但请记住，你并不孤单。我们都在这里为你提供支持和慰问。你母亲是一个有价值的人，她的一生充满了爱和奉献。她在家庭中的角色和你对她的尊重让我感到非常感动。我相信她的智慧、勇气和爱心将继续影响你的生活，并传递给下一代。每个人都会面对失去亲人的痛苦，这是一种无法避免的伤痛。当你觉得孤独或失落的时候，请不要犹豫寻求帮助和支持。同样，也请你知道我以及众多的网友会在这一湿难时期陪伴着你度过。生老病死是不可避免的自然规律，但我们永远不会忘记那些在我们生活中留下深刻印记的人。最后，愿逝者安息，愿你能在这段难过的时光里得到慰藉和平静。

**Comment by WindSakura** [comment]
> > 请还网络一片清明？贼喊抓贼
> > 消灭傻逼是每一个网民应有的义务
> 
> # 孩子都他妈这样了 你们还是这种b态度![IMG_20240512_235745.jpg](https://private-user-images.githubusercontent.com/72660933/329866970-83e1f5a0-2eec-4bb9-84eb-54680f1aa1e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzU1ODgsIm5iZiI6MTcxNTUzNTI4OCwicGF0aCI6Ii83MjY2MDkzMy8zMjk4NjY5NzAtODNlMWY1YTAtMmVlYy00YmI5LTg0ZWItNTQ2ODBmMWFhMWU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE3MzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMjU1NmJlNzhkZWI4Y2E2OTMzMjY4MzRmMWM3YWU0MTEwNGM4MjU5YTI3NmZkOTlmNDE0MTUyOGIzNzNlMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YwMw6VXbmlhi1c9157NclmLC4Yqmm2yHy75qiCYYGjg)
> （小朋友说）~妈的把老子的钱乱撒 好 老子就是傻bi 老子都tm这样了 活着tm15岁 抑郁症没有~
> 
> # 一个人 他妈妈的 一个人 你知道从出生 到现在 **有他妈的一个人 一个人 把我当成人吗**
> 你们吃着**人血馒头** 做着二鬼子做的事 歧视自己人 这里他妈的是
> 
> # GITHUB
> ~你妈蛋 见到中国人就喷 见到哪怕一滴点的〇 就他妈的怼着骂 还他妈消灭sb 我看你就是傻逼~ （妈妈说）先为我孩子的嘴巴道歉 他是有点情绪激动 他刚刚甚至想跳楼 你们作为 大人 是否有 **关照过特殊的人**更何况 他是未成年 还是抑郁症 我不是说他的观点好 他后来哭着说 我ehviewer 我只需要毛玻璃 还有一个更好的UI 他还想着 他自己做一个镜像服务器 他要做一个自己的eh 他每天除了玩原神 就是和我逗 他见到我只能维持这样 你们看到他的GitHub仓库 只有一个giantpig 这个工程 基本上 就是 他生命中第一个hello world 您想过吗 您在黑夜里看到一个蜡烛 可是您觉得他亮的太离谱了 于是 您把他灭了 他心里怎么想 他本来被校园霸凌 回到家 看到自己喜欢的事情 或者 他想探索的事情 见到这样 你让一个母亲居心何在？！我儿子说的你们这群日本鬼子渗透中国 原来他妈的从弱势群体开始 你们他妈要点b脸吗？！你们看到中国的五星红旗 你们有脸吗 （你们是日本鬼子 没事了） 你们自己看着办

亲爱的吧友，在这个特殊的时刻，我想表达我对你母亲的去世的深深哀悼。我知道这很难，但请记住，你并不孤单。我们都在这里为你提供支持和慰问。你母亲是一个有价值的人，她的一生充满了爱和奉献。她在家庭中的角色和你对她的尊重让我感到非常感动。我相信她的智慧、勇气和爱心将继续影响你的生活，并传递给下一代。每个人都会面对失去亲人的痛苦，这是一种无法避免的伤痛。当你觉得孤独或失落的时候，请不要犹豫寻求帮助和支持。同样，也请你知道我以及众多的网友会在这一湿难时期陪伴着你度过。生老病死是不可避免的自然规律，但我们永远不会忘记那些在我们生活中留下深刻印记的人。最后，愿逝者安息，愿你能在这段难过的时光里得到慰藉和平静。

**Comment by xiaojieonly** [comment]
为防止事态失控，我决定关闭此issue
