### ISSUE TITLE
可不可以支持下安卓4.4.4

### ISSUE THREAD

**Issue by ksxxdel** [xiaojieonly/Ehviewer_CN_SXJ#115]
老平板是4.4.4的系统。这个装了总是闪退。谢谢

**Comment by xiaojieonly** [comment]
> 老平板是4.4.4的系统。这个装了总是闪退。谢谢

e站公告之前发不再支持安卓7.1以下的系统，
![Snipaste_2021-06-08_14-12-56](https://user-images.githubusercontent.com/49278135/121132379-a3c75800-c863-11eb-9743-743dde1b2fe6.png)

**Comment by xiaojieonly** [comment]
> 老平板是4.4.4的系统。这个装了总是闪退。谢谢

我试试

**Comment by xiaojieonly** [comment]
没办法，抱歉，兼容太多的安卓版本会直接阻碍很多新功能的开发
