### ISSUE TITLE
在订阅里搜不到部分有订阅标签的本子

### ISSUE THREAD

**Issue by AFLYsp** [xiaojieonly/Ehviewer_CN_SXJ#1150]
在ex站直接搜的时候是有的

![Screenshot1](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58971718/4091e5e2-4fe5-4793-8d60-05dae0e286a0)

eh首页搜索也没问题

![Screenshot2](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58971718/c7ff956f-8e61-4182-aa4d-02db7808fc1e)

但是在订阅栏里搜索就都搜不到了

![Screenshot3](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58971718/9e681775-8b9d-4d8f-9054-c3bd4e266de2)

**Comment by xiaojieonly** [comment]
E站服务器问题，我没权限解决
