### ISSUE TITLE
1.9.7.10版本及以后看不到历史记录

### ISSUE THREAD

**Issue by fanggchang** [xiaojieonly/Ehviewer_CN_SXJ#1151]
机型是荣耀90,REA-AN00，系统是magic8.0，a14。
看了一个本子之后在历史记录里找不到，好难受啊

**Comment by GreetGod** [comment]
个人同样出现这个问题，我怀疑是历史计入数量这个设置项默认值为0导致BUG。可以在【设置-EH-历史记录数量】这个选项内更改数值保存后就能正常显示历史记录

**Comment by fanggchang** [comment]
还真是

**Comment by EarOfWheat** [comment]
正解，我升级上来发现还看不了记录，来closed才解决
