### ISSUE TITLE
为什么点下载之后没有反应？

### ISSUE THREAD

**Issue by ztgajv** [xiaojieonly/Ehviewer_CN_SXJ#1152]
![Screenshot_2024-04-21-08-52-56-888_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/167658445/3787acea-7328-44f3-8672-1fd88e31e7f9)

**Comment by xiaojieonly** [comment]
系统不让下载呗

**Comment by ztgajv** [comment]
> 系统不让下载呗

可是我应该开权限了啊

**Comment by ztgajv** [comment]
没有禁止安装啊

**Comment by ztgajv** [comment]
奇怪了

**Comment by ztgajv** [comment]
> > 系统不让下载呗
> 
> 可是我应该开权限了啊

图片放不出来，好怪
