### ISSUE TITLE
图片搜索

### ISSUE THREAD

**Issue by sdo9004** [xiaojieonly/Ehviewer_CN_SXJ#1153]
1.9.7.11现在没有图片搜索了吗😭

**Comment by Steve-337** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/commit/262857daf88f9d63bd4598cbc2ba82623edab17f
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/commit/6156471a352dec080ba4bff03441123620e5cfcc

**Comment by xiaojieonly** [comment]
下一版就有了
E站那边重新提供了
