### ISSUE TITLE
关于下载问题求教

### ISSUE THREAD

**Issue by duya4399** [xiaojieonly/Ehviewer_CN_SXJ#1158]
请问一下大佬，为啥我e站手机本地文件无法删除，在app里删除本子后，手机本地文件夹内还存在这个本子，清理下载冗余和删除图片文件都已经勾选上，还是无法删除，目前我手机e站本地文件数量是e站内的目录本子数量的两倍，我查看了一下应该是以前在app内删除的本子，手机本地文件中都没有删除
![6a359ebf04e07a9ce3af4c53d902c29](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/167956621/2d585c12-a9ce-493e-99f2-0ce97822e31b)
![7aa433acb322112b4cecb8d4d1b54b6](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/167956621/c918b5cc-1ff0-4da9-b890-e70c95833b47)

**Comment by xiaojieonly** [comment]
有bug，建议手动删除，后面会抽时间修一下
