### ISSUE TITLE
收藏夹内没有全选按钮

### ISSUE THREAD

**Issue by sacimol** [xiaojieonly/Ehviewer_CN_SXJ#1159]
有段时间担心e站倒闭, 所以收藏都是选本地, 最近想移动到云端方便电脑查看, 发现没有批量移动的按钮, 之前用过彩E是有这个功能的;
也试过绿e导出数据然后在彩e中导入数据并进行批量操作, 但可能是格式不同, 彩e读不到绿e导出的本地收藏;
图一为彩e:
![Screenshot_2024-04-24-15-06-06-694_moe tarsin ehv](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58618519/ea136af2-a69b-45e9-a82a-dfa4c9437ac8)
![Screenshot_2024-04-24-15-06-23-329_com xjs ehview](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58618519/07d43c8d-1a2c-4a13-bdf8-f0e575eacecb)

**Comment by xiaojieonly** [comment]
目前没这功能，以后有时间会搞搞看
