### ISSUE TITLE
求助：阅读历史无法录入

### ISSUE THREAD

**Issue by Johndoe14185** [xiaojieonly/Ehviewer_CN_SXJ#1162]
作者你好，最新版本的阅读历史不能录入，“历史”选项里不显示画廊，只有“这里是阅读历史”，劳烦作者有空时修复一下，谢谢作者！

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1151

**Comment by Johndoe14185** [comment]
👌，谢谢作者解答
