### ISSUE TITLE
跨版本记录历史记录被清空

### ISSUE THREAD

**Issue by ka-hasu** [xiaojieonly/Ehviewer_CN_SXJ#1163]
从大概是1.9.6.7跨版本到目前最新版本，发现历史记录被清空
[logcat-2024-04-26-12-53-34-181.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/15125526/logcat-2024-04-26-12-53-34-181.txt)

**Comment by EarOfWheat** [comment]
#1128  #1151

是否为已解决相似问题

**Comment by EarOfWheat** [comment]
#1151

**Comment by q15751261559** [comment]
同，不仅历史记录被清空而且无法记录新的历史记录

**Comment by ka-hasu** [comment]
> #1128 #1151
> 
> 是否为已解决相似问题

谢谢哥，数据被清除了哭麻了😭，早知道不更新了

**Comment by ElementGC** [comment]
设置-EH里面有一个历史记录上限，在那里设置一下就好，应该是更新之后新加的，默认为0所以就没有记录
