### ISSUE TITLE
排行榜中部分无法正常打开

### ISSUE THREAD

**Issue by Dingzheng0615** [xiaojieonly/Ehviewer_CN_SXJ#1171]
如最近万华镜雪女的几个，可以在排行榜界面看到，但是点击打开却显示“什么都没有找到”，而我可以在白e和网站上正常打开这些

**Comment by xiaojieonly** [comment]
换表站，两个排行榜不是一个东西

**Comment by Dingzheng0615** [comment]
就是表站，而且我切里站会什么都打不开

**Comment by Dingzheng0615** [comment]
里站的host文件也打开了

**Comment by Dingzheng0615** [comment]
里站的问题我知道解决方案了，也不看里站，懒得搞了

**Comment by Dingzheng0615** [comment]
> 换表站，两个排行榜不是一个东西

用的是表站

**Comment by Dingzheng0615** [comment]
这些打不开的我可以通过其他途径添加到收藏里，然后可以在收藏里正常打开和下载
