### ISSUE TITLE
更新1.9.1.11后关于下载项的一些问题

### ISSUE THREAD

**Issue by 1005GitHub** [xiaojieonly/Ehviewer_CN_SXJ#1173]
我很久没更新，不记得更新前是什么版本
### 1. 无法浏览在之前版本的下载的画廊
在APP内无法浏览
![Screenshot_20240429_131131_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/aeebcf57-daa1-4e4b-b05a-7b025afae7e5)
![Screenshot_20240429_131202_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/2b7935c1-088f-4af0-ba5d-3da4013cbee5)
但是文件并未消失，可以在文件管理器内浏览
![Screenshot_20240429_131340_com huawei filemanager](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/42843b01-761b-477c-a079-a89a3460cf9b)
![Screenshot_20240429_131344_com huawei filemanager](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/fe6ba690-904b-4171-8931-38aa64fcd440)
此外还有个可能对解决问题有帮助的细节，即下载的gif在文件管理器内都变成jpg了
### 2.无法下载新画廊
可以进行正常浏览
![Screenshot_20240429_131743_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/e7e0d9bf-e0bc-47cd-b797-abae16fbec14)
![Screenshot_20240429_131745_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/d5ec4832-0677-4619-b8f8-07d5a19547b3)

但无法进行下载
![Screenshot_20240429_131832_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/545d9e2c-9782-4f90-8cd6-3b50801cc92a)
![Screenshot_20240429_131835_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/8d173646-4bc4-4e96-94a9-2d298db05cfe)

如果以上问题在先前的版本里已**有提及或修复**，请通知我。
此外，在将来可能的修复了该问题的新版本发布前，以旧版本覆盖可以解决吗？如果可以，哪个版本可以呢？

**Comment by 1005GitHub** [comment]
![Screenshot_20240430_043355](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/2ee180e6-fb71-4a97-a40b-ac0a00881c02)
我想这就是原因了

**Comment by 1005GitHub** [comment]
> ![Screenshot_20240430_043355](https://private-user-images.githubusercontent.com/91907569/326579817-2ee180e6-fb71-4a97-a40b-ac0a00881c02.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjM0OTAsIm5iZiI6MTcxNDQyMzE5MCwicGF0aCI6Ii85MTkwNzU2OS8zMjY1Nzk4MTctMmVlMTgwZTYtZmI3MS00YTk3LWE0MGItYWMwYTAwODgxYzAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZDk4ZGUwMjQ2YzZlMDE1MmE5Y2U5OGRhODEzNGJlNmMyNjFiZTU2ZjliZGUzNGQzY2E5YzM3NDI5OGJmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hazxuvipp0SXPtV5p3kKrxErw8vGwsNDniFHMBrSSqw) 我想这就是原因了

![Screenshot_20240430_043921_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/91907569/96a45217-fc1b-4b13-b0b8-73b901527bf4)
天哪，还是下载不了。到底是怎么回事？

**Comment by xiaojieonly** [comment]
我不知道，我这里复现不出来你的问题，多半还是系统问题

**Comment by 1005GitHub** [comment]
> 我不知道，我这里复现不出来你的问题，多半还是系统问题

感谢通知。请问“系统问题”是什么？有何参考。
