### ISSUE TITLE
最新版本历史记录仍未解决

### ISSUE THREAD

**Issue by italycalibur2019** [xiaojieonly/Ehviewer_CN_SXJ#1174]
没看到其他人反馈不知道是不是自己机型的问题，手机有root过。
![Screenshot_2024-04-29-19-41-10-379_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/53480306/bd540453-9276-4734-ab2f-48340f84a15e)

手机型号：Redmi Note 11T Pro 
系统版本：HyperOS 1.0.1.0
软件版本：1.9.7.11

**Comment by xiaojieonly** [comment]
重新设置历史记录数量
