### ISSUE TITLE
图片显示invalid page

### ISSUE THREAD

**Issue by Asterash** [xiaojieonly/Ehviewer_CN_SXJ#1181]
在画廊更新后会出现部分下载过的图片未从本地提取，而是每次点开进行加载显示，且出现缩略图和原文件不匹配的情况，删除画廊后不匹配的图片显示invalid page或解析失败且无法对这部分图片进行下载，但缩略图保持正常。
![IMG_20240502_094751](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168694839/82e7bfbe-70d1-4fb4-ad67-e16e5501f8b5)
![Screenshot_20240502_094619](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168694839/2cb4e8b7-a6fd-4cb6-848b-6b99d334347c)
![Screenshot_20240502_094629](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168694839/6ed8ffc0-5c48-45f1-b372-96f0ba43beee)

**Comment by Asterash** [comment]
现在发现只有覆盖下载会出现这个问题

**Comment by dritterplatz** [comment]
> 现在发现只有覆盖下载会出现这个问题

我现在重新下了还是这样

**Comment by xiaojieonly** [comment]
本地文件删了重下
