### ISSUE TITLE
下载中止后继续下载，进度会回溯，而且还会再消耗一遍配额

### ISSUE THREAD

**Issue by YuRen97** [xiaojieonly/Ehviewer_CN_SXJ#1184]
比如我现在下载个2000图的画廊，下载1800张它速度归0停止了，文件夹里已经有1800张图片，但是如果我要继续下载，它会从1200张的进度开始。
![QQ图片20240504205459](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/149453415/ac7967fa-834c-466f-b9a0-e3e310c14816)
![QQ图片20240504205514](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/149453415/49416f38-581b-41de-9a19-50694bea11e6)

**Comment by xiaojieonly** [comment]
是不是权限没给？继续下载会重新检查本地文件，已经下载好的图片会自动跳过

**Comment by junwense** [comment]
> 是不是权限没给？继续下载会重新检查本地文件，已经下载好的图片会自动跳过

这个问题我也遇到过，大部分是下载大图片画廊比如2000左右，下载失败就会重新下载，其他倒是正常下载，覆盖下载也容易导致这个问题
