### ISSUE TITLE
误卸载数据恢复问题

### ISSUE THREAD

**Issue by Lmyssh** [xiaojieonly/Ehviewer_CN_SXJ#1185]
不小心把eh卸载了，没有做数据备份，导致重新安装后，明明下载的本地本子还在 但是无法读取了，请问这种情况怎么解决呀？

**Comment by junwense** [comment]
> 设置→下载→恢复下载项，记得确认下载路径与原下载路径一致

下载文件过多的话恢复会出问题的，而且如果使用了覆盖下载，会导致下载目录有同画廊的多版本文件，恢复也会有问题
