### ISSUE TITLE
求求下载后自动打包成压缩包的功能

### ISSUE THREAD

**Issue by bkhslj** [xiaojieonly/Ehviewer_CN_SXJ#1188]
(*´﹃｀*)
因为发现本应用连1GB 300张GIF的压缩包都能正常读取，所以想用干脆压缩包的形式存储。
以缩短每次从手机复制到电脑上要等待覆盖确认的时间……

**Comment by xiaojieonly** [comment]
拒绝🙅🏻‍♀️
