### ISSUE TITLE
关于归档下载

### ISSUE THREAD

**Issue by ThreeSourLemon** [xiaojieonly/Ehviewer_CN_SXJ#1189]
归档下载的文件会下载到/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/
这个不应该和普通下载一样下载到/storage/emulated/0/EhViewer/archiver/嘛
归档下载的文件 不会在下载列表里 不能和普通下载的漫画一样可以直接查看
选zip文件用ehviewer打开观看后也不能保存进度
希望归档下载可以和普通下载一样出现在下载列表里 并且可以保存进度
普通下载下太多老是被ban ip

**Comment by xiaojieonly** [comment]
下载完前不退出会自动导入到下载列表，麻烦仔细看看更新日志

**Comment by ThreeSourLemon** [comment]
> 下载完前不退出会自动导入到下载列表，麻烦仔细看看更新日志

 测试了下 没有被添加到下载列表里面
但是漫画详情页面显示已下载
/storage/emulated/0/EhViewer/download/目录下有已经解压好的图片
手动在设置-下载-恢复下载项 提示：未找到可恢复下载项

漫画详情页面点击已下载进行删除操作也没有效果
/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/目录里的压缩包
和/storage/emulated/0/EhViewer/download/里的已解压文件夹 依旧存在

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/43909683/bd333b64-ecfb-446e-9a8d-4ab23fceb8ac

**Comment by xianren45** [comment]
可以给我下载链接吗？好久没用现在用不了了😭😭😭
