### ISSUE TITLE
标签翻译

### ISSUE THREAD

**Issue by Lapis-chan** [xiaojieonly/Ehviewer_CN_SXJ#1190]
我app卸载重装后标签翻译没了，设置里显示需要花费时间下载数据文件，它是会自动下还是说要挂个梯子什么的
![Screenshot_2024-05-07-22-46-40-792_com xjs ehview](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/169173477/f2eeb08c-0937-4a6a-8e4d-b2c6dae420c6)

**Comment by xiaojieonly** [comment]
等，挂个梯子会快一点
