### ISSUE TITLE
阅读历史突然空了

### ISSUE THREAD

**Issue by jesjes1234** [xiaojieonly/Ehviewer_CN_SXJ#1192]
阅读历史突然空了 而且再看新本里面还是空的 怎么回事呢  
![Screenshot_2024-05-08-20-52-23-991_com xjs ehview](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/42902299/7337672a-f1f4-457e-b763-1f1085696fc1)

**Comment by StarDustDurgan** [comment]
一样的问题

**Comment by YwdFora** [comment]
一样的问题，阅读历史不能用好久了

**Comment by jesjes1234** [comment]
救命啊 突然就没了 然后怎么弄也出不来

**Comment by jesjes1234** [comment]
找到个解决办法 去设置里-历史记录数量-重新设置一下数量 就有了

**Comment by YwdFora** [comment]
> 找到个解决办法 去设置里-历史记录数量-重新设置一下数量 就有了

感谢，解决了。应该是版本更新把这一项重置了
