### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by 2024githubInc** [xiaojieonly/Ehviewer_CN_SXJ#1193]
账号可以在网页端登录，且可以访问里站。

网络配置
未使用其他代理。
内置ehentai 开启
内置exhentai 开启
自定义未设置
安全dns 未开启
域名前置 开启

如果使用ehentai站点查看，可以搜索，但缩略图看不见，点开画作后可以看见评论区但点开详细图片会报网络错误。
如果使用exhentai站点查看，搜索后报网络错误。

尝试导出日志，但日志文件为空。

**Comment by yellowteaegg** [comment]
我也出现了网络错误

**Comment by Lxy575** [comment]
我在境内亦有相同之问题

**Comment by xiaojieonly** [comment]
重新登录
