### ISSUE TITLE
常用的裸连设置近日突然用不了了

### ISSUE THREAD

**Issue by Lxy575** [xiaojieonly/Ehviewer_CN_SXJ#1196]
如题，已经按照答疑中设置了host和域名前置，但是仍然无法裸连exhentai和e-hentai，用的是联通宽带，前几天一直可用但是突然不好使了，不知是我个人原因还是大家均有有类似问题。

**Comment by xiaojieonly** [comment]
我都正常，应该是网的问题，换个网试试
