### ISSUE TITLE
历史纪录失效

### ISSUE THREAD

**Issue by miku9425** [xiaojieonly/Ehviewer_CN_SXJ#1200]
更新到最新版本，看本子依然显示不出历史纪录，整片都是空白的

**Comment by miku9425** [comment]
草，破案了，没设置历史纪录显示数量导致的，没设定的话就一直是空白

**Comment by serdfn** [comment]
找到历史记录数量，如果到达指定设定的上限会清空，下次把记录数量调高一点就行也可以调成无限制

![Screenshot_2024-05-12-10-38-32-83_159c494ea8977f628e53d8d36755ba4c.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/141130496/2af427c0-ed8c-4c8d-b11c-7280923c3702)

第一次用评论功能，见谅
