### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by Ailuolit** [xiaojieonly/Ehviewer_CN_SXJ#1204]
0/5000进入程序，打开下载页面，下载显示0B/S，但是10秒吃完5000配额，然后509。

**Comment by dufif** [comment]
你是不是挂着公共梯子上的？

**Comment by Ailuolit** [comment]
实际上，我没挂梯子，裸连的

**Comment by dufif** [comment]
配额跟着ip走 可能你隔壁邻居冲完了 如果是第一次有这种情况的话过段时间等刷新再观察一下

**Comment by Ailuolit** [comment]
从上上周开始的，ip我重启路由器也没用，退版本也没用，我怀疑是移动的问题

**Comment by Ailuolit** [comment]
你们上eh，还用梯子吗？

**Comment by xiaojieonly** [comment]
我不用，WiFi换个密码试试

**Comment by xiaojieonly** [comment]
或者用手机流量试试

**Comment by Ailuolit** [comment]
都试过没用才来github求助的-.-

**Comment by Ailuolit** [comment]
![20240514-113337](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/953d8984-b47e-4baa-b598-ee0207d430ab)
![20240514-113355](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/37faa472-2a3d-4e7b-8532-bd18bbe5832a)
![20240514-113422](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/5a6ed2d0-eca7-4562-a95b-2133d6c5b908)
![20240514-113446](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/13c964c1-2951-4d66-98a1-06eb5bc9b86c)
![20240514-113534](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/c8e37438-37d1-4abe-80a3-022ea49fbdce)
![20240514-113541](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/a425a821-e264-4cb4-bffe-08734289b69a)
![20240514-113555](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118603800/d041927c-b1ea-42a9-b0a1-698ab5d839b3)

**Comment by xiaojieonly** [comment]
我按照你的流程走了一遍，
结果是：和app没有关系

**Comment by Ailuolit** [comment]
我疑惑的地方是，明明没有数据在跑，但是配额却像流水一样的掉。  而造成0b/s的原因我稍后挂梯子看能不能解决，如果挂梯子可以解决0b/s的问题，那应该是移动运营商的问题。

**Comment by Ailuolit** [comment]
> 我按照你的流程走了一遍， 结果是：和app没有关系

刚刚用梯子试了一下，依旧有上述问题，我现在怀疑是手机问题。

**Comment by lvzhishang** [comment]
> > 我按照你的流程走了一遍， 结果是：和app没有关系
> 
> 刚刚用梯子试了一下，依旧有上述问题，我现在怀疑是手机问题。

我最近也出现这个问题了，还说过来看看有没有解决方案...
