### ISSUE TITLE
exh啥錯誤訊息都沒有，eh正常可看

### ISSUE THREAD

**Issue by zxc102635** [xiaojieonly/Ehviewer_CN_SXJ#1205]
![Screenshot_20240513-231310385 (1)](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/112270203/db63d916-40fd-44b1-bf23-3b4a21d20be6)

**Comment by fivetwoson** [comment]
我这边也是，突然就变这样了
![Screenshot_2024-05-14-03-43-08-700_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/169732789/1555114c-60b2-4a01-9c7a-2d34f7e2b8b3)

**Comment by xiaojieonly** [comment]
cookie重新登录下
