### ISSUE TITLE
xj绿e下载本子后无法加载

### ISSUE THREAD

**Issue by l2959414766** [xiaojieonly/Ehviewer_CN_SXJ#1206]
最近遇到这种情况，遇到比较大的本子下载后，在下载页面观看会加载不出来。通常一页/15mb左右这种。除非长按图片重新加载才会出来。

**Comment by xiaojieonly** [comment]
习惯就好，大图在网络不稳定的时候是会出现加载失败的问题

**Comment by l2959414766** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] xj绿e下载本子后无法加载 (Issue #1206)




 
习惯就好，大图在网络不稳定的时候是会出现加载失败的问题

**Comment by l2959414766** [comment]
行吧，下载完了也加载不出来，太难了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] xj绿e下载本子后无法加载 (Issue #1206)




 
习惯就好，大图在网络不稳定的时候是会出现加载失败的问题

**Comment by MatthewsWang-pri** [comment]
我也遇到了类似情况

**Comment by 2911894613** [comment]
我也遇到了，在本地文件里看是下载成功了的，但在eh里看就一直转圈加载不出来
