### ISSUE TITLE
为什么加载不出图片  求大佬帮

### ISSUE THREAD

**Issue by qingnianshuumen** [xiaojieonly/Ehviewer_CN_SXJ#1208]
![截屏_20240518_232005](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/170196066/46bc694f-e7b4-476f-8536-10b7af635691)
重新下载后开始转圈了
![截屏_20240519_005650](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/170196066/d6b15bb2-f8e8-40b3-b861-fe8e6f86459f)

**Comment by qingnianshuumen** [comment]
原来用的红米12pro可以裸连看，现在换安卓6就不行了

**Comment by ZYsuai** [comment]
同上，求大佬帮忙

**Comment by ZYsuai** [comment]
> 同上，求大佬帮忙

点进去图片是网络错误

**Comment by xiaojieonly** [comment]
低版本安卓需要挂梯子，重新登陆试试

**Comment by Edian-Midir** [comment]
低版本挂梯子重新登陆也无法访问图片,只能访问到列表,怀疑是因为Android 6的设备不支持资源图片域名的ssl证书导致的
