### ISSUE TITLE
出现了解释失败的问题。

### ISSUE THREAD

**Issue by YukuliKurumi** [xiaojieonly/Ehviewer_CN_SXJ#121]
已经下载的图片可以正常使用，但是无论是收藏还是搜寻功能都会出现解释失败。我不是很懂编程，不是很懂里面原因，请问有什么方法可以把我的错误内容转告给您？谢谢。

**Comment by xiaojieonly** [comment]
好好看一下更新日志，并在已解决和解决的issue里好好找找和看看。



---Original---
From: ***@***.***&gt;
Sent at: 2021年6月21日(Mon) AM9:38
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [xiaojieonly/Ehviewer_CN_SXJ] 出现了解释失败的问题。 (#121)




 
已经下载的图片可以正常使用，但是无论是收藏还是搜寻功能都会出现解释失败。我不是很懂编程，不是很懂里面原因，请问有什么方法可以把我的错误内容转告给您？谢谢。

**Comment by YukuliKurumi** [comment]
真奇怪，我把sni打开了之后把梯子去掉就能上了。难道是梯子的问题吗？可是这个贴纸我在哪里用都挺正常的，上ex原网也没问题。

**Comment by YukuliKurumi** [comment]
不过无论如何，感谢了🌚👍

**Comment by xiaojieonly** [comment]
裸连不香嘛？



---Original---
From: ***@***.***&gt;
Sent at: 2021年6月21日(Mon) Noon1:57
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 出现了解释失败的问题。 (#121)




 
不过无论如何，感谢了🌚👍
