### ISSUE TITLE
希望作者大大增加webdav的功能,减轻手机存储

### ISSUE THREAD

**Issue by AiharaMei** [xiaojieonly/Ehviewer_CN_SXJ#1210]
用的时间久了256G的存储顶不住了,备份到了nas上后,又想着用ehviewer看
真心希望往后能出个webdav功能,浏览云盘的资源,本地数据库也能记录下进度

**Comment by xiaojieonly** [comment]
。。。

**Comment by xiaojieonly** [comment]
我目前没有nas，所以目前这个功能没法开发，如果有能力可以试着提交一个pull request
