### ISSUE TITLE
头像显示有问题

### ISSUE THREAD

**Issue by ShiraiKurokor** [xiaojieonly/Ehviewer_CN_SXJ#1212]
![Screenshot_2024-05-21-12-53-40-316_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/61131877/c7d70bcd-9b0a-44a5-bad7-0dee696d6de9)
头像显示有问题，一个圆包裹一个方。
希望对头像显示做好适配，或干脆显示方头像。

**Comment by xiaojieonly** [comment]
换张大点的图试试
