### ISSUE TITLE
ex访问不了，cookie登录后，igneous自动变mystery

### ISSUE THREAD

**Issue by a20510593** [xiaojieonly/Ehviewer_CN_SXJ#1214]
一样同个网，电脑网页登录，也有同样自动变mystery问题，但删除cookie底下yay的louder值，就顺利进入ex了

eh却无法这样解决，切回表站再cookie登录，igneous值还正常，一切回ex就自动变mystery

切回表站cookie登录后，勾选锁定igneous值，一样变mystery，有解吗？
![remix-4762582c-6a03-45dc-9783-f6f6eaf70696](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/170619780/39531f06-d5d4-44bb-a38d-ca149b20bf72)

**Comment by xiaojieonly** [comment]
站点是ex的情况下用cookie重新登录

**Comment by a20510593** [comment]
> 站点是ex的情况下用cookie重新登录

站点ex一登录进去，cookie的igneous就显示mystery，无解阿
