### ISSUE TITLE
最近一周出现解码失败

### ISSUE THREAD

**Issue by cheeseburger617** [xiaojieonly/Ehviewer_CN_SXJ#1219]
最近浏览画廊出现解码失败，多次刷新也没用，最开始在https://exhentai.org/g/2924904/8bd6e49aa4/的p15发现，刷新没用后看评论区也有出现相同情况的人，这个画廊也是相同的情况https://exhentai.org/g/2926455/7190807070/，随后尝试了以前能正常浏览的画廊，也有解码失败的情况出现
![Screenshot_2024-05-26-00-41-38-256_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/170820187/00c41341-0c52-4629-8477-8029cea1cc87)

**Comment by AustinZhang1024** [comment]
今天也遇到了，有解决方案吗

**Comment by cheeseburger617** [comment]
> 今天也遇到了，有解决方案吗

没，挂梯子换节点都试过了，都没解决

**Comment by AustinZhang1024** [comment]
> > 今天也遇到了，有解决方案吗
> 
> 没，挂梯子换节点都试过了，都没解决

我重新登录也试了，没啥用，不知道为啥这个issue被关了

**Comment by AustinZhang1024** [comment]
我知道了，用浏览器登陆ex，然后再输入cookies在客户端登陆，不要直接在客户端登陆。安卓上可以用via之类的工具
