### ISSUE TITLE
配额有问题

### ISSUE THREAD

**Issue by zjdhczjjdhd** [xiaojieonly/Ehviewer_CN_SXJ#1221]
我今天明明一个画廊也没下载，可今天晚上下载的时候配额显示5034/5000

**Comment by zjdhczjjdhd** [comment]
还有一件事，不登陆的话就不能下载画廊，之前还是可以下载的

**Comment by lvzhishang** [comment]
我这边也是，而且我发现我搜索不了shotacon标签，下载过的很多画廊会出现404
![Screenshot_2024-05-28-07-33-54-342_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/27761823/15a398ce-3490-44bd-b7af-a77303d1dee8)
![Screenshot_2024-05-28-07-34-15-228_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/27761823/fdbc90c1-f1ec-4e06-8b6e-043665528a9c)
