### ISSUE TITLE
一直加载显示画廊是什么情况

### ISSUE THREAD

**Issue by rremo888** [xiaojieonly/Ehviewer_CN_SXJ#1223]
![Screenshot_20240528_140609](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/142709117/9de7ce43-3b0c-46d1-8c41-850adec8003a)
如图，打开软件后就这样，等待一段时间后显示超时。网站可以正常登录，软件偶尔可以看但是大部分时间都无法加载，要怎么办呢？

**Comment by xiaojieonly** [comment]
单纯网不好

**Comment by rremo888** [comment]
> 单纯网不好

感觉并不是，无论是连接wifi还是流量的情况下裸连都用不了，但是开了梯子就可以，换了站点、账号也没用
