### ISSUE TITLE
最新更新後，歷史紀錄沒紀錄任何閱讀過作品

### ISSUE THREAD

**Issue by zxc102635** [xiaojieonly/Ehviewer_CN_SXJ#1227]
![Screenshot_20240601-231203215 (1)](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/112270203/581ee79c-b675-445a-9e03-33dac80b20b9)

**Comment by Grox0101** [comment]
我也有这个问题

**Comment by xiaojieonly** [comment]
设置里设置下数量
