### ISSUE TITLE
跪求大佬加入功能

### ISSUE THREAD

**Issue by s0me0nels** [xiaojieonly/Ehviewer_CN_SXJ#1229]
大佬能不能加入下载列表随机打开的功能啊，看到喜欢的tag就下载了不知不觉列表已经5k+了，难以选择下一个看什么TAT
又或者加入一个能将下载列表中的本子批量放入收藏夹的也行，跪谢大佬

**Comment by xiaojieonly** [comment]
好的

**Comment by xiaojieonly** [comment]
下一版上
