### ISSUE TITLE
Anbox 用 houdini 後無法執行

### ISSUE THREAD

**Issue by laichiaheng** [xiaojieonly/Ehviewer_CN_SXJ#123]
如我用原生的 Anbox 跑沒有問題，但是一用上 houdini 後就只會跑出白畫面

**Comment by xiaojieonly** [comment]
啊，这，我得先搜一下anbox和houdini分别是啥😂

**Comment by xiaojieonly** [comment]
跨度有点大，不做单独支持了，抱歉

**Comment by laichiaheng** [comment]
現在已經改用新的 Waydroid 了，他好像是要用來取代舊的 Anbox 用的？
不過只能在 Wayland 上運行就是……
