### ISSUE TITLE
功能請求 看完後自動跳轉下一個畫廊

### ISSUE THREAD

**Issue by SAwings** [xiaojieonly/Ehviewer_CN_SXJ#1230]
有些畫家沒有合集只能一個一個的翻ARTISTCG看
要請問作者在技術上可否增加當第一本看完後自動跳轉下一個畫廊 可能在設定開啟之類
不知道有沒有辦法做到 謝謝🙏
![Screenshot_20240602_093348_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/47296047/7262a7f9-858d-476f-90ff-aff4539392c7)

**Comment by xiaojieonly** [comment]
有是有，但是我个人觉得意义不大(⊙o⊙)…
