### ISSUE TITLE
更新1.9.8.1之后出现了问题

### ISSUE THREAD

**Issue by 7881632** [xiaojieonly/Ehviewer_CN_SXJ#1232]
下载的东西无法再加载，不知道怎么好..更改下载位置好像也不行不能读写，然后也移除了管控还是不行救救孩子，难不成只有我一个人遇到了问题？我是鸿蒙系统

**Comment by xiaojieonly** [comment]
系统没给权限，我也爱莫能助

**Comment by xiaojieonly** [comment]
你可以去贴吧问问，鸿蒙吧啥的
