### ISSUE TITLE
希望添加下载如果超时自动下载下一本的功能

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#1235]
现在不知道是为什么经常下载的时候会卡在最后几页下不动（如下图），得手动暂停再开始，这样又能正常下完。
       希望能添加一个下载速度保持0b/s超过2秒，就自动暂停当前下载进行另一本下载的功能。
![Screenshot_2024-06-04-21-38-10-977_com miui gallery-edit](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/5333f096-167e-4151-96c0-46eb10471668)
@xiaojieonly

**Comment by xiaojieonly** [comment]
1

**Comment by s0me0nels** [comment]
这个现在也有吧，挂在那一会它回变成失败状态然后下后面的，等回过头来再全部继续就好了

**Comment by tongsang** [comment]
> 这个现在也有吧，挂在那一会它回变成失败状态然后下后面的，等回过头来再全部继续就好了

但实际情况是，几个小时过去后面一大堆没下，还是在下那一本并且0b/s😅

**Comment by xiaojieonly** [comment]
已写好，测一下下一版上
