### ISSUE TITLE
只是说一下出现的现象

### ISSUE THREAD

**Issue by FB123406** [xiaojieonly/Ehviewer_CN_SXJ#1236]
现在绿E有些标签搜不到了，但是其他E有的可以搜到例如正太和萝莉标签，网站版上也搜不到。虽然直接搜某些标签不行，但是可以通过搜其他标签间接找到同一个目标。不知道是什么情况

**Comment by Steve-337** [comment]
确保是里站然后再次尝试

**Comment by FB123406** [comment]
我确认过了是里站

**Comment by lvzhishang** [comment]
我也是，我还说为什么彩E可以，绿E搜不着...好难受啊

**Comment by xiaojieonly** [comment]
可能是今天中国区h@h服务器出了点意外导致的，你再试试？
或者检查下是否不小心屏蔽了相关tag
我自己手机上看了下感觉是正常的
😵‍💫😵‍💫😵‍💫
如果还不行请重新打开本issue

**Comment by lvzhishang** [comment]
大佬，确认了好多回啦，出现这种情况有差不多半个月了，之前我还问过一次配额的问题，后来把安全dns关掉，配额就恢复正常了，不再是下不动配额还框框掉。不过出现另外一个问题就是这个，我是正太标签看不到了，而且之前下载过的画廊再点开详情就会是404...

**Comment by lvzhishang** [comment]
> 大佬，确认了好多回啦，出现这种情况有差不多半个月了，之前我还问过一次配额的问题，后来把安全dns关掉，配额就恢复正常了，不再是下不动配额还框框掉。不过出现另外一个问题就是这个，我是正太标签看不到了，而且之前下载过的画廊再点开详情就会是404...

具体图片我再1221号问题里发过😭

**Comment by Steve-337** [comment]
我在想会不会是梯子地区导致的，反正没能复现
