### ISSUE TITLE
关于某些tag的搜索问题

### ISSUE THREAD

**Issue by FB123406** [xiaojieonly/Ehviewer_CN_SXJ#1237]
可能是由于我不小心重开过一次，所以这次我没看到有重开按钮，只能开个新的了。

总结一下，目前发现问题的tag有“正太”“低存在感正太”“萝莉”。表现直接搜索显示空白，但是可以通过搜索同一作品的其他tag找到。绿E和网页都有同样的问题，不排除和账户有关，但是彩E不受影响。已确认是里站，并且没有将tag设置屏蔽，多次测试问题仍然存在。另有人指出此现象已存在较长一段时间，但有的用户似乎没有受到影响。

**Comment by xiaojieonly** [comment]
根据你的描述，如果网页端有同样的问题，那就是E站服务器有问题，或者你账号有问题

**Comment by lvzhishang** [comment]
我刚试了一下，把这个地方改了就可以搜出来了
![Uploading Screenshot_2024-06-05-11-05-32-784_com.xjs.ehviewer.jpg…]()
兄弟你要不要试试

**Comment by lvzhishang** [comment]
我刚试了一下，把这个地方改了就可以搜出来了
![Screenshot_2024-06-05-11-05-32-784_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/27761823/22172236-af40-4f13-98a2-4c1d8059ac45)
兄弟你要不要试试

**Comment by lvzhishang** [comment]
我刚试了一下，把这个地方改了就可以搜出来了
![Screenshot_2024-06-05-11-05-32-784_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/27761823/22172236-af40-4f13-98a2-4c1d8059ac45)
兄弟你要不要试试

**Comment by lvzhishang** [comment]
之前是第一个站点，确实搜不出来

**Comment by FB123406** [comment]
好吧，我搞错了。问题出在绿E进不去里站但是彩E可以。

**Comment by FB123406** [comment]
搞定了，我用彩E的cookie登录绿E就能进里站了

**Comment by 1620527018** [comment]
我也遇见这种情况，不只是标签搜不出来之前下载好的点进去后也显示此图库已被删除。视乎e站对恋童癖来了一场猎巫行动
