### ISSUE TITLE
请求增加高级搜索选项支持，特别是expunged画廊搜索支持

### ISSUE THREAD

**Issue by freecube0209** [xiaojieonly/Ehviewer_CN_SXJ#1239]
e站搜索有高级搜索选项，请求把这些搜索功能添加进来。特别是expunged画廊的搜索支持希望做成一个可选开关，别的什么搜索筛选倒是无所谓，但是expunged搜索支持希望能实现。

**Comment by xiaojieonly** [comment]
已经有了

**Comment by freecube0209** [comment]
> 已经有了

感谢，找到了。昨天找昏头了。
