### ISSUE TITLE
解碼失敗

### ISSUE THREAD

**Issue by s4028600** [xiaojieonly/Ehviewer_CN_SXJ#1240]
下載下來
大部分是正常的
少量圖片解碼失敗
用檔案瀏覽器開啟長這樣
![Screenshot_20240605_213347_File Manager +](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/19856067/fb279589-b50f-4107-aeb5-c29f199e84b1)
重新下載
清理內存之類的都沒用

**Comment by xiaojieonly** [comment]
有些E站链接从H@H服务器上是损坏的，试着挂梯子重新下载或者裸连重新下载

**Comment by s4028600** [comment]
我不用掛梯子
裸連是代理改成直接連線嗎
