### ISSUE TITLE
希望加入smb的NAS网络下载和阅读路径

### ISSUE THREAD

**Issue by venom8823** [xiaojieonly/Ehviewer_CN_SXJ#1241]
随着ai本子质量的越来越高，想要珍藏的本子也越多越多了，手机本地内存和SD卡那点容量根本不够  呜呜呜  只能用内网nas来扩展容量了，希望能加入读取网络内存路径的smb方式进行扩展，哦捏该Orz

**Comment by xiaojieonly** [comment]
1
