### ISSUE TITLE
麻烦问一下“TargetlmageUrl error”要怎么办

### ISSUE THREAD

**Issue by kuimang** [xiaojieonly/Ehviewer_CN_SXJ#1242]
![Screenshot_20240606_185304](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/171930578/698db37c-6500-4bdf-93c4-c26a39923016)
好像只有设置里勾选加载原图以后才会出现，下载会卡在0b/s，然后一会提示下载失败

**Comment by xiaojieonly** [comment]
e站分配的H@H服务器有问题导致的

**Comment by kuimang** [comment]
> e站分配的H@H服务器有问题导致的

麻烦问一下，这种服务器自身问题没法解决是吗？我查了下往期反馈，好像只能取消原图或者反复点下载才行
