### ISSUE TITLE
里站是不是又炸了

### ISSUE THREAD

**Issue by ji336612547** [xiaojieonly/Ehviewer_CN_SXJ#1244]
![Screenshot_20240607_230543](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168664379/ca89cd66-8d94-45d3-8400-867ef7d433a6)

**Comment by ji336612547** [comment]
里站又咋了有没有人知道

**Comment by SnowKala** [comment]
是啊进里站过一会就自动切换成表站了..

**Comment by xiaojieonly** [comment]
用cookie重新登录
