### ISSUE TITLE
大佬能不能加个下载的图片压缩保存成CBZ格式

### ISSUE THREAD

**Issue by X5426X** [xiaojieonly/Ehviewer_CN_SXJ#1249]
类似tachiyomi里的下载保存为CBZ存档功能，这样就不会被其他软件扫描读取出来，避免尴尬
![Screenshot_20240609_113737_eu kanade tachiyomi j2k](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/169754417/3885332e-f6a2-41b8-8737-eb2d23c95a03)

**Comment by xiaojieonly** [comment]
目前没精力搞新的反扫描功能，抱歉
