### ISSUE TITLE
登录问题，和收藏夹问题

### ISSUE THREAD

**Issue by xiaotian-ac** [xiaojieonly/Ehviewer_CN_SXJ#125]
收藏夹转换不了，一直都是默认打开的收藏夹，
       另外用压缩包下载时，明明已经登录，有cookie账号，但仍显示需要登录，
       种子下载时，网盘打开显示文件为空
       大图前几天能打开，也能下载，最近又打不开，且下载进度一直为0

**Comment by DerivativeMarmot** [comment]
> ```
>    收藏夹转换不了，一直都是默认打开的收藏夹，
>    另外用压缩包下载时，明明已经登录，有cookie账号，但仍显示需要登录，
>    种子下载时，网盘打开显示文件为空
>    大图前几天能打开，也能下载，最近又打不开，且下载进度一直为0
> ```

进入收藏夹界面之后，左滑屏幕，会显示其他收藏夹。右上角的爱心能选择默认收藏夹。
你用网盘下载种子？？？一般都用qbittorrent，Deluge, Transmission 什么的
其他的不知道

**Comment by xiaojieonly** [comment]
现在还有问题吗？
