### ISSUE TITLE
下载求助

### ISSUE THREAD

**Issue by Shinokin** [xiaojieonly/Ehviewer_CN_SXJ#1250]
在下一些图片比较多的图库的时候，恢复下载的时候图库都会重头开始下载，之前下载的几百张图都加载不出来，清理缓存也没有用，还有就是更新图库覆盖下载的时候也会重新下载图库，总是会用掉不少配额，该怎么解决呀

**Comment by xiaojieonly** [comment]
是不是开了原图下载？要么是没给权限，图片数据保存不了、读取不了
