### ISSUE TITLE
里站变表站

### ISSUE THREAD

**Issue by SnowKala** [xiaojieonly/Ehviewer_CN_SXJ#1251]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/160128362/9107f774-6dfa-4a7f-8670-db19fb9c727d

重新登录后主页面是里站内容，
但只要过一段时间再刷新就会变成表站内容
且无法再变回里站，只能重新登录。
经过测试，只要点收藏，或者其他选项
也会导致上述情况
已下载画廊可正常下载
igneous不是mystery
请问这是什么情况...

**Comment by SnowKala** [comment]
切了设备也不行，目前看来应该是账号异常（？

**Comment by xiaojieonly** [comment]
我不是很清楚，E站服务器给什么我就展示什么，你可以看看正太和萝莉的tag能不能搜的出来东西，搜的出来就没问题，搜不出来那就是E站把你账号限了
