### ISSUE TITLE
希望当访问父画廊的时候能在APP中下载画廊

### ISSUE THREAD

**Issue by 422-802** [xiaojieonly/Ehviewer_CN_SXJ#1253]
一下全是APP中使用情况。
当画廊更新后，访问父画廊时只有新版本按钮没有下载按钮。
但是少数情况下存在新画廊被上传者故意只上传一张图的情况（画廊无法删除，将原先的图删完后新画廊传一张白图，达成对画廊“删除”的效果）。
此时即使能访问老画廊，依旧无法下载，只有去新画廊的按钮。希望大佬优化一下这一点

**Comment by xiaojieonly** [comment]
E站不支持此功能
