### ISSUE TITLE
关于软件功能问题

### ISSUE THREAD

**Issue by kangkangkkk6** [xiaojieonly/Ehviewer_CN_SXJ#1255]
想问一下这个的功能的具体用法，因为我反复开关几次并没有感觉哪里发生改变，谢谢作者大大解答
![IMG_20240611_034833](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/164253496/53ca91d9-4e5b-455e-8f46-4964077c1eb0)

**Comment by xiaojieonly** [comment]
多标签筛选，开了之后，点击标签会进行多标签搜索
