### ISSUE TITLE
云端收藏夹获取失败与历史记录功能失效

### ISSUE THREAD

**Issue by Nekofur** [xiaojieonly/Ehviewer_CN_SXJ#1256]
出现两个问题，使用最新1.9.8.1版本，已经尝试分别使用直连与VPN，使用具有里站权限CooKie直接登录
1，今天打开本应用，进入收藏页面，查看收藏夹，显示哭泣熊猫头，收藏夹数量仍然正常，退出登录后重新登入，显示哭泣熊猫头以及下方”Err“，收藏夹数量为0，查看其他网站选项显示”请登录“，随后查看账号cookie的igneous变为”mystery“。

2，该版本eh历史记录功能一直无效，打开显示为空白”这里是阅读历史“（一直有这个问题，顺便跟开发者反映一下叭）

**Comment by Nekofur** [comment]
突然好了……完全没有任何操作，只是发完issues不死心就又试了一次，然后就正常了

**Comment by xiaojieonly** [comment]
6
