### ISSUE TITLE
为什么有时配额用的飞快有时却几乎不消耗

### ISSUE THREAD

**Issue by RebirthDAN** [xiaojieonly/Ehviewer_CN_SXJ#1257]
铜星用户，挂梯使用，有时配额光是浏览几个本子就已经一万了，有时下载好几本却采用了几百配额（配额几乎是以个位数增长），是跟host或者H@H有关系吗？体感觉得host能用的时候配额用的会慢，并且不同节点有时也会影响配额的消耗速度，H@H开的是auto-detected

**Comment by xiaojieonly** [comment]
我不是很清楚，抱歉

**Comment by xiaojieonly** [comment]
用cookie重新登录下试试
