### ISSUE TITLE
Android 14出现恶意代码

### ISSUE THREAD

**Issue by YaeSakura0911** [xiaojieonly/Ehviewer_CN_SXJ#1259]
![Screenshot_20240606_095636_Smart Manager](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/26689532/4f32db1d-d117-4fc8-9790-73dcf79e650f)
打开软件时会提示发现恶意代码，在线支付时也会提示安全风险

**Comment by YaeSakura0911** [comment]
发现作者对类似回复并不友好，姑关闭该issue

**Comment by YaeSakura0911** [comment]
发现作者对类似回复并不友好，故关闭该issue

**Comment by UjuiUjuMandan** [comment]
境外软件“Ehviewer”包含恶意代码，会窃取用户个人信息、散布反动水印宣传、使用户的手机成为“挖矿僵尸”。强烈建议工信部下架此非法应用。@中央网信办 @平安浙江
