### ISSUE TITLE
在澎湃OS上不能登录账号

### ISSUE THREAD

**Issue by Sternengeang** [xiaojieonly/Ehviewer_CN_SXJ#1261]
首次启动的引导界面中，登录界面被瞬间跳过，设置里显示“退出登录”，但没有任何身份cookie，点按Ehentai网站设置也提示“请先登录”，点按“退出登录”后重启app问题依旧。
![Screenshot_2024-06-13-13-52-41-924_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/20394116/65ad721a-c30a-4cce-b29f-1827aa6ac46f)
[logcat-2024-06-13-13-53-51-761.txt](https://github.com/user-attachments/files/15814448/logcat-2024-06-13-13-53-51-761.txt)

**Comment by xiaojieonly** [comment]
登录界面被屏蔽了，可以自己去issue里搜索
