### ISSUE TITLE
閱讀歷史無法記錄

### ISSUE THREAD

**Issue by zzz89915** [xiaojieonly/Ehviewer_CN_SXJ#1265]
好像從前幾個版本開始就開始有這個問題了
不管點進哪個畫廊都不會有閱讀紀錄
不知道是不是只有我有這個問題
還望大佬可以告知一下解決辦法謝謝
![Screenshot_20240614_172408_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/123270319/fda97a31-57f7-41aa-a39a-c5066573f187)

**Comment by FengTeLai** [comment]
在设置—EH—历史记录数量。那里设置一下，再试试

**Comment by zzz89915** [comment]
> 在设置—EH—历史记录数量。那里设置一下，再试试

解決了，原來還有一個這個設置，感謝🥰
