### ISSUE TITLE
[氵]  toast通知“好痛”

### ISSUE THREAD

**Issue by aw59** [xiaojieonly/Ehviewer_CN_SXJ#1270]
在清空应用数据之后打开应用的瞬间退出到桌面可以稳定复现

这算是什么，彩蛋吗，指的是什么“好痛”🫣

![Screenshot_20240616-200753](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/70953327/6b8a66bb-ea94-498c-9b9c-b3237c719ab3)
![mmexport1718539430217](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/70953327/06a7fc86-a7bc-4e50-b308-b9ad2a9d32d3)

**Comment by xiaojieonly** [comment]
权限申请被拒了
