### ISSUE TITLE
已下载完成的画廊会有概率出现单页解码失败的情况

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#1271]
在不翻墙的情况，下载的画廊会有这种解码失败的情况发生，想要解决的话就得翻墙，然后重新进入APP，点进该画廊，选择解码失败的单页就进行刷新，完成重新下载。
问题是，一些解码失败的单页在通过这种方式刷新下载完成后，在下次登上APP打开时，它又会解码失败。
而且有这种解码失败的单页的画廊还不能通过“全选+下载”的方式筛选出来，从下载列表的页面看，它们都是“已完成”……

**Comment by xiaojieonly** [comment]
正常情况，偶发，多半是亚洲H@H服务器问题
