### ISSUE TITLE
希望作者大大能增加一个分页显示功能

### ISSUE THREAD

**Issue by stereoorange** [xiaojieonly/Ehviewer_CN_SXJ#1272]
有些tag下作品较多，有时候想找一些老作品看就要翻页很久，可否增加一个类似网页e站的作品分页显示功能，或是增加根据发布时间搜索的搜索选项？
本人对网络编程不了解，只是作为一个建议，如果作者大大无意添加该功能或落实起来较为麻烦请无视该想法。

**Comment by xiaojieonly** [comment]
已经有了
