### ISSUE TITLE
历史记录不见了

### ISSUE THREAD

**Issue by Fullary** [xiaojieonly/Ehviewer_CN_SXJ#1275]
浏览了多少都没有历史记录，以前也没删过，上上上个版本之后就没有了。
![Screenshot_2024-06-21-10-16-44-026_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118233202/63c2677d-684b-49ce-8743-88b64fbd0eaa)

**Comment by mo-han** [comment]
同样问题，但是和版本无关。我一直开着自动更新，当前版本也用了一段时间了。前几天还用过“历史”版块，功能正常，但今天发现历史页面全空。

**Comment by xiaojieonly** [comment]
设置里重新设置一下
