### ISSUE TITLE
怎么注册账号，总显示菜单被禁用


### ISSUE THREAD

**Issue by ldh243110** [xiaojieonly/Ehviewer_CN_SXJ#1276]

**Comment by ldh243110** [comment]
![Screenshot_2024-06-22-20-34-00-047_com.android.browser.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168818299/dfe368fb-10e8-4455-9136-c70df56ab630)

![Screenshot_2024-06-22-20-33-44-103_com.android.browser.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/168818299/c42062db-33fb-469f-91a2-3635cbe75110)

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11
