### ISSUE TITLE
切换到里站打不开，同账号同网络在电脑能打开里站。

### ISSUE THREAD

**Issue by dev44il** [xiaojieonly/Ehviewer_CN_SXJ#1279]
打开app里站打不开，也没有提示，切换表站能打开。同个网络同个账号在电脑能打开里站。
![Screenshot_2024-06-25-17-41-51-012_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/173788335/09076b8e-f731-4f2f-acae-cad62e3b233c)

**Comment by dev44il** [comment]
> 打开app里站打不开，也没有提示，切换表站能打开。同个网络同个账号在电脑能打开里站。 ![Screenshot_2024-06-25-17-41-51-012_com xjs ehviewer](https://private-user-images.githubusercontent.com/173788335/342672597-09076b8e-f731-4f2f-acae-cad62e3b233c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDg5ODEsIm5iZiI6MTcxOTMwODY4MSwicGF0aCI6Ii8xNzM3ODgzMzUvMzQyNjcyNTk3LTA5MDc2YjhlLWY3MzEtNGYyZi1hY2FlLWNhZDYyZTNiMjMzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwOTQ0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTc5ODdiODQxOTRhZGFlZjI4MDliOWM1YzVlZjUyZjE3NDRkYjRlODI5YzU3ODUzYTMzOTMwNWFlYTBmNWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tq2WZ_ZB8SN0w5GMyRAwXpdiLQrcTUVnIqf-oIUz664)

![Uploading IMG_20240625_174417.jpg…]()

**Comment by baiyunlong0525** [comment]
我也是，昨天晚上用着用着突然就不能访问了。

**Comment by xiaojieonly** [comment]
手机端cookie过期了，用cookie重新登录下

**Comment by baiyunlong0525** [comment]
好使，NB。又可以上班摸鱼了
