### ISSUE TITLE
读写权限相关问题优化

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#1282]
近期发现很多用户出现下载的本子无法查看，交流后发现大多数均为本APP会被判定为风险APP，容易被系统收回APP的权限从而导致无法读取，建议只使用 文档 来授权下载目录(或者在发现APP丢失读写权限后提示用户打开权限/用文档重新授权，当然也可以把默认下载位置改为应用文件目录的，但会不方便管理)

**Comment by xiaojieonly** [comment]
有没有一种可能，系统压根不告诉我没有权限
