### ISSUE TITLE
里站用不了了，退出想重新登陆这样了这么回事

### ISSUE THREAD

**Issue by ji336612547** [xiaojieonly/Ehviewer_CN_SXJ#1283]
![Uploading Screenshot_20240628_215004.jpg…]()

**Comment by fantasysimulation** [comment]
我里站也忽然用不了了，换了时点和按之前的解决方法去弄也不行。

**Comment by fantasysimulation** [comment]
> 我那里也突然用不了了，换了时点后按了原来的解决方法也不起作用。

现在是网页里站登的进去，应用的里站还是哭泣安卓头

**Comment by xiaojieonly** [comment]
用cookie重新登录
