### ISSUE TITLE
阅读历史完全消失

### ISSUE THREAD

**Issue by fengya-wang** [xiaojieonly/Ehviewer_CN_SXJ#1284]
以前的阅读历史和最新的阅读都没法进入到阅读历史中
![Screenshot_2024-06-29-16-36-05-167_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/174177555/36a194fd-0dbe-4772-af47-1a76f29680f9)

**Comment by 2911894613** [comment]
设置里改一下就好了
eh-历史记录数量
