### ISSUE TITLE
下载后看不了

### ISSUE THREAD

**Issue by 2911894613** [xiaojieonly/Ehviewer_CN_SXJ#1285]
如题，下载一些大一点的本子，一页十几兆的那种，下载完成后看不了，点进去图片一直转圈。在本地文件里找到下载的文件夹，发现图片其实已经下载成功了，但在eh里就是看不了

**Comment by 2911894613** [comment]
捐赠银星下载的原图。挂着梯子网络也很稳定，一秒几兆下完的中间没卡顿。难道说eh不能看很大的图片吗，在外面下载的图片是能看的

**Comment by xiaojieonly** [comment]
存储权限没给

**Comment by 2911894613** [comment]
> 存储权限没给

我下载小的图片，在eh里是可以看的。就是某些本子有点大看不了，这也是没存储权限吗？

**Comment by xiaojieonly** [comment]
大多数情况下是的
