### ISSUE TITLE
希望能增加一个自动翻页功能

### ISSUE THREAD

**Issue by Assiby11125** [xiaojieonly/Ehviewer_CN_SXJ#1286]
就像picacg的那样，可以看差分方便一点

**Comment by Steve-337** [comment]
阅读右下角悬浮按钮就是![Screenshot_2024-07-01-19-44-15-498_com.xjs.ehviewer-edit.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/f5bdc0fc-4b1c-40e2-b1c9-63db3489cf3c)
