### ISSUE TITLE
最新版闪退好几次了

### ISSUE THREAD

**Issue by jay00128** [xiaojieonly/Ehviewer_CN_SXJ#1289]
暂时用回6月版了
[crash-2024-07-01-20-12-34-829.log](https://github.com/user-attachments/files/16052984/crash-2024-07-01-20-12-34-829.log)
[crash-2024-07-01-20-13-56-425.log](https://github.com/user-attachments/files/16052987/crash-2024-07-01-20-13-56-425.log)

**Comment by xiaojieonly** [comment]
1.9.8.4修了
