### ISSUE TITLE
归档下载相关问题

### ISSUE THREAD

**Issue by ChXWu** [xiaojieonly/Ehviewer_CN_SXJ#1292]
使用三星OneUI 6.1，首先感谢作者的工作。

最近我发现部分gallary会出现归档失败，调了adb看了下
archiver的下载路径是：`/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ `这个似乎是自动生成的，不可修改

1. 比如说我有这个一个档案`[Kenja Time (MANA)] Gentle Connect! Re:Dive 2 'Amakuchi' (Princess Connect! Re:Dive) [Chinese] [从本子了解公主连结&reoltora个人重嵌] [Decensored] [Digital].zip`,（gid2162994）
那么下载文件的绝对路径`/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/[Kenja Time (MANA)] Gentle Connect! Re:Dive 2 'Amakuchi' (Princess Connect! Re:Dive) [Chinese] [从本子了解公主连结&reoltora个人重嵌] [Decensored] [Digital].zip`路径长度就会超过255字符导致**下载失败。**
2. 如果是个奇怪的包含“/”的名字, 比如`[Kenja Time (MANA)] Fate/Gentle Order 5 (Fate/Grand Order) [Decensored] [Digital].zip`(gid2569094), 那么结果目录会被拆成三级`[Kenja Time (MANA)] Fate`，`Gentle Order 5 (Fate`，`Grand Order) [Decensored] [Digital].zip`，下载成功了，但是**下载记录和download文件中可以预料的没有出现**
3. 另外一些情况我就不太理解了，比如我在下载gid1905632的时候，下载成功了，**下载记录和download文件中也不会出现**

首先，我看见`/storage/emulated/0/`已经会自动生成EhViewer文件夹了，里面也会有archiver，temp，data等等文件夹产生（但是archiver只有文件夹没有数据），仍然在使用andriod/data下的archiver这是故意设计还是OneUI的bug？

其次下载的zip文件中存在包含`/`的情况，这个是linux整体的问题，应该有解决手段？比如提前重命名？

**Comment by xiaojieonly** [comment]
1，我研究一下

**Comment by baiyingui** [comment]
我也遇到类似的问题，使用归档下载时，会有部分本子只能得到一个压缩包，但绿e软件内的档案分区无法将其读出，比如这个https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法读出，中途也试着归档下载了其他本子，都可以正常被app读出，且正常归类至档案分区。

**Comment by xiaojieonly** [comment]
> 我也遇到类似的问题，使用归档下载时，会有部分本子只能得到一个压缩包，但绿e软件内的档案分区无法将其读出，比如这个[https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法读出，中途也试着归档下载了其他本子，都可以正常被app读出，且正常归类至档案分区。](https://exhentai.org/g/3048365/c183b45caf/%EF%BC%8C%E5%BD%92%E6%A1%A3%E4%BA%863%E6%AC%A1%E5%A7%8B%E7%BB%88%E6%97%A0%E6%B3%95%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%AD%E9%80%94%E4%B9%9F%E8%AF%95%E7%9D%80%E5%BD%92%E6%A1%A3%E4%B8%8B%E8%BD%BD%E4%BA%86%E5%85%B6%E4%BB%96%E6%9C%AC%E5%AD%90%EF%BC%8C%E9%83%BD%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%A2%ABapp%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%94%E6%AD%A3%E5%B8%B8%E5%BD%92%E7%B1%BB%E8%87%B3%E6%A1%A3%E6%A1%88%E5%88%86%E5%8C%BA%E3%80%82)

新开个issue

**Comment by xiaojieonly** [comment]
> 使用三星OneUI 6.1，首先感谢作者的工作。
> 
> 最近我发现部分gallary会出现归档失败，调了adb看了下 archiver的下载路径是：`/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ `这个似乎是自动生成的，不可修改
> 
> 1. 比如说我有这个一个档案`[Kenja Time (MANA)] Gentle Connect! Re:Dive 2 'Amakuchi' (Princess Connect! Re:Dive) [Chinese] [从本子了解公主连结&reoltora个人重嵌] [Decensored] [Digital].zip`,（gid2162994）
>    那么下载文件的绝对路径`/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/[Kenja Time (MANA)] Gentle Connect! Re:Dive 2 'Amakuchi' (Princess Connect! Re:Dive) [Chinese] [从本子了解公主连结&reoltora个人重嵌] [Decensored] [Digital].zip`路径长度就会超过255字符导致**下载失败。**
> 2. 如果是个奇怪的包含“/”的名字, 比如`[Kenja Time (MANA)] Fate/Gentle Order 5 (Fate/Grand Order) [Decensored] [Digital].zip`(gid2569094), 那么结果目录会被拆成三级`[Kenja Time (MANA)] Fate`，`Gentle Order 5 (Fate`，`Grand Order) [Decensored] [Digital].zip`，下载成功了，但是**下载记录和download文件中可以预料的没有出现**
> 3. 另外一些情况我就不太理解了，比如我在下载gid1905632的时候，下载成功了，**下载记录和download文件中也不会出现**
> 
> 首先，我看见`/storage/emulated/0/`已经会自动生成EhViewer文件夹了，里面也会有archiver，temp，data等等文件夹产生（但是archiver只有文件夹没有数据），仍然在使用andriod/data下的archiver这是故意设计还是OneUI的bug？
> 
> 其次下载的zip文件中存在包含`/`的情况，这个是linux整体的问题，应该有解决手段？比如提前重命名？

已尝试修复，下一版更新，如果还是不行，请重新打开此issue
