### ISSUE TITLE
大佬求加入功能

### ISSUE THREAD

**Issue by s0me0nels** [xiaojieonly/Ehviewer_CN_SXJ#1293]
大佬我是上次求加入下载列表随机打开的人，很抱歉麻烦您，但能不能请您加入阅读时可以看到该画廊名字或者id的功能，方便在随机打开后遇到不合口味的能够找到对应画廊并删除。尤其是图集类的画廊由于没有封面真的找不到名字qAq

**Comment by xiaojieonly** [comment]
再说吧
