### ISSUE TITLE
已下载本子本地内容完整却要重新下载

### ISSUE THREAD

**Issue by decayici** [xiaojieonly/Ehviewer_CN_SXJ#1295]
全选下载列表，点击开始下载，在所有本子均显示已下载的前提下，大部分本子正常，但有部分本子要重新下载，之后经检查，本地文件里该本子所有图片完整，但是下载列表里面显示仍要重新下载
请问如何解决?系统为安卓10，大部分本子正常，应该不存在权限问题。

**Comment by decayici** [comment]
没有更换手机，更换目录等任何其他操作

**Comment by decayici** [comment]
刚才看着本子重新下载完，弹出已完成，再点开又要重新下载了

**Comment by xiaojieonly** [comment]
删除后重新下载，我在排查了

**Comment by decayici** [comment]
兄弟，已经反复删除多次下载列表了，不管是只删除下载列表，还是文件列表一起删除都试过了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月4日(周四) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 已下载本子本地内容完整却要重新下载 (Issue #1295)




 
删除后重新下载，我在排查了
