### ISSUE TITLE
小米11下载归档时崩溃

### ISSUE THREAD

**Issue by EnderAvaritia** [xiaojieonly/Ehviewer_CN_SXJ#1296]
小米11在使用1.9.8.4下载归档时应用崩溃
以下是崩溃之后点导出日志获得的日志
[logcat-2024-07-04-15-38-56-091.txt](https://github.com/user-attachments/files/16095210/logcat-2024-07-04-15-38-56-091.txt)

**Comment by xiaojieonly** [comment]
日志显示是权限不足导致无法创建文件，从而导致的奔溃，你要不检查一下权限？

**Comment by EnderAvaritia** [comment]
![Screenshot_2024-07-05-11-33-59-541_com.miui.securitycenter.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/84321282/e07f3b57-ec7d-4d4b-a512-bc8a11fb5f1e)

看着应该没问题，更新后没有提示需求更多权限，更新前无崩溃问题

![logcat-2024-07-05-11-35-23-290.txt](https://github.com/user-attachments/files/16104559/logcat-2024-07-05-11-35-23-290.txt)

今天凌晨还崩了一次

**Comment by EnderAvaritia** [comment]
> 日志显示是权限不足导致无法创建文件，从而导致的奔溃，你要不检查一下权限？

刚刚下载又崩了数次，我确信开了存储权限了，先换回1.9.8.1试试
[logcat-2024-07-05-22-12-24-091.txt](https://github.com/user-attachments/files/16110723/logcat-2024-07-05-22-12-24-091.txt)

**Comment by xiaojieonly** [comment]
好的，是不是归档下载的时候页面处于下载列表，然后就奔溃了？
如果是的话那这个问题我修好了

**Comment by EnderAvaritia** [comment]
> 好的，是不是归档下载的时候页面处于下载列表，然后就奔溃了？
> 如果是的话那这个问题我修好了

没看懂什么叫页面处于下载列表
不过估计是吧？我相信大佬的定位能力

**Comment by PATPATPATPON** [comment]
您好，我在上大学中，无法亲自回复您的邮件。我将在放假后，尽快给您回复。

**Comment by xiaojieonly** [comment]
> > 好的，是不是归档下载的时候页面处于下载列表，然后就奔溃了？
> > 如果是的话那这个问题我修好了
> 
> 没看懂什么叫页面处于下载列表 不过估计是吧？我相信大佬的定位能力

好的，你是想尽快更新，还是等到八月份和其他的修复和功能一起更新？

**Comment by EnderAvaritia** [comment]
> > > 好的，是不是归档下载的时候页面处于下载列表，然后就奔溃了？
> > > 如果是的话那这个问题我修好了
> > 
> > 没看懂什么叫页面处于下载列表 不过估计是吧？我相信大佬的定位能力
> 
> 好的，你是想尽快更新，还是等到八月份和其他的修复和功能一起更新？

按大佬的计划来吧，我回滚一个版本之后用的很好，没发现什么问题，目前不急

**Comment by xiaojieonly** [comment]
好的

**Comment by xiaojieonly** [comment]
> > > > 好的，是不是归档下载的时候页面处于下载列表，然后就奔溃了？
> > > > 如果是的话那这个问题我修好了
> > > 
> > > 
> > > 没看懂什么叫页面处于下载列表 不过估计是吧？我相信大佬的定位能力
> > 
> > 
> > 好的，你是想尽快更新，还是等到八月份和其他的修复和功能一起更新？
> 
> 按大佬的计划来吧，我回滚一个版本之后用的很好，没发现什么问题，目前不急

这个issue我先关闭了，如果到时候新版还有问题，可以重新打开
