### ISSUE TITLE
有些画廊无法搜索

### ISSUE THREAD

**Issue by 0552684** [xiaojieonly/Ehviewer_CN_SXJ#1297]
有些画廊无法通过搜索跳转，比如这个画廊  https://exhentai.org/g/2264511/60ff7fbb82/

这个画廊可以通过链接和收藏来查看，但是不管是搜索标题还是相似搜索或者搜索作者都没办法搜出来。

![Screenshot_2024-07-07-06-54-15-70_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/172019510/da6d63ad-f99b-489c-b486-d311af6dcad9)
![Screenshot_2024-07-07-06-54-12-39_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/172019510/4f30acbf-657e-4fe9-b218-20374c4011ba)
![Screenshot_2024-07-07-06-54-39-14_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/172019510/13ed2f61-fdd0-4263-bdb3-926bdcdc59b6)

不知道这个是个bug还是别的什么？能修复这个问题吗？

**Comment by xiaojieonly** [comment]
E站分配给你的H@H服务器有问题

**Comment by 0552684** [comment]
> E站分配给你的H@H服务器有问题

那这种需要怎么解决？我新弄一个账号吗？
