### ISSUE TITLE
内置hosts超时 挂梯子也进不去

### ISSUE THREAD

**Issue by q55876045** [xiaojieonly/Ehviewer_CN_SXJ#13]
自定义hosts ul.ehgt.org  94.100.24.82超时
换梯子关内置也进不去
![Screenshot_20201129-040310_EhViewer](https://user-images.githubusercontent.com/30213412/100524992-ff9b8f00-31f7-11eb-9bfe-20ab71da5963.jpg)

**Comment by xiaojieonly** [comment]
> 自定义hosts ul.ehgt.org 94.100.24.82超时
> 换梯子关内置也进不去
> ![Screenshot_20201129-040310_EhViewer](https://user-images.githubusercontent.com/30213412/100524992-ff9b8f00-31f7-11eb-9bfe-20ab71da5963.jpg)

关了梯子试试？或者关了host然后再挂梯子试试

**Comment by xiaojieonly** [comment]
最新版我host修复了

**Comment by q55876045** [comment]
两个方法我都试过了，换手机好像就能解决，我也不知道啥原理。。。

**Comment by asdasd1dsadsa** [comment]
我的情况是eh能上ex不能上。后来去ip测速找到真实ex站ip，填到自定义hosts就行了。此刻我填的是178.175.128.252

**Comment by q55876045** [comment]
我也是一样的情况，能请问下怎么看ip测速的真实ex的ip，我也用过别人给的ex站hosts，但是没用。我这边是电信的网络呢

**Comment by q55876045** [comment]
解决问题了，谢谢提供可用IP地址的老哥。
