### ISSUE TITLE
关于归档的建议

### ISSUE THREAD

**Issue by nyanpasunyan** [xiaojieonly/Ehviewer_CN_SXJ#1300]
遇见的问题：最近APP的普通下载出现错误的几率比以前增加了很多，出错和就会停止下载，于是就会需要不得不多次重复去再开始那些出错的下载任务。

建议：鉴于归档比普通下载要稳定的多，而且不会占用梯子的gp配额，归档的用处会越来越大，所以希望把归档下来的本子整合进下载当中，让归档文件也能和普通下载的本子一样直接浏览。

**Comment by xiaojieonly** [comment]
下载列表有专门的归档分组

**Comment by nyanpasunyan** [comment]
> 下载列表有专门的归档分组
谢谢大大的回复。目前可以归档，但只是单纯的下载，下载完之后不会显示在APP之中，要另外找到后单独打开。
大大，我的意思是，让归档也能像普通下载一样，下载下来之后直接显示在APP中，能像普通下载那样可以分类可以检索。
大大可以参考一下jhentai这款APP。
![Screenshot_20240709-103410](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/106543457/971c351f-56a5-4ac7-a584-291a024e1e76)
