### ISSUE TITLE
归档下载之后不会出现在下载列表当中

### ISSUE THREAD

**Issue by nyanpasunyan** [xiaojieonly/Ehviewer_CN_SXJ#1301]
问题：归档下载之后不会出现在下载列表当中。

建议：希望能把归档单独做一套类似目前普通爬图下载的界面，方便管理下载进度以及下载之后的阅读。

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/106543457/9fe0afa4-5e93-4996-a7f4-169f7311242a

**Comment by xiaojieonly** [comment]
下载列表里有一个归档分组，从屏幕右边划出来可以看到

**Comment by xiaojieonly** [comment]
> 下载列表里有一个归档分组，从屏幕右边划出来可以看到

你这有bug啊

**Comment by xiaojieonly** [comment]
你app关了重新打开下载列表看看

**Comment by xiaojieonly** [comment]
什么手机？安卓几？

**Comment by nyanpasunyan** [comment]
> 你app关了重新打开下载列表看看

谢谢大大，关了重开就解决了。
期待大大以后有空了能在归档里面增加一些分类就更好了。

**Comment by nyanpasunyan** [comment]
> 你app关了重新打开下载列表看看

重新测试了好几次，发现几个新问题。
1,归档下载基本稳定，偶尔会出现点了归档但是完全没反应的问题。
2,这个比较严重，归档下载完经常不会出现下载列表里面，出不出现完全随机，目前还在测试。
3，归档下载完以后，无论本子出不出现在下载列表里面，压缩包都会被保留，而且APP里没有删除归档压缩包的手段。并且压缩包时保存在Android/date文件夹内，普通用户就算用其他文件浏览APP也无法访问到这个文件夹，基本等于没法删除。
4，手机和平板的性能完全足够的情况下（骁龙8+）在浏览超过100页本子的缩略图的时候，非常卡，体感在10帧以下。

**Comment by nyanpasunyan** [comment]
> 什么手机？安卓几？

有一台三星note10➕，安卓12，骁龙855，浏览缩略图不卡。
还有两台平板，一台骁龙8➕，安卓13，浏览缩略图（超过100页时）非常卡。
另外一台平板，骁龙870，安卓13，浏览缩略图不卡。

**Comment by nyanpasunyan** [comment]
> 你app关了重新打开下载列表看看

测试了之后又发现一些问题。

问题：1，归档的本子文件夹中，有一些只要图片文件，缺少.ehviewer和.thumb文件。要手动APP内打开下载的本子一次才会出现这2文件。

问题：2，使用恢复下载只能恢复下载列表中默认分类中的本子，其他全部丢失（即使那些本子还在原来的位置）。

**Comment by xiaojieonly** [comment]
好的，我优化一下，下一版一起更新

**Comment by xiaojieonly** [comment]
> > 什么手机？安卓几？
> 
> 有一台三星note10➕，安卓12，骁龙855，浏览缩略图不卡。 还有两台平板，一台骁龙8➕，安卓13，浏览缩略图（超过100页时）非常卡。 另外一台平板，骁龙870，安卓13，浏览缩略图不卡。

这应该是平板的问题

**Comment by nyanpasunyan** [comment]
> > > 什么手机？安卓几？
> > 
> > 
> > 有一台三星note10➕，安卓12，骁龙855，浏览缩略图不卡。 还有两台平板，一台骁龙8➕，安卓13，浏览缩略图（超过100页时）非常卡。 另外一台平板，骁龙870，安卓13，浏览缩略图不卡。
> 
> 这应该是平板的问题

之前有过其他手机，也是同样问题，超过50张到100张预览图时就会非常卡，并且这个问题已经存在过很多个版本之中了（至少有1年以上）。

**Comment by xiaojieonly** [comment]
为什么呀？我手机上用着很流畅啊，是不是网卡导致的？

**Comment by nyanpasunyan** [comment]
> 为什么呀？我手机上用着很流畅啊，是不是网卡导致的？


我很确定不是网络导致的。我附上一个视频大大可以看一看，大约50张缩略图以内很流畅，超过之后就会越来越卡。

以下是对先发现问题和之前发现问题测试之后的报告：

1，与网络有关的是缩略图加载的问题，这也是昨晚发现的。很久以前eh就会出现缩略图加载慢，甚至一直加载不出来的问题，但是直接点进去看又加载很快，直到昨天我下载了一个彩色的eh，发现彩e设置，高级，当中有一个激进地加载缩略图的功能，打开后可以改善缩略图加载不出来的问题，如果可以的话，希望大大可以参考一下彩e来解决缩略图加载的问题。https://github.com/Ehviewer-Overhauled/Ehviewer

2，关于归档之后会有很大几率不会出现在下载列表中的问题，我对比了另外一个类似功能的app，jhentai同样的功能，发现jh是直接app内下载，从来没有这个问题，eh是调用外部下载器，不仅归档之后会有很大几率不会出现在下载列表中的问题，然后下载之后无法删除压缩包，还会出现不手动点开下载完的本子一次，就缺少.ehviewer和.thumb文件的问题。希望大大也能参考一下jh来找到解决问题的办法。https://github.com/jiangtian616/JHenTai

3，关于大大的eh中恢复下载项功能只会恢复下载列表中默认分类中的内容的问题，我对比了jh的本子信息文件（类似大大的.ehviewer文件），jh信息文件中多了一个下载列表分类的信息，不知道是不是因为缺少这个信息导致恢复下载项的问题。


https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/106543457/48a344a1-c002-4d32-b7b5-8d05f9c7b648

**Comment by xiaojieonly** [comment]
哦，个人建议在E站设置里把预览的相关设置设为默认值，然后进入专门的预览页，浏览所有略缩图

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/6be4f12d-095c-4e5f-9fe0-cc02f6940406)
