### ISSUE TITLE
加载图片多次出现解码失败

### ISSUE THREAD

**Issue by zhudalai** [xiaojieonly/Ehviewer_CN_SXJ#1306]
![Screenshot_2024-07-10-16-47-52-126_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/132544562/02355ecd-8813-4145-aedd-c43a36b75f79)

**Comment by xiaojieonly** [comment]
E站分配的H@H服务器不稳定导致的，如果开启了原图显示，请尝试关闭原图显示
