### ISSUE TITLE
里站网络异常

### ISSUE THREAD

**Issue by gugualaolian** [xiaojieonly/Ehviewer_CN_SXJ#1307]
7月九日晚上开始，表站可进，里站直接网络异常，不管是WiFi还是流量都无法进入。
开关安全DNS和使用备用手机也没用。
但是我翻到墙外（测试使用巴黎节点）就能进里站。
这是我号有问题，还是我们地区网络的问题。

**Comment by xiaojieonly** [comment]
用cookie重新登录

**Comment by UjuiUjuMandan** [comment]
@xiaojieonly cookie 失效会什么都不显示，而不是显示网络错误。

**Comment by UjuiUjuMandan** [comment]
@gugualaolian @0310kk @1acte @wavewavewing @Aurora-JG-Lun

目前软件中的 hosts 中 exhentai.org 的 IP 有如下，请检查能否**直连**直接用浏览器打开。

- https://178.175.128.252
- https://178.175.129.252
- https://178.175.129.254
- https://178.175.128.254
- https://178.175.132.20
- https://178.175.132.22

正常情况下，打开后浏览器会立即提示不安全，请告诉我能否看到这个提示。

**Comment by 0310kk** [comment]
使用的是手机，六个IP情况都一样，


1、在邮箱里直接打开链接显示ERR_CONNECTION_REFUSED，


2、复制后直接使用edge浏览器打开，搜索引擎试过必应和百度，也用Chrome浏览器试过，情况一样，直接打开是
【嗯… 无法访问此页面178.175.128.254 已拒绝连接。
请尝试：
检查连接
ERR_CONNECTION_REFUSED】，


3、挂了梯子（梯子状况良好，可以通过域名在浏览器秒开里站）后，先是【你的连接不是专用连接
攻击者可能试图从 178.175.128.254 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_COMMON_NAME_INVALID】，


之后继续高级打开，显示【此服务器无法证明它是 178.175.128.252；它的安全证书来自 *.exhentai.org。这可能是由错误配置或者有攻击者截获你的连接而导致的。


继续访问 178.175.128.252 (不安全)】，
继续访问后，
【Error 404 Not Found
Not Found


Guru Meditation:
XID: 120913400


Varnish cache server】，




另外，完全卸载ehviewer，重新安装最新版后，在登录界面，使用密码登录会直接提示登录失败，网络错误，使用网页登录则是net::ERR_CONNECTION_TIMED_OUT，挂梯子也一样情况，只能通过cookie登录，


下载彩版ehviewer后，原本也无法使用exhentai画廊节点，在设置里把http引擎从OKhttp换成cronet之后，就可以正常使用里站节点了，



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年7月27日(周六) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 里站网络异常 (Issue #1307)




 
@gugualaolian @0310kk @1acte @wavewavewing @Aurora-JG-Lun
 
目前软件中的 hosts 中 exhentai.org 的 IP 有如下，请检查能否直连直接用浏览器打开。
  
https://178.175.128.252
 
https://178.175.129.252
 
https://178.175.129.254
 
https://178.175.128.254
 
https://178.175.132.20
 
https://178.175.132.22
  
正常情况下，打开后浏览器会立即提示不安全，请告诉我能否看到这个提示。

**Comment by UjuiUjuMandan** [comment]
@0310kk

能否透露一下您所在的省份？或者仅告诉我是否是浙江？

请直连打开 https://ipinfo.io/ 并告诉我 org 这行显示什么？这是您的网络运营商。

请尝试以下 IP 是否能正常显示不安全：

- https://178.175.128.251
- https://178.175.128.253
- https://178.175.129.251
- https://178.175.129.253
- https://178.175.132.19
- https://178.175.132.21

**Comment by 0310kk** [comment]
并不是浙江，org：AS9808 China Mobile Communications Group Co., Ltd.


六个IP，现在手机通过edge浏览器直接打开和挂梯子打开的情况都一样，




你的连接不是专用连接
攻击者可能试图从 178.175.128.253 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_COMMON_NAME_INVALID






此服务器无法证明它是 178.175.128.253；它的安全证书来自 *.exhentai.org。这可能是由错误配置或者有攻击者截获你的连接而导致的。
继续访问 178.175.128.253 (不安全)




继续访问
Error 404 Not Found
Not Found


Guru Meditation:
XID: 181593452


Varnish cache server，




另外突然想起来，关于ehviewer的配额问题，有时候没有挂梯子，直接使用流量打开APP后，两次间隔时间完全足够配额恢复，正常已用配额应该是0，但发现配额会显示已被使用一部分，几千，几百都有，这是什么原因呢？



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年7月27日(周六) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 里站网络异常 (Issue #1307)




 
@0310kk
 
能否透露一下您所在的省份？或者仅告诉我是否是浙江？
 
请直连打开 https://ipinfo.io/ 并告诉我 org 这行显示什么？这是您的网络运营商。
 
请尝试以下 IP 是否能正常显示不安全：
  
https://178.175.128.251
 
https://178.175.128.253
 
https://178.175.129.251
 
https://178.175.129.253
 
https://178.175.132.19
 
https://178.175.132.21

**Comment by UjuiUjuMandan** [comment]
我看到很多发帖子的IP属地是浙江。

上面几位也麻烦提供相同的信息。

@0310kk 可能是因为这个IP不只你一个人在用和上E站。

**Comment by 0310kk** [comment]
未挂梯子的流量IP也是公用的吗？这种配额被使用的情况是不是有可能存在e站账号被盗用的问题？有没有办法避免这种情况？



---原始邮件---
发件人: "ᡠᠵᡠᡳ ᡠᠵᡠ ***@***.***&gt;
发送时间: 2024年7月27日(周六) 晚上7:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 里站网络异常 (Issue #1307)




 
我看到很多发帖子的IP属地是浙江。
 
上面几位也麻烦提供相同的信息。
 
@0310kk 可能是因为这个IP不只你一个人在用和上E站。

**Comment by UjuiUjuMandan** [comment]
@0310kk 当然了，不然IPv4那么少，怎么可能一户一个IP。不存在。捐赠20美元，这样配额就跟着你账号走而不是IP了。

https://ehwiki.org/wiki/Donation/Chinese#.E4.B8.80.E6.AC.A1.E6.80.A7.E5.A0.B1.E9.85.AC
