### ISSUE TITLE
新功能请求 是否可以使得在下载界面里面的那个能搜索所有的分类

### ISSUE THREAD

**Issue by EnderAvaritia** [xiaojieonly/Ehviewer_CN_SXJ#1309]
下载分了十几个分类，每个里面都有几十部漫画，想找一部漫画实在糟心，是否可以使得下载界面里面那个搜索可以搜索所有的漫画
话说下载界面那个搜索是不是大小写敏感阿，是否可以忽略大小写？

**Comment by xiaojieonly** [comment]
目前不能，后面会优化一下
