### ISSUE TITLE
音量鍵翻頁問題

### ISSUE THREAD

**Issue by Chromartha** [xiaojieonly/Ehviewer_CN_SXJ#1310]
首先感謝作者的辛勞，這邊使用的Viewer版本是1.9.8.4，運行環境為Android14

這個問題很久以前就存在了
在打開下載的圖庫後如果直接使用音量鍵翻頁會在翻了3頁之後跳回剛進入的頁面並無限循環
目前解法是要先自己滑動螢幕翻過幾頁後才會恢復正常可以使用音量鍵翻頁

不是太大的問題但持續滿久了所以上來跟作者提一聲。

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版上
