### ISSUE TITLE
关于清除下载路径缓存后下载列表的画廊加载问题

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#1312]
就是每次下载功能出了问题需要【清除下载路径缓存】后，每个下载标签内的画廊都需要【点开标签页后等待一段时间才会加载出缩略图与页数信息】，如果不等加载完毕直接点进去会出现【卡住一段时间并大概率卡死停止运行】的情况，想问一下有没有能一次性加载出所有下载画廊信息的方法
![Screenshot_20240713_191154_EhViewer](https://github.com/user-attachments/assets/8f2ab80e-214b-4189-a5bd-26cd7a352861)

**Comment by xiaojieonly** [comment]
暂时没有
