### ISSUE TITLE
突然无法浏览里站

### ISSUE THREAD

**Issue by 0310kk** [xiaojieonly/Ehviewer_CN_SXJ#1313]
你好，突然就无法浏览里站了，设置里没有进行过变动，之前是可以直连画廊站点exhentai，然后最近突然就连不上了，直接显示网络错误，原本以为是igneous过期，但是重新去获取最新的cookie重登账号依旧显示网络错误，将画廊站点改成ehentai可以正常浏览，但站点选ex就不行，用梯子也同样显示网络错误，版本1.9.8.4，回退上个版本也一样显示网络错误，

**Comment by 1acte** [comment]
出现同样的问题＋1
重新获得cookie后依然无法进入里站，显示网络错误。但表站依然可以
用电脑登里站，使用旧igneous和新igneous均正常

**Comment by qiye7493** [comment]
> 你好，突然就无法浏览里站了，设置里没有进行过变动，之前是可以直连画廊站点exhentai，然后最近突然就连不上了，直接显示网络错误，原本以为是igneous过期，但是重新去获取最新的cookie重登账号依旧显示网络错误，将画廊站点改成ehentai可以正常浏览，但站点选ex就不行，用梯子也同样显示网络错误，版本1.9.8.4，回退上个版本也一样显示网络错误，

可能是软件问题，我退版本不行之后重新获取cookie登录也不行，换白e用旧cookie就能正常浏览了

**Comment by xiaojieonly** [comment]
用cookie重新登录
https://nicebowl.fun/11

**Comment by 0310kk** [comment]
> 用cookie重新登录 https://nicebowl.fun/11

试过了，浏览器使用表里站都可以正常浏览，然后获取最新的cookie来登录，但是还是不行，使用旧的cookie也不行，去贴吧里看了，同样的情况出现还挺多的，都是突然无法使用

**Comment by 1acte** [comment]
使用网页登录没问题。但是手机用您做的这个软件就无法进里站，退出重新登录、换igneous都不行。万分感谢

**Comment by xiaojieonly** [comment]
那没办了，我复现不出来
