### ISSUE TITLE
持续几月 无法连接上图库

### ISSUE THREAD

**Issue by ryougishikifor214** [xiaojieonly/Ehviewer_CN_SXJ#132]
已更新至1.8.0.4
![Screenshot_2021-07-23-18-45-05-047_com xjs ehviewer](https://user-images.githubusercontent.com/43427057/126771660-1d19833f-9312-413e-8f68-1f2dd4ec20c4.jpg)
一直是这样出错 这几个月的版本都是这样子

一直挂的VPN  
突然几个月前的一天开始不正常

**Comment by xiaojieonly** [comment]
开了VPN的话，就把高级里网络相关的选项都关了
