### ISSUE TITLE
安全dns 使用的Yandex DNS已经在cn地区无法访问

### ISSUE THREAD

**Issue by a1092595196** [xiaojieonly/Ehviewer_CN_SXJ#1322]
安全dns 使用的Yandex DNS已经在cn地区无法请求成功
建议更换
地区:cn
代码位置:https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/app/src/main/java/com/hippo/ehviewer/client/EhDns.java
第88行:.url(HttpUrl.get("https://77.88.8.1/dns-query"));
请求更换至cloudflare DOH
cloudflare==>>Zero Trust==>Gateway==>>DNS Locations==>>DoH endpoint
以下测试来自AS141739 China Telecom
https://cloudflare-dns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "68", "RR": "A", "Answer": "172.67.2.238"}]
https://security.cloudflare-dns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "181", "RR": "A", "Answer": "104.20.19.168"}]
https://dns.quad9.net/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}]
https://doh.sb/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "104.20.18.168"}]
https://doh.opendns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}]
https://dns.opendns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}]
https://dns.umbrella.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "261", "RR": "A", "Answer": "172.67.2.238"}]

https://doh.pub/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "104.20.19.168"}]
有点意外dnspod居然没污染
测试结果均未污染

---------------以下测试都被污染了
https://dns.alidns.com/dns-query
https://doh.360.cn/dns-query
https://dns.ipv6dns.com/dns-query

**Comment by UjuiUjuMandan** [comment]
> 有点意外dnspod居然没污染

你关掉梯子再打开 https://doh.pub/dns-query?name=e-hentai.org 看看？

> 安全dns 使用的Yandex DNS已经在cn地区无法请求成功

你是怎么判断无法请求成功的？打开 https://77.88.8.1 看看？

在 https://www.itdog.cn/http/ 测试显示 1.1.1.1 和 1.0.0.1 在多个地区都是超时，而 77.88.8.1 响应速度都在 2s 以内，没有超时。状态写的“失败”明显是误判。

**Comment by xiaojieonly** [comment]
> 安全dns 使用的Yandex DNS已经在cn地区无法请求成功 建议更换 地区:cn 代码位置:https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/app/src/main/java/com/hippo/ehviewer/client/EhDns.java 第88行:.url(HttpUrl.get("https://77.88.8.1/dns-query")); 请求更换至cloudflare DOH cloudflare==>>Zero Trust==>Gateway==>>DNS Locations==>>DoH endpoint 以下测试来自AS141739 China Telecom https://cloudflare-dns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "68", "RR": "A", "Answer": "172.67.2.238"}] https://security.cloudflare-dns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "181", "RR": "A", "Answer": "104.20.19.168"}] https://dns.quad9.net/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}] https://doh.sb/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "104.20.18.168"}] https://doh.opendns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}] https://dns.opendns.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "172.67.2.238"}] https://dns.umbrella.com/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "261", "RR": "A", "Answer": "172.67.2.238"}]
> 
> https://doh.pub/dns-query 结果[{"Query": "e-hentai.org.", "TTL": "300", "RR": "A", "Answer": "104.20.19.168"}] 有点意外dnspod居然没污染 测试结果均未污染
> 
> ---------------以下测试都被污染了 https://dns.alidns.com/dns-query https://doh.360.cn/dns-query https://dns.ipv6dns.com/dns-query

如果有更好的dns地址，非常欢迎提交pull request

**Comment by a1092595196** [comment]
> > 有点意外dnspod居然没污染
> 
> 你关掉梯子再打开 https://doh.pub/dns-query?name=e-hentai.org 看看？
> 
> > 安全dns 使用的Yandex DNS已经在cn地区无法请求成功
> 
> 你是怎么判断无法请求成功的？打开 https://77.88.8.1 看看？
> 
> 在 https://www.itdog.cn/http/ 测试显示 1.1.1.1 和 1.0.0.1 在多个地区都是超时，而 77.88.8.1 响应速度都在 2s 以内，没有超时。状态写的“失败”明显是误判。


我明确写出了我的测试环境AS141739 China Telecom并没有梯子
打开https://doh.pub/dns-query?name=e-hentai.org 确实是没有污染可能其他ip测试不是这个结果
使用python
import dns.message
import requests
import base64
import json

doh_url = "https://doh.pub/dns-query"
domain = "e-hentai.org"
rr = "A"
result = []

message = dns.message.make_query(domain, rr)
dns_req = base64.b64encode(message.to_wire()).decode("UTF8").rstrip("=")
r = requests.get(doh_url + "?dns=" + dns_req,
                 headers={"Content-type": "application/dns-message"})
for answer in dns.message.from_wire(r.content).answer:
    dns = answer.to_text().split()
    result.append({"Query": dns[0], "TTL": dns[1], "RR": dns[3], "Answer": dns[4]})
    print(json.dumps(result))

**Comment by UjuiUjuMandan** [comment]
@a1092595196

DNSPod 有国外节点，或许这种架构让他对来自国外查询的回复没有污染。你可能为 doh.pub 使用了代理。

<img width="718" alt="Screenshot 2024-07-25 at 18 30 29" src="https://github.com/user-attachments/assets/d53c188b-8999-4af3-8e7e-53751aa1a639">

**Comment by a1092595196** [comment]
> @a1092595196
> 
> DNSPod 有国外节点，或许这种架构让他对来自国外查询的回复没有污染。你可能为 doh.pub 使用了代理。
> <img alt="Screenshot 2024-07-25 at 18 30 29" width="718" src="https://private-user-images.githubusercontent.com/125150101/352072305-d53c188b-8999-4af3-8e7e-53751aa1a639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQxNzYsIm5iZiI6MTcyMTkwMzg3NiwicGF0aCI6Ii8xMjUxNTAxMDEvMzUyMDcyMzA1LWQ1M2MxODhiLTg5OTktNGFmMy04ZTdlLTUzNzUxYWExYTYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWE2NjJkMDZmNDk3ODVhYTczZjQ2NTNjNjczNjYzOWQxZmYwYTM1Y2U0MTA5NDcxYzBjYjYxMThlNzM0YjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.luDA9BdoZ6WuSeACZbOC2NTXTmKOPQiAdl7fTisMLE8">

![屏幕截图 2024-07-25 183951](https://github.com/user-attachments/assets/c29807d0-b6ed-460a-bfac-e6fd19b92477)


并没有梯子但是我发现我的dnspod使用的ip是162.14.21.56对他请求的https://doh.pub/dns-query  https://162.14.21.56/dns-query?name=e-hentai.org)  ，是我的问题我本地dns响应影响了测试结果。重新查询了全国dns对doh.pub的返回并没有这个ip只有海外ip返回的该ip

**Comment by ihfserkm** [comment]
en
[ ](https://github.com/ttssYI/udsjc/issues/2) [ ](https://github.com/yjldkd/tdsdj6/issues/4) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/5) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/3) [ ](https://github.com/yjldkd/tdsdj6/issues/5) [ ](https://github.com/ttssYI/udsjc/issues/5) [ ](https://github.com/yjldkd/ufdsuju/issues/3) [ ](https://github.com/yjldkd/ufdsuju/issues/4) [ ](https://github.com/yjldkd/tdsdj6/issues/3) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/idajr/ufdtk/issues/10) [ ](https://github.com/idajr/ufdtk/issues/3) [ ](https://github.com/yjldkd/tdsdj6/issues/8) [ ](https://github.com/yjldkd/ufdsuju/issues/1) [ ](https://github.com/idajr/ydsj/issues/7) [ ](https://github.com/yjldkd/tdsdj6/issues/1) [ ](https://github.com/yjldkd/ufdsuju/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/6) [ ](https://github.com/idajr/ydsj/issues/5) [ ](https://github.com/yjldkd/ufdsuju/issues/7) [ ](https://github.com/idajr/ydsj/issues/9) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/8) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/idajr/ufdtk/issues/1) [ ](https://github.com/yjldkd/ufdsuju/issues/10) [ ](https://github.com/idajr/ufdtk/issues/6) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/1) [ ](https://github.com/idajr/ufdtk/issues/5) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/9) [ ](https://github.com/idajr/ydsj/issues/9) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/4) [ ](https://github.com/yjldkd/ufdsuju/issues/10) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/7) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/5) [ ](https://github.com/idajr/ydsj/issues/7) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/idajr/ydsj/issues/1) [ ](https://github.com/yjldkd/tdsdj6/issues/5) [ ](https://github.com/yjldkd/ufdsuju/issues/7) [ ](https://github.com/ttssYI/udsjc/issues/6) [ ](https://github.com/idajr/ydsj/issues/8) [ ](https://github.com/yjldkd/ufdsuju/issues/8) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/10) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/ttssYI/udsjc/issues/2) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/6) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/yjldkd/tdsdj6/issues/7) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/ttssYI/udsjc/issues/1) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/2) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/idajr/ydsj/issues/9) [ ](https://github.com/idajr/ydsj/issues/7) [ ](https://github.com/idajr/ufdtk/issues/2) [ ](https://github.com/idajr/ufdtk/issues/1) [ ](https://github.com/yjldkd/ufdsuju/issues/7) [ ](https://github.com/yjldkd/tdsdj6/issues/4) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/ttssYI/udsjc/issues/4) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/idajr/ufdtk/issues/5) [ ](https://github.com/idajr/ufdtk/issues/5) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/yjldkd/ufdsuju/issues/10) [ ](https://github.com/idajr/ydsj/issues/5) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/yjldkd/ufdsuju/issues/6) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/7) [ ](https://github.com/idajr/ydsj/issues/9) [ ](https://github.com/idajr/ydsj/issues/9) [ ](https://github.com/yjldkd/ufdsuju/issues/1) [ ](https://github.com/idajr/ufdtk/issues/3) [ ](https://github.com/yjldkd/tdsdj6/issues/5) [ ](https://github.com/idajr/ufdtk/issues/2) [ ](https://github.com/idajr/ufdtk/issues/6) [ ](https://github.com/ttssYI/udsjc/issues/1) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/1) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/idajr/ydsj/issues/4) [ ](https://github.com/ttssYI/udsjc/issues/5) [ ](https://github.com/ttssYI/udsjc/issues/8) [ ](https://github.com/yjldkd/tdsdj6/issues/7) [ ](https://github.com/idajr/ydsj/issues/2) [ ](https://github.com/ttssYI/udsjc/issues/2)
