### ISSUE TITLE
删除已下载的画廊后无法正常重新下载

### ISSUE THREAD

**Issue by 389152202** [xiaojieonly/Ehviewer_CN_SXJ#1323]
起因是原本画廊要更新，但是偶尔总有几本会几页下载不动，于是尝试删除重新下载，删除已下载的画廊，预览略缩图正常但是重新阅读和下载都只能到40，后面统统显示invalid page，删除后本地数据也没找到画廊文件，删除-退出-历史重新下载 也不起作用

**Comment by 389152202** [comment]
目前删除了两本画廊均无法正常下载，只能看到40页，我尝试了设置-高级功能中的清除画廊下载路径缓存和清理内存缓存、设置-下载功能中的清理下载冗余均无法解决这个问题。其他没有进行过删除操作的画廊均可以进行正常下载或在线阅读。

**Comment by xiaojieonly** [comment]
分配的H@H服务器有问题

**Comment by 389152202** [comment]
没有解决的办法吗
