### ISSUE TITLE
最新版的问题

### ISSUE THREAD

**Issue by Xdyn2005** [xiaojieonly/Ehviewer_CN_SXJ#1325]
![Screenshot_20240724_144511.jpg](https://github.com/user-attachments/assets/5eb3f9c2-4927-4e7b-b8a3-322835b6155e)

以前都没有什么问题，这次更新之后打开软件上面显示一个好痛，然后然后屏幕中间有一个，安卓系统小机器人头部哭泣的标志，无论是重下还是重梯子都没用，怎么办？

**Comment by xiaojieonly** [comment]
梯子换节点，换到好为止
