### ISSUE TITLE
某个本子下载完了软件加载不出来 本地文件夹打开可以正常打开

### ISSUE THREAD

**Issue by chuangyuan1** [xiaojieonly/Ehviewer_CN_SXJ#1328]
本子名字：(C102) [Twilight Road (Tomo)] Alice mo Gohoushi ga Shitaidesu | 爱丽丝也想要侍奉 (Blue Archive) [Chinese] [欶澜汉化组]

下载完点开就一直转圈怎么也转不开 本地文件夹打开就好使
系统鸿蒙4.0
软件版本1.9.8.4
试过把本子删了重下也不行
貌似不止这一个本子会 部分本子也遇到过类似的情况

**Comment by xiaojieonly** [comment]
1
