### ISSUE TITLE
[功能申请] 收藏 转化为 订阅

### ISSUE THREAD

**Issue by DerivativeMarmot** [xiaojieonly/Ehviewer_CN_SXJ#133]
希望能出一个功能，可以收集收藏里画廊的标签，然后选其中数量最多的几个标签，添加到My Tag里面。差不多就是自动化订阅？
就不需要手动在My Tag里添加标签了。然后也能达到一个**个性化**推荐的效果。

**Comment by xiaojieonly** [comment]
最新版本已解决，目前可以自行管理tag了
