### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by Villkiss-chen** [xiaojieonly/Ehviewer_CN_SXJ#1330]
WiFi良好 但是无法加载 一直转圈圈
![Screenshot_2024-07-29-13-02-24-555_com xjs ehviewer](https://github.com/user-attachments/assets/bbad460a-45c7-45b4-8e5a-b48db8fbc00a)

**Comment by UjuiUjuMandan** [comment]
请说一下您的大致地区和以下IP的直连情况：

https://104.20.18.168
https://104.20.19.168
https://172.67.2.238

**Comment by xiaojieonly** [comment]
挂梯子
