### ISSUE TITLE
无法加载，但是没有任何提示

### ISSUE THREAD

**Issue by hanbaowanghaochi** [xiaojieonly/Ehviewer_CN_SXJ#1331]
![Screenshot_2024-07-29-16-59-39-928_com xjs ehviewer](https://github.com/user-attachments/assets/bdb6de24-28f5-4ef2-bdbd-ceeba8fa4871)

平板上可以打开exhentai 同一个账号
手机可以打开ehentai，打开ex会出现上面这个样子
看着看着突然就这样了

**Comment by fantasysimulation** [comment]
我也出现了这个问题，以前是忽然好的，现在按上面的方法试过了还是没用。

**Comment by xiaojieonly** [comment]
用cookie重新登录
