### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by yuzhe530** [xiaojieonly/Ehviewer_CN_SXJ#1332]
![Screenshot_20240730_225251](https://github.com/user-attachments/assets/6cb34625-08ea-4014-9620-5d528410ca3c)
![Screenshot_20240730_225256](https://github.com/user-attachments/assets/1f5d9f54-6fc3-48b3-85ac-48d2a5801673)
一直在转圈圈，有时候会跳个超时

**Comment by UjuiUjuMandan** [comment]
请说一下您的大致地区和以下IP的直连情况：

https://104.20.18.168
https://104.20.19.168
https://172.67.2.238

**Comment by xiaojieonly** [comment]
挂梯子吧

**Comment by yuzhe530** [comment]
> 请说一下您的大致地区和以下IP的直连情况：
> 
> https://104.20.18.168 https://104.20.19.168 https://172.67.2.238

这三个都连不上，地区在浙江

**Comment by UjuiUjuMandan** [comment]
@yuzhe530 谢谢提供信息，下个版本会应用我新加入的IP，应该可以解决直连问题。

请再检查以下 exhentai 的 IP 是否被封锁：

https://178.175.129.254
https://178.175.128.254

**Comment by yuzhe530** [comment]
> @yuzhe530 谢谢提供信息，下个版本会应用我新加入的IP，应该可以解决直连问题。
> 
> 请再检查以下 exhentai 的 IP 是否被封锁：
> 
> https://178.175.129.254 https://178.175.128.254

用浏览器打开是404

**Comment by UjuiUjuMandan** [comment]
@yuzhe530 了解了，只有 e-hentai 被封锁。
