### ISSUE TITLE
ehviewer 封面和略缩图显示不了

### ISSUE THREAD

**Issue by Raeidon** [xiaojieonly/Ehviewer_CN_SXJ#1349]
内部的图片可以加载，麻烦问一下怎么处理
ps:
![Screenshot_20240802_110445_com xjs ehviewer](https://github.com/user-attachments/assets/2f70d4db-4a0e-4796-977f-82c4860c86e6)
该关的都关了，已经是最新版本了

**Comment by xiaojieonly** [comment]
梯子不行，换个梯子试试

**Comment by Raeidon** [comment]
我这个梯子一个月之前还是可以的啊
