### ISSUE TITLE
可以做一个汉语专区吗

### ISSUE THREAD

**Issue by gzxdiaobaole** [xiaojieonly/Ehviewer_CN_SXJ#1356]
不知道为什么是不是我没探索到怎么只看汉语本子，希望能在只筛选中文的情况下能够同时搜索别的标签，现在好像只能在汉语区里乱翻，不能在锁定一个标签的情况下搜索第二个标签🤓

**Comment by gzxdiaobaole** [comment]
还有就是我没搞明白怎么屏蔽标签

**Comment by xiaojieonly** [comment]
每个标签之间加上两个空格就可以进行多标签搜索
