### ISSUE TITLE
偶现图片解码失败问题

### ISSUE THREAD

**Issue by yanhan0123** [xiaojieonly/Ehviewer_CN_SXJ#1357]
画廊下载时偶尔有解码失败的图片，一般刷新即可解决，但最近发现有个画廊的特定图片一直失败。该图片可在其他ehviewer中正常下载，查看文件夹发现文件已下载，文件大小与彩e下载的图片一致，但图片已损坏。
画廊信息：[FANBOX] 臣訾 (附带文案) (12063067)  日期20240728  第21张

**Comment by yanhan0123** [comment]
补充一下，十六进制查看损坏图片，发现前面有一大片0

**Comment by jiangzeminjia2s** [comment]
补充一点，开启下载原图之后，很多图片用app都打不开，但确实已经下载了

**Comment by xiaojieonly** [comment]
可以试试用档案下载
