### ISSUE TITLE
下载画廊时会弹出ehviewer无法无法响应的提示

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#1359]
如题，弹出该提示后，必须点击一次确认，强制关闭APP一次，之后再将APP打开，才能正常进行下载了。
但如果一次性连续下载好几个画廊，或者在下载时频繁地翻看主页的其他页面，也有很高的概率弹出该提示。
日常使用倒是没什么问题，就是很影响体验。
（本地已下载20000+的画廊，猜测应该和这方面有关）

**Comment by xiaojieonly** [comment]
活用下载分组功能，下载列表中左滑打开下载侧边栏可看到
