### ISSUE TITLE
关于阅读时图片配额消耗过快的疑问

### ISSUE THREAD

**Issue by Brevlend** [xiaojieonly/Ehviewer_CN_SXJ#1362]
在仅使用默认配置的情况下，阅读图片，配额消耗的非常快（5000点甚至无法阅读200页），取消勾选host、梯子全局模式、图片大小780，依然消耗飞起，感觉像是每张图片都是原图下载的消耗量，求助是为什么…？😢

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11
