### ISSUE TITLE
关于eh缩略图

### ISSUE THREAD

**Issue by kaqitolitai** [xiaojieonly/Ehviewer_CN_SXJ#1364]
每次打开eh（绿）缩略图就全部失败加载不出来，刷新也没有用，求解！！！

**Comment by kaqitolitai** [comment]
补充一下，每次打开软件就会出现图片中的情况
![Uploading Screenshot_20240812-174621.jpg…]()

**Comment by BeyondArc** [comment]
遇到同样的问题。前天没有缩略图。昨天有一部分有，但是刷新又没有了，有缩略图的那部分不会变多。今天又一个都没有了。

**Comment by xiaojieonly** [comment]
晚上人多+网不好是这样的
