### ISSUE TITLE
默认排序是以什么为依据的？

### ISSUE THREAD

**Issue by Petro-Rabbit** [xiaojieonly/Ehviewer_CN_SXJ#1369]
![PixPin_2024-08-17_21-14-08](https://github.com/user-attachments/assets/bc8d077c-764b-4880-ae54-fb01bba6ba73)

尝试修改文件时间没有效果，下载漫画的默认排序应该是每个文件里的 .ehviewer 文件记录的。
我猜测其中数字英文混合的是校验码，第 4 和 9 及以后的行分别对应漫画本身和其中每一页的校验码？
经测试，第 8 行对应漫画总页数，但上面3个单数的意义不明， 5 和 6 行似乎总是为1，7 行总是和 8 行相同，表示总页数。第 3 行的7位数字经测试也和顺序无关。难道下载默认排序记录在其他地方？
有些已经下架的漫画无法通过在详情页重下来将它顶到最前面，请问漫画是依据什么来排序的？5，6，7 行又代表什么？

**Comment by xiaojieonly** [comment]
按下载时间
