### ISSUE TITLE
关于阅读与下载的问题和关于搜索的小建议

### ISSUE THREAD

**Issue by crasher32** [xiaojieonly/Ehviewer_CN_SXJ#137]
关于阅读与下载
app的设置中有阅读和下载两项
其中阅读选项中没有提供“只阅读原图”这个选项，只有各种分辨率以及自动
而下载中提供了下载原图这一选项
经过我的实验发现，似乎下载功能就是把阅读中的图片保存下来了
也就是说如果开启下载原图功能，那么阅读也全部是以原图获取
如果不开启下载原图功能，则阅读和下载的不一定是原图
个人希望将阅读和下载的图片分辨率分隔开
毕竟只有特别喜欢的才会选择下载，而下载肯定是希望下载原图，而一般的阅读则不必获取原图来消耗大量配额<（￣︶￣）>

===========================================================================

关于搜索
纯个人建议可以借鉴一下 https://github.com/EhTagTranslation/EhSyringe 这个项目，在搜索时输入中文可以跳出相应的tag

![avatar](https://user-images.githubusercontent.com/5716100/60812493-310b5900-a1c4-11e9-85f7-1d4212765156.gif)

或者输入英语能跳出相应的tag也行
这样真的能方便不少
纯个人建议，不知道实现难度，太难的话就算了吧（￣▽￣）~*

**Comment by xiaojieonly** [comment]
已实现
