### ISSUE TITLE
突然出现封面加载失败的现象

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#1370]
刚不久前才出现的，系统是安卓14
![Screenshot_20240818_232832_EhViewer](https://github.com/user-attachments/assets/57e7f2c6-4a5a-4de7-a925-8ba8d0031519)

**Comment by DidyouseetheSunrise** [comment]
每次刷新除开极少数画廊以外封面均加载失败，点进详情页、退出重启程序和刷新也无法解决

**Comment by Aurora-JG-Lun** [comment]
同上，今天刚出现

**Comment by zuobinhao** [comment]
今早打开就这样了😭

**Comment by Control-Core** [comment]
好像18号9点之前的都没事？

**Comment by banned2054** [comment]
昨天或者是前天开始的、前几页的封面加载不出来，订阅和热门也会加载不出来部分封面。并且搜索不受影响

**Comment by xiaojieonly** [comment]
已修，晚上更新

**Comment by user599** [comment]
> 已修，晚上更新

更新过了还是一样的情况，清理了数据也没行

**Comment by user599** [comment]
> 已修，晚上更新

还是有一部分封面会加载失败
