### ISSUE TITLE
2024年初更新后缩略图原图均无法加载

### ISSUE THREAD

**Issue by yaojian1121** [xiaojieonly/Ehviewer_CN_SXJ#1375]
[logcat-2024-08-19-21-49-22-132.txt](https://github.com/user-attachments/files/16660453/logcat-2024-08-19-21-49-22-132.txt)

初始错误应该是这个? 搜了下好像是证书问题不太懂;(
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

人在海外网络是没问题的
搜索文字类信息都能取到
只有图片获取有问题包括下载都无法完成

安卓版本6.0

**Comment by xiaojieonly** [comment]
新版已修复
