### ISSUE TITLE
请问，我这边看不到评论区怎么办啊

### ISSUE THREAD

**Issue by kuhdrd** [xiaojieonly/Ehviewer_CN_SXJ#1376]
白色图是我的，黑色图是我同学的，我们两个人都是一个版本，但我的看不了画廊评论，我的账号有里站权限，也重新登陆过了
![mmexport1724083993285](https://github.com/user-attachments/assets/d9e5fe5c-fff1-47b3-bc6f-74cf3b03426a)
![mmexport1724083990708](https://github.com/user-attachments/assets/67ef1b61-506d-43e1-b044-a312f254e0ca)

**Comment by xiaojieonly** [comment]
可能是设置里把评论关了

**Comment by kuhdrd** [comment]
> 可能是设置里把评论关了

谢谢您，我才发现要手动开😂
