### ISSUE TITLE
无法在应用内更新版本

### ISSUE THREAD

**Issue by ddtshallong** [xiaojieonly/Ehviewer_CN_SXJ#1377]
自从去年某个版本开始，在应用内更新版本会在通知栏显示下载进度，完成后闪烁一下就消失了
设备：小米12su/小米mixfold4
系统：安卓14 小米澎湃os1.0.9.0

**Comment by UjuiUjuMandan** [comment]
澎湃OS贴心地帮恁删除了色情病毒软件捏~
