### ISSUE TITLE
阅读缓存没有正确起效

### ISSUE THREAD

**Issue by enclave416** [xiaojieonly/Ehviewer_CN_SXJ#1378]
在A画廊阅读几页以后退出再打开B画廊进行阅读，在B画廊阅读完毕以后再重新打开A画廊，此时A画廊所有的图片需要全部重新加载。
有些时候甚至阅读完当前画廊后再退出，再进入也需要重新加载

尝试改变了阅读缓存大小，但是没有起效，只影响正在阅读的画廊的图片加载。

之前的1.9.7.2版本未出现这个问题，后来每次更新都发现有这个问题，这个版本也是这样，只能一直回退到1.9.7.2

希望能帮忙解决一下，谢谢作者

**Comment by xiaojieonly** [comment]
已修，下一版上
