### ISSUE TITLE
我希望使用ehviewer查看我上传的私人(private)画廊

### ISSUE THREAD

**Issue by xbc0n0** [xiaojieonly/Ehviewer_CN_SXJ#1381]
我上传了private的画廊但是我无法通过ehviewer来阅读它，我希望使用ehviewer查看我上传的私人(private)画廊。
建议在侧边栏添加一个“我上传的”模块，来遍历当前登录账号上传的画廊列表，它不需要编辑/删除画廊等其他功能，只需要跳转到相应画廊的详情页面就可以，我相信这不是一个困难的问题。
😊thanks

**Comment by xbc0n0** [comment]
我已经通过添加收藏夹的方式来使用ehviewer访问私人画廊了，此问题终结😂

**Comment by xiaojieonly** [comment]
好的，之后有时间我也会研究一下这个问题
