### ISSUE TITLE
特定画廊下载问题

### ISSUE THREAD

**Issue by sun123war** [xiaojieonly/Ehviewer_CN_SXJ#1384]
https://exhentai.org/g/2039646/c071158dcd/
这个作者的好多汉化作品的第510或511页下载会显示509，我确定不是自己配额问题，因为其他作品仍然可以正常下载，而且评论里也有人提到这个问题，可以麻烦您看一下吗

**Comment by xiaojieonly** [comment]
509就是配额问题，E站服务器返回509，我咋弄都没有，我没有服务器权限
