### ISSUE TITLE
请问为什么wifi热点迁移数据使用不了？

### ISSUE THREAD

**Issue by 7200xiaote** [xiaojieonly/Ehviewer_CN_SXJ#1385]
两台手机新手机旧手机都有电话卡了，并且旧手机也开了热点让新手机成功连上，但是旧手机显示连接不存在，创建通信失败等一类的报错。

**Comment by xiaojieonly** [comment]
不清楚，你可能连反了

**Comment by 7200xiaote** [comment]
> 不清楚，你可能连反了

两台手机都试过迁移了，但还是不行。
