### ISSUE TITLE
画廊封面无法读取

### ISSUE THREAD

**Issue by gugualaolian** [xiaojieonly/Ehviewer_CN_SXJ#1386]
更新1.9.8.6版本后，所有画廊的封面都无法加载。（如下图，如果图被正确发送的话）
![Screenshot_20240826_015110_com xjs ehviewer](https://github.com/user-attachments/assets/53b07725-a918-4c7e-b095-1f5aed79f37b)
同时，点击封面查看tag的功能由于缺少封面也无法使用。
但是点进去后缩略图可以正常加载。
回退安装1.9.8.5和1.9.8.4版本的话，有大约5-10%的画廊封面可以被加载，其他画廊和1.9.8.6版本一样，无法加载。

已经尝试过开关【修正缩略图连接】和【清理缓存】，但没有效果。

**Comment by xiaojieonly** [comment]
挂vpn了是吧？挂了vpn就把host啥的都关了
