### ISSUE TITLE
可以下载，网络没问题，但读取失败

### ISSUE THREAD

**Issue by 2911894613** [xiaojieonly/Ehviewer_CN_SXJ#1388]
可以在线预览看，也可以下载，下载完成后本地也可以看到下载的文件，但就是不能在eh里面看图。在eh里面点开下载好的漫画就会显示读取失败

**Comment by 2911894613** [comment]
补充一下，比如一个30页的画廊，下载了29页，还剩1页没下载完，那这个时候点进去其实是可以看这29页已经下好的图的。但如果30页全下完了，那再点进去就会显示读取失败了

**Comment by xiaojieonly** [comment]
没给权限
