### ISSUE TITLE
有關下載的問題

### ISSUE THREAD

**Issue by cmtg994r** [xiaojieonly/Ehviewer_CN_SXJ#1389]
我記得蠻之前的版本，在圖源是e-h的情況下，下載原圖只要不登錄切飛航模式換IP就能一直下載了
EX圖庫有針對登入帳號進行流量限制
可是現在即使是e-h圖源在沒有登入的情況下，即使用了飛航模式切換IP，還是會被限流無法進行下載原圖的
我不確定是app的問題，還是網站有進行相關的更新來限制
這個問題有辦法進行修復嗎？

**Comment by cmtg994r** [comment]
![Screenshot_20240827_163500_Chrome](https://github.com/user-attachments/assets/89cabd31-33a8-4b69-90f5-4d55a6879357)
大致上就像這樣，完全沒有速度

**Comment by xiaojieonly** [comment]
E站改了，所有配额都跟着账号走了，只有没登录的情况下才会走Ip配额，你可以这么理解
