### ISSUE TITLE
下載後閱讀問題

### ISSUE THREAD

**Issue by JunQi0226** [xiaojieonly/Ehviewer_CN_SXJ#1390]
https://e-hentai.org/g/2692451/0936f174dc/
這部畫廊原檔1.07G，在勾選下載原圖情況下閱讀會一直轉圈無法正常顯示，即使下載後閱讀也只會顯示封面，其餘頁面也是轉圈圈。
如果將下載原圖取消勾選就能正常閱讀，有嘗試清除快取，閱讀快取設最大值
版本1.9.8.6，不曉得是不是因為閱讀快取大小不足，還請作者解惑，謝謝作者！

![Screen_Recording](https://github.com/user-attachments/assets/16d22c37-d756-4ccb-80ba-ad265207bb10)

**Comment by xiaojieonly** [comment]
一张图十多M，网不好加载肯定慢

**Comment by RobotV1** [comment]
我似乎遇到了相同的问题：开启“下载原图”后，极少数图片会在慢速转圈1次（疑似为下载读条）后无限快速转圈。将含有这种图片的画廊下载到本地后，这些图片也无法在软件中正常显示（现象变为无限快速转圈），但可以用文件管理器在下载目录中找到可正常打开的图片文件。
示例：
以下画廊中的几乎所有图片：https://exhentai.org/g/3032622/42dc1ec596/
