### ISSUE TITLE
请求添加“一键更新已下载的画廊”功能，以及对于下载内容更新的建议

### ISSUE THREAD

**Issue by RobotV1** [xiaojieonly/Ehviewer_CN_SXJ#1391]
在目前版本，若要更新已保存到本地的画廊，则必须逐个手动打开已下载画廊，然后选择版本进行更新。若待更新的画廊数量较多，该操作将十分繁琐。故请求添加一个新功能：一键检查所有已下载的画廊是否存在新版本，随后覆盖更新所有存在新版本的已下载画廊。若某些画廊新版本的页数少于已下载版本，则执行更新前需要用户手动确认。

另外，注意到大部分情况下，画廊更新只涉及该画廊中少量图片的添加或改动，而目前版本的画廊覆盖更新功能似乎会删除所有已下载的图片，随后重新下载所有图片，这常常严重浪费流量与EH配额。若能设法避免重复下载已保存的图片，或能显著改善该问题。

**Comment by xiaojieonly** [comment]
以目前的E站已有接口很难做到此功能
