### ISSUE TITLE
更新完页面加载不出来

### ISSUE THREAD

**Issue by daochengyutian** [xiaojieonly/Ehviewer_CN_SXJ#1393]
![Screenshot_2024-08-28-11-58-53-160_com xjs ehviewer](https://github.com/user-attachments/assets/59829aef-4d42-4186-ab36-5dbca0bff58c)

**Comment by daochengyutian** [comment]
各位大佬帮忙看看

**Comment by xiaojieonly** [comment]
已关闭问题里自己搜
