### ISSUE TITLE
无法获取配额以及搜索结果显示不全

### ISSUE THREAD

**Issue by Malcolm-Allen** [xiaojieonly/Ehviewer_CN_SXJ#1395]
1.E站配额显示为0/0，更换网络环境也无法改善

2.在搜索栏中搜索时仅显示第一页，除非进行第二次搜索否则无法正常显示所有结果

**Comment by gao950912** [comment]
我也是

**Comment by xiaojieonly** [comment]
1：已修，十月份更新上，我九月份有事
2：应该是网速慢导致的，我复现不出来

**Comment by gao950912** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Malcolm-Allen** [comment]
> 1：已修，十月份更新上，我九月份有事 2：应该是网速慢导致的，我复现不出来

感谢大佬！大佬辛苦！

关于问题2：您可以试试从搜索历史里搜索而不是其他方式，复现率大概三分之一？

**Comment by xiaojieonly** [comment]
> > 1：已修，十月份更新上，我九月份有事 2：应该是网速慢导致的，我复现不出来
> 
> 感谢大佬！大佬辛苦！
> 
> 关于问题2：您可以试试从搜索历史里搜索而不是其他方式，复现率大概三分之一？

还是没复现出来
