### ISSUE TITLE
你好，我想问问如果使用新版，会不会把旧版本的收藏和历史记录覆盖清除掉？

### ISSUE THREAD

**Issue by qszine377** [xiaojieonly/Ehviewer_CN_SXJ#14]
你好，我想问问如果使用新版，会不会把旧版本的收藏和历史记录覆盖清除掉？

这个对我来说挺重要的，收藏了好多

**Comment by typitk** [comment]
这个安装不会覆盖掉旧的版本（停更的那个版本），而是作为另一个app来安装，然后你的手机上会同时存在旧的和这个新的，所以这个新的app自然就不会拥有旧的app本地收藏和历史记录了，本人亲测

**Comment by xiaojieonly** [comment]
> 你好，我想问问如果使用新版，会不会把旧版本的收藏和历史记录覆盖清除掉？
> 
> 这个对我来说挺重要的，收藏了好多

你可以试试设置-->高级-->导出数据，然后在新版中导入。有人这样操作成功了

**Comment by PuddingVitamin** [comment]
老版本设置-->高级-->导出数据，随后在新版选择数据导入（会自动识别），然后根据数据的多与少手机会卡在选择页面一会儿。此刻只需要等待就好了。
