### ISSUE TITLE
希望能更新API到30

### ISSUE THREAD

**Issue by kongCHEN10** [xiaojieonly/Ehviewer_CN_SXJ#140]
更新到arm64位

**Comment by xiaojieonly** [comment]
安卓11没法用？

**Comment by kongCHEN10** [comment]
> 安卓11不能用？

提个建议而已，做不到就算了

**Comment by Gong-Mi** [comment]
> 安卓11没法用？

安卓12就开始淘汰了32位了
安卓13全面64位 32只能扔虚拟机
![Screenshot_2021-11-12-01-56-51-953_com miui thirdappassistant](https://user-images.githubusercontent.com/62661921/141457250-f8c15b98-660a-42e3-a7b3-089ba45bed54.jpg)

**Comment by Gong-Mi** [comment]
@xiaojieonly

**Comment by xiaojieonly** [comment]
api更新到31会导致低版本的手机没法安装或没法使用，所以目前为了兼容性考虑选择了一个比较中间的api版本

**Comment by xiaojieonly** [comment]
已跟新为64位应用，api暂时不改
