### ISSUE TITLE
对已下载的文档全部勾选并点击下载时，会有已丢失文件但仍然显示已下载的画廊（数量还不少）

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#1400]
如题

**Comment by suweiai1314** [comment]
一些下好的版权本也没了😭

**Comment by suweiai1314** [comment]
重新下载好的本，再次点击下载开始的话，它还是从0开始下，这就很奇怪，我下好后根据文件码搜了一下本地文件，发现图片文件全在，但是在APP里打开阅读还是需要重下。
这个问题我自己试了一下，已知的解决法是，把问题画廊在下载里删除，再重新下一遍就行了。

**Comment by suweiai1314** [comment]
出现问题的画廊，有些只有一两页需要重新下，有些则是一大本，还有一些是整本从0开始下，但在下载页面的显示全是“已完成”

**Comment by xiaojieonly** [comment]
> 重新下载好的本，再次点击下载开始的话，它还是从0开始下，这就很奇怪，我下好后根据文件码搜了一下本地文件，发现图片文件全在，但是在APP里打开阅读还是需要重下。 这个问题我自己试了一下，已知的解决法是，把问题画廊在下载里删除，再重新下一遍就行了。

这个应该是覆盖下载功能导致的bug，现在覆盖下载已经弃用了，以后应该会好很多
