### ISSUE TITLE
上传者为Disowned时，上传者留言不可见。

### ISSUE THREAD

**Issue by leaim** [xiaojieonly/Ehviewer_CN_SXJ#1402]
如题，网页上看了下，上传者评论还是在的，但app里已经获取不到了。

**Comment by xiaojieonly** [comment]
搜不出来。。。

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/7b016097-f3e5-4c52-a54a-c02c544c5e20)

**Comment by leaim** [comment]
啊，不是名字，是上传者选择 Disowned 之后。
例如https://e-hentai.org/g/2852522/76b62fb82d/ 这个本，网页上能看到上传者的第一条评论“用最小白的团子一键翻的，自己撸管用，劣质机翻漏翻无润色”。app看不到了
