### ISSUE TITLE
getGalleryDownloadDir该方法内某一段在模拟器上运行时十分卡顿

### ISSUE THREAD

**Issue by hozzldf** [xiaojieonly/Ehviewer_CN_SXJ#1403]
这段代码是我从1.9.6.7源码中抠出来的。但是新版本也有一样的问题。
我的运行环境是雷电模拟器，当你下载了大量的本子，然后因为模拟器提供的内部空间不足而通过该模拟器自带的映射功能将下载文件夹映射到外部的真实硬盘空间时，我标记的这段代码就会动辄卡个十几二十秒。
当我找到是这段代码之后，我只大致研究了下这段代码的作用，发现好像没什么用有点多余。
于是我就自行注释掉运行至今（实际上我不是从1.9.6.7版本开始这么干的，已经很久了）。
然后最近因为缩略图的原因不得不升级新版本代码，不过发现新版本代码这一段不好直接通过简单注释掉来修改。
所以就提了这个bug。希望能修复。

`
public static UniFile getGalleryDownloadDir(GalleryInfo galleryInfo) {
        UniFile dir = Settings.getDownloadLocation();
        if (dir != null) {
            // Read from DB
            String dirname = EhDB.getDownloadDirname(galleryInfo.gid);
            if (null != dirname) {
                // Some dirname may be invalid in some version
                dirname = FileUtils.sanitizeFilename(dirname);
                EhDB.putDownloadDirname(galleryInfo.gid, dirname);
            }

            //-----------这段会卡顿-----------------------
            // Find it
            /*if (null == dirname) {
                UniFile[] files = dir.listFiles(new StartWithFilenameFilter(galleryInfo.gid + "-"));
                if (null != files) {
                    // Get max-length-name dir
                    int maxLength = -1;
                    for (UniFile file : files) {
                        if (file.isDirectory()) {
                            String name = file.getName();
                            int length = name.length();
                            if (length > maxLength) {
                                maxLength = length;
                                dirname = name;
                            }
                        }
                    }
                    if (null != dirname) {
                        EhDB.putDownloadDirname(galleryInfo.gid, dirname);
                    }
                }
            }*/
            //-----------到这里结束 --------------------------

            // Create it
            if (null == dirname) {
                dirname = FileUtils.sanitizeFilename(galleryInfo.gid + "-" + EhUtils.getSuitableTitle(galleryInfo));
                EhDB.putDownloadDirname(galleryInfo.gid, dirname);
            }

            return dir.subFile(dirname);
        } else {
            return null;
        }
    }
`

**Comment by xiaojieonly** [comment]
改不了，抱歉。。。
这应该是模拟器的问题

**Comment by hozzldf** [comment]
@xiaojieonly 我贴的这段代码中关键卡顿的那个地方不能直接删掉吗？新版本逻辑我没看太明白。所以不知道怎么处理。
旧版本的话卡顿的那段其实就是在读取文件之前先遍历了一下本地的所有文件夹，仅此而已没有其他操作，相当没有意义。所以我当时就把那段直接注释掉了。
新版本加的那些代码我没太捋清楚写了些啥所以就改不太动。如果还是存在读取之前先遍历一遍文件夹这种没什么意义的操作，我觉得依然是可以把整个给注释掉的。
