### ISSUE TITLE
[补]上传者为Disowned时，上传者留言不可见。

### ISSUE THREAD

**Issue by leaim** [xiaojieonly/Ehviewer_CN_SXJ#1404]
如题，上回没说清楚。是上传者选择 Disowned 之后。
例如https://e-hentai.org/g/2852522/76b62fb82d/ 这个本，网页上能看到上传者的第一条评论
“用最小白的团子一键翻的，自己撸管用，劣质机翻漏翻无润色”。
app看不到了

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版上
