### ISSUE TITLE
建议把为标签投票也加进来

### ISSUE THREAD

**Issue by TangibleDreams913** [xiaojieonly/Ehviewer_CN_SXJ#1407]
如题，希望在APP里面集成新增标签、为标签投票、查看标签状态的功能
每次看到打错的标签或者遗漏的标签都感觉十分难受，但是本人是穷狗，梯子全是滥用ip，这让我也上不了主站玩
如能采纳，不胜感激

**Comment by xiaojieonly** [comment]
以后有时间会弄
