### ISSUE TITLE
1.9.8.6下载原图依然失败：TargetImageUrl error

### ISSUE THREAD

**Issue by hameln233** [xiaojieonly/Ehviewer_CN_SXJ#1408]
只能原图下载最近一两个月的，其余一概不能原图下载，只显示TargetImageUrl error

**Comment by hameln233** [comment]
但是，选择非原图下载又能顺利下载，可否修复此问题？

**Comment by xiaojieonly** [comment]
挂梯子试试

**Comment by hameln233** [comment]
> 挂梯子试试

这就是问题所在之一，为了提高下载速度，每次使用此app均挂了梯子，无果

**Comment by xiaojieonly** [comment]
已改，新的错误提示会在十月份的版本更新，现在下载原图需要gp，gp不足会报此错误

**Comment by hameln233** [comment]
> 已改，新的错误提示会在十月份的版本更新，现在下载原图需要gp，gp不足会报此错误

我知道了，非常感谢
容我最后提出一些疑问：此前该项目也有人发出同样的问题，症状均一致：即使使用梯子，面对超过上传时间约两个月的原图就会被卡，而以前我自己使用时若没有配额切换一个结点即可，完全没发生这样的问题。现在发生这些问题，难道是因为最近网站的运营策略改变导致的？
