### ISSUE TITLE
不知道为什么wifi无法加载，用数据可以，求大佬解答

### ISSUE THREAD

**Issue by 2930942153** [xiaojieonly/Ehviewer_CN_SXJ#141]
用wifi一直转圈无法加载，用数据能勉强加载但是会很卡
![Screenshot_2021-08-23-16-38-52-210_com xjs ehviewer](https://user-images.githubusercontent.com/83175245/130420186-223bc326-b067-4de9-807a-a4fca5e2b0e9.jpg)

**Comment by Mr-momo-ME** [comment]
艹，你跟我刚好反过来了，我是WiFi可以，数据流量不行😂

**Comment by xiaojieonly** [comment]
网不好
