### ISSUE TITLE
澎湃OS在应用内更新的时候安装包直接消失

### ISSUE THREAD

**Issue by Fixatedwings** [xiaojieonly/Ehviewer_CN_SXJ#1410]
已关闭“安全守护”，
可以通过浏览器下载安装包正常更新，App内置下载无法使用

具体情况为：
进主界面弹出新版本可供下载-->
点击“下载”-->
状态栏可以看到本App正在下载安装包-->
到100%后状态栏里的下载项消失（浏览器下载的安装包会留在状态栏供点击安装）
![1039c5da06c4a287411f5c7eb46254b3](https://github.com/user-attachments/assets/943b6c36-8c66-40f9-ab80-d446bfb000cd)
![77505b4f88ecd1270581076abe1165e8](https://github.com/user-attachments/assets/c9603e29-f1a4-45c5-857a-7e32a3ed2b3a)

**Comment by xiaojieonly** [comment]
去贴吧问问，华为是这样的。。。
