### ISSUE TITLE
收藏夹默认云端收藏无法改为本地收藏

### ISSUE THREAD

**Issue by laoling123** [xiaojieonly/Ehviewer_CN_SXJ#1412]
大佬，百忙之中打扰了，冒昧问一下在未登录状态下收藏夹默认是云端收藏要怎么调成本地收藏呢？还是说必须要在登录状态下才能调整呢？在作品界面点击收藏后显示的是本地收藏，但是到收藏界面就变为了云端收藏……
相关问题只找到“无法自己选择收藏夹”这一个![Screenshot_2024-09-13-12-26-21-531_com.xjs.ehviewer-edit.jpg](https://github.com/user-attachments/assets/8a02e83f-a84e-4b27-a85b-1729ff4cc396)

![Screenshot_2024-09-13-13-02-20-159_com.xjs.ehviewer-edit.jpg](https://github.com/user-attachments/assets/fe6cf388-ee00-4f9f-b031-1eca10967b34)

**Comment by xiaojieonly** [comment]
你这没登录啊

**Comment by xiaojieonly** [comment]
右侧侧边栏可设置

**Comment by laoling123** [comment]
> 右侧侧边栏可设置

好的，麻烦您了，右边栏好像是没有相关按键提示的，一开始没有留意，实在不好意思_(:з」∠)_
