### ISSUE TITLE
偶尔会出现解码失败的问题

### ISSUE THREAD

**Issue by hdjsheifnjs** [xiaojieonly/Ehviewer_CN_SXJ#1415]
其他页数是好好的，但到了部分页数后会显示解码失败，刷新只会一直在加载，退出重进、切换网络和重开梯子也无法解决
这个问题出现的不频繁，就偶尔会来一下，而且有时是刚刚还能看却退出界面再点进去就显示解码失败了

**Comment by xiaojieonly** [comment]
配额用完了，关闭原图试试

**Comment by hdjsheifnjs** [comment]
> 配额用完了，关闭原图试试

我看了下应该没开原图，也没有下载只是正常点开
