### ISSUE TITLE
关于部分画廊归档下载后无法被app读出的问题

### ISSUE THREAD

**Issue by baiyingui** [xiaojieonly/Ehviewer_CN_SXJ#1416]
十分感谢xiaojieonly的付出，感谢老大的辛苦劳作。
最近使用绿e自带的归档下载时，发现有部分本子只能得到一个压缩包（储存路径为：/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ ），但是绿e的档案分区无法将其读出。比如这个  https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法读出，中途我也试着归档下载了其他本子，可以正常被app读出，且能正常归类至档案分区。此类可以被正常读出的归档本子，除了有一个  /storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/   路径的压缩包外，在/storage/emulated/0/EhViewer/download/  路径下会有解压好的文件夹，内有jpg文件。
我在归档下载时是一直将绿e作为前台挂着，全程没有退出或者放在后台的情况，是保持在画廊本子页面的。
希望老大看一下，谢谢。

**Comment by xiaojieonly** [comment]
好的，能提供手机型号、安卓版本、app版本吗？

**Comment by xiaojieonly** [comment]
> 十分感谢xiaojieonly的付出，感谢老大的辛苦劳作。 最近使用绿e自带的归档下载时，发现有部分本子只能得到一个压缩包（储存路径为：/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ ），但是绿e的档案分区无法将其读出。比如这个 [https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法读出，中途我也试着归档下载了其他本子，可以正常被app读出，且能正常归类至档案分区。此类可以被正常读出的归档本子，除了有一个](https://exhentai.org/g/3048365/c183b45caf/%EF%BC%8C%E5%BD%92%E6%A1%A3%E4%BA%863%E6%AC%A1%E5%A7%8B%E7%BB%88%E6%97%A0%E6%B3%95%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%AD%E9%80%94%E6%88%91%E4%B9%9F%E8%AF%95%E7%9D%80%E5%BD%92%E6%A1%A3%E4%B8%8B%E8%BD%BD%E4%BA%86%E5%85%B6%E4%BB%96%E6%9C%AC%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%A2%ABapp%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%94%E8%83%BD%E6%AD%A3%E5%B8%B8%E5%BD%92%E7%B1%BB%E8%87%B3%E6%A1%A3%E6%A1%88%E5%88%86%E5%8C%BA%E3%80%82%E6%AD%A4%E7%B1%BB%E5%8F%AF%E4%BB%A5%E8%A2%AB%E6%AD%A3%E5%B8%B8%E8%AF%BB%E5%87%BA%E7%9A%84%E5%BD%92%E6%A1%A3%E6%9C%AC%E5%AD%90%EF%BC%8C%E9%99%A4%E4%BA%86%E6%9C%89%E4%B8%80%E4%B8%AA) /storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ 路径的压缩包外，在/storage/emulated/0/EhViewer/download/ 路径下会有解压好的文件夹，内有jpg文件。 我在归档下载时是一直将绿e作为前台挂着，全程没有退出或者放在后台的情况，是保持在画廊本子页面的。 希望老大看一下，谢谢。

更新到最新版了吗？这个下载路径还是旧版的路径，那一版是有bug的

**Comment by baiyingui** [comment]
![Screenshot_2024-09-18-17-43-34-551_com android settings](https://github.com/user-attachments/assets/623cad93-2323-4061-992d-e44070fc4629)
这里是版本和型号，疏忽了。新版的绿e还没归档下载过上文提到的那个画廊，我删除掉压缩包重新归档下载一下，谢谢提醒。

**Comment by baiyingui** [comment]
> > 十分感谢xiaojieonly的辛苦，感谢老大的辛苦劳作。最近使用绿e自带的归档下载时，发现有部分本子只能得到一个压缩包（存储路径为：/storage/emulated/0/Android/data/com .xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ ），但是分区的文件无法将其写入。比如这个[https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法归档，中途我也尝试归档下载了其他本子，可以正常被应用归档，且能正常整理至归档分区。此类可以被正常归档的归档本子，除了有一个](https://exhentai.org/g/3048365/c183b45caf/%EF%BC%8C%E5%BD%92%E6%A1%A3%E4%BA%863%E6%AC%A1%E5%A7%8B%E7%BB%88%E6%97%A0%E6%B3%95%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%AD%E9%80%94%E6%88%91%E4%B9%9F%E8%AF%95%E7%9D%80%E5%BD%92%E6%A1%A3%E4%B8%8B%E8%BD%BD%E4%BA%86%E5%85%B6%E4%BB%96%E6%9C%AC%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%A2%ABapp%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%94%E8%83%BD%E6%AD%A3%E5%B8%B8%E5%BD%92%E7%B1%BB%E8%87%B3%E6%A1%A3%E6%A1%88%E5%88%86%E5%8C%BA%E3%80%82%E6%AD%A4%E7%B1%BB%E5%8F%AF%E4%BB%A5%E8%A2%AB%E6%AD%A3%E5%B8%B8%E8%AF%BB%E5%87%BA%E7%9A%84%E5%BD%92%E6%A1%A3%E6%9C%AC%E5%AD%90%EF%BC%8C%E9%99%A4%E4%BA%86%E6%9C%89%E4%B8%80%E4%B8%AA)/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ 路径的压缩包外，在/storage/emulated/0/EhViewer/download/ 路径下有解压好的文件夹，里面有jpg文件。我在归档下载时一直将绿e作为前端挂着，全程没有退出或者放在后台的情况，是保留在画廊本子页面的。希望老大看一下，谢谢。
> 
> 更新到最新版本了吗？这个下载路径还是旧版本的路径，那一版本有bug的

![Screenshot_2024-09-18-17-43-34-551_com android settings](https://github.com/user-attachments/assets/bd88ca5d-5b91-4b12-8fd2-fb8e61257a97)
这里是版本和型号，疏忽了。新版的绿e还没归档下载过上文提到的那个画廊，我删除掉压缩包重新归档下载一下，谢谢提醒。

**Comment by baiyingui** [comment]
> > 十分感谢xiaojieonly的付出，感谢老大的辛苦劳作。 最近使用绿e自带的归档下载时，发现有部分本子只能得到一个压缩包（储存路径为：/storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ ），但是绿e的档案分区无法将其读出。比如这个 [https://exhentai.org/g/3048365/c183b45caf/，归档了3次始终无法读出，中途我也试着归档下载了其他本子，可以正常被app读出，且能正常归类至档案分区。此类可以被正常读出的归档本子，除了有一个](https://exhentai.org/g/3048365/c183b45caf/%EF%BC%8C%E5%BD%92%E6%A1%A3%E4%BA%863%E6%AC%A1%E5%A7%8B%E7%BB%88%E6%97%A0%E6%B3%95%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%AD%E9%80%94%E6%88%91%E4%B9%9F%E8%AF%95%E7%9D%80%E5%BD%92%E6%A1%A3%E4%B8%8B%E8%BD%BD%E4%BA%86%E5%85%B6%E4%BB%96%E6%9C%AC%E5%AD%90%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E8%A2%ABapp%E8%AF%BB%E5%87%BA%EF%BC%8C%E4%B8%94%E8%83%BD%E6%AD%A3%E5%B8%B8%E5%BD%92%E7%B1%BB%E8%87%B3%E6%A1%A3%E6%A1%88%E5%88%86%E5%8C%BA%E3%80%82%E6%AD%A4%E7%B1%BB%E5%8F%AF%E4%BB%A5%E8%A2%AB%E6%AD%A3%E5%B8%B8%E8%AF%BB%E5%87%BA%E7%9A%84%E5%BD%92%E6%A1%A3%E6%9C%AC%E5%AD%90%EF%BC%8C%E9%99%A4%E4%BA%86%E6%9C%89%E4%B8%80%E4%B8%AA) /storage/emulated/0/Android/data/com.xjs.ehviewer/files/Download/storage/emulated/0/EhViewer/archiver/ 路径的压缩包外，在/storage/emulated/0/EhViewer/download/ 路径下会有解压好的文件夹，内有jpg文件。 我在归档下载时是一直将绿e作为前台挂着，全程没有退出或者放在后台的情况，是保持在画廊本子页面的。 希望老大看一下，谢谢。
> 
> 更新到最新版了吗？这个下载路径还是旧版的路径，那一版是有bug的

绿e版本为1.9.8.6，归档下载不了了，日志
[logcat-2024-09-18-18-57-53-528.txt](https://github.com/user-attachments/files/17042846/logcat-2024-09-18-18-57-53-528.txt)
安卓版本和型号
![IMG_20240918_185734](https://github.com/user-attachments/assets/2416ad36-922a-4019-b4f3-03e806033a13)
发生错误图
![IMG_20240918_185744](https://github.com/user-attachments/assets/17fce881-1308-48da-9b0b-ddfe6c4c83c1)
😭😭

**Comment by baiyingui** [comment]
尝试了多次下载，中间在ex网址重新设置了两次归档链接，还是下载失败。

**Comment by baiyingui** [comment]
归档ip失效后，重置了两次归档链接，重新归档还是下载失败

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
最新版试试，如果还是不行可以重新打开issue
