### ISSUE TITLE
APP里的排行榜页面显示错乱，不显示图片

### ISSUE THREAD

**Issue by vicentory** [xiaojieonly/Ehviewer_CN_SXJ#1422]
1、//希望APP主页和排行榜页面里显示漫画图片数量，另一个APP目前是有（这个功能的，感觉蛮实用。PS：在设置里找到了，很好用。
2、还有APP打开排行榜显示页面错乱见附件，不知道什么原因。![Screenshot_2024-09-22-22-14-45-131_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/8cb55892-362a-44e7-8583-e9ab64ea669f)

**Comment by xiaojieonly** [comment]
从时间点进去

**Comment by vicentory** [comment]
> 从时间点进去

好的，谢谢
