### ISSUE TITLE
功能请求 是否可以添加手动排序的方式

### ISSUE THREAD

**Issue by EnderAvaritia** [xiaojieonly/Ehviewer_CN_SXJ#1423]
换手机导入数据，即便是把整个文件夹转移过来之后下载的漫画顺序也全乱了，使用高级里面的wifi迁移也完全没效果
看见issue里面有与排序有关的，而且标记complete了，但是没找到教程，更新日志里面也没找到，来问一下
顺带，为啥我开了暗色模式之后，别的设备里面接受数据那个界面是暗色的，新设备是亮色的，怪欸

**Comment by xiaojieonly** [comment]
两边都更新到最新版再更新试试

**Comment by EnderAvaritia** [comment]
> 两边都更新到最新版再更新试试

用的已经是最新版了，之后又重新安装了一遍最新版，无效果。
不过排序功能？

**Comment by xiaojieonly** [comment]
这是个bug

**Comment by xiaojieonly** [comment]
手动排序有点难弄

**Comment by xiaojieonly** [comment]
我修一下，十月份更新上

**Comment by xiaojieonly** [comment]
之前是迁移时快速搜索乱序了

**Comment by xiaojieonly** [comment]
新设备主题不生效可能要重新设置一下？或者是系统bug

**Comment by EnderAvaritia** [comment]
> 新设备主题不生效可能要重新设置一下？或者是系统bug

已经试过清除数据之后重新设置了，估计是bug吧

**Comment by EnderAvaritia** [comment]
> 手动排序有点难弄

大佬靠你了

**Comment by EnderAvaritia** [comment]
> 手动排序有点难弄

不是要手动排序云端收藏阿，是要手动排序下载的文件阿
而且这个云端收藏新增的按钮点了也没反应阿
