### ISSUE TITLE
有没有什么办法可以保存画廊的排序

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#1424]
如题，需要换个手机，但是上次换了手机以后整个画廊的排序，以及我自己做的分类什么的全部没了，所以我又重新搞了一遍。请问有没有什么办法可以保存这些设定并且转移到新手机里？

**Comment by xiaojieonly** [comment]
有bug，清空数据后在新版1.9.8.7重新迁移即可
