### ISSUE TITLE
红米澎湃os里站出现空指针报错

### ISSUE THREAD

**Issue by farawayshore** [xiaojieonly/Ehviewer_CN_SXJ#1429]
如题，型号是Redmi K70 Ultra,天玑9300+芯片，表站完全没问题，转用里站时只有账号初登陆正常加载，在搜索或刷新页面后就会报错。
不是很懂安卓编程，上网搜了一下报错信息，好像是因为变量没有初始化导致的。
![Screenshot_2024-09-30-16-55-27-083_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/d4699608-f67e-4815-baf6-ca9dcfbb06a8)

**Comment by yfd458** [comment]
＋1

**Comment by jmc-akatsuki** [comment]
附议，使用设备一加ACE，我前天打开1.9.8.6版本ehv的时候主页打不开，没有文字提示，昨天打开的时候提示更新1.9.8.7，覆盖安装后主页显示上述图片同样的提示，表站正常。

**Comment by simoneleisaber** [comment]
一样的，有什么求解决方法

**Comment by simoneleisaber** [comment]
一样的，求解决方法

**Comment by LeenDenVan** [comment]
有同样的报错，设备小米平板5pro

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
是不是cookie到期了？重新登录试试？

**Comment by xiaojieonly** [comment]
偶发现象还是说100%复现？

**Comment by LeenDenVan** [comment]
重新登陆账号了，问题依旧，每次进入都是如此。
![Screenshot_2024-10-02-17-25-39-268_com xjs ehview](https://github.com/user-attachments/assets/00c96172-a4e0-440c-9b04-6fbd9576e939)

> 偶发现象还是说100%复现？

**Comment by farawayshore** [comment]
> 是不是cookie到期了？重新登录试试？

更换了一次cookies，应该不是到期的问题。重新登录会好一小下，但是一刷新/检索好像就会报错，然后即便不搜索关键词也就一直报这个错了

**Comment by xiaojieonly** [comment]
1

**Comment by farawayshore** [comment]
> 偶发现象还是说100%复现？
一旦开始报错就一直只显示报错页面，目前只换cookies的时候重登过一次，重登后就是好一小下(显示画廊目录)然后开始报错。导出cookies显示的字段都是正常的，并且一开始是打开cookies锁定的。
另外就是前面有楼表示在上个版本里站会sad panda，这个我也一样，上个版本就一直上不了里站，等到这次更新后才变成报这个错
我再去试一下别的cookies和多次重登的情况

**Comment by farawayshore** [comment]
欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?

**Comment by farawayshore** [comment]
> 欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?

确认了，不是，现在又报错了

**Comment by farawayshore** [comment]
> > 欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?
> 
> 确认了，不是，现在又报错了
> 

不对劲，我开着cookies锁定好像cookies导出的时候igneous字段还是变mystery了

**Comment by farawayshore** [comment]
> > > 欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?
> > 
> > 确认了，不是，现在又报错了
> > 
> 
> 不对劲，我开着cookies锁定好像cookies导出的时候igneous字段还是变mystery了

我现在使用一个cookies反复退出重登，现在变成一旦登入立刻igneous字段就是mystery然后报空指针错

**Comment by farawayshore** [comment]
> > > > 欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?
> > > 
> > > 确认了，不是，现在又报错了
> > > 
> > 
> > 不对劲，我开着cookies锁定好像cookies导出的时候igneous字段还是变mystery了
> 
> 我现在使用一个cookies反复退出重登，现在变成一旦登入立刻igneous字段就是mystery然后报空指针错
哦，这个是我的问题，我傻逼了，把导出的错误字段导入进去了

**Comment by farawayshore** [comment]
> > > 欸，好像还真是上个cookies没锁定，但是之前应该不是，一开始是一直开着cookies锁定的，难道是最早的cookies对应的账号本身出了什么问题?
> > 
> > 确认了，不是，现在又报错了
> > 
> 
> 不对劲，我开着cookies锁定好像cookies导出的时候igneous字段还是变mystery了

但是这个问题是存在的，好像igneous字段锁定锁不住了，我把eh退出清后台再进入好像就会触发igneous变mystery

**Comment by xiaojieonly** [comment]
ip变动太频繁会这样

**Comment by farawayshore** [comment]
我手头一时半会找不到别的cookiess了，但是考虑的这个cookies短时间内可以访问，应该不是cookies对应账号的问题

**Comment by farawayshore** [comment]
> ip变动太频繁会这样

但是我测试的ip是确定的啊，就是直接用的手机流量没挂梯子

**Comment by farawayshore** [comment]
我其实怀疑可能是手机本身的某种安全防护之类的东西导致的，但是原生澎湃的机型bootloader解锁起来太麻烦了，导致手机没有root没办法关相关的东西

**Comment by xiaojieonly** [comment]
我试着修了一下，你急不？

**Comment by farawayshore** [comment]
> 我试着修了一下，你急不？

表站还能用，所以不是很急

**Comment by xiaojieonly** [comment]
[通过百度网盘分享的文件：1.9.8.8.apk](https://pan.baidu.com/s/1n4y7kLBqmU6lIGns6kyCDA )提取码：vgzw

**Comment by xiaojieonly** [comment]
你试试，还有问题没

**Comment by LeenDenVan** [comment]
我试了一下，问题已经解决了。

> [通过百度网盘分享的文件：1.9.8.8.apk](https://pan.baidu.com/s/1n4y7kLBqmU6lIGns6kyCDA)提取码：vgzw

**Comment by farawayshore** [comment]
> 你试试，还有问题没

还是锁不住，但是igneous变mystery之后报错信息变了
![Screenshot_2024-10-02-18-32-49-625_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/fae3d749-508c-478e-b235-7f435ccb7047)

**Comment by farawayshore** [comment]
> 我试了一下，问题已经解决了。
> 
> > [通过百度网盘分享的文件：1.9.8.8.apk](https://pan.baidu.com/s/1n4y7kLBqmU6lIGns6kyCDA)提取码：vgzw

你多退出清后台重进试试，这次确实比之前延续的久了一点，但是我这边还是不行

**Comment by farawayshore** [comment]
而且好像是稳定的退出清后台重进两次后出问题
以下按操作顺序排列
![IMG_20241002_184204.jpg](https://github.com/user-attachments/assets/be9b20fc-2b1c-4120-a14e-cf1a7cac94f8)

![Screenshot_2024-10-02-18-39-25-484_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/81b0b2be-9f2a-478f-8abf-c44241c53702)

![Screenshot_2024-10-02-18-39-29-820_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/f36be2b9-15d7-4c55-a1b3-8fb9899062c2)

此时退出清后台重进

![正在上传 IMG_20241002_184229.jpg…]()

此时退出清后台重进

![IMG_20241002_184251.jpg](https://github.com/user-attachments/assets/8cc88dd2-40ba-4f6e-94c9-36b4cf51e077)

**Comment by xiaojieonly** [comment]
cookie变了啊，这有点麻烦了，感觉像是账号问题

**Comment by xiaojieonly** [comment]
试过网页端退出，重进里站，然后拿最新的cookie吗？

**Comment by farawayshore** [comment]
> 试过网页端退出，重进里站，然后拿最新的cookie吗？

这个是n久前找的公用cookies，我倒是找了不止这一个，但是现在翻不大出来了。而且我有朋友也在用这个cookies，他好像就没啥问题

**Comment by xiaojieonly** [comment]
那大概是被别人顶掉了

**Comment by farawayshore** [comment]
> 那大概是被别人顶掉了

cookies还有使用人数上限的吗?在eh服务器端不是看起来应该都像是一个账号在不同地点登录一样?之前用了蛮久的也没这茬啊

**Comment by xiaojieonly** [comment]
改了

**Comment by LeenDenVan** [comment]
> > 我试了一下，问题已经解决了。
> > > [通过百度网盘分享的文件：1.9.8.8.apk](https://pan.baidu.com/s/1n4y7kLBqmU6lIGns6kyCDA)提取码：vgzw
> 
> 你多退出清后台重进试试，这次确实比之前延续的久了一点，但是我这边还是不行

试了几次依然没问题。至于cookie中igneous字段改变这件事，我这里并没有发生，我使用的是我个人的账号。

**Comment by farawayshore** [comment]
> 改了

那确实有可能，我现在好像就稳定一些

**Comment by farawayshore** [comment]
先这样吧，感谢🙏

**Comment by xiaojieonly** [comment]
好的
