### ISSUE TITLE
这种情况怎么解决？

### ISSUE THREAD

**Issue by t329-lang** [xiaojieonly/Ehviewer_CN_SXJ#143]
![Screenshot_2021-08-30-22-55-51-405_com xjs ehviewer](https://user-images.githubusercontent.com/89741485/131359335-37bf2657-89c2-4fae-925c-d86edfc99383.png)
![Screenshot_2021-08-30-22-55-57-238_com xjs ehviewer](https://user-images.githubusercontent.com/89741485/131359390-8582b820-0bb1-417c-9972-da12140d287a.png)
不知道为什么又突然进不了了，翻了墙，也关了相关的网络的选项。因为的Vpn问题吗

**Comment by xiaojieonly** [comment]
翻墙了打不开就是vpn的问题
