### ISSUE TITLE
【Bug】里站bug

### ISSUE THREAD

**Issue by Typ1calS33le** [xiaojieonly/Ehviewer_CN_SXJ#1432]
订阅，主页等需要联网的页面只有：Attempt to invoke interface method ‘int java.util.List.size()‘ on a null object reference
表站与下载没问题

**Comment by qwqcwcawa** [comment]
看看你igneous是不是mystery

**Comment by Mline0726** [comment]
> 看看你igneous是不是mystery

是，大佬应该怎么办呢？

**Comment by qwqcwcawa** [comment]
> > 看看你igneous是不是mystery
> 
> 是，大佬应该怎么办呢？

以前能正常进里站现在进不去就换个干净点的ip退出登录用账号密码重登一遍，以前也进不去就用欧美节点重新注册一个号一般等5~14天就有里站权限了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1429
