### ISSUE TITLE
本子封面图无法显示是为什么？

### ISSUE THREAD

**Issue by qwe147zxc** [xiaojieonly/Ehviewer_CN_SXJ#1435]
Why can't the cover picture be displayed？版本1.9.8.5，封面图无法显示，但正文可以查看和放大。
![Screenshot_2024-09-30-00-18-32-469_com xjs ehviewer](https://github.com/user-attachments/assets/edfb4088-5fb3-4e0b-a524-17800b8c5dd3)
![Screenshot_2024-09-30-00-19-51-456_com xjs **ehviewer](https://github.com/user-attachments/assets/05e0a60b-1be6-466b-a84b-a752071aff08)**

**Comment by xiaojieonly** [comment]
更新到最新版试试

**Comment by qwe147zxc** [comment]
虽然那之后安装新版本成功恢复封面了，但现在问题又出现，我又安装了一次也没解决
