### ISSUE TITLE
無法正確顯示頁面，只出現了錯誤訊息

### ISSUE THREAD

**Issue by carlosleung** [xiaojieonly/Ehviewer_CN_SXJ#1436]
無法正確顯示頁面，只出現了錯誤訊息
samsung galaxy tab S9 FE+
![Screenshot_20241005_154119_EhViewer](https://github.com/user-attachments/assets/a4d9d74b-2e80-403c-bed3-dbe4200c8228)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1429
