### ISSUE TITLE
1.9.8.7提示错误消息，退回老版本无法显示内容

### ISSUE THREAD

**Issue by westtt1** [xiaojieonly/Ehviewer_CN_SXJ#1438]
![Screenshot_2024-10-05-20-09-01-778_com xjs ehviewer](https://github.com/user-attachments/assets/caca6631-309e-43a0-9ccc-32f07614d129)
![Screenshot_2024-10-05-20-01-31-564_com xjs ehviewer](https://github.com/user-attachments/assets/9458206e-8c52-4af8-bdd7-267d909a535f)

**Comment by westtt1** [comment]
解决了https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/222#issue-1131450616

**Comment by happygood123** [comment]
请问是怎么解决的？
