### ISSUE TITLE
无法解析，更新之后显示Attempt to......

### ISSUE THREAD

**Issue by Serahri** [xiaojieonly/Ehviewer_CN_SXJ#1442]
打开之后显示Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
请问下怎么恢复呀之前都正常用的

**Comment by liveviiv** [comment]
我也是

**Comment by cyslm** [comment]
我也是，刚解决了，重新登录输cookie，可能身份过期了

**Comment by xiaojieonly** [comment]
楼上正解

**Comment by Serahri** [comment]
我试了一下，但是现在ignuous变成了mystery，登陆进去还是attemp to这些😭
