### ISSUE TITLE
下载内容每本都会有 10% 左右页数失败

### ISSUE THREAD

**Issue by Takkoury** [xiaojieonly/Ehviewer_CN_SXJ#1444]
![get_thumbnail](https://github.com/user-attachments/assets/c102a304-2176-48e7-be9b-1b14e0b9c266)

下载会固定有一定量的页数失败，再次启动下载任务也会失败，下载失败的页数直接在线看会显示网络错误，但其他网络行为都不会有问题

目前使用的是 1.9.8.7 版本，尝试回滚到 1.9.8.6 依然有这个问题

**Comment by qwqcwcawa** [comment]
检查网络环境，看看下载图片的时候clash的日志

**Comment by xiaojieonly** [comment]
网不好
