### ISSUE TITLE
下载标签能不能加个字母排序功能

### ISSUE THREAD

**Issue by Usefull-hash** [xiaojieonly/Ehviewer_CN_SXJ#1446]
每次导入导出以后，下载列表里的标签排序会完全乱掉，希望能给个**字母排序**的功能。
我手机上分类了近百个标签，所以很难管理。
谢谢大佬，大佬长命百岁，身体健康

**Comment by xiaojieonly** [comment]
新版本已修复导入导出的乱序问题
