### ISSUE TITLE
无法显示内容

### ISSUE THREAD

**Issue by LinHuaiSheng1** [xiaojieonly/Ehviewer_CN_SXJ#1448]
在主页面上一直显示：Attempt to invoke interface method ‘int java.util.List.size()’ on a null object reference

搜索后依然是这样。

**Comment by CoronaZero** [comment]
遇到了同样的问题，然后降级到1.9.8.6版本，同样无法加载，但没有错误提示

**Comment by zhaoshuailong** [comment]
遇到了同样的问题，降级也无法解决

**Comment by xiaojieonly** [comment]
cookie过期了，重新登录下，或者梯子换个节点
