### ISSUE TITLE
用软体进入里站就会发生错误

### ISSUE THREAD

**Issue by Nightmare1996** [xiaojieonly/Ehviewer_CN_SXJ#1449]
![Screenshot_20241011-163813_EhViewer](https://github.com/user-attachments/assets/fc17db91-85c3-4e30-bf3f-fbab8dedab70)
如图，用里站就会出现，但用表站反而没事，我需要如何调整？

**Comment by SokiArra** [comment]
同问，已经有几天了

**Comment by CoronaZero** [comment]
是的，和 #1448 一致，我也遇到了这个问题，尝试降级软件但还是报错。
同节点浏览器访问正常。

**Comment by fenri-1** [comment]
同样

**Comment by CheeseNeverDie** [comment]
+1

**Comment by 1VeniVediVeci1** [comment]
退出账号重登亲测有效

**Comment by xiaojieonly** [comment]
cookie失效了，重新登录下
