### ISSUE TITLE
请求技术支持

### ISSUE THREAD

**Issue by HarbingerGunshiplin** [xiaojieonly/Ehviewer_CN_SXJ#1452]
原软件我下载了1617个画廊，但因为bug卸载后重装并恢复画廊时发现只能恢复1559个，请问这是BUG吗？如何解决？

**Comment by xiaojieonly** [comment]
不是bug，是因为有些画廊没有下载没有对应文件所以无法恢复
能恢复1559已经很不错了

**Comment by HarbingerGunshiplin** [comment]
> 不是bug，是因为有些画廊没有下载没有对应文件所以无法恢复 能恢复1559已经很不错了

我看到手机储存目录里还是有1617个文件夹，查看了一下应该东西都没丢，那也就是说我现在只能这样看那恢复了的1559个画廊了？

**Comment by xiaojieonly** [comment]
是的
