### ISSUE TITLE
显示Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by Songluprime** [xiaojieonly/Ehviewer_CN_SXJ#1454]
版本为1.9.8.7，进入后主界面显示Attempt to invoke interface method 'int java.util.List.size()' on a null object reference。更换vpn，更改设置，重新安装均未解决，目前人在国外打开也仍然显示这段字样。

**Comment by Lusyas** [comment]
一样

**Comment by Ky1inZ** [comment]
+1，求解决方法

**Comment by xiaojieonly** [comment]
cookie失效了，重新登录

**Comment by SK-Sakuya** [comment]
走网页重登了，还是不行

**Comment by AzusagawaSakuya** [comment]
> cookie失效了，重新登录
我的重新登录了也是，外站能打开但切到里站画廊就显示这个，号是19年注册的
