### ISSUE TITLE
里站无法加载，表站正常（已确认有里站权限，浏浏览器打得开）

### ISSUE THREAD

**Issue by DrSenkin** [xiaojieonly/Ehviewer_CN_SXJ#1458]
内置exhentai host 我试过开关都不行
安全dns也试了
域名前置我也试了
尝试过清理缓存和内存

报错为：网络错误
环境为MUMU12模拟器
已安装谷歌框架
运行模拟器的是windows10

**Comment by DrSenkin** [comment]
[logcat-2024-10-18-23-57-19-075.txt](https://github.com/user-attachments/files/17437937/logcat-2024-10-18-23-57-19-075.txt)

**Comment by Tommy12pl** [comment]
我与楼主情况相同，均为无法用app打开里站，但报错略有不同，如图
![Screenshot_2024-10-20-01-20-56-552_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/590051d7-072d-43da-a562-a68a5bc85838)

**Comment by Jenye327** [comment]
我也有這個問題，這樣做就好了，最近常常eh都會出問題得重新登入：
1.登出
2.vpn連到歐美
3.登入

**Comment by xiaojieonly** [comment]
用cookie重新登录
