### ISSUE TITLE
怎么注册账号

### ISSUE THREAD

**Issue by heixiaobaiai** [xiaojieonly/Ehviewer_CN_SXJ#1459]

**Comment by Pony-CW** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/430#issuecomment-1313115909
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/432#issue-1447423697
https://ex.acg.uy/
https://t.me/acg_uy/3
