### ISSUE TITLE
搜索显示什么都找不到

### ISSUE THREAD

**Issue by GGbongde** [xiaojieonly/Ehviewer_CN_SXJ#1463]
主页界面的本都是能看的，但是如果我想搜索一个tag就显示什么也没搜到，从主页界面的本的tag点进去也是一样。版本是最新版我也重新下了好几次了
![Screenshot_2024-10-22-09-46-17-127_com xjs ehviewer](https://github.com/user-attachments/assets/dc1b0a40-d971-4618-accc-2de18d1753a6)
![Screenshot_2024-10-21-23-01-22-091_com xjs ehviewer](https://github.com/user-attachments/assets/589c4e9f-adc6-4289-91ac-edb7b1833e9c)

**Comment by xiaojieonly** [comment]
换成表站试试
