### ISSUE TITLE
attempt to invoke interface method "intjava.util.List.size()"on anull object reference问题，在重新登录后没有好，想请问大佬还有没有别的解决办法，非常感谢~

### ISSUE THREAD

**Issue by Rhongomyniad7** [xiaojieonly/Ehviewer_CN_SXJ#1465]

**Comment by iaw-dlay** [comment]
#1442

**Comment by Rhongomyniad7** [comment]
> #1442

我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。

**Comment by iaw-dlay** [comment]
> > #1442
> 
> 我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。

这个问题应该是里站cookie的19位igneous过期导致的，需要重新登录获取更新后的cookie，你在重新登陆后页面是显示【解析失败】还是依然是【attempt to invoke interface method "intjava.util.List.size()"on anull object reference】？

**Comment by Rhongomyniad7** [comment]
> > > #1442
> > 
> > 
> > 我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。
> 
> 这个问题应该是里站cookie的19位igneous过期导致的，需要重新登录获取更新后的cookie，你在重新登陆后页面是显示【解析失败】还是依然是【attempt to invoke interface method "intjava.util.List.size()"on anull object reference】？

依然是attempt to invoke interface method "intjava.util.List.size()"on anull object reference

**Comment by iaw-dlay** [comment]
> > > > #1442
> > > 
> > > 
> > > 我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。
> > 
> > 
> > 这个问题应该是里站cookie的19位igneous过期导致的，需要重新登录获取更新后的cookie，你在重新登陆后页面是显示【解析失败】还是依然是【attempt to invoke interface method "intjava.util.List.size()"on anull object reference】？
> 
> 依然是attempt to invoke interface method "intjava.util.List.size()"on anull object reference

你的ehv版本应该是1.9.8.7吧，那就可能是这个版本的问题，回退到1.9.8.6估计就可以了。

**Comment by Rhongomyniad7** [comment]
> > > > > #1442
> > > > 
> > > > 
> > > > 我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。
> > > 
> > > 
> > > 这个问题应该是里站cookie的19位igneous过期导致的，需要重新登录获取更新后的cookie，你在重新登陆后页面是显示【解析失败】还是依然是【attempt to invoke interface method "intjava.util.List.size()"on anull object reference】？
> > 
> > 
> > 依然是attempt to invoke interface method "intjava.util.List.size()"on anull object reference
> 
> 你的ehv版本应该是1.9.8.7吧，那就可能是这个版本的问题，回退到1.9.8.6估计就可以了。

.6就超时了。。。多灾多难，我要不等一个.8更新吧

**Comment by iaw-dlay** [comment]
> > > > > > #1442
> > > > > 
> > > > > 
> > > > > 我重新登录了，无论是直接用账号密码还是用cookie都没有效果，唉。。
> > > > 
> > > > 
> > > > 这个问题应该是里站cookie的19位igneous过期导致的，需要重新登录获取更新后的cookie，你在重新登陆后页面是显示【解析失败】还是依然是【attempt to invoke interface method "intjava.util.List.size()"on anull object reference】？
> > > 
> > > 
> > > 依然是attempt to invoke interface method "intjava.util.List.size()"on anull object reference
> > 
> > 
> > 你的ehv版本应该是1.9.8.7吧，那就可能是这个版本的问题，回退到1.9.8.6估计就可以了。
> 
> .6就超时了。。。多灾多难，我要不等一个.8更新吧

1.9.8.6显示超时可能是从今天中午开始的因为e站变动导致的问题，试试刚更新的1.9.8.9？

**Comment by xiaojieonly** [comment]
表站正常的话，那就是cookie问题

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/42e52991-ed75-4bc4-9bcd-188e0d62247f)
