### ISSUE TITLE
突发的解析失败

### ISSUE THREAD

**Issue by lbrony** [xiaojieonly/Ehviewer_CN_SXJ#1467]
浏览中突然开始出现解析失败情况
![Screenshot_20241025_151848](https://github.com/user-attachments/assets/1ce1084b-2d06-40d1-8678-f65f3eb813c4)
，校园网或流量表现均一致，在出现该情况前一切表现正常
现在可以进行搜索，缩略图能正常加载，但是无法阅读，无法下载

**Comment by ICEY1W32** [comment]
遇到了同样的问题，尝试重新登陆与切换代理节点都无法解决

**Comment by zhijmazi** [comment]
同样问题，开启vpn无法解决

**Comment by amamiya-yuuko-1225** [comment]
BTW，从已下载界面进入已在本地删除的画廊，还是可以正常从服务器拿到图片的。
我在墙外也遇到，和墙应该无关

**Comment by windevil04** [comment]
一样，换vpn线路也没用，但是直接进网页版能正常阅览没有问题，应该是应用的问题

**Comment by FengTeLai** [comment]
igneous未失效，里站所有画廊全都解析失败，表站正常进入画廊。

**Comment by xixueguibu** [comment]
是的，突然全部无法下载，里站的封面可以解析出来但是无法加载一直解析失败，估计是app的问题

**Comment by Steve-337** [comment]
e站更新了，等APP跟进(表站不受影响)
https://forums.e-hentai.org/index.php?showtopic=244935

**Comment by Reto911** [comment]
可能是网页端做了修改？目前看来表站是正常的

**Comment by bghjmn32** [comment]
海外ip，同样情况。

**Comment by 373578807** [comment]
貌似是因为菠萝更新了h@h服务器后端导致的  16号发了公告

“- The minimum supported version of H@H has been increased to 1.6.2. Clients still running older versions should update ASAP.

- The H@H RPC/C&C servers have been replaced. Let me know if you have any issues with H@H after this. You don't have to restart your client, they have been automatically migrated to the new servers. If you use a custom client that doesn't support auto-migration, the old servers will go offline soon, so you should update them ASAP.”

**Comment by kilahvn** [comment]
吓死我了，还以为是乌克兰对德左动手了

**Comment by 1013905619** [comment]
一样

**Comment by mslxl** [comment]
The webpage has changed, and another EHviewer client encountered the same issue. They resolved it in [this commit](https://github.com/FooIbar/EhViewer/pull/1793/commits/94f3d47663b6dc45eec9aac9a84b64b15f3ad460) by xb2016. I think this could serve as a useful reference.

However, I don’t have enough time to apply their changes due to various reasons :cry:. Hopefully, someone interested would be willing to do so.

**Comment by jingmitushuguan** [comment]
所以啥时候才能看里站

**Comment by sjzyc123** [comment]
网页版怎么看本子啊

**Comment by jkl35** [comment]
解析問題解決了，但是又換另外一個問題出現
![1000425690](https://github.com/user-attachments/assets/abda1aef-2fd7-4229-a878-840bc50afd60)

**Comment by xiaojieonly** [comment]
更新了

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/fda62e58-c21e-4a8e-9f68-3af068e05b7f)

**Comment by jkl35** [comment]
> ![image](https://private-user-images.githubusercontent.com/49278135/380170893-fda62e58-c21e-4a8e-9f68-3af068e05b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjM2MjQsIm5iZiI6MTcyOTg2MzMyNCwicGF0aCI6Ii80OTI3ODEzNS8zODAxNzA4OTMtZmRhNjJlNTgtYzIxZS00YThlLTlmNjgtM2FmMDY4ZTA1YjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEzMzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZmU2NGE4ZDgzY2RhY2ZkODM0ZDc0NzE2ZTFlZDEwNGY3NzExNGY5YjhkN2M1YjA1Yjk3OTk1MzM4OTdkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rr_FijpxZT9I6O398iZPIKzI2LCV4eo1RN0FJx0DOkk)

網頁裡沒有這個選項
