### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by xxwmdd** [xiaojieonly/Ehviewer_CN_SXJ#1469]
[](url)
![Screenshot_2024-10-25-20-47-28-119_com xjs ehviewer](https://github.com/user-attachments/assets/a9ae0724-37db-40d8-b3fe-4b298134d51c)

**Comment by HicirTech** [comment]
确实 不管是绿E还是彩E

**Comment by xiaojieonly** [comment]
更新试试，或者等一会，H@H服务器正在更新

**Comment by HicirTech** [comment]
通过[#1470](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1470#issuecomment-2437816629)中的解决方法，已经解决了p_token 以及预告no hint的问题

我觉得这个issue可以close了
