### ISSUE TITLE
E站银星会员为啥连着下十来个本子也会显示被banIP

### ISSUE THREAD

**Issue by TachibanaKanadeYYDS** [xiaojieonly/Ehviewer_CN_SXJ#147]
![Screenshot_2021-09-09-22-36-19-084_com hippo ehviewer](https://user-images.githubusercontent.com/90424535/132768151-cec12ae3-d9f2-42fa-9873-da6c2b8b0c95.jpg)
实际上是ban 账号明明额度绝对是够的。同时下载数量也没有拉满只是把多线程设置成5个。版本用的是老的1.77。是因为脚本问题吗?但是之前并没有这么严格起码也是三四十个数量才被ban。现在的状况甚至不如之前没有捐赠充值时普通会员的额度高。

**Comment by 2362918558** [comment]
一般是ip额度 你开飞行模式再联网试试

**Comment by TachibanaKanadeYYDS** [comment]
好的谢谢，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月12日(周日) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] E站银星会员为啥连着下十来个本子也会显示被banIP (#147)




 
一般是ip额度 你开飞行模式再联网试试
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TachibanaKanadeYYDS** [comment]
好像不太行，还是显示被banIP。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月12日(周日) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] E站银星会员为啥连着下十来个本子也会显示被banIP (#147)




 
一般是ip额度 你开飞行模式再联网试试
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TachibanaKanadeYYDS** [comment]
![Screenshot_2021-09-12-11-54-13-220_com xjs ehviewer](https://user-images.githubusercontent.com/90424535/132971734-9c98040b-f6c8-4a89-bf26-188e9d464d27.jpg)

**Comment by TachibanaKanadeYYDS** [comment]
我这次总得是最新1.8.10的，大概在直连模式24H内连续下了50本-60本左右被锁了。

**Comment by Sugarydream** [comment]
这个好像是连续下载会被认定为爬虫 , 下载的时候多暂停一下就可以了..

**Comment by xiaojieonly** [comment]
可能是这个IP还有别人也在下载东西导致的
