### ISSUE TITLE
1.9.8.9查看已下载的本子显示读取失败

### ISSUE THREAD

**Issue by Lornight** [xiaojieonly/Ehviewer_CN_SXJ#1474]
查看已下载的本子显示读取失败
![Screenshot_20241026_015241](https://github.com/user-attachments/assets/a9685705-616c-4356-a51e-c0ab150937c7)

**Comment by kyll02** [comment]
![Screenshot_20241026-023441](https://github.com/user-attachments/assets/74d43c0a-3895-4749-b440-9f98be2f086b)
同樣1.9.8.9

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/12bce04b-ec10-4d63-9785-188cd81b98e8)
