### ISSUE TITLE
用ehviewer點里站本子看就顯示parse error是為什麼？

### ISSUE THREAD

**Issue by aes-layout-se** [xiaojieonly/Ehviewer_CN_SXJ#1476]
如標題
只有里站會這樣，表站顯示卻沒問題

![Screenshot_2024-10-26-01-23-56-64_159c494ea8977f628e53d8d36755ba4c](https://github.com/user-attachments/assets/f58ddf3e-b852-4a23-ab51-c07d92747535)

**Comment by droid600291** [comment]
ex更新了一些東西，更新到1.9.8.9後再試試

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480
