### ISSUE TITLE
点开画廊显示解析失败

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#1478]
从25号早上起，点开任何画廊都会显示解析失败。网页版eh并没有这个问题，所以应该不是网络问题。不知道是什么情况。

**Comment by Ishimagikarp** [comment]
下载也会显示失败

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480
