### ISSUE TITLE
登录切换至里站后只有“什么都没找到”

### ISSUE THREAD

**Issue by sr-umme** [xiaojieonly/Ehviewer_CN_SXJ#1479]
![Screenshot_20241026_063754](https://github.com/user-attachments/assets/7fdafb85-3e46-45a2-8185-d2a00b2c73d5)
已经尝试清除所有数据和重新下载，依然未能解决

**Comment by sekiro1008** [comment]
我也遇到了同样问题

**Comment by xiaojieonly** [comment]
cookie过期了

**Comment by sekiro1008** [comment]
通过网站重新登录了几次，我又可以连接上里站了
