### ISSUE TITLE
安卓10切后台无应用

### ISSUE THREAD

**Issue by ARealNOOB** [xiaojieonly/Ehviewer_CN_SXJ#148]
就是打开软件，切到多任务不显示后台，每次想多任务删掉进程就很麻烦。
![Screenshot_20210916-232810](https://user-images.githubusercontent.com/79206852/133640667-95942f3d-93de-4596-a407-c9c5f8e08f0b.jpg)
手机是一加6，也不知道是我的系统问题还是软件更新后的问题。之前版本没出现过这个情况

**Comment by syokounya** [comment]
一加8 Android11也是一样的问题

**Comment by xiaojieonly** [comment]
一加的问题

**Comment by xiaojieonly** [comment]
试试最新版，如果最新版还是这样就请重新打开
