### ISSUE TITLE
无法显示预览，图片加载显示获取ptoken错误

### ISSUE THREAD

**Issue by jawnd** [xiaojieonly/Ehviewer_CN_SXJ#1480]
表里站一样的错误，能获取到画廊但内容和预览都无法加载
![Screenshot_2024-10-26-09-11-29-868_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/f7661c3f-5f53-4cca-ac58-f4a7cea7b2c1)

![Screenshot_2024-10-26-09-11-10-343_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/14de15cd-1464-4830-99f1-6d7518f238a5)

**Comment by jawnd** [comment]
app是刚更的最新版本，我恰好也是红米+澎湃

**Comment by RC-1140Fixer** [comment]
我是三星，我也这样

**Comment by jawnd** [comment]
> 我是三星，我也这样

已解决，e站设置里这样改就可以了
![photo_2024-10-25_23-21-59](https://github.com/user-attachments/assets/025618f6-3546-41bc-bb0c-0f2afa61dd8d)
![photo_2024-10-25_23-07-36](https://github.com/user-attachments/assets/84964840-3284-40f7-9499-38bec1edc8a0)

**Comment by RC-1140Fixer** [comment]
> > 我是三星，我也这样
> 
> 已解决，e站设置里这样改就可以了 ![photo_2024-10-25_23-21-59](https://private-user-images.githubusercontent.com/111733165/380355953-025618f6-3546-41bc-bb0c-0f2afa61dd8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTAyMzAsIm5iZiI6MTcyOTkwOTkzMCwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTUzLTAyNTYxOGY2LTM1NDYtNDFiYy1iYjBjLTBmMmFmYTYxZGQ4ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMjMyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjdmYjE0NjUxYjliODEyNDc0MWJkOWE2NjllN2FmYThhNjUxNWJjYzk0ZTQ4YmJkODg0OWIxNGNkYjBjODFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cnRY1MhjelZUZ4p_8V95vHcoKiSCll1sW0Hzp0ybXVY) ![photo_2024-10-25_23-07-36](https://private-user-images.githubusercontent.com/111733165/380355956-84964840-3284-40f7-9499-38bec1edc8a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTAyMzAsIm5iZiI6MTcyOTkwOTkzMCwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTU2LTg0OTY0ODQwLTMyODQtNDBmNy05NDk5LTM4YmVjMWVkYzhhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQwMjMyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODZkYTMwZjI0NmNhOGY1OGI4MmFkMzA3ZTFlYjljN2JjMjI4NjY2ODQ3NjA2NWRkODU3NDgwMzY3MDM4NmI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.25BCpf78rW6oseYnXoZVVVtM3E3yfg0EhqGyofxw6yc)

非常感谢！但是很奇怪图2我改不了40行，卡在4行了。不过依然解决了问题。

**Comment by Hw109** [comment]
自测图二可以不用更改，只要把图一 Gallery Page Thumbnail Labeling 改为 None 就可以解决了

**Comment by masklizard** [comment]
我的 Gallery Page Thumbnail Labeling 內並沒有 None的選項怎麼辦?

**Comment by yongkangz428** [comment]
亲测有效

**Comment by Uricaes** [comment]
测试有效，我改了none还是ptoken，图2还是得改成normal，40改不了无所谓

**Comment by ilikeelf** [comment]
> 自测图二可以不用更改，只要把图一 Gallery Page Thumbnail Labeling 改为 None 就可以解决了

不，还是要改，我上只改none正常使用一段时间后，下午还是出现了ptoken错误。size选项改了以后才又恢复正常。

**Comment by dgbrhv** [comment]
> 自测图二可以不用更改，只要把图一 Gallery Page Thumbnail Labeling 改为 None 就可以解决了

自测必须要要改图二，但是第二个选项改不动，只能是4

**Comment by ovozzk** [comment]
改了之后还是显示解析失败

**Comment by ovozzk** [comment]
但是切换表站之后可以成功解析  里站还是不行

**Comment by MingzhenZHANG43** [comment]
![mmexport1729926542181](https://github.com/user-attachments/assets/6d54775a-6d1f-482b-b95e-3e2a25697e10)
找到了，size改成normal就好了

**Comment by MIBRainbow6** [comment]
这里的size选项我只有normal和large，而且我默认的是normal，改large也没用。自从更新之后只有网页端能看了，哎

**Comment by GiveMeOneLastKiss** [comment]
![Screenshot_20241026_183009_com microsoft emmx_edit_14005863310362](https://github.com/user-attachments/assets/5679ec1f-30be-4d26-b3fe-ad0d7fdd9713)
设置页没有Gallery Page Thumbnail Labeling这个选项怎么办？

**Comment by 661266** [comment]
原本還可以進畫面調整，想說帳號重新登看看再調整有沒有效果，劫奪現在出現這畫面

![Screenshot_2024-10-26-21-35-04-36_159c494ea8977f628e53d8d36755ba4c](https://github.com/user-attachments/assets/c104fc10-191d-49bc-9d19-7c0c4014d788)

**Comment by 6657259** [comment]
> ![Screenshot_20241026_183009_com microsoft emmx_edit_14005863310362](https://private-user-images.githubusercontent.com/108352131/380415425-5679ec1f-30be-4d26-b3fe-ad0d7fdd9713.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTQ1ODQsIm5iZiI6MTcyOTk1NDI4NCwicGF0aCI6Ii8xMDgzNTIxMzEvMzgwNDE1NDI1LTU2NzllYzFmLTMwYmUtNGQyNi1iM2ZlLWFkMGQ3ZmRkOTcxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNDUxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDU3Y2Y1ZTc0ZDZkNDU0MTI5MTgxM2UxYzdiZWFjOGQwNmJmMDYzNDdjZDZhZDFiMWNlYjliMzczZTQ5MTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kdrLmBBsLgj-G1gQSvsS2MMYRV2XAsiogDmm2KSgHYU) 设置页没有Gallery Page Thumbnail Labeling这个选项怎么办？


使用欧美节点登入里站exhentai.org的设置页面

**Comment by cidosc** [comment]
补充，修改设置确实有效，但在应用内修改可能不被保存，建议上ex本站修改

**Comment by Forward03** [comment]
> > 自测图二可以不用更改，只要把图一 Gallery Page Thumbnail Labeling 改为 None 就可以解决了
> 
> 自测必须要要改图二，但是第二个选项改不动，只能是4

情况相同，图一默认是None 图二改为Normal 之后可以了

**Comment by huanlerenjianBA** [comment]
![Screenshot_20241027_034020_com xjs ehviewer](https://github.com/user-attachments/assets/057ac9dc-53c7-46f7-9313-23b457e7b603)
请问这种情况要怎么办

**Comment by xiaojieonly** [comment]
> ![Screenshot_20241027_034020_com xjs ehviewer](https://private-user-images.githubusercontent.com/186423431/380449328-057ac9dc-53c7-46f7-9313-23b457e7b603.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5OTQ4ODIsIm5iZiI6MTcyOTk5NDU4MiwicGF0aCI6Ii8xODY0MjM0MzEvMzgwNDQ5MzI4LTA1N2FjOWRjLTUzYzctNDZmNy05MzEzLTIzYjQ1N2U3YjYwMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwMjAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjRjM2MxYWM3NTEzOWFkOTZmZjY3NTZhODJhNDU2NDdhMzhiN2I0ZGNhZjM2NWIzNDU3MDFmMDcwZGM4NTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fg6io-81SKbkr2Z-IeqHlOxWHfbAx_jkphKHhBUW5I4) 请问这种情况要怎么办

账号被暂停了

**Comment by ntryydsnty** [comment]
vivo手机亲测有效

**Comment by ntryydsnty** [comment]
vivo测试有效

**Comment by xiaojieonly** [comment]
[1.9.8.9如果有无法下载问题的解决方案 ](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1486)

**Comment by Acero522** [comment]
> ![Screenshot_20241026_183009_com microsoft emmx_edit_14005863310362](https://private-user-images.githubusercontent.com/108352131/380415425-5679ec1f-30be-4d26-b3fe-ad0d7fdd9713.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDU1MTksIm5iZiI6MTczMDAwNTIxOSwicGF0aCI6Ii8xMDgzNTIxMzEvMzgwNDE1NDI1LTU2NzllYzFmLTMwYmUtNGQyNi1iM2ZlLWFkMGQ3ZmRkOTcxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNTAwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWZlNDJiYWRlMTBkZjYxMDJhMmJiNmFiOWNmZjE1MWQzYTc2ODcwOTJkYzg4MGFjNDZlNzY5YTBlNzVhMzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w06vVqacIANtcMtAsODMSEMx8YLzdjx1NxrTBoqYBLA) 设置页没有Gallery Page Thumbnail Labeling这个选项怎么办？

找不到这个选项的到exhentai.org设置，不是e-hentai.org

**Comment by CXSBNING** [comment]
> > 我是三星，我也这样
> 
> 已解决，e站设置里这样改就可以了 ![照片_2024-10-25_23-21-59](https://private-user-images.githubusercontent.com/111733165/380355953-025618f6-3546-41bc-bb0c-0f2afa61dd8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzE4NzksIm5iZiI6MTczMDAzMTU3OSwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTUzLTAyNTYxOGY2LTM1NDYtNDFiYy1iYjBjLTBmMmFmYTYxZGQ4ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMjE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2E5NzAzMzA4ZmY4MzBmZjE3YzYyMmVmNWI5NGQxZjJiZTg4OTJjMDU0YTBiMGIzZWQwYTU2OWNlOTEyNzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oWlFLaawBpKhBZxbWvbrRrYCpQfFApbhGpeKmukNtio) ![照片_2024-10-25_23-07-36](https://private-user-images.githubusercontent.com/111733165/380355956-84964840-3284-40f7-9499-38bec1edc8a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzE4NzksIm5iZiI6MTczMDAzMTU3OSwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTU2LTg0OTY0ODQwLTMyODQtNDBmNy05NDk5LTM4YmVjMWVkYzhhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMjE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDhhYzBjNWY1OTBmMjZmY2EzNWQ2MmNjYTUwNmQxNzZjZGQ0MThmN2M3NGJmMzU2Mjg5MjQ1ZWY3OGI0ZWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UjWkerHMpt6niTrOCi4RiqCDULK_UqZH8i8OdFrUWDI)
我oppo改完之后就能正常使用了

**Comment by TrukZero** [comment]
很怪，我可以改Normal，但下面只能选4，其他选项都切不了

**Comment by sw841352371** [comment]
如果没有选项亲测请去里站设置，里站和表站设置选项不一样的

**Comment by thxx-0263** [comment]
我的设置一直是none,还是看不了

**Comment by thxx-0263** [comment]
> 我的设置一直是none，还是看不了

https://exhentai.org/uconfig.php
可以了，在ehviewer里直接设置没用，得用网页登录里站设置才生效。

**Comment by LUrenjia114** [comment]
我使用的是公开分享的cookie，无法进入ehentai设置（显示expired login session），挂了梯子也无效（题外话，我每次再次进入里站模式的eh软件都需要退出登录重新用cookie登入否则igneous栏会显示mystery无法浏览，锁定cookie igneous功能无效，很久的问题了，问过其他人使用同一cookie没有复现，同一设备使用不同的网络包括不限于各种WiFi和数据甚至肉身更换ip也无效）

**Comment by KiWinger** [comment]
> 已解决，e站设置里这样改就可以了 ![photo_2024-10-25_23-21-59](https://private-user-images.githubusercontent.com/111733165/380355953-025618f6-3546-41bc-bb0c-0f2afa61dd8d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTYyNzgsIm5iZiI6MTczMDA5NTk3OCwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTUzLTAyNTYxOGY2LTM1NDYtNDFiYy1iYjBjLTBmMmFmYTYxZGQ4ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjEyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjliZGUyOGVjZGYxYTdhOTIwZWQxMTMxYWMyMTE0YzRhNzhiMzJjNzQzYjU5ODMxNDBkMGEzY2YzMGQwMDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.23R-5wpMzBWsSzvlv3fr98a3DWsdQ6GGvBJbA8fjCUY) ![photo_2024-10-25_23-07-36](https://private-user-images.githubusercontent.com/111733165/380355956-84964840-3284-40f7-9499-38bec1edc8a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTYyNzgsIm5iZiI6MTczMDA5NTk3OCwicGF0aCI6Ii8xMTE3MzMxNjUvMzgwMzU1OTU2LTg0OTY0ODQwLTMyODQtNDBmNy05NDk5LTM4YmVjMWVkYzhhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwNjEyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDRkNjRiMzZmYjU3OWQyZDViYzNlYjAzMmE2OGMwZGMwYTgyZGUxYmMyZjBiZGJkNjE5OTkzYjdiMjU3NTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S5vFIZpXd4jUw71fGdZNM26lgLeHWseC60k3qvJWIsc)

👍🏻 有效，好评
tips: 两项都要改，
第一项在最下，第二项在中间！

**Comment by Locked-Sirius** [comment]
我小米14修改了Gallery Page Thumbnail Labeling还是显示获取pToken错误

**Comment by RakuyoKcin** [comment]
> > ![Screenshot_20241027_034020_com xjs ehviewer](https://private-user-images.githubusercontent.com/186423431/380449328-057ac9dc-53c7-46f7-9313-23b457e7b603.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5OTQ4ODIsIm5iZiI6MTcyOTk5NDU4MiwicGF0aCI6Ii8xODY0MjM0MzEvMzgwNDQ5MzI4LTA1N2FjOWRjLTUzYzctNDZmNy05MzEzLTIzYjQ1N2U3YjYwMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwMjAzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjRjM2MxYWM3NTEzOWFkOTZmZjY3NTZhODJhNDU2NDdhMzhiN2I0ZGNhZjM2NWIzNDU3MDFmMDcwZGM4NTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fg6io-81SKbkr2Z-IeqHlOxWHfbAx_jkphKHhBUW5I4) 请问这种情况要怎么办
> 
> 账号被暂停了

显示expired login session怎么办，我是用cookie登录的

**Comment by hozzldf** [comment]
在网页中修改了设置。确认设置正确依然无效。

**Comment by ancientszhe** [comment]
已解决   normal要改，要是改了没效果看看自己看的表站里站，对应去改好了

**Comment by kubus3000** [comment]
各位大佬是如何进EH网页的我一打开网页就白屏
![屏幕截图 2024-10-29 153044](https://github.com/user-attachments/assets/c94570a8-8520-473a-9ef6-13f6eee89395)

**Comment by kubus3000** [comment]
请问各位大佬怎么进EH网页的我进去就白屏
![屏幕截图 2024-10-29 154909](https://github.com/user-attachments/assets/995e7b72-69be-4aba-93f2-f176841908cb)

**Comment by lingxuexiao** [comment]
![Screenshot_20241029_172106](https://github.com/user-attachments/assets/ccfc5401-8b74-47d3-97ea-3967d8c05353)
请问进这个页面后显示空白怎么解决？

**Comment by xiaojieonly** [comment]
都适配了，现在应该不用改了

**Comment by Han2144** [comment]
我也是前几天受到影响的，而且症状一样，可以看到书库但是打开后没有缩略图。不过我这边提示Check Failed。我本身就选了none，现在把尺寸也改成normal了但是还是一样。

**Comment by xr03061** [comment]
大佬，我的根据这些改了还是一样没变，改回去也一样，oppo一加的手机，求解

**Comment by xiaojieonly** [comment]
已修好
