### ISSUE TITLE
1.9.8.9无预览图无pToken问题

### ISSUE THREAD

**Issue by GhostBoys** [xiaojieonly/Ehviewer_CN_SXJ#1482]
里e设置里已经弄了Gallery Page Thumbnail Labeling选None但还是没有预览图和提示获取pToken错误
![Screenshot_2024-10-26-14-18-40-102_com xjs ehviewer](https://github.com/user-attachments/assets/15565f76-cae6-420c-a60a-50f4c0f617cb)
![Screenshot_2024-10-26-14-18-37-756_com xjs ehviewer](https://github.com/user-attachments/assets/3a9c5466-0ad0-448a-93bd-fe4843d7aa31)
以上是设置截图

**Comment by dgbrhv** [comment]
![380355956-84964840-3284-40f7-9499-38bec1edc8a0](https://github.com/user-attachments/assets/a5c57e4d-f8c2-42c8-93eb-fd6251eafc29)
据说还要改这个，但我第二个选项改不成40，不过size改成normal就解决了

**Comment by andylee871202** [comment]
改成normal後解決了，感謝!!!
