### ISSUE TITLE
1.9.8.9版本更新后里去进不去了

### ISSUE THREAD

**Issue by zzzgggg114** [xiaojieonly/Ehviewer_CN_SXJ#1484]
更新版本后里区刷新显示什么都没有找到 重新登陆 重新安装都试过了 网页表区能进 里区进去就是空白 该不会是账号被封了？

**Comment by TragicJoke** [comment]
我也是，更新后里站进不去，解析失败，回退版本也不行。
网页端就能正常进。

**Comment by xiaojieonly** [comment]
cookie失效了

**Comment by zzzgggg114** [comment]
> 我也是，更新后里站进不去，解析失败，回退版本也不行。 网页端就能正常进。

我搞定了 梯子换美国节点重新登陆然后保存cookie登陆就行了
