### ISSUE TITLE
1.9.8.9如果有无法下载问题的解决方案

### ISSUE THREAD

**Issue by GreensonZheng** [xiaojieonly/Ehviewer_CN_SXJ#1486]
跟无法获取ptoken的解决方案一样，进到ehentai网站里的设置，翻到最下方，找到Gallery Page Thumbnail Labeling：选择none；往上翻找到Thumbnail Settings， 里面的size选择normal项即可。
个人红米K70 Ultra澎湃系统，今天挂梯没法下载之后点画廊阅读发现ptoken错误，借助前面大佬搞的的解决方法。
希望对大家有帮助。

**Comment by GreensonZheng** [comment]
记得设置完点最下面的apply哈，其实这里就是一个问题的不同说法而已。

**Comment by madao1111** [comment]
![Screenshot_2024-10-26-21-47-25-188_com xjs ehviewer-edit](https://github.com/user-attachments/assets/ae3e6ad3-2b4c-4f4e-b220-8918bc15ee78)

![Screenshot_2024-10-26-21-47-34-914_com xjs ehviewer-edit](https://github.com/user-attachments/assets/40ec87ed-4be2-4183-9ce6-af54c9060679)

可以试试用app内的网站设置来修改

**Comment by baimao5777** [comment]
谢谢好哥哥。最下面那个我默认一直都是none，然后照楼主说的Thumbnail Settings里面的size选择normal之后终于显示出来了，下载和ptoken的问题都解决了，不知道为啥原来一直好好的，1.9.8.9更新完就出问题了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480
