### ISSUE TITLE
小米14无法直接在应用程序内直接更新

### ISSUE THREAD

**Issue by Shinozaki-Ayumi** [xiaojieonly/Ehviewer_CN_SXJ#1488]
每次更新推送更新下载后，不知道是什么程序会把已经下载好的apk直接删除，不会弹出安装窗口。
必须手动用浏览器进行下载，才能避免自动删除。
自带的杀毒检测已经全部关闭，也是无法解决。

**Comment by sacimol** [comment]
小米系统自带下载器的锅，我小米13也是这样，这下载器好像有单独的拦截机制，冻结手机管家也没用，以前经手过的华为平板以及联想平板都可以正常在线更新
