### ISSUE TITLE
isue

### ISSUE THREAD

**Issue by darthX** [xiaojieonly/Ehviewer_CN_SXJ#1493]
![Screenshot_20241027_084514_com xjs ehviewer](https://github.com/user-attachments/assets/8dc5ca78-7328-474c-978e-f2b5ad92f918)
这是什么意思？为什么我的账号被闭了？我没做过什么违规的事情吧

**Comment by MarineUSEC** [comment]
> ![Screenshot_20241027_084514_com xjs ehviewer](https://private-user-images.githubusercontent.com/60180369/380460463-8dc5ca78-7328-474c-978e-f2b5ad92f918.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDMwMjEsIm5iZiI6MTczMDAwMjcyMSwicGF0aCI6Ii82MDE4MDM2OS8zODA0NjA0NjMtOGRjNWNhNzgtNzMyOC00NzRjLTk3OGUtZjJiNWFkOTJmOTE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA0MTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNmNlNjhlYjZmMTExOGYwOWI5Y2M1YjEzYWVhOGQ5OTQ5OWQ0MjcwMzNmOGI3OGFkMGQ1OThhOGM2ZTIwYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wuRt7A1buslbqP4sAXwKBNEcf5-FKEAK987RtoJAsCU) 这是什么意思？为什么我的账号被闭了？我没做过什么违规的事情吧

看别人说这样就是寄了，找找要封多久吧，如果是时间太长那还是重新注册好了。

**Comment by xiaojieonly** [comment]
在web端重新登录获取下cookie试试
