### ISSUE TITLE
1.9.8.9更新后依然无法正常加载

### ISSUE THREAD

**Issue by iamlmy** [xiaojieonly/Ehviewer_CN_SXJ#1494]
系统：miui14.0.20
画廊信息、tag、封面、评论都能正常显示，但是画廊预览没有加载，显示为“没有预览”，点击“没有预览”提示no hints
点击阅读按钮，可以正常获取页数，但是
提示pToken获取错误

**Comment by Alexlovewoof** [comment]
我也是这样

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480

**Comment by iamlmy** [comment]
> #1480

成功了，谢谢
