### ISSUE TITLE
类原生安卓系统无法正常访问ex画廊（有可访问账号）

### ISSUE THREAD

**Issue by FunnyLu** [xiaojieonly/Ehviewer_CN_SXJ#1495]
大约3-4天前开始无法访问，eh画廊可以正常访问，且网页端可以访问ex画廊

**Comment by FunnyLu** [comment]
点击阅读加载图片不成功显示获取ptoken失败
![Screenshot_20241027-145521](https://github.com/user-attachments/assets/72d25944-bc3a-4c09-9433-ba12ca917a42)
![Screenshot_20241027-145451](https://github.com/user-attachments/assets/51e76649-87ae-4d80-81a5-61b88500ef4b)

**Comment by FunnyLu** [comment]
1.9.8.7版本可以访问eh，1.9.8.9版本无法访问eh

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480
要么是cookie失效了
