### ISSUE TITLE
请问后面会出支持鸿蒙next的eh移动端版本吗？

### ISSUE THREAD

**Issue by guoqingling** [xiaojieonly/Ehviewer_CN_SXJ#1497]
如果给您和团队带来打扰了十分抱歉，我就询问一下。
以及如果要从新适配新os，从本软件的角度，需要什么样的技术栈？谢谢您！

**Comment by UjuiUjuMandan** [comment]
安装器：该安装来源为病毒应用，禁止安装。

浏览器：根据法律法规要求以及投诉举报，此网页包含违法或违规内容，已停止访问。

应用市场：应用信息不得出现低俗、涉黄、涉赌、涉毒等违法违规内容。

中华人民共和国刑法：第三百六十四条　传播淫秽的书刊、影片、音像、图片或者其他淫秽物品，情节严重的，处二年以下有期徒刑、拘役或者管制。

**Comment by cx69237176** [comment]
next不允许安装第三方应用，不太可能会有next的版本

**Comment by xiaojieonly** [comment]
不会
