### ISSUE TITLE
可以浏览画廊，但无法下载

### ISSUE THREAD

**Issue by Tierra361433** [xiaojieonly/Ehviewer_CN_SXJ#1498]
显示下载失败...旧的本也读取失败

**Comment by ZhangQingsen** [comment]
+1我也是这样的问题，不过在浏览器看已经看不到配额了。可能是E站又改规则了而不是repo的问题。

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480
