### ISSUE TITLE
提问与建议

### ISSUE THREAD

**Issue by wjddythhk** [xiaojieonly/Ehviewer_CN_SXJ#1499]
想知道这个版本的ehviewer有没有书签保存浏览数据的功能，我以前是用那个褐色图标版本的，因为那个版本的书签功能可以保持当前浏览位置的功能，对我这种找老作品的来说很有帮助，不知道能不能增加一个这样的功能，当然，我并不熟悉这个版本的功能，如果有这样的功能可能是我的使用方法不对，请指教一下。

**Comment by xiaojieonly** [comment]
目前没有
