### ISSUE TITLE
超时的问题是怎么回事(・o・)

### ISSUE THREAD

**Issue by IronLord-coder** [xiaojieonly/Ehviewer_CN_SXJ#15]
一直在转圈，然后就会显示超时，无论内置hosts开关还是挂梯子都没有用

**Comment by xiaojieonly** [comment]
> 一直在转圈，然后就会显示超时，无论内置hosts开关还是挂梯子都没有用

网络问题，你的情况应该只是个例，不过我现在正在研究这种情况

**Comment by xiaojieonly** [comment]
> 一直在转圈，然后就会显示超时，无论内置hosts开关还是挂梯子都没有用

挂梯子的时候关掉host试试

**Comment by 974260581** [comment]
26号就开始超时了，开始是宽带网络超时，用移动网络还行，现在只能挂梯子

**Comment by xiaojieonly** [comment]
> 26号就开始超时了，开始是宽带网络超时，用移动网络还行，现在只能挂梯子

你看的表站还是里站？

**Comment by Visvaria** [comment]
不是个例吧..原版就没有问题

**Comment by xiaojieonly** [comment]
> 不是个例吧..原版就没有问题

我手机上最新版表站移动网电信网都没问题，里站得挂梯子。

**Comment by 974260581** [comment]
我看里站的，用电信宽带，原版也是这样超时的

**Comment by xiaojieonly** [comment]
我更新了内部dns，之后可能会有改善

**Comment by zsiye** [comment]
电信网，看里站就超时😭

**Comment by PuddingVitamin** [comment]
我也是电信网，目前还在调试，使用的版本是最新的1.7.6.09，最开始使用1.7.6.07无论如何网络都有问题，最开始里站不行，后来表站都看不了了。随后我（先是完全卸载了07版本然后才）下载了09版本过后发现网络一切畅通，缩略图能看，里站能上。（此时是移动数据流量），但是在大约2分钟后又出现“网络错误”的情况，不是超时，而是网络错误。跑出去挂SSR也是不行的，最后连上了（电信）wifi过后又可正常使用。互联网是混沌的，摸不着头脑，各位可参考我的解决方式，顺便再次感谢作者！

**Comment by Norhua** [comment]
我也是，一直超时联通的4G和电信的宽带都不行，我已经试了，有三个版本的eh了，都是网络超时
