### ISSUE TITLE
Ex里站无法登录成功的问题. (界面显示 Sad Panda)

### ISSUE THREAD

**Issue by MrHGinko** [xiaojieonly/Ehviewer_CN_SXJ#150]
刚好是因为之前的 [版本](https://github.com/seven332/EhViewer) 始终没有评论加载因此检查了下更新

发现之前的已经停止维护 于是找到大佬这里

反复调整高级有关网络的设置 以及 挂梯子均无法连接ex, 表站倒是可以直连.

而seven332大佬这个可以通过vpn连接到ex.

看了下加载链接都没问题 细入就知识盲区了 = = 

界面提示均为sad panda. 而实际exhentai确实可以访问, 有可能是网络配置出错了吗?

**Comment by Arturia-Pendragon** [comment]
我得解决方案是

1. 设置->画廊站点，切换到 e-hentai 表站
2. 退出登录，退出APP
3. 打开手机的梯子
4. 开启APP，在登录界面选择网页登录（这步最重要），不要通过APP内的用户名密码框登录
5. 网页登录成成功后，退回到APP首页漫画列表，刷新两下，确保可以正常浏览表站的漫画
6. 设置->画廊站点，重新切换到 exhentai 里站

如果你的问题跟我样，此时退回到APP首页，就可以刷新出里站的漫画列表了，这问题怀疑是APP内部登录无法写入cookie，导致里站解析权限认证过不去

**Comment by linzhen666** [comment]
不行

**Comment by MrHGinko** [comment]
@xiaojieonly 作者大大你好, 可能是这个原因导致的问题

应该是启动时登录网址为 表站eh, 我在pc端登录时cookie只存在member_id与pass_hash, 重点 第三个igneous不存在 (pc端)
此时移动端登录(通过网页还是直接在app上登录) 登录后查看cookie会发现 igneous的值为 mystery.

我这边正是这个原因导致了登录后里站始终连接不上(界面显示sad panda).

而在pc端(登录后)访问里站, 发现网站cookie的igneous存在 且有值 (表站登录不存在该字段). 直接复制再转移到app上使用cookie登录, 登录后正常访问里站.

包括之前所说的 [版本](https://github.com/seven332/EhViewer)  也存在这个问题, 通过网页登录还是app登录 都是在表站登录的, 此时获取不到igneous值, 进而导致切换里站出现访问不了的情况.

**Comment by MrHGinko** [comment]
> 我得解决方案是
> 
> 1. 设置->画廊站点，切换到 e-hentai 表站
> 2. 退出登录，退出APP
> 3. 打开手机的梯子
> 4. 开启APP，在登录界面选择网页登录（这步最重要），不要通过APP内的用户名密码框登录
> 5. 网页登录成成功后，退回到APP首页漫画列表，刷新两下，确保可以正常浏览表站的漫画
> 6. 设置->画廊站点，重新切换到 exhentai 里站
> 
> 如果你的问题跟我样，此时退回到APP首页，就可以刷新出里站的漫画列表了，这问题怀疑是APP内部登录无法写入cookie，导致里站解析权限认证过不去

感谢你的回复, 目前我这边问题通过pc端登录访问里站获取cookie的形式解决了, 应该是eh调整了cookie策略, 我这边是因为登录表站无法获取igneous值导致的

**Comment by MrHGinko** [comment]
非常抱歉重新打开此issue, issue有大量相关重复提交因此重新打开. 此方法我已多次验证可行
无奈本人技浅, 无法提交相关PR修复

也有请各位大佬看一下.

**Comment by xiaojieonly** [comment]
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

**Comment by MrHGinko** [comment]
谢谢大佬更新 ! 🎉

**Comment by Mironken** [comment]
谢谢上面大佬的解决方案，孩子可以正常上了，还以为是账号被ban了谢谢大佬

**Comment by cloud21-beluga** [comment]
成功解决了！感谢大佬分享！

**Comment by niganmahaihaieiyo** [comment]
![Screenshot_2023-06-16-04-56-47-795_io github nekoinverter ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136757207/8cbb9e37-5e68-4e02-aebe-136a195d16d8)
跟上面的版本貌似不大一样，为啥我这没有ex的内置txt啊，用了楼上大佬的方法也进不去，要么ip被ban，要么badpanda，搞了一个晚上了都

**Comment by niganmahaihaieiyo** [comment]
换了1.9.5之后就成这样了，不知道还是不是badpanda这个问题
![Uploading Screenshot_2023-06-16-05-24-11-534_com.xjs.ehviewer.jpg…]()

**Comment by niganmahaihaieiyo** [comment]
版本更新之后就这样了
![Screenshot_2023-06-16-05-24-11-534_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136757207/3ab65406-a239-4dc0-920d-3dab5d626484)

**Comment by xiaojieonly** [comment]
检查cookie，没问题的话挂梯子

**Comment by KumoKami03** [comment]
我是科技苦手，請問有什麼梯子可以裝的嗎，我也是進不到ex

**Comment by jjjdjsn** [comment]
本来使用正常，在只能加载一两张图片以后卸载重下就出现sad panda了，有没有大佬知道解决方法

**Comment by F0ksay** [comment]
> @xiaojieonly 作者大大你好, 可能是这个原因导致的问题
> 
> 应该是启动时登录网址为 表站eh, 我在pc端登录时cookie只存在member_id与pass_hash, 重点 第三个igneous不存在 (pc端) 此时移动端登录(通过网页还是直接在app上登录) 登录后查看cookie会发现 igneous的值为 mystery.
> 
> 我这边正是这个原因导致了登录后里站始终连接不上(界面显示sad panda).
> 
> 而在pc端(登录后)访问里站, 发现网站cookie的igneous存在 且有值 (表站登录不存在该字段). 直接复制再转移到app上使用cookie登录, 登录后正常访问里站.
> 
> 包括之前所说的 [版本](https://github.com/seven332/EhViewer) 也存在这个问题, 通过网页登录还是app登录 都是在表站登录的, 此时获取不到igneous值, 进而导致切换里站出现访问不了的情况.

正解，感谢。另外提醒大伙儿一句，按照这个原理，实在不会搞就卸载APP然后重装。安装完挂梯子，登陆方式选择网页登录，然后站点选择直接选里站登录。

**Comment by F0ksay** [comment]
> 我是科技苦手，請問有什麼梯子可以裝的嗎，我也是進不到ex

既然你已经上github了，那么要么你有梯子，要么你在墙外。一般这两种网络条件下都可以进里站了。请检查cookie，或者卸载APP重装，登陆方式选择网页登录，然后站点选择直接选里站登录。

**Comment by qscuzi** [comment]
@F0ksay 请问cookie怎么获得啊？我这边，试过卸载APP重装登录方式，网页登录，然后选里站了，但还是半个熊猫头，说
![Screenshot_20241112_162651_com xjs ehviewer](https://github.com/user-attachments/assets/f11c0aa1-4afc-48bf-94a9-db817fd26b0d)
什么都没有找到
![Screenshot_20241112_162651_com xjs ehviewer](https://github.com/user-attachments/assets/1c169706-b9bc-4756-90d5-81ecbc97aab0)

**Comment by F0ksay** [comment]
> @F0ksay 请问cookie怎么获得啊？我这边，试过卸载APP重装登录方式，网页登录，然后选里站了，但还是半个熊猫头，说
> ![Screenshot_20241112_162651_com xjs ehviewer](https://github.com/user-attachments/assets/f11c0aa1-4afc-48bf-94a9-db817fd26b0d)
> 什么都没有找到
> ![Screenshot_20241112_162651_com xjs ehviewer](https://github.com/user-attachments/assets/1c169706-b9bc-4756-90d5-81ecbc97aab0)
> 

https://nicebowl.fun/11#C3S4
参考此链接，内附完整教程

**Comment by redshotacon** [comment]
9 位 igneous cookie 已于 2024-11-19 凌晨吊销，请不要再使用。那么这个账号应该如何再次进入里站呢？

**Comment by F0ksay** [comment]
> 9 位 igneous cookie 已于 2024-11-19 凌晨吊销，请不要再使用。那么这个账号应该如何再次进入里站呢？

你是cookie吊销不是账号注销吧，PC重新登陆获取cookie信息即可。请翻看我上边发的教程链接。

**Comment by xwxyz** [comment]
**分享一个梯子，有免费用**
[袋鼠加速](https://dsvp1n.live/share.html?channel=s3)

**Comment by JCDBZ** [comment]
网站也无法登录里站了 请问是账号被办了吗 有没有什么补救措施 总之先谢过诸位大佬

用了很久的号上不去 以前胡乱建的号上去里站了 能看loli内容 很变态 不知道为什么

**Comment by F0ksay** [comment]
> 网站也无法登录里站了 请问是账号被办了吗 有没有什么补救措施 总之先谢过诸位大佬
> 
> 用了很久的号上不去 以前胡乱建的号上去里站了 能看loli内容 很变态 不知道为什么

我猜测单纯是cookies失效了。在我第一次回复之后一段时间，我发现只用cookies之类的也能登录，未必通过网页登录。具体教程见https://nicebowl.fun/11#C3S4

**Comment by shuiNone** [comment]
大佬们你们好，我的情况有点抽象：
我可以通过网站直接访问里站，但是通过里站的cookie在不同版本的软件上都无法登录到里站。我尝试了其他的软件，可以通过相同的cookie访问里站。请问大佬们这可能是什么问题呢？PS:我的设备是小米14，hyperOS 3.0.5.0WNCCNXM
因为有其他软件了所以不急（，不过还是习惯这个软件，希望有大佬可以提供建议
