### ISSUE TITLE
1.9.8.9版本关于ex问题

### ISSUE THREAD

**Issue by weishenshi** [xiaojieonly/Ehviewer_CN_SXJ#1502]
更新1.9.8.9后里站简略图里显示没有预览，打开后显示No hints如何解决？
![Screenshot_2024-10-27-23-25-05-008_com xjs ehviewer](https://github.com/user-attachments/assets/9af0bd08-1504-425b-8176-eb51f8fcfcdb)

**Comment by Snowenh** [comment]
同问，覆盖回1.9.8.7之后打开直接变解析失败了，不过搜索和封面还是正常的

**Comment by Snowenh** [comment]
看前面那个带攻略tag的

**Comment by weishenshi** [comment]
看了攻略解决了，把里站设置里面的关于size的那个auto改成normal就正常了

**Comment by weishenshi** [comment]
看了攻略解决了，把里站设置里面的关于size的那个auto改成normal就正常了

**Comment by xuechen105** [comment]
这个我弄不了，打开设置之后是一片空白

**Comment by xuechen105** [comment]
> 这个我弄不了，打开设置之后是一片空白

![Uploading Screenshot_20241028_003147.jpg…]()

**Comment by 480533688** [comment]
> 看了攻略解决了，把里站设置里面的关于size的那个auto改成normal就正常了

没错就是这个，解决了
