### ISSUE TITLE
不知道怎么设置，我打开了那个e站的里站打开是一片空片，设置不了那个nome

### ISSUE THREAD

**Issue by xuechen105** [xiaojieonly/Ehviewer_CN_SXJ#1503]
开了vpn也不行
![Screenshot_20241028_003147](https://github.com/user-attachments/assets/bd49c9d3-ab2b-44ee-bb2b-a70d2655b950)

**Comment by xiaojieonly** [comment]
重新登录

**Comment by xuechen105** [comment]
> 重新登录

还是一样，一片空白，都完全没有显示
