### ISSUE TITLE
获取pToken错误，且无法进入网站设置

### ISSUE THREAD

**Issue by mushifuchen** [xiaojieonly/Ehviewer_CN_SXJ#1504]
![Screenshot_20241028_044741_com_xjs_ehviewer_GalleryActivity](https://github.com/user-attachments/assets/218105e3-32eb-4043-b9b6-be6d04ea1b05)
![Screenshot_20241028_043216_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/f8da7e59-c582-4729-bda7-4da9b5cba193)

有看到老哥们的图但是找不到这个设置页面，逛了很久论坛也没有找到只好求助一下

**Comment by timesea2004** [comment]
![1000021583.jpg](https://github.com/user-attachments/assets/1c511202-e9fa-4e38-90c3-fa1357ab4598)

![1000021604.jpg](https://github.com/user-attachments/assets/279b204d-5056-4571-bb9a-0fa26d1574b0)

直接从app内选：设置→EH→ehentai设置就可以了。如果你app内部进不去设置的话，也可以点这个链接
https://e-hentai.org/uconfig.php
