### ISSUE TITLE
更新后预览图全部一样为第一张，并且配额问题我这里始终是0，有没有佬一样的怎么解决的

### ISSUE THREAD

**Issue by fengci66** [xiaojieonly/Ehviewer_CN_SXJ#1509]
![Screenshot_20241029_005139_com xjs ehviewer](https://github.com/user-attachments/assets/943cec74-f1b8-4408-9e8e-25ae45bd3858)
![Screenshot_20241029_005151_com xjs ehviewer](https://github.com/user-attachments/assets/3d1ea26c-91d3-4f54-a73f-b8ef326d7469)
![Screenshot_20241029_005201_com xjs ehviewer](https://github.com/user-attachments/assets/5cd844ee-ef5f-44c7-be55-d738c25b1e87)

**Comment by Pandaaaa906** [comment]
一样

**Comment by Bacardiff** [comment]
打开主页设置把Eh网站设置里这个勾选上
![Uploading IMG_20241029_161918.jpg…]()

**Comment by Bacardiff** [comment]
打开主页设置把Eh网站设置里这个勾选上
![IMG_20241029_161918](https://github.com/user-attachments/assets/6d4472d0-be16-4a27-8dd9-3a58b8ced5c7)

**Comment by xiaojieonly** [comment]
更新了
