### ISSUE TITLE
ex里站似乎更新了cookies登录方式 , 可能导致无法登录

### ISSUE THREAD

**Issue by Sugarydream** [xiaojieonly/Ehviewer_CN_SXJ#151]
概述:
  最近手机端本软件登不上里站 , 但电脑浏览器可以.
  经检查cookies , 发现手机端软件显示igneous的值为mystery , 而电脑端cookies多了一项sk键值项.
  但是ipb_pass_hash和ipb_member_id一样
  个人推测是否是软件上没有此设置导致该问题 .
  但是个人目前没有学习dart & flutter , 看不懂 , 不会自查QAQ
  ( 也可能是中国IP封禁也说不一定~~ )

电脑端环境:
  Win10 Google Chrome 92
  美国IP登录 真人率1%
  cookies截图:
![Inked屏幕截图 2021-09-26 203251_LI](https://user-images.githubusercontent.com/91417189/134808305-3ae6296f-4159-454b-881d-c72ba5abdc7c.jpg)

手机端环境:
  红米K30 ehviewer1.8.1.0
  中国IP 真人度74%
  ( 电脑码的,回头补截图 )

不太清楚这样描述有没有问题 ..
总之有什么需要的信息尽管问 , 第一次发这种东西有点不知所措XD
就这样ww

**Comment by MrHGinko** [comment]
是这样的 相关里站无法登录的问题 请查看issue #150

**Comment by xiaojieonly** [comment]
楼上正解
