### ISSUE TITLE
希望更改对精神控制类tag的误翻

### ISSUE THREAD

**Issue by theUtopian666** [xiaojieonly/Ehviewer_CN_SXJ#1510]
mind control这个tag的直译是精神控制，然而在eh的中文tag里翻译成了催眠，然而催眠和精神控制是被包括的关系，催眠只是精神控制中的一个小分类，在这里翻译成催眠是不严谨的。

我个人希望能将mind control的翻译调整成精神控制，然后参考pixiv，加上hypnosis这个tag作为催眠的tag。

以及mind break这个tag直译是精神破坏而不是洗脑，洗脑的话应该使用mindwash或者mindwashing，这是专有词汇了，况且洗脑和精神破坏的区别还是挺大的，甚至精神破坏都不一定属于精神控制这个大分类，使用药物等手段也可以使人精神崩溃。

我认为这会导致一些投稿者错误的理解了tag的意思，填写了错误的tag，导致部分观众点进tag却发现作品中并没有自己想要的内容后，在评论区和另一些认为这么打tag没问题的人吵起来的情况。我希望这种情况越少越好。

我希望这个意见能够传达到eh的相关人员那里。

**Comment by Pony-CW** [comment]
你应该去这个地方
https://github.com/EhTagTranslation/Database/
![ResizedImage_2024-10-29_08-45-44_2071.jpg](https://github.com/user-attachments/assets/252e917b-1aa8-49fc-95cb-07ffba9ca355)

包括这个地方
https://ehtt.vercel.app/list/all
![ResizedImage_2024-10-29_08-44-32_2383.jpg](https://github.com/user-attachments/assets/5f6f3b23-14de-4033-9d4b-76b221c7266b)

**Comment by Pony-CW** [comment]
不过确实e站也写成催眠
![ResizedImage_2024-10-29_08-51-46_1297.jpg](https://github.com/user-attachments/assets/3cb7625a-5130-4daa-825f-dfd7e5f67a57)

想改的话，发e站论坛有关tag的帖子吧

**Comment by Pony-CW** [comment]
> 不知道能不能直接改

**Comment by theUtopian666** [comment]
> > 不知道能不能直接改

试过了，不能直接改（悲

**Comment by xiaojieonly** [comment]
我先关了，还有问题可以重新打开
