### ISSUE TITLE
求助：冇法解决“解析失败”问题，已尝试版上issue所有方法

### ISSUE THREAD

**Issue by jger8780** [xiaojieonly/Ehviewer_CN_SXJ#1513]
具体情况：
人在香港，号用很多年了，前几天我还是能正常使用里站，结果别天就发生以下情况
![Screenshot_20241029_072845_EhViewer](https://github.com/user-attachments/assets/7e24ebb5-080c-4bcd-b01a-32dea67eadcd)
![Screenshot_20241029_072854_EhViewer](https://github.com/user-attachments/assets/e77aba90-585b-4c81-87ba-4d8243d7b3ef)
连接vpn、重新下载更新版本、改igneous及其他方法也试过，什至换号都不行，我不知道为什么能登陆帐号但不能用，一直跳解析失败。
求求大家救救孩子，已经不小心弄没了100G本子了（还没备份），我真的想继续用eh看大家说骚话，求求義父们了

**Comment by bloodydust** [comment]
我也一样，今天点进去看本子突然就解析失败了，我还以为是没更新的原因，原来更新了也无法解决吗

**Comment by slwy1303357042** [comment]
> 我也一样，今天点进去看本子突然就解析失败了，我还以为是没更新的原因，原来更新了也无法解决吗

我更新之后解决了解析失败的问题，能点进本子了，但是点进本子后划到最底下想看本子缩略图会显示没有预览，点击左上角的阅读进去会显示获取ptoken错误，还是看不了

**Comment by slwy1303357042** [comment]
> > 我也一样，今天点进去看本子突然就解析失败了，我还以为是没更新的原因，原来更新了也无法解决吗
> 
> 我更新之后解决了解析失败的问题，能点进本子了，但是点进本子后划到最底下想看本子缩略图会显示没有预览，点击左上角的阅读进去会显示获取ptoken错误，还是看不了

我的问题解决了，在#1480里有解决方法

**Comment by bloodydust** [comment]
> > > 我也一样，今天点进去看本子突然就解析失败了，我还以为是没更新的原因，原来更新了也无法解决吗
> > 
> > 
> > 我更新之后解决了解析失败的问题，能点进本子了，但是点进本子后划到最底下想看本子缩略图会显示没有预览，点击左上角的阅读进去会显示获取ptoken错误，还是看不了
> 
> 我的问题解决了，在#1480里有解决方法

我更新版本后能正常用了，但发生了奇怪的事。以前我用eh时是不能挂vpn的，否则就会警告连接vpn啥啥啥，甚至因此被禁用过几天账号。但现在我不连vpn没法用，反倒连上vpn能正常用了，也没有之前的警告啥的

**Comment by xiaojieonly** [comment]
更新了
