### ISSUE TITLE
dalao 这个荣耀手机更新应用后 显示什么都没有找到

### ISSUE THREAD

**Issue by accentgod** [xiaojieonly/Ehviewer_CN_SXJ#1514]
![Screenshot_20241029_095821_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/02ec4a8f-6395-4a2f-ab7e-8942c390c2f2)
![Screenshot_20241029_095741_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/684e26f1-67df-40cb-ab2a-afc96c8b5f8a)
无论是直连 还是关掉域名前置 连接上小飞机也是不行   一直显示没有没有找到

**Comment by xiaojieonly** [comment]
cookie过期了
