### ISSUE TITLE
关于预览图重复的问题

### ISSUE THREAD

**Issue by 1601252126** [xiaojieonly/Ehviewer_CN_SXJ#1518]
预览图显示重复图像，但进入大图显示正常
![Screenshot_20241029_200942_com xjs ehviewer](https://github.com/user-attachments/assets/b6b7dcc7-32ee-40b1-a1b1-0ed5194fa5fe)

**Comment by xiaojieonly** [comment]
更新到最新版

**Comment by 1601252126** [comment]
已修复，感谢
