### ISSUE TITLE
我想问一下，各位大佬，我这是怎么回事，解析失败，下载本子也下载不了

### ISSUE THREAD

**Issue by whoami233754** [xiaojieonly/Ehviewer_CN_SXJ#1519]
预览图现在可以了，但是还是解析失败，然后上版本开始就下载本子速度没有，然后下载不了。之前一直好好的，我试了裸连和翻墙都没有用。
![Uploading Screenshot_2024-10-29-20-26-10-47_159c494ea8977f628e53d8d36755ba4c.jpg…]()

**Comment by EricEricEr** [comment]
有紧急更新了，重下一下可能就好了？

**Comment by xiaojieonly** [comment]
更新到最新版
