### ISSUE TITLE
为什么进不去ex?

### ISSUE THREAD

**Issue by iGongi2004** [xiaojieonly/Ehviewer_CN_SXJ#1522]
[
![Screenshot_2024-10-30-03-20-11-147_com xjs ehviewer](https://github.com/user-attachments/assets/7978ffd6-86da-4c08-83fb-e9303102e229)
](url)

**Comment by baim5** [comment]
我也进不去了里站了，之前都能的

**Comment by overload000** [comment]
一样

**Comment by xiaojieonly** [comment]
cookie过期
