### ISSUE TITLE
提问：现在为什么看图看着看着就gp不足了

### ISSUE THREAD

**Issue by qqzzwU** [xiaojieonly/Ehviewer_CN_SXJ#1527]
之前记得都是显示配额不足，然后换个梯子节点就好了，现在为什么都不行了，一直显示gp不足，这个gp是什么新的东西吗

**Comment by xiaojieonly** [comment]
现在gp和账号挂钩了，不和ip挂钩

**Comment by xiaojieonly** [comment]
gp是配额的意思

**Comment by Pony-CW** [comment]
https://ehwiki.org/wiki/Gallery_Points
https://github.com/FooIbar/EhViewer/issues/1563#issuecomment-2310031101

**Comment by Pony-CW** [comment]
还有这个
https://github.com/FooIbar/EhViewer/issues/1375#issuecomment-2201905018
