### ISSUE TITLE
点进去图片无法加载

### ISSUE THREAD

**Issue by zmsmao** [xiaojieonly/Ehviewer_CN_SXJ#153]
点进去图片无法加载

**Comment by hduxbdisjsjjdjdh** [comment]
我也有同样的问题

**Comment by zphiroude1234** [comment]
一样，也无法下载。早前还能直接看图和下载

**Comment by pleasecall** [comment]
把那个安全dns（doh）关了重启软件试试

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
