### ISSUE TITLE
点击任何作品都会解析失败

### ISSUE THREAD

**Issue by nmnmtttt** [xiaojieonly/Ehviewer_CN_SXJ#1530]
点击任何作品都会跳这个 打开了vpn ，只有exhentai站点会这样
![Screenshot_20241031_233916_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/df0d97ad-5bd0-4179-b994-61c62068240e)

**Comment by dojustme** [comment]
下载最新版

**Comment by nmnmtttt** [comment]
thx
