### ISSUE TITLE
某些画廊解码失败，疑似因为webp格式

### ISSUE THREAD

**Issue by DRNeunzehn** [xiaojieonly/Ehviewer_CN_SXJ#1531]
app为1.9.9.0的最新版本
我在uploader:-terry-的最新几个本子都发现，封面和缩略图都显示不出来。无论点进去在线阅读还是下载之后再看，每一张都会显示解码失败
个人排查原因，疑似为这个上传者最新几本都用.webp格式

但同样用了.webp格式的画廊exhentai.org/g/3108447/e4b0f6b59e/，则虽然也出现封面和缩略图全都显示不出来的问题，但点进去看的话，除了封面那一张解码失败外都能解码

同时别的画廊都没有出问题

**Comment by xiaojieonly** [comment]
嗯，为了适配webp，下一版将不再支持安卓九以下的手机
