### ISSUE TITLE
有部分画廊仍然会显示解析失败

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#1532]
能点开画廊，但无法加载封面和缩略图，点开后显示解析失败，按照#1480的攻略设置仍然不行，无论里站还是表站
![Screenshot_20241101_202757_EhViewer](https://github.com/user-attachments/assets/593cc15d-0a43-4a05-9326-9a97eae3431d)
![Screenshot_20241101_202801_EhViewer](https://github.com/user-attachments/assets/7065ab59-a386-4716-b47b-513765933b46)
![Screenshot_20241101_202809_EhViewer](https://github.com/user-attachments/assets/1e4e91b5-1315-40cc-967f-516bfbdf7604)

**Comment by zhang42905** [comment]
俺也一样。

**Comment by xiaojieonly** [comment]
应该是webp格式的画廊，下一版提供支持，但是下一版将不再支持安卓9以下的手机
