### ISSUE TITLE
画廊还是显示解析失败

### ISSUE THREAD

**Issue by nanliang6666** [xiaojieonly/Ehviewer_CN_SXJ#1536]
画廊还是显示解析失败
根据#1480将Gallery Page Thumbnail Labeling设置为none（一直是none），正则表达式在Thumbnail Settings也改成了normal
可还是没有用，仍然解析失败
![Screenshot_20241103_135307_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/7b4f5417-96ec-4f33-a0f9-af3111be7897)
![Screenshot_20241103_135304_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/eec27f60-1c32-4c26-878a-310c17cabf6f)

**Comment by xiaojieonly** [comment]
更新到最新版
