### ISSUE TITLE
浏览画廊时显示网络错误

### ISSUE THREAD

**Issue by kerybotu** [xiaojieonly/Ehviewer_CN_SXJ#1537]
在使用VPN连接的情况下，Ehviewer出现了画廊加载问题，具体表现如下：

表站：主界面能够正常显示画廊的标题和标签，但缩略图无法加载（显示为撕裂的图片图标）。进入画廊后，评论可以正常显示，但缩略图依旧加载失败。进入阅读模式时，会显示几秒钟的加载动画（期间下行速率约为10kb/s），之后提示“网络错误”。同时，画廊内容无法加载和下载（卡在0%）。

![Screenshot_2024_11_03-19_42_19](https://github.com/user-attachments/assets/d2519a3a-891b-4a73-ab49-6071727e53f6)
![Screenshot_2024_11_03-19_43_33](https://github.com/user-attachments/assets/1cd0986c-09b5-450f-8651-b4a969dea93c)
![Screenshot_2024_11_03-19_43_04](https://github.com/user-attachments/assets/b34ae23b-b952-4490-9e19-63c81372be17)
![Screenshot_2024_11_03-19_42_10](https://github.com/user-attachments/assets/d63295aa-f48e-48be-bbf1-a4b752a8a53f)

切换至里站后，主界面直接显示“什么都没找到”。确认拥有里站访问权限，并且使用相同VPN节点在浏览器网页版可正常访问。 
 
浏览器访问情况：表站和里站均可正常访问，未遇到任何错误提示
尝试操作：在软件高级设置中已多次调整代理、hosts、安全DNS、域名前置等选项，均无效

环境说明：  
系统：安卓7（原生安卓系统）
网络：WiFi 2.4Ghz，全局VPN（以上过程均使用相同VPN节点且IP未受限）  
软件版本：最新版 1.9.9.0

**Comment by HicirTech** [comment]
同样的问题，通过清理数据解决…记得先备份后清理， something to do with cache …

**Comment by kerybotu** [comment]
> 同样的问题，通过清理数据解决…记得先备份后清理， something to do with cache …

我试过了，清数据没用，打开后还是网络错误

**Comment by xiaojieonly** [comment]
vpn换个节点

**Comment by Louis-Yang21** [comment]
在开启VPN的情况下显示网络错误，可尝试这样解决：
设置->高级->代理，如果当前选项是"系统代理"，则改为“直接连接”，之后恢复正常
估计是EH的代理模式和我们自己的VPN相冲突了导致的

**Comment by nehzil-D** [comment]
遇到同样问题，上述尝试均无效，系统也是安卓7
