### ISSUE TITLE
更换手机并成功导入设置后，已经下载到本地，但画廊已下架的漫画，重新读取现实为下载失败，无法打开观看

### ISSUE THREAD

**Issue by xiaojunsp** [xiaojieonly/Ehviewer_CN_SXJ#1538]
![Screenshot_2024-11-03-22-40-34-860_com xjs ehviewer](https://github.com/user-attachments/assets/88176a75-eced-428b-bd02-23cd2df86890)
![Screenshot_2024-11-03-22-40-42-927_com xjs ehviewer](https://github.com/user-attachments/assets/6a6bd732-915d-4ae0-8316-5906126d06a3)
环境：
红米K50，安卓14

**Comment by xiaojieonly** [comment]
1
