### ISSUE TITLE
搜索汉化组等名称有许多画廊看不见了

### ISSUE THREAD

**Issue by QIYUnie** [xiaojieonly/Ehviewer_CN_SXJ#1539]
搜索汉化组或者一些关键词的时候几天前还可以搜索到数十个相关内容这俩天只能看到几条搜索结果，但是已经收藏的本子可以再去收藏里正常打开，点击收藏里打开的本子的相关tag也看不到本子

**Comment by xiaojieonly** [comment]
分配的H@H服务器问题

**Comment by QIYUnie** [comment]
那请问有什么解决办法嘛
