### ISSUE TITLE
三星s20，APP被识别成了启动器

### ISSUE THREAD

**Issue by hanserJimor** [xiaojieonly/Ehviewer_CN_SXJ#154]
![Screenshot_20211002-192409_Permission controller](https://user-images.githubusercontent.com/75347131/135714040-c1608f8b-ad4f-4c84-8b34-b1fc78e58120.jpg)

**Comment by hanserJimor** [comment]
主要是跟三星pay的一个快捷操作冲突了，有点小难受_(:з」∠)_

**Comment by solitary-sails** [comment]
一加也是这样，而且新版本还出现了软件不显示在后台管理菜单里。不知道是不是因为被识别成了启动器。

**Comment by xiaojieonly** [comment]
哈！！！！，我去研究下

**Comment by linckr** [comment]
MIUI也一样，MIUI 12.5 K40p 21.8.4版本

**Comment by xiaojieonly** [comment]
已修复
