### ISSUE TITLE
更新到1.9.9.0后无法读取webp格式的画廊

### ISSUE THREAD

**Issue by chensite6** [xiaojieonly/Ehviewer_CN_SXJ#1541]
无论是封面还是缩略图都无法显示，点开后显示解析失败
![Screenshot_2024-11-04-18-32-11-663_com xjs ehviewer](https://github.com/user-attachments/assets/4ff8a512-b635-4ff1-b62d-b121f7d3cd4b)
![Screenshot_2024-11-04-18-32-08-162_com xjs ehviewer](https://github.com/user-attachments/assets/f729c868-7cc7-42ee-8d2c-5d0b9ba34708)
![Screenshot_2024-11-04-18-31-49-283_com xjs ehviewer](https://github.com/user-attachments/assets/8f4eb48a-b060-49a8-beff-8427616cc4fc)

**Comment by Weih2236** [comment]
![Screenshot_2024-11-04-18-34-52-074_com xjs ehviewer](https://github.com/user-attachments/assets/0ac4d2df-7f6a-4897-b010-f43fadc4b01d)
遇到一样的问题，但是内容能正常阅读

**Comment by chensite6** [comment]
> ![Screenshot_2024-11-04-18-34-52-074_com xjs ehviewer](https://private-user-images.githubusercontent.com/133908714/382723104-0ac4d2df-7f6a-4897-b010-f43fadc4b01d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTczMzUsIm5iZiI6MTczMDcxNzAzNSwicGF0aCI6Ii8xMzM5MDg3MTQvMzgyNzIzMTA0LTBhYzRkMmRmLTdmNmEtNDg5Ny1iMDEwLWY0M2ZhZGM0YjAxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2JmOTE2YTQ2MjFjYjg5ZTVhNjczYjUxNGQ4NGNjMTcwYjhiOWZlNjFlNDI2ODAzZTE5NWViMjNhYWNlZjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KwLMLYjDgPvs0oKN3Tr9CsoE679bqKp7-xYWVhHicuI) 遇到一样的问题，但是内容能正常阅读

请问你是自己设置过了吗？可以下载无法正常显示的画廊吗？

**Comment by Lununz** [comment]
也遇到这个问题，下载过来也一样解析失败

**Comment by Johnjolno** [comment]
一样问题+1

**Comment by smoothstone3** [comment]
same
