### ISSUE TITLE
1.9.9.1更新后里区超时

### ISSUE THREAD

**Issue by zzzgggg114** [xiaojieonly/Ehviewer_CN_SXJ#1547]
更新之后正常使用 第二天就进不去一直显示超时 表区正常能看 现在重新网页登陆 用之前保存的cookie登陆都不行 是cookie过期了吗

**Comment by zzzgggg114** [comment]
补充 电脑上里区正常能进 而且读取了电脑上的cookie复制到手机cookie登陆还是超时

**Comment by xiaojieonly** [comment]
更新到最新版试试
