### ISSUE TITLE
1991还是灰色封面 灰色预览 可以下载 但是无法解析

### ISSUE THREAD

**Issue by yxzh-rng** [xiaojieonly/Ehviewer_CN_SXJ#1549]
如题1991还是灰色封面 灰色预览 可以下载 图片可以在手机内查看 但是APP内无法解析 
更新不易 V50略表感谢

**Comment by 2333lcx** [comment]
同样的问题，补充一下图片
![c864f07d5476e8dabfe03ca85e82e41a](https://github.com/user-attachments/assets/334167a8-def4-428f-9088-57995ff76a02)
![dbf7102a493e2c0ac97048900a42efe9](https://github.com/user-attachments/assets/b796e159-5209-4ce8-9cb2-fa8851ab8aa9)

**Comment by yxzh-rng** [comment]
> 相同的问题，补充一下图片 ![c864f07d5476e8dabfe03ca85e82e41a](https://private-user-images.githubusercontent.com/151045292/383412144-334167a8-def4-428f-9088-57995ff76a02.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzAyNTEsIm5iZiI6MTczMDg2OTk1MSwicGF0aCI6Ii8xNTEwNDUyOTIvMzgzNDEyMTQ0LTMzNDE2N2E4LWRlZjQtNDI4Zi05MDg4LTU3OTk1ZmY3NmEwMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwNTEyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODgzZDY2NzA1OGFjOTA3NDlmNzk2MGM5MDAyMTE4YWZjMzRjM2MxNDA0MjJjNzJhZjhlOTY0OTEzNDcwN2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._-HqP-u1-4rn3Z_1mWdXXn2uwPXW3KCVor-upgmfHXQ) ![dbf7102a493e2c0ac97048900a42efe9](https://private-user-images.githubusercontent.com/151045292/383412159-b796e159-5209-4ce8-9cb2-fa8851ab8aa9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzAyNTEsIm5iZiI6MTczMDg2OTk1MSwicGF0aCI6Ii8xNTEwNDUyOTIvMzgzNDEyMTU5LWI3OTZlMTU5LTUyMDktNGNlOC05Y2IyLWZhODg1MWFiOGFhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwNTEyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjVmNTQwMjM1ZmEwNDY0MzI4MWViMDA2Mjc0M2UwZGY3YjNhYjZiYmE0MDFkOTliYzZlN2UyMDc0ODgwOTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h3oD3GhqW_dKYTtW_4q8YDlWn60x2icbyTnZCdzTHFM)

本问题更新到1.9.9.2已经解决 ：）
