### ISSUE TITLE
下载页面点击暂停有概率闪退

### ISSUE THREAD

**Issue by mrbyfwg** [xiaojieonly/Ehviewer_CN_SXJ#155]
[logcat-2021-10-03-05-46-48-943.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/7272287/logcat-2021-10-03-05-46-48-943.txt)
5点45左右复现了几次

**Comment by xiaojieonly** [comment]
目前无法有效避免此问题，能问下最新版还有这问题吗？

**Comment by xiaojieonly** [comment]
1.9.2.4(未发版) 已修复
