### ISSUE TITLE
更新后图片保存下来无法修改时间

### ISSUE THREAD

**Issue by hdjsheifnjs** [xiaojieonly/Ehviewer_CN_SXJ#1550]
以前图片保存下来后可以进行时间修改，我会用这个功能改图片排序，新版之后保存的图片无法修改时间了。
虽然图片格式能改回来但麻烦了很多，想问下以后图片格式是默认为wedp了吗
![Screenshot_2024-11-05-14-30-41-455_com.miui.gallery-edit.jpg](https://github.com/user-attachments/assets/424bb423-0a92-4cce-a3c9-d60daf3befc0)

**Comment by hdjsheifnjs** [comment]
知道是文件格式导致的，但wedp格式有办法改成jpg格式吗？

**Comment by hdjsheifnjs** [comment]
在文件管理里改成jpg就正常了不会有什么问题，就是比以前麻烦了很多。以后e站的图片格式都默认是wedp了吗

**Comment by Pony-CW** [comment]
我邮件看到过来说一下…webp后缀名改jpg，它还是webp…建议百度补习一下图片格式的区别与转换

我想e站可能会一直用webp来降低存储负担

**Comment by hdjsheifnjs** [comment]
> 我邮件看到过来说一下…webp后缀名改jpg，它还是webp…建议百度补习一下图片格式的区别与转换
> 
> 我想e站可能会一直用webp来降低存储负担

好吧，我懂的不多可能是理解错了什么，不过后缀改成jpg确实能解决我的问题，所以说e站之后是默认wedp了吧
以及跑个题想再麻烦下问个问题，最近我的gitHub打开图片是跳转到浏览器打开，想问下要怎么解决？

**Comment by Pony-CW** [comment]
> 好吧，我懂的不多可能是理解错了什么，不过后缀改成jpg确实能解决我的问题，所以说e站之后是默认wedp了吧
> 以及跑个题想再麻烦下问个问题，最近我的gitHub打开图片是跳转到浏览器打开，想问下要怎么解决？

我的app一直这样，所以我不知道怎么解决，或许这就是正常的
最好关闭议题，本来我也是看改后缀行为看不惯才过来的，如果没有关于ehviewer的话题就可以关了这个issue了
有也重新开一个
