### ISSUE TITLE
怎么数据导出不了啊

### ISSUE THREAD

**Issue by sjzyc123** [xiaojieonly/Ehviewer_CN_SXJ#1554]
![Screenshot_20241105_185428_com.xjs.ehviewer_edit_92070608525533.jpg](https://github.com/user-attachments/assets/e2ded043-1508-4fac-8701-4f98f8d9510a)

是收藏太多了吗？

**Comment by sjzyc123** [comment]
谁能说说是怎么回事啊

**Comment by sjzyc123** [comment]
求解😭

**Comment by xiaojieonly** [comment]
你没找对导出目录吧？

**Comment by xiaojieonly** [comment]
实在不行用WiFi迁移
