### ISSUE TITLE
1.9.9.1以及2的白屏闪退。

### ISSUE THREAD

**Issue by 0901mana** [xiaojieonly/Ehviewer_CN_SXJ#1555]
在下载画集总大小9.94G，页数1631页的内容时，发生白屏闪退（后续重新打开app，再次点击下载内容依旧会重复该行为）。
不清楚是内存问题还是手机型号问题，荣耀30。（目前第一次下近10g内容，也许是画集大小过大缘故？）

**Comment by deadline85** [comment]
我也是好像都是在看那种一千多张的或者体积比较大的图集都会有概率白屏闪退

**Comment by xiaojieonly** [comment]
1
