### ISSUE TITLE
1.9.9.2 用rar來啟動閱讀軟體，會停止運作

### ISSUE THREAD

**Issue by zxc102635** [xiaojieonly/Ehviewer_CN_SXJ#1557]
![Screenshot_20241106-002800656 (1)](https://github.com/user-attachments/assets/72223301-1fa5-4875-8e69-3b8cac59df6a)

![Screenshot_20241106-002353209 (1)](https://github.com/user-attachments/assets/43557ff0-b493-4756-a43b-1894d5c63db6)

**Comment by xiaojieonly** [comment]
1

**Comment by tongsang** [comment]
退回老版本后能正常打开，😅还以为是我更新系统更炸了

**Comment by xiaojieonly** [comment]
在修了
