### ISSUE TITLE
1.9.9.1封面预览图加载不出来，内容解析错误

### ISSUE THREAD

**Issue by 1653421500** [xiaojieonly/Ehviewer_CN_SXJ#1558]
![Screenshot_20241106_002330](https://github.com/user-attachments/assets/e12107db-b3b3-4c11-9502-2f82058e22e9)
![Screenshot_20241106_002845](https://github.com/user-attachments/assets/204e2b08-3f7c-458e-87d0-579597695089)

**Comment by Paracehll** [comment]
> ![Screenshot_20241106_002330](https://private-user-images.githubusercontent.com/110712594/383231129-e12107db-b3b3-4c11-9502-2f82058e22e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjgxMzgsIm5iZiI6MTczMDgyNzgzOCwicGF0aCI6Ii8xMTA3MTI1OTQvMzgzMjMxMTI5LWUxMjEwN2RiLWIzYjMtNGMxMS05NTAyLTJmODIwNThlMjJlOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNzMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDczZmQ4ZTdmYjRlOGFhZDM0ZWVmZTU1NjgwMzVkOGY0OGY0ZjlhYWU2NDBiYTE0OGMyYmI3MjFmNzAwZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MCb7dr-DaIe_p2u2craGrK2TkGfz1Fbnj-e5ZBY_GMU) ![Screenshot_20241106_002845](https://private-user-images.githubusercontent.com/110712594/383231494-204e2b08-3f7c-458e-87d0-579597695089.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjgxMzgsIm5iZiI6MTczMDgyNzgzOCwicGF0aCI6Ii8xMTA3MTI1OTQvMzgzMjMxNDk0LTIwNGUyYjA4LTNmN2MtNDU4ZS04N2QwLTU3OTU5NzY5NTA4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNzMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzE5ZDVjNjFhMmFmOTI2YzM3NTFmNjU5ZmE5OGJhZjFkMDllN2Y2MTM0MDAyZjk5MGE4Y2VlOWE1Y2MwMjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ng3jNCDgbnmTxFWPaEnW13kHcS9WspQmJ0dLwMmcvZs)

我 1.9.9.0 遇到同樣問題，更新到最新版 1.9.9.2 就解決了

**Comment by 1653421500** [comment]
> > ![屏幕截图_20241106_002330](https://private-user-images.githubusercontent.com/110712594/383231129-e12107db-b3b3-4c11-9502-2f82058e22e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjgxMzgsIm5iZiI6MTczMDgyNzgzOCwicGF0aCI6Ii8xMTA3MTI1OTQvMzgzMjMxMTI5LWUxMjEwN2RiLWIzYjMtNGMxMS05NTAyLTJmODIwNThlMjJlOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNzMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDczZmQ4ZTdmYjRlOGFhZDM0ZWVmZTU1NjgwMzVkOGY0OGY0ZjlhYWU2NDBiYTE0OGMyYmI3MjFmNzAwZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MCb7dr-DaIe_p2u2craGrK2TkGfz1Fbnj-e5ZBY_GMU) ![屏幕截图_20241106_002845](https://private-user-images.githubusercontent.com/110712594/383231494-204e2b08-3f7c-458e-87d0-579597695089.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjgxMzgsIm5iZiI6MTczMDgyNzgzOCwicGF0aCI6Ii8xMTA3MTI1OTQvMzgzMjMxNDk0LTIwNGUyYjA4LTNmN2MtNDU4ZS04N2QwLTU3OTU5NzY5NTA4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNzMwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzE5ZDVjNjFhMmFmOTI2YzM3NTFmNjU5ZmE5OGJhZjFkMDllN2Y2MTM0MDAyZjk5MGE4Y2VlOWE1Y2MwMjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ng3jNCDgbnmTxFWPaEnW13kHcS9WspQmJ0dLwMmcvZs)
> 
> 我 1.9.9.0 遇到同样问题，更新到最新版本 1.9.9.2 就解决了

是这样更新完毕之后解决了问题
