### ISSUE TITLE
求求你请为安卓8以下提供严重维护更新

### ISSUE THREAD

**Issue by HangHorn1354** [xiaojieonly/Ehviewer_CN_SXJ#1560]
是这样的，我目前安卓8.1.0，我没有其他手机有安卓9以上了，我只能用1.9.9.0，目前最后一个版本支持安卓8以下，开始经常遇到无法解折了，现在新增的都无法观看，我很快感到烦躁，因为看不见新的东西了，希望你们为安卓8以下提供非常严重的维护更新，不提供**新功能**即可，拜托，我很需要它，现在几乎看不见新的了，你只需要紧急维护修复即可，不新增功能就行了，拜托了，很急

别问我为什么不买新手机，问就是没钱😭
![Screenshot_2024-11-06-01-49-57-11](https://github.com/user-attachments/assets/b46979c1-84b6-461e-9808-a759be70dc92)
![Screenshot_2024-11-06-01-50-21-31](https://github.com/user-attachments/assets/cb30a143-f56c-42b9-bc41-eee933224710)
![Screenshot_2024-11-06-01-51-43-34](https://github.com/user-attachments/assets/f97b5960-baa0-4ec9-aeb7-f50b5a3e8e01)

**Comment by HangHorn1354** [comment]
抱歉，有点急了，我才看见最近已关闭的Issue，我明白了，为了适配webp格式才不支持安卓8以下，但是否有何办法解决该问题呢？希望帮帮忙，实在没有办法的话，请关闭该Issue并设为不在计划内

非常抱歉浪费你的时间，我算是暂时再也看不见新的了

**Comment by kofwe** [comment]
我也没办法看了 手机厂商都不给老机型配升级包了  得了 而且我e站账号已经忘了 都是cookie登录的 现在这样子只能拜拜了

**Comment by HangHorn1354** [comment]
> 我也没办法看了 手机厂商都不给老机型配升级包了 得了 而且我e站账号已经忘了 都是cookie登录的 现在这样子只能拜拜了

Kofwe，你好，我目前也不知道为什么，查了一下webp格式兼容支持解码，CSDN那边说的好像是安卓4以上就可以解码了，好像是BitmapFactory这个解码？我到现在不明白为了适配webp格式才不得不已不支持安卓8以下，到现在还是不明白，我很希望作者xiaojieonly为安卓8以下提供严重维护更新，另用其他办法修复适配webp格式什么的，我不知道能说什么了，唉😭

**Comment by xiaojieonly** [comment]
我试试

**Comment by xiaojieonly** [comment]
顺利的话今天就能支持

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/70c911f2-40e8-421c-8015-18af53256cca)
目前来看是好了，但不保证稳定性，不过后面出bug会慢慢修

**Comment by HangHorn1354** [comment]
> ![image](https://private-user-images.githubusercontent.com/49278135/383458982-70c911f2-40e8-421c-8015-18af53256cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MTIyOTIsIm5iZiI6MTczMDkxMTk5MiwicGF0aCI6Ii80OTI3ODEzNS8zODM0NTg5ODItNzBjOTExZjItNDBlOC00MjFjLTgwMTUtMThhZjUzMjU2Y2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE2NTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ODdmYWU2ZGYxMWVmZDA0MTYzMzAzMzQwZmMxMjVkYmY0ODAyNmJhYTFmY2UwZWEyYzBmNGI4NjM1NjU3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zrFFnEGBNGi9FGrW8JeJ_vi2O-vlWyI4ihkxUhwrKt8) 目前来看是好了，但不保证稳定性，不过后面出bug会慢慢修

那谢谢作者，我会等你发布更新！
