### ISSUE TITLE
读取错误

### ISSUE THREAD

**Issue by asasasp** [xiaojieonly/Ehviewer_CN_SXJ#1561]
常用解决方案已经看过了，全没用
不知道咋就突然变这样了，系统一直没更新，是安卓13，但突然就读取不了了，很怪...
图片可以正常下载，下载到的图可以用相册打开。但用app全都读取错误，部分本子的图打开甚至会直接闪退。
关权限再开的方法已经用过了，没效果。删除文件重下也没效果

**Comment by xiaojieonly** [comment]
权限没给可能
