### ISSUE TITLE
下载的都读取失败，还没法重新下载

### ISSUE THREAD

**Issue by sjzyc123** [xiaojieonly/Ehviewer_CN_SXJ#1562]
![Screenshot_20241106_083134_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/09ca869c-ce8f-4e00-90cb-258cac64b4b0)

怎么解决啊

**Comment by xiaojieonly** [comment]
重新下载试试

**Comment by sjzyc123** [comment]
> 重新下载试试

不行啊，根本下载不了，其他的也下载不了
