### ISSUE TITLE
下载列表缩略图加载出现问题

### ISSUE THREAD

**Issue by AgCl-cdqz** [xiaojieonly/Ehviewer_CN_SXJ#1563]
自1.9.9.0更新后，原本可以正常显示的缩略图变为如图1所示的状态
![Screenshot_20241106_111918_com xjs ehviewer_edit_147874794319622](https://github.com/user-attachments/assets/8910589a-cf6e-4341-b1f2-4ad8aa92c277)
查看出现问题画廊所在文件夹发现.thumb文件正常存在且可以打开，如图2与图3所示
![Screenshot_20241106_112117_bin mt plus](https://github.com/user-attachments/assets/70852c90-a733-488e-9695-4cf863245a39)
![Screenshot_20241106_112248_bin mt plus](https://github.com/user-attachments/assets/e7bfa9a6-f4a5-4746-877c-36ddbba38aad)
另外，新下载的画廊与进入画廊详细界面查看过的可以恢复正常，如图4与图5所示
![Screenshot_20241106_112448_com xjs ehviewer](https://github.com/user-attachments/assets/0ebc16f8-4a14-4274-844f-fab06a3e061f)
![Screenshot_20241106_112452_com xjs ehviewer](https://github.com/user-attachments/assets/28861e02-85d5-4f14-9463-78b88642497c)
安卓版本为12，目前软件更新至最新1.9.9.2仍然有此问题

**Comment by xiaojieonly** [comment]
1，已尝试修复，顺利的话今天更新
