### ISSUE TITLE
1.9.2打开部分原画下载的画廊后应用会崩溃

### ISSUE THREAD

**Issue by moku3636** [xiaojieonly/Ehviewer_CN_SXJ#1564]
[logcat-2024-11-06-12-08-54-132.txt](https://github.com/user-attachments/files/17641572/logcat-2024-11-06-12-08-54-132.txt)

**Comment by Ray-maker1** [comment]
我也是，那个有栖川什么的一打开就闪退

**Comment by flppt** [comment]
我也一样，昨天新下载的几个打开直接就闪退

**Comment by xiaojieonly** [comment]
已修
