### ISSUE TITLE
1.9.9.1解析错误，1.9.9.2网络错误，完全无法访问

### ISSUE THREAD

**Issue by 861360455** [xiaojieonly/Ehviewer_CN_SXJ#1565]
1.9.9.1一直无法裸连，上周挂梯子还能看，这周挂梯子也解析错误。更新1.9.9.2之后一直显示网络错误。尝试过回退版本直到1.9.8.2也没解决问题

**Comment by 861360455** [comment]
> 1.9.9.1一直无法裸连，上周挂梯子还能看，这周挂梯子也解析错误。更新1.9.9.2之后一直显示网络错误。尝试过回退版本直到1.9.8.2也没解决问题

**Comment by 861360455** [comment]
更正一下，回退到1.9.8.2

**Comment by xiaojieonly** [comment]
cookie过期了
