### ISSUE TITLE
关于重采样下载的文件后缀显示问题

### ISSUE THREAD

**Issue by FengTeLai** [xiaojieonly/Ehviewer_CN_SXJ#1566]
现在E站新画廊重采样是webp格式，但下载下来的还是显示为jpg格式。
希望以后能完善下文件后缀问题。

例：重采样为jpg文件，下载的后缀就显示jpg，gif显示gif，webp显示webp。
按E站画廊图片对应的文件后缀显示。

这不是重要诉求，不急。

**Comment by xiaojieonly** [comment]
已修
