### ISSUE TITLE
从下载界面访问已下载但画廊被下架的漫画会导致崩溃，1.9.9.2

### ISSUE THREAD

**Issue by cykalet** [xiaojieonly/Ehviewer_CN_SXJ#1568]
![logcat-2024-11-07-01-37-03-443.txt](https://github.com/user-attachments/files/17650908/logcat-2024-11-07-01-37-03-443.txt)

**Comment by xiaojieonly** [comment]
更新试试

**Comment by cykalet** [comment]
> 更新试试
问题还在，例如タクロヲ堂 g:"takurowo-dou$"的本子。但还是有个别能正常看
![logcat-2024-11-18-18-35-36-800.txt](https://github.com/user-attachments/files/17798869/logcat-2024-11-18-18-35-36-800.txt)
