### ISSUE TITLE
非常抱歉！我发现1.9.9.3出问题了

### ISSUE THREAD

**Issue by HangHorn1354** [xiaojieonly/Ehviewer_CN_SXJ#1569]
@xiaojieonly 作者大大，又是我，非常抱歉！对不起！🙇‍♂️🙇‍♂️🙇‍♂️

的确如你所说，我更新到1.9.9.3后发现一些事情，在安卓8以下，在我的手机上试图适配解码webp格式后，的确成功解码了，但是发现两个大问题和一个不知道怎么回事的问题，阅读观看时图片大小不正常显示，只抓捕到左上角一部分，而预览那方面异常合页，怎么说呢，类似两页合到一页了，还有预览另一方面有时候不正常完整显示，不知道是不是网络问题，截图如下
![Screenshot_2024-11-07-01-54-46-95](https://github.com/user-attachments/assets/3b8521f7-e720-469b-a4e6-4d5caa3c6114)
![Screenshot_2024-11-07-02-00-13-90](https://github.com/user-attachments/assets/571b89cd-7b6d-430d-81a1-493f89abcd00)
![Screenshot_2024-11-07-02-01-39-44](https://github.com/user-attachments/assets/7845ca30-c855-4815-ba36-dcce69932611)
![Screenshot_2024-11-07-01-59-25-82](https://github.com/user-attachments/assets/609bb5be-0f59-44f0-bdc7-396983c99dba)

**Comment by HangHorn1354** [comment]
5555😭，作者大大，实在非常抱歉，又麻烦你了，虽然成功让安卓8以下适配解码webp格式了，但是来了这几个bug，我可以继续等，别担心我😭

**Comment by xyzk903** [comment]
+1，天塌了要😭

**Comment by HangHorn1354** [comment]
> +1，天塌了要😭

我属于没有想到我就这么一个简单的要求是给安卓8以下维护更新适配webp格式，不要求新增功能那种，结果没想到引来了两个大问题，本来早点睡觉安净，结果我看见作者半夜发布，我立刻熬大夜，现在2点40分了，这回又要麻烦作者大大再次修复了，实在对不起作者了😭😭

**Comment by CapitalGrin** [comment]
这图你也是水灵灵的就这么发出来了……

**Comment by sjzyc123** [comment]
请问我的本地收藏数据导不出来，该怎么办啊？

**Comment by HangHorn1354** [comment]
> 这图你也是水灵灵的就这么发出来了……

不发出来我也不好描述情况啊，只能冒着风险被封号硬是发出去😭😭

**Comment by chiya695** [comment]
我也遇到这种情况了，还以为是自己设置出了问题😭

**Comment by HangHorn1354** [comment]
害，也不知道作者什么时候更新

我稍微想说一下，别在意，其他作者版本的Ehviewer居然没问题，我属于没想到，但唯一麻烦的是只能翻墙，但这里基本不用翻墙，是我很喜欢很需要的重要第一优点，所以我一直很希望这位作者版本Ehviewer保持下去维护更新

**Comment by xiaojieonly** [comment]
安卓8以下的手机不想再维护了，走一步看一步吧，太累了

**Comment by HangHorn1354** [comment]
> 安卓8以下的手机不想再维护了，走一步看一步吧，太累了

好吧，能理解，那我不再缠着了，祝你顺利，我有点难绷qwq
