### ISSUE TITLE
版本是1.9.9.2，用ex的话大部分本子的预览图加载不出来。

### ISSUE THREAD

**Issue by amustl** [xiaojieonly/Ehviewer_CN_SXJ#1571]
![Screenshot_20241107_072825_com xjs ehviewer](https://github.com/user-attachments/assets/645a2965-ac18-4a46-a76f-48cced60c286)

**Comment by amustl** [comment]
但是换了表站节点就能加载出来

**Comment by 1902520039** [comment]
一样的人问题

**Comment by 1902520039** [comment]
一样的问题

**Comment by 332d** [comment]
我也一样

**Comment by qwe147zxc** [comment]
我是基本除了更新前已经看过的本子外，剩下的本子封面都加载不出来

**Comment by xiaojieonly** [comment]
更新一下
