### ISSUE TITLE
1.9.9.3版本问题反馈:阅读第三方压缩包文件会闪退

### ISSUE THREAD

**Issue by jipril** [xiaojieonly/Ehviewer_CN_SXJ#1572]
1.9.9.1版本之前都可以把压缩包文件用ehviewer打开，直接阅读，通过这个方法可以自行下载很多版权漫画看。更新到1.9.9.2和1.9.9.3后，用ehviewer打开压缩包文件时会加载一会儿然后直接闪退。

**Comment by jipril** [comment]
![Screenshot_2024-11-07-08-27-38-387_com xjs ehviewer](https://github.com/user-attachments/assets/8a4d0723-7b37-43fd-bea5-336db6f926bd)
![Screenshot_2024-11-07-08-27-45-187_com miui thirdappassistant](https://github.com/user-attachments/assets/bb138adf-ddd9-42b1-be4a-cb206a2fbef7)
![Screenshot_2024-11-07-08-27-52-461_android](https://github.com/user-attachments/assets/f9c30c7f-07a7-4c38-b821-60e0ec3b3b8e)

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
在修了

**Comment by xiaojieonly** [comment]
已修
