### ISSUE TITLE
麻烦各位大佬有空帮我看一眼，我手机app不小心屏蔽的标签好像取消不掉了

### ISSUE THREAD

**Issue by 2394079412** [xiaojieonly/Ehviewer_CN_SXJ#1574]
我手机选择屏蔽的标签网页端显示不出来，网页端屏蔽的手机却可以显示，而且哪怕我网页端订阅了标签也没有用，不会显示
有大佬知道手机端的屏蔽标签该如何取消吗
![qq_pic_merged_1730948154661](https://github.com/user-attachments/assets/c6a6e739-2a87-42bc-8f51-494d70c81b10)
![Screenshot_2024-11-07-10-55-15-62_159c494ea8977f6](https://github.com/user-attachments/assets/b13518df-8b7b-4124-b190-5aa2377a1969)

**Comment by xiaojieonly** [comment]
右上角不是有设置按钮吗？里面可以删

**Comment by 2394079412** [comment]
> 右上角不是有设置按钮吗？里面可以删

没用的，我app里面屏蔽的标签那里没有显示，所以我不知道哪里能删了

**Comment by xiaojieonly** [comment]
去浏览器上删e-hentai.org
