### ISSUE TITLE
本地收藏数据导不出来，也导入不了，是不是软件跟外置存储器连接不上了啊

### ISSUE THREAD

**Issue by sjzyc123** [xiaojieonly/Ehviewer_CN_SXJ#1575]
![Screenshot_20241106_103414_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/96c7cf6f-0f35-4373-ab83-5e935d884b37)

![Screenshot_20241107_123620_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/5db19048-48c0-46bd-92cd-8cd3ffe563f2)

![Screenshot_20241107_123630_bin.mt.plus.jpg](https://github.com/user-attachments/assets/a9f4b279-aee8-412c-a55e-243cbfa4ad41)

**Comment by xiaojieonly** [comment]
检查下存储权限给没给，不然的话建议用WiFi迁移
