### ISSUE TITLE
已下載畫廊的縮圖問題

### ISSUE THREAD

**Issue by GhMoose** [xiaojieonly/Ehviewer_CN_SXJ#1578]
版本1.9.9.3
大部份已下載畫廊的縮圖仍舊無法顯示，顯示死圖
已嘗試清除快取重讀仍無法解決問題
必須點進畫廊讓其重載才能恢復，但對已下架的畫廊就沒辦法了

再麻煩您了，謝謝

**Comment by xiaojieonly** [comment]
是的，建议关闭系统的垃圾清理功能

**Comment by GhMoose** [comment]
不好意思，請問意思是縮圖死了就只能點畫廊重讀嗎？
下架的讀不到的就沒辦法了？

謝謝
