### ISSUE TITLE
列表封面预览图无法加载，但是详情页的预览图加载速度很快

### ISSUE THREAD

**Issue by aidaidjian** [xiaojieonly/Ehviewer_CN_SXJ#158]
![Screenshot_2021-10-13-22-42-47-386_com xjs ehviewer](https://user-images.githubusercontent.com/53386448/137160219-80125012-6f3d-41ec-8204-3e6a3e258798.jpg)
![IMG_20211013_225735](https://user-images.githubusercontent.com/53386448/137160245-38b3618a-deb8-4ee2-8ba6-bcb0cf42ab1d.jpg)
![Screenshot_2021-10-13-22-51-03-610_com xjs ehviewer](https://user-images.githubusercontent.com/53386448/137160266-947c62c3-c9fb-47c0-bee1-0a62e901dc94.jpg)
![Screenshot_2021-10-13-23-04-09-813_com xjs ehviewer](https://user-images.githubusercontent.com/53386448/137160584-f7a7ce63-f846-4d08-9420-ada915091063.jpg)

**Comment by MrHGinko** [comment]
可以尝试在设置中找到修复缩略图链接选项并开启
EhViewer -> EH -> 修正缩略图链接

**Comment by xiaojieonly** [comment]
也可以试试最新版~
