### ISSUE TITLE
更新几个版本后下载好的漫画封面全部消失

### ISSUE THREAD

**Issue by djfjdk** [xiaojieonly/Ehviewer_CN_SXJ#1581]
正常画廊里的封面还正常但是下载好的漫画所有的封面都消失了，需要一个一个点开画廊界面才能重新加载封面，有同样的人遇见这个问题吗？我下载了很多漫画不可能真的一个一个点去重新加载吧。
![Screenshot_2024-11-08-19-40-33-644_com xjs ehviewer](https://github.com/user-attachments/assets/da474b8d-4f8c-4180-a5fd-1a5bacb39a3e)

**Comment by Rex50208** [comment]
同樣問題+1 尤其是古早時期下載的

**Comment by baiyingui** [comment]
我倒是也有这个问题，点进去重新加载封面过后，清楚ehv后台回来封面还是没有
