### ISSUE TITLE
1.9.9.3 点击阅读时崩溃

### ISSUE THREAD

**Issue by kerybotu** [xiaojieonly/Ehviewer_CN_SXJ#1583]
![Screenshot_2024_11_08-22_36_58](https://github.com/user-attachments/assets/c650dfad-2942-494e-a8bf-5757d4a01f16)
![Screenshot_2024_11_08-22_37_02](https://github.com/user-attachments/assets/3faf61ee-1ebb-4ffc-8f6e-9707f84ba16c)
![Screenshot_2024_11_08-22_36_48](https://github.com/user-attachments/assets/b99e4f63-d17b-4f91-90db-e8c82f5bdee0)
全程挂梯访问，浏览器测试IP没有ban
站点：表站
如图所示，前面的界面略缩图加载不出来，点击阅读以后直接崩溃，显示“EhViewer已停止运行”。
尝试退回以前版本，测试了很多个版本，但是依然略缩图加载不出来，然后阅读界面直接网络错误。
尝试清除数据重新打开，问题依旧。

现在只能从E站网页端下载存档然后用EhViewer打开阅读（因为实在是受不了网页端阅读那高延迟），虽然我GP用不完（玩HV玩的），但是一个个下载太麻烦了，不想一个个下载。

操作系统：Android 7（原生安卓）
架构：arm64
软件版本：1.9.9.3
全程挂梯访问，但是去掉梯子问题依旧。
尝试游客登录，问题依旧。

**Comment by xiaojieonly** [comment]
换个新设备吧，安卓7版本太低了，最好是安卓9以上的设备

**Comment by xiaojieonly** [comment]
给低版本的Android做适配实在是太痛苦了

**Comment by liang543xx** [comment]
为啥我Android15也是这个情况

**Comment by xiaojieonly** [comment]
等更新吧
