### ISSUE TITLE
1.9.9.3版本漫画加载不完整，只能加载出非常小的画面

### ISSUE THREAD

**Issue by XLL0234** [xiaojieonly/Ehviewer_CN_SXJ#1585]

**Comment by 7peanuts** [comment]
缩放不对，只显示一半。预览图也变成两幅并排的了。
看了下关闭问题的回答，是 webp 图片的问题，低于安卓 9 显示不全。
jhentai 和 ehviewer UjuiUjuMandan 分叉版还可以正常显示

**Comment by XLL0234** [comment]
> 缩放不对，只显示一半。预览图也变成两幅并排的了。 看了下关闭问题的回答，是 webp 图片的问题，低于安卓 9 显示不全。 jhentai 和 ehviewer UjuiUjuMandan 分叉版还可以正常显示
啊，这样啊。请问这个问题后续会修复吗？

**Comment by HangHorn1354** [comment]
> > 缩放不对，只显示一半。预览图也变成两幅并排的了。 看了下关闭问题的回答，是 webp 图片的问题，低于安卓 9 显示不全。 jhentai 和 ehviewer UjuiUjuMandan 分叉版还可以正常显示
> > 啊，这样啊。请问这个问题后续会修复吗？

大概率不会，同时发现你把你的话怎么进回复内容了🤣

**Comment by xiaojieonly** [comment]
看情况修
