### ISSUE TITLE
有没有办法提高下载速度

### ISSUE THREAD

**Issue by Spicy-sugarfree-hotpot** [xiaojieonly/Ehviewer_CN_SXJ#1588]
下载速度高的话有200-300Kb/s，低的话就几百b/s，下载速度还会波动，一直从低到高再从高到低。而且一个下载内容，比如说几百页，它一次下不完，剩下一百多页显示下载失败。然后再第二次下载。要下几次才能下完。用网和流量都一样，挂梯子也是。大佬们有没有什么办法

**Comment by xiaomaos1** [comment]
我下载也只有kb级别，不过我挂梯子能有mb级别的下载速度。
