### ISSUE TITLE
Seriously a Launcher?

### ISSUE THREAD

**Issue by everclearecct** [xiaojieonly/Ehviewer_CN_SXJ#159]
![Screenshot_20211016-112210_Permission_controller](https://user-images.githubusercontent.com/89713164/137571982-6702e6b8-fe4d-4607-b7d6-385ddb10b995.png)

**Comment by xiaojieonly** [comment]
emmmmmmm~that‘s interesting🤔🤔🤔🤔🤔🤔

**Comment by xiaojieonly** [comment]
fixed
