### ISSUE TITLE
[Bug]打开特定漫画，先图片跳成白屏，然后tag变回英文

### ISSUE THREAD

**Issue by banned2054** [xiaojieonly/Ehviewer_CN_SXJ#1590]
- 版本号:1.9.9.3
- 设备: 小米Pad5
- 系统: Android13
- [logcat-2024-11-10-20-15-51-900.txt](https://github.com/user-attachments/files/17691190/logcat-2024-11-10-20-15-51-900.txt)
- 问题描述：
访问[这个本子](https://exhentai.org/g/3032757/9cd5fc33e4/)的时候，第一次打开图片，加载出来后会突然跳成一张白色的图片，接着就退出漫画阅读，回到本子的画廊，但画廊的tag全都变成英文的，而我设置了显示中文。第二次打开图片软件直接关闭了。
之后重复测试，要么关闭软件，要么白屏然后退出阅读模式。其中白屏次数是最多的

**Comment by xiaojieonly** [comment]
更新到最新版试试，应该是原图浏览时图片尺寸过大导致内存溢出了
