### ISSUE TITLE
预览图加载不出来，打开图片解码失败

### ISSUE THREAD

**Issue by GhostBoys** [xiaojieonly/Ehviewer_CN_SXJ#1594]
![Screenshot_2024-11-11-12-12-25-251_com xjs ehviewer](https://github.com/user-attachments/assets/2c02a42c-6a31-492a-aa24-c9bd5cd6e3c0)
![Screenshot_2024-11-11-12-12-35-174_com xjs ehviewer](https://github.com/user-attachments/assets/4591f0f5-e167-41eb-a9c9-c1fad59c2147)
![Screenshot_2024-11-11-12-12-39-977_com xjs ehviewer](https://github.com/user-attachments/assets/8bb44a40-3e7a-43a6-bf6d-1f070d4cd382)
已经修改过token报错的设置，过了一段时间后就变成这样一直没恢复了，里e

**Comment by MEchooo** [comment]
升级 1.9.9.3版本就好了。解决了

**Comment by GhostBoys** [comment]
> 升级 1.9.9.3版本就好了。解决了

我的就是1.9.9.3版本
