### ISSUE TITLE
1.9.9.3无法观看近期漫画

### ISSUE THREAD

**Issue by QiuShui1012** [xiaojieonly/Ehviewer_CN_SXJ#1598]
“近期”的范围大致在11-03后，缩略图无法正常显示，点进阅读界面后发现显示解码失败，再次点击也无法加载成功。重启应用后仍然如此
手快点可以在显示解码失败前看见加载条转完，11-03前的漫画也完全能看，可以排除网络问题
会是因为e站改了解码规则吗？还是因为我这系统是安卓15所以不支持部分格式？

**Comment by LUrenjia114** [comment]
我也遇到了，我刚开始以为是部分画廊的问题，最近找某些画师新作的时候才发现的，我的是1.9.9.0版本的

**Comment by GhostBoys** [comment]
加一已经看了11月3号之后的都有缩略图和解码失败的问题最新的1.9.9.3版本，怀疑是修改了上传后的图片编码，需要大佬做检查更新了
![Screenshot_2024-11-14-21-07-13-185_com xjs ehviewer](https://github.com/user-attachments/assets/064951aa-d460-41a3-bc04-d14b999d5673)

**Comment by xiaojieonly** [comment]
等更新
