### ISSUE TITLE
ex刚进去就是是什么都没有

### ISSUE THREAD

**Issue by kurumi47** [xiaojieonly/Ehviewer_CN_SXJ#1599]
![Screenshot_2024-11-12-16-18-25-137_com xjs ehviewer](https://github.com/user-attachments/assets/93ccfd9d-6a04-4281-8113-d9db4b779537)

**Comment by asd21069283** [comment]
+1

**Comment by BioTechUncorn** [comment]
我的也是，我是删了重新安装的，记得先导出数据

**Comment by xiaojieonly** [comment]
cookie过期或ip被封
