### ISSUE TITLE
要不要试试用DoH以替代hosts？

### ISSUE THREAD

**Issue by VoidxHoshi** [xiaojieonly/Ehviewer_CN_SXJ#16]
ehviewer停止维护后的另一个接手者NekoInverter也是这样处理的，不过不知道为什么他现在删库跑路了。
https://github.com/NuclearVGA/EhViewer
（某位也想接手维护的朋友备份的NekoInverter的库）

**Comment by xiaojieonly** [comment]
好的，谢谢，我这就研究下

**Comment by xiaojieonly** [comment]
> ehviewer停止维护后的另一个接手者NekoInverter也是这样处理的，不过不知道为什么他现在删库跑路了。
> https://github.com/NuclearVGA/EhViewer
> （某位也想接手维护的朋友备份的NekoInverter的库）

好的，谢谢，我这就研究下

**Comment by xiaojieonly** [comment]
> ehviewer停止维护后的另一个接手者NekoInverter也是这样处理的，不过不知道为什么他现在删库跑路了。
> https://github.com/NuclearVGA/EhViewer
> （某位也想接手维护的朋友备份的NekoInverter的库）

我弄好了，发了新版
