### ISSUE TITLE
 请问下载列表中的排序可以新增按照档案中的大小排序吗?

### ISSUE THREAD

**Issue by december50106** [xiaojieonly/Ehviewer_CN_SXJ#1601]
想從大小最大的漫画開始刪除 但没有找到这个排序选项

![螢幕擷取畫面 2024-11-12 200200](https://github.com/user-attachments/assets/e5a384f5-10ef-4009-9de7-0d79d5508258)

![螢幕擷取畫面 2024-11-12 200540](https://github.com/user-attachments/assets/03f8a5fa-b952-426d-8122-96bb36adf0f8)

**Comment by xiaojieonly** [comment]
目前不行
