### ISSUE TITLE
1.9.9.3版本在Android 7.1.1下会出现阅读时强制放大的情况

### ISSUE THREAD

**Issue by CaOUMay** [xiaojieonly/Ehviewer_CN_SXJ#1602]
无论修改哪种页面缩放都无法进行修改、匹配到设备的宽度
不知是我设置不对，还是后面需要修复一下？

**Comment by HangHorn1354** [comment]
> 无论修改哪种页面缩放都无法进行修改、匹配到设备的宽度 不知是我设置不对，还是后面需要修复一下？

作者目前放弃继续提供支持安卓9以下了，1.9.9.3只是试图支持安卓9以下，结果就是解码是解码了，但还是有点问题，没办法了，不想麻烦作者回复可以提前把Open设为Closed

**Comment by xiaojieonly** [comment]
已修，等更新吧
