### ISSUE TITLE
1.9.9.3版本在MIUI里，点击下载画廊会导致APP崩溃

### ISSUE THREAD

**Issue by NFSLYY** [xiaojieonly/Ehviewer_CN_SXJ#1606]
手机设备：红米 K40 （高通骁龙870）
操作系统：Android 13 / MIUI 14.0.8
软件版本：1.9.9.3
————————
详情：
在一周前，所有App功能都是正常的
然后三天前，当我点击下载的时候，我的App会直接闪退，然后不生成任何日志，但是需要下载的画廊会显示在下载列表里，会显示“未完成”（但如果直接点进去看，图片是可以被下载的，就是不能点击开始下载）
随后重新启动时，MIUI会弹出消息推送权限窗口，每一次闪退后重新进App都会出现这样的情况
![Screenshot_2024-11-13-02-16-33-822_com lbe securi](https://github.com/user-attachments/assets/fe4d2ce1-cb7b-4fc4-a206-633f1e38405c)

我已经尝试过下列步骤：
重装App
关闭VPN（开启的时候对应的host文件也已经关闭了）
删除所有已下载的画廊
清除App数据后直接找随机画廊下载
清除App数据并导入备份数据
回退版本（1.9.9.2也出现了这个问题，但是在这之前好好的）

**Comment by xiaojieonly** [comment]
已修，等更新

**Comment by sliots** [comment]
MIUI13依旧会闪退

**Comment by NFSLYY** [comment]
> 已修，等更新

已更新到1.9.9.4，问题依然存在……
