### ISSUE TITLE
无法加载，流泪机器人（挂了梯）

### ISSUE THREAD

**Issue by IAMDart** [xiaojieonly/Ehviewer_CN_SXJ#161]

**Comment by IAMDart** [comment]
（表站）

**Comment by IAMDart** [comment]
三星手机，版本1.7.10.8，开了伪装就流泪机器人和解析失败，不开一律流泪机器人

**Comment by xiaojieonly** [comment]
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

**Comment by xiaojieonly** [comment]
更新下吧兄弟

**Comment by xiaojieonly** [comment]
> 三星手机，版本1.7.10.8，开了伪装就流泪机器人和解析失败，不开一律流泪机器人

更新到最新版本然后按照我给的图片设置（需要手机系统安卓6以上）
