### ISSUE TITLE
[功能请求]下载内的封面缩略图默认为第一张图片

### ISSUE THREAD

**Issue by littleppg** [xiaojieonly/Ehviewer_CN_SXJ#1610]
现在下载内画廊的封面因为要重新读取画廊信息，导致某些已下架的画廊封面没有了。
希望能默认下载好的画廊的第一张图片为封面，不再去获取画廊信息。

感谢您

**Comment by terence121** [comment]
难怪我就觉得奇怪一直要重新刷新才可以看到封面，断网了直接封面都看不到只可以一个一个按进去选........
拜托大佬回调吧要不然用一下卡一下每次浏览都要重新刷新加载好麻烦哦。

感恩大佬赞叹大佬

**Comment by RBQ114514** [comment]
以前下载的画廊封面有个隐藏文件.thumb，现在都没了，而且以前下载的.thumb文件也加载不出来

**Comment by HibikiZ3** [comment]
以前下载的全都要自己手动点进去刷新封面，太多了根本点不完，还是希望修复一下

**Comment by xiaojieonly** [comment]
1
