### ISSUE TITLE
请问下关于后缀

### ISSUE THREAD

**Issue by qclm441362230** [xiaojieonly/Ehviewer_CN_SXJ#1614]
目前新版本支持webp格式 不过我个人用的是快图来看图的识别不了(图片太多 几万张 用别的app会崩溃)想请问下app内哪里能设置webp和jpg格式的切换吗？以前都是默认jpg的 昨晚看了好几次app都没看到切换的设置

**Comment by Pony-CW** [comment]
你这是想让开发者加一个图片转码功能，在阅读器软件上显然不适合

**Comment by qclm441362230** [comment]
可能我没描述清楚 不是在阅读软件上转格式 是自己选择要下载的图片格式 以前都是默认jpg 现在是默认的webp了 要把webp转jpg我肯定有办法的 就是app内下载默认格式不是jpg才想问问

**Comment by qclm441362230** [comment]
仔细看了下我说的确实没描述清楚 我的锅 我想要的是下载图片格式为jpg 不是默认webp 这么说的话就看懂了 不是要在app内把webp转成jpg后缀

**Comment by Pony-CW** [comment]
恐怕这个选项 e 站本身也没给，可以去翻翻 e 站论坛看看有没有什么收获

**Comment by qclm441362230** [comment]
你这么说的话是e站本身就变成webp格式了吗 我也不是太懂 app92版本左右更新才这样的 默认变成webp格式 我翻了不少别人的提问 发现只有我有这种忧虑

**Comment by xiaojieonly** [comment]
下载jpg格式是后缀错误，是个bug，然后现在e站大部分图片都是webp格式了
