### ISSUE TITLE
切换画廊站点为exhentai搜不到内容

### ISSUE THREAD

**Issue by skczjun** [xiaojieonly/Ehviewer_CN_SXJ#1615]
切换画廊站点为exhentai搜不到内容，任何内容都搜不到

**Comment by xiaowang-shine** [comment]
![Screenshot_20241117_175737_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/9220d4b3-fcf7-4dbb-bdc8-89a54183c8f7)
之前更新完就变成这个样子了，里站的Ehviewer设置也打不开，这怎么办啊。

**Comment by xiaojieonly** [comment]
用cookie重新登录

**Comment by xiaowang-shine** [comment]
解决了
