### ISSUE TITLE
看不到余额了

### ISSUE THREAD

**Issue by kuhdrd** [xiaojieonly/Ehviewer_CN_SXJ#1617]
![Screenshot_2024-11-16-15-46-09-764_com xjs ehviewer](https://github.com/user-attachments/assets/58128657-a49a-4d79-9262-7dff336bfd94)
已经好几个版本了，也重新登陆过，还是看不到

**Comment by xiaojieonly** [comment]
重新登录试试

**Comment by kuhdrd** [comment]
> 重新登录尝试

还是不行，但是进网页版可以看到配额
