### ISSUE TITLE
仅显示 10 个预览 [1.9.9.4]

### ISSUE THREAD

**Issue by shixichann** [xiaojieonly/Ehviewer_CN_SXJ#1618]
仅显示 10 个预览
如果点击，您可以查看 11 日之后的图像。
下载没有问题

Ehviewer_CN_SXJ 版本号 / Ehviewer_CN_SXJ version
1.9.9.4
操作系统版本 / operating system version
"Android 8.0.0" + "4.4.23+"
设备型号 / Device model
HUAWEI MediaPad T5

翻訳前：
プレビューが10件しか表示されない

タップしたら11件目以降も画像は見れる
Downloadは問題ない

**Comment by shixichann** [comment]
仅显示 10 个预览
[Screenshot_20241116-173352](https://github.com/user-attachments/assets/f552c740-f7db-4658-a683-f48986c74b60)

第11张图片，点击就会显示该图片
![Screenshot_20241116-173410](https://github.com/user-attachments/assets/fef85c62-1a4f-4839-b9ed-eb0a232c474c)

第 10 张图像，显示与预览不同的图像
![Screenshot_20241116-173425](https://github.com/user-attachments/assets/0a1ed543-1b4f-4c7e-808d-d5f0bd476af6)
第一个图像显示与预览相同的图像。
从第二个图像开始，显示与预览不同的图像。


翻訳前：
プレビューが10枚しか表示されない

11枚目、タップしたら画像が表示される

10枚目、プレビューと違う画像が表示される

1枚目、プレビューと同じ画像が表示される
2枚目以降、プレビューと違う画像が表示される

**Comment by xiaojieonly** [comment]
1

**Comment by shixichann** [comment]
1？
下次更新会修复吗？

翻译前：
1？
次回アップデートでなおりますか？
