### ISSUE TITLE
账号有里站权限，igneous也填写正常，但是表站里站都无法加载任何封面和略缩图，进本就显示解码失败？

### ISSUE THREAD

**Issue by bsagyh** [xiaojieonly/Ehviewer_CN_SXJ#1624]
本来一直用里站可以正常使用，有一天突然就发生了如题所说的情况且一直无法解决，且切换表站后也无法载图

**Comment by Pony-CW** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
