### ISSUE TITLE
什么都没找到

### ISSUE THREAD

**Issue by 1902520039** [xiaojieonly/Ehviewer_CN_SXJ#1626]
今天突然变成这样了，是怎么回事？更新了1.9.94.
![Screenshot_2024-11-19-10-47-55-048_com xjs ehviewer](https://github.com/user-attachments/assets/68cbb660-eb22-46cc-9825-3ec93fbef37c)
了

**Comment by Chachkey15** [comment]
同，vpn換了幾個地區也一樣,ver1.9.9.3

**Comment by kubus3000** [comment]
好像是突然不能进里站了，只能进表站，昨天都能正常进里站的

**Comment by Chachkey15** [comment]
> 好像是突然不能进里站了，只能进表站，昨天都能正常进里站的
里站網頁版正常...

**Comment by Chachkey15** [comment]
app突然又能正常顯示了。。。

**Comment by ecccccc1** [comment]
igneous失效了，需要重新登录

**Comment by kurodasense** [comment]
换了e-hentai能正常进入，但是不能进入ex的，，

**Comment by yu36107021** [comment]
看來不只有我這樣 先放心了
晚點再看看修好沒
網頁跟app都一樣

**Comment by HibikiZ3** [comment]
> igneous失效了，需要重新登录

刚试了一下 重新登录也无效

**Comment by HibikiZ3** [comment]
> igneous失效了，需要重新登录

重新登录不行。得用“网页登陆”

**Comment by windevil04** [comment]
凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题

**Comment by HibikiZ3** [comment]
> 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题

重新登录，登录的时候选择“网页登陆”

**Comment by windevil04** [comment]
> > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> 
> 重新登录，登录的时候选择“网页登陆”

很神奇啊，回复上一条之前我就用网页重新登录了一遍，但是没有用，看了你的回复又用网页重新登录结果就好了……不过还是感谢🙏

**Comment by 1902520039** [comment]
> > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> 
> 重新登录，登录的时候选择“网页登陆”

还是不行啊，网页登陆完igneous还是mystery

**Comment by HibikiZ3** [comment]
> > > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> > 
> > 
> > 重新登录，登录的时候选择“网页登陆”
> 
> 还是不行啊，网页登陆完igneous还是mystery

去群里问问吧，我用网页重新登录之后就好了

**Comment by yu36107021** [comment]
> > > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> > 
> > 
> > 重新登录，登录的时候选择“网页登陆”
> 
> 还是不行啊，网页登陆完igneous还是mystery

掛個歐美ip 
e重新登入
google右上設置>隱私與安全性>查看所有網站資料和權限>刪除exhentai所有cookie>重新進去exhentai
我這樣就有新的17位igneous了

**Comment by 1902520039** [comment]
> > > > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> > > 
> > > 
> > > 重新登录，登录的时候选择“网页登陆”
> > 
> > 
> > 还是不行啊，网页登陆完igneous还是mystery
> 
> 掛個歐美ip e重新登入 google右上設置>隱私與安全性>查看所有網站資料和權限>刪除exhentai所有cookie>重新進去exhentai 我這樣就有新的17位igneous了

好了好了！太感谢了！

**Comment by Chachkey15** [comment]
> > > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> > 
> > 
> > 重新登录，登录的时候选择“网页登陆”
> 
> 很神奇啊，回复上一条之前我就用网页重新登录了一遍，但是没有用，看了你的回复又用网页重新登录结果就好了……不过还是感谢🙏

我分享一下我的案例吧，我一開始是app無法正常顯示，然後在電腦上打開裏站，然後神奇的事發生了，手機app能正常顯示。

**Comment by 1600201210** [comment]
> > > > 凌晨两点多突然用不了了，还以为是自己网络问题，想等等，发现大家都一样…一样不能进里站，切到表站就行。但是相同线路网页版进ex就没问题
> > > 
> > > 
> > > 重新登录，登录的时候选择“网页登陆”
> > 
> > 
> > 还是不行啊，网页登陆完igneous还是mystery
> 
> 去群里问问吧，我用网页重新登录之后就好了

老哥有群号吗，想加入组织啊😭😭
