### ISSUE TITLE
无法加载详图，无法加载缩略图，显示网络错误

### ISSUE THREAD

**Issue by hlyml** [xiaojieonly/Ehviewer_CN_SXJ#1627]

**Comment by hlyml** [comment]
![Uploading Screenshot_2024-11-19-13-34-37-667_com.xjs.ehviewer.jpg…]()

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/cf30ff3c-be7d-4812-b501-e8282d05410b)

**Comment by xiaojieonly** [comment]
重新登录试试

**Comment by ssd3210** [comment]
> 重新登录试试

我也遇到相同问题，看到这个issue退出登陆后没法登录了，登录界面一闪就过去了，设置里也没有登陆选项，还是退出登录。重复试了好几次都是这样

https://github.com/user-attachments/assets/f0e6ecde-c056-4ba9-b6a5-67d7c7c5cd1c
