### ISSUE TITLE
可以查看已经下载的，缩略图和封面也能看到，但是无法阅读和下载，显示读取失败

### ISSUE THREAD

**Issue by qwerdfab666** [xiaojieonly/Ehviewer_CN_SXJ#1628]
如图
![Screenshot_20241114_220359_com xjs ehviewer](https://github.com/user-attachments/assets/a76b1e8d-b074-4ee1-8f3d-47352da55306)

**Comment by xiaojieonly** [comment]
应该是没给权限

**Comment by qwerdfab666** [comment]
我是给了全部文件的权限的，查了很多，能做到设置调整几乎都试过了还是不行。
