### ISSUE TITLE
今天登到里站一直显示“什么都没有找到”，挂了梯子也不行，以前裸连都是可以的 但是挂了梯子可以上表站

### ISSUE THREAD

**Issue by makshhgg** [xiaojieonly/Ehviewer_CN_SXJ#1629]
![Screenshot_20241119_161231](https://github.com/user-attachments/assets/d47ec98d-3903-4c0e-baca-80583eb9b28b)
有朋友明白是怎么回事吗，这应该不是被封号吧

**Comment by makshhgg** [comment]
我是安卓10

**Comment by yu36107021** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1626
