### ISSUE TITLE
里站看不了了

### ISSUE THREAD

**Issue by zeroinblack** [xiaojieonly/Ehviewer_CN_SXJ#1630]
![Screenshot_2024_1119_162507.png](https://github.com/user-attachments/assets/ecfaa433-c8f9-465d-8282-14f3cfd51576)

挂vpn也不行，表站还可以正常看

**Comment by WGKDYW** [comment]
我也是，更新之后里站进不去了cookie显示igneous: mystery

**Comment by Pony-CW** [comment]
我求你们了问之前搜一下issue不好么……

**Comment by zxc102635** [comment]
重登>開美ip>app下方網頁登入

**Comment by yu36107021** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1626
