### ISSUE TITLE
已下载的画廊点击进入观看会出现闪退

### ISSUE THREAD

**Issue by vkexli** [xiaojieonly/Ehviewer_CN_SXJ#1631]
一般会闪退的是总大小比较大的那种 比如总大小200m左右 单图10m左右就容易出现这种状况
在以前 这种只是打开会反复出现解析失败 无法通过刷新解决 后续更新后是变成一直转圈 总之都是无法加载图片 但本地储存查询是能看到有完整图片的 最近一两次更新 这种图片无法加载的问题变成一点击进入观看就会app闪退 应用已经更新到最新版本依然有这个问题 系统是安卓10 求解决

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
我优化了下，下一版上，如果还是不行可以重新打开这个issue
