### ISSUE TITLE
下载的画廊封面不显示

### ISSUE THREAD

**Issue by Minami-Kotoli** [xiaojieonly/Ehviewer_CN_SXJ#1632]
点详情进去重新加载才能显示
![Image_1732018616782](https://github.com/user-attachments/assets/5ce2dded-50e2-4ec2-b962-7a70894341bd)

**Comment by wksts** [comment]
同，而且我里站进不去了，重新登入也是如此

**Comment by cy2014orz** [comment]
一样

**Comment by xiaojieonly** [comment]
是这样的，目前在想怎么优化

**Comment by xiaojieonly** [comment]
建议少吧eh的缓存数据当垃圾清理，没有手动清理过的，可以看看手机清理设置啥的
