### ISSUE TITLE
在19号开始不额外挂梯子就显示网络错误

### ISSUE THREAD

**Issue by yinyan9066** [xiaojieonly/Ehviewer_CN_SXJ#1633]
是只有我这样吗 还是都是这样 有什么解决方法吗

**Comment by RubyLuna0w0** [comment]
我也是，暂时还没有解决办法

**Comment by cy2014orz** [comment]
等待更新吧，我也是

**Comment by RBQ114514** [comment]
重新登陆一下

**Comment by 00loli** [comment]
网络错误，重新登陆不管用

**Comment by Hono373** [comment]
按照可靠消息，应该是站长修改了登录机制
每3个月还是更短的时间会刷新igneous字段
你们看不到ex的话可以看看自己的cookies，这个应该是null了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
