### ISSUE TITLE
请问e站账号出现mystery是怎么回事

### ISSUE THREAD

**Issue by hzjknfbb** [xiaojieonly/Ehviewer_CN_SXJ#1634]
进绿e的ex，打着什么都找不到，如何解决

**Comment by hzjknfbb** [comment]
下面还弹出什么little h啥

**Comment by skkznsnxjxhs** [comment]
mystery我也一样，就不能看里站，之前还能通过保存的igneous搞，现在不知道为什么不行了只要进去就mystery

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
