### ISSUE TITLE
网页登陆的人机验证显示不完全

### ISSUE THREAD

**Issue by miukyu** [xiaojieonly/Ehviewer_CN_SXJ#1636]
今天发现全部内容不显示，上来看了一眼说是重新登陆就好，单纯账号密码说验证码不正确，选择网页登陆显示验证码只有一半根本没办法登陆了，有什么解决办法吗（这已经是拖放到最大了没法左右移动
![Screenshot_20241120-091042](https://github.com/user-attachments/assets/f37cc6ad-95e6-4fbf-9eea-626438c8ccb1)
）

**Comment by xiaojieonly** [comment]
缩小不就能看到了

**Comment by miukyu** [comment]
> 缩小不就能看到了

![Screenshot_20241120-104130__01](https://github.com/user-attachments/assets/9066ac90-40bc-4bca-ac93-c06898864cd1)
![Screenshot_20241120-104135__01](https://github.com/user-attachments/assets/be59df41-fb65-4b03-9403-10b5743c54fd)
第一张图是默认状态，第二张图是放大状态无论如何只能改变背景eh网址的缩放但是无法影响这个人机验证

**Comment by xiaojieonly** [comment]
把默认浏览器换成chrome浏览器试试

**Comment by miukyu** [comment]
> 把默认浏览器换成chrome浏览器试试

![Screenshot_20241120-114153](https://github.com/user-attachments/assets/9b539797-9df8-4646-8059-12a4179df927)
![Screenshot_20241120-114226](https://github.com/user-attachments/assets/dde25e84-948a-4f8f-a96a-be6f379c325d)
应该和这个没关系我试过了改了很多种都还是这样子，你在app上网页登陆是正常吗

**Comment by xiaojieonly** [comment]
我用的cookie登录

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by xiaojieonly** [comment]
先在web端登录，拿到cookie后用cookie在APP上登录

**Comment by gsqagaoshiqinga-stack** [comment]
我也遇到这个问题了。
1.登录次数过多需要验证。
2.身边没有pc只有手机。
一开始想的是找一个能看cookie的手机浏览器，整了半小时。
后面发现……只要把手机调成横屏就行了

![Image](https://github.com/user-attachments/assets/10b1238a-1309-48cb-8585-6551f097aa3a)
