### ISSUE TITLE
最近的版本中封面缩略图出现异常

### ISSUE THREAD

**Issue by KnightLightning3** [xiaojieonly/Ehviewer_CN_SXJ#1637]
如图:
![bf1c73fae17871f5988e31aaa593db3c](https://github.com/user-attachments/assets/08d87d03-4650-4658-8a92-8412fe8bde5d)
![f4f4ea0900eb1aa0ca601fc148f0a2b2](https://github.com/user-attachments/assets/bc24ac41-3760-46e3-b4aa-78fbf67cfc05)
本地画廊可以正常阅读但是封面缩略图缺失. 可能是1.9.4版本后才出现此问题. 但是我不能确定.
此项问题发生在较早下载的某些画廊中, 最近下载的画廊封面依然正常, 但是这段时间版本更新了数次, 我不清楚较早下载和较最近下载之间的具体版本的差异

**Comment by a975028722** [comment]
我的是直接出现什么都没有![Screenshot_20241120_112350_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/2025a88e-6ae1-4dcb-956f-d26de567f16d)

**Comment by KnightLightning3** [comment]
> 我的是直接出现什么都没有![Screenshot_20241120_112350_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/2025a88e-6ae1-4dcb-956f-d26de567f16d)

这个好像是最近的版本网络也出了问题，我网页端能进去app进不去

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by KnightLightning3** [comment]
> #1625

原来如此, 非常感谢
