### ISSUE TITLE
加载图片显示网络错误

### ISSUE THREAD

**Issue by BlueSpaceX** [xiaojieonly/Ehviewer_CN_SXJ#1638]
最近经常会出现图片加载“网络错误”的情况，如图所示，基本上每隔几页就会出现一些图片加载不出来的问题，更换节点也没有任何效果

![Screenshot_2024-11-20-13-52-36-241_com xjs ehviewer](https://github.com/user-attachments/assets/8eb57e20-2f10-46b7-a23c-f20a0206fe6c)

**Comment by Hcdgvcjgyu** [comment]
可以尝试先下载下来再查看
