### ISSUE TITLE
搜索特定标签会完全没有结果

### ISSUE THREAD

**Issue by santacreeper** [xiaojieonly/Ehviewer_CN_SXJ#1639]
日常搜genderchange突然就没法出任何搜索结果了，别的标签都没问题，但是发现搜索很多东西都会没有结果，包括male gender 单独一个字母g等等

**Comment by Genera1559** [comment]
我是所有tag包括主页都没有任何搜索结果.

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
