### ISSUE TITLE
里站看不到内容

### ISSUE THREAD

**Issue by million0403** [xiaojieonly/Ehviewer_CN_SXJ#1640]
app内画廊站点选择里站看不到内容，更换e-hentai后正常显示
![Screenshot_2024-11-20-15-06-35-040_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/7248a768-6df3-4b76-aef4-0962a5a6a8a3)

![Screenshot_2024-11-20-15-08-21-411_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/9bb3a690-5539-494c-b6e5-f28feeeb97f1)

![Screenshot_2024-11-20-15-06-23-511_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/153ad11f-52f6-48db-84e4-9d131f9a0455)

![Screenshot_2024-11-20-15-06-32-739_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/d1727e40-ddce-48af-a16d-1dffadb3c30c)

**Comment by SurfSoya** [comment]
出现了一样的问题

**Comment by Genera1559** [comment]
我也是

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
