### ISSUE TITLE
里站现实什么都没有找到

### ISSUE THREAD

**Issue by Laxwei** [xiaojieonly/Ehviewer_CN_SXJ#1642]
表站就一切正常，里站无论是主页还是标签都显示什么都找不到。也重新登录过了，也还是不行。我是一直用自己VPN的，eh内部代理我已经关闭了。![S41120-19124741_com.xjs.ehviewer.png](https://github.com/user-attachments/assets/381852c9-99a6-4f13-97c9-01a3c5ba8e73)

![S41120-19123894_com.xjs.ehviewer.png](https://github.com/user-attachments/assets/d421417d-7339-48b8-a28a-1b57a075d607)

![S41120-19133108_com.xjs.ehviewer.png](https://github.com/user-attachments/assets/c8348a5b-187b-40c7-af64-d80148625965)

**Comment by hy200597** [comment]
我也一样，什么都看不了

**Comment by 1600201210** [comment]
一样，我的igneous项变成了sk=几十个字母数字

**Comment by 1600201210** [comment]
插眼求解决办法

**Comment by sakana456** [comment]
一样，等一个解决办法

**Comment by EricZhou05** [comment]
退出重登即可解决（需用欧美ip）
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1641

**Comment by hzjknfbb** [comment]
> 退出重登即可解决（需用欧美ip）
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1641

我用欧美ip一样登不进去

**Comment by 1600201210** [comment]
> 退出重登即可解决（需用欧美ip） #1641

没有用

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by Sakura4548** [comment]
我成功了，在获得新的inj后刚开始是不用的，我把所有是内置vpn关掉后换的英国重新登陆，就好了。
