### ISSUE TITLE
里站两个登录方式都无法进入

### ISSUE THREAD

**Issue by wwwjjjsou** [xiaojieonly/Ehviewer_CN_SXJ#1646]
如题，之前都能进里站，这次igneous失效之后就不行了，用cookie前两条ipb_member_id和ipb_pass_hash登陆还是不行，用网页输入账号密码登陆也还是不行，igneous显示的都是mystery，操作挂的都是美国节点，不知道是不是被封了。
![Screenshot_2024-11-21-09-27-14-861_com xjs ehviewer-edit](https://github.com/user-attachments/assets/736c2ed9-c096-452d-928e-d26bb9f04ba5)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
