### ISSUE TITLE
ehviewer网页版有没有大佬给个网址，苹果手机下不了app唉

### ISSUE THREAD

**Issue by jsjsja111** [xiaojieonly/Ehviewer_CN_SXJ#1647]

**Comment by xiaojieonly** [comment]
额，可以试着花点小钱买个安卓玩

**Comment by Pony-CW** [comment]
e-hentai.org
exhentai.org
哥们，ehentai不等于ehviewer，倒不如说ehviewer基于ehentai

**Comment by Pony-CW** [comment]
苹果可以用 [Yealico](https://apps.apple.com/us/app/yealico/id1359000639)，通过使用[阿巴基猫](https://wc3818290.home.blog)的规则实现美观性观看

或者安装 [Eros-FE](https://github.com/3003h/Eros-FE) 和 [EhPanda](https://github.com/EhPanda-Team/EhPanda)，安装方法自行查阅
