### ISSUE TITLE
改变默认下载位置后，原本下载位置的文件不会被eh读取

### ISSUE THREAD

**Issue by GiveMeOneLastKiss** [xiaojieonly/Ehviewer_CN_SXJ#1648]
有没有可能设置多个下载文件夹以使用eh扫描完整媒体库，并将其中一个路径设置为默认下载位置？将这两个设置分开可能有助于eh的使用。
关于为什么我要修改下载位置，因为原来下载路径下的本子太多，导致app下载响应变得特别慢甚至卡死，只能换了下载路径。

**Comment by xiaojieonly** [comment]
我研究下

**Comment by xiaojieonly** [comment]
你是什么手机？下载了多少画廊？
