### ISSUE TITLE
请问里站权限是会被回收吗

### ISSUE THREAD

**Issue by shigureica** [xiaojieonly/Ehviewer_CN_SXJ#1649]
我的账号是自己的，之前一直都可以正常访问里站，这次更新后就无法访问，尝试了站里的一些帖子的方式仍然在igneous处显示mystery，舍不得几百本的收藏夹啊

**Comment by shigureica** [comment]
顺便请问一下显示mystery和null的区别是什么

**Comment by xiaojieonly** [comment]
[旧的9位igneous cookie失效，字段被强行转换为mystery](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625)
