### ISSUE TITLE
下載列表中封面圖大規模不顯示

### ISSUE THREAD

**Issue by Ber-ray** [xiaojieonly/Ehviewer_CN_SXJ#1653]
Android12
最近下載的沒問題
只要點入項目中他讀取到了就會恢復顯示，但我不可能一兩千個慢慢點
![Screenshot_20241122_043634_EhViewer](https://github.com/user-attachments/assets/513eb0d3-88d8-4d10-863b-5a949c97c535)

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已尝试修复，下一版更新，
