### ISSUE TITLE
表里站画廊标题和封面正常，但缩略图与内容均显示解码失败如何解决？

### ISSUE THREAD

**Issue by begoniarain** [xiaojieonly/Ehviewer_CN_SXJ#1655]
版本1.9.9.4。自cookie更新以后，尽管重新获取了igneous字段并能够正常进入里站搜索画廊，并且画廊标题与封面图均显示正常，但在开启内置hosts，域名前置与安全DNS的情况下缩略图和内容均无法查看并显示解码失败。而关闭上述三项并开启梯子却能够正常查看缩略图与内容。求助怎样能够在不开梯子，使用内置映射的情况下正常查看？

**Comment by xiaojieonly** [comment]
裸连得看网络运营商的脸色，建议换个运营商的网络试试
