### ISSUE TITLE
关于里站显示不出来封面图的问题

### ISSUE THREAD

**Issue by weishenshi** [xiaojieonly/Ehviewer_CN_SXJ#1656]
绿e已更新到最新，但是现在里站的封面图全都刷新不出来（切换到表站可以正常刷新），但是点进去的缩略图都能正常刷新。

**Comment by shikimori997** [comment]
略缩图都没了，我直接显示什么都没有

**Comment by weishenshi** [comment]
隔了段时间登上去就正常了，也挺奇怪的。之前像是缩略图刷新不出来经常见到过，也是隔一段时间就能好，这次封面图刷新不出来还是第一次见。
