### ISSUE TITLE
进入软件后，主界面显示什么都没有找到

### ISSUE THREAD

**Issue by shikimori997** [xiaojieonly/Ehviewer_CN_SXJ#1657]
如题，现在怎么刷新都不行，有没有教一下解决方法
![Screenshot_20241123-021521](https://github.com/user-attachments/assets/8535c7fa-2d95-41ff-a0e2-22fe7b2296b4)

**Comment by chy5301** [comment]
同样的问题，今天刚发现

**Comment by GreensonZheng** [comment]
今天+1

**Comment by DongXD22** [comment]
+1

**Comment by 1078249029** [comment]
+1

**Comment by xiaojieonly** [comment]
igneous过期了，重新登录下
