### ISSUE TITLE
点击收藏会导致cookie的igneous丢失，无法访问里站。奇怪的情况

### ISSUE THREAD

**Issue by BALALABAKA** [xiaojieonly/Ehviewer_CN_SXJ#1659]
目前版本1.9.9.4，问题可能是在前几个版本出现的。

问题出现流程：
1/重新使用cookie登录，'主页'和'热门'可以正常登录
2/点击'收藏'后，页面显示[expired login session]+流泪安卓头。此时设置里cookie还正常
3/再访问'主页'，发现已经无法加载
4/在设置里查看cookie 发现 igneous值变为mystery

设置中[锁定Cookie igneous字段]，开启关闭与否 不影响这个问题发生。

以上都是访问ex站点前提下出现

**Comment by BALALABAKA** [comment]
关于节点问题，试了美英加三国和香港台湾的IP，不影响问题产生

**Comment by BALALABAKA** [comment]
igneous也是通过网页刷新的最新，不是旧的9位数字

**Comment by BALALABAKA** [comment]
刚下了个隔壁彩E正常，排除我这边环境问题，只能等更新优化了

**Comment by xiaojieonly** [comment]
复现不出来，可能是因为梯子节点用的人太多了导致的
