### ISSUE TITLE
希望在“根据状态过滤”中加入已观看选项

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#1661]
下了这么多本子肯定是要看的，看了之后肯定也得删。
       可在一次激情澎湃的发泄后，要从未下载和以完成与未观看的本子中，挑出刚才看过的本子，选中再删除是有点痛苦的。（除了上诉情况可能也会在一页500本的情况下翻了好几页才找到几本对上当时感觉的本来看，所以删起来很麻烦）
       现在APP内已经可以显示每本的总页数和阅读页数，能不能利用这两个已知数据，加上一个根据阅读进度，筛选以阅读的本子，来方便删除？
       推荐判定标准为，观看每本的总页数的40%，视为已阅读。因为现在有广告汉化组在末尾会塞5，6页广告，以及可能在挑要看的本子的时候会翻一两页就放弃观看换别的本子的情况。
![Screenshot_2024-11-23-18-59-04-477_com xjs ehviewer](https://github.com/user-attachments/assets/42b00c6a-8154-4ccc-b413-d4513e1895af)
![Screenshot_2024-11-23-18-59-57-165_com xjs ehviewer](https://github.com/user-attachments/assets/2af4b4a4-734f-4b9a-b0a3-e110d3696f71)

**Comment by xiaojieonly** [comment]
1，我想下
