### ISSUE TITLE
打开显示“什么都没有找到”和流泪熊猫头该怎么办？Q：shown“nothing found”，what can I do？

### ISSUE THREAD

**Issue by ziyue3154262773** [xiaojieonly/Ehviewer_CN_SXJ#1662]
用楼里大佬的方法解决了：退出重登。
使用网页登录，登录前先在游览器上登录这个网站：https://forums.e-hentai.org，用同样的账户名和密码就可以

原疑问：人在国外，应该不会出现网络问题，也已经更新到版本1.9.9.4，手机寄回国修理一个月后后再打开就变成这样了。求大佬解惑，下附图片

Question solved by reload the account using following comments ：
1st load on website https://forums.e-hentai.org
2st using the same account name and secret code of the website to log on app by the method of website.

Orinal Q：
IP with no Internet limitation；
updated yet to 1.9.9.4；
shown like the picture after one month's phone repairing.
Asking for help.
![Screenshot_20241123_194659_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/65b07360-aee2-42de-8d51-a24a8366687d)

**Comment by SmallK111407** [comment]
同，求解

**Comment by YuncengC1oud** [comment]
我爷一样

**Comment by YuncengC1oud** [comment]
我也一样

**Comment by 3525932396** [comment]
我也是

**Comment by xiaojieonly** [comment]
重新登录，igneous过期了

**Comment by ziyue3154262773** [comment]
呜呜呜咱就是说有解决方案么？现在都转言耽社看去了





------------------ 原始邮件 ------------------
From: 3525932396 ***@***.***&gt;
发送时间: 11/24/2024, 09:54
To: xiaojieonly/Ehviewer_CN_SXJ ***@***.***&gt;
抄送: ziyue3154262773 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 打开显示“什么都没有找到”和流泪熊猫头该怎么办？Q：shown“nothing found”，what can I do？ (Issue #1662)





 
我也是

**Comment by ziyue3154262773** [comment]
靴靴！另外能多问一句如何保留下载项目重新登陆哇？我目前只会卸载重新下载来登陆





------------------ 原始邮件 ------------------
From: SXJ_LonelyDog ***@***.***&gt;
发送时间: 11/25/2024, 01:59
To: xiaojieonly/Ehviewer_CN_SXJ ***@***.***&gt;
抄送: ziyue3154262773 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 打开显示“什么都没有找到”和流泪熊猫头该怎么办？Q：shown“nothing found”，what can I do？ (Issue #1662)





 
重新登录，igneous过期了

**Comment by YuncengC1oud** [comment]
貌似重新登陆了也不好使，还是弹这个

**Comment by ziyue3154262773** [comment]
我重新登录后成功了！直接用的网页登录，
https://forums.e-hentai.org，登录前先在游览器上登录了这个界面还有网页版内站

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 打开显示“什么都没有找到”和流泪熊猫头该怎么办？Q：shown“nothing found”，what can I do？ (Issue #1662)




 
貌似重新登陆了也不好使，还是弹这个

**Comment by ziyue3154262773** [comment]
换一个私人账号试试呢？我换之前用的是共用的





------------------ 原始邮件 ------------------
From: YuncengC1oud ***@***.***&gt;
发送时间: 11/26/2024, 17:18
To: xiaojieonly/Ehviewer_CN_SXJ ***@***.***&gt;
抄送: ziyue3154262773 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xiaojieonly/Ehviewer_CN_SXJ] 打开显示“什么都没有找到”和流泪熊猫头该怎么办？Q：shown“nothing found”，what can I do？ (Issue #1662)





 
貌似重新登陆了也不好使，还是弹这个
