### ISSUE TITLE
cookie登录删除igneous信息后无限自动游客登录，重装也不行怎么办?

### ISSUE THREAD

**Issue by 03liulimao** [xiaojieonly/Ehviewer_CN_SXJ#1663]
关掉两个内置host开关，复制cookie，退出登录后选择cookie登录，删除igneous内容登录后，瞬间跳成游客登录，想退出登录，但是登录页面在跳出后瞬间又自动游客登录，删掉app重新下载也是瞬间自动游客登录。

**Comment by xiaojieonly** [comment]
李跳跳关了
