### ISSUE TITLE
CLEARTEXT communication to exhentai.org not permitted by network security policy

### ISSUE THREAD

**Issue by pikeduo** [xiaojieonly/Ehviewer_CN_SXJ#1664]
如题，有时候搜索会报错
![Screenshot_2024-11-25-11-44-48-014_com xjs ehviewer](https://github.com/user-attachments/assets/5c300c1f-5b9a-4c42-a4b1-de204376dc82)
必须把搜索内容删减一些，才能正确搜索出来结果
![Screenshot_2024-11-25-11-47-01-572_com xjs ehviewer](https://github.com/user-attachments/assets/feac9b50-443c-4d4b-b5c7-6f04446bae64)
貌似是因为搜索内容出现不同语种的语言

**Comment by xiaojieonly** [comment]
是这样的
