### ISSUE TITLE
有关数据传输的问题

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#1668]
换了新手机，把旧手机的数据通过wifi迁移，导出导入数据的方式转移过来了，然后也通过传输文件的方式把全部的本从旧手机转到了新手机。但是目前来看有大部分的画廊在新手机上还是需要重新下载，请问有什么解决办法吗

**Comment by xiaojieonly** [comment]
是这样的，有些画廊的数据是在缓存里，所以迁移不了，后面会完善wifi迁移
