### ISSUE TITLE
开启Multi page viewer后在Ehviewer打开画廊出错(pToken Error)

### ISSUE THREAD

**Issue by AXIS5hacker** [xiaojieonly/Ehviewer_CN_SXJ#1669]
![Screenshot_20241126_132115_com.xjs.ehviewer_edit_350628298249622.jpg](https://github.com/user-attachments/assets/61cce16a-02a8-4a91-b518-b1bf92529846)
如上图，将选项调为Yup后，在Ehviewer中打开画廊后图片加载全变成Get pToken Error

使用版本：1.9.9.4

**Comment by xiaojieonly** [comment]
是这样的
