### ISSUE TITLE
二次开发需求

### ISSUE THREAD

**Issue by supersun3757** [xiaojieonly/Ehviewer_CN_SXJ#1673]
开发者大大。
我目前在做一个小程序，旨在删除下载的重复文件夹（重复书籍名），以求节省空间占用。
目前我遇到了这样一个问题，我计划整合同一本书的不同章节（系列作品）。
比如我现在有书1与书2。现在我将书2中的所有图片重命名顺序后保存在书1的文件夹中。
但是我发现你的软件存储目录中有一个.ehviewer文件（猜测是阅读器配置文件），我以文本文件格式打开后发现里面有如下信息：
***
VERSION2
00000000
3095448
0b8fe937da
1
1
25
25
0 e0f1fc27b4
1 7d1702d55a
2 4d83c48e8a
3 a7a40bc77b
4 8f8e63c80c
5 8f41a270ee
6 ef9b207143
7 da43aa6345
8 e2c5e94c55
9 bb8dda825e
10 cc7b5c2684
11 329a41efcc
12 decb59e420
13 8d61fbda3f
14 990d0fa70d
15 aa86997d51
16 93d26816ad
17 667febee18
18 306d1ab081
19 8bf008f894
20 94c102b8fc
21 ba5ceeb389
22 876dcd5bb0
23 4cbe8f6296
24 97aea07e27
***
我很好奇”24 97aea07e27“这里的十六进制数据的含义是什么？如果没有它只修改上面的25是否会对阅读器照常影响。希望您能解答一下，如果您能介绍一下上面文件中每一行的意义是什么就更好了。
谢谢。
另外，这里我提供一个更新书籍的思路，遇到新版本的书籍直接通过删除重复名字目录的方式在内存上删除这本书籍，然后在您软件上删除旧版本的信息，再下载新版本的书籍。如果您需要我提到这个功能的代码，我可以将它开源出来。但是我只擅长python与c/c++，所以很抱歉不能直接帮助您维护本项目。

**Comment by supersun3757** [comment]
> 开发者大大。 我目前在做一个小程序，旨在删除下载的重复文件夹（重复书籍名），以求节省空间占用。 目前我遇到了这样一个问题，我计划整合同一本书的不同章节（系列作品）。 比如我现在有书1与书2。现在我将书2中的所有图片重命名顺序后保存在书1的文件夹中。 但是我发现你的软件存储目录中有一个.ehviewer文件（猜测是阅读器配置文件），我以文本文件格式打开后发现里面有如下信息：
> 
> VERSION2 00000000 3095448 0b8fe937da 1 1 25 25 0 e0f1fc27b4 1 7d1702d55a 2 4d83c48e8a 3 a7a40bc77b 4 8f8e63c80c 5 8f41a270ee 6 ef9b207143 7 da43aa6345 8 e2c5e94c55 9 bb8dda825e 10 cc7b5c2684 11 329a41efcc 12 decb59e420 13 8d61fbda3f 14 990d0fa70d 15 aa86997d51 16 93d26816ad 17 667febee18 18 306d1ab081 19 8bf008f894 20 94c102b8fc 21 ba5ceeb389 22 876dcd5bb0 23 4cbe8f6296 24 97aea07e27
> 
> 我很好奇”24 97aea07e27“这里的十六进制数据的含义是什么？如果没有它只修改上面的25是否会对阅读器照常影响。希望您能解答一下，如果您能介绍一下上面文件中每一行的意义是什么就更好了。 谢谢。 另外，这里我提供一个更新书籍的思路，遇到新版本的书籍直接通过删除重复名字目录的方式在内存上删除这本书籍，然后在您软件上删除旧版本的信息，再下载新版本的书籍。如果您需要我提到这个功能的代码，我可以将它开源出来。但是我只擅长python与c/c++，所以很抱歉不能直接帮助您维护本项目。

**Comment by xiaojieonly** [comment]
图片 token
