### ISSUE TITLE
全屏模式关不掉

### ISSUE THREAD

**Issue by hswnice** [xiaojieonly/Ehviewer_CN_SXJ#1674]
亮色主题和暗色主题关不掉全屏模式，只有黑色主题能退出全屏模式

**Comment by xiaojieonly** [comment]
没看懂

**Comment by hswnice** [comment]
阅读设置里面的全屏选项关掉以后依然全屏显示，不会显示状态栏

**Comment by hswnice** [comment]
![Uploading Screenshot_20241129_120245.jpg…]()

**Comment by hswnice** [comment]
![Screenshot_20241129_120242](https://github.com/user-attachments/assets/090a8937-9d72-4030-9211-ce8cfc80e3b4)
![Screenshot_20241129_120245](https://github.com/user-attachments/assets/dd5c2752-0bc3-4284-b3a8-b64ff508bf55)
全屏选项是关闭的，但是还是全屏显示了

**Comment by hswnice** [comment]
![Screenshot_20241129_120242](https://github.com/user-attachments/assets/0125d589-96db-4ec0-b1e9-823f0d40a06b)
![Screenshot_20241129_120245](https://github.com/user-attachments/assets/f89f4be7-1492-4898-a74d-890a8f2fa283)
阅读设置里全屏选项是关闭的，但是依然是全屏显示
![Screenshot_20241129_120729](https://github.com/user-attachments/assets/96f713a8-0e08-4119-8328-a2b9bfe856c7)
只有黑色模式能正常显示手机状态栏

**Comment by hswnice** [comment]
> 没看懂

如上

**Comment by xiaojieonly** [comment]
我看看

**Comment by xiaojieonly** [comment]
已修，下一版上
