### ISSUE TITLE
下载本子的时候总是最后有一两页没法下载

### ISSUE THREAD

**Issue by yisuwi** [xiaojieonly/Ehviewer_CN_SXJ#1675]
我不知道是我个人网络的问题还是其他的，每次下载的时候到最后总有个别几页没法下载一直转圈圈，换其他的网络或者清除缓存也没有用，只要点进去必是转圈圈加载不出来0kb/s，但是详情页预览图可以显示出来，有谁知道怎么解决吗

**Comment by youshou1** [comment]
> 我不知道是我个人网络的问题还是其他的，每次下载的时候到最后总有个别几页没法下载一直转圈圈，换其他的网络或者清除缓存也没有用，只要点进去必是转圈圈加载不出来0kb/s，但是详情页预览图可以显示出来，有谁知道怎么解决吗

我是直接跳过或者反复点击
