### ISSUE TITLE
下载列表等备份文件经导入/导出后无法被读入

### ISSUE THREAD

**Issue by fruitcereal** [xiaojieonly/Ehviewer_CN_SXJ#168]
设置-高级-导出数据后的.db文件可以被自身读入，但是在被其他eh浏览app读入时显示“无法读入文件”。

**Comment by fruitcereal** [comment]
补充：经测试，其他app导出的.db文件本可以被自身导入。但是由该app导入后，便无法再被其他app导入了。推测是该app在导入/导出.db文件后会占用住文件导致其他app无法导入。但是在卸载该app后其他app仍无法读入该.db文件。总而言之，**所有的.db备份文件只要被这个app一导入就废了**。只能来报个issue了，我所有的下载列表数据文件的备份在被该app导入之后都gg了，其他app完全没法读入……

**Comment by duzhaokun123** [comment]
linux 没有文件占用机制
是文件被改成不兼容的了
有一次更新使其与其他eh客户端都不兼容

**Comment by fruitcereal** [comment]
有任何方式可以重新将文件改成兼容的吗，我所有的备份在导入后全部不可用了。

**Comment by duzhaokun123** [comment]
查到转换方式 逆着来就行了
作者要不写这个工具我就写了 (鉴于作者半开源, 不保证写得出来)

**Comment by duzhaokun123** [comment]
具体像这样错误
```
Caused by: t4: Tag mismatch. Expected: UNIVERSAL BIT STRING, but found UNIVERSAL SEQUENCE
11-16 19:20:52.526  9720 25938 W System.err:    at s4.a(Asn1BerParser.java:7)
11-16 19:20:52.526  9720 25938 W System.err:    at gy.x(Unknown Source:23)
11-16 19:20:52.526  9720 25938 W System.err:    ... 9 more
```

**Comment by xiaojieonly** [comment]
我不知道其他客户端的代码，基本没法弄，然后我的代码是全开源的，除了还没有写完二没上传的代码外，能上传的我都上传了

**Comment by xiaojieonly** [comment]
然后数据导入导出这块的代码我没有未提交的代码，上次修改应该是半年前了

**Comment by xiaojieonly** [comment]
还有就是我一个人的精力有限，不可能把别人的代码拿来一点点分析，就为了给别人做适配。。。。。。

**Comment by xiaojieonly** [comment]
最后，我没有用过别人的软件（hippo的最初版除外，但是他不维护了，不然我也不会自己搞来维护了），我是我自己维护的版本的忠实用户

**Comment by xiaojieonly** [comment]
这个问题应该是因为我的软件数据库添加了一个用户**黑名单的表**，而其他版本的软件没有**添加用户黑名单的功能**，自然就没有这张表，所以才会出现我这个版本的软件导出的数据没法被别人的版本使用的问题
