### ISSUE TITLE
图片过大时会闪退

### ISSUE THREAD

**Issue by zac10097** [xiaojieonly/Ehviewer_CN_SXJ#1682]
举例：https://exhentai.org/g/3118333/0b4f50ac29/的第1、18、19、20页，大致范围为7MB以上，能正常下载图片，但用eh打开就会导致闪退

**Comment by xiaojieonly** [comment]
手机型号，安卓版本发一下

**Comment by xiaojieonly** [comment]
是最新版吗？
更新到最新版试试，不行再重新打开issue

**Comment by zac10097** [comment]
之前是1.9.9.4版本，红米k50手机出现这个问题，更新到1.9.9.6版本之后没有这个问题了，谢谢
