### ISSUE TITLE
画廊预览异常

### ISSUE THREAD

**Issue by BizareeLing** [xiaojieonly/Ehviewer_CN_SXJ#1683]
版本1.9.9.4，画廊预览会自动合并两张图片，以单次加载预览数为一组，前一半显示合并的预览图，后一半空白，附一张图用于理解说明
![Screenshot_20241201_121219](https://github.com/user-attachments/assets/c51ad12b-4eec-44b3-ac5e-1040c729a4e7)
安卓版本8.0，因此不指望会修，进提供反馈，至少看图是没有问题的（）

**Comment by xiaojieonly** [comment]
更新一下试试

**Comment by BizareeLing** [comment]
并没有什么变化（
也许单纯只是我低安卓版本导致的？
