### ISSUE TITLE
1.9.9.5下载封面问题并未修复

### ISSUE THREAD

**Issue by HibikiZ3** [xiaojieonly/Ehviewer_CN_SXJ#1684]
安卓14
![Screenshot_2024-12-01-13-38-58-627_com xjs ehviewer](https://github.com/user-attachments/assets/0cf8a9ae-b9ef-4a80-8e59-d5948e4c4b3b)

**Comment by TAT213** [comment]
已经不会读取本地封面文件.thumb了

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，晚上再次更新
