### ISSUE TITLE
记得以前画廊更新在下载里是可以直接更新的

### ISSUE THREAD

**Issue by 739471428** [xiaojieonly/Ehviewer_CN_SXJ#1687]
记得以前画廊更新在下载里是可以直接更新的，某个版本后突然就不行了，只能去更新的画廊全部重新下。这个功能是没有了还是画廊自己的原因啊？现在有个300多页的本每次更新几页都要重新下，太难受了😣

**Comment by xiaojieonly** [comment]
有bug，会导致无限重复下载
