### ISSUE TITLE
1.9.9.5原图下载后大分辨率图片无法显示一片黑

### ISSUE THREAD

**Issue by ghfg1** [xiaojieonly/Ehviewer_CN_SXJ#1688]
![Screenshot_2024-12-02-11-10-50-705_com xjs ehviewer](https://github.com/user-attachments/assets/b922be80-9d28-4d7f-83c6-8e103f0af51e)

**Comment by xiaojieonly** [comment]
额

**Comment by ghfg1** [comment]
> 额

回退到1.9.9.4的时候这个画廊会直接闪退
试了好几个大分辨率都都会出现这种问题下载完无法显示

**Comment by xiaojieonly** [comment]
手机型号
安卓版本发一下

**Comment by ghfg1** [comment]
> 手机型号 安卓版本发行一下

k60安卓13

**Comment by ghfg1** [comment]
> 手机型号 安卓版本发一下

话说什么时候能修复啊

**Comment by xiaojieonly** [comment]
更新一下试试

**Comment by ghfg1** [comment]
> 更新一下试试



还是不行[](url)
![Screenshot_2024-12-03-10-22-01-528_com xjs ehviewer](https://github.com/user-attachments/assets/ceff89bd-42e0-495b-8727-b03b9180e08e)
只有最后的那个汉化组公告分辨率不大能显示出来
问题是在1.9.9.5那个优化大图以后出现的1.9.9.4没有这个问题
