### ISSUE TITLE
下载的原图会显示黑色或者混乱

### ISSUE THREAD

**Issue by wuyilong1201** [xiaojieonly/Ehviewer_CN_SXJ#1691]
这个问题我发下仅存在于观看方式是从上到下，屏幕一次显示多个图片会这样，观看方式从左到右屏幕只显示一张图片就不会这样，跟以前打开下载的原图会闪退也是一样的情况版本1995，一加ace2pro，安卓13
![IMG_20241203_003035](https://github.com/user-attachments/assets/5b9bff84-67d7-4e7f-a7ba-c7bde7f4748a)

**Comment by xiaojieonly** [comment]
更新一下试试

**Comment by wuyilong1201** [comment]
1996也有同样问题

**Comment by wuyilong1201** [comment]
> 更新一下试试

1996也有同样问题

**Comment by ProvidenceP** [comment]
我也遇到了，1997版本

**Comment by 2911894613** [comment]
我也一模一样啊，这为啥closed了？
