### ISSUE TITLE
1.9.9.6切换主题时应用崩溃

### ISSUE THREAD

**Issue by liaofuyu1** [xiaojieonly/Ehviewer_CN_SXJ#1692]
![Screenshot_20241203-081822](https://github.com/user-attachments/assets/893cd96c-38c8-4d6b-8bd1-537b1fc06bef)
在切换主题时，第一次会无法生效并跳转主页

![Screenshot_20241203-082049](https://github.com/user-attachments/assets/fbf1b1ac-6fcf-4147-b749-ab67e71b58dc)
短时间第二次点切换主题会应用崩溃，重启后生效

![Screenshot_20241203-082233](https://github.com/user-attachments/assets/39c07bb5-4ab2-44e9-b01e-40662340dcde)

崩溃日志链接
https://bin.mkr.pw/~674e510d632ce757b6266a5f

**Comment by xiaojieonly** [comment]
已修，下一版上
