### ISSUE TITLE
1.9.9.6UI建议

### ISSUE THREAD

**Issue by liaofuyu1** [xiaojieonly/Ehviewer_CN_SXJ#1693]
![Screenshot_20241203-082604](https://github.com/user-attachments/assets/93197616-6d0d-456e-b3eb-6c020469d979)
选项首页中，每个选项间感觉还是像以前用细淡色横线隔开要好看点

![Screenshot_20241203-082745](https://github.com/user-attachments/assets/6bd5d1a8-551d-4dd1-9735-abbc0b6206a5)

**Comment by xiaojieonly** [comment]
已修，下一版上
