### ISSUE TITLE
仅显示 10 张图像预览[1.9.9.6]

### ISSUE THREAD

**Issue by shixichann** [xiaojieonly/Ehviewer_CN_SXJ#1694]
1.9.9.6
仅显示 10 张图像预览

2024/09/04 15:00 仅限 10件
2024/09/04 15:00 前 没问题

![Screenshot_20241203-145559](https://github.com/user-attachments/assets/586f8f2a-f4aa-4480-b4e1-2e39c746a320)
![Screenshot_20241203-145613](https://github.com/user-attachments/assets/508bb361-a8a1-40b5-acb4-1bf46c4add24)

![Screenshot_20241203-145528](https://github.com/user-attachments/assets/1a44cbde-e2ff-4bcd-83c4-a5148c25207c)
![Screenshot_20241203-145542](https://github.com/user-attachments/assets/9d9bd4ea-4f90-489f-adbb-e0585178bc75)

翻译前：
画像のプレビューが10枚だけになる

2024/09/04 15:00 後　10枚のみ
2024/09/04 15:00 前　問題無し

**Comment by xiaojieonly** [comment]
网络问题，习惯就好
