### ISSUE TITLE
1996版在WindowsSubsystemForAndroid上恢复下载目录里的下载项出现解码失败

### ISSUE THREAD

**Issue by sleepman36** [xiaojieonly/Ehviewer_CN_SXJ#1696]
![image](https://github.com/user-attachments/assets/5a3adb58-13df-48c3-91ad-bf9d2a8431ef)
今天重装了WSA发现Ehviewer里的下载项全部没有封面 ，并且打开显示解码失败

**Comment by xiaojieonly** [comment]
。。。挂梯子试试，多半是网络错误

**Comment by sleepman36** [comment]
> 。。。挂梯子试试，多半是网络错误

我用了HTTP代理还是不行 ，不过更换下载目录就可以正常显示封面了，切换到有以前下载项的目录就还是出现解码失败
![image](https://github.com/user-attachments/assets/ca9a2f3a-0b92-45ad-ba3e-c96c003cbf22)
![image](https://github.com/user-attachments/assets/b1adaa0e-009d-492b-a415-7e353813d411)

**Comment by sleepman36** [comment]
![image](https://github.com/user-attachments/assets/e082600f-2a70-4197-baed-4476058b9c58)
日志上应该有记录吧，等我复现一下，存了一年多的呜呜呜
