### ISSUE TITLE
有没有什么可以一键分享本地收藏的方法

### ISSUE THREAD

**Issue by sdshdv** [xiaojieonly/Ehviewer_CN_SXJ#17]
这样就算用了不同开发者开发的ehviewer也可以互相转移本地收藏，还可以把自己的收藏一键全部分享给其他人

**Comment by xiaojieonly** [comment]
> 这样就算用了不同开发者开发的ehviewer也可以互相转移本地收藏，还可以把自己的收藏一键全部分享给其他人

好想法，我可以试试能不能实现

**Comment by xiaojieonly** [comment]
> 这样就算用了不同开发者开发的ehviewer也可以互相转移本地收藏，还可以把自己的收藏一键全部分享给其他人

收藏内容暂时设置只能通过剪切板一个个分享，我看之前有些人收藏夹有几百上千的数据，本地内容到好说，万一是分享的线上内容到时候直接请求e站的连接的话可能会直接判定操作违规，导致封号。所以打算暂时只搞个够用的，这个功能这周应该就能更新发布一版。到时候记得来捧场😋

**Comment by xiaojieonly** [comment]
> 这样就算用了不同开发者开发的ehviewer也可以互相转移本地收藏，还可以把自己的收藏一键全部分享给其他人

我弄出个只能在我发的最新本之间才能互相分享的功能，而且一次只能传一个，限制颇多，批量分享要压缩的信息太多，暂不支持😞

**Comment by sdshdv** [comment]
> 我弄出个只能在我发的最新本之间才能互相分享的功能，而且一次只能传一个，限制颇多，批量分享要压缩的信息太多，暂不支持😞

也行吧，感谢开发者的爆肝了

**Comment by xiaojieonly** [comment]
> > 我弄出个只能在我发的最新本之间才能互相分享的功能，而且一次只能传一个，限制颇多，批量分享要压缩的信息太多，暂不支持😞
> 
> 也行吧，感谢开发者的爆肝了

哈，之后慢慢优化，争取能支持批量分享
