### ISSUE TITLE
特别多的文件时，恢复下载会失败

### ISSUE THREAD

**Issue by PiedmontStream** [xiaojieonly/Ehviewer_CN_SXJ#170]
重装系统后，尝试恢复导出的数据库，导出的数据库文件被损坏了
因此尝试使用自带的恢复下载项，不出意外地因为文件过多而失败(约90G,4000多个非空目录)

只找到了一个18年的数据库，抢救了一部分。
有希望后续版本中修复吗？

**Comment by PiedmontStream** [comment]
读了下代码，貌似流程是从每个目录下的.ehview文件中拿到gallery_id和gallery_token然后用api拿到剩下的信息来恢复到数据库，然后可能因为恢复数量太多api被限流了。
我后面备份下文件然后元信息自己爬一遍吧，这个要求平板跑完有点牵强了……

**Comment by xiaojieonly** [comment]
每天下一点积少成多吧，目前只能这样了

**Comment by zzx111ded** [comment]
我有一个很蠢很蠢但能解决的办法，3434752062加qq细嗦
