### ISSUE TITLE
一些由于屏蔽画廊设置导致的bug

### ISSUE THREAD

**Issue by HoRains** [xiaojieonly/Ehviewer_CN_SXJ#1703]
当我在进行某个tag的搜索时，如果恰好这个tag的第一页全部都含有我屏蔽的tag，会导致整个搜索结果显示为什么都未找到，比如我在搜索female: tickling的tag时，由于这个时间点第一页的所有画廊都包含我屏蔽的language: English，所以最后导致结果直接显示什么都没有找到；是否能够调整一下消除这个bug

**Comment by HoRains** [comment]
使用exhentai自己的语言屏蔽设置好像能绕过这个问题🤔那这个问题就没这么严重了，还请开发者有空的时候看看

**Comment by xiaojieonly** [comment]
。。。是这样的
