### ISSUE TITLE
仅显示 10 张图像预览[1.9.9.6] 延续

### ISSUE THREAD

**Issue by shixichann** [xiaojieonly/Ehviewer_CN_SXJ#1706]
＞网络问题
真的是网络问题吗？

这在[1.9.9.0]之前没有发生过

JHenTai[8.0.5+2264] 或 Foolbar/EhViewer[1.13.1] 不会出现类似问题

请调查

＞ネットワークの問題、とにかく慣れてください
本当にネットワークの問題ですか？

[1.9.9.0]以前では発生しませんでした

JHenTai[8.0.5+2264]やFoolbar/EhViewer[1.13.1]では同様の問題は起きていません

調査をお願いします

**Comment by xiaojieonly** [comment]
是的，网络问题，或者网页设置问题。
我复现不出来你的问题
