### ISSUE TITLE
部分画廊的一些图片就是加载不出来

### ISSUE THREAD

**Issue by rtptpp** [xiaojieonly/Ehviewer_CN_SXJ#1708]
不是网络问题，网页版EX站能正常加载所有图像
尝试下载这个画廊也是一直卡在最后一页下不下来。
或许是手机型号的问题？但我觉得不太可能。
![Screenshot_20241207_185019_com xjs ehviewer](https://github.com/user-attachments/assets/1b73a787-5a7a-4bce-9050-85f68df2f4ac)
![Screenshot_20241207_183619_com xjs ehviewer](https://github.com/user-attachments/assets/180f374c-6d5d-4ae4-b27b-f3e7da33a744)

**Comment by Stevezombie** [comment]
我的也是这样，不晓得怎么回事

**Comment by xiaojieonly** [comment]
分配的H@H服务器问题
