### ISSUE TITLE
[功能建议]新建本地收藏标签功能

### ISSUE THREAD

**Issue by ludwigmoonlight** [xiaojieonly/Ehviewer_CN_SXJ#1709]
类似下载标签，用来添加本地收藏用的标签方便管理和分类。本地收藏只有一个不是很方便，eh的云端收藏又不能重新命名且有数量限制

**Comment by OLD-6-DRIVER** [comment]
附议，本地收藏只有一个文件夹，只能按收藏时间排序，不能自行改变顺序或者分类，一页一页翻起来很费劲。求大神添加
