### ISSUE TITLE
兄弟们，求助!

### ISSUE THREAD

**Issue by LKPforever** [xiaojieonly/Ehviewer_CN_SXJ#171]
为啥我卸载一段时间后，在下载就看不了了啊，封面什么都能看，就是一直处在加载状态，之前都是直连的啊
![Uploading Screenshot_2021-11-16-00-39-03-73_159c494ea8977f628e53d8d36755ba4c.jpg…]()

**Comment by Wuliwalaking** [comment]
兄弟我也一样，缩略图、封面、评论都正常，大图一开就寄了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
