### ISSUE TITLE
关于原图下载显示黑页图片

### ISSUE THREAD

**Issue by vkexli** [xiaojieonly/Ehviewer_CN_SXJ#1716]
在新一版中修复了部分老的画廊不能观看的问题后 最近我发觉偶然又遇到了这个情况 姑且还只是个例 这个画廊差不多314m 单图差不多9m左右 我机子是安卓10系统 打开发觉有概率出现 黑页 (这个画廊开头的图片如果是横长方形 就会是横长方形的黑图片 后面的是竖着的就是竖黑页) 或者图片只有一部分被加载 或者前面的图片的某一部分在后面的页数中出现在黑页的某一角落 偶尔打开还有概率能看到某一张图片被加载了一部分但其余都是黑页
还有的有概率见到 如果原画廊某几页中存在黑页白字的文字描述 在最初下载的时候有概率发现黑页是纯黑页 无法看见白字 但之后在刷新几次后又能看见 这个实际上是最早遇到的黑页问题 因为后来又没出现了 反而是上面出现那个问题的画廊通过刷新没法解决 删了重下也不行 尝试关了原图 然后删了重下才能看见了

**Comment by xiaojieonly** [comment]
看起来是读取权限没给

**Comment by vkexli** [comment]
我今天再次有一个画廊触发了这个黑页问题 也是3百m左右 不知为何就偶尔会有一两个触发这个问题 其余的好像没问题 但触发黑页的画廊我选择删了然后关原画就能被读取到
然后 我还发觉有一个问题 我是把存放地址改到sd卡的 sd卡似乎无法创建带Unicode那种😎🍆💢符号的文件夹而导致下载失败 这个有什么好办法吗

**Comment by vkexli** [comment]
刚刚又再次遇到了一个 这次似乎删了关原图也无法解决 而且我发觉删除画廊包括图片之后再次点击下载 还是瞬间有27页的进度 感觉根本没删掉 下载里尝试清理下载冗余 也无效 高级里清理内存缓存也不能让这以前下了的27页归0 虽然后面的页面 27页后的十多页中随机进一页 转圈加载图片 有概率能显示出图片 这些操作在关原图后才有概率 开着的时候是只有黑页 然后已经显示出的图片 出来 再进去有概率还是黑页 前面那27页里面 有的图片会变成只有一半显示出来 然后这一半还缩小了 在黑页的左右一小块概率随机出现 有的页面 就是无论怎么刷新都是黑页 然后有大概率点刷新 会一直在那转圈 只能退出应用重进但之后也只能看到黑页

**Comment by vkexli** [comment]
> 看起来是读取权限没给
我好像不太会怎么重新打开流
新版我再用了下 发觉还是不行 尝试更换旧设备 安卓9 下载同一个画廊 但还是不行 也是开原图就黑页 刷新无效 
以前的不是特别找得到了 我就只找到一个最近的
我给个链接吧
https://exhentai.org/g/3154021/94e80b12c3/

**Comment by 2911894613** [comment]
我也一样，原图下载就会概率碰到这种问题

**Comment by vkexli** [comment]
> 我也一样，原图下载就会发生概率波动这类问题

概率 
说是概率 
但不同设备下同一个画廊 
前一个黑页 
后一个也必然黑 
关原图 
才可能有一定机会解决

**Comment by 2911894613** [comment]
我试了一下白e（nekoinverter），可以看原图。你在xiaojieonly这个版本的ehviewer下载后，去白e里面点击下载，他会读取你本地已经下载的漫画然后直接下载完成，然后就可以看了。

**Comment by vkexli** [comment]
> 我试了一下白e（nekoinverter），可以看原图。你在xiaojieonly这个版本的ehviewer下载后，去白e里面点击下载，他会读取你本地已经下载的漫画然后直接下载完成，然后就可以看了。

好吧 你说的对 虽然白e不更新了 点具体的画廊会提示错误而打不开 但点下载还是和绿e一样的名称 可以共用 但灰e下载名称不一样所以不能共用 这样操作除了就是会麻烦点 但至少能用了

**Comment by 2911894613** [comment]
nekoinverter这个24年底还在更新，有人维护的。不是之前那个白e

**Comment by vkexli** [comment]
> nekoinverter这个24年底还在更新，有人维护的。不是之前那个白e

你如果说的是能直接在git搜nekoinverter然后下载的那个版本的话 那个是我上面提到的灰e 灰e文件名和绿e不相同 会导致需要重新下载 灰e文件夹命名格式取的是画廊的标题属性 而绿e取的是日文标题属性的值
我暂时没找到还有别的分支的e

**Comment by xiaojieonly** [comment]
已修，下一版上
