### ISSUE TITLE
关于hath技能对ehviewer的影响

### ISSUE THREAD

**Issue by cidosc** [xiaojieonly/Ehviewer_CN_SXJ#1720]
我已经用h@h获得了一定量的hath，但请问开启哪些特权能提高ehv的体验
https://1drv.ms/i/s!AnuvEWmA5hWK1xMoWBwmIYoxFjBs
https://1drv.ms/i/s!AnuvEWmA5hWK1xThQ-y2PHRnk-PM

**Comment by cidosc** [comment]
在线查看**画质**很差

**Comment by xiaojieonly** [comment]
![image](https://github.com/user-attachments/assets/e0bb3d5e-c7f0-4672-8c1d-f04a3f7144f0)
