### ISSUE TITLE
能否增加类似这种喜欢和屏蔽标签的功能？

### ISSUE THREAD

**Issue by ghsqhub** [xiaojieonly/Ehviewer_CN_SXJ#1721]
![Screenshot_2024-12-13-00-31-03-603_top.jtmonster.jhentai-edit.jpg](https://github.com/user-attachments/assets/f4ad24df-99b3-41eb-9711-08581327fe37)

**Comment by xiaojieonly** [comment]
目前书签栏点一下会变成订阅栏，可以屏蔽或订阅tag

**Comment by Harmskyblue** [comment]
> 目前书签栏点一下会变成订阅栏，可以屏蔽或订阅tag

e站tag订阅集上限只有一百个，不太够用，不知道能不能本地设置一个订阅集

**Comment by ghsqhub** [comment]
> 目前书签栏点一下会变成订阅栏，可以屏蔽或订阅tag

藏的好深，这里的隐藏和展现怎么改？图里的隐藏是我在其他软件调的![Screenshot_2024-12-18-00-17-51-599_com.xjs.ehviewer-edit.jpg](https://github.com/user-attachments/assets/37c9c9c8-3b0b-4078-b69d-22132a5cc5f1)

**Comment by xiaojieonly** [comment]
> > 目前书签栏点一下会变成订阅栏，可以屏蔽或订阅tag
> 
> 藏的好深，这里的隐藏和展现怎么改？图里的隐藏是我在其他软件调的![Screenshot_2024-12-18-00-17-51-599_com.xjs.ehviewer-edit.jpg](https://private-user-images.githubusercontent.com/104250090/396579653-37c9c9c8-3b0b-4078-b69d-22132a5cc5f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDY3NTYsIm5iZiI6MTczNTIwNjQ1NiwicGF0aCI6Ii8xMDQyNTAwOTAvMzk2NTc5NjUzLTM3YzljOWM4LTNiMGItNDA3OC1iNjlkLTIyMTMyYTVjYzVmMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwOTQ3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjM0MzZjODE4ZGFhODI3MjY1MzAyMDYyNDVkMDgxNzBhNDM5MTg0MTRhOWFkOWI4ZjA4MWRmZDRkZWZhODAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F1J1ifKBzwd7L5QCNk0t9cQ4TESzzhu7ziMDkt2W0As)

点加号
