### ISSUE TITLE
[功能建议]希望增加点按区域反转功能

### ISSUE THREAD

**Issue by KTG-suger** [xiaojieonly/Ehviewer_CN_SXJ#1722]
希望在阅读选项中增加点按翻页区域左右反转功能。

挺多漫画有那种大跨页的表现，这种情况下开从右到左观感更好，但是手机太大了，用右手拇指跨过去按左边屏幕好难受，音量键也是用久了手指痛，而且我备用机用的mate30没有音量键，。，

所以希望能增加个阅读点按区域左右反转的选项。

**Comment by xiaojieonly** [comment]
早就有了，设置里可以改

**Comment by KTG-suger** [comment]
> 早就有了，设置里可以改

不好意思，我只找到了反转音量键的开关，并没有找到反转点按的设置在哪，可以讲一下这个功能在哪开启吗。
![Uploading Screenshot_20241216_120303_com.xjs.ehviewer.jpg…]()

**Comment by KTG-suger** [comment]
> 早就有了，设置里可以改

不好意思，我只找到了反转音量键的开关，并没有找到反转点按的设置在哪，可以讲一下这个功能在哪开启吗。
![Screenshot_20241216_120303_com xjs ehviewer](https://github.com/user-attachments/assets/21a25955-d37a-4872-b5bc-1bf08939edc6)
