### ISSUE TITLE
图片搜索

### ISSUE THREAD

**Issue by xxxwind505** [xiaojieonly/Ehviewer_CN_SXJ#1724]
不知道为什么图片搜索他搜不出来东西一直显示再转也没说没找到什么的就是等不出结果来
![Screenshot_20241216_221758_com_xjs_ehviewer_MainActivity](https://github.com/user-attachments/assets/2d76f8d1-03b6-4e58-9830-92dcb808f686)

**Comment by monkeykinsa** [comment]
我也一样。要怎么处理啊。。

**Comment by xiaojieonly** [comment]
是这样的，E站的搜图功能越改越烂
