### ISSUE TITLE
为什么下载的画廊的图片，会显示在系统相册里，我现在相册4万＋了

### ISSUE THREAD

**Issue by Spicy-sugarfree-hotpot** [xiaojieonly/Ehviewer_CN_SXJ#1725]

**Comment by MC57348** [comment]
![Screenshot_2024-12-19-15-57-26-712_moe tarsin ehviewer](https://github.com/user-attachments/assets/5ffac543-a55c-419e-9bc3-18338fee2bc0)
有没有把允许媒体扫描关掉？

**Comment by Spicy-sugarfree-hotpot** [comment]
开过一次，发现有点问题，就关了，但是相册还是很多

**Comment by Spicy-sugarfree-hotpot** [comment]
我又重复了一遍，开了又关上，现在相册没有了。谢谢！
