### ISSUE TITLE
封面加载不出来但是实际内容图片可以正常加载

### ISSUE THREAD

**Issue by THO48** [xiaojieonly/Ehviewer_CN_SXJ#1726]
![Screenshot_20241219-051450.png](https://github.com/user-attachments/assets/ac8c0d6c-cbab-4c5c-b0d2-718a87083fa7)

![Screenshot_20241219-051503.png](https://github.com/user-attachments/assets/54e56252-2d24-44e7-b84b-35b967a394c5)

设置里的各种设置都试过了，缩略图大小、缩略图分辨率、修正缩略图链接，也重新安装过几次，都不能修复。而且无法导出日志
设备是小新pad,android 13

**Comment by THO48** [comment]
![Screenshot_20241219-051856.png](https://github.com/user-attachments/assets/63aafcc0-1f50-41ec-90c3-ae49b1a94ec1)

点击导出日志只有个白框，是因为只有内置存储吗？

**Comment by xiaojieonly** [comment]
挂个梯子试试，这种情况通常是网不好
