### ISSUE TITLE
版本1.9.9.6 重新登陆过 昨天还能看里站今天就看不了了，求解决方法

### ISSUE THREAD

**Issue by 332d** [xiaojieonly/Ehviewer_CN_SXJ#1728]
![Screenshot_2024-12-21-20-31-29-056_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/66c95034-c194-48c0-8467-dc238ff135c1)

**Comment by 4a124** [comment]
我也是这个情况，不知道怎么解决

**Comment by HaiMFeng** [comment]
同样的情况

**Comment by HaiMFeng** [comment]
但是表站正常

**Comment by 1020329192** [comment]
好像是网站的问题，不是软件的

**Comment by KTG-suger** [comment]
之前cookie的igneous短位的失效了。大概率是这个原因。可以按顺序排查一下问题。

记得开始之前先挂好全局的阿美ip梯子。

首先去网页版登录一下自己的账号，确认一下到底是号被封了还是怎么了。如果网页版的ex也登不进去就可以直接重开了。

确认网页能进ex以后再去app设置里的身份cookie查看自己的igneous是否为数字字母长组合。如果不是，退出登录之后  阿美ip  全局  再次使用网页登录。

**Comment by 332d** [comment]
> 之前cookie的igneous短位的失效了。大概率是这个原因。可以按顺序排查一下问题。
> 
> 记得开始之前先挂好全局的阿美ip梯子。
> 
> 首先去网页版登录一下自己的账号，确认一下到底是号被封了还是怎么了。如果网页版的ex也登不进去就可以直接重开了。
> 
> 确认网页能进ex以后再去app设置里的身份cookie查看自己的igneous是否为数字字母长组合。如果不是，退出登录之后  阿美ip  全局  再次登录。

我前几个月也有这种情况，也是按这种方式解决的，可是现在又复发了

**Comment by skylight321** [comment]
还是不行老哥，挂美的梯子重新登了，还是显示什么都没有，ig是十七位的，网页版也等到上去，已经没法了。

**Comment by KTG-suger** [comment]
> 还是不行老哥，挂美的梯子重新登了，还是显示什么都没有，ig是十七位的，网页版也等到上去，已经没法了。

以防万一我问一下你不会是江苏的吧，。，

部分省份会把这种网页劫持，我当初在南京时候就没办法直连打开e站。可以尝试一下把内置的关了然后开梯子试下能不能打开，如果还不行我就真不知道什么问题了，。，

**Comment by CL-305** [comment]
> > 还是不行老哥，挂美的梯子重新登了，还是显示什么都没有，ig是十七位的，网页版也等到上去，已经没法了。
> 
> 以防万一我问一下你不会是江苏的吧，。，
> 
> 部分省份会把这种网页劫持，我当初在南京时候就没办法直连打开e站。可以尝试一下把内置的关了然后开梯子试下能不能打开，如果还不行我就真不知道什么问题了，。，

我岛国的，日常挂美国和台湾地区VPN，网页版一切正常，绿E就是楼主这个情况。

**Comment by 332d** [comment]
> > > 还是不行老哥，挂美的梯子重新登了，还是显示什么都没有，ig是十七位的，网页版也等到上去，已经没法了。
> > 
> > 以防万一我问一下你不会是江苏的吧，。，
> > 
> > 部分省份会把这种网页劫持，我当初在南京时候就没办法直连打开e站。可以尝试一下把内置的关了然后开梯子试下能不能打开，如果还不行我就真不知道什么问题了，。，
> 
> 我岛国的，日常挂美国和台湾地区VPN，网页版一切正常，绿E就是楼主这个情况。

要不要试试看挂美国VPN用cookie登陆，IG行什么都不填，我是这样解决的

**Comment by SeraBlack** [comment]
我用最后这个方法解决了，谢谢大哥

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by skylight321** [comment]
已解决，等了半天晚上就能登了。
