### ISSUE TITLE
下载只持续几秒下载就会失败 

### ISSUE THREAD

**Issue by hf2363** [xiaojieonly/Ehviewer_CN_SXJ#1729]
下载本子的只持续几秒就失败了 再点进去又持续几秒 一个本子得点击下载四五次 一旦下载多了可能只持续一两秒就失败了 另外刷新会出现错误代码429

**Comment by TELTimeFlies** [comment]
同，点击下载后，瞬间停止，同时下载的文件在软件里提示读取失败，但是在资源管理器里可以正常打开

**Comment by xiaojieonly** [comment]
网不好
