### ISSUE TITLE
图片页面 长按 点击分享 无法分享到其他应用 似乎与权限有关 EACCES (Permission denied)

### ISSUE THREAD

**Issue by mo-han** [xiaojieonly/Ehviewer_CN_SXJ#1730]
不同应用的报错提示各不相同 基本都是 导入失败 访问失败 获取资源失败 

其中 Joplin 给出的信息比较完整详细 贴在这里 以供参考 

```
ENOENT: /storage/emulated/0/EhViewer/temp/2878676-615c765e8b-00000034.webp: open failed: EACCES (Permission denied), open '/storage/emulated/0/EhViewer/temp/2878676-615c765e8b-00000034.webp'
```

**Comment by xiaojieonly** [comment]
你没给APP权限，与APP无关

**Comment by mo-han** [comment]
这你就猜错了 我当然已经给了存储相关的权限 
我贴两张截图为例 都是作为分享的目标应用遇到这个问题的应用 一个就是Joplin 另一个是佳能打印 

![Screenshot_20241226_192504](https://github.com/user-attachments/assets/908a7598-cadc-4763-9ab2-105ec69cafc7)
![Screenshot_20241226_192452](https://github.com/user-attachments/assets/afcace2f-7163-4720-bf4c-2854ac895daa)

难道 仅允许访问媒体文件 这个权限还不够访问ehv目录下的临时图片吗 
总不能说 还非得要 允许管理所有文件 这个权限吗 
可是 允许管理所有文件 这个权限本来就是不能随便给的 正经应用也不会请求这个权限 因为这个权限本就存在安全隐患 
再说 举例中的 Joplin 和 佳能打印 这两个应用 都是讲道理的正经应用 
它们并不需要 所有文件 这个权限 所以它们也不请求这个权限 
它们不要 我也没法给 

所以 问题还是回到 
为什么 允许访问媒体文件 这个权限已经打开了 
却还是不能访问 ehv 的图片呢 
为什么 其他的应用 都能正常地把图片和文档之类的文件 分享给这些 仅允许访问媒体文件 的应用呢 
为什么 只有 ehv 不行呢 
单从控制变量法来看 这也是和 ehv 相关
