### ISSUE TITLE
提议 增加下载标签内的标签

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#1731]
有没有可能做到一个下载标签内可以创建新的下载标签，比如说建立一个动漫的下载标签，然后在这个标签里可以继续创建标签给不同角色的画廊。 
目前把好几百个画廊放在一个标签里有时候想找特定角色的画廊挺难找的。

**Comment by xiaojieonly** [comment]
目前实现不了
