### ISSUE TITLE
我的账号突然变成了little hippo还什么都用不了

### ISSUE THREAD

**Issue by djfjdk** [xiaojieonly/Ehviewer_CN_SXJ#1732]
![Screenshot_2024-12-24-21-28-42-568_com xjs ehviewer](https://github.com/user-attachments/assets/d5220bc3-8548-4d56-812e-c3ddb9a34c77)
如图所示账号莫名其妙变成了这个，哪怕用网页登录也会变成这个号，我也没改名在eh上登录也是自己的账号。

**Comment by djfjdk** [comment]
通过关闭内置host，在美国ip重新登录后至少能看正常使用了，看收藏也确实是自己的账号，但名字还是变成了little hippo，不知道什么原因

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by LlReww** [comment]
我也是，但是我是进不了里站了，昨天开始这样，不到为啥

**Comment by LlReww** [comment]
> 我也是，但是我是进不了里站了，昨天开始这样，不到为啥

啊都去年的事了啊，那老哥有找到解决方法进里站吗

**Comment by LlReww** [comment]
> > 我也是，但是我是进不了里站了，昨天开始这样，不到为啥
> 
> 啊都去年的事了啊，那老哥有找到解决方法进里站吗
没事了，我是傻逼

**Comment by Nian114514** [comment]
不是哥们，你是傻逼，你倒是说一下你为什么是傻逼啊？
