### ISSUE TITLE
里站进入方法，本人亲测有效（至少我成功了）

### ISSUE THREAD

**Issue by dfh10010** [xiaojieonly/Ehviewer_CN_SXJ#1733]
不用捐赠的，我就没有捐赠，也不需要IP为欧美、国外邮箱、语言为英语这些，我就是QQ邮箱，IP中国，中文简体。首先要翻墙，然后再设置-EH-EHentai设置，把浏览地区/国家改为你用的节点（这一步也许可以忽略，因为我忘了应用也成功了），要是就不去EHentai设置，会跳出提示，说该节点连接过多，暂时用不了（反正差不多是这个意思）。提示最后会有时间，等时间到了再刷新主页或者重新启动E站，然后就进去了，而且不用在翻墙了，可以直连里站了

_Originally posted by @dfh10010 in https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/430#issuecomment-2561637651_

**Comment by Dream-238** [comment]
开了梯子设置进去一片空白根本设置不了😭

**Comment by Kuo-Litsing** [comment]
原本使用cookie登录，也是什么都没有，也进不去设置界面，退出后改用账号密码登录就有了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625

**Comment by xwxyz** [comment]
换个梯看看行不行，[下一个试试](https://dsvp1n.live/share.html?channel=s3)
