### ISSUE TITLE
瀏覽gif動圖會有撕裂問題

### ISSUE THREAD

**Issue by genecoco19658** [xiaojieonly/Ehviewer_CN_SXJ#1734]
如題 看gif時 畫面不知是不夠流暢或是怎樣 
![Screenshot_2024-12-25-22-17-39-297_com xjs ehviewer-edit](https://github.com/user-attachments/assets/68764ba8-6344-47d9-8fe7-f19227148826)

**Comment by xiaojieonly** [comment]
1
