### ISSUE TITLE
昨天还可以进入里站，今天就不行了，希望能找到原因及解决方法

### ISSUE THREAD

**Issue by noaharker** [xiaojieonly/Ehviewer_CN_SXJ#1740]
![Screenshot_20241228_104733](https://github.com/user-attachments/assets/a789043d-1554-4a09-9993-b4bedaf6736e)
[logcat-2024-12-28-07-06-24-818.txt](https://github.com/user-attachments/files/18264763/logcat-2024-12-28-07-06-24-818.txt)

**Comment by noaharker** [comment]
抱歉各位佬，经过排查，是我的cookie过期了，通过网站登录，重新获取cookie后，已经解决问题

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1625
