### ISSUE TITLE
使用wifi能正常观看，但使用数据会提示GP不足

### ISSUE THREAD

**Issue by nmslxswl888** [xiaojieonly/Ehviewer_CN_SXJ#1742]
![Screenshot_2024-12-28-13-20-37-889_com.xjs.ehviewer.jpg](https://github.com/user-attachments/assets/04505261-59e9-47fd-8f74-2d138f492111)

**Comment by xiaojieonly** [comment]
等一段时间，等他慢慢恢复

**Comment by nmslxswl888** [comment]
已经是好几个版本都这样了，唉
