### ISSUE TITLE
今天eh的服务器是不是出了什么问题？

### ISSUE THREAD

**Issue by babooms** [xiaojieonly/Ehviewer_CN_SXJ#176]
打开之后，主页错误，是流泪图标
版本更新到了最新

**Comment by babooms** [comment]
![Uploading Screenshot_20211123_135824_com.xjs.ehviewer.jpg…]()

**Comment by xiaojieonly** [comment]
你这图片能重新上传下不，我看不见

**Comment by babooms** [comment]
问题修复了，是登录掉了，所以图片不重要（）
