### ISSUE TITLE
兄弟们，帮帮忙，E站一直解析失败，我的VPN登录不上，但是用朋友的就可以。。。

### ISSUE THREAD

**Issue by 3280556935** [xiaojieonly/Ehviewer_CN_SXJ#177]

**Comment by xiaojieonly** [comment]
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

**Comment by xiaojieonly** [comment]
看下设置对不对，用vpn的话就把网络设置全关了试试

**Comment by xiaojieonly** [comment]
要么是网不好，要么是设置没设置对
