### ISSUE TITLE
怎么在电脑/软路由端实现域名前置？

### ISSUE THREAD

**Issue by More500code** [xiaojieonly/Ehviewer_CN_SXJ#179]
测试了一下在同一WIFI下
手机不开内置HOST 开域名前置可以直连里站
其他设备可以通过梯子连上表站？
请教一下怎么设置才能让其他设备也能直连里站？
软路由端设置好了host （手机不开内置host能直连）电脑设置好了cookies 也没能连上

**Comment by xiaojieonly** [comment]
github上工具千千万，你找找？，或者google搜一下有没有现成的工具吧
