### ISSUE TITLE
登陆里站后不能直连

### ISSUE THREAD

**Issue by YZQSR** [xiaojieonly/Ehviewer_CN_SXJ#180]

**Comment by xiaojieonly** [comment]
要么没有权限，要么网不好

**Comment by xiaojieonly** [comment]
如果网页上能进里站，那app就退出登录然后重新用cookie登录

**Comment by xiaomi7714** [comment]
网页也登不上了咋办啊啊啊啊啊呜呜

**Comment by qitan777** [comment]
我本来可以进入里站的，但是点了一次锁定cheek igneous字符后就不能进去了。请问这个怎么解决

**Comment by welomeo** [comment]
怎么注册

**Comment by xunhuanzhiren** [comment]
里站权限要捐多少？

**Comment by ChristopherRive** [comment]
兄弟们，我各种节点都试了，就是进不去里站ex，但是e-随便进去都能看，好急，想看的在ex看不了，求帮助，有偿

**Comment by xingyeyou** [comment]
之前能看里站的，昨天晚上突然看不了了，怎么办

**Comment by PegaXuX** [comment]
> 之前能看里站的，昨天晚上突然看不了了，怎么办

same issue

**Comment by 3525932396** [comment]
我这边里站显示“什么都没找到”（这是在主页！）
包括收藏夹和书签都是这样！
但是表站可以进。
求助！

**Comment by cykalurker** [comment]
一台手机可以进，另一台进不去。网络相同配置相同什么情况。
都有谷歌框架的外行机

**Comment by xingyeyou** [comment]
> 兄弟们，我各种节点都试了，就是进不去里站ex，但是e-随便进去都能看，好急，想看的在ex看不了，求帮助，有偿

我现在是把节点改成美国了，然后网页登陆，现在可以了，你试试

**Comment by xingyeyou** [comment]
> 我这边里站显示“什么都没找到”（这是在主页！） 包括收藏夹和书签都是这样！但是表站可以进。 求助！

我现在是把节点改成美国了，然后网页登陆，现在可以了，你试试

**Comment by xingyeyou** [comment]
> > 之前能看里站的，昨天晚上突然看不了了，怎么办
> 
> 同样的问题

我现在是把节点改成美国了，然后网页登陆，现在可以了，你试试

**Comment by dfh10010** [comment]
他们的方法我都进不去里站。我自己倒是乱弄之后进去了。首先要翻墙，然后再设置-EH-EHentai设置，把浏览地区/国家改为你用的节点（这一步也许可以忽略，因为我忘了应用也成功了），要是就不去EHentai设置，会跳出提示，说该节点连接过多，暂时用不了（反正差不多是这个意思）。提示最后会有时间，等时间到了再刷新主页或者重新启动E站，然后就进去了，而且不用在翻墙了，可以直连里站了

**Comment by dfh10010** [comment]
> 他们的方法我都进不去里站。我自己倒是乱弄之后进去了。首先要翻墙，然后再设置-EH-EHentai设置，把浏览地区/国家改为你用的节点（这一步也许可以忽略，因为我忘了应用也成功了），要是就不去EHentai设置，会跳出提示，说该节点连接过多，暂时用不了（反正差不多是这个意思）。提示最后会有时间，等时间到了再刷新主页或者重新启动E站，然后就进去了，而且不用在翻墙了，可以直连里站了

![IMG_20241225_140358](https://github.com/user-attachments/assets/d440c1d5-e5b3-4d36-8d61-1e04cf92c6bf)
![IMG_20241225_140435](https://github.com/user-attachments/assets/49efa50d-814a-4d99-8791-0fe0d4a65c9d)
我翻墙用的软件

**Comment by 7854mc** [comment]
有没有大佬知道为什么我有时候可以进里站有时候就不能显示什么都没有？

**Comment by liuyun114** [comment]
还真是，把节点变成美国，再重新网页登录就好了

**Comment by summerdada2077** [comment]
我自己弄好了，主要是新版本e站网页登录有问题，我是把绿e卸了（一定要卸载）然后下载以前的版本，之后像上面说的挂梯子网站登录就好了，还有一点就是登录后你的收藏夹会被清空，谨慎选择用不用我的方法哦

**Comment by wobuganxing** [comment]
你们说的方法全用了个遍 死活登不上去里站💢还想着注销个账号 重新创一个 结果不让我销

**Comment by hhd60** [comment]
我的是直接是cookie:igneous:mystery，完全不知道怎么弄....

**Comment by zishi2949-art** [comment]
“错误的igneous检查账号里站权限后重新登录”
这个怎么解决

**Comment by hsl2534** [comment]
“错误的igneous检查账号里站权限后重新登录”
这个怎么解决，之前是有可以进入里站的，然后现在登录了之后不显示我正常的用户名，就显示“little hippo”， 然后身份cookie不能用于登录

**Comment by ranger0812933** [comment]
> 「錯誤的igneous檢查帳號里站權限後重新登入」 這個怎麼解決，之前是有可以進入里站的，然後現在登錄了之後不顯示我正常的用戶名，就顯示“小河馬”，然後身份cookie無法用於登錄

我也遇到這問題.有救嗎

**Comment by fbizhg** [comment]
同样是这个问题，怎么破。
> “错误的igneous检查账号里站权限后重新登录”
> 这个怎么解决，之前是有可以进入里站的，然后现在登录了之后不显示我正常的用户名，就显示“little hippo”， 然后身份cookie不能用于登录

**Comment by summerdada2077** [comment]
我的重新可以进里站了。先说我账号和你们的一样以前，有里站权限后来也出现了igneous错误。解决方法也很奇怪，我甚至不知道他有没有效：正常使用e站表站，打卡登录，大概几天之后打开VPN，在浏览器网页上打开E站，然后在新版登录界面点“通过网页登录”，输入账号密码就能进了。其他我什么也没做了，如果没用不要喷谢谢

**Comment by perfect568** [comment]
网页登录和cookie都能用就是显示错误到底要怎么进

**Comment by liuyun113** [comment]
气笑了，还是用美国的节点然后网页登录进里站最好使，其他节点网页登录都用不了

**Comment by dfh10010** [comment]
我找到新的软件了JHenTai，跟E站同源，而且会直接告诉问题是什么（不过根据我的使用一般都是网络问题，直接裸连或者加速器换个节点就行，当然登录时还是要翻墙的）

我用中国移动云盘给你分享的文件：“1”
链接: https://yun.139.com/shareweb/#/w/i/2tyana2mRAzcr
/*v9V1mSm94ARH:/ 
复制本段信息，打开「中国移动云盘APP」获取。人人不限速，移动用户免流量！

这里面有我用到的软件（里面不止J站还有其他好东西），链接好像可以直接在网页上打开和下载的，不需要下载云盘

绿茶VPN
下载链接：（推荐谷歌chrome浏览器开启）： https://55.lcvpn.top?id=500699866

**Comment by liu1786561441-gif** [comment]
牢大救命了，你是我的神！

**Comment by laofengbao** [comment]
错误的igneous
检查账号里站权限后重新登
录

这个问题怎么解决？

**Comment by laofengbao** [comment]
错误的igneous
检查账号里站权限后重新登
录

这个问题怎么解决？
重新登录也没有用，挂美国梯子也不行，我之前是有里站权限的

**Comment by hanyayay** [comment]
兄弟，搞定了没，搞定了教教我，我也是这个问题

**Comment by laofengbao** [comment]
我解决了，我一共有三个E站的号，两个没里站权限的号，一个有权限的号，我出现那个问题后我退出重登登错号了，登成了没权限的号我以为是有权限的号，再加上我那时候以为我只有两个号就以为是软件出问题了还删了重下了一遍结果没用，直到几天后我翻收藏的才发现这个是我以前没权限的号，因为很多都是我很久以前看的，我才想起来自己有三个号，登了那个有权限的号发现可以看了&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;最后我总结一下我认为有用的方法没用的话可别怪我，第一重新登录挂美国地区的梯子，第二如果没有用就先退回表站正常签到几天再退出重新登录记得挂美国的梯子还有第一第二的重新登录用的是软件里的网页登录，第三是实在没办法的办法重新创一个账号这个就不用我教了吧，还有上面的方法要在你有真有里站权限的情况下用，最后希望你不是跟我一样登错号了如果是那也不错只需第一应该就行了


有收到请回复有，如果我的方法真的有用就跟我讲一下，我也好把方法分享给大家当然你分享也行就是希望分享的时候加上我的网名 老冯包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年5月3日(周日) 晚上11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 登陆里站后不能直连 (Issue #180)


hanyayay left a comment (xiaojieonly/Ehviewer_CN_SXJ#180)
 
兄弟，搞定了没，搞定了教教我，我也是这个问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanyayay** [comment]
我就这一个号，重新创个号进里站还得费钱，第二个我还没搞清签到是怎么个签到法，应该是登陆自动签了，我签到三天重新登也没用

**Comment by hanyayay** [comment]
会不会是因为我日常挂梯子进的，然后检测到地址不对把我的权限取消了？

**Comment by hanyayay** [comment]
> 我解决了，我一共有三个E站的号，两个没里站权限的号，一个有权限的号，我出现那个问题后我退出重登登错号了，登成了没权限的号我以为是有权限的号，再加上我那时候以为我只有两个号就以为是软件出问题了还删了重下了一遍结果没用，直到几天后我翻收藏的才发现这个是我以前没权限的号，因为很多都是我很久以前看的，我才想起来自己有三个号，登了那个有权限的号发现可以看了&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;最后我总结一下我认为有用的方法没用的话可别怪我，第一重新登录挂美国地区的梯子，第二如果没有用就先退回表站正常签到几天再退出重新登录记得挂美国的梯子还有第一第二的重新登录用的是软件里的网页登录，第三是实在没办法的办法重新创一个账号这个就不用我教了吧，还有上面的方法要在你有真有里站权限的情况下用，最后希望你不是跟我一样登错号了如果是那也不错只需第一应该就行了
> 
> 
> 有收到请回复有，如果我的方法真的有用就跟我讲一下，我也好把方法分享给大家当然你分享也行就是希望分享的时候加上我的网名 老冯包
> […](#)

重新创账号还要捐赠才能进里站，主要是我就这一个账号。表站登陆三天然后退出挂美国节点的VPN，网页登陆也不行

**Comment by Nian114514** [comment]
我网页端表里站都可以进，手机端:网页登录也可以进，cookie内容正常，也可以cookie登录，也能正常看里站内容，但是就不能直连，难道现在里站也被墙了吗？

**Comment by HarbingerGunshiplin** [comment]
坏了，忘挂梯子导致我现在出现这情况，有没有比较稳妥的解决方法？我就这一个号了

<img width="720" height="1604" alt="Image" src="https://github.com/user-attachments/assets/cf23ca4d-05c1-47be-a8fa-ad895000ce9f" />

**Comment by Nian114514** [comment]
> 坏了，忘挂梯子导致我现在出现这种情况，有没有比较稳妥的解决方法？我就这一个号了
> 
> <img alt="图像" width="720" height="1604" src="https://private-user-images.githubusercontent.com/184951341/620446886-cf23ca4d-05c1-47be-a8fa-ad895000ce9f.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODM3ODI5NzcsIm5iZiI6MTc4Mzc4MjY3NywicGF0aCI6Ii8xODQ5NTEzNDEvNjIwNDQ2ODg2LWNmMjNjYTRkLTA1YzEtNDdiZS1hOGZhLWFkODk1MDAwY2U5Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcxMVQxNTExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzdhY2Q2MGI3Y2I5MjVhMWQ5NzAyNTVlZmYxZmVkY2MyZWI3MTA2OTg2ZTgwYTZiNGY5YTVlMWIzYjI3ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZqcGVnIn0.xnDNfhJFUW77xE0K3pX8qP_GDZfhaRjMplPmbw5vrjo">

额，我忘挂梯子只是加载不出来，怎么还能导致账号封禁呢？都这样了能怎么着？重新按步骤来呗

**Comment by HarbingerGunshiplin** [comment]
最扯淡的是我网页版是能进去的，黑底里站，但APP进不去了

**Comment by HarbingerGunshiplin** [comment]
签到必须连续签到吗

**Comment by laofengbao** [comment]
你现在是什么问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年7月15日(周三) 中午1:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 登陆里站后不能直连 (Issue #180)


HarbingerGunshiplin left a comment (xiaojieonly/Ehviewer_CN_SXJ#180)
 
签到必须连续签到吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!

**Comment by HarbingerGunshiplin** [comment]
网页版黑底的里站是能上的，但APP因为之前忘挂梯子去看下载上不了了，想怎么解决。因为网站的话不方便

**Comment by Sayu1226** [comment]
转载，我的省流方法：如果你们确信你们的账号有里站权限，且之前登录过里站。使用你们的浏览器翻译，登录e-hantai，不要进论坛，先点击我的首页，然后再点击我的设置，把梯子改成美国，然后刷新浏览器，确保IP变为美国，再直接通过网页浏览器进入exhantai。

之前有段时间没上e站，然后app就崩了，然后网页版的也进不去里站，当时以为是梯子炸了，就懒得弄直接用n站了，可是n站只收bz，没有cg，就倒腾了网页版的问题，发现是e站因为政治敏感封锁了亚太和us的ip导致进不了里站，但只要用挂个欧洲的ip就能解锁，之后所有的ip都能进了，我认为app也是同样的原因所以在之前的版本都进行各种尝试，但奈何我是个小白，这些host，dns什么的都不是很清楚，只能一个个尝试，但是变量太多，没有一个个是试完，也有可能是版本的原因，但总算在今天歪打正着了。

如果你是表站可以正常直连，拥有e站账号，进里站只有root哭泣，电脑端里站进不去，那你大概率可以通过此方法解决：版本1.7.10.1 准备一个有欧洲节点的vpn，将app的账号退出，关闭url和dns其他全开，退出app并在设置中彻底关闭，打开vpn挂欧洲节点（全局模式），打开app选择ex站点，如果画廊能够加载的话以后就可以正常直连了。希望对大家和开发者有所帮助。

**Comment by bu75ft** [comment]
> > 兄弟们，我各种节点都试了，就是进不去里站ex，但是e-随便进去都能看，好急，想看的在ex看不了，求帮助，有偿
> 
> 我现在是把节点改成美国了，然后网页登陆，现在可以了，你试试

我艹牛逼啊，真解决了，谢谢哥们儿
