### ISSUE TITLE
关于排行榜的一些建议

### ISSUE THREAD

**Issue by wordly123** [xiaojieonly/Ehviewer_CN_SXJ#181]
我想对排行榜这个功能提几点建议望采纳
其实很早之前我就想如果每天有一个按照收藏数量的排行榜就可以方便的找一些hso的本子 免去了天天找本子的痛苦
    1.其实大家只对画廊的排行榜感兴趣其他的排序我感觉可以去掉
    2.画廊排行榜里可以通过下拉框选择不同的时间段默认的是这一天的 还可以选择今天 今周 今月 今年 或者开放时间范围排序
    3.希望画廊排行榜加上封面缩略图
    4.画廊排行榜点名字跳转过去搜不到东西我不知道是不是设置的原因开启了日文标题这类的
    5.画廊排行榜的排序是否可以添加全局参数，就是我点画廊排行榜的时候加一个搜索参数筛选完后再排序 主要用途就是大伙都想看中文区的排行榜 添加一个全局chinese的标签搜索再排就舒服了当然别人也可以选其他语言的排行榜(当然就我们用的话默认参数也行)
    6.排行榜显示的数量我建议可以让用户自定义选择10条20条 

最后 
这些功能有点多，如果作者没时间的话我看看能抽时间实现这些 同是一名java开发emmm

**Comment by xiaojieonly** [comment]
第一条：既然有了就不删了，删了挺麻烦的，而且或多或少还是有人用的。
第二条：排行榜是个滑动列表，往下滑可以看到过去有史以来、一年、一个月、昨天，这些都是e站官方给的数据，如果需要添加新的排行榜单则需要额外构建服务器收集每个用户的使用信息（先不说服务器的资金问题，如果额外收集用户隐私可能会严重增加法律风险）
第三条：略缩图以后应该会有
第四条：如果登录站点是表站的话，部分标签搜不出东西是正常的因为这些内容可能只有里站才有，如果登录站点是里站，搜不到东西应该是内容已经被删除了，可能是上传的人自己删了也可能是官方下场删除了
第五条：同第二条，目前的排行榜信息是e站官方给的世界排行，国内排行则需要额外搭建服务器搜集用户隐私。
第六条：同上
综合来讲：不是没法实现，但是成本过高
