### ISSUE TITLE
新版通过链接调用APP会闪退

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#186]
从其他APP点击eh的链接跳转到APP后会闪退，点击图标可正常打开APP
![Screenshot_2021-12-13-00-43-51-019_com.miui.thirdappassistant.png](https://user-images.githubusercontent.com/48684035/145721235-b144406a-336f-43fb-ad84-b39e924766ee.png)
![Screenshot_2021-12-13-00-44-00-222_com.miui.bugreport.jpg.png](https://user-images.githubusercontent.com/48684035/145721256-e3192b59-6f56-42a5-8541-83b0f6e4d97d.png)

**Comment by 448464091** [comment]
还有，更新后，使用粘贴板都链接也会闪退

**Comment by Steve-337** [comment]
今天的新版仍然会闪退……我还是暂时回退旧版吧

**Comment by xiaojieonly** [comment]
正在修复，晚上应该可以发布修复版本

**Comment by xiaojieonly** [comment]
已解决
