### ISSUE TITLE
安装软件后，手机默认桌面被替换

### ISSUE THREAD

**Issue by Sakura286** [xiaojieonly/Ehviewer_CN_SXJ#187]
我手机是红米K30 pro，系统是MIUI 12.5.4国际版，安装的Ehviwer版本1.8.95

安装软件后系统导航方式立刻从全面屏手势自动调整为经典导航键，如果在系统里强行切换回全面屏手势，会导致手势失效。并且切换回桌面的时候，系统会提示让我在“POCO桌面”（系统默认）与“Ehviwer”这两个桌面启动器之间进行选择。卸载软件之后这些问题就都恢复正常了。

不是这个版本才有的，之前两个月左右用过一次，出过问题就卸载了。

**Comment by xiaojieonly** [comment]
已解决
