### ISSUE TITLE
如图，可以把你的作者名字加上去

### ISSUE THREAD

**Issue by RxinnotRstar** [xiaojieonly/Ehviewer_CN_SXJ#189]
![Screenshot_2021-12-15-14-39-05-441_com android systemui](https://user-images.githubusercontent.com/56676566/146137461-c467b814-76cc-4708-929a-f1addf5fd492.png)

**Comment by xiaojieonly** [comment]
好的

**Comment by xiaojieonly** [comment]
最新版已加
