### ISSUE TITLE
[功能申请] 自定义hosts中支持同一域名多个解析

### ISSUE THREAD

**Issue by NiceBowl335** [xiaojieonly/Ehviewer_CN_SXJ#19]
exhentai.org和ehgt.org等域名都对应着多个IP，支持在自定义hosts中对它们指定多个解析值也许有助于浏览速度的提升。

**Comment by xiaojieonly** [comment]
> exhentai.org和ehgt.org等域名都对应着多个IP，支持在自定义hosts中对它们指定多个解析值也许有助于浏览速度的提升。
> 另外再次请求与作者互动...
> [#9 (comment)](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/9#issuecomment-735401881)

难度有点高，

> exhentai.org和ehgt.org等域名都对应着多个IP，支持在自定义hosts中对它们指定多个解析值也许有助于浏览速度的提升。
> 另外再次请求与作者互动...
> [#9 (comment)](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/9#issuecomment-735401881)

好的，我想个法子\(￣︶￣*\))

**Comment by xiaojieonly** [comment]
咋关掉了？真打算下一版更新这个功能来着。。。。

**Comment by xiaojieonly** [comment]
> 咋关掉了？真打算下一版更新这个功能来着。。。。

哦，不对，已经支持了😂更新日志里忘填了
