### ISSUE TITLE
1.8.9.5点击评论区链接闪退

### ISSUE THREAD

**Issue by Roseoice** [xiaojieonly/Ehviewer_CN_SXJ#192]
设备Redmi k40，系统MIUI 12.5.18
1.8.9.5点击评论区链接闪退，提示应用空指针问题导致闪退

**Comment by xiaojieonly** [comment]
哪个画廊，给个画廊名字

**Comment by Roseoice** [comment]
实际使用中我看到画廊评论区有链接的都去试着点击，无一例外全部闪退

**Comment by Steve-337** [comment]
> 哪个画廊，给个画廊名字

实际上只要通过链接调用APP都会闪退，不管是APP内点击链接还是外部APP链接https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/186

**Comment by xiaojieonly** [comment]
我研究下

**Comment by xiaojieonly** [comment]
最新版本已解决。
