### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by qsh520** [xiaojieonly/Ehviewer_CN_SXJ#193]
![Uploading Screenshot_2021-12-19-15-59-27-70.png…]()

**Comment by xiaojieonly** [comment]
安卓几？什么手机？什么版本？你这图片我看不见
![image](https://user-images.githubusercontent.com/49278135/146677797-407a9649-a160-4969-bd3c-078d02dd3912.png)

**Comment by xiaojieonly** [comment]
额，太久没回复了，我关了
