### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by chenguanm** [xiaojieonly/Ehviewer_CN_SXJ#194]
图片为什么一直加载不出来

**Comment by chenguanm** [comment]
安卓11系统

**Comment by RxinnotRstar** [comment]
WiFi、数据流量互换，挂vpn或者断开vpn，检查设置的内置hosts有没有打开，检查软件是不是最新版本

**Comment by chenguanm** [comment]
手机host怎么开关？

**Comment by RxinnotRstar** [comment]
ehviewer设置-高级

**Comment by xiaojieonly** [comment]
https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg

**Comment by xiaojieonly** [comment]
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

**Comment by chenguanm** [comment]
谢谢成了
