### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by a765431** [xiaojieonly/Ehviewer_CN_SXJ#195]
[https://www.dropbox.com/s/73dcxbcpwxbfaa6/Screenshot_2021-12-21-19-53-48.png](https://www.dropbox.com/s/73dcxbcpwxbfaa6/Screenshot_2021-12-21-19-53-48.png)
Sony Xperia Z5 Premium E6833

**Comment by duzhaokun123** [comment]
android 多少

**Comment by a765431** [comment]
5.1.1

**Comment by xiaojieonly** [comment]
安卓5？？？？

**Comment by xiaojieonly** [comment]
最低得安卓6

**Comment by xiaojieonly** [comment]
这版本也太低了。。。。
