### ISSUE TITLE
直连环境下开启DoH后出现问题，无法下载/浏览图片。

### ISSUE THREAD

**Issue by fuchanghao** [xiaojieonly/Ehviewer_CN_SXJ#199]
下载/浏览图片永远是0%进度，必须要开启代理后才正常。
缩略图没有问题。

换成另一个人的ehviewer同样直连也能下载。
https://gitlab.com/NekoInverter/EhViewer

这里尝试关闭DoH后就能下载了，不知道这是什么bug。

[![TtSPb9.jpg](https://s4.ax1x.com/2021/12/24/TtSPb9.jpg)](https://imgtu.com/i/TtSPb9)

**Comment by xiaojieonly** [comment]
那就别开DNS，国内的dns全是被gfw污染过的

**Comment by xiaojieonly** [comment]
dns不是给国内用户用的

**Comment by lxksir** [comment]
加载不了预览图片请问是怎么回事呢

**Comment by subjects52** [comment]
只能看一页的内容，其他全是解析失败是怎么回事，有没有大佬解决一下

**Comment by opalfox** [comment]
老哥，我这里缩略图和预览图都可以加载，想看大图或者下载的话就会无限转圈/网络错误。请问这应该怎么解决吖，万分感谢🙏🏻

**Comment by Babymagun-1** [comment]
直接卸载，然后重新下载一个新的，然后按照网上写的该关啥就关啥就ok



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月6日(周六) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 直连环境下开启DoH后出现问题，无法下载/浏览图片。 (Issue #199)




 
老哥，请问我这里缩略图和预览图都可以加载，想看大图或者下载的话就会无限转圈/网络错误。请问这应该怎么解决吖，万分感谢🙏🏻

**Comment by kuhdrd** [comment]
现在是2023/1/6，我遇到了相应的问题无法解决，但我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来

**Comment by Dhfoe** [comment]
> 现在是2023/1/6，我遇到了相应的问题无法解决，但我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来

同上，我也是这个问题，更新到最新版还是解决不了，去其他e看了看好像是江苏重庆地区的ip劫持

**Comment by kuhdrd** [comment]
> > 现在是2023/1/6，我遇到了相应的问题无法解决，但我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来
> 
> 同上，我也是这个问题，更新到最新版还是解决不了，去其他e看了看好像是江苏重庆地区的ip劫持

我现在应该是解决了，我用[https://github.com/UjuiUjuMandan](url)这位主页的白eh下载绿eh里无法下载的项目，然后再在绿eh里挂梯子识别文件

**Comment by Dhfoe** [comment]
> > > 现在是2023/1/6，我遇到了相应的问题无法解决，但我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来
> > 
> > 
> > 同上，我也是这个问题，更新到最新版还是解决不了，去其他e看了看好像是江苏重庆地区的ip劫持
> 
> 我现在应该是解决了，我用[https://github.com/UjuiUjuMandan](url)这位主页的白eh下载绿eh里无法下载的项目，然后再在绿eh里挂梯子识别文件

我下载安装包解析错误，安卓9版本安装不了

**Comment by Dhfoe** [comment]
> > > 现在是2023/1/6，我遇到了相应的问题无法解决，但我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来
> > 
> > 
> > 同上，我也是这个问题，更新到最新版还是解决不了，去其他e看了看好像是江苏重庆地区的ip劫持
> 
> 我现在应该是解决了，我用[https://github.com/UjuiUjuMandan](url)这位主页的白eh下载绿eh里无法下载的项目，然后再在绿eh里挂梯子识别文件

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/pull/985
刚刚看到的，作者已经在解决了，还是等等吧

**Comment by darkundead55555** [comment]
1.9.6.9可以下载本子，之后的任一版本都只能点下载之后几秒内下载，然后停止，没打开DOH，也没用梯子，不知什么问题

**Comment by HMSGUO** [comment]
一点新问题，app写入失败
网页可以看，app无法查看和下载，只能预览
据其他网友考证是：文件夹名称有个长空格，不符合win命名规则，下载会写入失败

**Comment by hanyayay** [comment]
大佬，我这里是新版，封面能看到图但是点开后翻到下面显示没有预览，点开也看不到图片，是怎么回事
![Uploading Screenshot_20241026_213222_com.xjs.ehviewer.jpg…]()
![Uploading Screenshot_20241026_213226_com.xjs.ehviewer.jpg…]()

**Comment by hanyayay** [comment]
大佬，我这里是新版，封面能看到图但是点开后翻到下面显示没有预览，点开也看不到图片，是怎么回事？

**Comment by hanyayay** [comment]
画廊预览点开之后显示No hint

**Comment by 11111molang** [comment]
为什么我的e站能加载封面图片和略缩图，要是点进去看就一直加载，最后用红字写个读取失败，卸了重下还是这样。

**Comment by sunruizhe33-ops** [comment]
我也有加载不了图片，红字读取失败的问题

**Comment by chenmenglixue** [comment]
最新版本，封面和预览正常，大图读取失败

**Comment by ryotu8120-code** [comment]
我在看的时候会出现部分图片很快加载出来，而另一部分图片一直在加载转圈乃至最后出现读取失败的情况，因为后者又会导致我的下载一直完成不了，请问这是什么原因呢。

**Comment by 1234qwer-a** [comment]
我昨天还可以成功下载，今天就无法下载了，下载画廊，进度条一直是0B/s画廊除了封面，其他的都是没法加载出来的，睡个觉起来就这样了，更新了版本之后也是没用，两台手机上的都是，内存也没有满，也连了网，第三台可以下，但下的也很慢，半天也只下了一张，尝试了很多方法都没用，请知道怎么解决的人提供帮助
