### ISSUE TITLE
你好 封面显示不了呢

### ISSUE THREAD

**Issue by luckyboysmith** [xiaojieonly/Ehviewer_CN_SXJ#2]
你好，封面显示不了呢，希望能处理下，谢谢~~~~~~~~~~~~~~~~~~~~
感谢付出

**Comment by shuaixiaojie** [comment]
这个通常是网络原因，我自己手机上是可以显示的

**Comment by shuaixiaojie** [comment]
可以试试取消图片自适应

**Comment by Tstiano** [comment]
我也不能显示封面了呢。。。 图片自适应的设置请问在哪里呢？没有找到。。 感谢更新和付出👍

**Comment by shuaixiaojie** [comment]
设置->EH->往下滑 ->修正略缩图链接 或者可以试试设置略缩图大小为小

**Comment by luckyboysmith** [comment]
你好 你是不是在国外或者香港呢
我这边 从11月之后 基本上 打开app就无法显示封面 
在EH->设置->高级->关闭内置host后 直接无法访问，但是 此时 挂上vpn后可以访问 ，
但是 这挺麻烦的，如果不挂vpn 就是封面显示不了，但是可以下载，贴吧里这种情况遇到的人也挺多的，希望能再帮忙看看呢，谢啦ヾ(o′▽`o)ノ°°谢谢

**Comment by luckyboysmith** [comment]
> 设置->EH->往下滑 ->修正略缩图链接 或者可以试试设置略缩图大小为小



> 设置->EH->往下滑 ->修正略缩图链接 或者可以试试设置略缩图大小为小

你好 你是不是在国外或者香港呢
我这边 从11月之后 基本上 打开app就无法显示封面 
在EH->设置->高级->关闭内置host后 直接无法访问，但是 此时 挂上vpn后可以访问 ，
但是 这挺麻烦的，如果不挂vpn 就是封面显示不了，但是可以下载，贴吧里这种情况遇到的人也挺多的，希望能再帮忙看看呢，谢啦ヾ(o′▽`o)ノ°°谢谢

**Comment by shuaixiaojie** [comment]
嗯，我贴吧里有挂帖子，我会尽快排查的，国内我用的电信网，是可以加载图片的😥≡(▔﹏▔)≡

**Comment by gsliuming** [comment]
您好，感谢您！我这里也是，主页的缩略图加载不出来，点进去再退出来才能加载。

**Comment by Tstiano** [comment]
> 嗯，我贴吧里有挂帖子，我会尽快排查的，国内我用的电信网，是可以加载图片的😥≡(▔﹏▔)≡

我也是电信网，wifi和数据都试过，封面图加载不出来，同样的网络以前是没有问题的。感谢付出哦，加油！

**Comment by shuaixiaojie** [comment]
😰ok 正在研究

**Comment by Tstiano** [comment]
> 😰ok 正在研究



> 😰ok 正在研究

潇杰冲冲冲，感谢你👍

**Comment by 546077311** [comment]
感觉是封面的链接地址的内置hosts失效了，请问能提供封面的网络地址吗？我可以试试自己添加hosts~

**Comment by 1786178749** [comment]
关掉内置hosts，然后用梯子连就行了

**Comment by gsliuming** [comment]
挂梯子太麻烦了，能修复下内置hosts

**Comment by xiaojieonly** [comment]
> 挂梯子太麻烦了，能修复下内置hosts吗？谢谢啦！

好的，改好我就发一版

**Comment by xiaojieonly** [comment]
> 挂梯子太麻烦了，能修复下内置hosts吗？谢谢啦！

host修了一下，你可以看看最新版有没有用
