### ISSUE TITLE
[功能申请] 本地下载模块区分“已下载”，“未下载”，“下载中”3种类型的本子

### ISSUE THREAD

**Issue by qszine377** [xiaojieonly/Ehviewer_CN_SXJ#20]
想先提出这个需求，如果有大佬能实现的话真是感激不尽。

**Comment by w3553632** [comment]
我的想法是下载单独分出来，下载完后放到本地阅读列表里，本地阅读里加一个搜索和排序功能（最后一次阅读/阅读进度/名称排序/发行日期/下载日期）。简单说就是增强app作为本地阅读器的体验

**Comment by xiaojieonly** [comment]
> 我的想法是下载单独分出来，下载完后放到本地阅读列表里，本地阅读里加一个搜索和排序功能（最后一次阅读/阅读进度/名称排序/发行日期/下载日期）。简单说就是增强app作为本地阅读器的体验

别着急，有空就写

**Comment by xiaojieonly** [comment]
已实现
