### ISSUE TITLE
长按画廊闪退

### ISSUE THREAD

**Issue by ELITTK** [xiaojieonly/Ehviewer_CN_SXJ#200]
应用版本1.8.10.2
安卓12
`
[logcat-2021-12-26-10-22-25-085.txt](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/7776466/logcat-2021-12-26-10-22-25-085.txt)
`
在主页，订阅，热门以及搜索中长按画廊应用会崩溃
在下载 历史 收藏中，均能正确运行

**Comment by xiaojieonly** [comment]
好的，我尽快修复

**Comment by xiaojieonly** [comment]
最新版已修复
