### ISSUE TITLE
是否考虑编译并发布armv8版本

### ISSUE THREAD

**Issue by Fhokud** [xiaojieonly/Ehviewer_CN_SXJ#201]
近来某些设备已经在大中小核心中放弃对armv7的支持，只在超大核中保留armv7的支持，这时armv7的应用会出现耗电量巨大的问题，而armv8可以带来更低的耗电量以及更好的性能。

**Comment by xiaojieonly** [comment]
额，我研究下，我都是Android studio一键打包的🤣🤣🤣，给我点时间深入学习下，能搞的话我一定搞🧐🧐

**Comment by Fhokud** [comment]
> 额，我研究下，我都是Android studio一键打包的🤣🤣🤣，给我点时间深入学习下，能搞的话我一定搞🧐🧐

https://blog.csdn.net/qq_34983989/article/details/77840089

https://developer.android.com/games/optimize/64-bit?hl=zh-cn

**Comment by Fhokud** [comment]
GitHub Actions不香嘛？

**Comment by Fhokud** [comment]
加油

**Comment by xiaojieonly** [comment]
安排上了

**Comment by xiaojieonly** [comment]
好的，已经跟新成64位的了，你们千呼万唤始出来的64位应用~~~

**Comment by Fhokud** [comment]
感谢大佬

![sjjs](https://user-images.githubusercontent.com/62986412/162612565-61426129-3890-4d56-b7d7-ce5da7c881c3.jpeg)

可以这样打包可以吗，软件就不会变得超级大了
![onward](https://user-images.githubusercontent.com/62986412/162612495-3a12a35a-c8c1-4201-90e3-1fbca52c05ba.jpeg)
