### ISSUE TITLE
关于APP里站

### ISSUE THREAD

**Issue by ccsskk** [xiaojieonly/Ehviewer_CN_SXJ#203]
新手机坏了后新手机重新下了app后收藏夹有些显示 This gallery has been removed or is unavailable。后面想通过更改cookie来获得ignore的数值，但是登录上表站后进不去里站，无法获取数值。为什么换手机前能在APP里看里站本子换手机后不能呢，如果解决无法进入里站问题。十分感谢大家的帮助

**Comment by xiaojieonly** [comment]
cookie不对

**Comment by xiaojieonly** [comment]
进不去就是没有权限

**Comment by ccsskk** [comment]
但是这个账号在上一个手机是能看里站本子的，我不少收藏都是里站的，关于cookie，我试过在pc端登陆表站后再加入里站来查看cookie中错误的ignore，但里站进不去，输入网址后一直全白，无法得到里站的cookie

**Comment by ccsskk** [comment]
但是这个账号在上一个手机是能看里站本子的，我不少收藏都是里站的，关于cookie，我试过在pc端登陆表站后再加入里站来查看cookie中错误的ignore，但里站进不去，输入网址后一直全白，无法得到里站的cookie
