### ISSUE TITLE
识别为桌面，后台不显示

### ISSUE THREAD

**Issue by leemorn** [xiaojieonly/Ehviewer_CN_SXJ#210]
之前一直在用1.8.0.4版本，想试试新版本的，发现下载1.8.10.4会无法显示在后台，然后从1.8.0.4过后试，好像1.8.1.0就已经被识别为桌面了也不能显示后台，恢复到1.8.0.4才能正常使用，手机是1+8t安卓11版本，没有删除app和回滚到之前版本试过

**Comment by xiaojieonly** [comment]
正在处理中

**Comment by xiaojieonly** [comment]
已解决
