### ISSUE TITLE
显示未知主机但是原版正常

### ISSUE THREAD

**Issue by 00lingsui** [xiaojieonly/Ehviewer_CN_SXJ#211]
![Screenshot_2022-01-18-19-38-34-275_com miui home](https://user-images.githubusercontent.com/35698939/149931378-38e5e6c9-e588-416f-a8e2-366e02a7c720.jpg)

**Comment by xiaojieonly** [comment]
啥版本？网络设置设置对了吗？安卓几？

**Comment by 00lingsui** [comment]
> 啥版本？网络设置设置对了吗？安卓几？

最新版本，网络已科学，安卓11

**Comment by xiaojieonly** [comment]
网络设置全关了试下

**Comment by xiaojieonly** [comment]
挂了vpn的话就把app里的网络设置全关了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
