### ISSUE TITLE
求大佬解决一个非软件问题

### ISSUE THREAD

**Issue by dafgdf** [xiaojieonly/Ehviewer_CN_SXJ#217]
为什么在注册时总是跳出如图内容
![FW7`@I6{ QSBEW{ BP(1OOS](https://user-images.githubusercontent.com/98535078/151576844-1349fc58-4e01-4017-810b-4aacafb4a800.png)

**Comment by xiaojieonly** [comment]
https://forums.e-hentai.org/index.php?act=Reg&CODE=00

**Comment by dafgdf** [comment]
> https://forums.e-hentai.org/index.php?act=Reg&CODE=00

我是用的这个网址注册的，但还是会有如图结果

**Comment by xiaojieonly** [comment]
> > https://forums.e-hentai.org/index.php?act=Reg&CODE=00
> 
> 我是用的这个网址注册的，但还是会有如图结果

不会看英文的话，建议用chrome浏览器翻译一下再仔细看一遍翻译信息，然后根据提示注册
