### ISSUE TITLE
ex不显示

### ISSUE THREAD

**Issue by no1011** [xiaojieonly/Ehviewer_CN_SXJ#222]
请问我电脑网页ex正常 app的ex不显示内容是什么情况

**Comment by xiaojieonly** [comment]
没登陆？
用cookie重新登陆下试试

**Comment by YacratesWyh** [comment]
遇到了同一个问题。我解决需要手动更改cookie中igeneous项的数值。我用yandex浏览器装插件可以正常访问。应该用cookie手动登录就好了

**Comment by xiaojieonly** [comment]
> 请问我电脑网页ex正常 app的ex不显示内容是什么情况

楼上正解

**Comment by MadDogFG** [comment]
ex显示未知主机也是楼上的解决方法

**Comment by fand-alt** [comment]
请问具体是什么数值和什么插件呢
😢

**Comment by rwind1234** [comment]
所以igeneous項的數值到底改成什麼呢

**Comment by MadDogFG** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/150
看这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 中午1:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] ex不显示 (Issue #222)





 
所以igeneous項的數值到底改成什麼呢

**Comment by ametoyuki098** [comment]
请问是什么插件

**Comment by littleYOUTUBERqp** [comment]
我和你正相反。我应用ex能上，但网页ex不行。

**Comment by redshotacon** [comment]
9 位 igneous cookie 已于 2024-11-19 凌晨吊销，请不要再使用。那么现在应该如何进入里站呢

**Comment by Fluorrauy** [comment]
我用cookie重新登录，把那一栏留空就行了> 9 位 igneous cookie 已于 2024-11-19 凌晨吊销，请不要再使用。那么现在应该如何进入里站呢

**Comment by caimiao786** [comment]
我也是同样的问题，也是cookie中igeneous项的数值出错，我的解决方案如下：下一个白E（我用绿E这样做但不知道为什么不行），挂一个非滥用的欧洲节点，在白E用cookie登录，注意igneous留空，登录后，在设置中找到身份cookie，如果你的igeneous变为17位的一串字符，那就成功了，复制cookie重新在绿E登录即可，如果还是null或者是mystery，可能是你的账号或者节点有问题

**Comment by cgd2430** [comment]
> 我也是同样的问题，也是cookie中igeneous项的数值出错，我的解决方案如下：下一个白E（我用绿E这样做但不知道为什么不行），挂一个非滥用的欧洲节点，在白E用cookie登录，注意igneous留空，登录后，在设置中找到身份cookie，如果你的igeneous变为17位的一串字符，那就成功了，复制cookie重新在绿E登录即可，如果还是null或者是mystery，可能是你的账号或者节点有问题

我是复制cookie登出重新登录，igneous留空，登录后igneous变成null就能用ex了。

**Comment by debug721** [comment]
绿e挂一个没被滥用的欧洲节点 igneous就好了

**Comment by youshifangyu** [comment]
> 我也是同样的问题，也是cookie中igeneous项的数值出错，我的解决方案如下：下一个白E（我用绿E这样做但不知道为什么不行），挂一个非滥用的欧洲节点，在白E用cookie登录，注意igneous留空，登录后，在设置中找到身份cookie，如果你的igeneous变为17位的一串字符，那就成功了，复制cookie重新在绿E登录即可，如果还是null或者是mystery，可能是你的账号或者节点有问题

**Comment by dave8103018** [comment]
什么都没有找到？

**Comment by Girotly** [comment]
为什么显示ip基础限制？什么是未解锁单独配额，之前一直都可以用的

**Comment by zeolead** [comment]
里站以前可以用的，今天突然间就出现找不到任何东西了，切回表站又可以正常的看东西了这是为什么

**Comment by zeolead** [comment]
继续补充，网页版ex可以使用但APP版的进不去，总是显示找不到任何结果

**Comment by Sayu1226** [comment]
转载，我的省流方法：如果你们确信你们的账号有里站权限，且之前登录过里站。使用你们的浏览器翻译，登录e-hantai，不要进论坛，先点击我的首页，然后再点击我的设置，把梯子改成美国，然后刷新浏览器，确保IP变为美国，再直接通过网页浏览器进入exhantai。

之前有段时间没上e站，然后app就崩了，然后网页版的也进不去里站，当时以为是梯子炸了，就懒得弄直接用n站了，可是n站只收bz，没有cg，就倒腾了网页版的问题，发现是e站因为政治敏感封锁了亚太和us的ip导致进不了里站，但只要用挂个欧洲的ip就能解锁，之后所有的ip都能进了，我认为app也是同样的原因所以在之前的版本都进行各种尝试，但奈何我是个小白，这些host，dns什么的都不是很清楚，只能一个个尝试，但是变量太多，没有一个个是试完，也有可能是版本的原因，但总算在今天歪打正着了。

如果你是表站可以正常直连，拥有e站账号，进里站只有root哭泣，电脑端里站进不去，那你大概率可以通过此方法解决：版本1.7.10.1 准备一个有欧洲节点的vpn，将app的账号退出，关闭url和dns其他全开，退出app并在设置中彻底关闭，打开vpn挂欧洲节点（全局模式），打开app选择ex站点，如果画廊能够加载的话以后就可以正常直连了。希望对大家和开发者有所帮助。
