### ISSUE TITLE
【功能建议】希望适配并提供64位应用

### ISSUE THREAD

**Issue by lazyf11** [xiaojieonly/Ehviewer_CN_SXJ#226]
如题，现如今在骁龙888，尤其8 Gen 1以后大幅缩减32位应用支持变相促进应用开发转64位，而8 Gen 1只有ARM Cortex A710核心支持32位应用，因此，我个人觉得虽然提升可能不是很大，但还是希望能够升级原生支持64位并提供相关软件包下载，谢谢！

**Comment by xiaojieonly** [comment]
说句实话，压根没有必要。。。搞个缓存大点的手机，然后网弄好一点才是正道
![Snipaste_2022-02-13_14-04-55](https://user-images.githubusercontent.com/49278135/153741090-b496ce62-10df-432b-bc13-f717d0f2cdaa.png)

**Comment by duzhaokun123** [comment]
建议 pin 这个 issue 免得再有人问

**Comment by lazyf11** [comment]
> 说句实话，压根没有必要。。。搞个缓存大点的手机，然后网弄好一点才是正道 ![Snipaste_2022-02-13_14-04-55](https://user-images.githubusercontent.com/49278135/153741090-b496ce62-10df-432b-bc13-f717d0f2cdaa.png)

理是这个理，但未来的Android系统迟早会取消掉32位应用的支持啊，虽然我是不强求，只是想问一下有没有计划要转换，然后再提出建议的……不打算做可以延迟。

**Comment by xiaojieonly** [comment]
可以做，改个参数的事，但是安装包会变大一些

**Comment by xiaojieonly** [comment]
以后会改成64位的，你别急

**Comment by lazyf11** [comment]
> 以后会改成64位的，你别急

我也没急啊…

**Comment by xiaojieonly** [comment]
已支持，但稳定性未知
