### ISSUE TITLE
当使用socks代理是强制关闭域名前置

### ISSUE THREAD

**Issue by kagura114** [xiaojieonly/Ehviewer_CN_SXJ#230]
使用socks代理时打开域名前置会导致软件崩溃，而且此组合明显没有任何好处，建议强制二选一，防止出现无法进入软件改回设置

**Comment by xiaojieonly** [comment]
啊这。。。。。我看看怎么解决

**Comment by Fhokud** [comment]
在已经配置socks代理且启用域名前置的情况下，应用会直接闪退，之后应用无法进入。
关闭socks服务器或域名前置后恢复正常。

**Comment by Fhokud** [comment]
可能是1.8.11.3版本以后，因为这个Issues是 Feb 16th, 13th更新了版本号，之后在TG群里看到过反馈

**Comment by xiaojieonly** [comment]
已解决，开了vpn后直接我直接把域名前置软关闭了

**Comment by thirdlee** [comment]
晚上正看着呢，突然白屏了一下然后闪退了，再打开发现下载的内容没了，但是检查了下文件都在，用了设置里的恢复下载项，现在本都在但是下载项标签分类没有了，而且很多本有本地文件也能看但是下载项里搜索不到，本的下载时间也是乱的，有能恢复的方法吗？

**Comment by zhouyuhangc** [comment]
第一次用，没法登录进去改设置怎么办

**Comment by weilongbushiweichong** [comment]
登录完了还停留在登录界面，重复登录还是闪退到登录界面。

**Comment by MarshMoos** [comment]
新版本2.0.2.0，下载功能中的重置阅读进度和搜索画廊均会导致闪退

**Comment by LomgZhan** [comment]
新版2.0.2.0，长按收藏和点击种子均会闪退

**Comment by UDDENEC** [comment]
新版本开了梯子关了前置也会闪退

**Comment by inaitorimichihito-boop** [comment]
在版本2.0.2.0中，**长按图片**或**下载**甚至包括设置中绝大部分会弹出选择界面的互动都会导致**应用崩溃**和**闪退**

**Comment by neap0litanmouse-byte** [comment]
2.0.2.0版本长按画廊闪退，把搜索的词点收藏也会闪退

**Comment by zbmsn0011ext-del** [comment]
> 在版本2.0.2.0中，**长按图片**或**下载**甚至包括设置中绝大部分会弹出选择界面的互动都会导致**应用崩溃**和**闪退**

是的，之前还一切正常，就是从昨天开始的
