### ISSUE TITLE
缺少 EhTopListDetail

### ISSUE THREAD

**Issue by Left024** [xiaojieonly/Ehviewer_CN_SXJ#233]
代码 clone 到本地后用 Android Studio 打开，build 完之后报错缺少 EhTopListDetail，github上翻了翻也没有
求大佬指教

**Comment by xiaojieonly** [comment]
哦，我没提交这部分的代码

**Comment by xiaojieonly** [comment]
过段时间我再提交，或者你也可以按照以自己的想法来创建新的文件

**Comment by Left024** [comment]
谢谢大佬回复，还是希望大佬有空提交下，想学习下
