### ISSUE TITLE
不小心屏蔽了错误tag后衍生的使用问题

### ISSUE THREAD

**Issue by sandio594** [xiaojieonly/Ehviewer_CN_SXJ#235]
[Screenshot_20220224_225504_com xjs ehviewer](https://user-images.githubusercontent.com/57381916/155548611-07456a04-812f-42f6-adff-2d6c4105d06a.jpg)
不好意思，请问咱的设置选项在哪

**Comment by xiaojieonly** [comment]
额，屏幕太小导致按钮显示不全，我看看下一版修复一下

**Comment by xiaojieonly** [comment]
你手机分辨率多少？

**Comment by xiaojieonly** [comment]
什么手机型号

**Comment by xiaojieonly** [comment]
你把手机字体设小一点试试？

**Comment by xiaojieonly** [comment]
变侧栏你往下滑试试？应该可以往下滑的

**Comment by xiaojieonly** [comment]
修好了，正在更新，请稍后
