### ISSUE TITLE
用户名显示问题

### ISSUE THREAD

**Issue by omgpizzatnt** [xiaojieonly/Ehviewer_CN_SXJ#236]
![IMG_20220225_071049](https://user-images.githubusercontent.com/80859414/155623129-72607ea8-ae8d-470b-a732-f990c60e5fa3.png)
我身边的人在这显示的用户名都是这串字母
而且都装的是1.8.11.3或1.8.11.4版

**Comment by xiaojieonly** [comment]
我的，下一版修复
