### ISSUE TITLE
网络错误咋解决

### ISSUE THREAD

**Issue by daolang111** [xiaojieonly/Ehviewer_CN_SXJ#24]
今天显示网络错误咋办

**Comment by Luoyingliang** [comment]
网络错误

**Comment by xiaojieonly** [comment]
> 网络错误

我也没了

**Comment by 0769559** [comment]
大概在刚才已经不是之前的dns污染，E 站遭到
GFW TCP-RST链接阻断。算是喜提国内GFW
最高级网络封锁。
应该是微博的那几个乱发JM图片导致的，把e
站这个灰色的网站硬生生给屏蔽了。

在群里看到别人转发的一张nga的图是这么说的

**Comment by xiaojieonly** [comment]
> 大概在刚才已经不是之前的dns污染，E 站遭到
> GFW TCP-RST链接阻断。算是喜提国内GFW
> 最高级网络封锁。
> 应该是微博的那几个乱发JM图片导致的，把e
> 站这个灰色的网站硬生生给屏蔽了。
> 
> 在群里看到别人转发的一张nga的图是这么说的

@0769559 @Luoyingliang @daolang111 https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/26  
这是我最新分析的结果

**Comment by xiaojieonly** [comment]
> > 大概在刚才已经不是之前的dns污染，E 站遭到
> > GFW TCP-RST链接阻断。算是喜提国内GFW
> > 最高级网络封锁。
> > 应该是微博的那几个乱发JM图片导致的，把e
> > 站这个灰色的网站硬生生给屏蔽了。
> > 在群里看到别人转发的一张nga的图是这么说的
> 
> @0769559 @Luoyingliang @daolang111 #26
> 这是我最新分析的结果

应该还有的救
