### ISSUE TITLE
想请教一下如何取消屏蔽tag

### ISSUE THREAD

**Issue by teamaster23** [xiaojieonly/Ehviewer_CN_SXJ#242]
如题，在手机app端屏蔽错误了一个tag，但现在不知道怎么去掉，而且网页e-hentai上能直接搜到

**Comment by diocvuoawemfx** [comment]
是长按后屏蔽的吗

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/201452788-ff04ef76-7d70-4617-be5e-84ddf699dc99.png)

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/201452848-eeb3845c-39ed-41bc-98ef-473b0c7378ca.png)

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/201452892-21bcdebc-f36e-4689-bb34-b07b3cc0df8a.png)

**Comment by AIDK-202** [comment]
试过了，不行的，长按屏蔽的tag不会在侧边栏显示

![Image](https://github.com/user-attachments/assets/10586efa-3d6c-468e-acb0-4ebaa52edb90)

![Image](https://github.com/user-attachments/assets/4c2ce03a-0acd-4a54-84f2-2ed037135654)

**Comment by Lxxzz0** [comment]
解决方案：
1. 路径
设置 - EH - 屏蔽画廊 - 标签
2. 操作
删除掉不想屏蔽的tag。

**Comment by Lxxzz0** [comment]
![Image](https://github.com/user-attachments/assets/f3d1f302-36b0-47be-956d-687d4fa297be)

![Image](https://github.com/user-attachments/assets/e851c3a2-3d94-48fd-89e5-798f5e6e7e4a)

![Image](https://github.com/user-attachments/assets/6e2c6150-cb19-443e-9417-80b611567cea)
