### ISSUE TITLE
安装最新版本之后经常出现闪退

### ISSUE THREAD

**Issue by Hirschz** [xiaojieonly/Ehviewer_CN_SXJ#246]
每次打开应用程序很快就会闪退
iQOOneo5系统更新到最新版本

**Comment by xiaojieonly** [comment]
具体怎么复现？

**Comment by xiaojieonly** [comment]
是从哪个版本更新过来的？

**Comment by Fhokud** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/230#issuecomment-1073777139

**Comment by Hirschz** [comment]
> 是从哪个版本更新过来的？

我原先用的是1.7版本的e站，后来找在github找到了您发布的 1.8.11.5的安装包，安装后遇到了闪退问题，我尝试从 1.8.11.4版本更新到11.5版本，但仍然有闪退问题。
闪退的具体情况是在下载列表里暂停下载会有很大概率闪退（无论是单一暂停还是全部暂停都会出现闪退情况）。

**Comment by xiaojieonly** [comment]
回退的版本不够多，建议从更低的版本开始覆盖安装
