### ISSUE TITLE
关于华为手机自更新后就闪退的问题

### ISSUE THREAD

**Issue by zd201108** [xiaojieonly/Ehviewer_CN_SXJ#249]
我是从1.7.1版本直接更新到1.8.1版本，主要是1.7.1版本的无法再使用国内直连浏览，后来在朋友传过来的文件里才知道ehviewer已更新至1.8版本，更新以后浏览效率更高，但是在浏览图片时（点开阅读后），如果未等待图片加载完成就关闭阅读，就会立即弹出桌面。有时在下载图片时也会突然崩溃闪退至桌面，当然，也有几次在下载中崩溃时，程序通过自启动，最后画面停留在主页面。
自1.8.1后的每一个版本，基本上都是在按时更新，现在是1.8.11.5版本，该问题依然存在。
求助，这是手机问题还是有什么方法可以避免吗？
手机系统为：harmonyOS：2.0.0.223版本

**Comment by Fhokud** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/230#issuecomment-1073777139

**Comment by xiaojieonly** [comment]
能裸连的尽量裸连

**Comment by xiaojieonly** [comment]
大部分情况下都是梯子导致的

**Comment by xiaojieonly** [comment]
最新版已修复

**Comment by leoymsg** [comment]
新版会闪退

**Comment by wobushidalao233** [comment]
> 新版会闪退

我也是，看一会儿就闪退

**Comment by lotrxh** [comment]
安装后，闪退
