### ISSUE TITLE
将应用升级为64位

### ISSUE THREAD

**Issue by NekoCharm01** [xiaojieonly/Ehviewer_CN_SXJ#250]
目前应用仍然是armeabi-v7a和x86的架构，均为32位，在当前的设备上虽然仍能运行，但是性能不佳，可能出现兼容性问题，并且更新的处理器也会放弃对32位应用的支持。建议尽早升级使用64位的arm64和x86_64架构。

**Comment by Fhokud** [comment]
#201

**Comment by xiaojieonly** [comment]
好的，已经跟新成64位的了，你们千呼万唤始出来的64位应用~~~
