### ISSUE TITLE
裸连无法载出缩略图，走代理后显示网络错误，与#issue199相反的问题

### ISSUE THREAD

**Issue by Szczecin** [xiaojieonly/Ehviewer_CN_SXJ#253]
### 1. 裸连情况下，使用内置hosts.txt，能够获取到内容但是无法载出缩略图（或者是载入很慢）：
![Screenshot_20220329-155943](https://user-images.githubusercontent.com/46680534/160563208-76d6c443-6a94-48d5-a78b-e1c5fca215e9.jpg)

![Screenshot_20220329-155720](https://user-images.githubusercontent.com/46680534/160563253-d0e98872-55b6-4c52-98ef-15698f08ee97.jpg)

![Screenshot_20220329-155755](https://user-images.githubusercontent.com/46680534/160563272-d236cff9-2a4c-41ff-a003-6604068c3676.jpg)

### 2.当挂了代理后，缩略图飞快的载出来，但是无法访问内容，刷新提示网络错误：
![Screenshot_20220329-160342](https://user-images.githubusercontent.com/46680534/160563673-c9cdcf68-95a8-4c67-bacb-3b2fa9d530d5.jpg)

**Comment by zhuixingmomo** [comment]
我也想问这个问题

**Comment by 1532652146** [comment]
有解决办法了吗

**Comment by Szczecin** [comment]
> 我也想问这个问题

自己找到了解决办法：开启有效代理的情况下，在设置 > 高级 > 域名前置 绕过SNI封锁关掉即可。

**Comment by Szczecin** [comment]
> 有解决办法了吗

自己找到了解决办法：开启有效代理的情况下，在设置 > 高级 > 域名前置 绕过SNI封锁关掉即可。

**Comment by xiaojieonly** [comment]
挂了梯子就尽量别用或是少用内置的网络设置，大部分梯子代理技术不咋的，会导致网络配置冲突，严重的会导致软件闪退。当然，如果因为梯子导致软件用不了要让我来修的话，那是不可能的，因为我做的不是vpn~~~
