### ISSUE TITLE
登录用户无法进入里站

### ISSUE THREAD

**Issue by bigwetguo** [xiaojieonly/Ehviewer_CN_SXJ#254]
表站可进，切里站报网络错误，使用网页登录🉑访问里站。

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/222

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
