### ISSUE TITLE
关于版权炮的对策

### ISSUE THREAD

**Issue by pfpfpfp** [xiaojieonly/Ehviewer_CN_SXJ#255]
最近由于Irodori版权炮的缘故，一些画师的本子不能在eh上浏览了，我就想着自己找资源下载放到ehv的download目录里看，但是发现ehv不能识别，这个功能可以实现吗？

**Comment by xiaojieonly** [comment]
未来会可以支持，但是得等，我最近在修里站画廊种子下载的问题
