### ISSUE TITLE
关于网络无响应

### ISSUE THREAD

**Issue by xiaojieonly** [xiaojieonly/Ehviewer_CN_SXJ#26]
正在排查，今晚因该能弄好

**Comment by xiaojieonly** [comment]
原因可能是e站不在支持低版本安卓导致的，而且e站公告栏也有过通知，但是我因为当时工作忙加上抱着侥幸心理就没有及时更换新的协议。而我为了能适配更多机型，强行将最低版本定为了安卓4.0，这才导致了e站协议更新后被拒绝连接。我正在尝试修改低版本安卓系统请求时的ssl协议，尽最大努力保证低版本机型也能正常使用

**Comment by Leedw666** [comment]
但我用的安卓10啊，依然无法访问，eh都上不去

**Comment by zphiroude1234** [comment]
听说是遭到gfw网络封锁

**Comment by Leejiuhao** [comment]
楼上说的问题我今天也遇到了，昨天还访问的好好的，今天突然提示网络错误，无法访问

**Comment by xiaojieonly** [comment]
> 听说是遭到gfw网络封

**Comment by xiaojieonly** [comment]
说出来可能大家不信，我用公司网（香港服务器）发现好好的。。。。。等下班回去试试新办法

**Comment by xiaojieonly** [comment]
> 但我用的安卓10啊，依然无法访问，eh都上不去

但我打包软件时用的安卓4的api。。。。。

**Comment by Leedw666** [comment]
> > 但我用的安卓10啊，依然无法访问，eh都上不去
> 
> 但我打包软件时用的安卓4的api。。。。。

没关系哥，慢慢来，实在不行先整个安卓6版的再弄个安卓4版的

**Comment by xiaojieonly** [comment]
好了

> > > 但我用的安卓10啊，依然无法访问，eh都上不去
> > 
> > 
> > 但我打包软件时用的安卓4的api。。。。。
> 
> 没关系哥，慢慢来，实在不行先整个安卓6版的再弄个安卓4版的

好了
