### ISSUE TITLE
App 卡顿

### ISSUE THREAD

**Issue by OW1TY2** [xiaojieonly/Ehviewer_CN_SXJ#261]
每次一按下载后app都会卡住好一阵子，并频繁跳出停止回应的错误。部分时候app数分钟后便恢复正常，然后下一次按下载又卡住，有时候直接闪退。

此情况在Nokia 6.1Plus，Razer Phone 2和夏普R3三款手机都存在

**Comment by OW1TY2** [comment]
另外，此情况已持续好几个版本

**Comment by xiaojieonly** [comment]
app什么版本？

**Comment by xiaojieonly** [comment]
手机系统是安卓几？

**Comment by OW1TY2** [comment]
App是最新的1.8.12.1 但是1.8.12.0和1.8.11.5都有出现此问题
Android 11 10和9都有这个问题

**Comment by OW1TY2** [comment]
> 手机系统是安卓几？
App是最新的1.8.12.1 但是1.8.12.0和1.8.11.5都有出现此问题
Android 11 10和9都有这个问题

**Comment by OW1TY2** [comment]
> 手机系统是安卓几？



App是最新的1.8.12.1 但是1.8.12.0和1.8.11.5都有出现此问题
Android 11 10和9都有这个问题

**Comment by xiaojieonly** [comment]
最新版有问题吗？

**Comment by OW1TY2** [comment]
> 最新版有问题吗？

有

**Comment by OW1TY2** [comment]
> 最新版有问题吗？

找到问题原因了，原因是我把下载路径设定在SD卡，一旦切换回内置存储空间就不会出现这个问题，希望能帮到

**Comment by xiaojieonly** [comment]
ok

**Comment by xiaojieonly** [comment]
我有空研究下

**Comment by freesan44** [comment]
同出现上述问题，都是把存储路径放在外部SD卡就重复出现，并且很频繁，基本上出现在：
1，非下载时候，点击浏览某个图片
2，点击【下载】
3，某一个任务下载完成继续下一个任务的时候，点击进入其他窗口或者点击浏览图片

应该都是出现在读取或者同时读取下载时候就闪退

**Comment by freesan44** [comment]
@xiaojieonly 您好，请问这个闪退问题已经有解决方案了吗？因为现在使用闪退太频繁，基本上要闪退2,3次才能正常使用

**Comment by tcliuqq** [comment]
我的个人缓解问题办法：
1.每次进入app，随意找一本进入浏览，并开始卡顿；
2.等待至卡顿结束，可正常观看；
3.此时返回下载（同样路径在外置sd卡），则连续下载丝滑不卡顿。

**Comment by IABBI** [comment]
你好，浏览图片数量超过100张左右的画廊就会很卡，手机三星S24，安卓14，是不是三星自己的问题，感觉之前用别的牌子好像没遇到过

**Comment by bmhms** [comment]
> 你好，浏览图片数量超过100张左右的画廊就会很卡，手机三星S24，安卓14，是不是三星自己的问题，感觉之前用别的牌子好像没遇到过

作者好像不会做回复了

**Comment by JoeBrown09** [comment]
为什么突然有一天app完全无法运行，只能看到[我的收藏]，且无法打开，每个界面都在不停转

**Comment by zon8744-source** [comment]
me too> 为什么突然有一天app完全无法运行，只能看到[我的收藏]，且无法打开，每个界面都在不停转

**Comment by x1416041307** [comment]
哈哈。手贱点了下左边侧边栏的更改底图。现在侧边栏一划就闪退。怎么才能导出历史和下载数据啊。
