### ISSUE TITLE
画廊信息里有种子链接，但页面种子选项里没有种子，如何下载

### ISSUE THREAD

**Issue by Acgholic** [xiaojieonly/Ehviewer_CN_SXJ#264]
经常看到这种情况，画廊信息里有种子链接，但页面种子选项里没有种子，请问这样的种子如何下载？就是查看更多信息里，倒数第二行的种子那一项，如何下载这个链接对应的种子？

**Comment by xiaojieonly** [comment]
什么版本？

**Comment by onetianqing** [comment]
我感觉是没有种子文件上传，因为进去是种子画廊

**Comment by Acgholic** [comment]
> 什么版本？

1.9.0.4

**Comment by Acgholic** [comment]
> 我感觉是没有种子文件上传，因为进去是种子画廊

应该就是没有上传，但是画廊信息页面倒数第二行种子那一项有种子的地址，我就想知道这个地址的种子怎么下载？没法直接打开。

**Comment by xiaojieonly** [comment]
画廊详情页不是有种子下载入口吗？？？？？？

**Comment by xiaojieonly** [comment]
![31651717628_ pic](https://user-images.githubusercontent.com/49278135/166855625-f211e679-d7ae-4b5d-9b01-cbcb4e94ed15.jpg)
这个没法用？？？？？

**Comment by xiaojieonly** [comment]
没其他问题的话我就关了。。。。。。

**Comment by Acgholic** [comment]
> ![31651717628_ pic](https://user-images.githubusercontent.com/49278135/166855625-f211e679-d7ae-4b5d-9b01-cbcb4e94ed15.jpg) 这个没法用？？？？？

![Screenshot](https://user-images.githubusercontent.com/104074729/166858051-5dfbfb33-238d-4061-8d8b-639db54ad31a.jpg)
这种情况。没有种子文件，但是有种子地址。还是我理解错了，有种子地址，不一定有种子文件。
