### ISSUE TITLE
1.9.0.4打开zip压缩包漫画闪退

### ISSUE THREAD

**Issue by heoolaya** [xiaojieonly/Ehviewer_CN_SXJ#266]

**Comment by xiaojieonly** [comment]
？操作流程是啥？

**Comment by heoolaya** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Saciss** [comment]
> ？操作流程是啥？

打开漫画，看了几张，闪退( •̥́ ˍ •̀。 )

**Comment by heoolaya** [comment]
选择打开方式里选择ehviewer，选择后会直接闪退（1.8的版本基本会直接闪退），还有其他好几个版本（大约1.7之前的版本）能看一会，看一段时间后也会闪退，忘了以前用的那个版本，没有这些问题，zip压缩包六七百兆，机型honor 20青春版，不清楚是否个例




hello
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] 1.9.0.4打开zip压缩包漫画闪退 (Issue #266)





 
？操作流程是啥？

**Comment by xiaojieonly** [comment]
那你先回滚到旧版吧，这bug我得研究下

**Comment by hhy3390** [comment]
同遇到这个问题

**Comment by xiaojieonly** [comment]
最新版已解决

**Comment by heoolaya** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by heoolaya** [comment]
选择打开方式里选择ehviewer，选择后会直接闪退（1.8的版本基本会直接闪退），还有其他好几个版本（大约1.7之前的版本）能看一会，看一段时间后也会闪退，忘了以前用的那个版本，没有这些问题，zip压缩包六七百兆，机型honor 20青春版，不清楚是否ge'li
&nbsp;


hello
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 晚上9:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 1.9.0.4打开zip压缩包漫画闪退 (Issue #266)





 
？操作流程是啥？
