### ISSUE TITLE
hxd们，为什么我直连的情况下一直在加载呢？？

### ISSUE THREAD

**Issue by Saciss** [xiaojieonly/Ehviewer_CN_SXJ#267]

**Comment by Saciss** [comment]
![Uploading Screenshot_20220507_131438.jpg…]()

**Comment by xiaojieonly** [comment]
看不到截图

**Comment by Saciss** [comment]
![Screenshot_20220507_131438](https://user-images.githubusercontent.com/81513526/167256182-a8d1510d-fb63-4766-99aa-cfaf62a124a2.jpg)

**Comment by Saciss** [comment]
> 

现在可以看到了吗( •̥́ ˍ •̀。)

**Comment by xiaojieonly** [comment]
两个host都开了然后重启软件

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
