### ISSUE TITLE
收藏功能err

### ISSUE THREAD

**Issue by KleinKon** [xiaojieonly/Ehviewer_CN_SXJ#268]
点击收藏err，试了另一个版本的APP，也是err

**Comment by xiaojieonly** [comment]
没登录

**Comment by KleinKon** [comment]
登录了，用Cookie登录好几次都是err，只有侧栏还能正常显示收藏数。

**Comment by KleinKon** [comment]
![Uploading Screenshot_2022-05-30-23-40-36-665_io.github.nekoinverter.ehviewer.jpg…]()

**Comment by xiaojieonly** [comment]
截图看不见

**Comment by xiaojieonly** [comment]
是不是网络配置没配置好？

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by KleinKon** [comment]
网络配置和图里一样的 还是err

**Comment by xiaojieonly** [comment]
可能是账号问题，建议注册一个新账号看下
