### ISSUE TITLE
想请教一下，我这站点是eh，不是ex，但是无论我用什么代理或者裸连都是这个界面

### ISSUE THREAD

**Issue by otokaz** [xiaojieonly/Ehviewer_CN_SXJ#269]
换手机换网换代理，进去都是这个界面。
![Screenshot_20220509_134218_com xjs ehviewer](https://user-images.githubusercontent.com/77291634/167347846-1fd3d3b8-0f4d-46ba-814e-a61738c1cc53.jpg)

另外，我本来能进ex的，可是前几天开始我进不去了，显示sadpanda（with no panda），请问这个要怎么解决呢？

**Comment by otokaz** [comment]
哦对了，网络的设置是按照之前的来的
![Screenshot_20220509_140450_com xjs ehviewer](https://user-images.githubusercontent.com/77291634/167349960-9e2d2ca8-fd7f-4477-92c3-68321fc3d700.jpg)

试了下，我的网挂上科技之后是可以进nclient和pupil还有其他外网的。。

**Comment by Saciss** [comment]
＋1

**Comment by otokaz** [comment]
刚刚又试了下，网页端这些也是进不去。。是不是我科技出问题了

**Comment by ArcueidBrunsted** [comment]
Same issue

**Comment by 1090004161** [comment]
我也是这样不知道怎么回事

**Comment by ArcueidBrunsted** [comment]
看来还是梯子问题，我关了梯子直连居然能上，Shanghai Telecom

**Comment by otokaz** [comment]
> 

我关了还是一样。。。

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by otokaz** [comment]
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

看了，没有能解决的。。

**Comment by otokaz** [comment]
![Screenshot_20220514_103803_com xjs ehviewer](https://user-images.githubusercontent.com/77291634/168407843-feced296-b3c7-4111-a73a-dccf2722dda1.jpg)
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

![Screenshot_20220514_103813_com xjs ehviewer](https://user-images.githubusercontent.com/77291634/168407835-c1ffb4c4-2965-498d-87e9-d2897ecd7cba.jpg)

**Comment by otokaz** [comment]
另外，我发现我就算挂着梯子，怎么切线路，eh网页版无论里站还是表站我还是都进不去

**Comment by xiaojieonly** [comment]
把梯子关了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
