### ISSUE TITLE
app内卡顿内容难以加载 

### ISSUE THREAD

**Issue by deepdark08** [xiaojieonly/Ehviewer_CN_SXJ#270]
经常打不开内容 图片也加载不出
![Screenshot_20220511_003454_com xjs ehviewer](https://user-images.githubusercontent.com/105307285/167678826-2345e029-64ea-487d-98c1-ff7a3d17f951.jpg)
![Screenshot_20220511_003448_com xjs ehviewer](https://user-images.githubusercontent.com/105307285/167678831-b442a8be-b3b2-48fe-bb2a-2118be63be94.jpg)

**Comment by Saciss** [comment]
＋1

**Comment by xiaojieonly** [comment]
网不好

**Comment by xiaojieonly** [comment]
app安装到手机内存，别装到sd卡

**Comment by Saciss** [comment]
应该不是网的问题吧，500m的联通宽带裸连都是看运气才能进，经常性超时
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] app内卡顿内容难以加载  (Issue #270)





 
网不好

**Comment by Saciss** [comment]
这个卡顿应该是指网卡吧
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] app内卡顿内容难以加载  (Issue #270)





 
app安装到手机内存，别装到sd卡

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
