### ISSUE TITLE
一直显示网络错误怎么办

### ISSUE THREAD

**Issue by scarber** [xiaojieonly/Ehviewer_CN_SXJ#277]
![Screenshot_20220524_170508](https://user-images.githubusercontent.com/106148631/169994612-95f0575b-2421-4a4a-ba27-cb44f4eece5c.jpg)
非亚洲地址登入，科学上网也进不去怎么办

**Comment by Jyooka** [comment]
我也是，但我关了域名前置之后就进去了

**Comment by scarber** [comment]
谢谢谢谢，已经解决了
