### ISSUE TITLE
怎么用cookie登录

### ISSUE THREAD

**Issue by chenguanm** [xiaojieonly/Ehviewer_CN_SXJ#278]
我已经在网上找了很多获取cookie的方法，但是就是不知道用什么特殊的cookie才能登录，而且不明白登陆界面那三串语言的意思，哪个可以帮我解答一下( ๑ŏ ﹏ ŏ๑ )

**Comment by nyds123** [comment]
你如果已经在里站注册过，就用你的账号登陆，然后再在EH里面找到你的身份cookie就可以了
