### ISSUE TITLE
[Feature Request] 能否添加一个隔壁 Eh 的一个自动签到功能

### ISSUE THREAD

**Issue by PianCat** [xiaojieonly/Ehviewer_CN_SXJ#279]
功能来源：
https://gitlab.com/NekoInverter/EhViewer
功能说明：
自动访问新闻页面以领取新的一天奖励
官方说明： https://ehwiki.org/wiki/Dawn_of_a_New_Day

额外功能请求：
主动提醒 HentaiVerse 遭遇怪物
（隔壁也是有的）
（暂未知晓实现方式）

**Comment by xiaojieonly** [comment]
再说，最近工作很忙

**Comment by PianCat** [comment]
> 再说，最近工作很忙

开发辛苦了，可以等，能做就行
稍微完善了一下 Feature Requests 的说明
