### ISSUE TITLE
表站直连正常，里站和收藏夹不可用

### ISSUE THREAD

**Issue by WarnError** [xiaojieonly/Ehviewer_CN_SXJ#28]
运行环境为SDK26

**Comment by WarnError** [comment]
非Cookies问题

**Comment by WarnError** [comment]
同样无法直连的还有收藏夹

**Comment by xiaojieonly** [comment]
> 同样无法直连的还有收藏夹

修好了，但是里站挂梯子才行

**Comment by WarnError** [comment]
> > 同样无法直连的还有收藏夹
> 
> 修好了，但是里站挂梯子才行

收藏夹依旧无法使用，Cookies登录后无法评分

**Comment by EastCitySouthPath** [comment]
> > 同样无法直连的还有收藏夹
> 
> 修好了，但是里站挂梯子才行

大佬，现在可以覆盖安装吗

**Comment by xiaojieonly** [comment]
> > > 同样无法直连的还有收藏夹
> > 
> > 
> > 修好了，但是里站挂梯子才行
> 
> 收藏夹依旧无法使用，Cookies登录后无法评分

为啥我表站用的都好好的，里站挂了梯子也用的好好的。。。。。。。

**Comment by WarnError** [comment]
> > > > 同样无法直连的还有收藏夹
> > > 
> > > 
> > > 修好了，但是里站挂梯子才行
> > 
> > 
> > 收藏夹依旧无法使用，Cookies登录后无法评分
> 
> 为啥我表站用的都好好的，里站挂了梯子也用的好好的。。。。。。。
但直连表站时账号的收藏和评分等功能也用不了。。
