### ISSUE TITLE
连不上去啊，挂了梯子，油管那些都能上，就这个上不去

### ISSUE THREAD

**Issue by 2023899320** [xiaojieonly/Ehviewer_CN_SXJ#280]

**Comment by YJ2CS** [comment]
关闭自定义host.txt和安全DNS，并且关闭域名前置，之后重新登录，选择网页登录

**Comment by fand-alt** [comment]
我也是这样，但我试了没有😭

**Comment by YJ2CS** [comment]
> 我也是这样，但我试了没有😭

不好意思，还需要关闭域名前置。。你看我编辑的消息

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
