### ISSUE TITLE
下载经常卡住

### ISSUE THREAD

**Issue by xiangluoming** [xiaojieonly/Ehviewer_CN_SXJ#285]
每下载几十张就会卡住速度掉到0，点击暂停再恢复后又能继续，但是点开看里面有几张是没下载下来的，是不是某一张卡住了就会把后面所有的都卡住？还有浏览的时候也是这样经常会有几张加载不出来，点击刷新也没用，有时候退出画廊页面重新进可能又好了，是不是没有超时重试？

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
应该是ip限流了，建议换个ip接着下

**Comment by xiaojieonly** [comment]
如果添加超时重试的话不安全，频繁重复请求接口会导致ip被封禁
