### ISSUE TITLE
求助，为什么无法使用，会出现一个安卓机器人的头然后落泪

### ISSUE THREAD

**Issue by 1710430785** [xiaojieonly/Ehviewer_CN_SXJ#288]
账号登录使用cookie登录，无论使用梯子或者裸连都不能使用app，搜索功能都有那个安卓机器人的头落泪，没有任何文字提示

**Comment by exseii** [comment]
> 账号登录使用cookie登录，无论使用梯子或者裸连都不能使用app，搜索功能都有那个安卓机器人的头落泪，没有任何文字提使用cookie登录上去还是一样呀 还是什么都没有 请教下到底怎么使用

**Comment by 1710430785** [comment]
> 

我不道啊

**Comment by 1710430785** [comment]
> > 账号登录使用cookie登录，无论使用梯子或者裸连都不能使用app，搜索功能都有那个安卓机器人的头落泪，没有任何文字提使用cookie登录上去还是一样呀 还是什么都没有 请教下到底怎么使用

我不道啊

**Comment by 1710430785** [comment]
> > 账号登录使用cookie登录，无论使用梯子或者裸连都不能使用app，搜索功能都有那个安卓机器人的头落泪，没有任何文字提使用cookie登录上去还是一样呀 还是什么都没有 请教下到底怎么使用

刚刚又试了一下，把梯子换成美国的节点就能用表站了，里站没有试

**Comment by xiaojieonly** [comment]
一般来说都是可以裸连的
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
