### ISSUE TITLE
[BUG反馈]无法评论与点赞

### ISSUE THREAD

**Issue by Leedw666** [xiaojieonly/Ehviewer_CN_SXJ#29]
评论无法点赞和踩，也无法发出评论
![Screenshot_2020-12-12-00-54-54-417_com xjs ehviewer](https://user-images.githubusercontent.com/29456613/101931922-06250000-3c15-11eb-9e1a-4a5b0a63bc00.jpg)

**Comment by Rerlens** [comment]
账号貌似没登录？ 看不了收藏，添加不了收藏，无法评论，退出登录重新登录就会闪退

**Comment by xiaojieonly** [comment]
> 账号貌似没登录？ 看不了收藏，添加不了收藏，无法评论，退出登录重新登录就会闪退

我不小心把没完善的代码一起打包了导致的。。。明天我重新打包下

**Comment by Leedw666** [comment]
> > 账号貌似没登录？ 看不了收藏，添加不了收藏，无法评论，退出登录重新登录就会闪退
> 
> 我不小心把没完善的代码一起打包了导致的。。。明天我重新打包下

谢谢兄弟了
