### ISSUE TITLE
我挂了梯子上其他软件都可以，就eh不行，一直显示这个。

### ISSUE THREAD

**Issue by fand-alt** [xiaojieonly/Ehviewer_CN_SXJ#292]
![Screenshot_20220624_171507](https://user-images.githubusercontent.com/72299341/175504567-0fde7daa-39e9-4ed1-b785-61daeb52eecc.jpg)
![Screenshot_20220624_171607](https://user-images.githubusercontent.com/72299341/175504739-824f431f-4b7d-4257-b1b3-6960eebf703b.jpg)

**Comment by zmz2333** [comment]
您好，请阅读以下文档
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md#%E6%89%80%E6%9C%89%E7%BD%91%E7%BB%9C%E9%97%AE%E9%A2%98%E8%A6%81%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%9C%89%E9%97%AE%E9%A2%98%E8%A6%81%E4%B9%88%E6%9C%AC%E8%BA%AB%E7%BD%91%E4%B8%8D%E8%A1%8C%E6%9C%AC%E4%BA%BA%E5%9D%87%E4%B8%8D%E5%86%8D%E4%B8%BB%E5%8A%A8%E5%9B%9E%E5%A4%8D%E6%89%93%E9%92%B1%E7%9A%84%E5%8F%A6%E8%AF%B4

**Comment by fand-alt** [comment]
这个我看完了，第一显示不出来的的是表站不是里站，第二如果归类为网络问题的话解决方案就分为两种，如果说设置问题的话，那些开关按钮可以按的排列组合我都试过了，那些需要填写（比如http代理）的也没改过同时不知道怎么改，要是说网络问题的话……那具体什么问题我也不懂，不断换梯换节点是我唯一的处理方法，但没用。所以我这个问题就没有其他办法了吗？😢

**Comment by fand-alt** [comment]
谢谢了，我重新下载了一次，然后换成裸连配置又可以了
但是不重新下载之前换成裸连配置后用梯裸连都不行我就很迷😂
