### ISSUE TITLE
闪退太哈人了

### ISSUE THREAD

**Issue by SongKing123** [xiaojieonly/Ehviewer_CN_SXJ#294]
平均三到五分钟闪退一次，这谁顶得住，大佬能救救我吗

**Comment by SongKing123** [comment]
用的是小米平板5，安卓11，使用最新版本的ehviewer

**Comment by xiaojieonly** [comment]
额，我没平板。。。复现不了

**Comment by xiaojieonly** [comment]
手机有这种情况吗？

**Comment by SongKing123** [comment]
> 手机有这种情况吗？

手机偶尔也会出现，不怎么使用手机，闪退场景出现在各种情况下，画廊，观看期间，排行榜，等等都出现过

**Comment by SongKing123** [comment]
> > 手机有这种情况吗？
> 
> 手机偶尔也会出现，不怎么使用手机，闪退场景出现在各种情况下，画廊，观看期间，排行榜，等等都出现过

刚刚手机试着下了一个，果然一会儿就闪退了😂

**Comment by xiaojieonly** [comment]
app什么版本

**Comment by SongKing123** [comment]
> app什么版本

现在更新19.11之后不闪退了，之前是05闪退来着，现在就是裸连基本上没有略缩图，只能梯子才有略缩图

**Comment by xizilin2016** [comment]
> app什么版本

另外，鸿蒙系统好像也有些不适配，闪退太猛了

**Comment by xiaojieonly** [comment]
> > app什么版本
> 
> 另外，鸿蒙系统好像也有些不适配，闪退太猛了

最新版也这样？

**Comment by xizilin2016** [comment]
> > > app什么版本
> > 
> > 另外，鸿蒙系统好像也有些不适配，闪退太猛了
> 
> 最新版也这样？

现在好一些了
