### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by BunnySakura** [xiaojieonly/Ehviewer_CN_SXJ#297]
1. FEhviewer提供了H@H下载时查看下载费用的显示功能，原版和此版ehviewer都没有这个显示。不过提供了下载功能，即压缩包下载。希望在压缩包下载界面显示下载的费用；

![image](https://user-images.githubusercontent.com/48341563/177534252-b6e36c2f-ddf9-4882-9842-f022e04ca15c.png)

2. 收藏时希望能够显示`favorite note`

![image](https://user-images.githubusercontent.com/48341563/177534487-04c2ce7a-3593-4179-85fa-7b9bd5fab3fb.png)

**Comment by xiaojieonly** [comment]
1

**Comment by BunnySakura** [comment]
谢谢！thank you！
