### ISSUE TITLE
希望可以增加蓝奏云的下载链接

### ISSUE THREAD

**Issue by lixiangwuxian** [xiaojieonly/Ehviewer_CN_SXJ#3]
百度网盘在我这里下载速度一言难尽，而且apk格式还必须安装百度云下载，所以请求加入蓝奏云的下载链接。实在不行，也可以在代码库里建立一个文件夹存放编译好的apk文件。感谢。

**Comment by shuaixiaojie** [comment]
好的，github上我也是有release的，你可以试试github上下载，蓝奏云我去了解下，能加入一定加入

**Comment by shuaixiaojie** [comment]
百度云太慢了可以试试github上直接下载
 https://github.com/shuaixiaojie/Ehviewer_CN_SXJ/releases
 
 
 后面我会试着找一个速度快一些的网盘供大家下载使用O(∩_∩)O

**Comment by lixiangwuxian** [comment]
感谢，我第一次来看的时候是上周，当时还没加release来着，我以为就没加release。蓝奏云主要是存这种不超过100M的小文件很方便，下载也很快（基本取决于网速），还不需要客户端。

**Comment by shuaixiaojie** [comment]
好的，我尽快去弄

**Comment by shuaixiaojie** [comment]
蓝奏云等我下次更新一并发出来，新功能快写好了( •̀ .̫ •́ )✧

> 感谢，我第一次来看的时候是上周，当时还没加发行来着，我以为就没加发行。蓝奏云主要是存这种不超过100M的小文件很方便，下载也很快（基本而言网速），还不需要客户端。

**Comment by lixiangwuxian** [comment]
大佬NB!( •̀ .̫ •́ )✧
