### ISSUE TITLE
1.7.6.11版本ex依然网络错误

### ISSUE THREAD

**Issue by PuddingVitamin** [xiaojieonly/Ehviewer_CN_SXJ#30]
（前几天是可以看的）画廊站点切换为ex，软件内部高级设置总代理选项是系统代理，关掉了内置的hosts并且挂了SSR的香港节点，但是依然显示“网络错误”。是哪一部不正确呢？电信WIFI和移动数据都试过。电信WIFI是网络错误，移动数据报错为未知主机。可能最近只能看eh了。

**Comment by PuddingVitamin** [comment]
顺便同情一波xiaojie，接手没多久就遭遇GFW全面毁灭。

**Comment by xiaojieonly** [comment]
> （前几天是可以看的）画廊站点切换为ex，软件内部高级设置总代理选项是系统代理，关掉了内置的hosts并且挂了SSR的香港节点，但是依然显示“网络错误”。是哪一部不正确呢？电信WIFI和移动数据都试过。电信WIFI是网络错误，移动数据报错为未知主机。可能最近只能看eh了。

额，我挂梯子能正常进里站，可能是你梯子的服务器ip被里站封了。。。。

**Comment by Leedw666** [comment]
所以说为啥exh也要gfw，

> 顺便同情一波xiaojie，接手没多久就遭遇GFW全面毁灭。

所以为啥gfw要搞掉一个小众r18网站呢
