### ISSUE TITLE
能不能出个纯净版。现版本闪退，还常年无法连接。大概只有2点之后才能上。

### ISSUE THREAD

**Issue by JonesRico** [xiaojieonly/Ehviewer_CN_SXJ#300]

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by WalkerGloom** [comment]
去安装EhViewer原作者开发的版本，是白色图标的EhViewer

**Comment by WalkerGloom** [comment]
> _No description provided._

去安装EhViewer原作者开发的版本，是白色图标的EhViewer

**Comment by urturegenius** [comment]
半个月没用原来能进里站的为啥进不去了呢，还会被踢吗

**Comment by WalkerGloom** [comment]
> 半个月没用原来能进里站的为啥进不去了呢，还会被踢吗

并不会被踢，去用原作者开发的白色图标版本
