### ISSUE TITLE
最新版本图片加载问题

### ISSUE THREAD

**Issue by Kkzz2073** [xiaojieonly/Ehviewer_CN_SXJ#303]
不使用梯子可以看到搜索界面，点进浏览本子之后图片一直在转加载不出开。表里站都是这样。

开了梯子之后搜索界面显示落泪机器人。救命。

![Screenshot_20220717-233845_EhViewer](https://user-images.githubusercontent.com/109474374/179405818-6a49a585-9053-4081-b7c3-a7a0e6c55bd5.jpg)

**Comment by Kkzz2073** [comment]
开了梯子之后都搜索界面显示落泪机器人。

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
