### ISSUE TITLE
能不能加一个下载目录搜索和排序功能？

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#304]
我在app上已经保存了快7000本本子了，
![Screenshot_20220721-021401](https://user-images.githubusercontent.com/30853947/180054280-b61857d3-d753-4204-a89a-f0747e686ef5.png)

数量很多，而且每天都还会加几本进去，想要快速找到某一个画家或者某一个类型的本子的时候只能用主页搜索后再跳转。
比较麻烦，能不能加一个直接在下载目录里面搜索和排序以及标签搜索的功能？
谢谢大佬

**Comment by xiaojieonly** [comment]
我尽力

**Comment by tongsang** [comment]
谢谢大佬

**Comment by xiaojieonly** [comment]
已经有按名称查询的功能了，多标签查询和排序还在开发
