### ISSUE TITLE
能否在应用内提供本地的标签订阅？官方提供的标签订阅有100个数量上限，不够用。

### ISSUE THREAD

**Issue by mo-han** [xiaojieonly/Ehviewer_CN_SXJ#305]
现有的“书签栏”已经能收藏各种搜索请求（不仅仅是标签），但是，如果它像订阅功能那样把所有收藏结果“聚合”在一起显示的话，那多是一件美事~

**Comment by xiaojieonly** [comment]
暂时没法突破官方限制

**Comment by mo-han** [comment]
> 暂时没法突破官方限制

所以就想问问，能不能在本地实现一个订阅功能？
现在不是有现成的书签栏功能吗，里面是收藏的搜索项。如果能再进一步，把这些搜索项的搜索结果聚合到一个页面上，岂不美哉~
