### ISSUE TITLE
应用头像显示问题

### ISSUE THREAD

**Issue by HRxiaohu** [xiaojieonly/Ehviewer_CN_SXJ#306]
应用内头像显示错误 附图
![Screenshot_20220722_163756_com xjs ehviewer](https://user-images.githubusercontent.com/63327671/180400056-654ccdd2-f924-4837-938b-2f46dd4fe51a.jpg)

**Comment by xiaojieonly** [comment]
额，图片太小了，你有试过大一些的图片吗？

**Comment by HRxiaohu** [comment]
@xiaojieonly 还没有尝试，这个头像是EHviewer自动从e站同步的，并且在Hippo和Neko的版本中显示正常。

**Comment by xiaojieonly** [comment]
1
