### ISSUE TITLE
已登录之后退出登录，再点开应用会直接跳过登陆

### ISSUE THREAD

**Issue by yanguyue** [xiaojieonly/Ehviewer_CN_SXJ#307]
已经登录了情况下退出登录，然后重新打开应用，会闪过登录界面然后直接跳过登录直接进去

**Comment by xiaojieonly** [comment]
不应该啊，你应该是没退出吧？

**Comment by suxas** [comment]
> 已经登录了情况下退出登录，然后重新打开应用，会闪过登录界面然后直接跳过登录直接进去

重新安装即可，我刚才在1.7.3那个版本也遇到了这个问题，然后我网上一搜才发现大佬已经接手维护这么久了，谢谢大佬！
把握住每一次登录的机会吧！

**Comment by xiaojieonly** [comment]
1.7.3。。。。。。这也太久远了。。。
