### ISSUE TITLE
请问大佬画廊缩略图能看但是大图读取失败怎么办，不是那个直连的问题我挂着梯子的

### ISSUE THREAD

**Issue by kaninayuta710** [xiaojieonly/Ehviewer_CN_SXJ#312]

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by kaninayuta710** [comment]
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
不是DoH的问题，应该是e站有什么新机制或者账号有什么问题？，关掉下载原图就可以了，近期的画廊开着下载原图也能没事，几个月之前的就不行，最近才出现的问题，手里三个ehviewer都是这样

**Comment by xiaojieonly** [comment]
不是很清楚，但是下载原图有风险

**Comment by kaninayuta710** [comment]
> 不是很清楚，但是下载原图有风险

确实是e站的问题，现在他在高峰时段不能下载30天以前的画廊原图
