### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by liachihuo** [xiaojieonly/Ehviewer_CN_SXJ#319]
不用梯子进入软件一直在转圈，什么也加载不出来，我打开梯子再进又直接提示我网络错误，我梯子没有问题，大佬怎么办啊
![Uploading Screenshot_20220801_091150.jpg…]()

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
