### ISSUE TITLE
账号有铜星，但在APP内表E无法搜索到里E内容

### ISSUE THREAD

**Issue by cnGeBu** [xiaojieonly/Ehviewer_CN_SXJ#32]
电脑网页版正常，在表E搜索 lolicon 有结果

但APP内画廊站点选择e-hentai搜索 lolicon 却无结果，真的神秘。 cookie登录和网页登录账号都试了下，不行。

**Comment by cnGeBu** [comment]
大概发现问题出在哪了

我用NekoInverter版的白色EH登录后可以进行评分一类的，但是这边不行。

这边显示登录上了，却无法进行登陆后的操作，和未登录状态一样，铜星这种跟着账号走的自然没有效果。

希望作者大佬修复！

**Comment by xiaojieonly** [comment]
> 大概发现问题出在哪了
> 
> 我用NekoInverter版的白色EH登录后可以进行评分一类的，但是这边不行。
> 
> 这边显示登录上了，却无法进行登陆后的操作，和未登录状态一样，铜星这种跟着账号走的自然没有效果。
> 
> 希望作者大佬修复！

嗯

**Comment by xiaojieonly** [comment]
> 电脑网页版正常，在表E搜索 lolicon 有结果
> 
> 但APP内画廊站点选择e-hentai搜索 lolicon 却无结果，真的神秘。 cookie登录和网页登录账号都试了下，不行。

最新版应该可以了。旧版为了适配低版本安卓系统导致登陆系统异常，现在最新版本登陆功能能用了，应当就好了，很抱歉这么久才恢复，最两周公司工作有点多，每天都加班到很晚，实在是有些应付不过来了。o(￣┰￣*)ゞ

**Comment by cnGeBu** [comment]
> > 电脑网页版正常，在表E搜索lolicon有结果
> > 但APP内画廊站点选择e-hentai搜索lolicon却无结果，真的神秘。cookie登录和网页登录账号都试了下，不行。
> 
> 最新版本应该可以了。旧版本为了适应低版本安卓系统导致登陆系统异常，现在最新版本登陆功能能用了，已经就好了，很抱歉这么久才恢复，最两周公司工作有点多，每天都加班到很晚，实在是有些应付不过来了。o（￣┰￣ *）ゞ

感谢大佬一直以来的更新！对大佬您心怀最高的敬意！
