### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by luoyesuki** [xiaojieonly/Ehviewer_CN_SXJ#321]
建议优化一下搜索功能，在搜索栏中选择tag时应该是在现有输入内容后加入tag
比如点击l chinese后从"a:muk"变为"a:muk l:chinese"。这样子在搜索多tag类型及中文译本时非常方便
但现有搜索是从a:muk变为l:chinese，导致除第一个tag以外，其余的都要手动输入，十分不便

**Comment by xiaojieonly** [comment]
最新版已修复，空格要你自行添加
