### ISSUE TITLE
v1.9.1.3 _ java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by xxxloli123** [xiaojieonly/Ehviewer_CN_SXJ#327]
--------- beginning of crash
08-11 22:13:31.314 20064 25405 E AndroidRuntime: FATAL EXCEPTION: SpiderWorker-2
08-11 22:13:31.314 20064 25405 E AndroidRuntime: Process: com.xjs.ehviewer, PID: 20064
08-11 22:13:31.314 20064 25405 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at com.hippo.util.ExceptionUtils.getReadableString(ExceptionUtils.java:65)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.downloadImage(SpiderQueen.java:1184)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.runInternal(SpiderQueen.java:1555)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at com.hippo.ehviewer.spider.SpiderQueen$SpiderWorker.run(SpiderQueen.java:1565)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
08-11 22:13:31.314 20064 25405 E AndroidRuntime: 	at com.hippo.yorozuya.thread.PriorityThread.run(PriorityThread.java:38)
08-11 22:13:33.294  8263 32258 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
--------- beginning of main[]()

**Comment by xxxloli123** [comment]
没有登录账号。

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
1.9.1.4已修复，即将发版
