### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by RX93CN** [xiaojieonly/Ehviewer_CN_SXJ#333]
白天正常，到了晚上6点后就无法正常连接了，显示连接超时或者长时间刷新才有图像，白色版EhViewer也无法稳定连接，是网络问题还是内置的插件失效了？

**Comment by liuge210** [comment]
+1

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
