### ISSUE TITLE
寻求比较便捷e站捐赠方法(可有偿) 

### ISSUE THREAD

**Issue by HoriYuko** [xiaojieonly/Ehviewer_CN_SXJ#336]
这是目前可以找到的e站捐赠方案:https://github.com/kk9448/ehDonate

请问，除此之外还没有有什么比较不错(便捷/无需身份验证）的代替方案吗？[可有偿] 。

ps：本人对于e站的需求非常的有限(赞助20美金成为铜星即可)。

**Comment by xiaojieonly** [comment]
我不提供e站捐赠方案

**Comment by HeiZiHolo** [comment]
> 这是目前可以找到的e站捐赠方案：https://github.com/kk9448/ehDonate
> 
> 请问，除此之外还没有有什么比较不错(便捷/无需身份验证）的代替方案吗？[可有偿] 。
> 
> ps：本人对于e站的需求非常的有限（赞助20美金成为铜星即可）。
海鲜市场有代捐赠服务
