### ISSUE TITLE
咨询一下大佬，为什么我用新的梯子clash之后打不开Ehviewer

### ISSUE THREAD

**Issue by Murlocalex** [xiaojieonly/Ehviewer_CN_SXJ#337]
以前我用某蛙云的v2ray，后来那个梯子机场跑路后，我用了新的clash以后，Eh一直显示未知主机，之后看了前面的帖子，把安全DNS关掉后显示网络错误，推特yutube都可以打开，只有Eh无法打开，大佬可以帮忙解决一下吗，谢谢大佬
![Screenshot_20220821_012749_com xjs ehviewer](https://user-images.githubusercontent.com/54952714/185759341-95fdef35-abd0-4ae5-8e3d-95b06bd16ce7.jpg)
![Screenshot_20220821_012755_com github kr328 clash foss](https://user-images.githubusercontent.com/54952714/185759346-87deae11-2786-48bd-a856-5c470613bc2d.jpg)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by Pen2dragon** [comment]
我也一样，eh显示未知主机，进不去，其他外网访问正常。用v2rayng能正常访问eh

**Comment by Pen2dragon** [comment]
哥们，我知道了。
eh 关闭域名前置和安全dns，退出登录，使用账户密码重登，实测梯子正常可以看
