### ISSUE TITLE
收藏没有本地收藏

### ISSUE THREAD

**Issue by zphiroude1234** [xiaojieonly/Ehviewer_CN_SXJ#34]
能正常本地收藏就是进去收藏只有云端收藏，没有本地收藏。

**Comment by xiaojieonly** [comment]
> 能正常本地收藏就是进去收藏只有云端收藏，没有本地收藏。

点进去屏幕从右往左划，你就可以选择本地收藏了

**Comment by xiaojieonly** [comment]
> 能正常本地收藏就是进去收藏只有云端收藏，没有本地收藏。

抱歉这么晚才回复

**Comment by xiaojieonly** [comment]
> > 能正常本地收藏就是进去收藏只有云端收藏，没有本地收藏。
> 
> 点进去屏幕从右往左划，你就可以选择本地收藏了

就像导出书签一样

**Comment by zphiroude1234** [comment]
> > > 能正常本地收藏就是进去收藏只有云端收藏，没有本地收藏。
> > 
> > 
> > 点进去屏幕从右往左划，你就可以选择本地收藏了
> 
> 就像导出书签一样

可以了，谢谢大佬
