### ISSUE TITLE
问题求助 end of input at character 0 of 

### ISSUE THREAD

**Issue by LoserPlus666** [xiaojieonly/Ehviewer_CN_SXJ#342]
![Screenshot_20220828_081934_com xjs ehviewer](https://user-images.githubusercontent.com/79098288/187052457-ebbf5ad3-601c-47c9-aa25-c8224ae10914.jpg)
这是咋回事

**Comment by kanadehusband** [comment]
巧了我也是突然昨天晚上出现这个问题

**Comment by LoserPlus666** [comment]
> 巧了我也是突然昨天晚上出现这个问题

我只有搜Chinese的时候这样，其他的都没事，逼我把其他语言都屏蔽了

**Comment by bilibili780** [comment]
直接搜Chinese能出来一页，再往下翻就显示End of input at character 0 of了，Chinese不打全不是只能显示一页就是直接End of input at character 0 of了

**Comment by fyl666kl** [comment]
一样的情况，昨晚还没有这种问题

**Comment by a546109781** [comment]
一样 我还以为就我这样

**Comment by uuuiiiiooo** [comment]
即使排除其他语言下，下滑多几页也会出现End of input at character 0 of

**Comment by KenCheung0115** [comment]
一样的情况，搜language:chinese下滑就会出现End of input at character 0 of

**Comment by xiaojieonly** [comment]
我看下

**Comment by xiaojieonly** [comment]
我复现不了。。。。。

**Comment by a546109781** [comment]
> 我复现不了。。。。。

不知道是不是e站的问题，这两天已经好了
