### ISSUE TITLE
how can i share image to traslation app?

### ISSUE THREAD

**Issue by galerious** [xiaojieonly/Ehviewer_CN_SXJ#346]
is there a additional setting for that?
or this function don't be supported in this app?

**Comment by xiaojieonly** [comment]
Then browse the interface, long press the picture, there will be a share button

**Comment by galerious** [comment]
> Then browse the interface, long press the picture, there will be a share button

here is two version of EhViewer.

this is nekoinverter version

![KakaoTalk_20220902_180327126_08](https://user-images.githubusercontent.com/112664403/188105171-d1c36b15-fe7f-418d-901c-c39cb4554597.jpg)
![KakaoTalk_20220902_180327126_07](https://user-images.githubusercontent.com/112664403/188105220-010694f9-575a-4176-871c-e913ee82cba2.jpg)
![KakaoTalk_20220902_180327126_06](https://user-images.githubusercontent.com/112664403/188105255-f85c1c31-16ff-41d2-8d21-2c436818436f.jpg)
![KakaoTalk_20220902_180327126_05](https://user-images.githubusercontent.com/112664403/188105280-11ef2481-e79a-4d20-9bcc-2c9f0c2cd1a5.jpg)
![KakaoTalk_20220902_181039649](https://user-images.githubusercontent.com/112664403/188106305-c8c5ea2c-5259-468b-8af4-89c4b48ceb5e.jpg)

this version can share picture to translation app or message app or image search app

and this is your version.

![KakaoTalk_20220902_180327126_04](https://user-images.githubusercontent.com/112664403/188105612-ae932948-e3fb-47b3-8dae-febd6f2121d9.jpg)
![KakaoTalk_20220902_180327126_03](https://user-images.githubusercontent.com/112664403/188105646-c6e3fbc3-c9c2-456e-9d7d-f22b4b30cec9.jpg)
![KakaoTalk_20220902_180327126_01](https://user-images.githubusercontent.com/112664403/188105663-a64f75f0-6871-41a4-9c49-7bf02dd05d92.jpg)
![KakaoTalk_20220902_180327126](https://user-images.githubusercontent.com/112664403/188105687-5b5453bd-8b60-488c-b3ff-bbf02e97bee6.jpg)
![KakaoTalk_20220902_180927619](https://user-images.githubusercontent.com/112664403/188106418-13cd73b7-7601-4579-8f50-7f37df1596c5.jpg)

i don't know why it can't...
can you find reason?
