### ISSUE TITLE
无法使用自定义hosts

### ISSUE THREAD

**Issue by Mo-Yuxi** [xiaojieonly/Ehviewer_CN_SXJ#348]
当自己在自定义hosts输入域名和IP后尝试加载，出现报错“java.net.Inet4Addresscannot be cast tojava.util.List”，软件内无法浏览任何内容，删除添加的自定义hosts条目后恢复正常

已打开的选项：两个内置hosts，安全dns和域名前置

**Comment by Mo-Yuxi** [comment]
当前版本1.9.1.4

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
我自己试了下是正常的
![Screenshot_2022-09-18-11-25-52-569_com xjs ehview](https://user-images.githubusercontent.com/49278135/190884365-6b075a81-f0cf-438a-ba0d-2e63be702516.jpg)
1.9.1.4

**Comment by xiaojieonly** [comment]
如果还是有问题，请重新打开此问题
