### ISSUE TITLE
这个是为什么

### ISSUE THREAD

**Issue by 18229910127** [xiaojieonly/Ehviewer_CN_SXJ#349]
![Screenshot_2022-09-07-13-10-30-294_com xjs ehviewer](https://user-images.githubusercontent.com/113004405/188793538-aa5fb20c-a325-483e-ad9c-aa1c8aa6e586.jpg)

**Comment by 18229910127** [comment]
求求了怎么也登不上

**Comment by xiaojieonly** [comment]
[常见问题汇总](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md)
