### ISSUE TITLE
下载列表搜索出来的结果会有一些变成空白

### ISSUE THREAD

**Issue by kirito5210** [xiaojieonly/Ehviewer_CN_SXJ#359]
首先万分感谢作者大大加入了下载列表搜索功能，真的特别需要。用了以后发现了两个问题：
一是搜出来的结果列表中有一些漫画会显示一片空白，但是点一下空白的地方能进到漫画里去
二是搜索出来的结果不能移动到其他标签下，这个功能是还没有添加吗，想要用搜索后再移动来给本子分类

**Comment by kirito5210** [comment]
![Screenshot_2022-09-25-14-16-34-308_com xjs ehview](https://user-images.githubusercontent.com/61077462/192131165-250395f1-7fc4-429f-a4fb-7be1b1dd6779.jpg)
具体情况如图所示

**Comment by kirito5210** [comment]
又试了一下移动本子功能是正常的，不过搜索结果界面问题确实存在

**Comment by xiaojieonly** [comment]
安卓几？

**Comment by xiaojieonly** [comment]
已修复
