### ISSUE TITLE
求e站hosts文件

### ISSUE THREAD

**Issue by Nightmare-Serene** [xiaojieonly/Ehviewer_CN_SXJ#36]
网页版e站突然无法上了，要更新最新的e站hosts，求文件

**Comment by xiaojieonly** [comment]
> 网页版e站突然无法上了，要更新最新的e站hosts，求文件

    Map<String, List<InetAddress>> map = new HashMap<>();
    put(map, "e-hentai.org", "104.20.26.25+104.20.27.25");
//    put(map,"exhentai.org", "178.175.132.22+178.175.128.252+178.175.128.254+178.175.129.252+178.175.129.254+178.175.132.20");
    put(map, "repo.e-hentai.org", "94.100.28.57");
    put(map, "forums.e-hentai.org", "94.100.18.243");
    put(map, "ehgt.org", "37.48.89.44+178.162.139.24+178.162.140.212+81.171.10.48");
//    put(map, "ehgt.org", "178.162.139.24");
    put(map, "ul.ehgt.org", "94.100.24.82+94.100.24.72");
    builtInHosts = map;

**Comment by xiaojieonly** [comment]
> 网页版e站突然无法上了，要更新最新的e站hosts，求文件

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/app/src/main/java/com/hippo/ehviewer/client/EhDns.java
