### ISSUE TITLE
主页界面一片空白

### ISSUE THREAD

**Issue by 2913869557** [xiaojieonly/Ehviewer_CN_SXJ#360]
![Uploading Screenshot_2022-09-25-14-34-19-0460591821.png…]()

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/192134596-42b482a2-c124-4c4f-a7f1-fe8af093e667.png)
看不见你发的啥

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by 2913869557** [comment]
@xiaojieonly 没问题了，刚创的新号，没有获得里站的访问权限
