### ISSUE TITLE
搜索框x按键失效

### ISSUE THREAD

**Issue by JohnnyJoestar12138** [xiaojieonly/Ehviewer_CN_SXJ#364]
![Screenshot_20220925_185757](https://user-images.githubusercontent.com/114338898/192140115-5093f6da-5cd5-46df-8677-882cdefdc763.jpg)
更新到1.9.2.2版本后搜索框右上角清空搜索框按键失效

**Comment by xiaojieonly** [comment]
1

**Comment by UNSCs117** [comment]
确实，MiPad 5和荣耀note10端全部出这个问题，而且是版本更新后出现的小bug。。。

**Comment by xiaojieonly** [comment]
最新版已修复
