### ISSUE TITLE
搜索栏消除按钮( X ) 无法正常使用

### ISSUE THREAD

**Issue by HoriYuko** [xiaojieonly/Ehviewer_CN_SXJ#365]
最新版应用的搜索栏消除按钮( X ) 无法正常使用, 无法一次性消除输入字符。

![Screenshot_20220925_220123_com.xjs.ehviewer.jpg](https://user-images.githubusercontent.com/98299926/192144900-0b5775f5-345d-4aeb-a7d6-66f82cb61550.jpg)

**Comment by xiaojieonly** [comment]
最新版已修复
