### ISSUE TITLE
配置文件导出后无法导入其他版本Ehviewer

### ISSUE THREAD

**Issue by ayachinene0721** [xiaojieonly/Ehviewer_CN_SXJ#366]
虽然在[这个反馈](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/168) 里面已经了解到了导出.db文件后无法导入其他版本的eh，但是没有看到解决办法，还请大佬指点一下

**Comment by xiaojieonly** [comment]
我开发新功能用，更新了.db数据库版本，其他eh的.db文件版本比我的第一个版本，自然用不了，如果喜欢别的eh可以先从养成只用自己喜欢的eh开始。我适配了别人就适配不了我自己望周知
