### ISSUE TITLE
本子详情页封面显示问题

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#37]
如图，向下滑动封面却停在原位置
![Screenshot_2020-12-15-08-53-35-854_com xjs ehviewer](https://user-images.githubusercontent.com/48684035/102153946-4c978a80-3eb3-11eb-94fc-fe0c9b3c2c21.jpg)

**Comment by xiaojieonly** [comment]
> 如图，向下滑动封面却停在原位置
> ![Screenshot_2020-12-15-08-53-35-854_com xjs ehviewer](https://user-images.githubusercontent.com/48684035/102153946-4c978a80-3eb3-11eb-94fc-fe0c9b3c2c21.jpg)

安卓几？

**Comment by Steve-337** [comment]
> > 如图，向下滑动封面却停在原位置
> > ![Screenshot_2020-12-15-08-53-35-854_com xjs ehviewer](https://user-images.githubusercontent.com/48684035/102153946-4c978a80-3eb3-11eb-94fc-fe0c9b3c2c21.jpg)
> 
> 安卓几？

安卓11，Redmi k30pro MIUI12.2.1稳定版

**Comment by 974260581** [comment]
安卓10也是

**Comment by xiaojieonly** [comment]
好的，有时间我就立刻修，这几天加班比较多，可能会稍微晚一点才能修好，希望能理解

**Comment by Steve-337** [comment]
> 好的，有时间我就立刻修，这几天加班比较多，可能会稍微晚一点才能修好，希望能理解

这是小问题，不影响阅读
还是要以自己为主
多注意身体

**Comment by xiaojieonly** [comment]
> > 好的，有时间我就立刻修，这几天加班比较多，可能会稍微晚一点才能修好，希望能理解
> 
> 这是小问题，不影响阅读
> 还是要以自己为主
> 多注意身体

多谢理解
