### ISSUE TITLE
安卓 12 上通过 url 打开 app 的问题

### ISSUE THREAD

**Issue by xiaooloong** [xiaojieonly/Ehviewer_CN_SXJ#370]
在安卓 12 上打开 EH 链接无法跳转至应用内。

[另一个 fork 版](https://gitlab.com/NekoInverter/EhViewe)的应用在高级设置内可以调出系统的设置页面将 4 个支持的域名添加至系统信任后即可通过链接打开 app。
 
粗略搜了一下是有这些改动：
```
./app/src/main/java/com/hippo/ehviewer/ui/fragment/AdvancedFragment.java:    private static final String KEY_OPEN_BY_DEFAULT = "open_by_default";
./app/src/main/res/values/strings.xml:    <string name="open_by_default">Open by default</string>
./app/src/main/res/values-zh-rCN/strings.xml:    <string name="open_by_default">默认打开</string>
./app/src/main/res/xml/advanced_settings.xml:        android:key="open_by_default"
./app/src/main/res/xml/advanced_settings.xml:        android:title="@string/open_by_default"
```

请问安卓 12 有什么其他方式可以调出系统对应用的这个“打开支持的链接”设置界面么？
或者咱们也可以跟进一下这个设置选项？

**Comment by xiaooloong** [comment]
仔细看了下应该是 [这次提交](https://gitlab.com/NekoInverter/EhViewer/-/commit/c40ba85e50efd2d2d142e31a4dc8a1df11d1bb13) 和 [这次提交](https://gitlab.com/NekoInverter/EhViewer/-/commit/7a5eeffe0bb4287b4b2369630950632703ab0756) 新增的功能

**Comment by xiaojieonly** [comment]
1

**Comment by AkazaRenn** [comment]
可以直接通過設置進入![Screenshot_20221023-081732.png](https://user-images.githubusercontent.com/8340896/197391592-dade32ff-1000-4a85-9c20-b6d8bd7eaa44.png)

**Comment by EYW-015** [comment]
> 可以直接通過設置進入![Screenshot_20221023-081732.png](https://user-images.githubusercontent.com/8340896/197391592-dade32ff-1000-4a85-9c20-b6d8bd7eaa44.png)

小米手机的MIUI没有此设置项，国行系统与欧洲系统均不可见，”默认应用>打开链接“中的设置，实测无效，adb调试报错: non-debuggable app

**Comment by EYW-015** [comment]
> > 可以直接通過設置進入![Screenshot_20221023-081732.png](https://user-images.githubusercontent.com/8340896/197391592-dade32ff-1000-4a85-9c20-b6d8bd7eaa44.png)
> 
> 小米手机的MIUI没有此设置项，国行系统与欧洲系统均不可见，”默认应用>打开链接“中的设置，实测无效，adb调试报错: non-debuggable app

解决方案：谷歌市场下载"Miui Hidden Settings Activity"，在设置中搜索"Manage Application"，找到需要设置的应用，在"默认打开"中添加链接即可
