### ISSUE TITLE
新bug反馈

### ISSUE THREAD

**Issue by Leedw666** [xiaojieonly/Ehviewer_CN_SXJ#38]
滑动时封面图会卡在界面上，而且ex还是不能直连，甚至挂着梯子连接ex也会显示奇怪的错误+哭泣的安卓机器人
![Screenshot_2020-12-15-20-43-35-358_com xjs ehviewer](https://user-images.githubusercontent.com/29456613/102216673-77ff9100-3f16-11eb-92bf-d5f9805201aa.jpg)
![Screenshot_2020-12-15-20-43-45-279_com xjs ehviewer](https://user-images.githubusercontent.com/29456613/102216691-7d5cdb80-3f16-11eb-85bd-d80cbe4c2c92.jpg)

**Comment by xiaojieonly** [comment]
> 滑动时封面图会卡在界面上，而且ex还是不能直连，甚至挂着梯子连接ex也会显示奇怪的错误+哭泣的安卓机器人
> ![Screenshot_2020-12-15-20-43-35-358_com xjs ehviewer](https://user-images.githubusercontent.com/29456613/102216673-77ff9100-3f16-11eb-92bf-d5f9805201aa.jpg)
> ![Screenshot_2020-12-15-20-43-45-279_com xjs ehviewer](https://user-images.githubusercontent.com/29456613/102216691-7d5cdb80-3f16-11eb-85bd-d80cbe4c2c92.jpg)

安卓几？

**Comment by Leedw666** [comment]
安卓10,miui12

**Comment by tgzephrys** [comment]
解决了吗
