### ISSUE TITLE
〖功能请求〗将本地收藏转为云端收藏

### ISSUE THREAD

**Issue by Fhokud** [xiaojieonly/Ehviewer_CN_SXJ#380]
- 将本地收藏添加到一个指定的云端收藏夹
- 限制转换速度，避免大量本地收藏转换时出现被封的情况

这个功能可以帮助我们方便的迁移数据

**Comment by rilyuuj** [comment]
借楼问一下导出功能是不是可以兼容旧版apk(H大最后版本)收藏导入新版(此版本)并与新版本地收藏合并。现在旧版本地还有400多个收藏，不敢导出，害怕之后会覆盖新的本地收藏。
