### ISSUE TITLE
请问因为使用快速搜索从而导致出现一小时访问限制的原因是什麼呢？

### ISSUE THREAD

**Issue by HoriYuko** [xiaojieonly/Ehviewer_CN_SXJ#382]
动态公网ip 在使用快速搜索栏搜索画集(查看是否有新的画集种子) 一段时间后，应用会出现访问限制的警告。

详细情况：在使用快速搜索栏搜索画集(查看是否有新的画集种子) 一段时间后，应用会出现访问限制的警告。

但是在更改路由器[更改mac地址或重启路由器后(动态公网ip)] ，一小时访问限制便会解除 (ip地址未发生变化)。

**Comment by xiaojieonly** [comment]
e站不允许动态ip
