### ISSUE TITLE
EhViewer不再能正常访问里站(exhentai)

### ISSUE THREAD

**Issue by Noromon** [xiaojieonly/Ehviewer_CN_SXJ#383]
熊猫里站(ExHentai)修改了页面与搜索逻辑，现在:
1. 不再能跳页，ehviewer永远只能获取搜索第1页的信息
2. 不再能获取画廊内的缩略图

**Comment by chiaki-ops** [comment]
第一个问题似乎只有里站存在，表站是正常的

**Comment by flashyou1995** [comment]
请问现在eh无法刷页数该怎么办，等后续更新吗

**Comment by Noromon** [comment]
> 请问现在eh无法刷页数该怎么办，等后续更新吗

是的，只能等更新
熊猫将分页逻辑从"page=\<页数\>"改成了"next=\<gid\>"
ehviewer并没有给用户自己写解析器的途径，所以只能等开发者更新

或者改用表站e-hentai

**Comment by kinor038591** [comment]
ex網站更改了搜尋頁面的規則 不再以頁數(page=?)去顯示結果
改成用next跟prev配合本子編號 給出前後的搜尋結果
?next=2366547 本子編號2366547後(預設)25個搜尋結果
?prev=2366546 本子編號2366546前(預設)25個搜尋結果

e-h網站有類似的設定(from) 但還是有帶頁數 所以可以正常顯示
?page=3&from=2366147

**Comment by xiaojieonly** [comment]
好了，请看最新更新日志，E站页面跳转政策更新了
