### ISSUE TITLE
【功能建议】关于ex搜索功能改动，不知可否做页码本地缓存？

### ISSUE THREAD

**Issue by yoyokirby** [xiaojieonly/Ehviewer_CN_SXJ#385]
首先感谢作者长期更新，想对新的搜索功能造成的无页码问题提出一个不完善的想法。

我想应该很多人是会长期搜索固定的词条组合吧(这也是搜索词条收藏存在的意义)，可能很多人的搜索结果并不会拉到非常长的页数，可能就几十页。那么能否通过用户手动翻页(或者自动翻页，但这样做可能会对服务器造成过多请求，可能自动翻5页或者10页这样？)，然后将搜索结果保存在本地，以做到提供页码？然后可能新搜索结果进来的时候可以合并更新本地缓存？对收藏夹也可以使用这种方式。

实际上我还没有想明白这个没有页码的改动是不是完全不可理喻，但从我个人使用习惯来说，我可能会隔段时间对某个固定组合进行搜索，在大约几十页或一百页的内容中随机翻到中间的某页再进行浏览，所以这种翻页的需求应该是较为合理的存在吧。

我明白开发一个新的功能并不容易，仅仅是提出一个不完善的想法。再次非常谢谢作者长期以来的更新。

**Comment by akinokoika** [comment]
你这相当于维护一个持续更新的本地数据库，还涉及到合并冲突等问题，程序上需要的改动还挺多的
目前来说，个人认为最简单的复现页码功能就是每次搜索时维护一个本地变量，初值为1表示从第一页起计数，每NEXT一次+1，需要翻到第X页时程序自动进行NEXT操作并更新变量即可，当然考虑到服务器请求限制，X越大时需要的时间越长

**Comment by asuka-mio** [comment]
> 你这相当于维护一个持续更新的本地数据库，还涉及到合并冲突等问题，程序上需要的改动还挺多的 目前来说，个人认为最简单的复现页码功能就是每次搜索时维护一个本地变量，初值为1表示从第一页起计数，每NEXT一次+1，需要翻到第X页时程序自动进行NEXT操作并更新变量即可，当然考虑到服务器请求限制，X越大时需要的时间越长

肯定不能这么实现 翻个五十页就得等一分来钟 时间全浪费网络请求上了 还是按gid跳转来吧

**Comment by akinokoika** [comment]
> > 你这相当于维护一个持续更新的本地数据库，还涉及到合并冲突等问题，程序上需要的改动还挺多的 目前来说，个人认为最简单的复现页码功能就是每次搜索时维护一个本地变量，初值为1表示从第一页起计数，每NEXT一次+1，需要翻到第X页时程序自动进行NEXT操作并更新变量即可，当然考虑到服务器请求限制，X越大时需要的时间越长
> 
> 肯定不能这么实现 翻个五十页就得等一分来钟 时间全浪费网络请求上了 还是按gid跳转来吧

个人觉得如果想要保留类似过去的页面跳转功能，这是一种实现开销很小的方案，以后给有跳转页面这种特殊需求的人使用，几分钟的等待比没有选项更好
不过在昨天的更新里，开发者表示对无法使用的旧功能在以后要移除
技术在不断变化，软件更新可能会添加新功能并删除不再需要的旧功能是很正常的，不过对于该问题的提问者来说，可能这是一个没有帮助的遗憾结果

**Comment by xiaojieonly** [comment]
e站给出了时间跳转逻辑，现在按照E站给的来
