### ISSUE TITLE
最新的版本现在完全进不去里站，用梯子也不行。

### ISSUE THREAD

**Issue by rrrrrff** [xiaojieonly/Ehviewer_CN_SXJ#388]
![Screenshot_20221104_021345_com xjs ehviewer](https://user-images.githubusercontent.com/117387849/199802056-524d47c9-7ad3-4c6a-b109-be8c4a95d629.jpg)
![Screenshot_20221104_021340_com xjs ehviewer](https://user-images.githubusercontent.com/117387849/199802071-b099684d-6d90-4822-bc7f-d9bee41d9cf5.jpg)
![Screenshot_20221104_021335_com xjs ehviewer](https://user-images.githubusercontent.com/117387849/199802081-59889c3e-3ac9-4d8e-8d1f-68dff137968f.jpg)

**Comment by xiaojieonly** [comment]
要么cookie不对，要么网络配置有问题

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
