### ISSUE TITLE
恢复下载目录后无限闪退

### ISSUE THREAD

**Issue by xproducer** [xiaojieonly/Ehviewer_CN_SXJ#39]
我一开始想导入数据，但显示找不到，就改变下载路径进行恢复下载项的操作，恢复完后回到主页想看本子，结果直接闪退，之后连打开都打开不了，一点图标就是0.5秒内白屏闪退。清除数据重新登录就卡住转圈了（这个不知道是不是我的网络问题）

**Comment by xiaojieonly** [comment]
> 我一开始想导入数据，但显示找不到，就改变下载路径进行恢复下载项的操作，恢复完后回到主页想看本子，结果直接闪退，之后连打开都打开不了，一点图标就是0.5秒内白屏闪退。清除数据重新登录就卡住转圈了（这个不知道是不是我的网络问题）

app的问题，旧版数据不兼容了
