### ISSUE TITLE
请问如何修改默认下载标签

### ISSUE THREAD

**Issue by oosaber** [xiaojieonly/Ehviewer_CN_SXJ#391]
请问除了重装 还有其他方法设置吗

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/199982603-8ab773c5-1469-45ca-9d63-6d0d358f7817.png)

**Comment by oosaber** [comment]
好的 谢谢

**Comment by 229599557** [comment]
你好，我现在也是这一个问题，全部下载的东西都在默认的标签里，每次要看下载的东西那一些的时候都要一点一点翻找现在1.9.9.9的版本，我找不到您图上标识的这些东西。

**Comment by nojz3186-source** [comment]
> 你好，我现在也是这一个问题，全部下载的东西都在默认的标签里，每次要看下载的东西那一些的时候都要一点一点翻找现在1.9.9.9的版本，我找不到您图上标识的这些东西。

下载界面往左划。
