### ISSUE TITLE
下载漫画时突然0kb，提示如下

### ISSUE THREAD

**Issue by sleepy2con** [xiaojieonly/Ehviewer_CN_SXJ#394]
![Screenshot_2022-11-04-23-54-10-954_com xjs ehviewer](https://user-images.githubusercontent.com/86127159/200027531-c45a9b7e-ccd2-4ef9-a839-4b9fb2ec1fcf.jpg)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
