### ISSUE TITLE
封面缩略图加载失败

### ISSUE THREAD

**Issue by jiangdashi495** [xiaojieonly/Ehviewer_CN_SXJ#395]
如题，不管是否勾选修正缩略图链接都是无法显示
![Screenshot_2022_1105_012237](https://user-images.githubusercontent.com/110834044/200037714-8085f515-2b35-4aef-aa8f-158222424850.png)

**Comment by Restartzz1** [comment]
我是挂梯子缩略图就能正常加载了

**Comment by xiaojieonly** [comment]
网不好
