### ISSUE TITLE
经常超时，缩略图无法显示

### ISSUE THREAD

**Issue by Mike-Ty** [xiaojieonly/Ehviewer_CN_SXJ#4]
![Screenshot_20201121_105745_com sxj ehviewer](https://user-images.githubusercontent.com/60571318/99865964-69a8a880-2be8-11eb-8068-badc504d17ea.jpg)

**Comment by Mike-Ty** [comment]
希望解决，大佬辛苦了

**Comment by xiaojieonly** [comment]
> 希望解决，大佬辛苦了

好的，到时候更新1.7.7版本，看看能不能修复下，1.7.6我主要更新了汉化书签和详情页标签。

**Comment by wapy9** [comment]
缩略图把设置里高级里的host关了就能显示了

**Comment by lixiangwuxian** [comment]
卧槽，感谢，解决了困扰我已久的问题 @wapy9

**Comment by Mike-Ty** [comment]
谢谢大大，问题已经解决
