### ISSUE TITLE
修复/更换 tag翻译

### ISSUE THREAD

**Issue by URARUA** [xiaojieonly/Ehviewer_CN_SXJ#40]
当前tag翻译使用的数据库已不能正常使用（seven332/Ehviewer的code里面看起来已经没有这个了）
这是新的 [翻译数据库](https://github.com/EhTagTranslation/Database)

**Comment by xiaojieonly** [comment]
> 当前tag翻译使用的数据库已不能正常使用（seven332/Ehviewer的code里面看起来已经没有这个了）
> 这是新的 [翻译数据库](https://github.com/EhTagTranslation/Database)

好的，在搞了，等我把详情页略缩图的问题解决下一起更

**Comment by URARUA** [comment]
已经修复完成
