### ISSUE TITLE
为什么我的下的作者这个版本一直转圈圈，能看缩略图却无法阅读，白E正常

### ISSUE THREAD

**Issue by manmanstop** [xiaojieonly/Ehviewer_CN_SXJ#403]

**Comment by manmanstop** [comment]
急死了急死了

**Comment by manmanstop** [comment]
解决了，关闭软件。清除软件所有数据、或者卸载也行（前提记得备份）然后重新打开

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
