### ISSUE TITLE
关于tag的点击形式问题

### ISSUE THREAD

**Issue by phantomkings** [xiaojieonly/Ehviewer_CN_SXJ#405]
在更新后，点击搜索的tag都变成了不可叠加的模式
如图，以【单男主】为例，在点击搜索栏时只会出现male:sole male。这个字样是无法与其他tag联动搜索的。
![Screenshot_2022-11-06-11-55-47-43_159c494ea8977f628e53d8d36755ba4c](https://user-images.githubusercontent.com/117555857/200153475-4d5cfcf3-1710-498a-9a0e-a2c4418ce07f.jpg)
![Screenshot_2022-11-06-11-56-51-41_159c494ea8977f628e53d8d36755ba4c](https://user-images.githubusercontent.com/117555857/200153487-35e5b555-b269-40a2-ae26-b53b5acf5d27.jpg)
![Screenshot_2022-11-06-11-57-01-62_159c494ea8977f628e53d8d36755ba4c](https://user-images.githubusercontent.com/117555857/200153497-011a2013-3fe4-47c2-911f-27cf57381e1c.jpg)

原本的tag若是点击后出现的字符是m:“sole male$”，这个就可以多个联用。
![Screenshot_2022-11-06-11-58-13-26_159c494ea8977f628e53d8d36755ba4c](https://user-images.githubusercontent.com/117555857/200153525-1f126368-c1df-490c-b65f-5f162efa11dc.jpg)

请问一下这种情况有无解决办法，似乎很多人没有这个问题，但也有一些人和本人一样出现这个问题

**Comment by xiaojieonly** [comment]
最新版已解决
