### ISSUE TITLE
搜索栏历史搜索的问题

### ISSUE THREAD

**Issue by animationplayer** [xiaojieonly/Ehviewer_CN_SXJ#407]
假如我之前搜索过female:"mind control$" language:chinese，那么搜索栏会有该条历史搜索
当搜索栏是空的，我直接点击该条历史搜索，然后搜索，结果是正常的
但当我先输入female:mind control，在点击该历史搜索，会变成female:"mind female:"mind control$" language:chinese，进而导致什么都搜索不出来

进一步测试表明，对带空格的搜索都有这个问题，例如female:"mind break$" language:chinese。但对不带空格的，则是正常的，例如female:slave language:chinese

**Comment by xiaojieonly** [comment]
自己操作有问题

**Comment by animationplayer** [comment]
> 自己操作有问题

那怎么操作？
如果说正常操作是自己在搜索栏打出来，那历史搜索的意义是什么？
如果不是，我想不到还有什么操作了
