### ISSUE TITLE
[bug]无法导入数据也无法导出数据

### ISSUE THREAD

**Issue by jungleooo** [xiaojieonly/Ehviewer_CN_SXJ#41]
安卓10，MIUI12
可以正常使用，但是导入数据时提示找不到任何数据，导出数据时提示导出数据失败
安装的时候和旧版eh是共存的，由于MIUI12的特性，我怀疑是没有权限访问EhViewer这个路径，然后尝试给了权限，还是无法正常导入导出数据。但是诡异的是，下载是可以正常下载到这个路径的。

**Comment by xiaojieonly** [comment]
> 安卓10，MIUI12
> 可以正常使用，但是导入数据时提示找不到任何数据，导出数据时提示导出数据失败
> 安装的时候和旧版eh是共存的，由于MIUI12的特性，我怀疑是没有权限访问EhViewer这个路径，然后尝试给了权限，还是无法正常导入导出数据。但是诡异的是，下载是可以正常下载到这个路径的。

这个我先记着，之后尝试修复一下（；´д｀）ゞ

**Comment by jungleooo** [comment]
辛苦辛苦

**Comment by wsn37** [comment]
> > 安卓10，MIUI12
> > 可以正常使用，但是导入数据时提示找不到任何数据，导出数据时提示导出数据失败
> > 安装的时候和旧版eh是共存的，由于MIUI12的特性，我怀疑是没有权限访问EhViewer这个路径，然后尝试给了权限，还是无法正常导入导出数据。但是诡异的是，下载是可以正常下载到这个路径的。
> 
> 这个我先记着，之后尝试修复一下（；´д｀）ゞ

一开始下载也不行，自定义了下载路径后就可以了。可能搞个自定义导出路径也能一了百了
