### ISSUE TITLE
「收藏」無法跳轉頁面

### ISSUE THREAD

**Issue by Steagh** [xiaojieonly/Ehviewer_CN_SXJ#419]
打開「收藏」頁面，只顯示一頁
往下滑會跳出「沒找到下一頁」
而且顯示的作品並不是按照收藏順序應該有的第一頁
即使使用搜索，也無法找到其他作品

**Comment by xiaojieonly** [comment]
那就是没有，建议左滑看看自己选对了收藏文件夹没
