### ISSUE TITLE
更新1.9.4.0版本后每次打开app会重置里站igneous

### ISSUE THREAD

**Issue by henrycaven9** [xiaojieonly/Ehviewer_CN_SXJ#427]
用cookie登陆里站，1.9.4.0版本app每次打开都得退出账号，重新用cookie登陆。

如果正常关闭app再重新打开，会发现app里账号cookie一栏igneous会变成mystery，导致无法进入里站。

**Comment by henrycaven9** [comment]
请问能否在设置里增加一个选项，选择是否自动更新本地cookie，即可以主动锁定登陆时使用的cookie值不因里站返回值改变。

**Comment by xiaojieonly** [comment]
可以，但是如果你不怕里站权限被封的话可以试试。。。。

**Comment by xiaojieonly** [comment]
合并到此[issue](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/397)
