### ISSUE TITLE
1.9.4版本许多缩略图无法显示，点进去能正常观看

### ISSUE THREAD

**Issue by lqpok** [xiaojieonly/Ehviewer_CN_SXJ#428]

**Comment by lqpok** [comment]
还有导出的数据无法被白e彩e所读取 求修复下

**Comment by xiaojieonly** [comment]
网不好
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
