### ISSUE TITLE
无法下载内容

### ISSUE THREAD

**Issue by 79070492** [xiaojieonly/Ehviewer_CN_SXJ#43]
里站可以直连，内容均可以正常浏览，但是无法下载。在流量，WiFi，vpn的情况下均可以浏览但都不能下载。请问如何解决

**Comment by xiaojieonly** [comment]
> 里站可以直连，内容均可以正常浏览，但是无法下载。在流量，WiFi，vpn的情况下均可以浏览但都不能下载。请问如何解决

这。。。能和我讲下软件版本号和手机安卓系统版本号不，我有空排查下

**Comment by 79070492** [comment]
软件版本1.7.6.15，安卓10
版本号:RMX2071_11_A.25_7b3f2277

**Comment by wsn37** [comment]
> 里站可以直连，内容均可以正常浏览，但是无法下载。在流量，WiFi，vpn的情况下均可以浏览但都不能下载。请问如何解决

你有没有试试自定义一下下载路径

**Comment by 79070492** [comment]
通过更换路径解决了，非常感谢。问题已确认
（预设:默认目录)0/EhViewer/download提示，该文件夹不可写，已经给了写入权限，但不知道为什么不能写入
更改为（预设:应用文件目录1）0/ Android/ data/后问题解决
额外的小问题:似乎不能自定义储存路径，除两个预设路径外其他文件夹不会显示
问题圆满解决，再次感谢
