### ISSUE TITLE
怎么进去里站啊还是没搞懂

### ISSUE THREAD

**Issue by Fullary** [xiaojieonly/Ehviewer_CN_SXJ#435]
差不多是10年左右注册的账号，后来一直没用，最近好多画师都直接送里站了，好不容易找回密码了，一登录，哎，没用。。。

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
还是不行就百度一下

**Comment by xiaojieonly** [comment]
百度也不行就google
