### ISSUE TITLE
App 入不到里站，但網頁能進

### ISSUE THREAD

**Issue by Csk244** [xiaojieonly/Ehviewer_CN_SXJ#439]
今日下午3點多開始就有這情況，用app能進表站，但進不到里站。但我用網頁也能進里站
我用了白版來試，也是同一個情況啊

**Comment by Csk244** [comment]
3個EhViewer也進不了,試了很久, 終於找到方法能進了

方法很奇怪, 就是先退出登錄, 再在登錄中用網頁方法登入. 之前我用Cookie方法登入都不行的

**Comment by xiaojieonly** [comment]
没其他问题的话我就把issue关了
