### ISSUE TITLE
一直显网络错误怎么办？

### ISSUE THREAD

**Issue by 863373533** [xiaojieonly/Ehviewer_CN_SXJ#446]
开科技显示网络错误不开科技只有流泪熊猫

**Comment by 1016470686** [comment]
把内置hosts关了
![Screenshot_2022-11-20-01-39-46-59_159c494ea8977f628e53d8d36755ba4c](https://user-images.githubusercontent.com/116863902/202864183-a27bf86d-82af-4bd9-8c59-d27ebfe2939a.jpg)

**Comment by 1016470686** [comment]
把内置hosts关了

**Comment by 1016470686** [comment]
把内置hosts关了

**Comment by 1016470686** [comment]
> 开科技显示网络错误不开科技只有流泪熊猫

把内置hosts关了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
