### ISSUE TITLE
估计是下的东西有点多，被封IP了

### ISSUE THREAD

**Issue by fly9593** [xiaojieonly/Ehviewer_CN_SXJ#447]
自己搭的梯子，进里站下东西，估计是短时间下了太多东西（下了大概40几本吧），然后就登不上去了，但是换一个ip可以登上。这里也希望大家引以为戒吧。尽量在线看，真要下东西也别用自己的私人IP

**Comment by zzx111ded** [comment]
只要一次不超过5000就行啊

**Comment by fly9593** [comment]
> 只要一次不超过5000就行啊

但是我的ip的确被封了，这个梯子还是我自己搭的。，就我一个人再用。另外你说的5000是指一次下5000张图吗？

**Comment by droid600291** [comment]
短時間流量太大被當爬蟲很正常，就算你是在線看的也一樣
不過我記得被封的話等一小時系統就會自動解封了，還沒看到有永Ban的狀況出現

**Comment by fly9593** [comment]
> 短時間流量太大被當爬蟲很正常，就算你是在線看的也一樣 不過我記得被封的話等一小時系統就會自動解封了，還沒看到有永Ban的狀況出現

那我估计是被永ban了，我是9月底的时候被封的，现在还是上不去

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
