### ISSUE TITLE
老平板安卓5.1.1，安装失败

### ISSUE THREAD

**Issue by zzx111ded** [xiaojieonly/Ehviewer_CN_SXJ#449]
2k10寸大屏又舍不得扔，拿来看本子刚好呜呜呜
求助一个支持5.1.1的版本，功能多少都没事，只要支持就好，当阅读器用（一定得是sxj大佬版本的）

**Comment by xiaojieonly** [comment]
下一版我看看能不能改一改

**Comment by xiaojieonly** [comment]
你要不给平板刷个机？刷成安卓6的？

**Comment by zzx111ded** [comment]
哇大佬回我了，老机子似乎没刷机包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)




 
你要不给平板刷个机？刷成安卓6的？

**Comment by xiaojieonly** [comment]
https://wwsu.lanzouy.com/iwHoU0rqykad
密码:849y

**Comment by xiaojieonly** [comment]
你试试

**Comment by zzx111ded** [comment]
太感谢了，我马上试试





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)





 
https://wwsu.lanzouy.com/iwHoU0rqykad
 密码:849y

**Comment by zzx111ded** [comment]
不行捏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 中午1:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)





 
你试试

**Comment by zzx111ded** [comment]
还是闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 中午1:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)





 
你试试

**Comment by xiaojieonly** [comment]
额

**Comment by zzx111ded** [comment]
jh就正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 中午1:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)






额

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by zzx111ded** [comment]
还有原版1.7.12也行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 中午1:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)






额

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by xiaojieonly** [comment]
https://wwsu.lanzouy.com/ihsZa0rqz31i
密码:5uxp

**Comment by xiaojieonly** [comment]
你试试

**Comment by xiaojieonly** [comment]
可能需要挂梯子啥的

**Comment by zzx111ded** [comment]
老哥 还是不行，这么麻烦您挺不好意思的，我还是用原版加挂梯子吧，就不烦您了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] 老平板安卓5.1.1，安装失败 (Issue #449)





 
https://wwsu.lanzouy.com/ihsZa0rqz31i
 密码:5uxp

**Comment by xiaojieonly** [comment]
行吧
