### ISSUE TITLE
编译問題

### ISSUE THREAD

**Issue by eithwa** [xiaojieonly/Ehviewer_CN_SXJ#457]
您好:
我目前使用release版本1.9.4.1(6ccb37b)在andorid studio内进行编译，andorid sdk版本是12.0, os是windows10, jdk-17.0.5
下面这些部分无法编译，请问我是否需要安装其他的套件或更换套件版本?
谢谢
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/6ccb37bb171348cf5fbf48a6d928306c2f8bfcbc/app/src/main/res/layout/gallery_list_date_jump_dialog.xml#L7
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/6ccb37bb171348cf5fbf48a6d928306c2f8bfcbc/app/src/main/res/layout/gallery_list_jump_selector.xml#L15
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/6ccb37bb171348cf5fbf48a6d928306c2f8bfcbc/app/src/main/java/com/hippo/ehviewer/ui/scene/gallery/list/GalleryListScene.java#L1329

**Comment by xiaojieonly** [comment]
不建议使用主分支进行编译，建议使用其他分支，此分支我有没写完的代码没提交

**Comment by eithwa** [comment]
> 不建议使用主分支进行编译，建议使用其他分支，此分支我有没写完的代码没提交

您好:
请问1.9.4.1，E站页面跳转更改逻辑，
这部分的代码是否就没办法编译了吗
谢谢
