### ISSUE TITLE
[功能申请] 支持阅读画廊时手动输入页数换页

### ISSUE THREAD

**Issue by HourGlassZ** [xiaojieonly/Ehviewer_CN_SXJ#46]
如题

**Comment by duzhaokun123** [comment]
右下角加号->从上向下数第二个按钮

**Comment by duzhaokun123** [comment]
> 右下角加号->从上向下数第二个按钮

是第一个, 第二个是 NekoInverter 的[这次提交](https://gitlab.com/NekoInverter/EhViewer/-/commit/e74e7b4a9d40ced92e36f319cf8617bfd9f6d983)之后版本

**Comment by HourGlassZ** [comment]
> > 右下角加号->从上向下数第二个按钮
> 
> 是第一个, 第二个是 NekoInverter 的[这次提交](https://gitlab.com/NekoInverter/EhViewer/-/commit/e74e7b4a9d40ced92e36f319cf8617bfd9f6d983)之后版本

![Screenshot_20201220-153828_EhViewer-01.jpeg](https://user-images.githubusercontent.com/65544952/102707860-8fa19580-42d9-11eb-9f1e-666f45e8eb4b.jpeg)
是指阅读画廊时的跳转（我这边只有滑动进度条换页）

**Comment by duzhaokun123** [comment]
似乎没有地方加这个功能

- 底下的`SeekBar`点两边是首页和尾页
- 长按菜单是关于当前页的操作
- 单击菜单是调整设置

🤔

**Comment by xiaojieonly** [comment]
> 如题

我可以试试，但是现在功能申请有点多，兄弟你的申请估计得排很后面了😅

**Comment by xiaojieonly** [comment]
> 如题

第一个功能已经有了，第二个功能没有意义。
