### ISSUE TITLE
1.9.4.1版本无法翻译标签

### ISSUE THREAD

**Issue by 123LaoShiRen** [xiaojieonly/Ehviewer_CN_SXJ#464]
手机为红米k40 系统为MIUI12.5.14稳定版
无法显示翻译后的标签
尝试重新下载安装多次
尝试使用梯子
悲伤之余去午睡了
睡起来在被窝里些上述反馈时，应用在后台挂着
结果刚刚切回去准备截个屏时，开始显示翻译后的标签了
淦

**Comment by xiaojieonly** [comment]
是这样的，从github下载翻译资源需要时间
