### ISSUE TITLE
收藏页只能看第一个收藏夹

### ISSUE THREAD

**Issue by Rex1987** [xiaojieonly/Ehviewer_CN_SXJ#473]
点击收藏，默认跳转到收藏夹0，不知道能否切换

**Comment by xiaojieonly** [comment]
屏幕从右往左滑

**Comment by Pil0tXia** [comment]
@xiaojieonly 

>屏幕从右往左滑

请问可以增加一个实体按钮或者提醒吗？

我以为没有这个功能，来提issue时发现其实是已经做好了的。

这样对于新用户来说应该会更友好
