### ISSUE TITLE
[bug]新版本打开会直接闪退

### ISSUE THREAD

**Issue by babooms** [xiaojieonly/Ehviewer_CN_SXJ#48]
刚刚下载好1.7.7.0，打不开，点开直接闪退

**Comment by xiaojieonly** [comment]
> 刚刚下载好1.7.7.0，打不开，点开直接闪退

最新版应该不会闪退了，你的情况大概率是跳版本了

**Comment by babooms** [comment]
但是我旧版是1.7.6.15
应该不跳版本吧

**Comment by xiaojieonly** [comment]
> 但是我旧版是1.7.6.15
> 应该不跳版本吧
用最新版试试？

**Comment by xiaojieonly** [comment]
> 但是我旧版是1.7.6.15
> 应该不跳版本吧

(⊙﹏⊙)，如果不闪退了和我说下

**Comment by babooms** [comment]
> > 但是我旧版是1.7.6.15
> > 应该不跳版本吧
> 
> （⊙﹏⊙），如果不闪退了和我说下

好了可以了，用新版本就没事了

**Comment by xiaojieonly** [comment]
> > > 但是我旧版是1.7.6.15
> > > 应该不跳版本吧
> > 
> > 
> > （⊙﹏⊙），如果不闪退了和我说下
> 
> 好了可以了，用新版本就没事了

ok

**Comment by xiaojieonly** [comment]
> > > 但是我旧版是1.7.6.15
> > > 应该不跳版本吧
> > 
> > 
> > （⊙﹏⊙），如果不闪退了和我说下
> 
> 好了可以了，用新版本就没事了

旧数据没丢失吧？
