### ISSUE TITLE
老版本更新后，登不上去，cookie中的ign被改

### ISSUE THREAD

**Issue by xiaoshengbibi** [xiaojieonly/Ehviewer_CN_SXJ#480]
自从分页的更新版本后，每当应用完全退出后，cookie中的ign就会被改为mystery。完全退出是指任务管理器里面把他给删了。

**Comment by xiaojieonly** [comment]
在研究

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ#readme
最新版已给出解决方案
