### ISSUE TITLE
下载功能有问题

### ISSUE THREAD

**Issue by 23333233** [xiaojieonly/Ehviewer_CN_SXJ#482]
下载到最后一页有时候会下不动，速度那里也显示0kb，下几个小时都不一定能下好，但是暂停之后接着下载就能下下来

**Comment by 18739606025** [comment]
我也是这样，下载到90%左右，下载速度就归零，然后一直卡在这个漫画任务，不会自动切换下一个下载任务

**Comment by xiaojieonly** [comment]
正常，网络不稳定或者达到下载额度，都会这样
