### ISSUE TITLE
无法下载，已经下载的内容读取失败

### ISSUE THREAD

**Issue by Tolemu** [xiaojieonly/Ehviewer_CN_SXJ#485]
几天前突然开始出现的问题，app在下载图片以后一直覆盖原来的文件导致下载进度一直为0，只能保存缓存的图片。
现在唯一的办法是下载以后暂停，删除画册的文件夹，用浏览的方法把图片放到缓存里再点下载。但是有个更严重的问题。

那就是之前下载的图片也全部读取失败，用文件浏览器打开图片均正常。

**Comment by a9460620** [comment]
在設定裡面把下載路徑改為app內部路徑，就可以正常下載，看起來是路徑的問題

**Comment by xiaojieonly** [comment]
安卓12以上的版本外部路径没法使用了，只能用app的内部路径

**Comment by darrenxl** [comment]
安卓11及以下遇到读取失败可以排查一下应用权限
以Flyme9为例
应用管理-Ehviewer-应用权限-手机存储-文件访问范围
选择全部文件，或者指定文件-将你的的目标下载路径划入其中
同理，在图片访问范围中选择全部图片，尤其是在关闭了允许媒体扫描的情况下

**Comment by sdo9004** [comment]
前一天下好的东西今天去下载里看找不到了，去主页搜的话还能搜到进去显示已下载，感觉就像下载列表里被吞了怎么解决

**Comment by darrenxl** [comment]
哈哈，实不相瞒，大概上个月我也意识到出现了同样的问题，我自己专设了一个叫ongoing的下载分类，专门用来追更新，其中就有[takaman]的作品合集，大概100多页，每次在列表里单独点击下载都会重新下载，下载完毕后全部下载倒是不会参与，进入观看又是转圈，折磨几次后索性删掉另存到本地了，有时间的话我再往issue里看看有没有先例

**Comment by muhan152** [comment]
有一个奇怪的问题，在绿e 1.9.71中，已经下载（不是原图）的图集在图集更新后覆盖会有问题，大致是更新的图片和前40张会在每次查看的时候重新加载，是和缩略图有关系吗

**Comment by turmoyaz** [comment]
1.9.7.2还是会出现下载内容无法读取的现象，除非挂梯子打开，但是版权本就是没办法

**Comment by kangyanmie** [comment]
我在遇到这个问题的时候，是因为我刚更新了vivo的os4系统，然后下载的内容无法读取，参考上面的意见，我想到了把权限禁止再把权限打开。结果就OK了哈哈哈

**Comment by turmoyaz** [comment]
x80还没有更新os4😂，我也去试试搞搞权限，谢谢哥们

**Comment by exxhlyh** [comment]
> 我在遇到这个问题的时候，是因为我刚更新了vivo的os4系统，然后下载的内容无法读取，参考上面的意见，我想到了把权限禁止再把权限打开。结果就OK了哈哈哈

😘感谢。iqoo更新了os4后，eh出现问题，包括已下载内容无法读取，下载或者阅读某个本子的时候极速把配额烧完等问题。移除并重新赋予权限后就好了。

**Comment by 666666882772827299** [comment]
真的有用😂，把权限关闭后再打开👍突然感觉自己像小丑🤔

**Comment by xiaomo729** [comment]
不行，我还是有部分图片读取失败，而且就是特定那几张，删了重新2下载都没用，就是那几张会读取失败

**Comment by xiaomo729** [comment]
而且我感觉跟下载问题有关系，因为重新下载的时候我发现读取失败部分都是下载速度位0并且进度条往前跳的很快

**Comment by Nekok0327** [comment]
我现在下载也是越到最后越慢，到最后肯定有两页无法完成，继续下载也不行

**Comment by anarchycuriosity** [comment]
下载缓慢和下载失败建议挂VPN，无法读取可以先查看是否更新安装eh时系统自动把eh移到了隔离箱导致没有读取文件的权限

**Comment by TangJiFa** [comment]
我的一加11在colorsos15下赋予app“图片和视频”权限是没有“允许有限访问”和“始终全部允许”选项，只有“允许”和“不允许”我不清楚这是否会直接影响下载功能。但是我尝试了移除和赋予“图片和视频”“文件和文档”“所有文件访问权限”后依旧会有图片无法下载，具体表现为下载跑圈装满两圈后显示“读取失败”，检查下载位置也没有找到图片

**Comment by shelie3175** [comment]
读取失败是因为软件更新之后又被默认放进隔离箱里面了。感谢大佬帮助，我终于知道为什么看不了我的下载了

**Comment by 1234qwer-a** [comment]
我昨天还可以成功下载，今天就无法下载了，下载画廊，进度条一直是0B/s画廊除了封面，其他的都是没法加载出来的，睡个觉起来就这样了，更新了版本之后也是没用，两台手机上的都是，内存也没有满，也连了网，第三台可以下，但下的也很慢，半天也只下了一张，尝试了很多方法都没用，请知道怎么解决的人提供帮助
