### ISSUE TITLE
为什么我第一次用就显示配额满了

### ISSUE THREAD

**Issue by theskylink** [xiaojieonly/Ehviewer_CN_SXJ#490]
随便点一个本进去都是转圈，不显示图片，能搜到本子能加载缩略图就是看不了，点阅读全都是加载图标但就是加载不出来。然后我试着下载，刚开始下载也是一直没进度，反复试了好几次挂加速器能下载了结果显示配额满了。。。我一个本都还没看呢啊一个本都还没下呢啊怎么就能满了呢

**Comment by yuduchen7** [comment]
> 随便点一个本进去都是转圈，不显示图片，能搜到本子能加载缩略图就是看不了，点阅读全都是加载图标但就是加载不出来。然后我试着下载，刚开始下载也是一直没进度，反复试了好几次挂加速器能下载了结果显示配额满了。。。我一个本都还没看呢啊一个本都还没下呢啊怎么就能满了呢

换个ip就行

**Comment by xiaojieonly** [comment]
楼上正解
