### ISSUE TITLE
里站无法进入

### ISSUE THREAD

**Issue by zhuixingmomo** [xiaojieonly/Ehviewer_CN_SXJ#491]
有账号，里站无法加载，超时

**Comment by ScarletCurry** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/151#issue-1007384530
你从app中看看账号的身份cookie那栏igneous是不是mystery，是话就按他的方法 从电脑端的里站查看cookie，把这个igneous值输进去，这样就可以进入里站了
但我这里还有个问题就是必须裸连进去，开梯子进不去，但是裸连进里站也会加载超时，然后我把高级设置里的域名前置关了，就可以正常用梯子看里站了

**Comment by yzxcy** [comment]
> 
还真是igneous: 有问题
