### ISSUE TITLE
建议默认关闭域前置

### ISSUE THREAD

**Issue by Fangliding** [xiaojieonly/Ehviewer_CN_SXJ#499]
挂梯子发现死活打不开 仔细分析后发现是因为软件使用域前置连接 但只要client或者server的v2ray启用了destoverride 域前置请求的目的地将被覆写导致无法正常连接
不过这样苦了直连用户 最好的选择是默认打开在检测到系统开启vpn时自动关闭

**Comment by BJY666** [comment]
想知道如何关闭域前置，挂梯之后一直无法连接

**Comment by BJY666** [comment]
搞懂了，在高级-代理，设置成直接连接就行了

**Comment by xiaojieonly** [comment]
下一版会处理
