### ISSUE TITLE
种子无法获取，希望修正

### ISSUE THREAD

**Issue by wangfreexx** [xiaojieonly/Ehviewer_CN_SXJ#5]
种子获取显示错误，之前我看过源码，好像是正则表达式获取种子地址错误，但是苦于自身水平不会改，希望大佬能修改下，能够正常获取种子那就太好了

**Comment by xiaojieonly** [comment]
好的，下一版修复

**Comment by xiaojieonly** [comment]
> 种子获取显示错误，之前我看过源码，好像是正则表达式获取种子地址错误，但是苦于自身水平不会改，希望大佬能修改下，能够正常获取种子那就太好了

好的，下一版修复

**Comment by xiaojieonly** [comment]
> 种子获取显示错误，之前我看过源码，好像是正则表达式获取种子地址错误，但是苦于自身水平不会改，希望大佬能修改下，能够正常获取种子那就太好了

好的谢谢告知，我尽快在下一版中修复O(∩_∩)O

**Comment by xiaojieonly** [comment]
> 种子获取显示错误，之前我看过源码，好像是正则表达式获取种子地址错误，但是苦于自身水平不会改，希望大佬能修改下，能够正常获取种子那就太好了

1.7.7版本进行修复，1.7.6我更新了默认的汉化书签和详情页标签＞﹏＜

**Comment by wangfreexx** [comment]
大佬你好，你看下这个https://github.com/NekoInverter/EhViewer，也是维护相同的软件，直接搜索是搜不出来，你们是不是应该合并免得重复工作

**Comment by xiaojieonly** [comment]
> 大佬你好，你看下这个[https://github.com/NekoInverter/EhViewer，也是维护相同的软件，直接搜索是搜不出来，你们是不是应该合并免得重复工作](https://github.com/NekoInverter/EhViewer%EF%BC%8C%E4%B9%9F%E6%98%AF%E7%BB%B4%E6%8A%A4%E7%9B%B8%E5%90%8C%E7%9A%84%E8%BD%AF%E4%BB%B6%EF%BC%8C%E7%9B%B4%E6%8E%A5%E6%90%9C%E7%B4%A2%E6%98%AF%E6%90%9C%E4%B8%8D%E5%87%BA%E6%9D%A5%EF%BC%8C%E4%BD%A0%E4%BB%AC%E6%98%AF%E4%B8%8D%E6%98%AF%E5%BA%94%E8%AF%A5%E5%90%88%E5%B9%B6%E5%85%8D%E5%BE%97%E9%87%8D%E5%A4%8D%E5%B7%A5%E4%BD%9C)

我是兴趣使然，边学习边维护，人家比我强多了，等我变强了再去吧。。。现在还真不太好意思去找人家

**Comment by mophy-chun** [comment]
没有证书，有些型号的手机不能安装。大佬解决下。

**Comment by mophy-chun** [comment]
我用荣耀的手机，新更新为Magic系统，提示没有证书，安装不了。

**Comment by xiaojieonly** [comment]
> 我用荣耀的手机，新更新为Magic系统，提示没有证书，安装不了。

额，这是没平台审核的app，不让装属实正常，通常设置里设置下允许自行安装app就行

**Comment by xiaojieonly** [comment]
> 种子获取显示错误，之前我看过源码，好像是正则表达式获取种子地址错误，但是苦于自身水平不会改，希望大佬能修改下，能够正常获取种子那就太好了

兄弟我来晚了抱歉，你的问题我修好了
