### ISSUE TITLE
更新之后里站无法进入，无语言显示

### ISSUE THREAD

**Issue by fantasysimulation** [xiaojieonly/Ehviewer_CN_SXJ#502]
今天APP更新后里站还是无法进入，只出现半个金属头流泪，无文字。翻墙也不行，cookie正常

**Comment by 528127** [comment]
为啥我表站也这样，只有半个流泪头，别的啥也没有，是我到限额了吗

**Comment by fantasysimulation** [comment]
> 为啥我表站也这样，只有半个流泪头，别的啥也没有，是我到限额了吗

我是表站可以正常进去，就是有点卡。里站是怎么都进不去，VPN，重登，都试过了。现在是用浏览器进的去，APP进不去

**Comment by fantasysimulation** [comment]
![Uploading Screenshot_20230126_233937_com.xjs.ehviewer.jpg…]()

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md

**Comment by xiaojieonly** [comment]
截图看不到

**Comment by fantasysimulation** [comment]
![Screenshot_20230126_233937_com xjs ehviewer](https://user-images.githubusercontent.com/78940966/215334042-009dc640-e7ed-4b81-82c2-09b6722c155a.jpg)

**Comment by fantasysimulation** [comment]
> 

就是像这样的，到现在还是网页进的去，APP进不去
