### ISSUE TITLE
超链接跳转功能不完整

### ISSUE THREAD

**Issue by dukeodnminion** [xiaojieonly/Ehviewer_CN_SXJ#503]
该版本可以实现通过评论中的超链接指向某个画廊的功能，但是无法实现从评论中的超链接指向具体某张图的功能

比如一些月刊漫画评论区的漫画目录，使用该版本时点击目录中的超链接，只能定向到本画廊，而无法定位到超链接指向的画廊内的图
于是就变成如密传如密了

举例：https://exhentai.org/g/2440962/1507f7261b/

**Comment by xiaojieonly** [comment]
暂时无法提供此功能
