### ISSUE TITLE
无效证书/连接不安全 问题

### ISSUE THREAD

**Issue by veteran233** [xiaojieonly/Ehviewer_CN_SXJ#504]
请问能设置一个选项，使得在无效证书/连接不安全的情况下，继续访问吗？

**Comment by txyyh** [comment]
如果可以，还请附上需要此功能的动机

这往往可以更好地帮助解决您的问题

**Comment by veteran233** [comment]
> 如果可以，还请附上需要此功能的动机
> 
> 这往往可以更好地帮助解决您的问题

我在pc上部署了nginx用来反代，突破sni封锁。由于我的手机和pc处于同一局域网，想通过pc代理ehviewer，但出现了“网络错误”四个字，我也不知道为什么，猜测是证书问题。

**Comment by xiaojieonly** [comment]
手机里的sni关了

**Comment by xiaojieonly** [comment]
不是证书问题，这种情况要么是配置有问题，要么是nginx配置有问题
