### ISSUE TITLE
允许媒体扫描开启再关闭后，图库依然能扫描到图片

### ISSUE THREAD

**Issue by Learnho** [xiaojieonly/Ehviewer_CN_SXJ#514]
如题，允许媒体扫描开启再关闭后，图库依然能扫描到图片

**Comment by Learnho** [comment]
已解决，在下载图片的文件夹里面新建一个.nomedia文件夹

**Comment by xiaojieonly** [comment]
1

**Comment by xynb24** [comment]
What if there are no images in the media scanning gallery? Seek help

**Comment by xynb24** [comment]
允许媒体扫描开启后图库没有图片怎么办？

**Comment by kuqqqqqqi** [comment]
我是小米14，我关闭了（允许媒体扫描），但是相册还是能看到下载的本子。在下载图片的文件夹里新建.nomedia文件夹，依旧没有用。式了好多次了
