### ISSUE TITLE
Cookie丢失bug

### ISSUE THREAD

**Issue by FengJunJie1** [xiaojieonly/Ehviewer_CN_SXJ#516]
在使用一段时间（20min左右） igneous会变为mystery（在设置-身份COOKIE中看到的） 导致无法正常进入里站
用户只能重新退出/登录
每次使用的时候都要重复一遍上述操作 十分繁琐。

**Comment by xiaojieonly** [comment]
我研究一下，

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ#readme
最新版已给出解决方案
