### ISSUE TITLE
持续的sad panda

### ISSUE THREAD

**Issue by canyuegaoxuan** [xiaojieonly/Ehviewer_CN_SXJ#517]
持续的sad panda，表站也是sad panda。。。挂不挂梯子都一样，上周开始就一直这样，人傻了qwq

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
如果这个不能解决问题多半是网不好
