### ISSUE TITLE
希望新增关闭hentaiverse每日签到等活动提示功能

### ISSUE THREAD

**Issue by FuyukiAsahi** [xiaojieonly/Ehviewer_CN_SXJ#518]
RT，再次提出此issue，只因每天一开软件就看到dawn of a new day，翻着翻着莫名其妙又来个monster的提示，不敢更1.9.4.2及以上的任何版本，hentaiverse这些弹窗个人觉得很影响观感和使用体验，所以跪求作者考虑新增关闭的功能，万分感谢

**Comment by xiaojieonly** [comment]
好的

**Comment by Zenghaijian** [comment]
暗藏玄只因

**Comment by xiaojieonly** [comment]
下一版更新
