### ISSUE TITLE
提示读取失败

### ISSUE THREAD

**Issue by moesakura** [xiaojieonly/Ehviewer_CN_SXJ#526]
最新版本1.9.4.6
android color os 13
打开一个本子，kill app
重新打开本子提示读取失败
需要手动一张一张点击图片重新加载
过去几个版本都有这个问题

**Comment by xiaojieonly** [comment]
![image](https://user-images.githubusercontent.com/49278135/221079741-bd4c909b-83ac-4da5-85da-4ca1c0bfe30a.png)
违规操作，我没法处理，抱歉

**Comment by moesakura** [comment]
其实就是关闭app啊…
难道还有正常退出这样的操作吗
一般不都是杀后台
