### ISSUE TITLE
疑似用app被ban

### ISSUE THREAD

**Issue by caoacai** [xiaojieonly/Ehviewer_CN_SXJ#532]
![Screenshot_20230302-085410](https://user-images.githubusercontent.com/16099271/222307825-76c7bd1d-9875-4256-ae20-b98cae7db825.png)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
