### ISSUE TITLE
图片下载问题求助

### ISSUE THREAD

**Issue by grtpy** [xiaojieonly/Ehviewer_CN_SXJ#536]
画廊下载好后图片也是能正常加载的，退出app重新进入就读取失败了。
删了重新下还是会出现上面的情况
点刷新就会一直重复刷新提示网络错误，再刷新就能加载出来了，但是退出app一样会重复上面的问题。
下载的图片文件夹里也能正常打开。下载的画廊几十个里面可能会有一个出现这种情况

**Comment by xiaojieonly** [comment]
权限检查下，如果是偶现的话，我这边没法判断问题原因

**Comment by MauriceWang666** [comment]
遇到了相同的问题，似乎和安卓13更新有关

**Comment by grtpy** [comment]
影响不大就是会偶然发生一次，那一个画廊无论怎么重下都会发生同样的问题

**Comment by grtpy** [comment]
> 权限检查下，如果是偶现的话，我这边没法判断问题原因

没什么影响，就是只要那个画廊出现这个问题，以后怎么删除下载这个画廊都是这样

**Comment by grtpy** [comment]
> 遇到了相同的问题，似乎和安卓13更新有关

我的是安卓11

**Comment by grtpy** [comment]
> 权限检查下，如果是偶现的话，我这边没法判断问题原因

问题解决了，自己手机清理app缓存就没有这个问题了，eh自带的清理缓存清理的不够彻底？

**Comment by xiaojieonly** [comment]
是的
