### ISSUE TITLE
MIUI14 EH更新版本后屏蔽图库检索不起作用

### ISSUE THREAD

**Issue by zhentaisama** [xiaojieonly/Ehviewer_CN_SXJ#538]
已经关闭图库检索 但图库里还是出现图片
![Uploading Screenshot_2023-03-07-11-38-03-196_com.xjs.ehviewer.jpg…]()

**Comment by zhentaisama** [comment]
关闭后 已经重启过 仍未生效

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/514
