### ISSUE TITLE
你的打赏链接怎么用

### ISSUE THREAD

**Issue by qwe555666** [xiaojieonly/Ehviewer_CN_SXJ#540]
可以的话，发个手机号我用支付宝给

**Comment by xiaojieonly** [comment]
15224066043

**Comment by xiaojieonly** [comment]
扫二维码就行，谢谢老板

**Comment by qwe555666** [comment]
我都点不开，看不到二维码，怎么打赏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月1日(周四) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaojieonly/Ehviewer_CN_SXJ] 你的打赏链接怎么用 (Issue #540)




 
Closed #540 as completed.
