### ISSUE TITLE
下载的时候经常速度掉到0然后不动了

### ISSUE THREAD

**Issue by tyx776** [xiaojieonly/Ehviewer_CN_SXJ#542]
就是用了这款以后经常没有速度，就是速度0.然后也不会进行下一个下载。就这么一直卡在这，频率还不低。导致一天也没下几本。以前用大象版和白色版的时候没有这种问题，都能下到没有流量。所以来问一下，有没有什么办法能解决。当然搭梯的时候速度和0速度的问题几乎没有，但是你也知道梯子太多人用，用一会就没流量了。

**Comment by xiaojieonly** [comment]
网不好，时有发生是正常的，后续会稍微优化下
