### ISSUE TITLE
重开软件导致cookie中的igneous变成mystery，导致软件上不到里站。

### ISSUE THREAD

**Issue by 72888hshu** [xiaojieonly/Ehviewer_CN_SXJ#544]
现软件连不上里站，便决定重新登录。使用了cookie重新登录后（cookie是对照里站网页版的），成功登录并且能暂时浏览里站。关闭应用再重开后又不能浏览里站了。看了一下设定里的身份cookie资料后发现igneous数值变成了mystery，重登录后只要重开应用都会变成mystery，网页版里站能正常使用，所以可以确定不是账号的问题。

账号近期改了密码，不知道是不是这个原因。

版本：1.9.4.7

**Comment by xiaojieonly** [comment]
我检查下

**Comment by Erosionone** [comment]
同样的问题，只不过我的igneous值为null，网页可以上里站，不是账号问题

**Comment by metase** [comment]
遇到了同样的问题，一开始igneous正常，也可以显示里站内容但是无法打开。网页正常。重登录后变成了null

**Comment by IzumoMuraame** [comment]
我也是同样问题，igneous为mystery，无法登陆里站

**Comment by IzumoMuraame** [comment]
不过我的情况是退出登录重新登录一次之后就又正常了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ#readme
最新版已给出解决方案

**Comment by 72888hshu** [comment]
> https://github.com/xiaojieonly/Ehviewer_CN_SXJ#readme 最新版已给出解决方案

开启后igneous还是偶尔会变回mystery。
