### ISSUE TITLE
看不到任何EX畫廊

### ISSUE THREAD

**Issue by Hsuyuancheng** [xiaojieonly/Ehviewer_CN_SXJ#565]
看不到任何EX畫廊 只要是ex的都看不到 只能看E的

**Comment by Bitter-Man** [comment]
解决了吗，我换了好几个vpn了，e-能进，ex不行，清除数据和缓存好几次了

**Comment by Bitter-Man** [comment]
我的解决了，可能是VPN的问题，换手机重登录，查了下cookie，发现两次重登的igneous都不一样，一次是null，一次是mystyle，电脑网页登录EX，查了正常的igneous，OK了。
好奇怪，我以前登录，用网页登录一下就OK了，这次怎么就不行了。

**Comment by xiaojieonly** [comment]
没有权限，楼上正解
