### ISSUE TITLE
里站下载不了种子

### ISSUE THREAD

**Issue by 974260581** [xiaojieonly/Ehviewer_CN_SXJ#57]
里站下载不了种子，切换到表站重新入到页面就能下载。

**Comment by xiaojieonly** [comment]
> 里站下载不了种子，切换到表站重新入到页面就能下载。

好的，我之后留意下，修好了再回你

**Comment by Bright-de** [comment]
> > 里站下载不了种子，切换到表站重新入到页面就能下载。
> 
> 好的，我之后留意下，修好了再回你

可不可以把种子的发布时间，种子数，下载数也显示出来呢？

**Comment by xiaojieonly** [comment]
已经修好了，现在可以下载种子了，本地文件夹里已经下载过的种子会有弹窗提示已下载
