### ISSUE TITLE
开启允许媒体扫描后再关闭相册中仍扫描的到

### ISSUE THREAD

**Issue by kamitodayo** [xiaojieonly/Ehviewer_CN_SXJ#571]
不下心点到了现在很麻烦

**Comment by xiaojieonly** [comment]
[有bug](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/514)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/514
