### ISSUE TITLE
里站ex 无法加载缩略图

### ISSUE THREAD

**Issue by 373578807** [xiaojieonly/Ehviewer_CN_SXJ#578]
![Screenshot_20230516_155134](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/126319209/e14e7a20-6ec4-44db-b1bf-7a3c872eb622)
![Screenshot_20230516_155253](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/126319209/62c08f99-2bed-47de-a3d3-e4deeacc1ea2)
疑似是sni的问题 因为如果使用梯子便可以正常显示 并且没有缩略图不影响观看和下载

——————————————————
一小时后绿e莫名其妙的恢复了预览图……原因未知 但同系其他app貌似没有恢复  原因暂时未知  暂时不用处理了  作者辛苦了

**Comment by zsx1094108577** [comment]
缩略图能考，预览图好像看不了

**Comment by FuyukiAsahi** [comment]
封面缩略图可看，内容预览图依旧看不了

**Comment by CS1871415505** [comment]
我也有同样的问题，但是换表站站点的话好像可以看了，但这样就不能看里站的东西了。如果站点换成里站的话，还是看不了预览图.......

**Comment by rrrrr9029** [comment]
能看到封面的缩略图但是内容缩略图一直加载不出来，点进去能看到内容

**Comment by 373578807** [comment]
> 

经过测试 是里站缩略图走的是一个新的域名……s.ex.....

**Comment by xiaojieonly** [comment]
最新版已修复
