### ISSUE TITLE
里站缩略图看不了

### ISSUE THREAD

**Issue by 00loli** [xiaojieonly/Ehviewer_CN_SXJ#579]
前几天还好好的，这两天突然不行了，很难受😭作者大大辛苦了
![Screenshot_20230517_180321](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/133864352/1a4cc08d-f3e3-460a-9931-a1d644dfd787)

**Comment by rrrrr9029** [comment]
我也看不了内容缩略图，除了这点都没事

**Comment by kkkkk2345** [comment]
由1.9.4.6開始,便沒試過看到縮圖.每次更新試後,也要退回1.9.4.5.

**Comment by xiaojieonly** [comment]
最新版已修复
