### ISSUE TITLE
右侧书签栏设置功能异常

### ISSUE THREAD

**Issue by a123456gba** [xiaojieonly/Ehviewer_CN_SXJ#58]
右侧书签栏设置里面调整书签页顺序功能异常，进入设置后可以长按拖动三条杠但是最后返回后调整的书签栏顺序并没有是我调整的顺序，我尝试多次拉动书签顺序后显示的也不正常。我是用以前的db文件导入的信息。

**Comment by xiaojieonly** [comment]
> 右侧书签栏设置里面调整书签页顺序功能异常，进入设置后可以长按拖动三条杠但是最后返回后调整的书签栏顺序并没有是我调整的顺序，我尝试多次拉动书签顺序后显示的也不正常。我是用以前的db文件导入的信息。

额，我手机是能排序的。。。。大概率是因为数据不兼容导致的≡(▔﹏▔)≡

**Comment by a123456gba** [comment]
哪有什么解决办法吗

**Comment by a123456gba** [comment]
或者吧db文件可以把数据解出来自己一个一个整可以吗？

**Comment by xiaojieonly** [comment]
> 或者吧db文件可以把数据解出来自己一个一个整可以吗？

你可以在新版里边搜边添加，蛮烦是麻烦了点，但是有效是最有效的
