### ISSUE TITLE
#求助  app已经下载好的本子看不了预览图

### ISSUE THREAD

**Issue by MarkeTT0wn** [xiaojieonly/Ehviewer_CN_SXJ#580]
![Screenshot_20230518_010743_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/118434914/0d056cf9-656b-413f-a738-80f261abdb63)
如图所示，从图片位置点进去到了详情页也没有预览图，这次故障是更新了鸿蒙os3之后出现的，不知道有没有联系

**Comment by xiaojieonly** [comment]
这是本地预览图片缓存数据被系统删了，可以等后续修复，或者删了重新下载
