### ISSUE TITLE
EX里站突然变成网络错误

### ISSUE THREAD

**Issue by ShenYu-GW** [xiaojieonly/Ehviewer_CN_SXJ#581]
![Screenshot_20230518-134820992 (1)](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/121322006/230e03b2-4f31-45d5-be11-9b9e5da0c4b9)
今天打开App突然就变成这样，现在只能上EH了，EX完全进不去

**Comment by eiheiheiheihei** [comment]
我也是，ehviewer突然就上不去里站了，但在网页上登录exhentai是完全正常的

**Comment by xiaojieonly** [comment]
网不好，或者没权限，建议重新登录试试
