### ISSUE TITLE
换新版本之后依旧不显示预览

### ISSUE THREAD

**Issue by a928618778** [xiaojieonly/Ehviewer_CN_SXJ#588]
换回1.9.4.5可以显示封面，但内容预览图依旧不显示
![QQ截图20230523142754](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/134002367/e6d80c41-4ded-4813-8250-e7a629d0b6c7)
![QQ截图20230523143256](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/134002367/1710f1ce-f0a8-4c36-b41a-c0fc183e80e2)

**Comment by xiaojieonly** [comment]
网不好？，或者host没开
