### ISSUE TITLE
账号相关

### ISSUE THREAD

**Issue by jiananlu5180350** [xiaojieonly/Ehviewer_CN_SXJ#59]
刚刚（12.29  凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览

我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”

想问一下是什么原因 有没有什么解决办法

**Comment by xiaojieonly** [comment]
> 账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hip



> 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> 
> 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> 
> 想问一下是什么原因 有没有什么解决办法

1.7.6.11这版本就不能用登录功能。。。。建议换成其他版本，这版本只能看看表站，是当时因为gfw的问题拿出来救急用的。。。建议换成最新版，如果手机是安卓9以上的话

**Comment by xiaojieonly** [comment]
> > 账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hip
> 
> > 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> > 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> > 想问一下是什么原因 有没有什么解决办法
> 
> 1.7.6.11这版本就不能用登录功能。。。。建议换成其他版本，这版本只能看看表站，是当时因为gfw的问题拿出来救急用的。。。建议换成最新版，如果手机是安卓9以上的话

如果手机版本低抉择

> 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> 
> 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> 
> 想问一下是什么原因 有没有什么解决办法

如果手机版本比较低的话则建议换成1.7.6.10试试挂着梯子看。

**Comment by jiananlu5180350** [comment]
> > > 账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hip
> > 
> > 
> > > 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> > > 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> > > 想问一下是什么原因 有没有什么解决办法
> > 
> > 
> > 1.7.6.11这版本就不能用登录功能。。。。建议换成其他版本，这版本只能看看表站，是当时因为gfw的问题拿出来救急用的。。。建议换成最新版，如果手机是安卓9以上的话
> 
> 如果手机版本低抉择
> 
> > 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> > 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> > 想问一下是什么原因 有没有什么解决办法
> 
> 如果手机版本比较低的话则建议换成1.7.6.10试试挂着梯子看。

我现在是MIUI12，那我试试下个最新版的？

**Comment by xiaojieonly** [comment]
> > > > 账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hip
> > > 
> > > 
> > > > 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> > > > 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> > > > 想问一下是什么原因 有没有什么解决办法
> > > 
> > > 
> > > 1.7.6.11这版本就不能用登录功能。。。。建议换成其他版本，这版本只能看看表站，是当时因为gfw的问题拿出来救急用的。。。建议换成最新版，如果手机是安卓9以上的话
> > 
> > 
> > 如果手机版本低抉择
> > > 刚刚（12.29 凌晨12点40）原来的1.7.6版本可打开了，但是无封面预览
> > > 我将原来的那个账号通过cookie登录在大佬你的这个1.7.6.11版本登录，但是显示“little hippo”，且不能下载压缩包，点击会显示“请登录”
> > > 想问一下是什么原因 有没有什么解决办法
> > 
> > 
> > 如果手机版本比较低的话则建议换成1.7.6.10试试挂着梯子看。
> 
> 我现在是MIUI12，那我试试下个最新版的？

嗯，如果出现导入数据错误的话，可以用旧版导入数据然后一版版覆盖安装到最新版😂
