### ISSUE TITLE
浏览EX画廊的时候显示错误

### ISSUE THREAD

**Issue by 9baka99** [xiaojieonly/Ehviewer_CN_SXJ#592]
如题，浏览普通画廊的时候没有问题，可以正常显示，但是浏览ex画廊的时候就不显示任何图像，也没有错误提示
![1](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/134851839/9b204d4b-a6e3-4d29-81e1-d673819424a4)
如附件所示，我换了其他手机和模拟器都是这个问题，已经确认登陆账号

**Comment by ylu2233** [comment]
我也是这样的

**Comment by lzdacbs** [comment]
我也是

**Comment by carol37796** [comment]
昨天也發生同樣問題
後來刪掉重新載了1.9.4.8的版本就恢復正常了
暫時不敢再更新成較新版本

**Comment by 9baka99** [comment]
说来惭愧，我的问题好像解决的，似乎是cookie的问题，我用账号密码又登陆了一次就解决问题了

**Comment by 414398710** [comment]
我今天也出现这个问题了，上面的方法都试了，还是不行

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/608
E站维护，重新登录下就行
