### ISSUE TITLE
订阅栏未显示网站上设置的标签

### ISSUE THREAD

**Issue by Luomingsunhao** [xiaojieonly/Ehviewer_CN_SXJ#593]
我在手机浏览器上打开e站，把e站重新安装之后，订阅栏就显示不了网站上设置的标签了，我更改了一下标签组的命名，但是还是没有显示订阅的内容![Screenshot_20230529_152327_com.xjs.ehviewer.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/109960302/d46d971e-146d-4940-b3c6-c8de4b29c4ff)

**Comment by Luomingsunhao** [comment]
想咨询一下解决方法来着

**Comment by xiaojieonly** [comment]
app没登录吧？

**Comment by Luomingsunhao** [comment]
我登录了啊，两个账号全是只有云收藏之类的可以用，但是订阅栏啥都没有
