### ISSUE TITLE
关于6/1更新下载列表略缩图问题

### ISSUE THREAD

**Issue by FrankTaiki** [xiaojieonly/Ehviewer_CN_SXJ#596]
更新后下载列表虽然进入详情图片会出来，但把应用暂存清除后，图片又会消失，就跟更新前的问题一样，就算把暂存清除前，把资料汇出，在汇入也一样，略缩图还是无法预览，目前只剩下重新下载的方法吗

**Comment by xiaojieonly** [comment]
这问题已经修好了
