### ISSUE TITLE
紧急！新增“更新”功能问题！

### ISSUE THREAD

**Issue by xr1234n** [xiaojieonly/Ehviewer_CN_SXJ#597]
很感动作者努力制作了此功能，非常感谢你付出的努力！但这个需求在我长期的观察下发现要复杂许多。

上传者的画廊更新分几种：
1-有序更新：分为从最前开始加页，从最后开始加页。
2-无序更新：分按角色分类从中间插入式加页。
3-页面文本更新：无新加页而是修改其中某一页。

目前软件好像不能适用于上面所有情况。
已尝试更新了几个画廊，页序爆炸，请紧急停用此功能！避免悲剧发生。

**Comment by xr1234n** [comment]
彻底删除，更新乱序的画廊后，重新下只能下载前几页，后几页就显示lnvalid page，无法下载，大悲剧。
大大快用你无敌的代码想想办法😂

**Comment by xr1234n** [comment]
我这边彻底删除乱序画廊后重新下载，只能下前几页后面显示lnvalid page无法下载，悲剧

**Comment by dogenextdoor** [comment]
一键更新功能确实是方便了不需要重复下载，这边使用下来和上面描述一样。
尝试了重置缓存和已完成基础下下载也无法解决。我这边短期解决方法是阅读中每一个都点刷新可以短期解决问题。

**Comment by dogenextdoor** [comment]
体感上使用感觉是文件路径还是旧的，更新之后需要手动每个图片刷新去识别新的路径

**Comment by xiaojieonly** [comment]
是个bug，以后会修复

**Comment by Axwcm** [comment]
> 很感动作者努力制作了此功能，非常感谢你付出的努力！但这个需求在我长期的观察下发现要复杂许多。
> 
> 上传者的画廊更新分几种： 1-有序更新：分为从最前开始加页，从最后开始加页。 2-无序更新：分按角色分类从中间插入式加页。 3-页面文本更新：无新加页而是修改其中某一页。
> 
> 目前软件好像不能适用于上面所有情况。 已尝试更新了几个画廊，页序爆炸，请紧急停用此功能！避免悲剧发生。

就我下载了一百多g的经历来看，上传者的更新方式是千奇百怪的 。根本没有统一的方式。所以我对更新功能的前途比较悲观，很可能压根不存在解决这个问题的方法。因为本质上这是上传者自己排序的

**Comment by xr1234n** [comment]
有没有办法通过本地文件的哈希值等数据与网络请求中的数据进行对比选择性更新？

1、给本地想更新并下载完成的画廊，创建一个文本记录每个图片的哈希值等信息，编辑成字符串1。
2、软件向服务器发送请求或用爬虫的方式记录下新画廊的每个图片信息，编辑成字符串2。
3、在本地进行字符串1和2的对比操作，根据变化先调整已有图片序号，删除字符串2中不存在的图片，最后选择性发送请求下载没有的新图片。

（过程1需用户自主选择，因为不是所有画廊都会更新，也要提供删除图片信息记录文件的功能防止按错或画廊不在更新后文件占用空间）

以上是个人拙见，知识面太少不能给出更好的思路，还请有能力的大佬能一起探讨，帮助作者实现此功能！！

**Comment by xiaojieonly** [comment]
最新版已修，还出问题记得及时重新打开
