### ISSUE TITLE
保存搜索条件为书签时闪退

### ISSUE THREAD

**Issue by keepsmilence** [xiaojieonly/Ehviewer_CN_SXJ#6]
手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；

**Comment by xiaojieonly** [comment]
正在修改，稍等，待会就会发布修复版本

**Comment by xiaojieonly** [comment]
> 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；

正在修改，稍等，待会就会发布修复版本

**Comment by xiaojieonly** [comment]
> 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；



> > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> 
> 正在修改，稍等，待会就会发布修复版本

还在不？我正在上传

**Comment by xiaojieonly** [comment]
> 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；

你用我刚更新的版本试试

**Comment by xiaojieonly** [comment]
> 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；

大哥能回句话不？我很急，修好了你看下还闪不闪退

**Comment by iceberg2271** [comment]
> > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> 
> 大哥能回句话不？我很急，修好了你看下还闪不闪退

依旧闪退，且添加后不显示添加的内容，再次点击后无法重新开启软件，一直闪退了

**Comment by iceberg2271** [comment]
> > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> 
> 大哥能回句话不？我很急，修好了你看下还闪不闪退

并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。

**Comment by xiaojieonly** [comment]
> > > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> > 
> > 
> > 大哥能回句话不？我很急，修好了你看下还闪不闪退
> 
> 并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
> 接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。

我明白你意思了正在修复中

**Comment by xiaojieonly** [comment]
> > > > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > > > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > > > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> > > 
> > > 
> > > 大哥能回句话不？我很急，修好了你看下还闪不闪退
> > 
> > 
> > 并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
> > 接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。
> 
> 我明白你意思了正在修复中

大兄弟对不住哦，让你费心了，我马上修好，代码逻辑漏洞，很是抱歉

**Comment by xiaojieonly** [comment]
> > > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> > 
> > 
> > 大哥能回句话不？我很急，修好了你看下还闪不闪退
> 
> 并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
> 接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。

修好了，正在上传，您待会再辛苦下试试还会不会闪退👀

**Comment by xiaojieonly** [comment]
> > > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> > 
> > 
> > 大哥能回句话不？我很急，修好了你看下还闪不闪退
> 
> 并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
> 接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。

https://wws.lanzous.com/irX76inru2f
密码:5c21

**Comment by iceberg2271** [comment]
> > > > 手机xiaomi k30，安装最新版本，机子还安装过去年的原版（没卸载）；
> > > > 1、搜索后，保存为书签时，直接闪退，重新打开，书签没有保存成功；
> > > > 2、尝试从原版导出配置文件（为了还原书签和本地收藏夹和下载历史），导入你的版本，也闪退，且无法再打开；
> > > 
> > > 
> > > 大哥能回句话不？我很急，修好了你看下还闪不闪退
> > 
> > 
> > 并且出现恶性bug，添加书签后，不会闪退，但是书签栏却不显示添加内容，书签栏多出一行空白。。。点击空白闪退。。
> > 接下来软件再也无法进入。。。只能删除所有数据。重启系统都无法开启。
> 
> https://wws.lanzous.com/irX76inru2f
> 密码:5c21

ok了。没有问题了

**Comment by keepsmilence** [comment]
抱歉，这几天都没上来……刚装上，已可用，非常感谢；
