### ISSUE TITLE
右侧书签栏设置顺序功能确实有异常

### ISSUE THREAD

**Issue by a123456gba** [xiaojieonly/Ehviewer_CN_SXJ#60]
卸载后重新下载安装，没有选择导入数据，选择检测已下载项目，并且自己一个一个的自己加入标签，然后调整顺序，还是有调整顺序错误的问题发生。我的标签确实挺多的，有50个左右，有可能是过多标签才会出现的bug。

**Comment by xiaojieonly** [comment]
> 卸载后重新下载安装，没有选择导入数据，选择检测已下载项目，并且自己一个一个的自己加入标签，然后调整顺序，还是有调整顺序错误的问题发生。我的标签确实挺多的，有50个左右，有可能是过多标签才会出现的bug。

软件什么版本，手机什么安卓版本？

**Comment by xiaojieonly** [comment]
> 卸载后重新下载安装，没有选择导入数据，选择检测已下载项目，并且自己一个一个的自己加入标签，然后调整顺序，还是有调整顺序错误的问题发生。我的标签确实挺多的，有50个左右，有可能是过多标签才会出现的bug。

我研究下

**Comment by xiaojieonly** [comment]
已修，但是旧数据需要删除后重新导入
