### ISSUE TITLE
標籤遮避失效了

### ISSUE THREAD

**Issue by 661266** [xiaojieonly/Ehviewer_CN_SXJ#603]
標籤遮避失效了 ｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡

**Comment by xiaojieonly** [comment]
多半是画廊还没打上被屏蔽的标签

**Comment by 661266** [comment]
了解！ 感謝大大的回覆

SXJ_LonelyDog ***@***.***> 於 2023年6月15日 週四 上午10:55 寫道：
