### ISSUE TITLE
进入eh和ex都没问题，但都不显示图片

### ISSUE THREAD

**Issue by 2333tracy** [xiaojieonly/Ehviewer_CN_SXJ#605]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58852317/2d2d8daf-2d0a-4577-bc65-3e7e6e211eb1)
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58852317/f6240e17-2eb5-4771-bb03-a6709a79a21d)

**Comment by 2333tracy** [comment]
网页版是正常显示，eh是最新版，挂了梯子

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/608
E站维护，重新登录下就行
