### ISSUE TITLE
站域使用ex會出現404 而前段時間以及使用e皆不會

### ISSUE THREAD

**Issue by wsddaa** [xiaojieonly/Ehviewer_CN_SXJ#606]
之前登入都沒有問題，可以正常看到ex內的內容，不過今天使用時ex進入後顯示404安卓圖標，切換成e又正常顯示，想請問。

**Comment by admiralgut** [comment]
同问题，网页可以进里站，app切到ex无法正常显示，e站正常

**Comment by shaobo3350** [comment]
![16863287264598196436420759256386](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/99185326/e8ceb557-c9e8-45a9-a69c-3a532e8f8721)

简单来说获取不到igenous了

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/608
E站维护，重新登录下就行
