### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by LCGIZJ** [xiaojieonly/Ehviewer_CN_SXJ#607]
![Screenshot_2023-06-10-03-24-32-400_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/28826284/f1351b50-8b6c-44f0-980f-30050e44a2d7)
eh没问题，切换ex就成这样了

**Comment by shaobo3350** [comment]
简单来说获取不到igenous了

**Comment by BreakFaith01** [comment]
没有，我也是EX崩了。
看到有人一样就安心了，看起来我只能打开下载的看了。

**Comment by BreakFaith01** [comment]
> 没有，我两个都崩溃了。

看到大家和我一样我就安心了。

**Comment by SerikaG** [comment]
设置-EH-身份信息，检查igenous是否显示为mystery
假如是，退出并重新登录，登录后EX即可正常加载了
不知道为什么突然把igenous清除了，我都忘了账号密码一直靠的cookie登录，还好老绿E没卸从里面复制出来的

**Comment by BreakFaith01** [comment]
哦，谢谢，完成了。




10086K
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月10日(星期六) 中午12:55
***@***.***&gt;;
抄送:&nbsp;"♛Break ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] 这是什么情况？ (Issue #607)





 
设置-EH-身份信息，检查igenous是否显示为mystery
 假如是，退出并重新登录，登录后EX即可正常加载了
 不知道为什么突然把igenous清除了，我都忘了账号密码一直靠的cookie登录，还好老绿E没卸从里面复制出来的

**Comment by jojo1732061** [comment]
今天不知道为什么进不了里站了，到底是更新的原因还是其他的

**Comment by Sakura1Hana** [comment]
这个能用其他方式解决吗 我账号密码忘了只能用cookie登陆

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/608
E站维护，重新登录下就行
