### ISSUE TITLE
[BUG]网络错误

### ISSUE THREAD

**Issue by 514iloveu** [xiaojieonly/Ehviewer_CN_SXJ#61]
设置里的内置host等项目全都勾上了但是没有用，依旧显示网络错误，望修复
不过谢谢作者的维护，2021年快乐

**Comment by 514iloveu** [comment]
怎么上传图片？
我想上传图片可它每次都打开我的相机而不是相册

**Comment by HourGlassZ** [comment]
> 怎么上传图片？
> 我想上传图片可它每次都打开我的相机而不是相册

使用 Github Android Client

**Comment by 514iloveu** [comment]
> > 怎么上传图片？
> > 我想上传图片可它每次都打开我的相机而不是相册
> 
> 使用 Github Android Client

感谢
不过我没有谷歌三件套貌似用不了的样子
我看看能不能找台机子用电脑网页传
再次感谢您的回复
