### ISSUE TITLE
更新功能很可能不存在完美解决方法

### ISSUE THREAD

**Issue by Axwcm** [xiaojieonly/Ehviewer_CN_SXJ#612]
就我下载了一百多g的经历来看，上传者的更新方式是千奇百怪的 。根本没有统一的方式。所以我对更新功能的前途比较悲观，很可能压根不存在解决这个问题的方法。因为本质上这是上传者自己排序的

**Comment by xiaojieonly** [comment]
添加了新的更新逻辑，现在可以自己选择下载为新画廊还是覆盖下载
