### ISSUE TITLE
此反馈是一个提醒，bilibili uid 10028983337 公开传播了您的软件，请多加注意

### ISSUE THREAD

**Issue by ogasism** [xiaojieonly/Ehviewer_CN_SXJ#613]
[https://postimg.cc/CZCPm3V4](url)
[[https://postimg.cc/r0QhL5s0](url)
[[https://postimg.cc/r0QhL5s0](url)

**Comment by xiaojieonly** [comment]
我看看去

**Comment by xiaojieonly** [comment]
没找诶

**Comment by ogasism** [comment]
> 没找诶

抱歉，看到的有点晚。请看这个链接https://www.bilibili.com/video/BV1Xh4y1G7AP/
后来我也想了下，不过仅凭那个头像和该视频的置顶是否能界定为宣传

**Comment by xiaojieonly** [comment]
我私信说了下，具体看人家怎么做了。。。

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/73fd41c2-d893-41ed-930a-d4e016d0efcf)

**Comment by xiaojieonly** [comment]
不过我觉得其实还好，哔站上搜ehviewer东西挺多的。。。

**Comment by xiaojieonly** [comment]
哎~~~

**Comment by UjuiUjuMandan** [comment]
宣传又如何呢？跑到各个EhViewer仓库里发提醒有必要吗。

而且，你发图的方式是错的。

况且他的头像既不是本仓库的EhViewer也不是隔壁彩e，而是早就不维护了的Nekoinverter的版本。你是否发错地方了。

**Comment by ogasism** [comment]
> 宣传又如何呢？跑到各个EhViewer仓库里发提醒有必要吗。
> 
> 而且，你发图的方式是错的。
> 
> 况且他的头像既不是本仓库的EhViewer也不是隔壁彩e，而是早就不维护了的Nekoinverter的版本。你是否发错地方了。

哈哈，只要有人举报，网安顺着他的线索找到这里不管彩e还是绿e的维护者统统都得去蹲局子。

感谢你的反馈，下次我会去学下github的机制。

另外，你只知道他头像是Nekoinverter的版本，怎么确定他发的是不是其他别人的版本。我本意是提醒维护者并强制更新；不定期加密，加设这种机制。

还有GW的机制更新的越来越频繁了，你又是否感受这其中的驱动力。

**Comment by UjuiUjuMandan** [comment]
> 只要有人举报，网安顺着他的线索找到这里不管彩e还是绿e的维护者统统都得去蹲局子。

这仓库是公开的，APK文件也是所有人都能下载的，在Google里搜索能得到一大堆指向本仓库的结果，更别提还有好多倒卖App的。

EhViewer 存在也不是一天两天了，知道的人也很多，根本就不需要有什么人“公开传播”。过去没被封之前百度“EhViewer”吧发布它的人更是比比皆是。

早就引起所谓“网安”注意了好吗。

而这个人做了什么呢？他甚至连”EhViewer“这个关键字都没提。

> 强制更新；不定期加密，加设这种机制。

我觉得环境还没有差到开发者需要这么做，过去也没这么做过。按照你的逻辑下去，最好的方法是直接删除本仓库，也不发布APK，就自己用自己的。

> 还有GW的机制更新的越来越频繁了，你又是否感受这其中的驱动力。

是GFW。并不频繁，差不多2年才会有所行动一次。

---

```
![注释文本](https://i.postimg.cc/pd4wXvG3/image1.png)
![](https://i.postimg.cc/zv14Kj1j/image2.png)
```

![注释文本](https://i.postimg.cc/pd4wXvG3/image1.png)
![](https://i.postimg.cc/zv14Kj1j/image2.png)

**Comment by xiaojieonly** [comment]
没必要争论什么，那些卖app的人赚到的钱从来没有一分钱进到我的口袋里
