### ISSUE TITLE
最新版手机版会吞已下载的文件

### ISSUE THREAD

**Issue by bb1227** [xiaojieonly/Ehviewer_CN_SXJ#614]
手机 小米13miui最新版本
观看几个已下载的作品后 如果这时候下载新作品的话 会吞掉刚刚看过的部分作品 解决方法就是把吞掉的作品详细点开 把已下载点一下移除 然后再添加 就直接出现在下载目录里面 本质上好像是新版本的检索这一块有问题

**Comment by bb1227** [comment]
我是在看已下载的作品后 点开作者主页下载新作品 然后回去下载的目录里发现刚刚看过的作品直接消失了  就是没法检索 手机里的本地文件里是一直存在的 只是新版e站好像检索不到 我刚刚回退到4.9看了下好像没这个问题

**Comment by xiaojieonly** [comment]
哈？权限啥的都给了吗？

**Comment by aigeexist** [comment]
不是吞了，被挪到了列表的最末尾

**Comment by xiaojieonly** [comment]
楼上正解

**Comment by rex10189** [comment]
我很像也遇到了这个问题类似的情况，但应该不是被挪到了列表最末尾。我在画廊搜索里搜关键词其他本都会显示，但消失了的这个不会显示，如果是最末尾应该能搜出来。
