### ISSUE TITLE
![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

### ISSUE THREAD

**Issue by niganmahaihaieiyo** [xiaojieonly/Ehviewer_CN_SXJ#616]
![Screenshot_2023-06-16-04-56-47-795_io github nekoinverter ehviewer](https://user-images.githubusercontent.com/136757207/246249051-fb74eb65-c5a0-49a7-9b0b-4018c9b133df.jpg)
              ![Screenshot_2021-11-01-17-04-00-963_com xjs ehview](https://user-images.githubusercontent.com/49278135/145570174-ded5f42e-00bc-425a-8da0-a57068139f4e.jpg)

_Originally posted by @xiaojieonly in https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/150#issuecomment-991888109_

**Comment by xiaojieonly** [comment]
表站ip被封了，要挂梯子登录
