### ISSUE TITLE
[bug]应用内访问网页相关

### ISSUE THREAD

**Issue by 1235789gzy1** [xiaojieonly/Ehviewer_CN_SXJ#62]
1.7.7.1内eh网站设置，我的标签这两项依旧无法访问，挂了梯子也上不去，可能因为cookie没有挂上？(因为一些特殊原因，我的帐号登录ex不会出现igneous的值，需要我自己手动输入)

**Comment by 1235789gzy1** [comment]
![Screenshot_20210101-214551](https://user-images.githubusercontent.com/52618207/103439782-ec5a6400-4c7a-11eb-9c4b-14826b76ebc9.jpg)
![Screenshot_20210101-214545](https://user-images.githubusercontent.com/52618207/103439786-f54b3580-4c7a-11eb-99c9-accd79d33f7e.jpg)

**Comment by xiaojieonly** [comment]
> 1.7.7.1内eh网站设置，我的标签这两项依旧无法访问，挂了梯子也上不去，可能因为cookie没有挂上？(因为一些特殊原因，我的帐号登录ex不会出现igneous的值，需要我自己手动输入)

换成e-hentai再去打开，exhentai打不开属实正常。

**Comment by xiaojieonly** [comment]
> 1.7.7.1内eh网站设置，我的标签这两项依旧无法访问，挂了梯子也上不去，可能因为cookie没有挂上？(因为一些特殊原因，我的帐号登录ex不会出现igneous的值，需要我自己手动输入)

里站和表站的设置是通用的，表站什么设置，里站也是。。。
