### ISSUE TITLE
打不开里站exhentai,表站正常

### ISSUE THREAD

**Issue by thekingwei** [xiaojieonly/Ehviewer_CN_SXJ#620]
今天突然这样，更新了也不行，帐号重登也不行🥲，还换了不少梯子节点
不过暂时影响不大，希望作者大大有空研究下

**Comment by xiaojieonly** [comment]
cookie检查下

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/623
移步至
