### ISSUE TITLE
使用图片搜索后打开APP就是流泪机器人

### ISSUE THREAD

**Issue by hbdgq** [xiaojieonly/Ehviewer_CN_SXJ#621]
原本一切正常，使用图片搜索功能后显示解析失败，然后打开APP就是流泪机器人。重新登录和更新APP都没能恢复正常，高级设置里的选项也都开关过。网页端一切正常。

**Comment by soda882** [comment]
我这也是 一开始还正常 突然刷不出结果 点进画廊就流泪机器人 退出重登也解决不了

**Comment by qq921040493** [comment]
我这也是，刚进主页还有，刷新一下就sadpanda了

**Comment by hdjsheifnjs** [comment]
同样的情况，突然就流泪机器人没反应，重新登陆好了一下又变回流泪机器人

**Comment by MrYuChen233** [comment]
昨天晚上10点多还能直连连接，今天早上开始就一直流泪机器人了

**Comment by xiaojieonly** [comment]
被高墙了表站没法裸连了

**Comment by hbdgq** [comment]
已恢复
