### ISSUE TITLE
退出登录以后重启自动跳转主页

### ISSUE THREAD

**Issue by huakaiyuan** [xiaojieonly/Ehviewer_CN_SXJ#622]
miui13 今天上去发现一直没内容 然后看cookie发现账号失效想重新登录  点完之后重启应用登录界面就闪了一瞬间就跳转主页了 求帮助

**Comment by huakaiyuan** [comment]
Uploading Screenrecorder-2023-06-18-10-30-20-594.mp4…

**Comment by handysome6** [comment]
same

**Comment by xiaoyi159** [comment]
我也是一样啊，退出登陆再打开APP直接跳过了登录界面，只能先换彩e用用

**Comment by xiaoyi159** [comment]
艹，我找到原因了，是李跳跳！跳过了登录😂

**Comment by xiaoyi159** [comment]
> miui13 今天上去发现一直没内容 然后看cookie发现账号失效想重新登录 点完之后重启应用登录界面就闪了一瞬间就跳转主页了 求帮助

艹，我的找到原因了，是李跳跳！跳过了登录😂不知道你是不是这样

**Comment by xiaojieonly** [comment]
登录页被什么软件给屏蔽了

**Comment by ypq123456789** [comment]
> 

就是李跳跳的锅，我服了，万万没想到

**Comment by bb1227** [comment]
太有才了 问题搜着搜着就被网友解决了
