### ISSUE TITLE
里站打不开，表站正常。刚打开的时候里站也是正常的，但往下刷的时候就没办法显示。刷新一下就流泪机器人了，表站倒是很正常

### ISSUE THREAD

**Issue by Laxwei** [xiaojieonly/Ehviewer_CN_SXJ#623]

**Comment by SiberiaHusky** [comment]
相同

**Comment by der299** [comment]
我也，还以为号废了

**Comment by zs47** [comment]
我表站里站都打不开，麻

**Comment by Horizon3690** [comment]
> 

我的情况跟你一样，局域网流量都换了一遍都显示超时

**Comment by shenqiyali** [comment]
科学上网可以暂时解决

**Comment by Laxwei** [comment]
> 科学上网可以暂时解决

就是科学上网了我才能在这里发布议题。。。

**Comment by KyaruSAMA** [comment]
请尝试重新登录，并检查自己的身份cookie

**Comment by Horizon3690** [comment]
> 请尝试重新登录，并检查自己的身份cookie

你好，请问检查身份cookie的具体方式是什么，多谢

**Comment by KyaruSAMA** [comment]
> > 请尝试重新登录，并检查自己的身份cookie
> 
> 你好，请问检查身份cookie的具体方式是什么，多谢
设置→EH→身份cookie→查看ignore是否为mystery，是则重新登陆

**Comment by KyaruSAMA** [comment]
> > 请尝试重新登录，并检查自己的身份cookie
> 
> 你好，请问检查身份cookie的具体方式是什么，多谢
设置→EH→身份cookie→查看ignore是否为mystery，是则重新登陆。目前已知可能是因为大陆IP被墙

**Comment by shenqiyali** [comment]
设置→EH→身份cookie→查看ignore是否为mystery，是则重新登陆。目前已知可能是因为大陆IP被墙

**Comment by KyaruSAMA** [comment]
> > 
> 
> 我的情况跟你一样，局域网流量都换了一遍都显示超时

或者你可以试试，设置里的锁定cookieignore，我没试过，理论上应该可行

**Comment by Horizon3690** [comment]
> 或者你可以试试，设置里的锁定cookieignore，我没试过，理论上应该可行
好像没什么用，我这里仍显示超时😶

**Comment by xiaojieonly** [comment]
开梯子

**Comment by xiaojieonly** [comment]
表站被高墙了

**Comment by Laxwei** [comment]
emmm，我现在重新登陆解决了

**Comment by FrederickVonMagdeburg** [comment]
> 开梯子

开了，但是显示解析失败

**Comment by akinokoika** [comment]
来自管理员的回复：Looks like there were some network issues but as far as I can see everything is currently running normally. Any other issues would be unrelated

**Comment by akinokoika** [comment]
> 设置→EH→身份cookie→查看ignore是否为mystery，是则重新登陆。目前已知可能是因为大陆IP被墙

经过测试，你的方法是正确的，而且如果拥有合理的饼干是可以和以前一样的方式进行访问，即，无需且不能使用梯子

**Comment by yifan19988888** [comment]
亲测！为了给大家回复特意注册的账号！
如果设置→EH→身份cookie→查看ignore是否为mystery
退出登录之后，使用账号密码重新登陆，重复，使用 账号 密码 重新登录，不要用带mystery的cookie登录，就可以了

**Comment by hongren1** [comment]
我重新登录也不行，看里站还是解析失败，而且重新登录后igneous从mystery变成null了。

**Comment by LHR555** [comment]
重新登录后mystery变成Null，但仍然里站显示解析失败，域名前置也关掉了

**Comment by xiaojieonly** [comment]
> 

你这mystery变成null能进里站才怪

**Comment by 3274951799** [comment]
> 科学上网可以暂时解决

挂梯子之后没法下载，一直显示的下载额度用完

**Comment by LHR555** [comment]
> > 
> 
> 你这mystery变成null能进里站才怪

那不是飞了，我网页登录查看cookie，igneous值仍然为mystery，我是彻底被ban了吗

**Comment by yongkangz428** [comment]
上面那个老哥，退出登录然后找一个梯子挂一个美欧节点，然后选择网页登录，我也是里站用不了，然后试了一下网页登录然后就能用了，老哥，你可以试试

**Comment by yongkangz428** [comment]
上面那个老哥你可以试试，退出登录，找一个加速器，挂一个美欧节点.选择网页登录你可以试试这个方法，我之前里站也是看不了我用这个方法就好了，老哥你可以试试

**Comment by yongkangz428** [comment]
上面那个老哥你可以试试，退出登录，找一个加速器，挂一个美欧节点然后再进软件选择网页登录你可以试试这个方法，我之前里站也是看不了我用这个方法就好了，老哥你可以试试

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/637

**Comment by puoiuouo** [comment]
> 上面那个老哥你可以试试，退出登录，找一个加速器，挂一个美欧节点然后再进软件选择网页登录你可以试试这个方法，我之前里站也是看不了我用这个方法就好了，老哥你可以试试

我试过了不行，挂梯子就被ban，裸连就进不去，人麻了

**Comment by yongkangz428** [comment]
> 

 @老哥你试试这个叫Windscribe的梯子，这个梯子用的人少，我用这个上里站都没被封过，就是连接时候，确实有时候得试好几个节点才能连上，这个梯子不花钱也可以用，每个月有10g流量

**Comment by yongkangz428** [comment]
@

> > 上面那个老哥你可以试试，退出登录，找一个加速器，挂一个美欧节点然后再进软件选择网页登录你可以试试这个方法，我之前里站也是看不了我用这个方法就好了，老哥你可以试试
> 
> 我试过了不行，挂梯子就被ban，裸连就进不去，人麻了

老哥你试试这个叫Windscribe的梯子，这个梯子用的人少，我用这个上里站都没被封过，就是连接时候，确实有时候得试好几个节点才能连上，这个梯子不花钱也可以用，每个月有10g流量

**Comment by yongkangz428** [comment]
@LHR555

> 那个老哥你可以试试，退出登录，找一个加速器，挂一个美欧节点然后再进软件选择网页登录你可以试试这个方法，我之前里站也是看不了我用这个方法就好了，老哥你可以试试，如果你挂梯子不行，你可以老哥你试试这个叫Windscribe的梯子，这个梯子用的人少，我用这个上里站都没被封过，就是连接时候，确实有时候得试好几个节点才能连上，这个梯子不花钱也可以用，每个月有10g流量

**Comment by yongkangz428** [comment]
@puoiuouo 
老哥你试试这个叫Windscribe的梯子，这个梯子用的人少，我用这个上里站都没被封过，就是连接时候，确实有时候得试好几个节点才能连上，这个梯子不花钱也可以用，每个月有10g流量

**Comment by xiaojieonly** [comment]
移步 https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/637
