### ISSUE TITLE
快速浏览画廊闪退

### ISSUE THREAD

**Issue by 22hello** [xiaojieonly/Ehviewer_CN_SXJ#626]
只要点进去一个画册，当这个画册的图片特别多时，快速滑动再点进去一个详细图片必然闪退，并且在画册快速滑动时有不加载图片的文图

**Comment by xiaojieonly** [comment]
是华为手机吗？是的话就滑慢点

**Comment by 22hello** [comment]
不是，小米

**Comment by 22hello** [comment]
主要是慢的话也有几率闪退

**Comment by yyn12345** [comment]
![Screenshot_20230619_160810](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136992458/720f1544-ef34-4ef0-be47-62112a2034d3)
有谁知道这是怎么回事刷新几遍都是这样，一直说超时

**Comment by xiaojieonly** [comment]
挂梯子

**Comment by xiaojieonly** [comment]
> ![Screenshot_20230619_160810](https://user-images.githubusercontent.com/136992458/246767656-720f1544-ef34-4ef0-be47-62112a2034d3.jpg) 有谁知道这是怎么回事刷新几遍都是这样，一直说超时

挂梯子

**Comment by nanyijueze** [comment]
> 子

为什么我挂vpn会封禁ip？如果知道怎么解决可以说一下吗？

**Comment by xiaojieonly** [comment]
最新版试试？没问题的话我把这个issue关了，如果还出问题记得重新打开
