### ISSUE TITLE
不知道为什么这样

### ISSUE THREAD

**Issue by 2026j** [xiaojieonly/Ehviewer_CN_SXJ#628]
![Screenshot_20230619_000216](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136985981/37ad5b74-49a2-4905-8c68-25da4311f0cb)
怎么回事

**Comment by heihuadeyangang** [comment]
至少好过我这什么都不显示的sad android
![Uploading Screenshot_2023-06-19-00-47-27-007_com.xjs.ehviewer.jpg…]()

**Comment by heihuadeyangang** [comment]
至少好过我这什么都不显示的sad android

**Comment by FUSANGDAHONGHUA** [comment]
大哥你vpn所代理的地区被禁了，
换其他的地区

**Comment by xiaojieonly** [comment]
换节点
