### ISSUE TITLE
挂梯子是未知主机，无法操作，但是不挂梯子是sad Android，能刷新但是没用。

### ISSUE THREAD

**Issue by heihuadeyangang** [xiaojieonly/Ehviewer_CN_SXJ#629]
大佬，有救吗？
![Screenshot_2023-06-19-00-52-18-186_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136953657/0dcd5dbf-f6ba-4017-aaec-b1131ff27f7e)
![Screenshot_2023-06-19-00-47-27-007_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136953657/2c184ac6-617e-47dc-bc0f-20fdca1ab6c7)

**Comment by SongZhiDan** [comment]
打开梯子，关闭域名前置和安全dns，退出登录，使用账户密码重登，实测梯子正常可以看

**Comment by heihuadeyangang** [comment]
谢谢，表站上去了但是里站解析失败了，不过好歹能用

**Comment by LHR555** [comment]
和我一样，我里站进不去了，而且别人用我号测试APP和网页我都不能进里站，但是我用别人号APP也进不了里站，我难道账号加上手机一起被扬了？

**Comment by mabanvaran** [comment]
开梯子能看eh看不了ex，悲

**Comment by xiaojieonly** [comment]
检查cookie

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/623
请见此issue
