### ISSUE TITLE
里站上不去

### ISSUE THREAD

**Issue by huajiworld** [xiaojieonly/Ehviewer_CN_SXJ#63]
代理方式是系统代理，内置hosts，安全DNS，域名前置都开了，梯子也挂了，自定义hosts一个也没有，还是上不去里站，请作者大大帮忙解决一下这个问题，拜托了

**Comment by xiaojieonly** [comment]
把内置host关了，安全DNS，域名前置都开着，然后挂梯子试试如果连上里站了建议关了梯子裸连，大部分梯子都是共享ip很容易就会被封ip，建议小心为上

**Comment by huajiworld** [comment]
好的，谢谢作者大大

**Comment by huajiworld** [comment]
还是上不去啊，都按照你说的做了😭

**Comment by xiaojieonly** [comment]
额，我现在电信网裸连能上。。。。实在不行就先表站凑合下呗，除了萝莉外里站有的表站大部分都有其实，（个人不怎么喜欢萝莉，看着有种负罪感。。。。）

**Comment by huajiworld** [comment]
好吧，那还是谢谢作者你了

**Comment by xiaojieonly** [comment]
> 好吧，那还是谢谢作者你了

没事，网络问题真不是我想解决就能解决的，我只能是尽全力满足大部分人的需要，而且每个人的网络环境压根没办法统一，这方面解决最有效的办法其实还是用vpn，毕竟gfw不是吃素的，而且我从软件代码层能做的优化其实很有限o(￣┰￣*)ゞ；之后一旦又优化的好方法我会第一时间进行优化的。
