### ISSUE TITLE
有大佬知道是怎么回事吗

### ISSUE THREAD

**Issue by yyn12345** [xiaojieonly/Ehviewer_CN_SXJ#631]
![Screenshot_20230619_160810](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/136992458/da55ca53-5cf7-4cbf-94ef-b1422ecf385a)
有谁知道这是怎么回事刷新了几遍都说超时，一直在加载等了半天又说超时。

**Comment by xiaojieonly** [comment]
挂梯子，还是没用就检查下cookie

**Comment by pzj1122** [comment]
大佬挂梯子没用，如何检查cookie？

**Comment by yyn12345** [comment]
> 挂梯子，还是没用就检查下cookie
请问梯子是什么怎么弄 我没有cookie一直都用的是游客
