### ISSUE TITLE
有大佬知道怎么搞吗？挂梯子也没用

### ISSUE THREAD

**Issue by pzj1122** [xiaojieonly/Ehviewer_CN_SXJ#633]
![Screenshot_2023-06-19-19-08-49-68_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137065047/bb7ac709-2e4b-45c8-8767-9e402fa1d7f8)

**Comment by yyn12345** [comment]
请问梯子是什么该怎么弄

**Comment by pzj1122** [comment]
> 



> 请问梯子是什么该怎么弄是加速器

**Comment by pzj1122** [comment]
> 请问梯子是什么该怎么弄

加速器

**Comment by shyzmx** [comment]
怎么搞

**Comment by blblfs** [comment]
这好像是选了ex站但没有ex访问权限的界面

**Comment by xiaojieonly** [comment]
楼上说得对
