### ISSUE TITLE
从旧手机导出数据到新手机导入数据，下载数据没有一起导入

### ISSUE THREAD

**Issue by 2333tracy** [xiaojieonly/Ehviewer_CN_SXJ#634]
两个手机都是最新版，相同下载位置
其他数据比如快速搜索数据之类是正常导入的
不知道是不是旧手机画廊数量过多导致（7000+）
下载数据指下载的画廊，图片内容没法一起导入这我知道

**Comment by xiaojieonly** [comment]
以后数据库传导我会进行重构

**Comment by 2333tracy** [comment]
> 以后数据库传导我会进行重构

能否增加一个画廊检测功能？我把原来的画廊数据复制到了新手机，但在下载列表中并没有出现
