### ISSUE TITLE
表站一直在加载，就是看不了

### ISSUE THREAD

**Issue by 11985623** [xiaojieonly/Ehviewer_CN_SXJ#64]
本来1.7.6版本还可以用移动看，更新最新版后用移动网和wifi都看不了。
求解

**Comment by xiaojieonly** [comment]
> 本来1.7.6版本还可以用移动看，更新最新版后用移动网和wifi都看不了。
> 求解

最新版安卓9一下用不了，你安卓几？内置host内置dns和域名前置都开了没？

**Comment by 11985623** [comment]
10  都开了

**Comment by xiaojieonly** [comment]
> 10 都开了

额。。。。我用的电信网，按道理电信网和联通网都可以看来着。实在不行的话就只能挂梯子了😥
