### ISSUE TITLE
解析失败，但并非网络问题

### ISSUE THREAD

**Issue by LinZecheng1** [xiaojieonly/Ehviewer_CN_SXJ#649]
设备型号：荣耀X30i
安卓版本：Android12

我的设备及网络，在1.9.5.1的host失效前，在裸连的情况下，无任何问题
但在1.9.5.2版本更新后，在裸连的情况下便会显示解析失败
![Screenshot_20230623_095922](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137463783/a637cf6a-d7f8-4fd0-992f-1e922dd5b49a)

任何设置均未更改，我的网络设置也无任何变更
![Screenshot_20230623_095325](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137463783/55e24c3f-650b-472b-af19-015e4e5bb8cf)

我尝试过重新安装软件、多次重启软件、多次重启手机、多次重连网络或换网络，均无任何变化
但不知为何，我的历史记录却还能刷新出封面图
![Screenshot_20230623_100233](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137463783/088f9f03-72b9-4de8-b538-12f640f5a123)

**Comment by LinZecheng1** [comment]
？
![Screenshot_20230623_110434](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137463783/ed3d6a7a-13f8-4ed4-99a5-4ceafa13cc97)
怎么又变网路错误了嘞？
我不理解，我不明白，我不懂啊

**Comment by Qinlex479** [comment]
表站进不去可以看看作者最新公告，里站进不去可以看看这个https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/637

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ#readme

**Comment by LinZecheng1** [comment]
额...这个问题已经得到解决，因不明原因，我近期重新安装后，他能用了...

**Comment by LinZecheng1** [comment]
@xiaojieonly 我的网络依旧没有问题，但问题已经被解决，我已经能正常使用
我不知道是不是您解决的，但还是谢谢您
