### ISSUE TITLE
关于ehviewer1.9.5.2版本反馈

### ISSUE THREAD

**Issue by zd201108** [xiaojieonly/Ehviewer_CN_SXJ#650]
使用华为和荣耀手机裸连时：1.9.5.2之前的版本，裸线显示超时或一直转圈，挂梯子立马ban ip；1.9.5.2版本，裸连显示解析失败，关闭内置exhentai host.txt后仍然裸连无法解析，但挂梯子后，关闭或开启内置exhetai host.txt都可正常访问。

**Comment by shyzmx** [comment]
求大佬教如何挂梯子

**Comment by zd201108** [comment]
我用的是小火箭和猎豹。

**Comment by shyzmx** [comment]
谢谢大佬，就只要下载后运行就行了吗

**Comment by xiaojieonly** [comment]
gfw墙变高了，非我所愿，建议使用自定义host
