### ISSUE TITLE
问里站与表站的区别及如何加入里站

### ISSUE THREAD

**Issue by jiangziwan** [xiaojieonly/Ehviewer_CN_SXJ#655]
刚刚接触，但是非常喜欢这个软件，看了一些问题发现很多里站与表站，求讲解什么是里站？里站与表站的区别以及对如何加入里站？🙏🙏

**Comment by xiaojieonly** [comment]
google一下你就知道
出门右转www.google.com

**Comment by jiangziwan** [comment]
> google一下你就知道 出门右转www.google.com

现在我都懂了那么，最后是不是只要在捐赠里捐20美元也就是150RMB就可以将软件直接升级成里站，嫌麻烦可以直接回是或否

**Comment by jiangziwan** [comment]
> google一下你就知道 出门右转www.google.com

那在软件捐赠里捐150RMB就能直接换里站？
