### ISSUE TITLE
进不去啊，一直都是流泪机器人，挂了梯子也进不去

### ISSUE THREAD

**Issue by WWH2002** [xiaojieonly/Ehviewer_CN_SXJ#657]
我是小米10s，之前可以进去，只是偶尔进不去，进不去的时候挂个梯子也能进去了。但现在是完全进不去，挂了梯子也进不去，不挂也进不去一直显示解析错误，挂上梯子就显示页面无内容

**Comment by Borondir-Udalraph** [comment]
app重新登录试试

**Comment by xiaojieonly** [comment]
楼上正解，记得换成表站，挂了梯子进不去，多半是里站没权限，只能看表站
