### ISSUE TITLE
能不能麻烦将上版本的host分享一下 

### ISSUE THREAD

**Issue by zhentaisama** [xiaojieonly/Ehviewer_CN_SXJ#658]
这版本改了反而加载很慢或者超时了 以前还能加载的

**Comment by MeteorFn** [comment]
把進階設定內的域名前置關閉試試

**Comment by zhentaisama** [comment]
> 

关了就超时了

**Comment by zhentaisama** [comment]
> 把進階設定內的域名前置關閉試試

关了就超时了

**Comment by MeteorFn** [comment]
> > 把進階設定內的域名前置關閉試試
> 
> 关了就超时了

我看你在另一篇 issue 也有回，不過 1.9.5.2 的 內置 host.txt 與 exhentai 內置 host.txt 設定應該已經整合好可用的 host 了，如果你要用之前的版本手動添加 host 的話 repo 主頁的圖片中有 host 的資訊

**Comment by xiaojieonly** [comment]
代码上传记录里有
`
       Map<String, List<InetAddress>> map = new HashMap<>();
        if (Settings.getBuiltInHosts()){
            put(map, "e-hentai.org",  "104.20.135.21","104.20.134.21","172.67.0.127","104.20.26.25","178.162.139.18");
            put(map, "repo.e-hentai.org", "94.100.28.57", "94.100.29.73");
            put(map, "forums.e-hentai.org", "94.100.18.243");
            put(map, "ehgt.org", "37.48.89.44", "81.171.10.48", "178.162.139.24", "178.162.140.212"
                    , "2001:1af8:4700:a062:8::47de", "2001:1af8:4700:a062:9::47de", "2001:1af8:4700:a0c9:4::47de", "2001:1af8:4700:a0c9:3::47de");
            put(map, "gt0.ehgt.org", "37.48.89.44", "81.171.10.48", "178.162.139.24", "178.162.140.212"
                    , "2001:1af8:4700:a062:8::47de", "2001:1af8:4700:a062:9::47de", "2001:1af8:4700:a0c9:4::47de", "2001:1af8:4700:a0c9:3::47de");
            put(map, "gt1.ehgt.org", "37.48.89.44", "81.171.10.48", "178.162.139.24", "178.162.140.212"
                    , "2001:1af8:4700:a062:8::47de", "2001:1af8:4700:a062:9::47de", "2001:1af8:4700:a0c9:4::47de", "2001:1af8:4700:a0c9:3::47de");
            put(map, "gt2.ehgt.org", "37.48.89.44", "81.171.10.48", "178.162.139.24", "178.162.140.212"
                    , "2001:1af8:4700:a062:8::47de", "2001:1af8:4700:a062:9::47de", "2001:1af8:4700:a0c9:4::47de", "2001:1af8:4700:a0c9:3::47de");
            put(map, "gt3.ehgt.org", "37.48.89.44", "81.171.10.48", "178.162.139.24", "178.162.140.212"
                    , "2001:1af8:4700:a062:8::47de", "2001:1af8:4700:a062:9::47de", "2001:1af8:4700:a0c9:4::47de", "2001:1af8:4700:a0c9:3::47de");
            put(map, "ul.ehgt.org", "94.100.24.82", "94.100.24.72");
            put(map, "raw.githubusercontent.com", "151.101.0.133", "151.101.64.133", "151.101.128.133", "151.101.192.133");
`
        }`

        if (Settings.getBuiltEXHosts()){
            put(map, "exhentai.org", "178.175.128.252", "178.175.129.252", "178.175.129.254", "178.175.128.254",
                    "178.175.132.20", "178.175.132.22","172.64.206.24","172.64.207.24");
            put(map, "s.exhentai.org", "178.175.132.22", "178.175.128.254", "178.175.129.254");
        }
`
