### ISSUE TITLE
New version loads very slow

### ISSUE THREAD

**Issue by crankgud** [xiaojieonly/Ehviewer_CN_SXJ#659]
The newest version makes everything load at a very slow speed, doesn't matter if the connection type is wifi, mobile data or others. Thumbnails take a while to load and galleries will have missing pages to load, even if preload is active.

**Comment by MeteorFn** [comment]
Consider turning off the SNI setting in settings->advance, it solved my loading problem.

**Comment by crankgud** [comment]
> Consider turning off the SNI setting in settings->advance, it solved my loading problem.

Tuning off the SNI did help greatly, at least the first impressions with a few galleries I did check. Later on that I do a deeper dive, I'll see how well it does behave.

**Comment by zhentaisama** [comment]
> > Consider turning off the SNI setting in settings->advance, it solved my loading problem.
> 
> Tuning off the SNI did help greatly, at least the first impressions with a few galleries I did check. Later on that I do a deeper dive, I'll see how well it does behave.

If i turn off the SNI avoid，the app shows net work error. And I think this new version of Eh has change the host，so I need the foremost host.Do u have it？

**Comment by xiaojieonly** [comment]
> > Consider turning off the SNI setting in settings->advance, it solved my loading problem.
> 
> Tuning off the SNI did help greatly, at least the first impressions with a few galleries I did check. Later on that I do a deeper dive, I'll see how well it does behave.

This function is only for Chinese users in most cases, if you are not in China, you will not be able to use this function at all
