### ISSUE TITLE
旧版本解析失败，最新的直接网络错误

### ISSUE THREAD

**Issue by 31djgmcg** [xiaojieonly/Ehviewer_CN_SXJ#66]
之前用的1.7.6.11，本来一直可以但是今天中午以来就开始解析失败，然后更新到最新版直接网络错误

**Comment by xiaojieonly** [comment]
> 之前用的1.7.6.11，本来一直可以但是今天中午以来就开始解析失败，然后更新到最新版直接网络错误

最新版安卓9以下没法用

**Comment by 31djgmcg** [comment]
> > 之前用的1.7.6.11，本来一直可以但是今天中午以来就开始解析失败，然后更新到最新版直接网络错误
> 
> 最新版安卓9以下没法用

我安卓10的啊

**Comment by xiaojieonly** [comment]
> > > 之前用的1.7.6.11，本来一直可以但是今天中午以来就开始解析失败，然后更新到最新版直接网络错误
> > 
> > 
> > 最新版安卓9以下没法用
> 
> 我安卓10的啊

该开的东西开了没？host，dns，域名前置

**Comment by ChaosandStars** [comment]
同有此问题，网络错误，host，dns，域名前置均开启（电信网络）

**Comment by ChaosandStars** [comment]
试了试挂梯子有几率上去但很不稳定】

**Comment by xiaojieonly** [comment]
> 试了试挂梯子有几率上去但很不稳定】

表站还是里站？

**Comment by ChaosandStars** [comment]
> > 试了试挂梯子有几率上去但很不稳定】
> 
> 表站还是里站？

表站解析失败，里站前几天在使用VPN且全部打开host等设置后可以看到画廊，但点开阅读是509，现在里站也打不开了】

**Comment by xiaojieonly** [comment]
> > > 试了试挂梯子有几率上去但很不稳定】
> > 
> > 
> > 表站还是里站？
> 
> 表站解析失败，里站前几天在使用VPN且全部打开host等设置后可以看到画廊，但点开阅读是509，现在里站也打不开了】

509是因为梯子所在ip浏览流量被别人用光了，所以被e站限流了。表站解析失败就不太对劲了，你用的是自己的host还是原生的host？

**Comment by ChaosandStars** [comment]
> 原生的host？

原生的

**Comment by xiaojieonly** [comment]
> > 原生的host？
> 
> 原生的

关了host试试？我用的电信网好好的，表里都能看。。。。。😰

**Comment by xiaojieonly** [comment]
用最新的1.7.10
