### ISSUE TITLE
看完其他下载标签的内容后，会自动移入默认标签最下方

### ISSUE THREAD

**Issue by DearQAQ** [xiaojieonly/Ehviewer_CN_SXJ#662]
上个版本出现的问题，这个版本似乎仍未解决，对于有分作者收藏习惯的人来说太难受了，望大佬修复

**Comment by DearQAQ** [comment]
测试了下，似乎每个标签只会触发一次？之后再看这个标签的内容则不会触发这个问题

**Comment by xiaojieonly** [comment]
数据排序没有及时更新导致的，属于正常情况，但是有优化空间

**Comment by xiaojieonly** [comment]
移步：https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/600
