### ISSUE TITLE
主页解析错误

### ISSUE THREAD

**Issue by rhyspan** [xiaojieonly/Ehviewer_CN_SXJ#665]
![Screenshot_20230624_194348_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137617126/05c34c92-9c9b-4c35-82da-7af530f170ab)

主页解析错误，Q&A看了一圈没找到解决方法
梯子关了，高级设置调到正常了，360关了
重启重装清缓存都试过，没有用，求帮

**Comment by rhyspan** [comment]
不只是主页，除了“下载”和“设置”，其他都是解析错误
日志导出来是空的
版本最新，1. 9. 5. 2

**Comment by oo376575com** [comment]
我的也是

**Comment by xiaojieonly** [comment]
网不好
