### ISSUE TITLE
两个版本bug提交

### ISSUE THREAD

**Issue by sjdbsbsb** [xiaojieonly/Ehviewer_CN_SXJ#669]
一、1.9.5.2版本，进入大于40页的画廊，点进缩略图总览页面，下滑到底部第38、39、40页，开始加载41、42、43页时，APP闪退。（米13）

二、1.9.5.1开始的两个版本，有无法复现，但多次发生的，已下载画廊排序无故变化。（一次是不同下载文件夹内的10部左右画廊互相串文件夹且串排序；数次是新下载完成的几个画廊中的一个被排到文件夹底端，其余仍然在顶端）

目前已退回1.9.5.0未发生以上问题

**Comment by xiaojieonly** [comment]
已修

**Comment by xiaojieonly** [comment]
更新画廊会导致画廊排序变化，属于正常情况
