### ISSUE TITLE
问个关于原作者项目的小问题

### ISSUE THREAD

**Issue by melasto** [xiaojieonly/Ehviewer_CN_SXJ#67]
想问下，原作者是迁移到了下面gitlab的这个项目吗？
https://gitlab.com/NekoInverter/EhViewer
我看了下之前的issue没人问过，就问下

**Comment by duzhaokun123** [comment]
很明显不是
https://gitlab.com/NekoInverter/EhViewer/-/commit/c65eda03d3dfde0cb9fc27c76c6ce2c6ae6e77e6

原作者是[seven332](https://github.com/seven332)

**Comment by melasto** [comment]
ok thx
