### ISSUE TITLE
从1.9.5.2版本开始就出现下载然后app网络错误

### ISSUE THREAD

**Issue by hvjj** [xiaojieonly/Ehviewer_CN_SXJ#674]
从1.9.5.2版本开始就出现下载然后app网络错误，和浏览图只能加载部分的问题
![Screenshot_2023-07-03-09-50-20-36_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48812170/97d2fa5d-87bd-448a-b642-a93e5b819ad4)
![Screenshot_2023-07-03-08-58-33-47_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48812170/90a6be8a-fb13-4c06-8e5a-440eba862232)

**Comment by xiaojieonly** [comment]
更新，挂梯子，换节点
