### ISSUE TITLE
從1.9.5.2版本開始，頁面加載變很慢

### ISSUE THREAD

**Issue by jason840709** [xiaojieonly/Ehviewer_CN_SXJ#677]
如題，1.9.5.2和1.9.5.3在加載縮圖時非常慢，換安裝回1.9.5.1就沒這個問題了，希望可以改善

**Comment by idkcckdk** [comment]
我也有这样的问题，希望开发者可以找到解决的办法

**Comment by 00loli** [comment]
明显比以前卡多了

**Comment by xiaojieonly** [comment]
移步：https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604
