### ISSUE TITLE
为什么一会儿可以裸连？一会儿又裸连不了？

### ISSUE THREAD

**Issue by JamesHarden13913** [xiaojieonly/Ehviewer_CN_SXJ#68]

**Comment by xiaojieonly** [comment]
(⊙﹏⊙)，什么网？什么版本？安卓几？host dns ssl都开了吗？

**Comment by xiaojieonly** [comment]
> (⊙﹏⊙)，什么网？什么版本？安卓几？host dns ssl都开了吗？

你这提供的信息属实太少，以至于我都不知道从何下手（*゜ー゜*）

**Comment by xiaojieonly** [comment]
> _No description provided._

能连上但是时不时断线的话应该纯粹是网络问题了。。。

**Comment by JamesHarden13913** [comment]
移动的网，安卓10系统 三个选项都开了

**Comment by xiaojieonly** [comment]
网络不稳定
