### ISSUE TITLE
新版本闪退问题

### ISSUE THREAD

**Issue by jiangdashi495** [xiaojieonly/Ehviewer_CN_SXJ#680]
如题，从1.9.5.1更新到1.9.5.3频繁出现软件崩溃闪退问题，都是裸连没挂梯，手机是iQOOneo5s，安卓13，希望可以解决一下

**Comment by 22hello** [comment]
确实，这bug一直没修复

**Comment by xiaojieonly** [comment]
移步https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604
