### ISSUE TITLE
希望可以自己排序下載庫的順序

### ISSUE THREAD

**Issue by p12313461** [xiaojieonly/Ehviewer_CN_SXJ#681]
不然每次某個本子出新的一集那系列就要整個重點下載一遍，而且現在還有自訂下載書籤的本子讀完後回到預設下載位置的最下方的BUG,沒這功能太難受啦orz

**Comment by p12313461** [comment]
不對，bug問題更嚴重，點進去後就跑回預設最下面了

**Comment by hskao2024** [comment]
1.9.5.4新下載的本子 還是有些會跑到下載列的最下面

**Comment by TimCrownie** [comment]
我這邊是1.9.5.4更新後，新下載的本子會在最上方
但是更新前新下載的本子還是排在最下方

**Comment by StirrerCymbal5zn** [comment]
我也出现了同样的问题，每次应用崩溃后重启下载列表顺序都会被打乱

**Comment by xiaojieonly** [comment]
移步此issue https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/611
