### ISSUE TITLE
随机删除画廊

### ISSUE THREAD

**Issue by NoroHime** [xiaojieonly/Ehviewer_CN_SXJ#682]
最近版本开始每次打开都会随机删除大量画廊
其他fork版本ehv不会这样，手机空间也没有满
被删除后缩略图和.ehviewer文件也会消失
困扰了很久，并且被这个fork管理过的画廊没有办法转移到其他fork的ehv，我真的要疯了
一加7tpro coloros12.1

**Comment by xiaojieonly** [comment]
权限给了没？是不是手机自动清理把缓存数据全删了？
