### ISSUE TITLE
新版本平凡闪退

### ISSUE THREAD

**Issue by 22hello** [xiaojieonly/Ehviewer_CN_SXJ#683]
预览画廊图跟以前一样，只要滑快点查看详细图片就闪退 
MIUI14 安卓13

**Comment by hetcga** [comment]
>

**Comment by DT9025A** [comment]
附议
vivo T1
originOS，Android 11

**Comment by xiaojieonly** [comment]
有报错日志吗？

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604
