### ISSUE TITLE
😭为什么我不挂梯子挂梯子都进不去

### ISSUE THREAD

**Issue by Maplesotrys** [xiaojieonly/Ehviewer_CN_SXJ#684]
好久没用eh，我记得以前的版本我挂梯子是能进的，最近一上不挂梯子挂梯子都能搜图，但是不能载图

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
