### ISSUE TITLE
不知道为什么下载部分本子没速度，其他就很正常

### ISSUE THREAD

**Issue by lx3852043** [xiaojieonly/Ehviewer_CN_SXJ#685]
https://exhentai.org/g/2081786/b40c27602f/
https://exhentai.org/g/1603832/5972b61b00/
目前就这两个只有几b的速度。

**Comment by xiaojieonly** [comment]
e站的问题

**Comment by lx3852043** [comment]
> e站的问题

谢谢，不过电脑访问倒是正常的，唉。。好奇怪
