### ISSUE TITLE
新版本大量数据恢复时会恢复不全

### ISSUE THREAD

**Issue by deng112233** [xiaojieonly/Ehviewer_CN_SXJ#686]
新换了手机，在旧手机备份数据到导入新手机上时看到只能恢复一部分，软件都是新版本，数据量比较大，一共是12000条本子，恢复了6000多条，查看db文件发现旧手机备份的数据是完整的，怀疑应该是新功能和恢复数据之间有bug，然后降级到1947，恢复就变回正常了

**Comment by xiaojieonly** [comment]
以后会改
