### ISSUE TITLE
不明原因被ban

### ISSUE THREAD

**Issue by stxstxstx** [xiaojieonly/Ehviewer_CN_SXJ#687]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/55284283/d5c4142d-f973-4fd7-abd4-ec648291f45d)

您的IP地址已被暂时封禁表明您正在使用自动镜像/收集软件的页面负载。该禁令将在4天零8小时后到期

我确定我没有使用什么、自动处理，只是正常的看漫画而已

**Comment by xiaojieonly** [comment]
换ip
