### ISSUE TITLE
Randomly crash

### ISSUE THREAD

**Issue by haruhikawaii2k1** [xiaojieonly/Ehviewer_CN_SXJ#688]
[crash-2023-07-08-15-35-54-217.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12022599/crash-2023-07-08-15-35-54-217.log)
[crash-2023-07-12-07-39-34-928.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/12022600/crash-2023-07-12-07-39-34-928.log)

**Comment by xiaojieonly** [comment]
第一个是下载失败，应该属于正常情况。第二个是最近的预览页面加载内存溢出的问题，最新版应该已经修好了
