### ISSUE TITLE
1.9.5.2版本起裸连无法正常下载

### ISSUE THREAD

**Issue by plokijljj555** [xiaojieonly/Ehviewer_CN_SXJ#691]
有里站浏览权限。我在1.9.5.1版本使用软件的内置hosts裸连使用本软件没有任何问题（包括表站可以正常浏览）。但在1.9.5.2版本起（该版本把内置hosts改了？）无法正常下载，下载速度很慢且容易中断，甚至可能无法完成完整下载。1.9.5.4版本甚至连加载本子详情页也变慢了（列表的预览倒是快了很多）。想问问是不是内置hosts更新后的问题（比如刚好不适合我的ip?），或者是我什么设置错误。如果可以的话，可以告知我1.9.5.1的内置hosts是什么或者怎么看吗？我尝试自己找没找出我能裸连正常使用1.9.5.4版本的hosts
![000001eh](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/43328977/07da0e10-6e27-43d8-b2aa-6aa8db559f51)

**Comment by plokijljj555** [comment]
尝试修改api.e-hentai.org的hosts，无用。尝试修改s.exhentai.org的hosts，疑似改善？至少没有中断，一次下载完毕，但下载速度依然比1.9.5.1慢。依然不知道究竟是什么问题，应该更改什么。

**Comment by xiaojieonly** [comment]
更新到最新版试试
