### ISSUE TITLE
I would like Japanese support

### ISSUE THREAD

**Issue by shixichann** [xiaojieonly/Ehviewer_CN_SXJ#694]
app/src/main/res/values-ja/strings.xml
Is it possible to add the following to ?

not perfect
============================

     <string name="blacklist_id">ユーザー ID</string>
     <string name="blacklist">ブラックリスト</string>
     <string name="join_in_blacklist">ブラックリストに参加する</string>
     <string name="add_blacklist">ブロックされたユーザーを追加する</string>
     <string name="blacklist_tip">このブロック システムは、EHentai ウェブサイトのコメント システムに基づいてコメントをブロックし続けます。 \n\nレビューアーのブロック項目: このレビューアーによってアップロードされたコメントを除外します。 これにより、ギャラリー リストの読み込みに時間がかかる場合があります。 </string>
     <string name="blacklist_text">ユーザーをブロックする</string>
     <string name="delete_blacklist">ユーザー“%s“のブロックを解除しますか? </string>
     <string name="blacklist_reason_text">ブロックの理由</string>
     <string name="settings_eh_blacklist">コメントブラックリスト</string>
     <string name="settings_eh_blacklist_summary">アカウント名に従って他の人のコメントをブロックする</string>
     <string name="settings_advanced_dns_over_http_title">セキュア DNS (DoH)</string>
     <string name="settings_advanced_dns_over_http_summary">一部の地域での DNS 汚染を修正する</string>
     <string name="settings_advanced_domain_fronting_title">ドメインフロンティング</string>
     <string name="settings_advanced_domain_fronting_summary">SNI ブロックをバイパスする</string>
     <string name="settings_advanced_url_replace_title">URL マスカレード、SNI をオフにする必要があります</string>
     <string name="settings_advanced_url_replace_summary">URL 偽装 (再起動が必要です。開くとアカウント機能が無効になります)</string>
     <string name="settings_about_donate_guide">サポート ガイド</string>
     <string name="share_favorites_dialog_title">お気に入りを共有</string>
     <string name="share_favorites_dialog_message">お気に入り %s を共有しますか? </string>
     <string name="add_favorites_dialog_message">お気に入り %s を追加しますか? </string>
     <string name="settings_advanced_built_ex_hosts_title">組み込みの 例外 hosts.txt</string>
     <string name="settings_advanced_built_ex_hosts_summary">アプリケーションによって提供されるホストから IP へのマッピングは\nカスタム hosts.txt によって上書きできます</string>
     <string name="network_remind">VPN が有効になっていることが検出されました。ネットワーク セキュリティに注意してください</string>
     

     <string name="no_blicklist">これはブラックリストです</string>

====================

**Comment by shixichann** [comment]
app/src/main/res/values-ja/strings.xml

<resources>

    
    <string name="settings_eh_lock_cookies_igneous">Lock the Cookie igneous field</string> 
    <string name="settings_eh_lock_cookies_igneous_summary">特別な状況を除いて、これを有効にすることは推奨されない。</string>
    <string name="settings_eh_show_jpn_title_summary">EHentaiウェブサイトの設定で日本語タイトルを有効にする必要がある</string>
    <string name="settings_eh_show_tag_translations">タグの翻訳（中国語）を表示する</string>
    <string name="settings_eh_show_tag_translations_summary">原文ではなくタグ翻訳（中国語）を表示（データファイルのダウンロードに時間がかかります）</string>
    <string name="settings_eh_tag_translations_source">プレースホルダ</string>
    <string name="settings_eh_tag_translations_source_url">https://placeholder</string>
    <string name="settings_eh_show_gallery_comment">ギャラリーコメントを表示</string>
    <string name="settings_eh_show_eh_event">EHイベントを表示する</string>
    <string name="settings_read_reverse_volume_page">ボリュームキーの変換方向を逆にする</string>
    <string name="settings_download_download_order_by_asc">昇順でのダウンロードする</string>
    <string name="settings_download_download_order_by_asc_summary">すべてのギャラリーをダウンロードする場合は、順番にダウンロードします</string>


    
     <string name="blacklist_id">ユーザー ID</string>
     <string name="blacklist">ブラックリスト</string>
     <string name="join_in_blacklist">ブラックリストに参加する</string>
     <string name="add_blacklist">ブロックされたユーザーを追加する</string>
     <string name="blacklist_tip">このブロック システムは、EHentai ウェブサイトのコメント システムに基づいてコメントをブロックし続けます。 \n\nレビューアーのブロック項目: このレビューアーによってアップロードされたコメントを除外します。 これにより、ギャラリー リストの読み込みに時間がかかる場合があります。 </string>
     <string name="blacklist_text">ユーザーをブロックする</string>
     <string name="delete_blacklist">ユーザー“%s“のブロックを解除しますか? </string>
     <string name="blacklist_reason_text">ブロックの理由</string>
     <string name="settings_eh_blacklist">コメントブラックリスト</string>
     <string name="settings_eh_blacklist_summary">アカウント名に従って他の人のコメントをブロックする</string>
     <string name="settings_advanced_dns_over_http_title">セキュア DNS (DoH)</string>
     <string name="settings_advanced_dns_over_http_summary">一部の地域での DNS 汚染を修正する</string>
     <string name="settings_advanced_domain_fronting_title">ドメインフロンティング</string>
     <string name="settings_advanced_domain_fronting_summary">SNI ブロックをバイパスする</string>
     <string name="settings_advanced_url_replace_title">URL マスカレード、SNI をオフにする必要があります</string>
     <string name="settings_advanced_url_replace_summary">URL 偽装 (再起動が必要です。開くとアカウント機能が無効になります)</string>
     <string name="settings_about_donate_guide">サポート ガイド</string>
     <string name="share_favorites_dialog_title">お気に入りを共有</string>
     <string name="share_favorites_dialog_message">お気に入り %s を共有しますか? </string>
     <string name="add_favorites_dialog_message">お気に入り %s を追加しますか? </string>
     <string name="settings_advanced_built_ex_hosts_title">組み込みの 例外 hosts.txt</string>
     <string name="settings_advanced_built_ex_hosts_summary">アプリケーションによって提供されるホストから IP へのマッピングは\nカスタム hosts.txt によって上書きできます</string>
     <string name="network_remind">VPN が有効になっていることが検出されました。ネットワーク セキュリティに注意してください</string>
     

 <string name="no_blicklist">これはブラックリストです</string>



    <string name="app_name">EhViewer</string>

**Comment by xiaojieonly** [comment]
OK，thanks for your help,i well update in next version

**Comment by shixichann** [comment]
次のversionを楽しみにしています。
I look forward to the next version.
我期待下一个版本。

**Comment by shixichann** [comment]
ダウンロードに失敗した際に出る表示が「更新」となっています。
正しくは「失敗」ではありませんか？

The display that appears when the download fails is "更新".
Isn't it "失敗" correctly?

下载失败时出现的显示是“更新”。
不是正确的“失敗”吗？




今使ってる物：<string name="update">
正しい物：<string name="download_state_failed">

Things I'm using now：<string name="update">
Correct one：<string name="download_state_failed">

我现在正在使用的东西：：<string name="update">
正确之一：<string name="download_state_failed">

**Comment by shixichann** [comment]
ダウンロードに失敗した際に出る表示が「更新」となっています。
正しくは「失敗」ではありませんか？

The display that appears when the download fails is "更新".
Isn't it "失敗" correctly?

下载失败时出现的显示是“更新”。
不是正确的“失敗”吗？




今使ってる物：string name="update"
正しい物：string name="download_state_failed"

Things I'm using now：string name="update"
Correct one：string name="download_state_failed"

我现在正在使用的东西：：string name="update"
正确之一：string name="download_state_failed"

**Comment by xiaojieonly** [comment]
已经添加进代码文件
Added to code file
コードファイルに追加されました
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/84d94c7c-6f6a-41c7-ada3-2a092bc99c96)
