### ISSUE TITLE
下载封面无法加载

### ISSUE THREAD

**Issue by zbh2k** [xiaojieonly/Ehviewer_CN_SXJ#695]
[只有最近下载的几百本有封面，点进去后可以直接浏览本地文件，但略缩图均无法显示。 试过重新定位下载路径，和更换下载路径，之前下载的均无法显示，除非取消下载后重新下载才会显示略缩图。好哥哥，求解决办法
![_-1352620740__b771529e11fcfbf70d43ea2f88763c53_1065327180_Screenshot_2023-07-21-23-30-51-81_159c494ea8977f628e53d8d36755ba4c_0_wifi_0](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/140182397/22cd921a-202f-471b-8e66-40707f97c0cd)
![_-1492921285__9d7ec0ccdb0d952be3008fad01a5647e_1698254256_Screenshot_2023-07-21-23-30-46-61_159c494ea8977f628e53d8d36755ba4c_0_wifi_0](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/140182397/7d6126b8-56f2-46eb-ab92-8613ca949b23)
![_1554552119__50c360099d3a34c81945ed833d477b5a_-1495019741_Screenshot_2023-07-21-23-30-44-17_159c494ea8977f628e53d8d36755ba4c_0_wifi_0](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/140182397/14aa45bc-6910-4491-a996-4d360655eca1)

**Comment by xiaojieonly** [comment]
没办法，e站的url改了，旧的略缩图缓存被手机系统当垃圾处理掉后，就会出现这种问题，目前的方案是手动进入详情页重新获取略缩图，获取不了的话只能重新下
