### ISSUE TITLE
应用停止运行，无法加载缓存

### ISSUE THREAD

**Issue by imqinchen** [xiaojieonly/Ehviewer_CN_SXJ#696]
浏览到一半，返回到预览页，点击继续阅读按钮，之前浏览过的内容需重新加载。
浏览到一半，点击查看更多预览，加载至第二页预览，点击进入浏览，必定卡住停止运行。

版本1.9.5.4 设备mi 11 pro

**Comment by xiaojieonly** [comment]
安装最新版试试
