### ISSUE TITLE
1.9.5.5画廊乱序bug复现

### ISSUE THREAD

**Issue by sjdbsbsb** [xiaojieonly/Ehviewer_CN_SXJ#698]
从1.9.5.4更新1.9.5.5后，打开下载，约3个文件夹里的部分画廊位置互换了。来个文件夹内下载画廊排序功能吧，也方便放连载本，求求了。

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/37364543-fe9e-4d3c-a8a2-610bda471eef)

**Comment by xiaojieonly** [comment]
已添加至处理队列

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/3c2cd44d-54d8-4cb8-afa0-8516298d5d10)

**Comment by Fullary** [comment]
确实麻烦，一下子就不想看了，总计五千多画廊突然完全乱序，差点没给我送走。。。。。。

**Comment by xiaojieonly** [comment]
[发现问题了，更新封面更换的画廊会bug，没换封面的没问题](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/739)
