### ISSUE TITLE
该版本种子无法下载，其他的eh软件都没有这些问题

### ISSUE THREAD

**Issue by kuxuanmozhe** [xiaojieonly/Ehviewer_CN_SXJ#699]
Uploading 5_6192988355706227729.mp4…

**Comment by kuxuanmozhe** [comment]
就是下载种子后，无法使用这个种子文件，就下载个虚假的文件，里面什么都没有，用任何bt软件都看不到里面的东西

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/40748965-6be9-48c8-8f91-c676577787cc)
看不了你发的东西
