### ISSUE TITLE
标签还是英文

### ISSUE THREAD

**Issue by wapy9** [xiaojieonly/Ehviewer_CN_SXJ#7]
上个作者1.5版本还是哪个版本之后重新下载就是英文标签了，后来降级到1.4后覆盖升级标签是中文，现在下载使用了新版本，开启显示标签翻译还是英文，不知道为啥

**Comment by xiaojieonly** [comment]
> 上个作者1.5版本还是哪个版本之后重新下载就是英文标签了，后来降级到1.4后覆盖升级标签是中文，现在下载使用了新版本，开启显示标签翻译还是英文，不知道为啥

你确定安装的是1.7.6.04版本吗？默认的就是中文标签呀  
你可以等待一会儿再看看，可能是后台翻译文件还没下载完的问题，然后画廊第二次进入是直接读缓存的，为了流畅度不会重新刷新数据 ，最好是换个本子看下有没有汉化成功， 然后还可以试试手动添加英文书签进行验证 比如：female:sister  如果书签自动汉化了就证明汉化文件下载完了。

**Comment by wapy9** [comment]
你回复了之后，我验证了下，应该是汉化文件没下下来，然后发下是电信网问题，我挂了VPN之后汉化文件就下下来了
