### ISSUE TITLE
里站再次无法裸连了，是不是今后还得靠梯子过活了…

### ISSUE THREAD

**Issue by xmc611** [xiaojieonly/Ehviewer_CN_SXJ#70]
免费梯子还会509…给梯子花钱还不如给作者花，毕竟梯子就是拿来上里站的。

**Comment by xiaojieonly** [comment]
> 免费梯子还会509…给梯子花钱还不如给作者花，毕竟梯子就是拿来上里站的。

509是因为IP 流量被用完了，e站对每个IP都有限流，免费梯子用的人太多了509属实正常，而且容易被封号，我之后找找有没有里站能用的host，希望保持联系，到时候我发一组host你试试能不能用，能用我就更新到下一版(￣_,￣ )  ——我测不了，我用的wifi能表站和里站都能裸连(。_。)

**Comment by xmc611** [comment]
> > 免费梯子还会509…给梯子花钱还不如给作者花，毕竟梯子就是拿来上里站的。
> 
> 509是因为IP 流量被用完了，e站对每个IP都有限流，免费梯子用的人太多了509属实正常，而且容易被封号，我之后找找有没有里站能用的host，希望保持联系，到时候我发一组host你试试能不能用，能用我就更新到下一版(￣_,￣ ) ——我测不了，我用的wifi能表站和里站都能裸连(。_。)

好的，谢谢(*°∀°)=3

**Comment by xmc611** [comment]
好神奇？昨天不行，今天又能裸连了，难道我家WIFI是一回生二回熟？　(′～`；）

**Comment by xiaojieonly** [comment]
> 好神奇？昨天不行，今天又能裸连了，难道我家WIFI是一回生二回熟？　(′～`；）

🤣😂🤣😂
