### ISSUE TITLE
下载的画廊，预览图无法加载

### ISSUE THREAD

**Issue by zzz2254** [xiaojieonly/Ehviewer_CN_SXJ#701]
1.9.5.3版本，下载的画廊，预览图无法加载，第二个问题，被文件清理工具删除的图片，无法检测，再重新下载

**Comment by masonal123** [comment]
同样的问题，打开下载界面，发现很多本子的封面看不到了。得重新点进详情页才能恢复

**Comment by chanchanccc** [comment]
我也是，更新到最新版本也没用，去tg问也没有人回答

**Comment by xiaojieonly** [comment]
被你当垃圾删了，你让我怎么办?

**Comment by chanchanccc** [comment]
啊？我删他干啥，白E从来没有这些问题，现在更新了可以翻页了，我就不用绿E了，就是可惜我下的本子了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月04日 14:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaojieonly/Ehviewer_CN_SXJ] 下载的画廊，预览图无法加载 (Issue #701) |

被你当垃圾删了，你让我怎么办?
