### ISSUE TITLE
bug集合

### ISSUE THREAD

**Issue by xiaojieonly** [xiaojieonly/Ehviewer_CN_SXJ#704]
相关bug请于对应问题下进行讨论
新问题请开新帖

**Comment by xiaojieonly** [comment]
[文件夹名字及种子下载问题](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/609)

**Comment by xiaojieonly** [comment]
[进入“查看更多预览”页面，使用翻页功能跳转至后面页数，点击缩略图打开大图会发生应用闪退的问题，好像是图片越多越容易出现这种情况，大概是从更新了最新版后才发生](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604)
已解决（系统问题，系统黑暗模式不兼容app导致奔溃）
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/8d2c99f6-a073-4c12-b726-5f3510c73ab7)

**Comment by xiaojieonly** [comment]
[下载数量更新](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/590)

**Comment by xiaojieonly** [comment]
[书签多次调整顺序无法保存](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/708)

**Comment by xiaojieonly** [comment]
[画廊乱序bug复现](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/698)

**Comment by hskao2024** [comment]
最新版本下載區本子順序亂掉的問題還是存在 新下載的本會跑到最下面

**Comment by Fullary** [comment]
下载乱序另一个问题，古早下载的本子也乱序并且乱跑文件夹。

**Comment by Fullary** [comment]
更新的问题，更新完后还是会卡封面，并且第二次进入又要从新下载。

**Comment by TAjimu-veda** [comment]
版本1.9.5.6
问题：在上一个本子还未完全下载完毕的情况就开始下一本本子的下载，最终导致没有任何一个本子是完整下载完成的

**Comment by TAjimu-veda** [comment]
> 版本1.9.5.6
> 问题：在上一个本子还未完全下载完毕的情况就开始下一本本子的下载，最终导致没有任何一个本子是完整下载完成的

卸载重新安装问题还是存在

**Comment by xiaojieonly** [comment]
> 版本1.9.5.6 问题：在上一个本子还未完全下载完毕的情况就开始下一本本子的下载，最终导致没有任何一个本子是完整下载完成的

自身操作问题，与软件无关

**Comment by hvjj** [comment]
新版本清除缓存后下载的旧画廊无法观看显示erro

**Comment by horizoe10** [comment]
频繁报错“错误状态码：429”，使用过WIFI、流量，并分别进行过有无梯子的网络环境，都是这种情况。这会导致下载中的画廊直接停止，并且无法浏览其他内容，但是经过一段时间就自动好了，基本处于一分钟内一般时间都是报错

**Comment by xiaojieonly** [comment]
[分辨率过大的画廊图片Eh内无法加载显示](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/722)

**Comment by junbluedd** [comment]
1.9.5.7貌似不能裸连，我降级到1.9.5.6又能无梯子加载图了( ﾟ∀。)

**Comment by sister-complex** [comment]
> [进入“查看更多预览”页面，使用翻页功能跳转至后面页数，点击缩略图打开大图会发生应用闪退的问题，好像是图片越多越容易出现这种情况，大概是从更新了最新版后才发生](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604)
> 已解决（系统问题，系统黑暗模式不兼容app导致奔溃）
> ![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/8d2c99f6-a073-4c12-b726-5f3510c73ab7)
> 
> 

我这边问题还是稳定复现，手机是redmi k40s，不知道有没有同样的小伙伴

**Comment by qwe555666** [comment]
兄弟，我是六月份问过你怎么打赏过，我点开链接，只有死图，可以的话发图片到1041591991@qq.com，我的邮箱，好哒赏

**Comment by qw853286543** [comment]
> > [进入“查看更多预览”页面，使用翻页功能跳转至后面页数，点击缩略图打开大图会发生应用闪退的问题，好像是图片越多越容易出现这种情况，大概是从更新了最新版后才发生](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/604)
> > 已解决（系统问题，系统黑暗模式不兼容app导致奔溃）
> > ![image](https://user-images.githubusercontent.com/49278135/258599880-8d2c99f6-a073-4c12-b726-5f3510c73ab7.png)
> 
> 我这边问题还是稳定复现，手机是redmi k40s，不知道有没有同样的小伙伴

俺也一样，手机是红米note12 turbo，安卓13，miui14

**Comment by lcccw** [comment]
新版本平板打开侧边栏就固定闪退

**Comment by amnsjjj** [comment]
我在应用内无法更新软件，下载完资源后文件丢失，显示已被删除，必须在网站下载最新版重现安装后才能更新完成，这是什么问题，能修复吗

**Comment by Restore000** [comment]
求求了，新功能先放一放，修复一下TargetImageUrl error错误吧，触发原因不详，一个画廊出现一次接下来几天不能继续下载换节点也没用。

**Comment by xiaojieonly** [comment]
> 我在应用内无法更新软件，下载完资源后文件丢失，显示已被删除，必须在网站下载最新版重现安装后才能更新完成，这是什么问题，能修复吗
系统问题，建议手动更新
