### ISSUE TITLE
APP闪退

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#705]
打开此画廊(https://exhentai.org/g/2291989/9639ebed9d/) 点击新版本后把APP切到后台，APP即闪退（有时候不需要切后台也会闪退
![Screenshot_2023-07-26-18-40-51-329_com.fankes.apperrorstracking.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/90617f1f-2362-4dba-b85c-9d259c15c9be)

**Comment by Steve-337** [comment]
直接查看新版的画廊则不会闪退，必须从旧版画廊跳转到新版才会闪退

**Comment by lcccw** [comment]
新版本平板打开侧边栏固定闪退

**Comment by xiaojieonly** [comment]
已修复
