### ISSUE TITLE
1.9.5.5在三星的智能管理器中被认为是风险应用

### ISSUE THREAD

**Issue by IcarusAegis** [xiaojieonly/Ehviewer_CN_SXJ#706]
被识别为恶意软件，被识别为a.gray.sexpay.s
![Screenshot_20230726_224116_Smart Manager.png](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/46650308/33c88d21-31a9-451a-ae92-2d5c789f2b9b)

![Screenshot_20230726_223903_Package installer.png](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/46650308/180e848c-7b10-4c38-98bd-a39e848d56a4)

**Comment by xiaojieonly** [comment]
管我屁事，信了就卸载

**Comment by KaJ1L** [comment]
维护了几年的开源软件，你可以自己查代码。而且真想不报毒还不简单？加固混淆一下就可以了。实在怕要么卸了，要么把权限该关了就关了。

**Comment by IcarusAegis** [comment]
> 管我屁事，信了就卸载

只是提醒一下有误报发生。。。

**Comment by zxy662** [comment]
sexpay
