### ISSUE TITLE
能否添加阅读本地漫画的功能？（JPG或者压缩包）

### ISSUE THREAD

**Issue by Abm12138** [xiaojieonly/Ehviewer_CN_SXJ#707]
一些漫画因为版权炮或其他原因无法看了，从其他地方下载下来了，但还是想在这个APP上阅读。

**Comment by julius128** [comment]
赞成，我现在用的perfect viewer看的没下载的或者是版权本 但是perfect viewer 经常 会读取不出封面导致我要重新扫描本子，而且看漫画时候有时会加载不出来 
但是ehviewer下载完之后基本不会出现这个情况 
强烈希望追加这个！！！单独多开一个左边的标签（本地之类的 然后可以看到自己放进去的文件
