### ISSUE TITLE
大佬现在打开e绅士不管挂没挂代理都只会跳出一个安卓头在哭的表情这个要怎么处理

### ISSUE THREAD

**Issue by RnoJUN** [xiaojieonly/Ehviewer_CN_SXJ#71]
![Screenshot_20210127-014418](https://user-images.githubusercontent.com/78041258/105882922-96929500-6049-11eb-937d-02c002eb87bf.png)

**Comment by xiaojieonly** [comment]
设置->高级里的host，dns，ssl都开了吗？

**Comment by xiaojieonly** [comment]
安卓几？

**Comment by RnoJUN** [comment]
> 设置->高级里的主机，dns，ssl都开了吗？

弄好了现在这些开了能进但有时候一直转圈加载进不了网络也换了四种这种情况时好时坏有解决的方法吗

**Comment by xiaojieonly** [comment]
> > 设置->高级里的主机，dns，ssl都开了吗？
> 
> 弄好了现在这些开了能进但有时候一直转圈加载进不了网络也换了四种这种情况时好时坏有解决的方法吗

暂时没太好的办法≡(▔﹏▔)≡

**Comment by huangniu123456** [comment]
我的也是这样，安卓9 联通网
