### ISSUE TITLE
求助！！系统报毒！！无法安装！！

### ISSUE THREAD

**Issue by xr1234n** [xiaojieonly/Ehviewer_CN_SXJ#710]
软件应该被部分用户举报，被病毒库记录了。

现在手机不让安装软件更新，而且不停要求卸载软件。
![Screenshot_20230731_074013_Via](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/61616196/e835e5a7-6881-4d58-9c8f-d729a6d889cf)

**Comment by SamuNatsu** [comment]
不嫌麻烦就手动点击忽略，如果嫌麻烦就用vmos pro在手机上开个安卓虚拟机安装使用

不过y1s1，这些所谓的危险函数感觉就是个借口，实际上大部分app都会用到，看起来就像是没给腾讯钱所以才进了病毒库

**Comment by sjdbsbsb** [comment]
手机管家卸了，自带杀毒关了，纯净模式关了，开发者里允许安装未知来源开了

**Comment by xr1234n** [comment]
唉，就是手机自带的管家卸载不了、关闭不了，好像也调用了360的病毒库。支付宝和淘宝打开也会提示病毒，看来只有用虚拟机了。

**Comment by xiaojieonly** [comment]
卸载吧
