### ISSUE TITLE
导出数据无法被其他eh读取？

### ISSUE THREAD

**Issue by Alexo3o** [xiaojieonly/Ehviewer_CN_SXJ#713]
绿E导出的数据无法被彩E读取，不知道是什么原因（下载的本子数量7500左右），有什么解决办法吗

**Comment by xiaojieonly** [comment]
数据库版本号改下就行

**Comment by Alexo3o** [comment]
> 数据库版本号改下就行

请问该如何修改？我使用记事本打开显示一堆乱码，网上也没有搜到具体步骤。烦请指导，跪谢

**Comment by Alexo3o** [comment]
> 数据库版本号改下就行

请问该如何修改？我用记事本打开显示一堆乱码，网上也没有搜到具体步骤。烦请指导，跪谢
