### ISSUE TITLE
更新之后下载会回到默认分类问题

### ISSUE THREAD

**Issue by Yahagi01** [xiaojieonly/Ehviewer_CN_SXJ#724]
明明选的是自己创建的分类，过了一段时间就袭击跑回默认了，还有以前下载的老本子也会跑回去

**Comment by SQDFeng** [comment]
而且是以最早的时间出现在默认分类的最下端对吧

**Comment by Yahagi01** [comment]
> 而且是以最早的时间出现在默认分类的最下端对吧

对，直接以最早的时间出现在默认分类

**Comment by WeiRi** [comment]
我也是类似的问题，似乎是最近经常查看详情的本子就会自动被移动到那里

**Comment by StarDustDurgan** [comment]
我也是，分好类的本子莫名其妙跑到默认列表最底部了

**Comment by yinyan9066** [comment]
有解决方法了吗

**Comment by bb1227** [comment]
我猜 各位一定都是小米手机 因为我同学的oppo没事

**Comment by WeiRi** [comment]
> 我猜 各位一定都是小米手机 因为我同学的oppo没事

不是的，我是华为。另外我看南+上也有不少人遇到了类似情况

**Comment by Catinus** [comment]
> 我猜 各位一定都是小米手机 因为我同学的oppo没事

我三星s10加行，一样问题

**Comment by xiaojieonly** [comment]
更新最新版试试，不行的话重新打开issue，或者试试删除问题画廊后重新下载
