### ISSUE TITLE
自动翻页功能能不能整一个😁

### ISSUE THREAD

**Issue by bzt345** [xiaojieonly/Ehviewer_CN_SXJ#725]

**Comment by 13271861029** [comment]
8月15日的留言，本人同样建议能否支持自动翻页或幻灯片自动播放功能😊

**Comment by xiaojieonly** [comment]
一直想做，但是老是忘😂

**Comment by Small-tailqwq** [comment]
双手打是吧，笑死

**Comment by 13271861029** [comment]
> 双手打是吧，笑死

左手持枪，右手扣扳机，也正常吧 :-）有一种不就是专门攻击头部部分的吗，挺渴望能解放双手呢。

**Comment by xiaojieonly** [comment]
已经有了，请更新最新版

**Comment by 13271861029** [comment]
太酷啦！已收到邮件，明白！辛苦了大大







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月7日 11:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [xiaojieonly/Ehviewer_CN_SXJ] 自动翻页功能能不能整一个😁 (Issue #725) |

已经有了，请更新最新版
