### ISSUE TITLE
新功能请求 - 屏蔽画廊特定图片页

### ISSUE THREAD

**Issue by LainHE** [xiaojieonly/Ehviewer_CN_SXJ#726]
大大您好:

我个人很喜欢下载收藏自己喜欢的漫画, 但最近经常会遇到汉化者在上传的时候添加很多很多的`外部广告`, 着实不想下载这些牛皮癣
所以请求大大添加一个在下载之初就可以选择哪些图片可以屏蔽掉的功能

具体实现逻辑建议:
在`画廊预览`中长按<sub>~~(如果长按后能多选就更好了)~~</sub>可以选择哪些图片需要屏蔽, 屏蔽效果为:
 - 屏蔽后可能需要视觉标识哪些图片被屏蔽了, 比如调暗之类的
 - 屏蔽后下载默认不下载这些图片
 - 屏蔽后再观看漫画时默认跳过相关页, 或相关页提示已屏蔽、并不进行自动下载

软件开发我不是特别懂, 实现方法也许可以在`.ehviewer`中添加识别来做屏蔽? <sub>~~如果`.ehviewer`的确是用作识别的话...我只是看到每个下载的画廊里都有这个文件而已...~~</sub>

希望以上建议对您有帮助, 也拜托您认真考虑一下这个请求, 我真的其实忍了蛮久这个问题的了:sob:

**Comment by xiaojieonly** [comment]
已收录进需求集合

**Comment by TAT213** [comment]
.ehviewer里面有页数的数据，要是能把某些漫画的后7页直接改没了就好了

**Comment by yahoozhu** [comment]
[Eros-FE](https://github.com/3003h/Eros-FE)    这边已经初步实现了可以屏蔽二维码页，但ehviewer用得习惯些
