### ISSUE TITLE
我不知道为什么

### ISSUE THREAD

**Issue by csi141** [xiaojieonly/Ehviewer_CN_SXJ#727]
我的旧手机坏了，于是我购买了一台新手机并且下载了此软件，出乎我意料的是，它不工作。无论我下载哪个版本（因为我是条懒狗从不更新，而且忘了自己当初下载的是哪个版本了）它都无法正确加载阅读页，其他的功能一切正常，但是阅读页经常显示加载失败。气急败坏的我打算注册个账号去exhentai试试（因为同样的原因，本懒狗之前并没有eh账号），就在我注册完后登录的上的那一刻，我惊奇的发现居然一切正常了，不管我打开哪个本子都可以正确的加载阅读页，就像在我旧手机上工作的一样（而且我并没有切换到exhentai，版本是1.9.5.7）。现在我开始相信超自然力量了，并且我打算以后每次开导前都先给手机听一遍二进制圣歌以使机魂大悦

**Comment by xiaojieonly** [comment]
哈？？？！！！
开发者常用语：能用就再别乱动了😄
