### ISSUE TITLE
错误状态429是因为什么？

### ISSUE THREAD

**Issue by QAQlim** [xiaojieonly/Ehviewer_CN_SXJ#729]
是不是就会出现

**Comment by xiaojieonly** [comment]
没遇到过，一般来讲是网络问题

**Comment by kongbiaYYDS** [comment]
我也遇到过，真的很烦，他必须要下载下来才可以看得到，而且我这个下载完一张图片就会立马暂停，要你重新点一遍，而且开启下载之后就前几秒钟速度比较快能跑到一两百K，到后面的时候只能跑到几B，动不动就IP流量过多给我锁了，还他妈要等一个小时
