### ISSUE TITLE
新功能请求 - Archive Download下载模式

### ISSUE THREAD

**Issue by melon0918** [xiaojieonly/Ehviewer_CN_SXJ#732]
archive download可以打包下载，不会耗费配额也不会触发风控，下载速度也很快，很多热门本子可以免GP下载原图。
我自己GP也是用不完，巴不得全部下原图，但现在app里一张张下原图太慢了，配额耗尽了还需要去网页上重置，比较麻烦。

**Comment by xiaojieonly** [comment]
已实现
