### ISSUE TITLE
略缩图无法显示

### ISSUE THREAD

**Issue by zbh2k** [xiaojieonly/Ehviewer_CN_SXJ#733]
![Screenshot_2023-08-20-00-06-02-03_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/140182397/d73c3224-74f7-43d3-bce9-0c74e92f5047)
 这次的略缩图无法显示是本子浏览界面的内容略缩图无法显示，其他地方的略缩图都是正常的

**Comment by xiaojieonly** [comment]
网不好
