### ISSUE TITLE
下载的新作品会被移到画廊的最下面

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#735]
在下载完成以后，有时候下载的作品会被移动到画廊的最下面。以前下载完成的作品则不会有这个现象，但是新的作品有时会

**Comment by Yahagi01** [comment]
以前下载的也会，我已经好多以前下载的被移过去了

**Comment by noname1428** [comment]
如果在线打开已下载的作品然后强制关闭应用就会触发这个bug

**Comment by Ishimagikarp** [comment]
> 如果在线打开已下载的作品然后强制关闭应用就会触发这个bug

问题在于应用有些时候会闪退，然后就没什么办法

**Comment by steve12621** [comment]
我也有这个bug，但是我观察到的是，如果已经下载了一个画廊，再在主页的搜索中搜到并且阅读这个画廊，就会导致它被移到下载列表的最下面

**Comment by Ishimagikarp** [comment]
目前根据我的体验来看，下载一个画廊以后打开它，然后强行关掉EH，即使你把它放到了其他的文件夹里他也会被移动到默认的最下面。

**Comment by 661266** [comment]
我發現一段時間沒開eh  後來開啟後下載的第一個本子 一定閃退

**Comment by Ishimagikarp** [comment]
我这边也差不多，不过是点击下载的时候会卡住，然后有时会闪退

**Comment by FuyukiAsahi** [comment]
同样，，也没看到可以自己调整下载内文件顺序的功能

**Comment by Ishimagikarp** [comment]
这个倒是以前也没有，也不是什么太大的问题，但是这个移动到最下面是挺烦的问题

**Comment by xzphy1** [comment]
> 目前根据我的体验来看，下载一个画廊以后打开它，然后强行关掉EH，即使你把它放到了其他的文件夹里他也会被移动到默认的最下面。

感觉随便移的，看了这个帖子，刚建了个新文件夹下了20个本子，重开后只剩10个，发现剩下的本子在默认下面和其他消失本子随机混在一起，好在还是发现了这些消失的本子

**Comment by xiaojieonly** [comment]
最新版已经修好了
