### ISSUE TITLE
之前不挂梯子可以看，现在不挂和挂了都看不了

### ISSUE THREAD

**Issue by 244948** [xiaojieonly/Ehviewer_CN_SXJ#738]
![Screenshot_2023-08-27-03-13-25-68_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/143289796/9508fa7e-7ff7-4d5e-9b20-5ec849537a9e)

**Comment by xiaojieonly** [comment]
网不好，如果是浙江的话，最近亚运，严管
