### ISSUE TITLE
最新版的一个手机能用但另一个网络错误是因为啥

### ISSUE THREAD

**Issue by 31djgmcg** [xiaojieonly/Ehviewer_CN_SXJ#74]

**Comment by xiaojieonly** [comment]
安卓10以下用不了最新版

**Comment by zeroisD** [comment]
> 安卓10以下用不了最新版

安卓9用1.7.6.16还是网络错误哎

**Comment by zeroisD** [comment]
> 安卓10以下用不了最新版

安卓9前天用1.7.6.11中午还是好好的，晚上就网络错误了，现在多次卸载重装为1.7.6.16还是上不了。高级里的东西全开了都上不了

**Comment by deadhc** [comment]
安卓9电信网使用1.7.6.16，内置host、安全dns、域名前置 全开目前依然显示网络错误。

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md
