### ISSUE TITLE
如何打赏

### ISSUE THREAD

**Issue by qwe555666** [xiaojieonly/Ehviewer_CN_SXJ#740]
六月份问过这个问题，打开你的链接，是死图，请发打赏二维码到1041591991@qq.com

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/support.md

**Comment by xiaojieonly** [comment]
这个不行吗？

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/15535e61-c49b-4849-8c64-1c8560266877)

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/c28b40e1-cbc2-484c-a46b-e9334586843b)
