### ISSUE TITLE
华为手机无法安装最新版本

### ISSUE THREAD

**Issue by yellowteaegg** [xiaojieonly/Ehviewer_CN_SXJ#742]
被鸿蒙系统列为管控项目，即使关闭增强，移除管控也无法解决无法安装的问题
![Uploading Screenshot_20230904_010539_com.huawei.appmarket.jpg…]()

**Comment by xiaojieonly** [comment]
华为是这样的

**Comment by xiaojieonly** [comment]
和APP没有关系

**Comment by xiaojieonly** [comment]
个人建议换个手机

**Comment by anshen007** [comment]
把他从管控列表里移出来就行
