### ISSUE TITLE
[功能建议]改进下载项打开速度

### ISSUE THREAD

**Issue by akatSS8** [xiaojieonly/Ehviewer_CN_SXJ#743]
在不挂梯子的情况下，APP内打开已下载项会经历非常长时间的载入，有时能长达二三十秒。考虑到使用其他图库软件打开图片的时间短很多，挂梯子的情况下时间接近，应该是打开下载项过程中向服务器发出了请求。
能否改为优先直接打开已下载内容，减少打开已下载内容的时间。

**Comment by xiaojieonly** [comment]
详情页数据不在下载范围内
