### ISSUE TITLE
[功能建议]在无法连接服务器的情况下显示下载项封面

### ISSUE THREAD

**Issue by akatSS8** [xiaojieonly/Ehviewer_CN_SXJ#744]
在下载完成后，图集的封面图已下载的情况下，不挂梯子打开下载，已下载完成的图集不显示封面，导致无法靠封面查找内容。
能否用已下载的图片作为封面显示或直接下载作为封面的缩略图？
封面缩略图的大小应该不大吧。

**Comment by xiaojieonly** [comment]
已有略缩图缓存，正常断网情况下，若果有略缩图缓存会正常显示略缩图，建议检查下是不是被手机系统清理垃圾的时候把缓存数据清了
