### ISSUE TITLE
图片下载限额 （不知道算不算是问题）

### ISSUE THREAD

**Issue by Ishimagikarp** [xiaojieonly/Ehviewer_CN_SXJ#746]
在以前eh还没有被高墙的时候，每天能下载很多作品，但是在必须使用vpn以后，每次下载一小会就会直接跳出图片限额用尽，基本上几页就会这么来一次。必须要不停的换节点 才能够继续下载，但是下载一会以后又会显示用尽。我测试过几天不下载作品，但是这个问题依然在。不清楚这是什么原因

**Comment by rex10189** [comment]
现在eh也不需要vpn。
用vpn下载限额最直接的理由就是你的vpn不是私人ip是很多人共用的，不是一个人在用当然一下就限额用尽。

**Comment by Ishimagikarp** [comment]
> 现在eh也不需要vpn。 用vpn下载限额最直接的理由就是你的vpn不是私人ip是很多人共用的，不是一个人在用当然一下就限额用尽。

原来是这样，谢谢。不过现在我直接打开eh还是会出现网络错误，是因为什么原因吗？,目前是在国内，使用EHviewer 会超时

**Comment by HeJueyin** [comment]
为什么下载了半天进度还是 0
