### ISSUE TITLE
画廊中已下载完的本子时不时消失

### ISSUE THREAD

**Issue by rex10189** [xiaojieonly/Ehviewer_CN_SXJ#747]
有时候已经下载完的本点开观看，退出程序后重进本子会从画廊预览目录中消失 搜索画廊也搜索不出。
但从历史记录点进该本仍显示已下载，点下载会显示已添加到至下载列表 app上方弹出的下载提示点进去转跳是没有东西的，只能点进去把已下载里删除了再下载才能重新在画廊目录里显示。

eh版本1.9.5.8 ，手机Xperia 1 IV，安卓版本12

**Comment by rex10189** [comment]
搜了下消失相关的问题，有一个问题贴底下有人回复说文件是被挪到了列表最下面。但我这个应该不是这种情况，被挪到下面搜索画廊关键词应该也能搜出来，但我除了消失的那个其他都能搜出来 只有这个不见。

**Comment by lx3852043** [comment]
> 搜了下消失相关的问题，有一个问题贴底下有人回复说文件是被挪到了列表最下面。但我应该不是这种情况，被挪出来到这个下面搜索画廊关键词应该也能搜，但我除了消失的那个以外，到处都搜不到这个。

明明就是整个文件被删除了，我下了七百多个本子，无端端被删除剩下两百多个。昨天重新下了的，今天一看又没了

**Comment by lx3852043** [comment]
昨天下好了几个，早上一打开又没了。。

**Comment by xiaojieonly** [comment]
是不是权限没给？

**Comment by xiaojieonly** [comment]
应该是系统删的，APP不会无缘无故删东西
