### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Udciydhiites** [xiaojieonly/Ehviewer_CN_SXJ#752]
![Uploading Screenshot_2023_0914_145608.jpg…]()
![Uploading Screenshot_2023_0914_145300.jpg…]()
软件无法登录，网页登录没有验证码

**Comment by xiaojieonly** [comment]
用Cookie登录试试

**Comment by Udciydhiites** [comment]
> 用饼干登录试试

饼干需要特定的代码，不会使用啊
