### ISSUE TITLE
饼干cookie

### ISSUE THREAD

**Issue by Udciydhiites** [xiaojieonly/Ehviewer_CN_SXJ#755]
![Screenshot_2023_0917_085828](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/144997563/c732f028-def8-4e5c-877e-d228d0b46289)
该怎么获取饼干登录的文本，怎么使用啊

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11
