### ISSUE TITLE
关于导入数据后显示倒入成功但实际无导入的问题

### ISSUE THREAD

**Issue by vinda99** [xiaojieonly/Ehviewer_CN_SXJ#758]
导入数据后显示倒入成功，但实际数据未导入。
![Screenshot_2023-09-24-01-36-37-618_moe tarsin ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/61115093/27336489-7578-4882-a863-914a1bee81b0)
![Screenshot_2023-09-24-01-36-42-316_moe tarsin ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/61115093/76e8e8c5-0096-4e74-b692-458de684adc5)
![Screenshot_2023-09-24-01-36-48-305_moe tarsin ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/61115093/aa3c5ac2-94e2-44a3-ad2a-8e716f811484)

**Comment by BBQMASTERHE** [comment]
+1

**Comment by xiaojieonly** [comment]
能发下.db文件吗？

**Comment by xiaojieonly** [comment]
已修，下一版上
