### ISSUE TITLE
下载未完成的本子，点继续下载会全部重新再下载一遍

### ISSUE THREAD

**Issue by lzq14984** [xiaojieonly/Ehviewer_CN_SXJ#761]
下载本子，比如1未完成，点全部暂停，再点全部开始，未完成的会全部重新下载，点进去所有页也是重新在线加载，这是啥情况？

**Comment by 2064302020** [comment]
我也遇到了

**Comment by xiaojieonly** [comment]
那是在检查有没有没下载的图片

**Comment by 2064302020** [comment]
但是更新是时候一样从第一页开始要用整个本子相同流量重新检查，而且不能断开不然要重新检查。
更新前的图片我本地的图片是已经下载了，不知道为什么检查的时候还要下。
难道是我本子页数太大了或者有什么其他原因。
