### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by brokenheart164** [xiaojieonly/Ehviewer_CN_SXJ#762]
请问是不是手机系统太高而导致无法裸连和加速器的使用（每次挂一下加速器就要被ban7天）。以前用荣耀手机都可以不被卡  但自从换了IQOO11后就没办法连接了 （PS：一直都是有新版本就更新版本）。

**Comment by xiaojieonly** [comment]
手机问题，抱歉

**Comment by xiaojieonly** [comment]
建议换小米
