### ISSUE TITLE
里站无法加载预览图，缩略图，封面图  版本1.9.5.9

### ISSUE THREAD

**Issue by LeviLars** [xiaojieonly/Ehviewer_CN_SXJ#765]
已开host  Sni  安全dos关闭否则无法加载
不会贴图

**Comment by gmoloade** [comment]
我换了好几个版本 也没有画廊预览缩略图，，很怪

**Comment by LeviLars** [comment]
> 我换了好几个版本 也没有画廊预览缩略图，，很怪

我终于弄好了，你去下1.9.4.4然后把写在1.9.5.2那个host添加到自定义里就ok了

**Comment by jdbxhxjf** [comment]
> > 我换了好几个版本 也没有画廊预览缩略图，，很怪
> 
> 我终于弄好了，你去下1.9.4.4然后把写在1.9.5.2那个host添加到自定义里就ok了

1.9.5.2的host在哪里看啊 我没找到 可发一下吗
