### ISSUE TITLE
[建议] 无法连接时显示建议操作

### ISSUE THREAD

**Issue by duzhaokun123** [xiaojieonly/Ehviewer_CN_SXJ#77]
开vpn时连不上，内置hosts关了再试，还不行换个节点再试，再不行浏览器看能连上不(别用国产浏览器)，能连上再来问，连不上不是应用的问题别来问

#76 #74 #65 #64

另外创建Issues模板告诉用户来提问把各种信息带上

**Comment by 572289049** [comment]
#76 @xiaojieonly 大佬，设备：一台安卓5的手机，版本1.7.6.11；一台安卓7的手机，版本1.7.6.16；问题：两台手机都无法直连观看表站，挂上vpn观看表站，安卓5的手机显示网络错误，安卓7的手机显示解析失败；挂vpn观看里站，两台手机都没有问题，只是我这vpn的id资源老是被用完后显示509（e站机制），求恢复直连，或教一下怎么恢复，谢谢了。
ps：老作者的1.7.6版本挂vpn表站可以看里站不行；给挂vpn还看不了的朋友说一下【高级-代理-直接连接】有时候这样就可以看了，要挂vpn哦。
