### ISSUE TITLE
无法锁定cookie igneous字段

### ISSUE THREAD

**Issue by LUrenjia114** [xiaojieonly/Ehviewer_CN_SXJ#770]
使用公开cookie登录登录后每次打开软件进入都会被强制修改cookie igneous为“mystery”，导致无法访问里站，版本为1.9.5.9

**Comment by LUrenjia114** [comment]
回退版本到1.9.5.8依旧无效，每次重新打开软件后再次进入画廊详情就会寄，没有任何提示
![Screenshot_2023-10-04-23-54-33-213_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/146973719/ac82a3c2-8a27-4521-a52c-9dd23792c0b6)

**Comment by xiaojieonly** [comment]
设置->EH->锁定Cookie igneous字段

**Comment by LUrenjia114** [comment]
@xiaojieonly 我已经锁了，根本锁不住，是无法锁定
![Screenshot_2023-10-07-18-04-45-976_com xjs ehviewer-edit](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/146973719/1b1770cb-ca9f-44ea-95aa-5382cdb549e4)

**Comment by xiaojieonly** [comment]
那就是e站的问题，可能是ip有风险导致的

**Comment by xiaojieonly** [comment]
试试先关了cookie锁定，然后重新登陆，最后重新开启cookie锁定

**Comment by LUrenjia114** [comment]
@xiaojieonly 尝试过了依然无效，另外还尝试过卸载重新安装和更换网络，不管wifi还是数据流量甚至挂VPN都没有用，稳定在下次打开软件后进入任意画廊后强制修改cookie（另外咱问题没解决呢不要那么快关闭issue好吗😥）
