### ISSUE TITLE
鸿蒙4.0后ehviewer被列入风险应用了，有什么方法把它移出风险应用

### ISSUE THREAD

**Issue by AiharaMei** [xiaojieonly/Ehviewer_CN_SXJ#771]
更新鸿蒙4.0系统后，ehviewer被列入风险应用无法安装，通过禁用应用商店后可以安装，但是安装后会有一个感叹号，并且无法赋予存储权限。
通过adb不删除缓存卸载在安装后可以解决感叹号问题和无法赋予权限的问题，但是还是提示我风险应用，在下次软件更新后安装依旧会有感叹号和无法赋予存储权限的问题。
有没有大佬知道如何把他从风险应用中移出。

**Comment by xiaojieonly** [comment]
个人建议回滚到3.0
或者换手机

**Comment by zxwwen** [comment]
手机管家→病毒查杀→解除管控；其实可以安装的吧，安装选了解风险就可以继续下一步了
