### ISSUE TITLE
无法锁定cookie igneous字段

### ISSUE THREAD

**Issue by LUrenjia114** [xiaojieonly/Ehviewer_CN_SXJ#772]
使用公开cookie登录登录后每次打开软件进入都会被强制修改cookie igneous为“mystery”，导致无法访问里站，使用锁定cookie功能依然无效，必须重新登陆持续到下次打开软件，版本为1.9.5.9，同时尝试过回退版本也无效
![Screenshot_2023-10-07-18-04-45-976_com xjs ehviewer-edit](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/146973719/4f1bcc03-88b5-4130-8f74-2416b9c02638)

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/770
