### ISSUE TITLE
希望改进下载项打开速度

### ISSUE THREAD

**Issue by akatSS8** [xiaojieonly/Ehviewer_CN_SXJ#773]
上次好像有点没说明白。
我的意思不是点下载条目左侧的图，打开详情页面半天打不开，是直接点其他部分，直接打开画廊内容，跳过详情页面。这个打开速度相比旧版的应用要慢很多。
按理说就算不存储详情页面，仅存储对应的文件夹名和图片量应该占不了多少空间吧。

**Comment by xiaojieonly** [comment]
网不好，已经下载好的画廊打开不会卡
