### ISSUE TITLE
希望能在下载后于本地图库 中生成详细信息文件

### ISSUE THREAD

**Issue by kikouousya** [xiaojieonly/Ehviewer_CN_SXJ#774]
已赞助，如果有必要，可以协助开发
希望能在开启功能后 下载到本地的图库中写入详细信息
具体需求：
  生成一个.info之类的隐藏文件
  以任意格式（比如json）写入以下信息
      画廊类型（DOUJINSHI, IMAGESET等）
      “查看更多信息” 中的键值对
      画廊tag
用途：本人正在个人开发图库管理软件（类似eagle或billfish），如果能自动读取eh中下载的内容信息，将不胜感激。 （项目地址：https://gitee.com/kikouousya/wandering/）

如有具体问题 可以后续协商 1377606604

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/a99c64c2-ad17-48d8-972f-c5375272d17e)
我更希望与开源项目合作

**Comment by xiaojieonly** [comment]
然后大部分必要信息都能通过固定方法获得，比如画廊名称就是文件夹名称，图片数量就是文件夹内图片数量

**Comment by xiaojieonly** [comment]
下载日期什么的，file里有对应方法，然后图片顺序也是通过文件名辨别的，我这边的规则是从0001.xxx——9999.xxx

**Comment by xiaojieonly** [comment]
如果你想要收回赞助金额，可以选择重新打开issue并留下微信号或者支付宝账号

**Comment by kikouousya** [comment]
是开源的呀 主要需要的信息是画廊类型和画廊tag ，这些信息无法直接从文件夹获得

**Comment by kikouousya** [comment]
看来是之前没有更新许可和手动公开，现在应该可以点进项目查看介绍了
