### ISSUE TITLE
预览100页以后的图片会闪退

### ISSUE THREAD

**Issue by huangmaotaozi** [xiaojieonly/Ehviewer_CN_SXJ#775]
搜索框详情页的快捷tag再点击以前搜索过的画师+汉语tag之后会与之前的搜索内容重叠如：
手动搜索artist:"clone ningen$"  l:"chinese$"之后在详情页点击搜索框上的artist:"clone ningen$"出现artist:"clone ningen$"  l:"chinese$"再点击会出现artist:"clone  artist:"clone ningen$"  l:"chinese$"然后搜不出结果

**Comment by xiaojieonly** [comment]
标题复现不出来，评论属于补全算法问题，目前建议手动进行纠错
