### ISSUE TITLE
One UI 5.1, Android 12 画廊浏览闪退

### ISSUE THREAD

**Issue by lixinlkmn2004** [xiaojieonly/Ehviewer_CN_SXJ#778]
1.9.5.9最新版在Android 12, one UI 5.1运行有问题，画廊预览超过200页左右时加载不出来，点开就闪退😭

之前老版本没有遇到这个问题，节点没问题，网页版也正常

**Comment by xiaojieonly** [comment]
关闭夜间模式试试

**Comment by xiaojieonly** [comment]
系统问题，我没有对应的手机复现不出来

**Comment by lixinlkmn2004** [comment]
[crash-2023-10-28-11-34-10-516.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/13194333/crash-2023-10-28-11-34-10-516.log)

**Comment by lixinlkmn2004** [comment]
大佬你看看能不能从这里找到bug，幸苦了，感谢

**Comment by lixinlkmn2004** [comment]
[Uploading logcat-2023-10-28-11-34-19-033.txt…]()

**Comment by lixinlkmn2004** [comment]
[Uploading logcat-2023-10-28-11-34-19-033.txt…]()
