### ISSUE TITLE
导出文件无法导入到NekoInverter 的版本的E中

### ISSUE THREAD

**Issue by Nightmare-Serene** [xiaojieonly/Ehviewer_CN_SXJ#78]

**Comment by duzhaokun123** [comment]
> 1.7.7.0更新了1.7.6.15的数据库，越过1.7.6.15版本更新可能会导致闪退，遇到的朋友可以尝试使用最新版本或先更新为1.7.6.15再更新为1.7.7.1。

都说了不兼容，所以这是 bug 还是 feature

**Comment by Nightmare-Serene** [comment]
先更新为1.7.6.15再更新为最新版本还是不行

**Comment by duzhaokun123** [comment]
> 先更新为1.7.6.15再更新为最新版本还是不行

不行就对了，由于收藏分享功能数据库大改动
1.7.6.15 的源码可能包含新旧数据库转换的代码，你可以给 NekoInverter 提关于数据库格式转换的 PR，但我估计他不会合并

**Comment by xiaojieonly** [comment]
没他源代码
