### ISSUE TITLE
使用“下载原图”选项下载时，只有 100b ~ 50b 的下载速度，但会出现限制会短时间被加速用完

### ISSUE THREAD

**Issue by Sonic853** [xiaojieonly/Ehviewer_CN_SXJ#781]
据观察，下载10秒出现 100b ~ 50b 的下载速度后限制会从0飙升到800，跑超5000只用了1分多钟。

版本号：1.9.5.9
站点：exhentai

**Comment by Pony-CW** [comment]
> 据观察，下载10秒出现 100b ~ 50b 的下载速度后限制会从0飙升到800，跑超5000只用了1分多钟。

这个我之前就有关注过，其实是不断下载重试的结果
从你加载/下载图片的那一刻起，e 站就把那张图片所需要消耗的量从图片配额里完全扣掉，**无论你有没有加载/下载成功**
> 也可能是分配到图片链接后就开始扣了

**Comment by xiaojieonly** [comment]
公共ip吗？
这个我爱莫能及，救不了
