### ISSUE TITLE
画廊闪退，下载分组混乱

### ISSUE THREAD

**Issue by Catinus** [xiaojieonly/Ehviewer_CN_SXJ#782]
SM-G973W
One UI 4.1, Android 12
有时浏览画廊会闪退
下载文件分类中的文件有时会被丢回default（感觉可能是闪退造成的？）
每次被丢回去的都好像是一样的几个

**Comment by TAT213** [comment]
经验之谈，在线看一个画廊，然后再看本地已缓存的相同作者画廊会高几率触发闪退，而那个被弹到默认分组的bug是很久的了，比较旧的本子在下载页面里面点进详情页也会被弹到默认，最近几个月下载的在下载页点进画廊不会弹到默认，但是在主页搜索的画廊点进详情页就会被弹到默认，只有刚刚下载的本子可以放心在主页、热门页面直接点详情，下载后关过一次app，在主页热门页面点进这个新的画廊也会被弹进默认分组。

**Comment by xiaojieonly** [comment]
更新到最新版试试
