### ISSUE TITLE
下载画廊排序出错

### ISSUE THREAD

**Issue by zizzdog** [xiaojieonly/Ehviewer_CN_SXJ#783]
这个bug好久了，看了看数据库里有些本时间戳莫名其妙消失了，导致全都跑到画廊底部了，啥时候修修呀

**Comment by zizzdog** [comment]
另外发现这些本的缩略图链接全是`https://s.exhentai.org`开头的，有时间戳正常的本都是`https://ehgt.org`开头的。不知道这之间是否有关联

**Comment by xiaojieonly** [comment]
最新版修好了
