### ISSUE TITLE
更新时，本子要重新下载且不能断开

### ISSUE THREAD

**Issue by 2064302020** [xiaojieonly/Ehviewer_CN_SXJ#786]
更新的时候从第一页开始要用整个本子相同流量重新检查，而且不能断开不然要重新从第一页开始检查。
更新前的图片我本地的图片是已经下载了，不知道为什么检查的时候还要下。
难道是我本子页数太大了或者有什么其他原因。

我完全删除本地后，重新下载就可以继续断点下载。

**Comment by TAT213** [comment]
说实话，更新基本没法用，之前有人说封面不一样的更新会导致整个画廊一直重新下载，但是封面不变的更新也会有更新页每次重新打开之后重新加载的现象

**Comment by 2064302020** [comment]
确实，因为这个更新功能很难搞。
不如直接取消，然后有新本子时，下载那直接把旧的删了重新建一个新的下载。现在大家也不缺这点流量。

**Comment by xiaojieonly** [comment]
更新的时候需要检查新画廊和旧画廊的图片排序和图片数量，所以在一些节点上需要重新下载

**Comment by xiaojieonly** [comment]
试试新版的更新逻辑，可以直接下载为新画廊
