### ISSUE TITLE
配额显示不正确

### ISSUE THREAD

**Issue by chikao2024** [xiaojieonly/Ehviewer_CN_SXJ#788]
我有10000的配额，可绿E只能显示5000，超过5000就无法下载了，彩E正常显示10000的配额也可以足量使用。希望尽快修复啊，本以为今天更新后就可以卸载彩E了。。。

**Comment by status102** [comment]
而且似乎有个问题是，显示的GP是总获取GP，而不是当前可用GP

**Comment by chikao2024** [comment]
是的，彩E显示的就是当前可用的GP，显示总获取GP又没啥卵用。

**Comment by 603185423** [comment]
感觉像是e站自己的问题, 我手机chrome上看到的是50000的配额, pc端chrome和ehv看到都是5000配额
![chrome-Android](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/50170900/5f171ae3-2f96-4889-82aa-15bacf9dc334)
![ehv](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/50170900/614a5f61-02e9-4d4a-a79f-75dc28596611)
![chrome-PC](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/50170900/ebf7353a-7fa2-4073-8b61-b9af9ccddda7)

**Comment by xiaojieonly** [comment]
可能和请求头有关，后续我研究下
