### ISSUE TITLE
关于自动跟随系统进入黑暗模式的功能

### ISSUE THREAD

**Issue by LeonCCCCC** [xiaojieonly/Ehviewer_CN_SXJ#789]
1.9.6.0往后版本因为避免某些设备的崩溃原因删除了自动跟随系统进入黑暗模式的功能，请问这个功能是否会在未来修复后重新添加？

**Comment by xiaojieonly** [comment]
问题太多，没有能力购买各种型号的手机，心有余而力不足，只能删除功能，如果以后有钱了，会重新加回来
