### ISSUE TITLE
关于新版本新的闪退问题

### ISSUE THREAD

**Issue by newtypeblue** [xiaojieonly/Ehviewer_CN_SXJ#790]
1.9.6.1更新后，左右两边侧边栏打开就会出现闪退，机型是红米k40s、安卓13、miui 14.0.6、显示模式是浅色模式非深色模式。

**Comment by chikao2024** [comment]
清除下数据就好，没有侧边栏闪退的问题一切正常。

**Comment by ypq123456789** [comment]
我也是，已经下载旧版本禁止自动更新了，等下个版本吧

**Comment by xiaojieonly** [comment]
> 1.9.6.1更新后，左右两边侧边栏打开就会出现闪退，机型是红米k40s、安卓13、miui 14.0.6、显示模式是浅色模式非深色模式。

收到，这周更新个修复版
