### ISSUE TITLE
词条不能搜索

### ISSUE THREAD

**Issue by 159357t** [xiaojieonly/Ehviewer_CN_SXJ#791]
![Screenshot_2023-10-18-02-57-02-728_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/124063120/e3f1843c-ece9-4c01-b93e-dc8258c03791)
如同上面显示词条搜索没有内容

**Comment by xiaojieonly** [comment]
加号去掉试试
