### ISSUE TITLE
加载配额闪退

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#792]
使用warp访问(或者ip被ban)时，滑动侧边栏开始加载配额后就会闪退
![Screenshot_2023-10-18-17-24-59-497_com.fankes.apperrorstracking.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/c1a5474f-257f-437a-9d28-608088d3a668)

**Comment by manhole231** [comment]
加一，更新至1.9.6.1版本后划开左侧边栏就会闪退。关闭网络后似乎就不闪退了，但是中途开启还是会闪退
