### ISSUE TITLE
关于配额功能仅面向少数用户

### ISSUE THREAD

**Issue by FuyukiAsahi** [xiaojieonly/Ehviewer_CN_SXJ#793]
如题，1.9.6.1版本中更新的显示用户配额功能对裸连/自建用户有用，但对于通常vpn/机场用户几乎无效，这个数字会不停由大到小滚动，而一般不需要花费GP点重置，只要换一个节点就能搞定（如果想确定配额是否上限，看见熊猫头就立刻知道了），或者提供方设置设备功能自动解决此问题，所以个人觉得配额功能也可以增加一个开关功能，不知意下如何

**Comment by chikao2024** [comment]
你不去管它不就行了，何必还要麻烦设个开关，增加可能产生的Bug

**Comment by Small-tailqwq** [comment]
对于部分根据账号计算配额的用户来说还是有用的。放在那里又不碍事，感觉没必要再改来改去。

**Comment by xiaojieonly** [comment]
之后会 提供一个显示的开关
