### ISSUE TITLE
求助 画廊图片加载完毕后还是会转圈圈不显示

### ISSUE THREAD

**Issue by anyi77766** [xiaojieonly/Ehviewer_CN_SXJ#796]
加载完毕后继续转圈圈或者根本没反应 
![Screenshot_2023-10-22-11-07-06-07_159c494ea8977f628e53d8d36755ba4c](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/148668866/a6fc3168-dbb8-42ed-8695-d2a9ce5df2c5)

**Comment by xiaojieonly** [comment]
网不好，可能是在还剩1%的时候断开连接了。。。建议手动点击重新加载试试

**Comment by anyi77766** [comment]
好的  我多试试看
