### ISSUE TITLE
移除已下载的画廊无法重新下载没有进度，移除掉的图片也无法在线阅读显示Invalid page红字错误

### ISSUE THREAD

**Issue by zhiheng13** [xiaojieonly/Ehviewer_CN_SXJ#797]
起因是这样的，由于画廊更新功能使用中出现了一些问题，例如显示已下载后点进去仍然需要在线加载、更新完成后的画廊与作者上传的顺序不符。为了解决这个问题，我决定手动移除掉已下载的画廊并重新进行下载。
        但在移除掉已下载的画廊并重新进行下载时，只能下载小部分图片（推测为之前没有下载过的新更新的图片），而大部分图片（推测为之前完成过下载的图片）无法下载显示下载速度为0持续一段时间并自动结束下载显示为x张图片未完成。
        且当手动点开进行过移除操作的画廊进行在线阅读操作时，只能查看小部分图片（推测为之前没有下载过的新更新的图片），而大部分图片（推测为之前完成过下载的图片）无法查看并显示Invalid page红字错误。
        我尝试了设置-高级功能中的清除画廊下载路径缓存和清理内存缓存、设置-下载功能中的清理下载冗余均无法解决这个问题。
        没有进行过移除操作的画廊均可以进行正常下载或在线阅读。

**Comment by Fullary** [comment]
个人解决方法：删除，退出app，重新打开，历史记录，下载。

**Comment by xiaojieonly** [comment]
楼上正解
