### ISSUE TITLE
为什么用一段时间后会显示509

### ISSUE THREAD

**Issue by hyysus** [xiaojieonly/Ehviewer_CN_SXJ#80]
RT

**Comment by Zyanni** [comment]
有个人流量限制，你看得太多限流了。除非换ip接着用

**Comment by 9992935454** [comment]
叫别人开个热点给你看😄

**Comment by hyysus** [comment]
这是固定的嘛

**Comment by hyysus** [comment]
为什么以前用原版就没限制，有办法解除吗

**Comment by duzhaokun123** [comment]
> 为什么以前用原版就没限制，有办法解除吗

这只能说明以前限制宽或以前你看的少
换加速器节点或给e站捐钱

**Comment by hyysus** [comment]
我以前看的量和现在差不多啊

**Comment by duzhaokun123** [comment]
@hyysus 

> 这只能说明 以前限制宽 ***或*** 以前你看的少

> 或
> huò
> 也许，有时，表示不定的词：或许。或者（a.也许；b. ***连词，用在叙述句里，表示选择关系。*** 均亦单用“或”）。或然。或则。

**Comment by xiaojieonly** [comment]
用最新的版本吧，大部分网都能裸连，除非实在是拉跨的网。509是配额用完了，这个问题我已经回答了无数次了，希望以后不要有人再问了。

**Comment by xiaojieonly** [comment]
> 用最新的1.7.10吧，大部分网都能裸连，除非实在是拉跨的网。509是配额用完了，这个问题我已经回答了无数次了，希望以后不要有人再问了。

更换IP可解

**Comment by EhvPicPor** [comment]
我看什么都显示解析失败是为什么啊

**Comment by M3-ai** [comment]
新年快乐

**Comment by 18845740098lwx** [comment]
ip是什么咋换啊

**Comment by rainbooooom** [comment]
配额飙升巨快，只浏览几张就可以飚到几百。

**Comment by Evananly** [comment]
哦天哪，为什么更新完。。。没弹出下载，而且一直显示网络错误

**Comment by shadouxing8** [comment]
怎么给站主捐钱？

**Comment by 249693823** [comment]
> 用最新的版本吧，大部分网都能裸连，除非实在是拉跨的网。509是配额用完了，这个问题我已经回答了无数次了，希望以后不要有人再问了。

怎么提高配额呢？

**Comment by supedaie** [comment]
这种情况咋整
![Uploading Screenshot_2024-10-11-15-31-47-73_159c494ea8977f628e53d8d36755ba4c.jpg…]()

**Comment by supedaie** [comment]
这种情况咋整
![Screenshot_2024-10-11-15-31-47-73_159c494ea8977f628e53d8d36755ba4c](https://github.com/user-attachments/assets/d8fe81bc-1ecd-4dab-9c5b-7f949cabe6a6)

**Comment by 2up2** [comment]
捐赠完还是不能看怎么办

**Comment by wumai1457-beep** [comment]
真他妈又不显示的毛病 我* 
更新啥也没改

**Comment by Chara2099** [comment]
我现在有个情况，有些系列本每个本都是有一页509，只有一页，而且换ip也不行，怎么回事呢？🤔
