### ISSUE TITLE
今天下載/閱讀 都解解析失敗

### ISSUE THREAD

**Issue by 661266** [xiaojieonly/Ehviewer_CN_SXJ#800]
同標題 縮圖可以正常看 但點進去都解析失敗

**Comment by jack34142** [comment]
我是本來看的好好的, 從剛剛開始就只會跑出一張圖, 其他都解析失敗

**Comment by 661266** [comment]
真的就很突然

**Comment by Miukind** [comment]
+1

**Comment by AiharaMei** [comment]
我也遇到了

**Comment by TingYeeet** [comment]
相同狀況+1

**Comment by neverwatch233** [comment]
我还以为我网有问题

**Comment by Yankumo-Koishi** [comment]
我还以为就我这样，原来大家都有同样的问题啊，那没事了
所以到底是怎么回事呢

**Comment by caoshu0725** [comment]
+1

**Comment by jiyi-jiyi** [comment]
+1

**Comment by hdjsheifnjs** [comment]
同，早上还好好的

**Comment by SZY503** [comment]
同样求解决

**Comment by jiangdashi495** [comment]
同问题

**Comment by chikao2024** [comment]
今天所有的E都是这样，有很不详的预感，可能出大事了。。。

**Comment by Yankumo-Koishi** [comment]
> 今天所有的E都是这样，有很不详的预感，可能出大事了。。。

丁真？其他的EH客户端也是这样吗

**Comment by Lununz** [comment]
> > 今天所有的E都是这样，有很不详的预感，可能出大事了。。。
> 
> 丁真？其他的EH客户端也是这样吗

丁真，彩eh下午开始也解析失败了

**Comment by DidyouseetheSunrise** [comment]
+1

**Comment by YLchen22** [comment]
+1

**Comment by FuyukiAsahi** [comment]
+1

**Comment by infotion** [comment]
> > 今天所有的E都是这样，有很不详的预感，可能出大事了。。。
> 
> 丁真？其他的EH客户端也是这样吗

虽然只是瞎猜，但是感觉大的药来了（）

**Comment by slwy1303357042** [comment]
> > > 今天所有的E都是这样，有很不详的预感，可能出大事了。。。
> > 
> > 
> > 丁真？其他的EH客户端也是这样吗
> 
> 虽然只是瞎猜，但是感觉大的药来了（）

还能怎么来？顶多就是不能直连了吧，总不至于完全用不了了吧

**Comment by infotion** [comment]
> > > > 今天所有的E都是这样，有很不详的预感，可能出大事了。。。
> > > 
> > > 
> > > 丁真？其他的EH客户端也是这样吗
> > 
> > 
> > 虽然只是瞎猜，但是感觉大的药来了（）
> 
> 还能怎么来？顶多就是不能直连了吧，总不至于完全用不了了吧

目前在电脑上面直接去exhentai.org还是可以看的，可能ex那边后台骚操作把viewer的路堵死了（）

**Comment by Small-tailqwq** [comment]
最新发布版本已经修复了啊，使用hk节点关闭内置host和域前置等杂七杂八的功能能够正常观看。更新前同设置下部分漫画只能加载前几页，感觉是e那边自己的问题。

**Comment by slwy1303357042** [comment]
> 最新发布版本已经修复了啊，使用hk节点关闭内置host和域前置等杂七杂八的功能能够正常观看。更新前同设置下部分漫画只能加载前几页，感觉是e那边自己的问题。

那再等等说不定就好了

**Comment by neverwatch233** [comment]
最新版本已经修复了

**Comment by slwy1303357042** [comment]
> 最新版本已经修复了

我直连情况下还是跟之前一样

**Comment by Small-tailqwq** [comment]
> > > 今天所有的E都是这样，有很不详的预感，可能出大事了。。。
> > 
> > 
> > 丁真？其他的EH客户端也是这样吗
> 
> 虽然只是瞎猜，但是感觉大的药来了（）

https://e-hentai.org/news.php
今天正好网站更新了而已，别想太多，打个脚先

**Comment by xiaojieonly** [comment]
修好了
