### ISSUE TITLE
关于每次下载只能下载一页的问题反馈

### ISSUE THREAD

**Issue by caoshu0725** [xiaojieonly/Ehviewer_CN_SXJ#801]
第一次发问题，就是标题里写的那样，点击下载以后一次只下载一页然后就会中断，是挂着梯子出现的问题
以及不挂梯子的话下载速度一直是0，不知道这是我个人的问题还是说不挂梯子就都是这样呢。

**Comment by SZY503** [comment]
现都是只能看一页

**Comment by caoshu0725** [comment]
最新版可以正常使用了，此帖完结
