### ISSUE TITLE
关于下载问题。

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#802]
当我更新到1.9.6.2的时候，下载会莫名其妙的停止，Gp也始终停在0/5000没有改变但是下载总是失败，原因未知。

**Comment by TAT213** [comment]
之前还没问题，今天画廊都是下载一页就失败

**Comment by BreakFaith01** [comment]
对啊，昨天晚上还好好的，今天就是下载就解析失败，然后停止。


?Break&nbsp;Faith?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 晚上6:26
***@***.***&gt;;
抄送:&nbsp;"♛Break ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] 关于下载问题。 (Issue #802)





 
之前还没问题，今天画廊都是下载一页就失败

**Comment by xwt961125** [comment]
遇到相同问题，每次都是下载一页左右就被ban

**Comment by SauronSkywalker** [comment]
我也是，下载的时候每次只能下一两张就下不动了，但是在线看图没问题

**Comment by slwy1303357042** [comment]
> 我也是，下载的时候每次只能下一两张就下不动了，但是在线看图没问题

你在线看图没问题？我在线只能看一页，其他全部解析失败，要下载了才能看，但是下载下一页卡一页，就很麻烦

**Comment by xiaojieonly** [comment]
网络不稳定

**Comment by xiaojieonly** [comment]
> > 我也是，下载的时候每次只能下一两张就下不动了，但是在线看图没问题
> 
> 你在线看图没问题？我在线只能看一页，其他全部解析失败，要下载了才能看，但是下载下一页卡一页，就很麻烦

这个问题最新版已经修好了
