### ISSUE TITLE
下载了最新版还是会显示解析失败

### ISSUE THREAD

**Issue by hdjsheifnjs** [xiaojieonly/Ehviewer_CN_SXJ#803]
点进去的第一张图能加载的出来，但之后就仍然会解析失败 1.9.6.4也不行

**Comment by YLchen22** [comment]
+1

**Comment by 661266** [comment]
+1  1.9.6.4 也不行

**Comment by Evi1Bubble** [comment]
+1

**Comment by YingYeGui** [comment]
1.9.6.4也还是不行

**Comment by infotion** [comment]
现在6.4还是不行，在本站网页访问是正常的

**Comment by guanzile** [comment]
大佬，1.9.6.3也还是解析失败，救救孩子

**Comment by chikao2024** [comment]
问题解决了，最新的1.9.6.4可以正常解析和下载了。

**Comment by Small-tailqwq** [comment]
产生更换节点，关闭内置host与域前置功能

**Comment by chikao2024** [comment]
> 问题解决了，最新的1.9.6.4可以正常解析和下载了。

望xiaojie告知这次为何会遇到这种问题？

**Comment by slwy1303357042** [comment]
> 问题解决了，最新的1.9.6.4可以正常解析和下载了。

我直连还是跟之前一样的问题

**Comment by Small-tailqwq** [comment]
> > 问题解决了，最新的1.9.6.4可以正常解析和下载了。
> 
> 望xiaojie告知这次为何会遇到这种问题？

因为e站网页更新了，可以自己上去看看更新日志

**Comment by Small-tailqwq** [comment]
> > 问题解决了，最新的1.9.6.4可以正常解析和下载了。
> 
> 我直连还是跟之前一样的问题

那就不要直连，你都能上GitHub了你开个节点试试看先。

**Comment by xiaojieonly** [comment]
修好了

**Comment by xiaojieonly** [comment]
> > 问题解决了，最新的1.9.6.4可以正常解析和下载了。
> 
> 望xiaojie告知这次为何会遇到这种问题？

E站把页面结构改了

**Comment by slwy1303357042** [comment]
> > > 问题解决了，最新的1.9.6.4可以正常解析和下载了。
> > 
> > 
> > 我直连还是跟之前一样的问题
> 
> 那就不要直连，你都能上GitHub了你开个节点试试看先。

6.5可以了
