### ISSUE TITLE
新版1.9.6.5因应用自身空指针异常闪退

### ISSUE THREAD

**Issue by yxxyul** [xiaojieonly/Ehviewer_CN_SXJ#805]
手机型号小米13，版本号MIUI14.0.24

**Comment by yxxyul** [comment]
#
![Uploading 16984199806795988221505068273730.jpg…]()

**Comment by yxxyul** [comment]
![Uploading 16984199806795988221505068273730.jpg…]()

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/d4b7cb28-854a-4694-abba-0ce5f1b56c44)
看不到图

**Comment by yxxyul** [comment]
![16984199806795988221505068273730](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/117347075/ef8e2bbb-a917-45ba-bdb3-d48b0c95b186)

**Comment by yxxyul** [comment]
> ![图像](https://user-images.githubusercontent.com/49278135/278807399-d4b7cb28-854a-4694-abba-0ce5f1b56c44.png) 看不到图

不好意思，重新发了一张

**Comment by xiaojieonly** [comment]
在修了，马上会发布新版
