### ISSUE TITLE
关于长按已下载或閑置中本子的问题，想请教一下

### ISSUE THREAD

**Issue by FrankTaiki** [xiaojieonly/Ehviewer_CN_SXJ#807]
之前的版本在已经下载过或闲置中的本子，只要长按下载都会再次下载的功能，已经移除了吗。还挺方便的，点通知都能跳到下载的便签位置
现在下载长按只会跳出移除下载而已。

**Comment by xiaojieonly** [comment]
我记得这部分我没改过来着，如果不影响使用的话先这样吧？
