### ISSUE TITLE
求教 如何设置下载高质量的原图

### ISSUE THREAD

**Issue by Zhai-Wang** [xiaojieonly/Ehviewer_CN_SXJ#81]
漫画封面的“下载”似乎下载的分辨率较低 能在哪里设置吗
顺便问一下 同样的梯子 为什么pc端用浏览器访问e站就白屏 手机用浏览器却能正常显示
pc和手机端用的都是chrome 清理cookie也试过了

**Comment by xiaojieonly** [comment]
因为手机上请求的时候我帮你把请求加密了所以过墙的时候没有被拦截掉，而电脑上你没有加密请求导致请求直接被墙拦截了

**Comment by xiaojieonly** [comment]
设置->下载里有下载原图的选项
