### ISSUE TITLE
报毒问题

### ISSUE THREAD

**Issue by xqc114** [xiaojieonly/Ehviewer_CN_SXJ#811]
oppo A72 5G,安卓12,color os 12.1。下载1.9.6.5版本时报高危无法安装，下载1.9.6.2则不会出现该问题。希望提供无高危安装包

**Comment by YXFY123** [comment]
同样的问题，最新版本被手机自带管家拉黑名单了，希望作者能解决一下

**Comment by xiaojieonly** [comment]
与我无关，手机厂商问题，解决不了
