### ISSUE TITLE
预览设置为40行时的闪退问题

### ISSUE THREAD

**Issue by yoyokirby** [xiaojieonly/Ehviewer_CN_SXJ#812]
感谢作者保持维护更新，抱歉新开一次，之前那个太长而且找不到了(
由于本次解析失败不得不尝试了新版本，之前停在1.9.5.0了，发现现在只要不设置成40就不会闪退。

触发步骤：
1.设置为40行预览(无关预览图size为normal或large)，具体为Thumbnail Settings-You can set a default thumbnail configuration for all galleries you visit.-rows：选择40。
2.打开一个图片较多的画廊(200张或400张以上程度？杂志期刊或CG集居多)
3.进入查看更多预览画面(可以翻预览页的那个)
4.点击任意图片进入单图查看模式→此时闪退

暗黑模式：
无论开启或关闭暗黑模式均会触发

设置行数：
设置为20行/10行/4行预览时，不会出现。仅40行会出现。

App版本：
经我测试，在最新的1.9.6.5可以复现。
在1.9.5.0不会出现。
在1.9.5.1开始出现。

平台：
此前的版本于Mate40 Pro与MatePad Pro 12.6 2022上进行测试。
本次1.9.6.5于Mate60 Pro与MatePad Pro 13.2上进行测试。

本问题不是很紧急，因为20行也不是不能用。如果作者需要各类日志报告麻烦说下做法。感谢。

**Comment by yoyokirby** [comment]
[crash-2023-10-28-11-41-24-694.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/13194357/crash-2023-10-28-11-41-24-694.log)

**Comment by xiaojieonly** [comment]
1

**Comment by luoziyuan97** [comment]
您提的这个闪退问题同样困扰了我很久，之前也是没办法一直用的1.9.5.0，前几天因为解析失败问题被迫升级到1.9.6.5，然后发现还是闪退。但是刚刚看了下您提到的预览行数，发现我的是4并且选不了其他选项（10/20/40行貌似都需要捐赠解锁）

**Comment by yoyokirby** [comment]
> 您提的这个闪退问题同样困扰了我很久，之前也是没办法一直用的1.9.5.0，前几天因为解析失败问题被迫升级到1.9.6.5，然后发现还是闪退。但是刚刚看了下您提到的预览行数，发现我的是4并且选不了其他选项（10/20/40行貌似都需要捐赠解锁）

我目前的情况是有极个别的画廊会在20行闪退，绝大多数不会，没有发现规律。(并非页数多少，错误日志报错内容类似，仅数字不同)

你可以在设置-高级里打开应用崩溃时保存错误日志。触发崩溃后在系统目录/EhViewer/crash里找到日志并上传。另外你使用的机型/系统是？

更多行数除了捐赠也可以使用Hath兑换解锁，Hath可以使用GP和C进行兑换，GP和C可以通过上传画廊或运行H@H帮助分担服务器压力获得。此处仅是说明兑换方式。

**Comment by luoziyuan97** [comment]
[crash-2023-11-01-10-13-18-011.log](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/13222743/crash-2023-11-01-10-13-18-011.log)
设备为 荣耀X40GT，系统MagicOS 7（安卓12）
感谢您的帮助

**Comment by xiaojieonly** [comment]
已修

**Comment by luoziyuan97** [comment]
感谢作者大大，感谢楼主

**Comment by xiaojieonly** [comment]
跟新到最新版看看吧

**Comment by yoyokirby** [comment]
感谢，新版目前为止没有遇到闪退了。
