### ISSUE TITLE
划出菜单触发配额查询就看不了了

### ISSUE THREAD

**Issue by hswnice** [xiaojieonly/Ehviewer_CN_SXJ#813]
旧版本没事,更新配额查询之后只要划出菜单,再打开任何页面都是一个哭脸安卓图标,甚至其他EH客户端也用不了了,切换节点之后就都恢复了,但是之前操作过的节点就再也用不了了

**Comment by RX93CN** [comment]
还可能导致闪退，闪退重启后又一切正常。只是闪退会时不时在划出菜单栏时发生

**Comment by xiaojieonly** [comment]
复现不出来，应该是梯子的问题
