### ISSUE TITLE
终于找到个能用的版本 感谢作者 但我有个问题

### ISSUE THREAD

**Issue by bushisegui** [xiaojieonly/Ehviewer_CN_SXJ#814]
以前用的是彩e 转成绿e后本地一堆下载好的在列表里找不到
试着导入数据也没找到
但本地文件可以查看 
请问要修改什么文件或者配置才能导入吗
求好兄弟们教教我
谢谢

**Comment by NANADAIBA** [comment]
同问，我也是在彩E上面下的一堆资源，想知道怎么导入到绿E里

**Comment by NANADAIBA** [comment]
兄弟，找到办法了
现在彩E上点设置-高级-导出数据，把数据放到你手机里的EhViewer/data文件夹里，
然后打开绿E点设置-高级-导入数据，选中你刚刚放进来的那个数据，多试几次，重启重启，就可以看到绿E的下载里有之前的下载记录了，
我的彩E下载目录在Android/data的彩E目录下面，但绿E选下载目录的时候看不到data文件夹（红米手机），希望你能试试看

**Comment by bushisegui** [comment]
> 兄弟，找到办法了 现在彩E上点设置-高级-导出数据，把数据放到你手机里的EhViewer/data文件夹里， 然后打开绿E点设置-高级-导入数据，选中你刚刚放进来的那个数据，多试几次，重启重启，就可以看到绿E的下载里有之前的下载记录了， 我的彩E下载目录在Android/data的彩E目录下面，但绿E选下载目录的时候看不到data文件夹（红米手机），希望你能试试看

无法读取文件 估计需要修改什么

**Comment by galeondx** [comment]
同上 無法讀取

**Comment by BBQMASTERHE** [comment]
我这是显示导入成功但，实际上没有导入

**Comment by xiaojieonly** [comment]
额，这个我没太好的办法。。。

**Comment by Jake-Habert** [comment]
> 兄弟，找到办法了 现在彩E上点设置-高级-导出数据，把数据放到你手机里的EhViewer/data文件夹里， 然后打开绿E点设置-高级-导入数据，选中你刚刚放进来的那个数据，多试几次，重启重启，就可以看到绿E的下载里有之前的下载记录了， 我的彩E下载目录在Android/data的彩E目录下面，但绿E选下载目录的时候看不到data文件夹（红米手机），希望你能试试看

尝试了一下，我是红米K60，无法读取但是列表恢复了，虽然恢复了但是每个画廊都点不进去，2200+个画廊如果要我手动恢复多少配额都不够我使的（悲

**Comment by AntiLain** [comment]
高版本(>12)安卓的/data在不root的情况下应该是仅对所属应用本身和原生文件管理器开放读取权限

**Comment by Jake-Habert** [comment]
> 高版本(>12)安卓的/data在不root的情况下应该是仅对所属应用本身和原生文件管理器开放读取权限

应该不是这个问题，因为我彩E的下载路径是重新选择了文件夹，并非Android/Data目录下

**Comment by lunaticruna** [comment]
我也遇到这个问题了，因为不太懂安卓开发，没法研究导入部分的代码，所以主要是从导出的数据库文件入手的：
1. 如果可以的话，尝试删除彩E导出db文件中的room_master_table表，这个表在绿E的导出文件里不存在；
2. 如果你和我一样是绿E->彩E->绿E这样来回导入导出的话，可以尝试重新清掉绿E的数据后重新导入；我猜绿E导入彩E的db时候有主键冲突导致导入失败了，但是不能确定；

目前我这是已经导入成功了，虽然导入时提示“无法读取文件”，但是多导入几次，下载列表里的数据已经恢复进来了。如果有类似情况的话，可以参考下。。个人感觉问题2的因素可能大一点。

**Comment by Jake-Habert** [comment]
> 我也遇到这个问题了，因为不太懂安卓开发，没法研究导入部分的代码，所以主要是从导出的数据库文件入手的：
> 
>     1. 如果可以的话，尝试删除彩E导出db文件中的room_master_table表，这个表在绿E的导出文件里不存在；
> 
>     2. 如果你和我一样是绿E->彩E->绿E这样来回导入导出的话，可以尝试重新清掉绿E的数据后重新导入；我猜绿E导入彩E的db时候有主键冲突导致导入失败了，但是不能确定；
> 
> 
> 目前我这是已经导入成功了，虽然导入时提示“无法读取文件”，但是多导入几次，下载列表里的数据已经恢复进来了。如果有类似情况的话，可以参考下。。个人感觉问题2的因素可能大一点。

尝试了一下2，仍然是只能恢复列表，但每一个都无法打开，点进去会重新下载，并且似乎不会覆盖彩E的下载文件，在绿E重新下载并删除后彩E仍可以秒开且没有下载活动，导入列表后在下载选项选项里选择恢复下载项也无法恢复下载文件

**Comment by Jake-Habert** [comment]
https://github.com/FooIbar/EhViewer
这是彩E新版的的下载地址，作者换人了，你如果之前用的是彩E直接更新就好了
