### ISSUE TITLE
新功能请求-需要一个设置首页内容区的封面图和每条内容显示大小的选项

### ISSUE THREAD

**Issue by bhkz0510** [xiaojieonly/Ehviewer_CN_SXJ#815]
首先非常感谢作者制作并持续更新这款应用；在平板或其他更大屏幕的设备上使用此应用时，首页内容区的每条文本文本和其封面图片却不会跟随屏幕比例而放大，导致有时候很难看清封面的内容。希望作者可以添加一个可更改它们显示大小的选项，万般感谢！

**Comment by xiaojieonly** [comment]
以后再说
