### ISSUE TITLE
裸连“网络错误”，代理“解析失败”

### ISSUE THREAD

**Issue by RC-1140Fixer** [xiaojieonly/Ehviewer_CN_SXJ#817]
如题，本来是用彩色的，现在下载了最新版修复“解析失败”的1.9.6.5版本，情况更糟了，主页都显示“解析失败”。

设备：三星Galaxy Tab S8+
系统：oneUI 5.1.1，Android 13

![Screenshot_20231028_163853_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/39910382/112668e4-2cf9-40bb-95f0-08f379700e7e)

**Comment by xiaojieonly** [comment]
[常见问题汇总](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/feedauthor/EhviewerIssue.md)
