### ISSUE TITLE
新功能请求-评论时增加反馈提示

### ISSUE THREAD

**Issue by fear1999** [xiaojieonly/Ehviewer_CN_SXJ#818]
每次E站有什么API更新导致APP不能适配，一看站里评论区全是一堆巨婴在伸手求援，真的很让人反感。
能不能在弹出评论框时顺便弹个toast，说不要在站内评论区反馈第三方APP的Issue，或者在评论框边上放上Github issue page的link。
当然这不是APP的问题，APP很好，但用的人多了就有需要加点防巨婴功能。

**Comment by maz-1** [comment]
个人认为加在更新提示或更新后的changelog里就可以了，加到评论功能里太影响体验了。知道这么做不合适的自然就不做了，打死不改的巨婴提醒再多遍也没用。

**Comment by cztoki** [comment]
个人认为在更新提示或更新后的changelog里稍微提醒一下就可以了，加到评论功能里太影响体验了。知道这么做不合适的自然就不做了，打死不改的巨婴提醒再多遍也没用。

**Comment by AntiLain** [comment]
巨婴是约束不了的，看到那种评论点个vote-就行了

**Comment by Small-tailqwq** [comment]
> 巨婴是约束不了的，看到那种评论点个vote-就行了

赞同，app有问题的情况不顺路找到原发布的地方更新获取最新消息跑去人家画廊下面刷无意义评论只能吃我-8了
