### ISSUE TITLE
同一账号在2个设备上使用，一台可以ex，另一台不行

### ISSUE THREAD

**Issue by CharlesLTH** [xiaojieonly/Ehviewer_CN_SXJ#82]
不行的那一台机器，ex站只显示一个哭泣的安卓头，没有错误提示，可以访问表站

电脑网页、另一台设备均可以访问ex

**Comment by CharlesLTH** [comment]
已尝试注册新账号，仍然是无法访问里站
安卓8，无google框架
尝试进入软件设置里面的"EHentai设置"，发现无法加载网页
形况应该是软件无法读取账户的信息

**Comment by xiaojieonly** [comment]
额，安卓8得挂梯子
