### ISSUE TITLE
页数过多时，选择加载后面会闪退

### ISSUE THREAD

**Issue by RX93CN** [xiaojieonly/Ehviewer_CN_SXJ#822]
一份387页的同人志，中间150页左右没问题，如果直接从缩略图的300左右点进去观看，会直接闪退。过长的页数从末尾处进去观看都会直接闪退

**Comment by RX93CN** [comment]
更正:是空指针导致的，请作者修复一下
![Uploading IMG_20231030_010810.jpg…]()

**Comment by RX93CN** [comment]
![IMG_20231030_010810](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/110704357/0d6b3f0f-2275-4559-90fc-a42de66574d5)

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/f28e1d3b-d1e7-41b1-a3bf-37187d8e5071)
图片没上传完

**Comment by RX93CN** [comment]
> ![image](https://user-images.githubusercontent.com/49278135/279237970-f28e1d3b-d1e7-41b1-a3bf-37187d8e5071.png) 图片没上传完

下面这张就是没上传完的

**Comment by xiaojieonly** [comment]
修好了，今天会发一半
