### ISSUE TITLE
关于无预览图可能的解决方案，希望作者大大能给1.9.4.5版本修复一下解析失败

### ISSUE THREAD

**Issue by Achievement42** [xiaojieonly/Ehviewer_CN_SXJ#823]
试了近10个版本，唯独1.9.4.5版本之前的能正常显示预览图，可能是手机太老了，最新版怎么设置都没有预览图，直连挂梯子都尝试过了。

**Comment by gnflance** [comment]
我也是同样情况，最近更新后就没有预览图了

**Comment by Barryber** [comment]
我也是，只有1.9.4.5可以正常顯示，但會顯示解析失敗，若是新版本則是沒有縮略圖但能解析

**Comment by xiaojieonly** [comment]
建议将列表模式从略缩图改为详情，设置->EH->列表模式
