### ISSUE TITLE
Images fail to load, app says "Error analysis"

### ISSUE THREAD

**Issue by crankgud** [xiaojieonly/Ehviewer_CN_SXJ#824]
Whenever trying to read or look at a gallery, the app only gets to load a single image and the rest display "Error analysis" text.

To be able to let the app to load a different image: I have to get out of the gallery, turn off Wifi or Data, turn it back on and get into the gallery and hope the image that loads is the one that goes after the one I was previously looking at.

![Screenshot](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/137563191/eeaf9aa9-e5b5-46c7-a1c5-13903a37c146)

**Comment by Small-tailqwq** [comment]
Have you tried updating to the latest version?

**Comment by crankgud** [comment]
> Have you tried updating to the latest version?

Oh! For whatever reason my app didn't want to update and was on the 1.9.5.9 version. Thank you very much.

**Comment by xiaojieonly** [comment]
you have to update your version to 1.9.6.5 or higher
