### ISSUE TITLE
[问题反馈]未勾选下载原图的情况下，下载时Gp仍然狂飙

### ISSUE THREAD

**Issue by matduniverse** [xiaojieonly/Ehviewer_CN_SXJ#825]
似乎是从昨天开始出现的问题，随便下载一个几十页的本子，Gp会迅速从0飙到5000+，然后触发图片配额用尽。但我一直都没有勾选下载原图，以前下载过几千页的游戏CG，也从没出现过这一问题。想问下会是什么原因。
App版本是1.9.6.5，网络是直连没有挂VPN，4G网和wifi都会出现。
![Screenshot_2023-10-30-09-36-19-870_com xjs ehviewer jpg clean](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/24569185/118a24a4-883d-48be-a0b1-4014b0d08ac0)
![Screenshot_2023-10-30-09-36-26-245_com xjs ehviewer jpg clean](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/24569185/29038d90-3639-493d-ba1e-3b3fdbb905df)
![Screenshot_2023-10-30-09-38-41-035_com xjs ehviewer jpg clean](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/24569185/376e456c-3830-4ef0-9952-23f504cad33a)
![Screenshot_2023-10-30-10-06-56-658_com xjs ehviewer jpg clean](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/24569185/d3b6f89e-6070-4901-95ea-e3545c359466)

**Comment by Small-tailqwq** [comment]
开个账号配额吧，留个e站id发你200hath

问题好像是e更新了配额计算，现在配额消耗得更快了

**Comment by matduniverse** [comment]
> 开个账号配额吧，留个e站id发你200hath
> 
> 问题好像是e更新了配额计算，现在配额消耗得更快了

谢谢，id是matduniverse，member_id是1388653。我之前隐约感觉是E站调整了什么规则，但到处也没搜到有相关的讨论

**Comment by Small-tailqwq** [comment]
> > 开个账号配额吧，留个e站id发你200hath
> > 问题好像是e更新了配额计算，现在配额消耗得更快了
> 
> 谢谢，id是matduniverse，member_id是1388653。我之前隐约感觉是E站调整了什么规则，但到处也没搜到有相关的讨论

已经发了200hath，去HentaiVerse - Bazaar - MoogleMail里查看，领了之后去 hathpacker还是哪里把配额开一下，看不懂机翻应该也OK。
另外网站改了些啥也去新闻那一栏看看，论坛里也有人讨论的。
