### ISSUE TITLE
直至1.9.6.6版本还存在的老BUG

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#826]
下载的画廊在看过以后会有概率被挪到底部（但不是最底部，而且有的时候位置不同）[我不知道你们的正在修意思是下个版本，还是说正在修但还没修好，可能是我搞错意思了？总之虽然不太影响，但是下的本子太多了，有的时候找不到。]
有的时候下载画廊无论是网络、流量、翻墙，且在配额没有用完的情况下都会让下载的画廊失败（有的失败，有的正常下载），但是刷新几次就会好。
提个建议，排行榜的画廊可以点进去直接是画廊界面，而不是点击搜索，因为名字太全有的时候搜索不到（需要掐头去尾）。

**Comment by AKO326** [comment]
现在是不是不能下载原图了，在软件里勾选了下载原图，但是下载的还是压缩过的，你们也这样吗

**Comment by xiaojieonly** [comment]
顺序问题已修，原图问题已修，下一版更新
