### ISSUE TITLE
手机没问题，换PC却网络错误？

### ISSUE THREAD

**Issue by Invyyyy** [xiaojieonly/Ehviewer_CN_SXJ#83]
电信网络，手机和PC同一网络内，同一安装包。手机使用无问题，用PC模拟器使用却是网络错误，设置三项都是打开了的，不知道问题在哪，是否可帮忙解惑？

**Comment by xiaojieonly** [comment]
看一下模拟器安卓版本是不是安卓10

**Comment by Invyyyy** [comment]
> 
> 
> 看一下模拟器安卓版本是不是安卓10

噗……是我nt了 就顾着检查手机安卓版本 忘了看模拟器的版本了 才6.0 ~~~~~~赶紧换了去 多谢解答
