### ISSUE TITLE
咨询：自动更新

### ISSUE THREAD

**Issue by rhyspan1** [xiaojieonly/Ehviewer_CN_SXJ#832]
向各位大佬咨询一个小问题，那个“关闭自动更新”的按钮到底是关掉了是关闭自动更新还是打开是关闭自动更新？

**Comment by rhyspan1** [comment]
另外“检查更新”似乎并没有起效

**Comment by rhyspan1** [comment]
主要是每次重装都会删除搜索记录……有点烦的

**Comment by xiaojieonly** [comment]
> 向各位大佬咨询一个小问题，那个“关闭自动更新”的按钮到底是关掉了是关闭自动更新还是打开是关闭自动更新？

按钮打开是关闭自动更新

**Comment by xiaojieonly** [comment]
> 另外“检查更新”似乎并没有起效

是的，这个问题打算修但老是忘

**Comment by xiaojieonly** [comment]
> 主要是每次重装都会删除搜索记录……有点烦的

建议覆盖安装，重装会导致数据丢失
