### ISSUE TITLE
选择下载原图选项，也无法下载原图

### ISSUE THREAD

**Issue by Alferica** [xiaojieonly/Ehviewer_CN_SXJ#835]
试了好几次，2mb大小的图片下载下来只有200kb。
另一个版本的也是这样子

**Comment by AKO326** [comment]
我也是这样，彩e和绿e都这样，不知道是不是eh那边的问题

**Comment by gdovo704** [comment]
勾选下载原图后，不论是直接保存还是下载，都不是原图。10.30还可以下载原图，第二天开始就不行了。

**Comment by xiaojieonly** [comment]
![Snipaste_2023-11-01_12-55-06](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/b42a7b5a-b41f-4502-8e95-707a52b11de1)
选择了Prefer orginal images的话加载的图片就是原图

**Comment by xiaojieonly** [comment]
建议在设置中心中将偏好设置为图中样式，这样下载原图相对稳定，如果选了Prefer orginal images，加载的图片就是原图，大小是E站的问题

**Comment by Noromon** [comment]
![Screenshot_2023-11-01-13-39-47-143_1](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/22496071/3a8b17d3-85f1-452d-b294-c0b6361a68a0)

设置里偏好原图的选项要求银星赞助而无法选择，但通过网页端画廊内预览单图的Download Original file链接仍然可以下载到原图（图片文件大小正确(5m)，因此判断是真正的原图，没有下错）
请求作者追加模拟此种方式下载原图的原图下载逻辑

**Comment by Noromon** [comment]
阅读了源代码，GalleryPageParser对原图链接的匹配是使用"fullimg.php"作为关键词
但是现在e站下载原图链接的链接形式已经变成了
`https://exhentai.org/fullimg/<gid>/<page>/<hash>/<filename>`
原代码的匹配模式已不能匹配到真正的原图链接，请确认此问题并修复之

**Comment by xiaojieonly** [comment]
> 阅读了源代码，GalleryPageParser对原图链接的匹配是使用"fullimg.php"作为关键词 但是现在e站下载原图链接的链接形式已经变成了 `https://exhentai.org/fullimg/<gid>/<page>/<hash>/<filename>` 原代码的匹配模式已不能匹配到真正的原图链接，请确认此问题并修复之

我看看

**Comment by chikao2024** [comment]
隔壁彩E已经修复了，望Xiaojie也尽快修复啊

**Comment by chikao2024** [comment]
看了下连白E最新版三天前也修复了原图下载问题，Xiaojie这次落后了，奥利给，要迎头赶上啊。

**Comment by xiaojieonly** [comment]
新版已修

**Comment by 2911894613** [comment]
我最近就出现了这个问题。设置里选择原图后，不仅下载不了，连图也加载不了，显示targetimage url error

**Comment by 2911894613** [comment]
用的是最新版不是老版本
