### ISSUE TITLE
关于原图下载开关打开但不能下载原图的问题

### ISSUE THREAD

**Issue by Noromon** [xiaojieonly/Ehviewer_CN_SXJ#837]
![Screenshot_2023-11-01-13-39-47-143_1](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/22496071/3a8b17d3-85f1-452d-b294-c0b6361a68a0)

设置里偏好原图的选项要求银星赞助而无法选择，但通过网页端画廊内预览单图的Download Original file链接仍然可以下载到原图（图片文件大小正确(5m)，因此判断是真正的原图，没有下错）

此后阅读了源代码，GalleryPageParser对原图链接的匹配是使用"fullimg.php"作为关键词
但是现在e站下载原图链接的链接形式已经变成了
`https://exhentai.org/fullimg/<gid>/<page>/<hash>/<filename>`
原代码的匹配模式已不能匹配到真正的原图链接，请确认此问题是否存在和需要修复

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/835

**Comment by xiaojieonly** [comment]
设置选择了prefer orginal images后，图片链接打开自动为原图
