### ISSUE TITLE
配额占用混乱求助

### ISSUE THREAD

**Issue by zzpkl** [xiaojieonly/Ehviewer_CN_SXJ#840]
我最近开始使用绿E，发现下载时配额占用极高。一本200页的单行本下一半就已经占用3500+/5000(非原图)。请问是否有解决办法？

**Comment by xiaojieonly** [comment]
挂的梯子还是直连？挂的是梯子的话是正常的
没挂梯子的话，去E站个人设置里看看图片设置

**Comment by zzpkl** [comment]
我是直连的，图片质量设置为auto，和我之前使用白e时保持一致。但在一周前白e下载大概一次配额3-4本单行本不会遇到509

**Comment by zzpkl** [comment]
我发现下载时速度为0B的时候配额也会很快上升，不知道是否有参考价值？

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11

**Comment by xiaojieonly** [comment]
不应该啊，可能你用手机流量试试？
