### ISSUE TITLE
安卓6 ehviewer最新版本 打开网站闪退 封面不显示

### ISSUE THREAD

**Issue by zhenghhj** [xiaojieonly/Ehviewer_CN_SXJ#841]
最新版本1.9.6.7，ehentai设置和我的标签的网站打开会闪退回eh设置，封面图和详情页缩略图不会显示，也不显示图裂，纯黑。
老版本1.9.4.5，ehentai设置和我的标签打开不会闪退可正常更改，封面图和详情页缩略图正常显示。
但是老版本无法下载，目前只能需要下载时候安装新版本，平时用老版本。

**Comment by xiaojieonly** [comment]
不显示是网络问题，挂了梯子的话建议在设置->高级->域名前置 关闭此项功能，并关闭dns、host等

**Comment by xiaojieonly** [comment]
闪退问题正在研究

**Comment by zhenghhj** [comment]
安卓6网络环境和域名前置关dns、host都测试过，都无法显示。我另一个安卓11的手机能正常显示。而且安卓6访问只能挂梯子，安卓11可以直连。安卓61.9.6.7新版本在下载的画廊封面不显示，老版本正常显示。

**Comment by xiaojieonly** [comment]
你封面点进去试试，可能是封面缓存被系统当垃圾删了
