### ISSUE TITLE
关于自动检测更新的问题

### ISSUE THREAD

**Issue by lyl98021** [xiaojieonly/Ehviewer_CN_SXJ#842]
目前我使用的手机是MI 8 UD；系统版本是MIUI 12.5.2 稳定版。
在进入软件提示更新时点击下载后在下载管理里的文件名会显示是“Downloading version 1.9.6.7 (111)”，无法显示它的文件类型，且在下载完成后不会弹出软件更新的那个安装窗口，点击已下载的文件后会提示“未找到已下载的文件，文件可能已经被删除”，实际文件是刚刚才下好的。
现在我都是在网页上手动下载安装包下载的，这种情况下到是可以正常更新，希望能修复这一功能。

**Comment by xiaojieonly** [comment]
系统问题，我这边解决不了
