### ISSUE TITLE
新版本好像下载不了原图

### ISSUE THREAD

**Issue by chessest** [xiaojieonly/Ehviewer_CN_SXJ#843]

**Comment by NTCDCChief** [comment]
我也遇到了这个问题，别处看到e站下载原图的链接已经改了，所以原来的代码失效了：
https://github.com/FooIbar/EhViewer/issues/170
我看昨天已经有人在昨天在#835 #837 提到了这个问题，别处也有人修复了，应该不单纯是Prefer Original Image的问题
还请应用作者确认，非常感谢

**Comment by chessest** [comment]
选择Prefer orginal images需要silver star or source nexus perk

**Comment by xiaojieonly** [comment]
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/835
