### ISSUE TITLE
为什么图片配额用这么快？

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#846]
之前没有那么快啊，而且这次我只是刷新了一下“1未完成”的图集，每次就185（跟下载原图一样），还是说我以前没注意？

**Comment by xiaojieonly** [comment]
挂了梯子吗？挂了的话那就是别人和你用的同一个节点，配额全算一起了
https://nicebowl.fun/11
