### ISSUE TITLE
关于下载的本子过多，在下载界面快速拖动目录条会卡死的问题

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#849]
对，没错，又是我，一个下了**上万本本子**的男人，这次反应的问题是在下载界面拖动目录条（就粉色竖条的那个）的时候，经常出现卡死，拖动后目录条消失，以及就算是微曲面屏很难按中目录条的问题。
希望能将目录条加宽一点，以及让它不会因为拖动而卡死或者直接消失。
![1698929965789](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/2eaa9e38-3a49-4f35-b362-f7d6ff64fd0f)
![1698929965784](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/4fd5c887-d440-4a0f-b505-fd97dc643245)
![Screenshot_2023-11-02-21-01-19-201_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/9b4f8234-fe0f-4a22-bc4a-e3498fdc966f)

**Comment by xiaojieonly** [comment]
我尽力优化

**Comment by KyaruSAMA** [comment]
终于有人提了，下了2w+本翻以前下的本都看运气😂

**Comment by xiaojieonly** [comment]
1.9.7.0还有这个问题吗？

**Comment by tongsang** [comment]
。

> 1.9.7.0还有这个问题吗？

 @卡死问题已经解决了，但快速拖动目录条的时候还是会发生目录条消失（现1.9.7.2版本），或者显示位置错误的情况（概率百分之百），**我提供我现在的11626本下载记录的数据供带佬测试**。（以发送至您ehviewersu@gmail.com地址的邮箱）
另外目**录条的横向尺寸还是太小了**，手机上关掉防误触模式大致能解决好几下都按不中的情况，但在平板上又出现一样难以选中的问题，建议还是为了适配更多的设备加宽目录条

**Comment by xiaojieonly** [comment]
> 。
> 
> > 1.9.7.0还有这个问题吗？
> 
> @卡死问题已经解决了，但快速拖动目录条的时候还是会发生目录条消失（现1.9.7.2版本），或者显示位置错误的情况（概率百分之百），**我提供我现在的11626本下载记录的数据供带佬测试**。（以发送至您[ehviewersu@gmail.com](mailto:ehviewersu@gmail.com)地址的邮箱） 另外目**录条的横向尺寸还是太小了**，手机上关掉防误触模式大致能解决好几下都按不中的情况，但在平板上又出现一样难以选中的问题，建议还是为了适配更多的设备加宽目录条

我不认识这个邮箱啊！！！你在哪找的邮箱？
我邮箱是xiaojieonly@foxmail.com

**Comment by tongsang** [comment]
> > 。
> > > 1.9.7.0还有这个问题吗？
> > 
> > 
> > @卡死问题已经解决了，但快速拖动目录条的时候还是会发生目录条消失（现1.9.7.2版本），或者显示位置错误的情况（概率百分之百），**我提供我现在的11626本下载记录的数据供带佬测试**。（以发送至您[ehviewersu@gmail.com](mailto:ehviewersu@gmail.com)地址的邮箱） 另外目**录条的横向尺寸还是太小了**，手机上关掉防误触模式大致能解决好几下都按不中的情况，但在平板上又出现一样难以选中的问题，建议还是为了适配更多的设备加宽目录条
> 
> 我不认识这个邮箱啊！！！你在哪找的邮箱？ 我邮箱是[xiaojieonly@foxmail.com](mailto:xiaojieonly@foxmail.com)

额，应用里的开发者邮箱点击后，跳转成ehviewersu@gmail.com这个邮箱了，应该是你**只改了显示字符没有改跳转链接**，我已经重新发往xiaojieonly@foxmail.com了
![1704449694950](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/e81da3b1-797e-45b2-928f-e86cfac430fd)
![1704449694948](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/5a05b61b-3e76-4b1f-ab40-1da850d6430f)
![1704449694945](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/365bf0b2-e839-4105-b3fb-5aafd48468e7)

**Comment by xiaojieonly** [comment]
哦~这样啊

**Comment by xiaojieonly** [comment]
邮箱的问题修好了，列表的问题还在修

**Comment by xiaojieonly** [comment]
已更新列表分页

**Comment by tongsang** [comment]
感谢大佬的付出，也祝大佬新年快乐。新的列表翻页在设计上确实会非常好用，但可惜的是我点击列表第二页第一个本子的时候，实际上打开的是第一页第一个本子（已尝试清理内存缓存，和重新导入数据）

**Comment by tongsang** [comment]
> 已更新列表分页

感谢大佬的付出，也祝大佬新年快乐。新的列表翻页在设计上确实会非常好用，但可惜的是我点击列表第二页第一个本子的时候，实际上打开的是第一页第一个本子（已尝试清理内存缓存，和重新导入数据）。设置一页显示500条的时候到第500条都是点击后打开对应本子，但翻页后点击新的标题名字的本子出来的还是前一页对应排序顺序的内容
