### ISSUE TITLE
新版本为啥老是加载不出来啊，要挂梯子吗？

### ISSUE THREAD

**Issue by fyl666kl** [xiaojieonly/Ehviewer_CN_SXJ#85]
新版本为啥老是加载不出来啊，要挂梯子吗？

**Comment by xiaojieonly** [comment]
是的



---Original---
From: ***@***.***&gt;
Sent at: 2021年3月10日(Wed) Evening10:02
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [xiaojieonly/Ehviewer_CN_SXJ] 新版本为啥老是加载不出来啊，要挂梯子吗？ (#85)




 
新版本为啥老是加载不出来啊，要挂梯子吗？

**Comment by xiaojieonly** [comment]
现在1.7.10大概率不需要梯子了
