### ISSUE TITLE
能否加入一个在下载界面给已经下载的本子进行手动排序的功能？

### ISSUE THREAD

**Issue by tongsang** [xiaojieonly/Ehviewer_CN_SXJ#850]
就像下图所示，有的本子是分上中下话，或者多话的情况，而且并不是一次性被发布出来的，中间可能间隔很多天。已经被发布完的多话本子可以通过倒序话数加入下载队伍，来实现下图的正序排列。但如果之前下好了1，2话后，隔了一段时间才发布下一话的情况下，将新的一话加入下载队列。那想当然中间会因为其他下载的本子导致同个作品没有相邻以及保持正序。现如今我的结决方法就是干脆删掉之前下载的话数，直接重新倒序加入下载队列，所以希望能够加入一个在下载界面能手动拖动或者以其他方式实现本子排序的功能。
![1698930741096](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/30853947/20d9b2f6-27c7-4491-b7b7-30ff31179e7a)

**Comment by xiaojieonly** [comment]
下一版出
