### ISSUE TITLE
点击“更新”画廊然后取消并删除、清理下载缓存后，再次下载出现大半页面显示“Invalid page”，并且无论如何下载都无法显示这些页面

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#852]
![Screenshot_20231103_021656_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/81443964/0b2576cc-498b-4b62-9e87-0773ef5c6c54)

**Comment by DidyouseetheSunrise** [comment]
之后每次下载都是400页后的部分全部显示未完成下载失败

**Comment by DidyouseetheSunrise** [comment]
并且如果从画廊详情页点进400页后的内容在线观看，会直接导致闪退停止运行

**Comment by DidyouseetheSunrise** [comment]
![Uploading Screenshot_20231103_022506_EhViewer.jpg…]()

**Comment by DidyouseetheSunrise** [comment]
![Screenshot_20231103_022506_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/81443964/c156ea3a-b3b2-4be6-a7dc-48204c6b7d6e)

**Comment by DidyouseetheSunrise** [comment]
并且删除下载画廊-退出app-从历史记录下载也不行

**Comment by xiaojieonly** [comment]
下载里删除画廊，然后找一下手机文件夹里/Ehviewer/download 文件夹里删除掉对应文件夹试试

**Comment by hsqxcc** [comment]
问题还是有，删掉文件夹也不行，一般过一会就又可以下载，具体间隔没注意，但是一些版权本就会错过了
