### ISSUE TITLE
希望尽快更新修复无法下载原图问题

### ISSUE THREAD

**Issue by chikao2024** [xiaojieonly/Ehviewer_CN_SXJ#856]
因E站原图保存与下载逻辑改变，目前其他Ehviewer客户端最新版都更新了，解决了无法下载和保存原图的问题，现在唯独绿E还不行。Xiaojie加油啊，心目中绿E是最强之E，不能因为这个就沦为最差之E啊。。。😔 支持Xiaojie，尽快更新修复，等绿E更新后再次成为最强之E。

**Comment by chikao2024** [comment]
都一周了还没更新修复。。。😭

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
新版已经修了
