### ISSUE TITLE
已下载的画廊查看详细信息后会被重新排序

### ISSUE THREAD

**Issue by MrSneez** [xiaojieonly/Ehviewer_CN_SXJ#857]
所有已下载的画廊，在进入下载界面或者在搜索界面，只要点进详情，再退出应用(清除后台)后，这些进入过详情页的已下载画廊就会被刷新到下载界面的最下方。在未清除后台前还不会改变顺序，一清除后台，曾在上次打开软件后进行过此流程的画廊都会被刷新顺序。

**Comment by chikao2024** [comment]
厉害，感谢你找到已下载画廊乱序问题的触发条件了。

**Comment by suweiai1314** [comment]
强，我试了一下，也出现了一模一样的排序问题 对于我这种喜欢按顺序下系列作的人而言，这个bug每次触发都会让我重新再排序一次，属实麻了

**Comment by xiaojieonly** [comment]
我知道为什么了

**Comment by MrSneez** [comment]
> 我知道为什么了

感谢xiaojie大佬回复！不算是影响使用的大问题，只是我对下载顺序的确有些在意，有时候想看看下载过的本子评论得换另一个手机才敢看这样(
这个问题能被注意到就很庆幸了，再次感谢大佬！

**Comment by xiaojieonly** [comment]
注意很久了，一直没法复现，看到你的评论才想通为什么

**Comment by xiaojieonly** [comment]
修了，下个版本修复

**Comment by MrSneez** [comment]
> 修了，下个版本修复

好耶——谢谢大佬——
