### ISSUE TITLE
网站选择里e就显示解析失败

### ISSUE THREAD

**Issue by xsingle9527** [xiaojieonly/Ehviewer_CN_SXJ#859]
网站选择里e就显示解析失败，表站能进去，已登录，账号网页端也能进去

**Comment by cakef1y** [comment]
同样的问题，网页版里站能登录

**Comment by VcRin** [comment]
一样，最近我也出现这个情况，网页一切正常，app内进里E就解析失败

**Comment by rolandliu87** [comment]
> 网站选择里e就显示解析失败，表站能进去，已登录，账号网页端也能进去



> 同样的问题，网页版里站能登录



> 一样，最近我也出现这个情况，网页一切正常，app内进里E就解析失败

我解決問題了，app先登出你的帳號，重開之後選擇用瀏覽器登入，不要在app裡面登入，就好了

**Comment by subjects52** [comment]
> > 网站选择里e就显示解析失败，表站能进去，已登录，账号网页端也能进去
> 
> > 同样的问题，网页版里站能登录
> 
> > 一样，最近我也出现这个情况，网页一切正常，app内进里E就解析失败
> 
> 我解決問題了，app先登出你的帳號，重開之後選擇用瀏覽器登入，不要在app裡面登入，就好了

我试着用你的方式，但没有解决问题

**Comment by xiaojieonly** [comment]
使用cookie登录
