### ISSUE TITLE
表站能登，里站登不上

### ISSUE THREAD

**Issue by jasonli81** [xiaojieonly/Ehviewer_CN_SXJ#86]
安卓11，之前用的1.7.6.x版本，里站有时能上有时不能上，然后更新了最新版本以后只能裸连表站，里站上不去了，内置host，安全dns，域名前置都开了，现在是必须挂梯子了吗？

**Comment by jasonli81** [comment]
不好意思记错了，之前是1.7.7.1

**Comment by xiaojieonly** [comment]
用1.7.10
