### ISSUE TITLE
数据迁移后恢复下载项失败

### ISSUE THREAD

**Issue by durial12** [xiaojieonly/Ehviewer_CN_SXJ#861]
从旧手机上把EhViewer文件夹整体复制到新手机后，恢复下载项失败，本地文件无法恢复到下载目录里

**Comment by xiaojieonly** [comment]
数据库没迁移过来啊https://juejin.cn/s/ehviewer%E6%80%8E%E4%B9%88%E5%AF%BC%E5%85%A5%E6%95%B0%E6%8D%AE
