### ISSUE TITLE
下载好的早期内容会自然清空

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#862]
本地下载里，列表下载进度显示的依旧是已完成，但点开后需要加载。
目前只在单行本看到这样的情况，手动测试了一下，将已下载的一百本单行本全选并点击下载后，发现有十三本的内容都是空的，需要重新下载，且以下载顺序来看大多都是早期下载的单行本。

**Comment by suweiai1314** [comment]
把那十几本被清除本地数据的本拿出来看了一眼，发现都是上传者为brds19的无修单行本，不知道这里面是否有逻辑关联

**Comment by xiaojieonly** [comment]
是不是权限没给？也有可能是画廊存app缓存了，然后手机系统把缓存当垃圾删了导致的
