### ISSUE TITLE
希望可以增加下载时保留原图片名称的选项

### ISSUE THREAD

**Issue by unrance** [xiaojieonly/Ehviewer_CN_SXJ#863]
首先感谢大佬的付出
因为有些作者上传的顺序比较乱，但是原文件名是按顺序的；
还有些画廊大于2000张而分成了几部分，每部分都从1开始编号的话合并起来挺麻烦；
如果能保留原文件名会方便很多，希望可以考虑一下

**Comment by chikao2024** [comment]
所有的E客户端都是按顺序文件名的，要原文件名用种子就可以了。万一新增这功能导致以后下载出问题可就得不偿失了。

**Comment by xiaojieonly** [comment]
感谢二楼替我解答
