### ISSUE TITLE
下载画廊时配额被迅速用光

### ISSUE THREAD

**Issue by Dryhotdog123** [xiaojieonly/Ehviewer_CN_SXJ#865]
如题，在下载画廊时发现5000的配额被用完了，明明只有不到五十张的图一张都没有下完配额就用完了。本人没有使用vpn，也没有和多人共用一个ip。app的下载功能是否有问题，可能导致重复下载耗尽了配额?

**Comment by chikao2024** [comment]
现在无法下载原图，配额用都用不完，应该是你自身问题。
