### ISSUE TITLE
下载好的画廊有时会莫名其妙出现在默认标签下的最下层，移动回原来的标签也依然是在该标签的最下层

### ISSUE THREAD

**Issue by QAQNOQWQ** [xiaojieonly/Ehviewer_CN_SXJ#866]
下载好的画廊分配到其他标签，保持默认标签内无内容，经正常使用退出，有时打开APP会发现默认里出现了其他标签里的画廊，移动回原本的标签后，该画廊变成了该标签内的最低端一项。加上无法调整画廊的上下位置，顺序因这样被打乱好多次了= =

**Comment by sdo9004** [comment]
我是下载好的东西在下载列表会看不到去主页搜的话搜到显示已下载，就像贴吧吞楼一样把我下载列表的记录吞了

**Comment by xiaojieonly** [comment]
已修
