### ISSUE TITLE
App内切换标签组无法正常刷新

### ISSUE THREAD

**Issue by capllen** [xiaojieonly/Ehviewer_CN_SXJ#869]
用的版本是1.9.6.7，在app内打开我的标签页面后，发现虽然有切换标签组的选项，但是点击切换后，界面没有任何变化，无法切换，想要新建标签组也是一样。用浏览器重新打开，发现原来在app里点击的新建标签页确实已经建立了，怀疑是不是app内置的浏览器不能即时刷新导致的？

**Comment by xiaojieonly** [comment]
更新到最新版试试
