### ISSUE TITLE
画廊内容加载不出来

### ISSUE THREAD

**Issue by SkyKZhang** [xiaojieonly/Ehviewer_CN_SXJ#87]
登录了自己的帐号，主有内容，画廊简介界面也没问题，但点阅读后无限转圈，下载也没有速度

**Comment by fantasysimulation** [comment]
我也是，不知道为什么

**Comment by huangqi-player** [comment]
同问！

**Comment by Dnir2** [comment]
+1

**Comment by zd201108** [comment]
求助，版本1.7.8.4，可以打开表站，可以正常打开项目，可以观看缩略图，但是无法浏览，无法下载，只要预览网络就出问题。
Help, version 1.7.8.4, you can open the watch station, open the project normally, watch the thumbnail, but you can't browse or download it, so long as you preview the network, there will be problems.

**Comment by xiaojieonly** [comment]
关了dns
