### ISSUE TITLE
都一周多了，还没更新修复无法保存和下载原图问题。

### ISSUE THREAD

**Issue by chikao2024** [xiaojieonly/Ehviewer_CN_SXJ#871]
😭已经一周多了，还没更新修复无法保存和下载原图的问题，只能被迫用彩E，但彩E的直连不稳经常出错，求求尽快更新吧，真要受不了。😭

**Comment by slwy1303357042** [comment]
> 😭已经一周多了，还没更新修复无法保存和下载原图的问题，只能被迫用彩E，但彩E的直连不稳经常出错，求求尽快更新吧，真要受不了。😭

为什么我是今天才出现的问题

**Comment by goucanrellydance** [comment]
彩e求指路

**Comment by xiaojieonly** [comment]
修了
