### ISSUE TITLE
能设个开关，点本子进本子封面 和 长按直接阅读 两个功能互换吗？

### ISSUE THREAD

**Issue by Lovefish** [xiaojieonly/Ehviewer_CN_SXJ#873]
由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。

**Comment by slwy1303357042** [comment]
> 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。

有没有可能，你才是少数人

**Comment by Lovefish** [comment]
> > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> 
> 有没有可能，你才是少数人

你这个回复好像我说了大部分人都是这样似的？xswl

**Comment by slwy1303357042** [comment]
> > > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> > 
> > 
> > 有没有可能，你才是少数人
> 
> 你这个回复好像我说了大部分人都是这样似的？xswl

你的这个要求跟提出一个定制功能没有区别了，懂我意思？

**Comment by Lovefish** [comment]
> > > > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> > > 
> > > 
> > > 有没有可能，你才是少数人
> > 
> > 
> > 你这个回复好像我说了大部分人都是这样似的？xswl
> 
> 你的这个要求跟提出一个定制功能没有区别了，懂我意思？

好家伙，我问作者能不能。还定制功能呢😂，你就是作者了是吧。🤣

**Comment by slwy1303357042** [comment]
> > > > > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> > > > 
> > > > 
> > > > 有没有可能，你才是少数人
> > > 
> > > 
> > > 你这个回复好像我说了大部分人都是这样似的？xswl
> > 
> > 
> > 你的这个要求跟提出一个定制功能没有区别了，懂我意思？
> 
> 好家伙，我问作者能不能。还定制功能呢😂，你就是作者了是吧。🤣

搞笑了还你问的是能不能，那我也问你个能不能：你能不能不问啊？🤣
怎么样我问的也是能不能吧🤣
你特意问出来就是想让人家做还搁这装呢，要是做了以后一堆人都能提出这种要求，说白了你就是为了自己没想过别人

**Comment by Lovefish** [comment]
> > > > > > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> > > > > 
> > > > > 
> > > > > 有没有可能，你才是少数人
> > > > 
> > > > 
> > > > 你这个回复好像我说了大部分人都是这样似的？xswl
> > > 
> > > 
> > > 你的这个要求跟提出一个定制功能没有区别了，懂我意思？
> > 
> > 
> > 好家伙，我问作者能不能。还定制功能呢😂，你就是作者了是吧。🤣
> 
> 搞笑了还你问的是能不能，那我也问你个能不能：你能不能不问啊？🤣 怎么样我问的也是能不能吧🤣 你特意问出来就是想让人家做还搁这装呢，要是做了以后一堆人都能提出这种要求，说白了你就是为了自己没想过别人

我再问你一次，你是不是作者？不是作者的话，请自己去发issues不要这么不要脸的一直来贴在我下面。

**Comment by Lovefish** [comment]
> > > > > > 由于大部分时间都是直接阅读，去封面看评论或看缩略图的情况特别少。
> > > > > 
> > > > > 
> > > > > 有没有可能，你才是少数人
> > > > 
> > > > 
> > > > 你这个回复好像我说了大部分人都是这样似的？xswl
> > > 
> > > 
> > > 你的这个要求跟提出一个定制功能没有区别了，懂我意思？
> > 
> > 
> > 好家伙，我问作者能不能。还定制功能呢😂，你就是作者了是吧。🤣
> 
> 搞笑了还你问的是能不能，那我也问你个能不能：你能不能不问啊？🤣 怎么样我问的也是能不能吧🤣 你特意问出来就是想让人家做还搁这装呢，要是做了以后一堆人都能提出这种要求，说白了你就是为了自己没想过别人

哎，我觉得你是不是脑容量不够啊？我说加个开关适，用户可以自己选择，怎么就是为了自己没想过别人呢？对你的大脑感发育非常的抱歉啊。。。

**Comment by xiaojieonly** [comment]
以后有时间了可以加个开关
