### ISSUE TITLE
我的更新不了 你可以给我一下链接吗？

### ISSUE THREAD

**Issue by 3343145183** [xiaojieonly/Ehviewer_CN_SXJ#877]
我的显示没法更新 你可以把链接发我一下吗？ 谢谢好人

**Comment by chikao2024** [comment]
新版发布1.9.6.9     
紧急修复了获取原图链接获取错误导致无法下载原图的问题    
点击前往下载：[百度云](https://pan.baidu.com/s/1VC-75-LnJWnptCywMJa5FA)  密码:d3kc   
点击前往下载（电脑端可正常下载）：[蓝奏云](https://wwsu.lanzouj.com/iXCX71ek0cbe)  密码:cc8t
