### ISSUE TITLE
更新后在使用VPN时解析失败

### ISSUE THREAD

**Issue by Eugen12138** [xiaojieonly/Ehviewer_CN_SXJ#878]
使用app访问里站显示解析失败或者网络错误，但是网页端正常，app访问表站也正常

**Comment by Kirito2401** [comment]
我也是，不知道怎么办……

**Comment by mx41shy** [comment]
> 我也是，不知道怎么办……



> 使用app访问里站显示解析失败或者网络错误，但是网页端正常，app访问表站也正常

可以试试退出登录然后重新登录

**Comment by chikao2024** [comment]
自身问题，看igneous，看配额。

**Comment by xiaojieonly** [comment]
楼上正解
