### ISSUE TITLE
1.9.6.9更新后收藏夹直连一直转圈无法显示

### ISSUE THREAD

**Issue by faker1987** [xiaojieonly/Ehviewer_CN_SXJ#880]
1.9.6.9更新后收藏夹直连一直转圈无法显示，并且图片加载也慢很多，降级回旧版就一切正常。求管理员修复一下谢谢

**Comment by chikao2024** [comment]
我这边最新版收藏都显示正常没有问题

**Comment by faker1987** [comment]
> 我这边最新版收藏都显示正常没有问题

我也不知道为什么，最新版就会这样。降级会1.9.6.8就正常

**Comment by xiaojieonly** [comment]
更新到1.9.7.0试试
