### ISSUE TITLE
为什么封面和缩略图显示不出来啊 

### ISSUE THREAD

**Issue by jdbxhxjf** [xiaojieonly/Ehviewer_CN_SXJ#882]

**Comment by AntiLain** [comment]
提供详细信息，网络环境，app版本

**Comment by jdbxhxjf** [comment]
> 提供详细信息，网络环境，app版本

用的是绿e 我之前是4.0版本然后出现解析失败我就更新到最新版本了 更新之后发现出现封面和缩略图无法显示 我又下回4.0版本图片有了 但是 4.0版本之后的都看不到 我一直都是用梯子的  网上找的免费的sky 

> 提供详细信息，网络环境，app版本

**Comment by jdbxhxjf** [comment]
> 提供详细信息，网络环境，app版本

解决了把5.2的host添加到4.4的里面就好了

**Comment by Achievement42** [comment]
> > 提供详细信息、网络环境、应用程序版本
> 
> 解决了把5.2的主机添加到4.4的里面就好了



> _没有提供描述。_



> > 提供详细信息、网络环境、应用程序版本
> 
> 解决了把5.2的主机添加到4.4的里面就好了

老哥，怎么弄？4.4不会解析式失败？

**Comment by FengTeLai** [comment]
> 解决了把5.2的host添加到4.4的里面就好了
怎么操作的，我HOST找不来，更何况添加自定义

**Comment by xialirising** [comment]
> > 提供详细信息，网络环境，app版本
> 
> 解决了把5.2的host添加到4.4的里面就好了

具体怎么操作老哥 我也是这个问题

**Comment by xiaojieonly** [comment]
把安全dns关了，或者就是单纯的网不好
