### ISSUE TITLE
更新后使用VPN导致Sadpanda

### ISSUE THREAD

**Issue by Alsohao** [xiaojieonly/Ehviewer_CN_SXJ#886]
更新到新版本后使用vpn页面无法加载，不使用可以看到画廊但没法下载

**Comment by chikao2024** [comment]
是你自身问题，跟App无关

**Comment by Alsohao** [comment]
> 是你自身问题，跟App无关

你在VPN相关的下面都回复自身问题，什么问题呢？
如何诊断？

**Comment by chikao2024** [comment]
> > 是你自身问题，跟App无关
> 
> 你在VPN相关的下面都回复自身问题，什么问题呢？ 如何诊断？

用浏览器清空Cookies后访问 https://e-hentai.org/ 看表站主页能否正常显示，别的啥都不用做。如能正常显示，则Ehviewer客户端绝对可以正常使用；如显示白屏，用该IP打开Ehviewer客户端则必定Sadpanda，请更换其他节点或VPN。
