### ISSUE TITLE
加载不了搜索预览图

### ISSUE THREAD

**Issue by heloonihao** [xiaojieonly/Ehviewer_CN_SXJ#888]
![Screenshot_2023-11-14-12-52-35-395_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/150769256/a759bd98-0cc3-4530-80c8-c50842ea629f)
![Screenshot_2023-11-14-12-53-00-275_com android settings](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/150769256/727b6f52-ec7d-4a0c-a9d7-a412ff738e99)

我一直用的白eh搜索然后用你这看，白eh加载不出漫画，你的加载不出预览

**Comment by caesar-nono** [comment]
我的能加载出预览图。但是点进去就看不了了。

**Comment by xiaojieonly** [comment]
安全dns关了
