### ISSUE TITLE
请问怎么设置默认收藏夹？

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#89]
第一次设置后想取消默认，但找不到在哪弄了

**Comment by xiaojieonly** [comment]
功能还不完善，我研究下

**Comment by xiaojieonly** [comment]
![qq_pic_merged_1683253689760](https://user-images.githubusercontent.com/49278135/236366113-3ad22e1a-9da8-4b94-8317-f671a273e23c.jpg)
