### ISSUE TITLE
新功能请求:曾下载标签

### ISSUE THREAD

**Issue by xwt961125** [xiaojieonly/Ehviewer_CN_SXJ#890]
现在使用nas整理本子，下载好后会迁移到nas中，然后清空app中的下载，此时本子右下角已下载的标签消失，浏览时经常会下到已经下过的本子，不知道将来可否出一个功能标记已经下载过的本子。
  非常感谢！

**Comment by xiaojieonly** [comment]
很麻烦，对数据库的改动很大，不太现实，以后再说吧
