### ISSUE TITLE
清除登录后无法再次进入登录界面

### ISSUE THREAD

**Issue by ZHH-start** [xiaojieonly/Ehviewer_CN_SXJ#893]
我想登录，而我的状态是未登录，因此我退出并重新进入，然而登录界面只是闪烁一下就消失了。我直接清除软件数据后再次进入，发现登陆界面不能退出，否则就再也无法进入登陆界面了，无论是直接回到桌面再进，还是杀掉后台都不行，会进入站点选择界面，选择后就直接进入站点了。

**Comment by ZHH-start** [comment]
我甚至不能将输入法隐藏，不然也会马上进入选择，天哪，这什么鬼a

**Comment by bakemonoingithub** [comment]
我出现和你一样的问题，还未解决

**Comment by xiaojieonly** [comment]
是不是有什么软件带了强制跳过app广告页的功能？把这种功能关了就行

**Comment by ZHH-start** [comment]
> 是不是有什么软件带了强制跳过app广告页的功能？把这种功能关了就行

好像还真是，有一个李跳跳。我试试看。不过这登陆界面也会被识别为广告页吗？
