### ISSUE TITLE
无法获取里E数据

### ISSUE THREAD

**Issue by sr-umme** [xiaojieonly/Ehviewer_CN_SXJ#894]
我的账号可以登入里E网页版，但是却无法获得APP内的任何数据。

**Comment by fsjan1** [comment]
我刚也遇到这种情况了，试下在App内退出账号，然后再重新登录

**Comment by sr-umme** [comment]
> 我刚也遇到这种情况，在App内退出账号试下，然后重新登录
也尝试过，依然没有数据

**Comment by xiaojieonly** [comment]
这个是第三方app
