### ISSUE TITLE
关于旧版本无法显示缩略图的原因的推测

### ISSUE THREAD

**Issue by NiceBowl335** [xiaojieonly/Ehviewer_CN_SXJ#9]
在EhDNS.java中发现，预填写的ehgt.org的地址为81.171.14.118，而此域名目前的地址已经变更为178.162.139.24。
旧版本无法显示缩略图的原因是否正在于此呢？

**Comment by xiaojieonly** [comment]
> 在EhDNS.java中发现，预填充的ehgt.org的地址为81.171.14.118，而此域名当前的地址已经更改为178.162.139.24。
> 旧版本无法显示的原因是否正在上此呢？
> （在之前的Issue里，作者提出的解决方案是关闭内置主机，进一步印证了我的这个想法）
> 
> 很遗憾没有找到作者的联系方式，只好发在这个讨论区里了。
> 我之前写过一篇文章，Ex绅士里站访问教程-注册自己的账号畅游里站（[https://nicebowl.moe/ 11）。](https://nicebowl.moe/11%EF%BC%89%E3%80%82)
> 最近想完善一下文章中关于EhViewer的相关内容。
> 恳请作者能留一下联系方式，或电子邮件一下我的邮箱（[nicebowl@foxmail.com](mailto:nicebowl@foxmail.com)），我还有些其他的琐碎问题想向您请教，谢谢！

嗯是的，最新版本我已经修改了内置host

**Comment by xiaojieonly** [comment]
> 在EhDNS.java中发现，预填写的ehgt.org的地址为81.171.14.118，而此域名目前的地址已经变更为178.162.139.24。
> 旧版本无法显示缩略图的原因是否正在于此呢？
> （在之前的Issue里，作者给出的解决方案是关闭内置host，进一步印证了我的这个想法）
> 
> 很遗憾没有找到作者的联系方式，只好发在这个讨论区里了。
> 我之前写过一篇文章，Ex绅士里站访问教程——注册自己的账号畅游里站（[https://nicebowl.moe/11）。](https://nicebowl.moe/11%EF%BC%89%E3%80%82)
> 最近想完善一下文章中关于EhViewer的相关内容。
> 恳请作者能留一下联系方式，或电邮一下我的邮箱（[nicebowl@foxmail.com](mailto:nicebowl@foxmail.com)），我还有些其它的琐碎问题想向您请教，谢谢！

我这两天沉迷《群星》没来得及回复，抱歉🤣

**Comment by NiceBowl335** [comment]
> > 在EhDNS.java中发现，预填写的ehgt.org的地址为81.171.14.118，而此域名目前的地址已经变更为178.162.139.24。
> > 旧版本无法显示缩略图的原因是否正在于此呢？
> > （在之前的Issue里，作者给出的解决方案是关闭内置host，进一步印证了我的这个想法）
> > 很遗憾没有找到作者的联系方式，只好发在这个讨论区里了。
> > 我之前写过一篇文章，Ex绅士里站访问教程——注册自己的账号畅游里站（[https://nicebowl.moe/11）。](https://nicebowl.moe/11%EF%BC%89%E3%80%82)
> > 最近想完善一下文章中关于EhViewer的相关内容。
> > 恳请作者能留一下联系方式，或电邮一下我的邮箱（[nicebowl@foxmail.com](mailto:nicebowl@foxmail.com)），我还有些其它的琐碎问题想向您请教，谢谢！
> 
> 我这两天沉迷《群星》没来得及回复，抱歉🤣

还有想请教的是：
1.APP中的“修正缩略图链接”模块是实现了怎样的功能呢？
2.您发布的新版本是如何解决评论区无法显示的问题的呢？是因为e站修改了某些页面元素标记而导致旧版本(1.7.3)无法顺利抓取评论吗？
（抱歉，自己的Java水平约等于0，阅读源码有些吃力）

3.在1.7.6.07版本的源码包中，似乎EhDns.java文件中的内置host解析仍然是过期的....

此外，还是想再次请求一下您的即时通讯工具的联系方式，感觉在Github上交流不太方便...

**Comment by NiceBowl335** [comment]
T T 请求互动

**Comment by xiaojieonly** [comment]
> T T 请求互动

抱歉，我qq：1031082091

**Comment by xiaojieonly** [comment]
> > > 在EhDNS.java中发现，预填写的ehgt.org的地址为81.171.14.118，而此域名目前的地址已经变更为178.162.139.24。
> > > 旧版本无法显示缩略图的原因是否正在于此呢？
> > > （在之前的Issue里，作者给出的解决方案是关闭内置host，进一步印证了我的这个想法）
> > > 很遗憾没有找到作者的联系方式，只好发在这个讨论区里了。
> > > 我之前写过一篇文章，Ex绅士里站访问教程——注册自己的账号畅游里站（[https://nicebowl.moe/11）。](https://nicebowl.moe/11%EF%BC%89%E3%80%82)
> > > 最近想完善一下文章中关于EhViewer的相关内容。
> > > 恳请作者能留一下联系方式，或电邮一下我的邮箱（[nicebowl@foxmail.com](mailto:nicebowl@foxmail.com)），我还有些其它的琐碎问题想向您请教，谢谢！
> > 
> > 
> > 我这两天沉迷《群星》没来得及回复，抱歉🤣
> 
> 还有想请教的是：
> 1.APP中的“修正缩略图链接”模块是实现了怎样的功能呢？
> 2.您发布的新版本是如何解决评论区无法显示的问题的呢？是因为e站修改了某些页面元素标记而导致旧版本(1.7.3)无法顺利抓取评论吗？
> （抱歉，自己的Java水平约等于0，阅读源码有些吃力）
> 
> 3.在1.7.6.07版本的源码包中，似乎EhDns.java文件中的内置host解析仍然是过期的....
> 
> 此外，还是想再次请求一下您的即时通讯工具的联系方式，感觉在Github上交流不太方便...

评论是因为接口返回的数据结构变动导致评论处理方法异常抛出错误导致的，修改了数据处理方式就可以了；
dns还是过期的问题是因为我但是代码忘了提交了；
略缩图链接这个是原作者搞的功能，因为不影响更新我就没去研究，所以我也不太清楚。

**Comment by NiceBowl335** [comment]
> > > > 在EhDNS.java中发现，预填写的ehgt.org的地址为81.171.14.118，而此域名目前的地址已经变更为178.162.139.24。
> > > > 旧版本无法显示缩略图的原因是否正在于此呢？
> > > > （在之前的Issue里，作者给出的解决方案是关闭内置host，进一步印证了我的这个想法）
> > > > 很遗憾没有找到作者的联系方式，只好发在这个讨论区里了。
> > > > 我之前写过一篇文章，Ex绅士里站访问教程——注册自己的账号畅游里站（[https://nicebowl.moe/11）。](https://nicebowl.moe/11%EF%BC%89%E3%80%82)
> > > > 最近想完善一下文章中关于EhViewer的相关内容。
> > > > 恳请作者能留一下联系方式，或电邮一下我的邮箱（[nicebowl@foxmail.com](mailto:nicebowl@foxmail.com)），我还有些其它的琐碎问题想向您请教，谢谢！
> > > 
> > > 
> > > 我这两天沉迷《群星》没来得及回复，抱歉🤣
> > 
> > 
> > 还有想请教的是：
> > 1.APP中的“修正缩略图链接”模块是实现了怎样的功能呢？
> > 2.您发布的新版本是如何解决评论区无法显示的问题的呢？是因为e站修改了某些页面元素标记而导致旧版本(1.7.3)无法顺利抓取评论吗？
> > （抱歉，自己的Java水平约等于0，阅读源码有些吃力）
> > 3.在1.7.6.07版本的源码包中，似乎EhDns.java文件中的内置host解析仍然是过期的....
> > 此外，还是想再次请求一下您的即时通讯工具的联系方式，感觉在Github上交流不太方便...
> 
> 评论是因为接口返回的数据结构变动导致评论处理方法异常抛出错误导致的，修改了数据处理方式就可以了；
> dns还是过期的问题是因为我但是代码忘了提交了；
> 略缩图链接这个是原作者搞的功能，因为不影响更新我就没去研究，所以我也不太清楚。

啊，感谢回复。前段时间自己也折腾出了问题所在，但还是十分感谢！
