### ISSUE TITLE
请求老版本支持

### ISSUE THREAD

**Issue by YuHuanTin** [xiaojieonly/Ehviewer_CN_SXJ#90]
看了下不支持老版本的安卓
我的安卓版本是4.4

**Comment by xiaojieonly** [comment]
下一版，我尽力做

**Comment by YuHuanTin** [comment]
thx~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojieonly/Ehviewer_CN_SXJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojieonly/Ehviewer_CN_SXJ] 请求老版本支持 (#90)





 
下一版，我尽力做

**Comment by xiaojieonly** [comment]
> 看了下不支持老版本的安卓
> 我的安卓版本是4.4

你看下最新版的能装上去用不？

**Comment by YuHuanTin** [comment]
还是不行，会出现解析程序包错误

**Comment by lyl1433223** [comment]
呜呜呜，不要放弃我们安卓8.1
