### ISSUE TITLE
列表模式详情没有显示上传者

### ISSUE THREAD

**Issue by idkcckdk** [xiaojieonly/Ehviewer_CN_SXJ#902]
最新版本1.9.6.10 没有显示上传者
![Capture+_2023-11-22-13-19-41](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/138546743/f57b0468-991e-4e5d-922c-00afd60147f4)

**Comment by xiaojieonly** [comment]
更新到最新版
