### ISSUE TITLE
求助：无法评论

### ISSUE THREAD

**Issue by fhouia** [xiaojieonly/Ehviewer_CN_SXJ#906]
有账号能进里站，能看到别人的评论，能看到投票情况，能投票。自己评论时显示评论成功，但是刷新后没有自己的评论，退出重进也没有，隔一天再看也没有。已经持续多个版本

**Comment by 1acte** [comment]
跟你遇到一样的问题，也是持续多个版本。然后一开始还能给评论点赞，但评论完然后刷新一下在同一个本里就连给评论点赞都做不到了。

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
研究了下，是e站的问题，评论了之后就不让点赞啥的了

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/14abc374-7371-4e55-a0eb-a5ff737b9698)
