### ISSUE TITLE
生成.db文件会扰乱内容顺序

### ISSUE THREAD

**Issue by PegionFish** [xiaojieonly/Ehviewer_CN_SXJ#911]
版本：1.9.6.10（两边都是）
数据库条目数量：5196
问题：在设置-高级页面选择导出数据可以正常生成数据包并导入到其他设备，但导入后会发现内容顺序出现问题，部分条目被丢到最后

不知是否是由于导出数据的设备（Teclast M89，Android 7.0）只有3GB RAM导致。之前在另一台2GB RAM的平板（ASUS P00I，Android 8.0）上也有类似问题

**Comment by MrSneez** [comment]
嗯？虽然不懂这类东西，不过这会不会和已下载画廊查看过详情页后退出程序再进入，顺序也会自动跳至最后有关？

**Comment by PegionFish** [comment]
> 嗯？虽然不懂这类东西，不过这会不会和已下载画廊查看过详情页后退出程序再进入，顺序也会自动跳至最后有关？

我这边没有遇到过这个问题，比较爱莫能助，等开发者回复吧
不过猜想上应该都是数据库的问题？

**Comment by zizzdog** [comment]
实际上是因为部分刚看过的本子下载时间戳莫名变为0了，用旧版本1.9.4.9以前还是正常的，但是老版本现在用不了

**Comment by MrSneez** [comment]
> 实际上是因为部分刚看过的本子下载时间戳莫名变为0了，用旧版本1.9.4.9以前还是正常的，但是老版本现在用不了

xiaojie大佬周一关闭了问题857而且回复了，下个版本就可以修了——

**Comment by zizzdog** [comment]
> > 实际上是因为部分刚看过的本子下载时间戳莫名变为0了，用旧版本1.9.4.9以前还是正常的，但是老版本现在用不了
> 
> xiaojie大佬周一关闭了问题857而且回复了，下个版本就可以修了——

可算要要修了😭，半年我只能用以前的备份数据库不断修复丢失的时间戳，不然全跑底下去了

**Comment by MrSneez** [comment]
> > > 实际上是因为部分刚看过的本子下载时间戳莫名变为0了，用旧版本1.9.4.9以前还是正常的，但是老版本现在用不了
> > 
> > 
> > xiaojie大佬周一关闭了问题857而且回复了，下个版本就可以修了——
> 
> 可算要要修了😭，半年我只能用以前的备份数据库不断修复丢失的时间戳，不然全跑底下去了

啊呀兄啊，你不点进去看详情就没事儿啊，我现在就是这么干的
