### ISSUE TITLE
1965版本后开始无法显示封面和预览图，最新版本也没用

### ISSUE THREAD

**Issue by xialirising** [xiaojieonly/Ehviewer_CN_SXJ#916]
用的绿e，老手机了，安卓是6.0的，之前一直没问题。人在日本，无网络问题

**Comment by qianxingyuan** [comment]
我也是

**Comment by hdjsheifnjs** [comment]
同显示不出预览图，昨天还没问题的

**Comment by hdjsheifnjs** [comment]
可以试试用设置“eh”的修正缩略图链接，我是能看到封面但点进去显示不出缩络图，开了缩络图修正后就显示出来了

**Comment by xialirising** [comment]
> 可以试试用设置“eh”的修正缩略图链接，我是能看到封面但点进去显示不出缩络图，开了缩络图修正后就显示出来了
对我没有用，之前设置里的东西基本都试过了，不知道是安卓版本太老还是是ip关系

**Comment by xialirising** [comment]
有点不太行，之前设置里面都摸过了，现在这个样子确实很烦。不知道是我安卓版本太老还是ip原因

**Comment by xiaojieonly** [comment]
手机太老了，去中古店换个安卓9及以上的吧？
现在有wifi迁移功能，数据迁移还是比较方便的，唯一需要手动操作的就是把下载内容按路径拷贝到新手机

**Comment by xiaojieonly** [comment]
或者等新版本在看看
