### ISSUE TITLE
小米10至尊可以登陆无法连接，解析超时，收藏无法查看，账户无问题，疑似eh全家桶与系统不兼容，彩e可以登陆查看无法浏览收藏

### ISSUE THREAD

**Issue by 3blue34** [xiaojieonly/Ehviewer_CN_SXJ#917]
![camphoto_1118121244](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/07c01eba-3d13-45ce-a3fa-8333684ae830)

![camphoto_440155785](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/d42f28d8-903b-4b40-a5e7-13dd01642059)

![camphoto_1543968957](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/ceeb6c15-94ba-4804-8004-aaa04b1f5102)

![camphoto_387551585](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/af3ec39b-6a88-45cc-a785-cfa71dfe35c0)
![camphoto_838832689](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/0b28d62c-a6fc-4237-98ca-e5875a10c4bc)
[
![camphoto_761355704](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/152461826/b5440c3e-6a67-453e-b86d-8bc84f69b9ed)
](url)

**Comment by Gon-Emiya** [comment]
你可以试下这个，我试了ok。
https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/666

**Comment by xiaojieonly** [comment]
看看楼上，你这情况如果是自己挂了梯子的话一般都是梯子用的人太多导致的
