### ISSUE TITLE
下载好的老画廊在点击页面详情的“更新”后，有概率会出现打开时依然需要重新下载的情况

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#919]
举例来说，一个画廊是今日上传的，然后上传者因为校正错字等缘故后来上传了新版本，这时下载了旧版本画廊的用户就可以通过详情页的【更新】解决问题了。
但这个【更新】有概率出问题。
按理说可以通过【更新】完成画廊文件的更替，但实际上点了【更新】后，即便更新完毕的本地画廊显示【已完成】，但点进去后会发现图片文件还是在“转圈”（也就是重新下载）。
这样的问题出现了不止一次，而且点【更新】后，有可能当时还能看，但在关闭应用后再打开就需要重新加载图片文件了。
第更新需要配额，这个重新下载过程也吃配额，相当于一个画廊的更新部分需要吃两次配额，有点哈人呢，这算bug吗🙏🏻

**Comment by sdo9004** [comment]
我点更新直接提示我是否删除不知道到底要怎么更新

**Comment by p12313461** [comment]
還有畫廊如果是從前面開始更新圖集的話，後面的圖有機會卡死在舊圖不更新，點舊圖刷新的話會直接跳錯誤訊息然後連舊圖都不見了，只能刪掉eh重裝才能好

**Comment by xiaojieonly** [comment]
这个问题最新版修了，然后更新功能在下一版做了些扩展，到时候可以试试还有问题没
