### ISSUE TITLE
1.7.9.2

### ISSUE THREAD

**Issue by BXsaikou** [xiaojieonly/Ehviewer_CN_SXJ#92]
安卓10，能登陆账号，能浏览，能搜索，但不能打开大图，下载也是0

**Comment by qqqnnnqn** [comment]
我还是无法登录EXHANTAI 只能打开EHANTAI 而且只能看略缩图，点开就转圈，下载也下载不了

**Comment by xiaojieonly** [comment]
解决方法已经放出来了
