### ISSUE TITLE
红米k70不允许媒体扫描失效了

### ISSUE THREAD

**Issue by Athurpalago** [xiaojieonly/Ehviewer_CN_SXJ#920]
从k30u转移到k70之后选择不允许媒体扫描失效了

**Comment by CN4MaccAfee** [comment]
> 从k30u转移到k70之后选择不允许媒体扫描失效了


在download文件夹里自制添加一个.nomedia文件，系统就不会扫描了
最简单的自制方法，新建一个.txt文件，去掉文件名只保留后缀名，然后把后缀名改成.nomedia

**Comment by Athurpalago** [comment]
K70不许空白文件名😭

**Comment by xiaojieonly** [comment]
> K70不许空白文件名😭

重启手机试试？代码逻辑上没啥问题，系统堵路我属实是胳膊拧不过大腿
