### ISSUE TITLE
多版本出现配额翻倍情况

### ISSUE THREAD

**Issue by FengTeLai** [xiaojieonly/Ehviewer_CN_SXJ#923]
华为鸿蒙4，电信网
V1.9.6.9和1.9.7.0直连观看或待机时都出现Image Limits翻几倍的情况，我没开下载原图，依然消耗巨大
想问下下载线程数和预载图片是怎么计算的，什么图都没看，就涨40，一本18页的画廊直接消耗240
开VPN的时候配额属于正常消耗，一但直连，立马翻倍，这是为什么？

**Comment by xiaojieonly** [comment]
e站问题，我除了原图下载改了下啥都没动
