### ISSUE TITLE
个人碰到的问题汇总（缩略图，阅读类）

### ISSUE THREAD

**Issue by FengTeLai** [xiaojieonly/Ehviewer_CN_SXJ#925]
1.9.7.0无法像老版本在主界面用鼠标滚轴上下滑动翻页。
未开下载原图，浏览画廊内容，有时会出现配额消耗翻倍
E表站能正常直连，进里站时经常超时，主界面缩略图也是表站时能显示，里站不显示，开启“修正缩略图链接”时有些画廊能看到所有内容，有些缩略图依然图裂。
最后，能否添加画廊阅读时的鼠标滚轮翻页功能。

**Comment by xiaojieonly** [comment]
哈，哦，我大概知道了，下一版我把鼠标上下滑动的加回去
