### ISSUE TITLE
逆水行舟，不进则退。

### ISSUE THREAD

**Issue by chikao2024** [xiaojieonly/Ehviewer_CN_SXJ#926]
随着其他版本客户端都陆续解决了原图下载问题，唯独绿E的原图下载问题始终无法解决。。。真是希望越大，失望越大。😞 正所谓逆水行舟，不进则退，如今的绿E已经是最差之E了，虽然难过，但也只能跟用了近两年之久的绿E告别了。。。😞
😞😞😞😞😞😞😞😞😞😞😞
![IMG_20231205_131525](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/141544713/fd25cf2c-a8ad-4507-81ab-aee0b4377053)

**Comment by UjuiUjuMandan** [comment]
用爱发电的项目有什么好期待的呢？

作者是和你签协议必须要实现你的要求吗？

**Comment by chikao2024** [comment]
> 用爱发电的项目有什么好期待的呢？
> 
> 作者是和你签协议必须要实现你的要求吗？

绿E有捐赠的，我为绿E捐赠过所以才会哀其不幸，怒其不争，否则也不会有什么期待了。您的彩E是现在最强的，而且还没有捐赠，您才是真正的为爱发电。

**Comment by chikao2024** [comment]
为什么绿E提Issue的那么多？就是因为绿E是有捐赠的，不少提Issue的人都是给绿E捐赠过，所以才会对其有那么大的期待。绿E一直以来都有下载画廊乱序Bug也一直未解决，这已经忍了，很多Bug一旦不尽早解决，将来可能会越发难以解决，造成某种问题会一直存在。如今绿E的原图下载问题，已致部分汉化组通过绿E下载的画廊穿插了一些非原图，后续制作出来的汉化作品的质量也因此下降，所以绿E只要一天不修复这个Bug，所造成的影响就会一直延续下去。。。。。。

**Comment by UjuiUjuMandan** [comment]
> 如今绿E的原图下载问题，已致部分汉化组通过绿E下载的画廊穿插了一些非原图，后续制作出来的汉化作品的质量也因此下降，所以绿E只要一天不修复这个Bug，所造成的影响就会一直延续下去。。。。。。

什么汉化组不用种子和归档下载，去用手机应用下载原始文件？手机跑不了 Photoshop 吧。

你的这个结论，大概率是错的，因为你应该没有用 EhViewer 以外的下载方式验证是否是原图。

[白 E 的 Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 里面说过了：

*高频下载可能导致该选项被重置为 Auto，请自行减少并发下载数 / 增加下载延时 ( https://github.com/FooIbar/EhViewer/issues/137#issuecomment-1805579676 )*。

**Comment by chikao2024** [comment]
> > 如今绿E的原图下载问题，已致部分汉化组通过绿E下载的画廊穿插了一些非原图，后续制作出来的汉化作品的质量也因此下降，所以绿E只要一天不修复这个Bug，所造成的影响就会一直延续下去。。。。。。
> 
> 什么汉化组不用种子和归档下载，去用手机应用下载原始文件？手机跑不了 Photoshop 吧。
> 
> 你的这个结论，大概率是错的，因为你应该没有用 EhViewer 以外的下载方式验证是否是原图。
> 
> [白 E 的 Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 里面说过了：
> 
> _高频下载可能导致该选项被重置为 Auto，请自行减少并发下载数 / 增加下载延时 ( [FooIbar/EhViewer#137 (comment)](https://github.com/FooIbar/EhViewer/issues/137#issuecomment-1805579676) )_。

目前就您的下游版彩E是最稳定的，下载的都是原图，同时也在评论中提醒过了一些汉化组注意暂时不要用绿E下载原图，可用新版彩E或归档下载原图。

**Comment by UjuiUjuMandan** [comment]
> 同时也在评论中提醒过了一些汉化组注意暂时不要用绿E下载原图，可用新版彩E或归档下载原图。

你觉得汉化组直接电脑网页下载归档或者种子方便，还是用手机应用下载一次再传到电脑上汉化方便？

真有这种汉化组？麻烦把画廊链接发上来。

**Comment by chikao2024** [comment]
> > 同时也在评论中提醒过了一些汉化组注意暂时不要用绿E下载原图，可用新版彩E或归档下载原图。
> 
> 你觉得汉化组直接电脑网页下载归档或者种子方便，还是用手机应用下载一次再传到电脑上汉化方便？
> 
> 真有这种汉化组？麻烦把画廊链接发上来。

https://exhentai.org/g/2728325/a7fa0e344c/

原本汉化页中就有1280P的非原图，然后种子文件又是通过绿E下载的，造成种子文件更小了，里面又出现了更多的非原图。

**Comment by UjuiUjuMandan** [comment]
好吧，尽管难以置信，但是我确认了归档内的文件，确实如你所说。
