### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by idkcckdk** [xiaojieonly/Ehviewer_CN_SXJ#928]
在阅读漫画的时候可以增加条漫观看吗?因为观看韩漫的时候这个观看模式特别需要。

**Comment by xiaojieonly** [comment]
阅读设置里有，你可以找找

**Comment by idkcckdk** [comment]
没有只有上下

SXJ_LonelyDog ***@***.***> 于 2023年12月11日周一 16:13写道：
