### ISSUE TITLE
不能完整的下载完一个本子，总是下载几页后就转头下载其他本子了

### ISSUE THREAD

**Issue by TAjimu-veda** [xiaojieonly/Ehviewer_CN_SXJ#929]
![IMG_20231208_041406.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/64314685/2a1086d2-8bc7-4ea1-be0b-f914dfdcb788)

![IMG_20231208_041417.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/64314685/25b11c99-024b-45ba-a5b2-014a3cff21ae)

上一个版本就有这个问题现在更新了1.9.7.0一人存在此问题，希望作者大大看到能解决.

**Comment by xiaojieonly** [comment]
网络问题
