### ISSUE TITLE
下载的画廊只要阅读后还是会到底层

### ISSUE THREAD

**Issue by BreakFaith01** [xiaojieonly/Ehviewer_CN_SXJ#930]
经历了几个版本这个bug还是没好，还是说我得删除一下软件，亦或是说还没修好。
按创建时间降序也没用，被移动到底下的还是在底下。
就是如果重装软件可能会牺牲一下被删掉的画廊。

**Comment by xiaojieonly** [comment]
我复现不出啦啊，我也很绝望啊

**Comment by sjdbsbsb** [comment]
要不试试重构排序逻辑，放弃按ID或下载时间排序，直接支撑自由排序并锁定（就像主页左滑搜索标签一样）

**Comment by sjdbsbsb** [comment]
> 我复现不出啦啊，我也很绝望啊

可能是画廊“创建时间”的问题。我新下载的画廊A默认排序掉最底下了。选择创建时间升序，画廊A排第一行。选择创建时间降序，画廊A排在列表中间左右。这感觉不太合逻辑。

**Comment by xiaojieonly** [comment]
修好了，下一版跟新
