### ISSUE TITLE
恢复下载项无法识别已下载的内容，可能跟下载时不生成.ehviewer文件有关

### ISSUE THREAD

**Issue by openipka** [xiaojieonly/Ehviewer_CN_SXJ#931]
之前一两年通过绿E下载的本子，无法通过拖到原路径下再恢复下载项来在边栏-下载分类里恢复条目。

**我测试以后的结论是**：绿E下载的本子没有.ehviewer文件，导致无法识别；白E和彩E下载的均有.ehviewer文件，因此可以识别；
                                     以及绿E可以识别白E的下载文件，白E只能识别白E的下载文件，彩E可以识别白E和彩E的下载文件；

**以下是试验流程**：
1.下载的文件夹拖到Ehviewer/Downloads里，恢复下载项，失败；
2.新下载一个本子，确保新旧文件夹在同一个目录下，恢复下载项，失败；
3.把新下载的本子条目删除，但不删除图片文件，恢复下载项，失败；
4.用白E、彩E把设置内的目录重定向到跟绿E一致的目录，分别测试能否恢复下载项，均失败；
5.用白E新下载一个本子，发现存在.ehviewer文件，重复3，成功；
6.用彩E直接恢复下载项，成功；
7.此时用绿E再恢复下载项，成功；
8.用彩E下载一个本子，发现存在.ehviewer文件，使用绿E进行恢复下载项，失败；
9.用白E对彩E下载的本子恢复下载项，失败；
10.得出结论（我猜测可能是彩E的.ehviewer文件和白E的.ehviewer文件类似于新旧版，所以不能共通）
11.补充测试：用彩E先下一个本子，此时白E和绿E均不能恢复；然后用白E下同一个本子，注意到只有.ehviewer文件被修改；此时白E、彩E、绿E均可以恢复这个本子。

**我的想法是**：尽管可以通过高级选项里的导入导出数据来保存下载列表，但是这会让恢复下载项这一项毫无用武之地、并且初次使用之前并不知悉这点，容易“初见杀”造成麻烦。 还是应当把.ehviewer文件正常生成；至于.ehviewer文件能不能在各流通版本之间互通，我觉得理论上是应该可以的，但实际上可能因为平台和架构不同所以不考虑也可以。

**Comment by YuuhiCho** [comment]
同求绿e添加这个功能，因为需要用LANraragi的插件进行刮削，用到了.ehviewer文件

**Comment by xiaojieonly** [comment]
额

**Comment by zizzdog** [comment]
> 同求绿e添加这个功能，因为需要用LANraragi的插件进行刮削，用到了.ehviewer文件

你说的插件应该是我写的😂，不建议使用那个插件了，因为Lan作者可以直接搜索文件名里的Gid找到源画廊了，不过中文翻译的作者没更新，你可以下载这个压缩包，将解压出来的文件手动导入Lan插件库。
[EHentai.zip](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/13680681/EHentai.zip)

这个插件修改自原作者最新的Ehentai插件，区别在于源插件是搜索中括号[]内的数字作为gid，而ehviewer下载的文件名是纯数字开头，所以我修改了一下第147行以适配ehviewer下载的文件。导入插件，勾选Search using gID from title (falls back to title)即可。

**Comment by YuuhiCho** [comment]
> > 同求绿e添加这个功能，因为需要用LANraragi的插件进行刮削，用到了.ehviewer文件
> 
> 你说的插件应该是我写的😂，不建议使用那个插件了，因为Lan作者可以直接搜索文件名里的Gid找到源画廊了，不过中文翻译的作者没更新，你可以下载这个压缩包，将解压出来的文件手动导入Lan插件库。 [EHentai.zip](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/files/13680681/EHentai.zip)
> 
> 这个插件修改自原作者最新的Ehentai插件，区别在于源插件是搜索中括号[]内的数字作为gid，而ehviewer下载的文件名是纯数字开头，所以我修改了一下第147行以适配ehviewer下载的文件。导入插件，勾选Search using gID from title (falls back to title)即可。

膜拜，感谢大佬😭🙏
