### ISSUE TITLE
下载原图时显示targetlmageurl error

### ISSUE THREAD

**Issue by blankhand2020** [xiaojieonly/Ehviewer_CN_SXJ#934]
选择下载原图浏览过一些图片后会显示targetlmageurl error，取消下载原图后可以正常加载图片但勾回选项还是会再度显示，无法通过更换梯子节点来解决

**Comment by xiaojieonly** [comment]
那个画廊？

**Comment by blankhand2020** [comment]
> 那个画廊？

ex

**Comment by blankhand2020** [comment]
![Screenshot_2023-12-12-11-37-23-310_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/119048158/78cdc277-a800-4275-99ee-c6ece5f3014d)

**Comment by SakuraKongShi** [comment]
遇到了同样的问题，取消下载原图就正常了

**Comment by xiaojieonly** [comment]
我问的是画廊名称或者画廊链接，请不要给我站点

**Comment by blankhand2020** [comment]
> 我问的是画廊名称或者画廊链接，请不要给我站点
最近出现过这种情况的：

https://exhentai.org/g/2286672/b95bee3b23/
https://exhentai.org/g/2061089/8860dfe7e2/

**Comment by blankhand2020** [comment]
> 我问的是画廊名称或者画廊链接，请不要给我站点

最近一次出现这种情况的

**Comment by XiangRiKui-YYYHE** [comment]
我也是這種情況，大概三個月以前的畫廊，開原圖就會這樣

**Comment by blankhand2020** [comment]
版本更新后还是有这样的情况出现，依然无法用更换梯子节点的方法解决
最近出现问题的画廊：https://exhentai.org/g/2394025/bbe73a0324/
![Screenshot_2023-12-21-09-32-05-152_com xjs ehviewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/119048158/f8a65868-3e32-4335-8156-cefadc6697c1)

**Comment by xiaojieonly** [comment]
1

**Comment by XiangRiKui-YYYHE** [comment]
这是什么原因引起的，有办法修复吗

**Comment by xiaojieonly** [comment]
可能是配额用完导致的？你配额多吗？

**Comment by XiangRiKui-YYYHE** [comment]
配额是够的，近期的原图啥的都能看，时间久一点的就看不了

**Comment by XiangRiKui-YYYHE** [comment]
https://exhentai.org/g/1580595/8886c6a520/
像这种的我就加载不出来，不清楚是账号的问题还是哪里的问题

**Comment by XiangRiKui-YYYHE** [comment]
我懂了，是e站货币的问题。没货币就会这样

**Comment by ZhangQingsen** [comment]
我个人感觉是勾选下载原图导致的，好像之前E站改了什么导致下载原图只能下载最近一个月的画廊的。
by the way, 我现在下载以前的画廊原图都是(使用连点器)不停地开始暂停，每次下载一页就可以下载，当然太多会说我excessive page load。不知道这个流程是否可以自动化。

**Comment by XiangRiKui-YYYHE** [comment]
> 我个人感觉是勾选下载原图导致的，好像之前E站改了什么导致下载原图只能下载最近一个月的画廊的。 by the way, 我现在下载以前的画廊原图都是(使用连点器)不停地开始暂停，每次下载一页就可以下载，当然太多会说我excessive page load。不知道这个流程是否可以自动化。

你看一下你e站的货币多不多
