### ISSUE TITLE
特定畫廊出現錯誤

### ISSUE THREAD

**Issue by HENREX** [xiaojieonly/Ehviewer_CN_SXJ#936]
只有在這個畫廊有這個問題
[https://exhentai.org/g/2762702/89ff5e6063/](url)
縮圖留言標籤全都能正常加載，但點進去閱讀永遠都是error
已多次清理快取及轉換站點

**Comment by xiaojieonly** [comment]
重启下手机试试，我手机上能正常看

**Comment by xiaojieonly** [comment]
然后清理下app缓存
