### ISSUE TITLE
找不到已经下载的图

### ISSUE THREAD

**Issue by Raiter123** [xiaojieonly/Ehviewer_CN_SXJ#937]
有时候会发现有些已经下载的画廊在下载的页面上找不到的，请问这正常的吗

**Comment by YamiOdymel** [comment]
確實，好像被新的蓋過去了，但數量看起來是正常的

**Comment by xiaojieonly** [comment]
画廊排序有问题，你可以滑到画廊底部看看在不在那。
不过这个问题已经修好了，下一版更新
