### ISSUE TITLE
一直在访问我的剪切板是为啥？

### ISSUE THREAD

**Issue by sceic** [xiaojieonly/Ehviewer_CN_SXJ#939]
![Screenshot_2023-12-13-16-23-00-66_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/28992714/759ba578-39ac-4402-9df5-84ed252e6b32)

**Comment by UjuiUjuMandan** [comment]
不访问剪贴板怎么识别里面有没有画廊链接啊。

**Comment by UjuiUjuMandan** [comment]
你这个是什么 ROM ？

**Comment by xiaojieonly** [comment]
不放心的话可以卸载app
然后二楼正解
