### ISSUE TITLE
加载不出详情图

### ISSUE THREAD

**Issue by cqvq** [xiaojieonly/Ehviewer_CN_SXJ#940]
封面图跟预览图能加载（不稳定，偶尔能，偶尔不能），详情内容图就已经好久都加载不出来了，上个版本不行，最新版本也不行，好像是自从哪一天开始就不能加载出来了，一直在转圈圈

**Comment by xiaojieonly** [comment]
裸连的的话安全dns关了试试，挂了梯子就把高级里网络相关选项都关了，还不行的话请重新打开issue
