### ISSUE TITLE
手机更新后无法联网

### ISSUE THREAD

**Issue by dwwcc** [xiaojieonly/Ehviewer_CN_SXJ#941]
三星手机在更新one ui 6.0后无法进入exh观看，没挂梯子显示网络错误，挂了梯子就显示个安卓头

**Comment by xiaojieonly** [comment]
。。。。我没有三星手机

**Comment by dwwcc** [comment]
> 。。。。我没有三星手机

我知道了，应该是版本问题，更新后直接升级到安卓14了
