### ISSUE TITLE
APP直连的情况下无法阅读和下载。能看列表和简介

### ISSUE THREAD

**Issue by liveviiv** [xiaojieonly/Ehviewer_CN_SXJ#945]
可以看列表，简介页面， 小预览图，
点阅读进去在转圈圈 无法加载 也无法下载。
之前一直可以直接直连观看和下载。
请问有什么解决方法吗?
挂代理 需要关闭 安全DNS 这个开关才能观看和下载。

**Comment by xiaojieonly** [comment]
直连关闭安全dns
