### ISSUE TITLE
首次打开详情页会卡死

### ISSUE THREAD

**Issue by KyaruSAMA** [xiaojieonly/Ehviewer_CN_SXJ#947]
自1.9.6.8版本起出现，希望能够解决

**Comment by xiaojieonly** [comment]
复现不出来

**Comment by KyaruSAMA** [comment]
> 复现不出来

使用外置sd卡作为存储路径，当下载路径文件夹中已下载大量下载本子时首次打开详情页会卡，卡顿时间为10s-2min不等。
![Screenshot_20231218_172547_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48395254/eab7e732-495a-4068-b852-8b9173594d24)

**Comment by KyaruSAMA** [comment]
> 复现不出来

之前的版本只有下载新本子时才会卡住，从1.9.6.8开始点进第一次点击的详情页也会卡

**Comment by xiaojieonly** [comment]
额

**Comment by xiaojieonly** [comment]
现在应该好了吧？如果还有问题可以重新打开这个issue
