### ISSUE TITLE
[Feature]希望增加通过外置下载器更新eh功能

### ISSUE THREAD

**Issue by 1078249029** [xiaojieonly/Ehviewer_CN_SXJ#951]
希望能够用外置下载器，如idm，进行软件更新，这样能够方便对下载文件进行管理，我这里使用内置下载器下载完成后不能安装。
希望开发者能添加这个新功能。

**Comment by xiaojieonly** [comment]
你都能找到github了，可以直接github上下呀？

**Comment by 1078249029** [comment]
> 你都能找到github了，可以直接github上下呀？

只是单纯的懒癌犯了 /(ㄒoㄒ)/~~
所以只是希望能够加这个Feature
