### ISSUE TITLE
希望增加显示Gp余额功能

### ISSUE THREAD

**Issue by Tommy12pl** [xiaojieonly/Ehviewer_CN_SXJ#952]
如题，在目前的显示配额功能中有使用Gp重置配额的选项，但无法查看Gp余额且重置操作无二次确认，容易导致误操作，希望开发者能增加显示余额的功能（实在不行在设置里加个跳转网站的入口也行球球了）

**Comment by xiaojieonly** [comment]
刷新按钮按一下不就看得到了

**Comment by mo-han** [comment]
现在一直是0/0，刷新了也是0/0，点开来可以看到获取到的GP的明细，但是余额全部是0
