### ISSUE TITLE
跳转画廊新版本时闪退

### ISSUE THREAD

**Issue by Steve-337** [xiaojieonly/Ehviewer_CN_SXJ#953]
https://e-hentai.org/g/2769341/21710e9278/ 点击跳转到新版本后闪退
![Screenshot_2023-12-20-13-56-33-435_com.fankes.apperrorstracking.jpg](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/48684035/bca03c35-754c-4b04-8d45-c278470208ac)

**Comment by xiaojieonly** [comment]
1

**Comment by xiaojieonly** [comment]
已修，下一版更新
