### ISSUE TITLE
最新版还是没预览

### ISSUE THREAD

**Issue by Achievement42** [xiaojieonly/Ehviewer_CN_SXJ#954]
![01CFCF784C227A75AC56BD07606F7F3B](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/954be847-0023-4109-b8fb-027c01f84b94)
![D517882F7650E70F95942F302FB0D24B](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/59813216-c66d-4926-b1fd-dd96c0818cd8)
![DDC6C2BA42F0B3A518090E752D95E51C](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/e307be67-7ec7-4049-bc66-20adc1e07168)
![D3D5DD938FF601D4F30DA86DCC4277E1](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/a9e53d39-35fa-439e-aa75-01ed7a620393)
![7BA35F9571C4CF9A0D2B8DA404CEC82B](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/5bd3bef0-af52-4e87-ba71-e395eba35839)
![7257B99EA902C235372D635806E5B716](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/b0190042-08be-4ac0-971e-f5f80c022143)
![6692B88649CB953528947D1C8A315304](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/58147888/4672850e-b519-4b53-b942-e2e6696e8ef7)
去连别人家的网，换梯子什么的都试过了，是不是机型太老了啊

**Comment by xiaojieonly** [comment]
打开host然后关了修正略缩图链接，再试试

**Comment by Achievement42** [comment]
> 打开host然后关了修正略缩图链接，再试试

还是不行，还有就是点进大图之后的那个加载圈圈都不显示了，直接是黑屏加载几秒直接出图片
