### ISSUE TITLE
是否能添加一个选项，允许保存下载文件时仅使用 GID 作为文件夹名称？

### ISSUE THREAD

**Issue by buzzers** [xiaojieonly/Ehviewer_CN_SXJ#958]
如题。
因为我使用 Resilio Sync 在多台机器间同步下载数据，而本子的名字里进场带有特殊符号等导致同步时 Sync 修改文件名导致导入后不认，甚至干脆就静默失败丢失下载数据。所以希望能使用纯数字的 GID 作为目录名。如此在全平台系统上都能正常同步数据。

**Comment by xiaojieonly** [comment]
工作量太大了

**Comment by buzzers** [comment]
> 工作量太大了

如果我提交 PR 可以合并么？
