### ISSUE TITLE
没有启动下载原图，但观察配额消耗量是下载了原图[版本1.9.7.1]

### ISSUE THREAD

**Issue by godoway** [xiaojieonly/Ehviewer_CN_SXJ#967]
如题，并没有在配置中启用下载原图，但每张图片的消耗都是好几十。
自己使用网页是正常的消耗1

**Comment by xiaojieonly** [comment]
是裸连的吗？裸连网不好会导致重复请求消耗多余配额，，挂了梯子的，可能是别人也在用

**Comment by godoway** [comment]
> 是裸连的吗？裸连网不好会导致重复请求消耗多余配额，，挂了梯子的，可能是别人也在用

挂代理的。然后是铜星，配额跟账号走不跟IP走。
使用网页访问是每张图消耗1，使用客户端是按了图片大小消耗

**Comment by imkare** [comment]
我是裸连的，只是我是从绿e转过来看看的。我把绿e下载的项目复制到了白e的下载文件夹里。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月02日 18:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [xiaojieonly/Ehviewer_CN_SXJ] 没有启动下载原图，但观察配额消耗量是下载了原图[版本1.9.7.1] (Issue #967) |

是裸连的吗？裸连网不好会导致重复请求消耗多余配额，，挂了梯子的，可能是别人也在用

挂代理的。然后是铜星，配额跟账号走不跟IP走。
使用网页访问是每张图消耗1，使用客户端是按了图片大小消耗
