### ISSUE TITLE
请求新功能 能直接在下载标签页面修改标签标题，不用点右上角的三个点慢慢找

### ISSUE THREAD

**Issue by DidyouseetheSunrise** [xiaojieonly/Ehviewer_CN_SXJ#973]
![Screenshot_20240101_043327_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/81443964/82fd1233-c524-4374-9d5f-dfffb12e3b66)
每次内容变动后想要修改标题得慢慢找太难受了，请求添加能直接在界面里修改标签名称标题功能

**Comment by xiaojieonly** [comment]
以后再说
