### ISSUE TITLE
绿E设置头像从相册里选择无效

### ISSUE THREAD

**Issue by chikao2024** [xiaojieonly/Ehviewer_CN_SXJ#974]
如题，从相册中选择无效，只能通过拍照。此外生成的avatar_image.jpg文件由于在Cache文件夹内，只要手机清理下垃圾后头像文件就被删除，头像也就不显示了，希望能够对比进行优化。

**Comment by xiaojieonly** [comment]
只能拍照大概率是因为没给读取相册的权限，后者，建议清理垃圾别清理Ehviewer的数据，现在很难找到一个只有十几二十M的app软件了

**Comment by chikao2024** [comment]
> 只能拍照大概率是因为没给读取相册的权限，后者，建议清理垃圾别清理Ehviewer的数据，现在很难找到一个只有十几二十M的app软件了

绿E的相册给了，依然从相册选取头像无效。
此外建议将avatar_image.jpg文件路径设置在com.xjs.ehviewer\files下而不在com.xjs.ehviewer\cache下，这样手机清理垃圾就不会删掉头像文件了。

**Comment by chikao2024** [comment]
此外，感觉安卓13系统因限制原因，很多App都无法从Android\data\里的文件夹里选择图片作为头像使用。要么就直接把头像文件设置在主目录的Ehviewer文件夹里，再多建一个不含Cache或temp名字的文件夹里，这样应该能解决头像从相册选择和被垃圾清理掉的问题。
