### ISSUE TITLE
收藏时无法选择文件夹

### ISSUE THREAD

**Issue by Changcta** [xiaojieonly/Ehviewer_CN_SXJ#975]
点击收藏时会直接保存到默认收藏夹，不会弹出选择收藏夹。
1.9.7.1发现的，1.9.7.2依然存在。
是网站bug还是app的bug？

**Comment by xiaojieonly** [comment]
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/49278135/dd778b08-9aa8-4a69-bb87-0b77a37c3edd)
