### ISSUE TITLE
有些图片死活都加载不出来，但是彩e却能加载

### ISSUE THREAD

**Issue by Plainct** [xiaojieonly/Ehviewer_CN_SXJ#976]
https://e-hentai.org/g/2715250/6fe027d21c/
比如这个本的第一张图片，等一分钟也不行，就算点刷新下载条读完还是打不开转圈圈，
换成彩e就十几秒。
貌似是祖传bug了，不管哪个版本的绿e都是这个问题

**Comment by chikao2024** [comment]
试了下绿E可以正常打开，是自身问题，缓存不会清。

**Comment by xiaojieonly** [comment]
谢谢二楼
