### ISSUE TITLE
直连后能加载封面但是进画廊加载不了图片

### ISSUE THREAD

**Issue by seelesern** [xiaojieonly/Ehviewer_CN_SXJ#982]
很奇怪，之前一直能够直连的，是出了什么问题么？![QQ图片20240106145520](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/116353684/74a94386-d257-4fd0-853d-addabe82e1ca)
![QQ图片20240106145440](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/116353684/05dae7d2-c285-44f0-bb03-097bc89a6675)

**Comment by xikari765** [comment]
不是你一个人这样，放心吧，不是你的问题，等更新吧，目前我的解决方法是下载，然后等他进入下载任务栏之后，再打开梯子，没有办法在线观看了，因为他直接打开梯子会被ban ip

**Comment by kuhdrd** [comment]
> 不是你一个人这样，放心吧，不是你的问题，等更新吧，目前我的解决方法是下载，然后等他进入下载任务栏之后，再打开梯子，没有办法在线观看了，因为他直接打开梯子会被ban ip

我也是这样，但我的配额还会飞速消耗，即使我的下载进度一直为0，他还是在迅速消耗

**Comment by ADsunshine** [comment]
> 不是你一个人这样，放心吧，不是你的问题，等更新吧，目前我的解决方法是下载，然后等他进入下载任务栏之后，再打开梯子，没有办法在线观看了，因为他直接打开梯子会被ban ip

我也是这样，而且我换白e登录之后仍然无法加载图片……

**Comment by ADsunshine** [comment]
> > 不是你一个人这样，放心吧，不是你的问题，等更新吧，目前我的解决方法是下载，然后等他进入下载任务栏之后，再打开梯子，没有办法在线观看了，因为他直接打开梯子会被ban ip
> 
> 我也是这样，但我的配额还会飞速消耗，即使我的下载进度一直为0，他还是在迅速消耗

已经找到解决办法了，这个是江苏等地区的IP劫持，最简单的解决方法就是换一个IP地址

**Comment by xikari765** [comment]
> > > 不是你一个人这样，放心吧，不是你的问题，等更新吧，目前我的解决方法是下载，然后等他进入下载任务栏之后，再打开梯子，没有办法在线观看了，因为他直接打开梯子会被ban ip
> > 
> > 
> > 我也是这样，但我的配额还会飞速消耗，即使我的下载进度一直为0，他还是在迅速消耗
> 
> 已经找到解决办法了，这个是江苏等地区的IP劫持，最简单的解决方法就是换一个IP地址

所以是怎么换的？

**Comment by xiaojieonly** [comment]
安全dns关了试试

**Comment by UjuiUjuMandan** [comment]
应该是开了试试罢，当然得等下一个版本发布之后。

但是看起来江苏的劫持行为已经停止了，这个问题应该不存在了。

**Comment by xiaojieonly** [comment]
等下一版吧，没几天了
