### ISSUE TITLE
正文无法观看也无法下载，但预览图和封面都可以很迅速的加载出来，并且即使无法下载，我的配额也在迅速消失

### ISSUE THREAD

**Issue by kuhdrd** [xiaojieonly/Ehviewer_CN_SXJ#983]
现在是2023/1/6，我的DoH是默认关闭的，使用各种方法都无法浏览图片和下载，但预览图和封面都可以很迅速的加载出来，并且即使无法下载，我的配额也在迅速消失，5分钟不到就要消耗我5000多，即使我连1页都没有下载，这还是我在直连情况下遇到的

**Comment by xiaojieonly** [comment]
等下一版或者先安装旧版
