### ISSUE TITLE
关于下载的画质问题

### ISSUE THREAD

**Issue by Fangliding** [xiaojieonly/Ehviewer_CN_SXJ#991]
下载设置里那个下载原图 我猜应该是调用的那个 Download original 吧 这样会导致gp和credit流失(见 #901 )
但是如果在 hath perk 里买了 Source Nexus 会在setting里解锁一个选项  Prefer original images 这会允许在普通画廊中直接加载 original 图像(只要新本子单页不超10MB 一年历史的旧本子单页不超过4MB) 就不会有上述问题也可以下载原档图像了 问题是设置的download选项似乎会覆盖eh网页设置使得这种玩法不可能
再开一个开关太抽象而且不好控制 我个人建议是删掉下载里的图片分辨率 然后全部按 设置 EH Ehentai 里设定的分辨率和其他偏好进行下载
![image](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/45535409/c2c82744-8c66-4cc0-a9cf-a098b150aaee)

**Comment by xiaojieonly** [comment]
1

**Comment by Fangliding** [comment]
触发那个机制要选auto画质 好吧 这样也能用
