### ISSUE TITLE
app里igneous变成mystery，网页版查看cookie找不到igneous字段，EditThisCookie也查不到

### ISSUE THREAD

**Issue by glacieran** [xiaojieonly/Ehviewer_CN_SXJ#995]
app里站是sad panda的状态，网页版里站登不进去，查igneous字段也查不出来，按照现有的教程没办法操作
![QQ截图20240114115629](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/78967952/3da7b1b3-06c7-4943-8578-cee30da51f6a)
![QQ截图20240114115651](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/78967952/1a2c2395-05d9-4bd9-9afd-13888922272c)

**Comment by xiaojieonly** [comment]
https://nicebowl.fun/11
