### ISSUE TITLE
关于旧画廊更新与画廊下载的问题

### ISSUE THREAD

**Issue by suweiai1314** [xiaojieonly/Ehviewer_CN_SXJ#996]
在下载好的旧画廊的详情页面点击更新后，关闭APP并重启，打开状态显示“已完成”的已更新的新画廊时，内容却还需要下载，此时再去下载，它就从0开始了。
如果更新时开启了VPN，关闭APP再打开查看时没有开启，那这个bug的触发率很高。
把旧画廊删除，直接下载新画廊的话，VPN开不开都不影响下载进度和内容阅览。

除此之外，使用移动网络进行画廊下载时，它经常是在最后一个本子的最后一页停住，下载速度直接变成0的那种，往往需要切换网络来完成最后一页的下载。

**Comment by xiaojieonly** [comment]
网不好，正常
