### ISSUE TITLE
关于下载画廊的搜寻问题

### ISSUE THREAD

**Issue by Nightmare1996** [xiaojieonly/Ehviewer_CN_SXJ#999]
如题，我对已下载作品的搜寻机制感到疑惑
以我有下载aya3d的作品为例
当我搜寻AYA3D时，会显示190个标题有AYA3D的作品，但当我搜寻artist:aya3d时，只有显示22个不在那190个内的作品。
理论上以作者找作品时，不是应该有标签的都会显示吗？
![Screenshot_20240118-160923_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/157000545/0412c5ad-8266-4521-91c5-eb3b22267a4c)
![Screenshot_20240118-160951_EhViewer](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/assets/157000545/0a776dae-4996-4236-903b-99203e865235)

**Comment by xiaojieonly** [comment]
不一定，模糊查找会检索画廊标题，标签查询则只会匹配已打上对应标签的画廊，这是正常现象

**Comment by Nightmare1996** [comment]
> 不一定，模糊查找会检索画廊标题，标签查询则只会匹配已打上对应标签的画廊，这是正常现象

**Comment by Nightmare1996** [comment]
> 不一定，模糊查找会检索画廊标题，标签查询则只会匹配已打上对应标签的画廊，这是正常现象

可是它们在eh上都有artist:aya3d的标签啊?
那如果我想找到全部已下载的他的作品，我关键字应该怎么打?
